### ISSUE TITLE
PolyhedronBufferGeometry is missing index information

### ISSUE THREAD

**Issue by elifer5000** [mrdoob/three.js#10069]
##### Description of the problem 

Other buffer geometries (such as SphereBufferGeometry) contain index information, so shouldn't all those geometries based on PolyhedronBufferGeometry have it as well?

As it is, many more vertices than needed are created (compare with the regular geometry equivalent), and the faces information is lost, which can be useful.

##### Three.js version

- [x] Dev
- [x] r82
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Not an answer, just a comment...

I always thought is was odd that the Polyhedron geometries were implemented with smooth vertex normals. I would have expected Polyhedron vertex normals would be parallel to the face normals, yielding flat shading by default.

As the Polyhedron geometries are currently implemented, shared vertices have identical normals. Users must set `material.shading = THREE.FlatShading` to achieve the faceted appearance.

If we had implemented "flat" vertex normals, then the answer to the question is indexed-geometry will not work, because the shared vertices will have different normals.

**Comment by elifer5000** [comment]
@WestLangley I think it depends on the use case. I, for example, am using the icosahedron to approximate a sphere (a fairly common case). It makes sense then to have smooth normals. But I agree that it could be different for other polyhedra (or even other uses of the icosahedron).
If you can achieve the flat look with a material parameter, wouldn't it make sense to have both options available, flat and smooth?

**Comment by Mugen87** [comment]
To be honest, i prefer geometry entities with a straightforward level of complexity and a basic set of features. As far as i remember, the subdivision code of `PolyhedronBufferGeometry` would be way more complicated if you want to output an index geometry. Besides, you have the problem of creating seamless uv coordinates. This was also easier to achieve with the current approach.

If the standard geometry entities don't fulfill your requirements, you can still create a custom geometry in Blender.

**Comment by elifer5000** [comment]
Why should it be any different than the code that already existed with the regular (non-buffer) geometry? That one produced vertices and faces. I might be missing something, but shouldn't it be the same?

Also, I just checked and every single BufferGeometry entity produces indices, except the Polyhedron type.

**Comment by Mugen87** [comment]
Like i said before, I didn't find an acceptable and easy solution for the subdivision process in context of an indexed geometry. `PolyhedronBufferGeometry` is the only geometry that performs an actual subdivision. Other geometries work different...
