### ISSUE TITLE
Manipulating vertices on extrudeGeometry causes extra faces

### ISSUE THREAD

**Issue by henryJack** [mrdoob/three.js#10190]
##### Description of the problem 

When manipulating the vertices of an extruded shape you get additional faces. 

![image](https://cloud.githubusercontent.com/assets/22593502/20479740/3b7e4dac-afd7-11e6-869e-3544fcc6bbb6.png)

fiddle here... https://jsfiddle.net/kn3owveg/

It seems that adding `mesh.geometry.verticesNeedUpdate = true;` before the vertex manipulations in the function `modifyRadiusOfVertex` doesn't help.

Three.js version
- [ ] r83 Dev

##### Browser
- [x ] Chrome

##### OS
- [ x] Windows

**Comment by Mugen87** [comment]
I don't think that we see additional faces here. If you set the `wireframe` property of the materials to `true`, you see that these faces already exist before you call `createTaperedTubeMesh`. 

Besides, i think you shouldn't do this kind of geometry manipulation. If the triangulation process of a shape would be changed, your vertex selection would immediately fail. Therefore it's always better to configure the basic geometries of `three.js` only via the constructor properties.

Maybe you should use a custom geometry in order to create your mesh.

**Comment by henryJack** [comment]
Okay, thanks for pointing that out!

![image](https://cloud.githubusercontent.com/assets/22593502/20481892/74092b24-afe1-11e6-8731-c71175d59130.png)

![image](https://cloud.githubusercontent.com/assets/22593502/20481939/a82d592a-afe1-11e6-95a0-75ea036f1aee.png)

Manipulating vertices in this way seems to be a legitimate way of creating custom shapes. Otherwise, why would `verticesNeedUpdate = true` exist?

Is there no way of re-triangulating a face of a 3D shape for example by using `THREE.ShapeUtils.triangulateShape( vertices, holes );` ?

**Comment by Mugen87** [comment]
> Otherwise, why would verticesNeedUpdate = true exist?

`verticesNeedUpdate` is a generic attribute for all instance of `Geometry`. In your case, the usage might be counterproductive. Like i said before, the basic geometries of `three.js` are not designed to handle all kinds of manipulations. You are transforming the output of `ExtrudeGeometry` in a way, where we can't ensure prefect results.

> Is there no way of re-triangulating a face of a 3D shape for example by using THREE.ShapeUtils.triangulateShape( vertices, holes ); ?

`ShapeUtils .triangulateShape` can't be used to repeat the triangulation of the output geometry. The index/face generation is done by the implementation of `ExtrudeGeometry`.

Sry, that i can't provide better answers. I still think the easiest way to solve your problem is to create a custom geometry. Then you have full control over all details of the implementation.
