### ISSUE TITLE
Is MeshStandardMaterial intended as a replacement for Phong and Lambert

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10235]
I'm updating the materials docs, and reading through old pull requests, it seems like at least at one point
MeshStandardMaterial was intended as a replacement for Phong and Lambert materials.

Is this still the case? And if so should I add a note of this in the docs?

Apologies if this has been previously discussed elsewhere.

**Comment by WestLangley** [comment]
With `MeshLambertMaterial`, the illumination model is Lambertian, and the shading model is Gouraud. That is, the illumination calculation is performed at each vertex, and the resulting color is interpolated across the face of the polygon. Some users like it because it is more performant, especially on slower devices.

With `MeshPhongMaterial`, the illumination model is the Blinn-Phong model, and the shading model is Phong. That is, the vertex normals are interpolated across the surface of the polygon, and the illumination calculation is performed at each texel.

`MeshPhongMaterial` is not physically-based. In fact, `MeshToonMaterial`, a classic non-physically-based (NPR) material, extends MeshPhongMaterial.

`MeshStandardMaterial` also uses Phong per-pixel shading, but it uses a micro facet-based, and physically-based, illumination model. It is intended to be an easy-to-use PBR material.

`MeshPhysicalMaterial` is a more-flexible version of `MeshStandardMaterial`. I fully expect `MeshPhysicalMaterial` to be further enhanced in the future -- for example, adding anisotropy.

Not all users want a computationally intensive PBR material, so I would not consider `MeshStandardMaterial` to be a replacement for anything at this point.

**Comment by WestLangley** [comment]
Also, `MeshStandardMaterial` and `MeshPhysicalMaterial` work best when an environment map (`envMap`) is specified. This is so there is something to reflect. I would point this out in the docs, and always specify an environment map whenever these materials are used in either the examples or the documentation examples.

At some point, we will add support (at least for the physically-based materials) for image-based lights, of which environment maps are a special case.

**Comment by looeee** [comment]
@WestLangley many thanks for clarifying that. I'll update the docs. 

Is this related to the WebGLRenderer.physicallyCorrectLights toggle? I.e. do you need to use Standard or Physical materials for that to work?

**Comment by Mugen87** [comment]
@WestLangley Can you recommend papers, articles or books about physically based rendering? I'm always looking for good resources about this topic...

**Comment by WestLangley** [comment]
>Is this related to the WebGLRenderer.physicallyCorrectLights toggle?

@looeee `WebGLRenderer.physicallyCorrectLights` was [implemented](https://github.com/mrdoob/three.js/pull/8260) by @bhouston to provide physical SI units to the `intensity` parameter of each light type. My understanding is it is a work-in-progress, but it is an excellent contribution, IMHO.

>Can you recommend papers, articles or books about physically based rendering?

@Mugen87 There are so many... I think [this](https://interplayoflight.wordpress.com/2013/12/30/readings-on-physically-based-rendering/) is a fine compilation.

**Comment by Mugen87** [comment]
@WestLangley Thanks!

**Comment by looeee** [comment]
@Mugen87 I found a couple of articles from the guys at www.marmoset.co that give a great non-technical overview of PBR and how to use it:
- https://www.marmoset.co/posts/basic-theory-of-physically-based-rendering/
- https://www.marmoset.co/posts/physically-based-rendering-and-you-can-too/

@mrdoob, @WestLangley I'd like to link those two articles in the docs, do you think that would be OK? 

@WestLangley what I've gathered so far is that PBR is a concept rather than a specific implementation. Can you provide any details of how it's implement here? Not asking for any major technical details, just enough to give some explanation of how the material works in the docs. Especially:
- does it use energy conservation? 
- is Fresnel reflection calculated automatically from the Reflectivity and Roughness?

**Comment by bhouston** [comment]
BTW PBR is generally monochromatic energy conserving.  BlinnPhong energy conserving is discussed here: https://github.com/mrdoob/three.js/issues/9248


Fresnel reflections are calculated correctly in this Physical material - or at least they are to my knowledge (there my be bugs.)

The specific implementation that ThreeJS follows is very similar to the Physical material in UE4 in terms of its parameterization.  Almost all PBR models are based on the Disney PBR paper by Burley: https://disney-animation.s3.amazonaws.com/library/s2012_pbs_disney_brdf_notes_v2.pdf

The physically correct lights I believe are also correct to the best of my knowledge (e.g., there may be bugs.)

Physically correct lights work with both Standard (BlinnPhong model) as well as the Physical (GGX, Roughness/Metalic parameterization).

**Comment by Mugen87** [comment]
@bhouston Thanks for sharing the link to the paper!

Do you also know some resources about PBR for beginners? I mean developers or students, who are familiar with non-physically-based (NPR) materials but who want to start with more advanced concepts. I'm currently trying to gather some readings for my university. Unfortunately, we are a little bit weakly positioned in this area of 3D graphics programming...

**Comment by mrdoob** [comment]
> @mrdoob, @WestLangley I'd like to link those two articles in the docs, do you think that would be OK?

Sounds good to me! 👌

**Comment by bhouston** [comment]
Tutorial information is not really my strong suite, but there are these resources:

https://docs.unrealengine.com/latest/INT/Engine/Rendering/Materials/PhysicallyBased/index.html

https://www.youtube.com/results?search_query=understanding+PBR+

**Comment by reality3d** [comment]
@Mugen87
A bit late but I find this guide to be a great introduction on PBR from an authoring perspective 
https://www.allegorithmic.com/pbr-guide

**Comment by Mugen87** [comment]
@reality3d Many thanks!
