### ISSUE TITLE
Matrix4.makePerspective() is never used

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10265]
I'm updating the Matrix4 docs and there's a method called Matrix4.makePerspective( fov, aspect, near, far ) 

Internally this calculates the values of left, right, top and bottom and calls
Matrix4.makeFrustum( left, right, bottom, top, near, far )
and it looks like it is intended for use in PerspectiveCamera.updateProjectionMatrix()

However the PerspectiveCamera calculates its own versions of left, right, top and bottom in a slightly more complex way, taking into account zoom, view (if set) and filmOffset, and then calls Matrix4.makeFrustum directly. 

So it seems that Matrix4.makePerspective() is superfluous - is there a use case that I am missing?

**Comment by looeee** [comment]
Actually  I have found on place that it's used:
https://threejs.org/examples/#webgl_materials_cubemap_dynamic2

**Comment by mrdoob** [comment]
Nice catch! I don't think that's needed on that example.

**Comment by mrdoob** [comment]
And yes, I think we could remove `Matrix4`'s `.makePerspective()` if we're not using it.
/cc @WestLangley

**Comment by mrdoob** [comment]
We can also try to move the code from `PerspectiveCamera` to `Matrix4`.

**Comment by Mugen87** [comment]
Is it okay if i refactor `webgl_materials_cubemap_dynamic2`? I've seen there some more things to improve (e.g. `Geometry`-> `BufferGeometry`, usage of `OrbitControls`)

**Comment by Mugen87** [comment]
@looeee The dependency in `webgl_materials_cubemap_dynamic2` to `.makePerspective()` is now resolved.

**Comment by Mugen87** [comment]
Because `OrthographicCamera` calculates its `left`, `right`, `top`, `bottom` values in `updateProjectionMatrix`, i think `PerspectiveCamera` should also do this. Against this backdrop, i think we can remove `makePerspective()`.

**Comment by Mugen87** [comment]
Besides, parameters like 'fov' or 'aspect'  are directly camera related and should not be present in `Matrix4`...

**Comment by looeee** [comment]
@Mugen87 thanks! Looks good.

**Comment by mrdoob** [comment]
> Besides, parameters like `fov` or `aspect`  are camera related and should not be present in `Matrix4`. IMHO, i think we can remove `makePerspective()`.

What do you think @WestLangley?

**Comment by WestLangley** [comment]
We have `Matrix4` methods to create a rotation matrix, a translation matrix, a scale matrix, a shear matrix, etc., so why not have methods to create an orthographic  projection matrix and a perspective projection matrix?

Maybe `makeFrustum` could be renamed `MakePerspective`. (Thing is, the order of the args is different than those in `MakeOrthographic`... That's unfortunate.)

`makePerspective`, then, could be removed. It is just a different way of parameterizing the args. I am not sure if users rely on it or not.

This is sort of a mess, but I do not have a strong opinion on this one.

**Comment by Mugen87** [comment]
I just wanted to highlight that i'm not a fan of the current method signature of `makePerspective` (so `fov`, `aspect` etc.). But renaming `makeFrustum` to `makePerspective` is a good solution.

**Comment by mrdoob** [comment]
> I just wanted to highlight that i'm not a fan of the current method signature of `makePerspective` (so `fov`, `aspect` etc.). But renaming `makeFrustum` to `makePerspective` is a good idea 👍 

This is our chance then 👍

**Comment by looeee** [comment]
Closed via #10375

**Comment by bhouston** [comment]
BTW: 

(1) Matrix4makePerspective was intended to be an implementaiton of venerable gluPerspective function from OpenGL here: https://www.opengl.org/sdk/docs/man2/xhtml/gluPerspective.xml

(2) Matrix4.makeFrustum was intended to be an implementaiton of the standard OpenGL function glFrustum: https://www.opengl.org/sdk/docs/man2/xhtml/glFrustum.xml

I am okay with removing makePerspective but you shouldn't then rename makeFrustum to makePerspective and change makePerspective's signature.

You are just messing with non-standard terminology and also breaking a bunch of code - like mine.  I am getting warnings for what is clearly incorrect behavior.  I would have preferred that makePerspective just was completely removed rather than essentially breaking it.

I would obsolete the old makePerspective if you feel strongly about it, but this renaming is confusing as we were following OpenGL terminology and now we are not.

**Comment by WestLangley** [comment]
I was afraid of that...

Thing is, we support orthographic cameras, so `Matrix4.makeFrustum()` is not clear. Orthographic cameras have a frustum, too.

As I said above, I do not feel that strongly about this ... but thinking outside the box to suggest solutions, how about removing all the methods and and making new ones with new names?
```javascript
Matrix4.makePerspectiveProjection( left, right, top, bottom, near, far )
Matrix4.makeOrthographicProjection( left, right, top, bottom, near, far )
```
Now we are not confusing names with OpenGL nomenclature -- which is also good because the order of our args is different from OpenGL.

**Comment by bhouston** [comment]
There is also in OpenGL glOrtho: https://www.opengl.org/sdk/docs/man2/xhtml/glOrtho.xml

Maybe something like makePerspective() (which we could obsolete, I am okay with that), makePerspectiveFrustum(), makeOrthographicFrustum()?  I think the Frustum is a good term for specifying all of the frustum bounds.

**Comment by WestLangley** [comment]
>makePerspectiveFrustum(), makeOrthographicFrustum()?

We are not making a frustum, though. We are making a projection matrix...

This is such a mess because in the orthographic case, the args are the frustum parameters; in the perspective case, the args in our case are (I think) the dimensions of the front face of the frustum's near plane (plus the near/far distances) -- instead of the more-natural fov/aspect parameters.

As implemented with the left/right/top/bottom params, I can't imagine a user using the perspective method at all. How is the user supposed to know how to compute the args to pass into the function? As an internal method, it is fine.

**Comment by bhouston** [comment]
> As implemented with the left/right/top/bottom params, I can't imagine a user using the perspective method at all. How is the user supposed to know how to compute the args to pass into the function? As an internal method, it is fine.

What you are arguing for then is going back to the way it was. :)  gluPerspective was intended to be a user friendly means of setting up perspective matrices. :)

**Comment by WestLangley** [comment]
>What you are arguing for then is going back to the way it was. :)

Hehe. I don't like any of the solutions, quite frankly.

How about restoring what we had before, and adding

```javascript
Matrix4.makePerspectiveProjection( fov, aspect, near, far )
Matrix4.makeOrthographicProjection( left, right, top, bottom, near, far )
```

Then, we can remove duplicate functionality in a later release.

BTW, according to the docs

glFrustum — _multiply_ the current matrix by a perspective matrix

**Comment by bhouston** [comment]
> How about restoring what we had before, and adding
> Matrix4.makePerspectiveProjection( fov, aspect, near, far )
> Matrix4.makeOrthographicProjection( left, right, top, bottom, near, far )

So we would have 3 functions then?

makePerspectiveProjection, makeOrthographicProjection, makeFrustum?

With regards to naming, both makeFrustum and makePerspectiveProjection are both perspective projection creation functions, just with different parameterizations.

Maybe we should use something like makePerspectiveFromFOV and makePerspectiveFromNearPlane?  This way both creators explicitly state in their function names their specification.  (This is similar to makeRotationFromQuaternion and makeRotationFromEuler.)

And we can keep makeOrthographic without any "From" specifier because no disambiguation is required?

> glFrustum — multiply the current matrix by a perspective matrix

All gl matrix functions multiple the current matrix.  E.g.: https://www.opengl.org/sdk/docs/man2/xhtml/glTranslate.xml https://www.opengl.org/sdk/docs/man2/xhtml/glScale.xml https://www.opengl.org/sdk/docs/man2/xhtml/glRotate.xml

**Comment by WestLangley** [comment]
An attempt to summarize @bhouston's suggestion...

r.83 `makeOrthographic( left, right, top, bottom, near, far )` remains unchanged

r.83 `makePerspective( fov, aspect, near, far )` renamed to `makePerspectiveFromFOV( fov, aspect, near, far )`

Add `makePerspectiveFromNearPlane( left, right, top, bottom, near, far )` - same as `makeFrustum()` with args in a different order

r.83 `makeFrustum( left, right, bottom, top, near, far )` add to Legacy deprecated list; calls the new method `makePerspectiveFromNearPlane()`

**Comment by bhouston** [comment]
> Add makePerspectiveFromNearPlane( left, right, top, bottom, near, far ) - same as makeFrustum() with args in a different order

The reason why the top/bottom parameters are ordered the way they are in glFrustum/glOrtho is because in OpenGL's normalized device coordinate system, top is positive y, bottom is negative y.  Thus the glFrustum/glOrtho parameter order of (left, right, top, bottom) is actually: (xmin, xmax, ymin, ymax) - which makes sense.

I suspect that @looeee and @Mugen87 didn't know this is OpenGL's NDC and mistakenly believed that WebGL/OpenGL follows the convention of screenspace in Windows and Linux desktops in which y axis is facing downwards.  Thus they have inverted the parameters mistakenly.

This is OpenGL's NDC:

![image](https://cloud.githubusercontent.com/assets/588541/21668404/878e445c-d2cf-11e6-974d-6e8540204168.png)

**Comment by WestLangley** [comment]
I believe OpenGL's NDC space is [left-handed](http://www.songho.ca/opengl/gl_projectionmatrix.html), so the image above is not correct.

>Thus they have inverted the parameters mistakenly.

I believe `makeOrthographic()` and `makeFrustum()` have had their `top/bottom` args in a different order for many years. I may have recently suggested they be made to have identical signatures.

**Comment by bhouston** [comment]
+Y is up though in both NDC and the after projection space.

There is a difference between NDC and the coordinate space after projection (which is really the one we want to be dealing with here.)  In NDC, +z is into the screen.  The space after projection has -z into the screen - that difference between NDC and after projection is evidence on the page you linked.  Particularly this image:

http://www.songho.ca/opengl/files/gl_projectionmatrix01.png
http://www.songho.ca/opengl/files/gl_projectionmatrix02.png

**Comment by looeee** [comment]
>I suspect that @looeee and @Mugen87 didn't know this is OpenGL's NDC...

I can't speak for @Mugen87 but personally I had no idea these functions had OpenGL equivalents. Perhaps going forward, whatever final signature we end up with, comments could be added to the code linking to the related OpenGL functions to prevent this kind of confusion in the future?
