### ISSUE TITLE
Incorrect crossOrigin behaviour in ImageLoader

### ISSUE THREAD

**Issue by dhritzkiv** [mrdoob/three.js#10398]
##### Description of the problem 

In r83, [a new condition was added to the ImageLoader,](https://github.com/mrdoob/three.js/blame/dev/src/loaders/ImageLoader.js#L38) where if crossOrigin was NOT `undefined`, it would load a texture in a different way than when it was `undefined`:

```js
//snip
//ImageLoader at L38
else if ( this.crossOrigin !== undefined ) {
	image.crossOrigin = this.crossOrigin;
	image.src = url;
} else {
	//load it the normal way
}
```

However, some Loaders (such as the TextureLoader in the GLTFLoader) set crossOrigin to an explicit `false` value:

```js
//GLTFLoader at L795
textureLoader.crossOrigin = this.options.crossOrigin || false;
```

So, values such as `false`, `""`, and `null` will evaluate as true for `this.crossOrigin !== undefined`.

---

I think the solution is to change the check at L83 of ImageLoader from `if (this.crossOrigin !== undefined)` to simply `if (this.crossOrigin)`

---

Also, as a separate issue related to this, if `this.crossOrigin` is `true`, then `onProgress` behaviour is lost.

##### Three.js version

- [x] Dev
- [x] r83
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
Well, we first should specify the type of `crossOrigin`.

IMO it's keyword `strings` which should be passed to the `crossOrigin` property of `image`
(or default value`undefined`).

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

Empty strings work as `anonymous` so it also should be set to `image.crossOrigin`.

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

Boolean is weird for me.
What behavior is expected on `true/false`?

Also `null` is weird.
The default value of `crossOrigin` is`undefined`.
What is to set `null` for?

I prefer updating `GLTFLoader` and others not to set invalid values to `crossOrigin` rather than
updating `ImageLoader`.

**Comment by dhritzkiv** [comment]
Ah. Good points. So, in short, the crossOrigin is a string or `undefined`?

Would the best check then be `if (typeof this.crossOrigin === "string")`?

**Comment by takahirox** [comment]
> Ah. Good points. So, in short, the crossOrigin is a string or undefined?

Yes.

> Would the best check then be if (typeof this.crossOrigin === "string")?

Well, as I wrote I prefer updating `GLTFLoader` and others to set proper values to `crossOrigin`.
I'm really not sure if we should care the case that `crossOrigin` isn't `string`.

**Comment by mrdoob** [comment]
#10439
