### ISSUE TITLE
It is not possible to use this library via bower

### ISSUE THREAD

**Issue by casufi** [mrdoob/three.js#10431]
##### 
bower.json was deleted so it is not so easy  to use this library with bower 

##### r83
- [ ] r83

**Comment by mrdoob** [comment]
Yes, bower file was removed...
Do you mind if I ask why you're using bower instead of npm?

**Comment by casufi** [comment]
We are using bower as a corporate standard. That was not a personal choice.

**Comment by mrdoob** [comment]
Hmm... What corporation is that?

**Comment by NicolasRannou** [comment]
+1 - the web components and polymer library (wrapper library around web components by google) also uses Bower as a standard package manager so being able to import ThreeJS via bower simplifies the workflow...

https://beta.webcomponents.org/
https://www.polymer-project.org/1.0/

**Comment by SirVer** [comment]
+1 Another Polymer user here and depending on threejs there is a PITA without a bower file.

**Comment by mrdoob** [comment]
Out of curiosity, do you mind explaining what it is that you have to do? How is it a PITA?

**Comment by SirVer** [comment]
Right now the only supported solution seems to be to copy the minified and debug .js file into the repository, effectively forking it. I am not a specialist on bower, so maybe I missed something.

**Comment by NicolasRannou** [comment]
I have elements that rely on THREE.JS.
Polymer relies on Bower to manage all the package dependencies/versions.

Right now I copy `three.min.js` in my element. It cause several issues:
* I have to update `three.min.js` each time there is a new release (which is OK)
* Big problem is that it can create conflict between different `three.min.js` version.

If my element contains imports `v80` and I use another element from somebody else that imports `v84`, it can lead to conflict between versions. Also it will load `three.min.js` 2 times instead of only importing it 1 time.

If element A and B are both referring to the `THREEJS bower package`, it will work fine or in the worst case we get warning that element A requires `v80` and that element B requires `v84`, then the user chooses how to handle that.

**Comment by NicolasRannou** [comment]
Not sure what happens in the following scenario where 2 different versions of THREEJS are loaded:
https://jsfiddle.net/nicolasrannou/vc3qkhzh/

**Comment by mrdoob** [comment]
I see I see...

**Comment by mrdoob** [comment]
Fixed!

**Comment by SirVer** [comment]
The polymer team is on a mid-term transition off of bower onto npm, so this might not be needed in a few months anymore. For now, this is much appreciated.

**Comment by mrdoob** [comment]
@SirVer Please, let us know when that happens.

**Comment by NicolasRannou** [comment]
thanks @mrdoob !

@SirVer  I thought this through and is there an actual reason we do not just pull `three.js` from github: `bower install mrdoob/three.js`? I can not remember if there was a reason not to do it...

In this case, no need of `bower.json`.

I am wondering which is the utility of the `bower.json` file other than registering the package to the bower package repo...

**Comment by SirVer** [comment]
Fine with me! Thanks for keeping it around so long.

**Comment by mrdoob** [comment]
@casufi?

**Comment by casufi** [comment]
Same here. Thank you so much for your support.

**Comment by mrdoob** [comment]
@casufi sure thing. thanks!
