### ISSUE TITLE
force computeBoundingSphere when NeedsUpdate = true 

### ISSUE THREAD

**Issue by tonnot** [mrdoob/three.js#10449]
##### Description of the problem 
I think we need I way for THREE runs computeBoundingSphere() everytime we set needsUpdate = true.  Now set needsUpdate = true only have drawing effects, but not have any influence for raycast.  (I think...)

In addition, I think we'd need a way to force computeBoundingBox when needsUpdate=true.
Maybe:  needsUpdateAndBoxing? 

I'm talking about when you set needsUpdate for position attribute.

It could be appropiate when we change groups and indexes ? 
This change geometry aspect of objects and raycast would have to take into account....

What do you think ?
Thanks.

##### Three.js version

- [ ] Dev
- [x ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
I don't think it's a good idea to automatically recompute bounding boxes when vertex or index data are changed. There are use cases where data might vary but the respective bounding volumes (AABB and bounding sphere) stay the same. A computation of new bounding volumes would be a wasted operation in this case.

Since `BufferGeometry` provides and API for updating bounding volumes (`.computeBoundingBox()` and `.computeBoundingSphere()`), it's the responsibility of the user to call these methods if necessary. Against this backdrop, I don't see any benefits for introducing a new flag (like the mentioned `needsUpdateAndBoxing`).
