### ISSUE TITLE
Can't use CanvasRenderer or Projector when I'm using Three from npm

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#10617]
##### Description of the problem 
Here is a reproducible example, I have in my js file just the THREE import and after that the CanvasRenderer code as taken from [here](https://github.com/mrdoob/three.js/blob/master/examples/js/renderers/CanvasRenderer.js):
```js
import * as THREE from 'three';
import './CanvasRenderer'; // or Projector
```

The error in the console is 

```
Uncaught TypeError: Cannot set property d of #<Object> which has only a getter.
```

which happens when you assign the function on this line
```js
THREE.CanvasRenderer = function ( parameters ) {
```
Basically says that `THREE.CanvasRenderer` already exists and is not configurable, and indeed it does exist as a deprecation warning in [Three.Legacy.js](https://github.com/mrdoob/three.js/blob/master/src/Three.Legacy.js#L1443).

The same happens for Projector. As a bundler I use Webpack@2.2.0.

Sorry I wouldn't know what to export instead of that function in order to bypass this error.

##### Three.js version
- r84

**Comment by mrdoob** [comment]
Hmm, yeah... we still don't know how to modularise the stuff in the examples folder without breaking traditional workflows...

**Comment by marcofugaro** [comment]
What do you mean modularise stuff? Do you need any help?

**Comment by cecilemuller** [comment]
This thread might provide some context about the modules in examples issue: https://github.com/mrdoob/three.js/issues/9562

**Comment by marcofugaro** [comment]
Oh, the other day I did [this library](https://www.npmjs.com/package/three-addons) because I needed some Three.js addons in my workflow, maybe could be of any help.

Of course the only issue is with the two deprecation notice functions, as this issue reports.

**Comment by cecilemuller** [comment]
In the case of CanvasRenderer, the issue here is the conflict with the export from Three.Legacy.js: should CanvasRenderer be part of the core or only be in examples ?

---

But as for modularising examples in general: as long as we only have one file per example, it won't be usable both as simple <script> tag and as import-able module.

I think the cleanest solution would be to have each example as an ES module (that can be used for "import"), and a build target for each example (to generate a version that can be used for the classic <script> workflow).

The other main issue is examples inject themselves in the THREE namespace.

ES Modules would reference the functions directly:

	import {SVGRenderer} from 'examples/js/renderers/SVGRenderer.module.js';
	const myvar = new SVGRenderer();

But classic workflow would expects "THREE.SVGRenderer":

	<script src="examples/js/renderers/SVGRenderer.js">
	...
	var myvar = new THREE.SVGRenderer();

So the build target for classic would have to append append something like "THREE.SVGRenderer = SVGRenderer" to the built file.

**Comment by Mugen87** [comment]
Closing. As @cecilemuller mentioned, #9562 is the leading issue for this topic.

**Comment by cecilemuller** [comment]
In the meantime, if you use Webpack, you can manually alias files from "examples" to `import` this way, so even if it's not as clean, at least it's in the same bundle instead of having to have a <script> for each file:


In `package.json`:

```json
"dependencies": {
	"three": "0.85.0",
	"webpack": "2.4.1"
}
```

In `webpack.config.js`:

```js
resolve: {
	alias: {
		'three/OrbitControls': path.join(__dirname, 'node_modules/three/examples/js/controls/OrbitControls.js'),
		'three/OBJLoader': path.join(__dirname, 'node_modules/three/examples/js/loaders/OBJLoader.js')
		// ...
	}
},

//...

plugins:[
	new webpack.ProvidePlugin({
		'THREE': 'three'
	}),
	//...
]
```

In `application.js` (ES Modules version):

```js
import 'three';
import 'three/OrbitControls';
/* global THREE */

console.log(THREE.OrbitControls);
```

**Comment by ri** [comment]
I found that @cecilemuller's excellent workaround only worked with r82 in my situation (with Webpack 2 and using a legacy example).

In particular, cf975178 causes Webpack 2 to export the `THREE` properties in a way that can not be replaced and `CanvasRenderer` (unlike `OrbitControls` in @cecilemuller's example) has a pre-existing definition on `THREE`.

``` js
> THREE.CanvasRenderer
function CanvasRenderer() {

	console.error( 'THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.js' );

	this.domElement = document.createElementNS( 'http://www.w3.org/1999/xhtml', …

> THREE.CanvasRenderer = 42
42

> THREE.CanvasRenderer
function CanvasRenderer() {

	console.error( 'THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.js' );

	this.domElement = document.createElementNS( 'http://www.w3.org/1999/xhtml', …
```

As far as I can tell, the builtin `THREE` functions are exported using getters instead of object properties. In my case, cf975178 is the difference between these two _compiled_ export styles:

``` js
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "CanvasRenderer", function() { return CanvasRenderer; });

// or

exports.CanvasRenderer = CanvasRenderer;
```

To work with r83 and above, I just had to explicitly load the UMD version in the `ProvidesPlugin`:

``` js
new webpack.ProvidePlugin({
  'THREE': 'three/build/three'
}),
```

**Comment by pmaster06** [comment]
The only way for me without changing the sources or using a outdated 'custom' npm package was (r89, Webpack3, ES6):

`window.THREE = Object.unfreeze(require('three'))
require('three/examples/js/renderers/Projector')
require('three/examples/js/renderers/CanvasRenderer')

// After that you can do a:
let  renderer = new THREE.CanvasRenderer()

// with Object.unfreeze declared before:
// source found : [here](https://stackoverflow.com/questions/19293321/opposite-of-object-freeze-or-object-seal-in-javascript/26752410#26752410)

Object.unfreeze = function (o) {
  var oo = undefined
  if (o instanceof Array) {
    oo = []
    var clone = function (v) {
      oo.push(v)
    }
    o.forEach(clone)
  }
  else if (o instanceof String) {
    oo = new String(o).toString()
  }
  else if (typeof o == 'object') {
    oo = {}
    for (var property in o) {
      oo[property] = o[property]
    }
  }
  return oo
}`

**Comment by zstauber** [comment]
I use three.js with RequireJS (my preferred AMD loader) and have been able to successfully reincorporate CanvasRenderer.js and Projector.js into build/three.js in R90 if anyone wants a copy.

My use case was trying to use it to render a model of the solar system in Chrome on a Raspberry Pi 2 Model B, which simply not playing nice with WebGLRenderer in any way, shape, or form, including any of the examples on the threejs.org site, even after enabling the "Software override rendering list." :(

**Comment by BennyHinrichs** [comment]
@pmaster06 My dude. I've been working on this for like 4 hours, and your solution is the only thing that's worked!

**Comment by zstauber** [comment]
I just realized I could attach a file here.  Just use CanvasRenderer like you used to.
[three.js.zip](https://github.com/mrdoob/three.js/files/1753341/three.js.zip)

**Comment by morgansegura** [comment]
Thank you, very helpful!

**Comment by MagicLeeW** [comment]
@pmaster06 thx，very helpful

**Comment by r3gisc** [comment]
It was a pleasure to help
