### ISSUE TITLE
glTF Loader animation bug

### ISSUE THREAD

**Issue by leerichard42** [mrdoob/three.js#10754]
##### Description of the problem 
When loading the animated handsWithPlane.gltf file found here: https://www.dropbox.com/sh/dvprkyj2ly782jn/AABLjwQLiOSWfr2VDdtlzjYCa?dl=0

The plane, which should not be animated, seems to be taking animation values from the hands, even though the plane is not attached to any skeleton. 
![tiltedplane](https://cloud.githubusercontent.com/assets/4475130/22706602/e6243552-ed3d-11e6-87e9-1593ac26c0e4.png)

There are two additional test models in the folder, which are isolated versions of the animated hand and non-animated plane. 

##### Three.js version

- [x] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
I've confirmed this problem.
I found hand_L bone affects plane.
Maybe `SkinMesh`/`Skeleton` building issue?
I'll take a look closer....

/cc @donmccurdy

**Comment by takahirox** [comment]
BTW does this animation work correctly on other libraries?

**Comment by leerichard42** [comment]
Do you mean other than 3js? I couldn't find anywhere else to load and test glTF files, but I exported the animation as an FBX from Maya and it works when reimporting into Maya - I then converted it to glTF with assimp.

**Comment by cx20** [comment]
According to acquaintance Maya user
`Maya -> FBX -> assimp -> glTF` conversion path, I think that there is not much achievement.
Please try `Maya -> OpenMaya -> dae -> COLLADA2GLTF -> glTF`
I am sorry, I am not a Maya user, so I do not know how to use it.

**Comment by leerichard42** [comment]
I was able to export my Maya file using OpenCOLLADA, but I get a segfault when trying to convert that .dae file using COLLADA2GLTF. I've added my .ma and .dae files to the dropbox link, if that might help someone who is more familiar with the pipeline.

**Comment by takahirox** [comment]
This problem seems be caused by sharing a material between `SkinnedMesh` and `Mesh`.
The material has `skinning=true` property for `SkinnedMesh` but this makes plane mesh go wrong.

An easy workaround so far is separating materials.
I confirmed this problem disappeared by removing the following line
from "mesh_11" (for `SkinnedMesh`) in glTF file.

    "material": "lambert1",

I'm thinking how to solve this problem on Three.js...

**Comment by mrdoob** [comment]
Sounds like a bug in `WebGLRenderer`. It's there a working link I can use for testing?

**Comment by takahirox** [comment]
I'll make soon.

I speculate bone related uniforms in material are unexpectedly shared between `SkinnedMesh` and `Mesh`.

**Comment by takahirox** [comment]
I made an example.

https://takahirox.github.io/gltf-animation-bug/index.html

See here for workarounds.

https://github.com/takahirox/takahirox.github.io/blob/master/gltf-animation-bug/index.html#L83-L130

The root issue seems how to share a material between `Mesh` and `SkinnedMesh`.

This's my speculation.
It seems like this problem is caused by a shared material.
Only one material is shared in a scene, its `skinning` is set `true` for `SkinnedMesh`, and
the corresponding GLSL code has skinning related lines.
But the plane is just `Mesh` (non `SkinnedMesh`) and it doesn't have
`bindMatrix`, `bindMatrixInverse`, `skeleton`, `skeleton.boneMatrices`,
`geometry.attributes.skinIndex`, `geometry.attributes,skinWeight`.

The corresponding attributes and uniforms to these properties
are disabled and aren't updated respectively.

https://github.com/mrdoob/three.js/blob/0aaf85c5fd93f72a5022f46ab8632b6193069981/src/renderers/webgl/WebGLState.js#L449-L462

https://github.com/mrdoob/three.js/blob/8afa08db625c5979bbc77c56ff86e5e525681564/src/renderers/WebGLRenderer.js#L1846-L1869

Then the values used to previously render another object seem being reused.
So the plane unexpectedly does skinning animation.

To solve this, I have three ideas in my mind.
1. Separate materials for `Mesh` and `SkinnedMesh` in `GLTFLoader`. Easy but it won't strictly follow what glTF file specifies.
2. Upload skinning related dummy attributes and uniforms not to do skin animation if `material.skinning` is `true` and object is not `SkinnedMesh`
3. Update GLSL code. Currently branching with `#define USE_SKINNING` for skinning. If we replace it with uniform flag, we can dynamically turn on/off skinning depending on object.

**Comment by takahirox** [comment]
BTW, mesh_0 ~ mesh_10, mesh_12 ~ mesh_15 in this glTF file look weird.
They're used by nodes which don't have skin/skeleton but
have JOINT/WEIGHT (skinIndex/skinWeight) attributes.
I'm wondering if it's correctly made/converted.

(This isn't root issue. Even if we fix this, the animation bug reported remains.)

**Comment by leerichard42** [comment]
Good catch, I can file an assimp issue. Just to clarify, are the other hands most likely being animated because they're reusing the skinning from the first hand then?

**Comment by takahirox** [comment]
Yep, I think so.

**Comment by donmccurdy** [comment]
@takahirox Thanks for wading through all of this! 👏

> 1. Separate materials for Mesh and SkinnedMesh in GLTFLoader. Easy but it won't strictly follow what glTF file specifies.

If I understand correctly, this option won't help when there are two SkinnedMesh instances using the same material, but one has animation playing and the other does not?

**Comment by takahirox** [comment]
Probably it won't be problem.

This problem occurs if an object doesn't have skinning properties
(`bindMatrix`, `bindMatrixInverse`, `skeleton`, and so on).
The two `SkinnedMesh` instances should have them even if they don't play animation.

**Comment by mrdoob** [comment]
How about we remove `material.skinning` and inside WebGLProgram we check for object.isSkinnedMesh?

I'll give a it a try.

**Comment by mrdoob** [comment]
I think it should be fixed now?

**Comment by takahirox** [comment]
Not yet.

https://takahirox.github.io/gltf-animation-bug/index.html

(This example uses the latest dev three.js via rawgit)

**Comment by takahirox** [comment]
As I wrote the above, the problem is occurred by non-updating skinning attribute/uniform values.

https://github.com/mrdoob/three.js/issues/10754#issuecomment-279193969

**Comment by mrdoob** [comment]
I'll keep trying! 😁

**Comment by takahirox** [comment]
Cool!

The key is how we can share skinning material (GLSL code with `#define USE_SKINNING`)
between normal `Mesh` and `SkinnedMesh`.

The problem is, in current implementation, if `#define USE_SKINNING` is set
the skinning attribute/uniform values must be uploaded because
skinning code is hardcoded, we can't directly switch on/off.

**Comment by takahirox** [comment]
BTW, do you keep deprecating `material.skinning` even it didn't solve this issue?
If so, I need to remove `material.skinning` from some modules (mmd, outline, deffered...)

**Comment by mrdoob** [comment]
> BTW, do you keep deprecating `material.skinning` even it didn't solve this issue?

Yes, I can't see any reason for keeping it.

**Comment by mrdoob** [comment]
Interestingly, there is no shader crash when using http://threejs.org/build/three.js...

**Comment by mrdoob** [comment]
Okay, so `material.skinning` did indeed fix the issue, but there is another issue going on... `GLTFLoader` doesn't set `Skeleton.useVertexTexture` to `true` and we're running out of uniforms.

```
WebGLRenderer: too many bones - 336, this GPU supports just 251 (try OpenGL instead of ANGLE)
```

I've hacked this code in the test:

```js
loader.load( './handsWithPlane.gltf', function ( gltf ) {

	var object = gltf.scene !== undefined ? gltf.scene : gltf.scenes[ 0 ];

	object.traverse( function ( child ) {

		if ( child.isSkinnedMesh ) {

			var skeleton = child.skeleton;

			var size = Math.sqrt( skeleton.bones.length * 4 );
			size = THREE.Math.nextPowerOfTwo( Math.ceil( size ) );
			size = Math.max( size, 4 );

			skeleton.boneTextureWidth = size;
			skeleton.boneTextureHeight = size;

			skeleton.boneMatrices = new Float32Array( skeleton.boneTextureWidth * skeleton.boneTextureHeight * 4 ); // 4 floats per RGBA pixel
			skeleton.boneTexture = new THREE.DataTexture( skeleton.boneMatrices, skeleton.boneTextureWidth, skeleton.boneTextureHeight, THREE.RGBAFormat, THREE.FloatType );

			skeleton.useVertexTexture = true;

		}

	} );

	var animations = gltf.animations;
	...
```

And that gives me this:

![screen shot 2017-02-15 at 08 41 35](https://cloud.githubusercontent.com/assets/97088/22984578/aa603502-f35a-11e6-96af-8f8c184ead32.png)

Note that this is what I get with [the builds](https://rawgit.com/mrdoob/three.js/ab9e2e2aa32199492b1fee8e29b75000c302f2a3/build/three.js) pre-`material.skinning` removal:

![screen shot 2017-02-15 at 08 43 04](https://cloud.githubusercontent.com/assets/97088/22984644/e6a2045a-f35a-11e6-8ac1-20ee5b1338d8.png)

**Comment by mrdoob** [comment]
The solution for now will be to move the `useVertexTexture` logic to the `WebGLRenderer`.

**Comment by takahirox** [comment]
> Okay, so material.skinning did indeed fix the issue

You meant, on your environment 
the issue was solved by removing `material.skinning` and 
the animation on this example works correctly
(the plane doesn't play  animation) now?

https://takahirox.github.io/gltf-animation-bug/index.html

But on my environment (Windows10 + Chrome 56.0.2924.87 (64-bit))
still animation goes wrong, the plane plays animation (rotation).

![image](https://cloud.githubusercontent.com/assets/7637832/22987568/17bfee5e-f364-11e6-8b9a-a9a0e057ca38.png)
![image](https://cloud.githubusercontent.com/assets/7637832/22987576/2186915e-f364-11e6-96e6-02998e5788b3.png)

This issue would be platform specific?
That can be because the behavior if we don't upload attribute/uniform could be
platform specific.

**Comment by mrdoob** [comment]
Ok, now `WebGLRenderer` uses float vertex textures by default for skinning. If the GPU doesn't pass `gl.getParameter( gl.MAX_VERTEX_TEXTURE_IMAGE_UNITS ) > 0 && !! extensions.get( 'OES_texture_float' )` then it'll try using uniforms. If the total uniforms is more than the GPU handles it will log an error without crashing.

**Comment by mrdoob** [comment]
I guess everything I've done so far is fixing issues that are only popping on my limited GPU (MacBook). Now I can finally see the plane rotation issue you guys are talking about.

**Comment by mrdoob** [comment]
Have we confirmed that the animation plays correctly with other libraries?

**Comment by takahirox** [comment]
I've tried some other libraries but they couldn't load.
(LMK if anyone succeeded)

As I wrote, this glTF file has some problems.
I think we should make simpler glTF file which can reproduce this issue.
I'm trying.

**Comment by takahirox** [comment]
This issue isn't glTF specific.
Sharing material between `Mesh` and `SkinnedMesh` happens this issue.

I made a  simpler example.

(Demo) https://takahirox.github.io/gltf-animation-bug/index2.html
(Code) https://github.com/takahirox/takahirox.github.io/blob/master/gltf-animation-bug/index2.html

The left one is normal `Mesh` and the right one is `SkinnedMesh`.
They share a material.

Rotating a `Bone` of the `SkinnedMesh` unexpectedly affects the normal `Mesh` rotation.

https://github.com/takahirox/takahirox.github.io/blob/master/gltf-animation-bug/index2.html#L138

![image](https://cloud.githubusercontent.com/assets/7637832/23043159/40028b1e-f450-11e6-8c46-058ea3635abc.png)

If we separate material by replacing this line 

    plane = new THREE.Mesh( createPlaneGeometry(), material );

https://github.com/takahirox/takahirox.github.io/blob/master/gltf-animation-bug/index2.html#L111

with

    plane = new THREE.Mesh( createPlaneGeometry(), material.clone() );

then we get an expected result, non-rotation normal `Mesh`.

**Comment by takahirox** [comment]
I just noticed that `webgl_animation_skinning_morph` example doesn't display 2nd model.
It seems it has the same root issue.

**Comment by mrdoob** [comment]
> I just noticed that `webgl_animation_skinning_morph` example doesn't display 2nd model.
It seems it has the same root issue.

Yep. Noticed that too... Reverting!

**Comment by mrdoob** [comment]
@leerichard42 any chance you could export to GLTF2? I had a quick look again and I'm getting this:

![screen shot 2017-02-24 at 11 44 26](https://cloud.githubusercontent.com/assets/97088/23318306/a9a393ec-fa86-11e6-81eb-ae102351a5de.png)

**Comment by donmccurdy** [comment]
@mrdoob the warning can be ignored there; GLTF2Loader does still accept multiple nodes per mesh. Not sure if that result is related to gltf 2.0 or not.

**Comment by mrdoob** [comment]
Basically the problem (as @takahirox has explained) is that GLTF*Loader is creating `Meshes` and `SkinnedMeshes` that share the same material. Unfortunatelly, WebGLRenderer doesn't support that at the moment.

I've also noticed that `GLTF*Loader` also produce `SkinnedMeshes` with materials that do not have the `material.skinning` set to `true`.

I hope to clean this up eventually, but it's a hard problem that needs more clean up first.

**Comment by bhaux** [comment]
@mrdoob we're hoping to get character animation through gltf but this is one of our roadblocks - what timeline are you looking at for this?

**Comment by mrdoob** [comment]
I think we need more samples.

**Comment by bhaux** [comment]
what specifications/properties do you need for your examples?

**Comment by mrdoob** [comment]
We basically need samples that do not load correctly. So basically any roadblock you find.

**Comment by enesser** [comment]
Ran into this problem. Could not rig this box as follows --

![](https://i.stack.imgur.com/DPp8T.png)

With even just the top flap rigged, the entire box rotates:
https://codepen.io/enesser/pen/ad750cee253066e8e192951bb07c362f

Rigging the side flaps results in distorted geometry.

Workaround appears to setting different materials on anything that is rigged with, say, a "skinned_" prefix and traversing through the model and setting any material without that prefix to `material.skinning = false;`. Works OK for something as simple as the top flap animation but more complex animations are very difficult to do with this problem.

Blender file here: 
https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift-simple.blend

**Comment by donmccurdy** [comment]
^Same file: https://gltf-viewer.donmccurdy.com/#model=https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift-simple-v2.gltf

... the structure is interesting:

<img width="265" alt="screen shot 2017-10-16 at 8 38 18 am" src="https://user-images.githubusercontent.com/1848368/31620974-75f5c9c8-b24d-11e7-8089-6d33d7f8d040.png">

Not sure why Blender writes two meshes here. Does there need to be a bone anchoring the box or something? Or maybe something incorrect with skin weights/indices or how we're loading them...

**Comment by enesser** [comment]
@donmccurdy Not sure, here's what the outliner looks like for convenience -- 

<img width="373" alt="screen shot 2017-10-16 at 12 01 22 pm 1" src="https://user-images.githubusercontent.com/5659221/31625001-2633d070-b26a-11e7-95fb-af76f30a7eeb.png">

I can stabilize the box by using code to turn off material's skinning `(material.skinning)` on all materials that aren't attached to bones. Of course I have to duplicate materials in order to successfully to do that. That fixes the back flap but getting the side flaps not to distort seems tricky.

Interested in learning all I can about this, PBR & animations working on the web is really exciting.

**Comment by donmccurdy** [comment]
@enesser what are the names of the nodes in the three.js scene that you are disabling skinning on?  I'm trying on the Cube_0 and Cube_1 meshes, with https://gltf-viewer.donmccurdy.com/#model=https://s3-us-west-2.amazonaws.com/s.cdpn.io/168282/rigged-gift-simple-v2.gltf, and not seeing the right results. Were there any other changes?

**Comment by donmccurdy** [comment]
@enesser I've found the issue. There seems to be an expectation somewhere that the skin weights are normalized, or at least that there be a bone assigned to each vertex. In the `.blend` model you include, the vertices around the box's base are not assigned to any bones. That's not necessarily invalid (clearly it works in Blender) but it's causing issues in three.js for sure...

Anyway it's pretty easily fixed by adding a bone for the base, and assigning the remaining vertices.

Result: [rigged-simple-edit.zip](https://github.com/mrdoob/three.js/files/1617687/rigged-simple-edit.zip)

![91ace8b8-eed0-485e-9772-cccebf52716a-50400-0001d3ad823cdf37](https://user-images.githubusercontent.com/1848368/34758001-c9b4dbf6-f589-11e7-824f-5aac2ffa5011.gif)

I believe we've fixed the original issue ([materials are now cloned when skinning is used](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L2140-L2158)), so I'll close this issue.
