### ISSUE TITLE
Performance between r84 and r68

### ISSUE THREAD

**Issue by louisle** [mrdoob/three.js#10784]
>#### Update2: Proplem is resolved, I call `sortFacesByMaterialIndex`. Thank god for that.
>#### Update1: Difference when switch r71 to r72.
##### Slow when render mesh with too many face in r84, not happen in r68

Hi, I am beginner with threejs,
I use PlaneGeometry to create a map, and use about 62500 segments, and FPS is smaller 10.
When switch to r68, FPS is good(~60).

Some one help me to improve performance in r84.

You can edit for small-test. Change script tag in body to switch version.
http://jsfiddle.net/hoangvu171819/yzg1ap9v

Thanks.

**Comment by killerkarnikel** [comment]
At first, sorry for my english ;)
Thanks for this.
but i have an other performance problem. Im used r.84 instead of r.73 and the fps only fail on mobile  device (SonyZ5) . I found out, it is only when i use Spotlight.

- When im using r73 i dont have any problems ( using 50x Spotlights without shadow etc.. )
- When using r84 i have 15fps on my Device. Still 60fps in Firefox. When i disable Spotlight, or change to directionLight, there are no problems.

But what i think is , with r84 the spotlight has much better quality . I dont know where to adjust that? I already set the render to low quality..

http://jsfiddle.net/yzg1ap9v/3/

**Comment by killerkarnikel** [comment]
Hello, thanks for this post above.
#im sorry for my englisch.
I have another problem with spotlight. I was using r.73 and had 50x simple Spotlights without shadows etc.. it works without problems, still 60fps also on mobile.

Now i was changed to r84, and the spotlights are much better quality, and needing much more power. On desktop somethime i still have 60fps, but my device running with 20fps. But i was able to produce it for desktop also -> http://jsfiddle.net/yzg1ap9v/9/ 
(*if your desktop very fast you need to check it on device*)
I know 50x Spotlights are maybee to much, im just wondering if is it possible to power down the spotlights in r.84?
thanks and LOVE THREE JS :)
