### ISSUE TITLE
Optimising Vector3.applyMatrix4()...

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#10849]
After #10841, I was doing a quick check to the Chrome Developer Tools' Timeline and I noticed `isFinite()` taking quite a bit of time...

![screen shot 2017-02-20 at 21 35 18](https://cloud.githubusercontent.com/assets/97088/23152276/e434d4ea-f7b5-11e6-8976-e60647136c34.png)

https://github.com/mrdoob/three.js/blob/dev/src/math/Vector3.js#L288-L300

@WestLangley @bhouston Does this optimisation look good to you?

```js
applyMatrix4: function ( m ) {

	var e = m.elements;
	var tx = this.x, ty = this.y, tz = this.z;

	var x = e[ 0 ] * tx + e[ 4 ] * ty + e[ 8 ]  * tz + e[ 12 ];
	var y = e[ 1 ] * tx + e[ 5 ] * ty + e[ 9 ]  * tz + e[ 13 ];
	var z = e[ 2 ] * tx + e[ 6 ] * ty + e[ 10 ] * tz + e[ 14 ];
	var w = e[ 3 ] * tx + e[ 7 ] * ty + e[ 11 ] * tz + e[ 15 ];

	if ( w !== 0 ) w = 1 / w;

	this.x = x * w;
	this.y = y * w;
	this.z = z * w;

	return;

},
```

**Comment by WestLangley** [comment]
For related history, see the discussion in https://github.com/mrdoob/three.js/pull/7326 and https://github.com/mrdoob/three.js/issues/9387.

Also https://github.com/mrdoob/three.js/commit/8c4f342ac4b8b92877bf41f89380a5237b4effc7.

Looking at this `Vector3` method...
```javascript
multiplyScalar: function ( scalar ) {

	if ( isFinite( scalar ) ) {

		this.x *= scalar;
		this.y *= scalar;
		this.z *= scalar;

	} else {

		this.x = 0;
		this.y = 0;
		this.z = 0;

	}

	return this;

},
```
... in order to prevent `Infinity`, we return an incorrect answer without warning instead. I am not sure that is a good tradeoff.

>Does this optimisation look good to you?

Again, returning an incorrect answer without warning if `w` is zero.

/ping @bhouston

**Comment by bhouston** [comment]
I agree with checking for 0 in the divide function.  I have never seen before a checking isFinite/isNan in the multiplyScalar function, but I guess that is sort of the converse.  I think it is not necessary.  This goes against Three.JS's philosophy of not checking the validity of inputs.  A non-finite input to this function is just wrong and it is caused by a bug elsewhere.  I figure we do not have to protect against it.

The divide by 0 in the divide function is much more common, so I would leave that one.  I  guess I am inconsistent in my reasoning but I am favoring protecting us from the very common error of dividing by zero and less worried about this particular case.  I think these choices are also very common in other 3D libraries.

Once we decide to protect against non-finite values, we really should be checking for them almost everywhere for consistently sake -- but we we are not likely to do so, so why check in this function?

**Comment by bhouston** [comment]
@mrdoob I like your optimization.  Seems reasonable and fast.

**Comment by bhouston** [comment]
@WestLangley my first comment above is about removing the isFinite in the multiplyScalar function -- that seems like a reasonable thing to do given that isFinite is apparently super slow.  I wouldn't even have a warning for someone passing in a non-finite value -- because that is their own bug coming from some random other place.  Not Three.JS's responsibility to handle in any way.

**Comment by WestLangley** [comment]
>@mrdoob I like your optimization.

I do not like it for the reason I stated above.

I would just remove the `isFinite()` check from `Vector*.multiplyScalar()` and leave `applyMatrix4()` as is.

>I guess I am inconsistent in my reasoning but I am favoring protecting us from the very common error of dividing by zero and less worried about this particular case.

We can't check for zero-divide everywhere we divide. Consequently, I would not check for it at all.

**Comment by mrdoob** [comment]
We're in agreement then! I'll give it a go 👌
