### ISSUE TITLE
Three.RingGeometry breaks with inner radius of 0

### ISSUE THREAD

**Issue by henryJack** [mrdoob/three.js#10843]
##### Description of the problem 

If you generate a new RingGeometry via `THREE.RingGeometry( 0, 14, 8 );` and set the inner radius to 0, you end up with a shape which looks like this...
![image](https://cloud.githubusercontent.com/assets/22593502/23130204/76d2e1f4-f77d-11e6-8e13-8e0e68004626.png)

You should be seeing a `THREE.CircleGeometry` with outer radius `14`.

Example taken from... https://threejs.org/docs/?q=ring#Reference/Geometries/RingGeometry

##### Three.js version
- [x] r84

##### Browser
- [x] Chrome

##### OS
- [x] Windows

**Comment by Mugen87** [comment]
Because of this [line](https://github.com/mrdoob/three.js/blob/dev/src/geometries/RingGeometry.js#L53) the value of `innerRadius` is set to `20`. I don't think, we need to handle this in the code. It's better to adjust the settings of the controls in the geometry viewer so it's not possible to select a `0`.
