### ISSUE TITLE
camera.worldMatrix has NaN elements

### ISSUE THREAD

**Issue by eMYKion** [mrdoob/three.js#10936]
##### Description of the problem 

A small web game utilizing three.js crashed when I updated the three.min.js that the client uses.

In a render function, the client calls:

`var pLocal = new THREE.Vector3(x, 0, z); //in front of camera`
`var pWorld = pLocal.applyMatrix4(camera.matrixWorld);`

where `x`, `y`, and `z` are integers from keyboard events.

`console.log(pLocal);` returns a vector, typically:

`q {x: 0, y: 0, z: 0}`

but `console.log(pWorld)` returns:

`{x: NaN, y: NaN, z: NaN}`

When I switch the three.min.js back to a version from long ago, `console.log(pWorld)` returns:

`q {x: 0, y: 5, z: 0}`

`console.log(camera.matrixWorld)` returns a matrix with all elements defined.

switching back to the current three.js version,
`console.log(camera.matrixWorld)` returns a matrix whose last four elements are `NaN`.

The only variable here is the version of three.min.js. An old version works, but the new one does not.

##### Three.js version

- [ ] Dev
- [ ] r84
- [x] master branch from git as of 3/5/2017

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Can you create a jsfiddle showing the issue?

**Comment by eMYKion** [comment]
If you look at the console log, then after some time you will see:

`found NaN element in camera.matrixWorld`

An example output of camera.matrixWorld.elements gives:

`[0.7071067690849304, 0.7071067690849304, 0, 0, -0.7071067690849304, 0.7071067690849304, 0, 0, 0, 0, 1, 0, NaN, NaN, -Infinity, NaN]`

https://jsfiddle.net/o1mntvzn/11/

**Comment by jostschmithals** [comment]
Just a short observation (without digging in the source code):

`camera.position.z` decreases ad infinitum in the fiddle. If it reaches the possible minimum -3.4…e+38 (32bit, “single precision”), the `z` value of the translation (`matrixWorld.elements[14]`) is set to `–Infinity`, and in consequence of this the other values in the last column are set to `NaN` (but the value of `camera.position.z` remains at -3.4…e+38).

In 85dev the limit is -1.8…e+308 (64bit, “double precision”), so that it is reached somewhat later.

**Comment by jostschmithals** [comment]
Just a short observation (without digging into the source code):

`camera.position.z` decreases more and more in the fiddle. If it reaches the possible minimum -3.4…e+38 (32bit, “single precision”), the `z` value of the translation (`matrixWorld.elements[14]`) is set to `–Infinity`, and in consequence of this the other values in the last column are set to `NaN` (but the value of camera.position.z remains at -3.4…e+38).

In 85dev the limit is -1.8…e+308 (64bit, “double precision”), so that it is reached somewhat later.

**Comment by Ashajoney** [comment]
I am also facing the same problem.
Can you please guide me with the solution.
I am using THREE.js 85 Version

**Comment by mpacary** [comment]
Got a very similar problem when doing (r101):
`object.rotation.set(new THREE.Vector3(0, 0, 0));` to reset an Object3D rotation, following a [this example](https://stackoverflow.com/a/30154137/488666).
At least half of the `matrix` and `matrixWorld` elements had `NaN` values.
Using `object.rotation.x = 0; object.rotation.y = 0; object.rotation.z = 0;` fixed the problem.
`object.rotation.set(0, 0, 0);` works fine too.

**Comment by jsantell** [comment]
> Got a very similar problem when doing (r101):
> 
> `object.rotation.set(new THREE.Vector3(0, 0, 0));` to reset an Object3D rotation, following [this example](https://stackoverflow.com/a/30154137/488666), but reading comments carefully it appears this syntax does not work since r96 (at least).
> 
> After such a call in r101, least half of the `matrix` and `matrixWorld` elements have `NaN` values. Object disappears from scene and nothing is shown about it in console (some deprecation warning could be welcome).
> 
> Using `object.rotation.x = 0; object.rotation.y = 0; object.rotation.z = 0;` fixed the problem.
> `object.rotation.set(0, 0, 0);` works fine too.

`Euler.prototype.set` expects 3 arguments for the x, y and z values; `object.rotation.set(new THREE.Vector3(0, 0, 0))` sets the Euler's X rotation to a Vector3, which will produce `NaN` values in the matrix. Note there are some slight differences between `Euler` and `Vector3`.

The `copy` method will work with this scenario as expected

**Comment by RylanSchaeffer** [comment]
I'm having a related issue with `.unproject(camera)`. It seems all of my camera's projectionMatrixInverse elements are NaN. Does anyone know why this is, or what the solution might be?

https://discourse.threejs.org/t/vector3-unproject-camera-returns-nan/29419/8

**Comment by Mugen87** [comment]
@RylanSchaeffer Please use the forum for asking at help.
