### ISSUE TITLE
Question to Plane.distanceToPoint()

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#10957]
Let's say i create a plane like this:

```javascript
const n = new THREE.Vector3( 0, 1, 0 );
const d = 2;

const plane = new THREE.Plane( n, d );
```

I would expect that the point `(0,2,0)` lies on the plane so `.distanceToPoint()` returns `0`. But the actual result is `4` (see https://jsfiddle.net/dcrvrsn4/3/). This happens because `.distanceToPoint()` adds the `constant` value to the result of the former dot product (see [here](https://github.com/mrdoob/three.js/blob/dev/src/math/Plane.js#L101)). I've always thought you need to perform a subtraction. Or is this assumption wrong?
```
distance = q * n - d
```
see https://github.com/juj/MathGeoLib/blob/master/src/Geometry/Plane.cpp#L228

**Comment by andreasplesch** [comment]
The plane.translate method subtracts (the normal parallel component of) the offset from d both in three and in MathGeoLib:

https://github.com/juj/MathGeoLib/blob/master/src/Geometry/Plane.cpp#L141
https://github.com/mrdoob/three.js/blob/dev/src/math/Plane.js#L221

Not sure what it means exactly but it seems inconsistent with distanceToPoint using different signs in both.

Is d is the distance of the plane from the origin (along the normal) ? It seems it is the negated distance (along the normal):

https://github.com/mrdoob/three.js/blob/dev/src/math/Plane.js#L35

MathGeoLib does not negate:

https://github.com/juj/MathGeoLib/blob/master/src/Geometry/Plane.cpp#L98

So perhaps MathGeoLib and three could have different semantics for d (or for which side of the plane has positive distances).

**Comment by jostschmithals** [comment]
The docs (https://threejs.org/docs/?q=plane#Reference/Math/Plane) say clearly, that d in the Plane constructor is "the **negative** distance from the origin to the plane along the normal vector."

**Comment by WestLangley** [comment]
We are using Hessian Normal Form. For a consistent implementation, you will have to fight it out. :)

http://mathworld.wolfram.com/HessianNormalForm.html

vs.

https://en.wikipedia.org/wiki/Hesse_normal_form

**Comment by Mugen87** [comment]
@jostschmithals Indeed, the docs are correct. I'm just surprised that such a basic issue is handled differently in libraries. 

> So perhaps MathGeoLib and three could have different semantics for d.

It would be nice to know why there are different semantics. Maybe this information could then be part of the `three.js` docs.

**Comment by andreasplesch** [comment]
My 2c worth are that d representing the negated distance just makes things more confusing. It is unlikely that there is a convincing justification (other than perhaps convention in some systems). I do not think mathworld or wikipedia say anything about signs. Of course not worth changing anything.

**Comment by WestLangley** [comment]
>The docs (https://threejs.org/docs/?q=plane#Reference/Math/Plane) say clearly, that, in three.js, d in the Plane constructor is indeed "the negative distance from the origin to the plane along the normal vector."

But that is not correct. It should say the _signed distance_ from the origin to the plane.

**Comment by jostschmithals** [comment]
@WestLangley Since the distance, which is passed into the Plane constructor, is a scalar and not a vector, and since (as far as I know) a distance in the meaning of a **scalar** is always positive by definition, I would have assumed that the term “negative distance” (in the docs) would be correct in this case.

Being happy with the doc's wording, I would have interpreted them like this:

```
// Case 1:
const n1 = new THREE.Vector3( 0, 1, 0 );
const d1 = 2;
const q1 = new THREE.Vector3( 0, 2, 0 );
const plane1 = new THREE.Plane( n1, -d1 );
console.log( plane1.distanceToPoint( q1 ) );  // output: 0

// Case 2:
const n2 = new THREE.Vector3( 0, -1, 0 );
const d2 = 3;
const q2 = new THREE.Vector3( 0, -3, 0 );
const plane2 = new THREE.Plane( n2, -d2 );
console.log( plane2.distanceToPoint( q2 ) );  // output: 0
```

Up to now I know “signed distances” (in the meaning of distance **vectors**) only in association with “inside”/”outside” situations. But perhaps this is a gap in my knowledge?

**Comment by andreasplesch** [comment]
Using the Hessian normal form it is natural to calculate a signed distance of a point to a plane. The sign is relative to the direction of the normal. I think in most cases the equation is written so that a positive distance means that the point is on the side of the plane the normal is pointing towards.

But I think the documentation is correct in that d in three is actually the negated distance along the normal. That means a positive d produces a plane which is offset from the origin in the reverse direction of the given normal.

**Comment by sverbist** [comment]
Sorry for necroing this issue but I cannot make sense of it. The documentation currently does not state anything about a negated distance (and why would we use a 'negated' distance in the first place?)

The documentation and implementation of Plane.distanceToPoint() seems to follow http://mathworld.wolfram.com/HessianNormalForm.html quite well. However, http://www.nabla.hr/Z_MemoHU-022.htm shows the same equation subtracting the constant instead of adding. The latter seems to make more sense to me since the dot product should calculate the distance from the origin so you'd have to subtract the constant when the constant is defined as the distance of the plane from the origin in the direction of the normal.

That means I expect that if a plane is given by the vector (1,0,0) and constant 2, and my point is at (3, 0, 0), I expect the plane to be offset by 2 in the positive x-direction meaning the distance between point and plane should be 1, not 5 as three.js suggests.

At the very least, the description of the constant is very unclear to me :(

**Comment by mrdoob** [comment]
How do you think it should be rephrased to be more clear?

**Comment by sverbist** [comment]
> 
> 
> How do you think it should be rephrased to be more clear?

Well that depends on what exactly Plane.constant is. I think I'm rather thrown off and probably misunderstanding the explanation of the distance calculation in the two links I provided where one added and the other subtracted this constant.
How I currently interpret it is that the constant indicates the distance of the plane from origin in the direction of the plane normal. If this understanding is correct, then the implementation seems to be erroneous to me as it should subtract the constant value instead.
If the implementation is correct, then the documentation stating that the constant is the offset from origin in the normal direction seems erroneous.

I am not yet convinced the error lies in the code but rather my understanding. Though I found this issue where @Mugen87 in the original post described exactly what I would expect from the equation and description and I think this issue was closed mostly because the following:

> 
> 
> The docs (https://threejs.org/docs/?q=plane#api/math/Plane) say clearly, that, in three.js, d in the Plane constructor is indeed "the **negative** distance from the origin to the plane along the normal vector."

However, the documentation does not (or no longer) describe that the constant is the negative distance along the normal vector.
