### ISSUE TITLE
Bug in the SVGRenderer

### ISSUE THREAD

**Issue by anton-hexagons** [mrdoob/three.js#11027]
Stumbled upon a bug in the SVGRenderer.

Verison:
THREE.SVGRenderer 85dev

Example:
http://hexagons.se/demos/_vec_rec/

Bug:
Error: <svg> attribute transform: Expected number, "translate(NaN,NaN)".
(anonymous) @ SVGRenderer.js:234
traverseVisible @ three.js:10823
traverseVisible @ three.js:10829
render @ SVGRenderer.js:223
render @ main.js:152
(anonymous) @ main.js:155

**Comment by mrdoob** [comment]
Do you mind describing what you're trying to do?

**Comment by jostschmithals** [comment]
The reason for this error message seems to be: If the z position of a THREE.SVGObject is 0, there will be a division by 0 in line 228 of the SVGRenderer, so that the attribute can’t be set in line 234 of the Renderer.

You can easily reproduce this in the svg_sandbox.html example: 

If you replace lines 163-165 in svg_sandbox.html by `object.position.set(0, 0, 0)`, you get exactly the same error.

https://github.com/mrdoob/three.js/blob/dev/examples/svg_sandbox.html#L163-L165

**Comment by WestLangley** [comment]
In addition to the fact that `Projector` and `SVGRenderer` are duplicatiing code, the problem is that the camera matrices are not updated prior to being used in `SVGRenderer.render()`.

`Projector.projectScene()` is doing this

		if ( scene.autoUpdate === true ) scene.updateMatrixWorld();
		if ( camera.parent === null ) camera.updateMatrixWorld();

		_viewMatrix.copy( camera.matrixWorldInverse.getInverse( camera.matrixWorld ) );
		_viewProjectionMatrix.multiplyMatrices( camera.projectionMatrix, _viewMatrix );

`SVGRenderer.render()` is doing this

		_viewMatrix.copy( camera.matrixWorldInverse.getInverse( camera.matrixWorld ) );
		_viewProjectionMatrix.multiplyMatrices( camera.projectionMatrix, _viewMatrix );

		_renderData = _projector.projectScene( scene, camera, this.sortObjects, this.sortElements );

@mrdoob Perhaps some refactoring is in order?

**Comment by anton-hexagons** [comment]
@mrdoob So what I'm trying to do is to render and svg object, I guess I might have mixed up the SVGRenderer for an importer. Can you render .svg files with the WebGLRenderer?

@jostschmithals You're right, setting (object.position.z = 0.001) clears the error.

Tho I'm still having trouble rendering the svg file, I'll post in the forum:
https://discourse.threejs.org/t/stumbled-upon-an-bug-in-the-svgrenderer/82

**Comment by mrdoob** [comment]
https://discourse.threejs.org/t/stumbled-upon-an-bug-in-the-svgrenderer/82/8
