### ISSUE TITLE
Docs: Strange behavior with file protocol

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#11100]
##### Description of the problem 

It seems that #11078 introduces a little problem with Chrome. It was always possible to navigate through the docs  via the `file` protocol. When you now click on a link on the side navigation, you see the following:

![image](https://cloud.githubusercontent.com/assets/12612165/24577370/efe2ce6a-16cc-11e7-8dde-2bf41a405e45.png)

I'm also getting the following error in `page.js` at line [53](https://github.com/mrdoob/three.js/blob/dev/docs/page.js#L53).

> VM123 page.js:53 Uncaught TypeError: Cannot read property 'innerHTML' of null

BTW: I'm not having this problem with Firefox 52.

Tested with: Ubuntu 16.04, Chrome 56.0.2924.76

##### Three.js version

- [x] Dev
- [ ] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by jostschmithals** [comment]
I can reproduce this on Windows 10.
Browsing the docs locally works in Firefox, but not in Chrome.
I will have a look at it.

**Comment by jostschmithals** [comment]
At the first glance it seems to be no difficult problem.

Everything should work, if the redirection (which is not relevant for local use) is only made, 
`if (window.location.protocol !== 'file:')`.

If this quick diagnose is true, I will change it in this way.

**Comment by RemusMar** [comment]
> I'm also getting the following error in page.js at line 53.
> VM123 page.js:53 Uncaught TypeError: Cannot read property 'innerHTML' of null
> BTW: I'm not having this problem with Firefox 52.

When it comes to local files, Firefox was always better than Google Chrome.
Honestly, I did never like Chrome.

**Comment by jostschmithals** [comment]
FF and Chrome behave differently on local use - that's true. For example you can run the loader examples like `examples/webg_loader_obj.html` locally in FF, but not in Chrome.

Concerning the docs I had not expected a difference, and I had not yet recognized it, since I am always running a local server.

The special reason in the docs is that in Chrome `window.frameElement` is `null` for security reasons, if the page is run locally: http://stackoverflow.com/questions/17950598/using-iframe-with-local-files-in-chrome

But fortunately the problem can be easily solved as i wrote above.

**Comment by jostschmithals** [comment]
I’ve noted an additional security restriction when running local files in Chrome and without a local server:

When running the docs directly from the file system in Chrome, the links from an iframe to somewhere else in the site are blocked for security reasons. But this problem is not new and has nothing to do with the recent changes of the docs (the current docs behave the same). I can’t imagine a workaround for this.

But there is always the option to use FF or a local server+Chrome – or to browse the docs online and benefit from frequent updates ;)

**Comment by RemusMar** [comment]
> the links from an iframe to somewhere else in the site are blocked for security reasons 

Google Chrome is a piece of spyware by itself.
So that "security reasons" does not make any sense.

**Comment by Mugen87** [comment]
> But this problem is not new and has nothing to do with the recent changes of the docs (the current docs behave the same). I can’t imagine a workaround for this.

Well, you could navigate via the sidebar before #11078 was merged.

**Comment by jostschmithals** [comment]
> Well, you could navigate via the sidebar before #11078 was merged

I will restore this possibility as mentioned above. Have tested it and seems to work well.
