### ISSUE TITLE
shadowmap bug?!

### ISSUE THREAD

**Issue by jyunming-chen** [mrdoob/three.js#11158]
##### Description of the problem 

simple shadow map setting, with a spotlight on +Y axis, animating with variable height

The spotlight shines a block, which should cast shadow on the floor (on the XZ plane)

When the light is above 500, the shadow disappears;
if the light is below 500, the shadow is normal (as expected).
if the light is right at (0,500,0), you can see that the shadowMap is flawed ...

jsfiddle: https://jsfiddle.net/georgeChen/g4pnkv1s/

##### Three.js version
- r83

##### Browser
same behavior for Chrome and Firefox
- [x] Chrome
- [x] Firefox

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jostschmithals** [comment]
It seems to work, if you set spotLight.distance to (for instance) 1500 - even if the plane is not in the shadow camera's frustum. 

I don't know whether this makes sense ...

**Comment by Mugen87** [comment]
As a quick fix, check out this new [fiddle](https://jsfiddle.net/g4pnkv1s/15/). You have to set the `distance` of the spotlight to a high valu. So settings the camera values directly (like in your example) won't work because they will be overwritten in the `.update()` method of `SpotLightShadow`. See this issue for more information: #7690

Maybe we can update the `far` value only if distance is not zero (see [here](https://github.com/mrdoob/three.js/blob/dev/src/lights/SpotLightShadow.js#L25)) . I think this would solve the problem. So instead of:
```javascript
var far = light.distance || 500;
```
we do
```javascript
var far = ( light.distance !== 0 ) ? light.distance : 500;
```

**Comment by mrdoob** [comment]
@Mugen87 sounds good!

**Comment by mrdoob** [comment]
Also... #10668
