### ISSUE TITLE
PLYLoader in src/loaders

### ISSUE THREAD

**Issue by edap** [mrdoob/three.js#11201]
Hi, I'm working on a project where I need to load a .ply mesh. I'm using es6 and the three package provided through npm. Unfortunately, there is no npm package for the PLYLoader. Before to create a new one, I would like to ask if you would accept a PR that convert https://raw.githubusercontent.com/mrdoob/three.js/99392073204484a3597a5ca78b8af42fd87cdd72/examples/js/loaders/PLYLoader.js to the js style (using `import`, `export` ecc) that is used for the other loaders.
If there is some reason for which it is better to keep the PLY loader out of the three supported loaders?

Last but not least, thank you for your works ;)

**Comment by Mugen87** [comment]
> If there is some reason for which it is better to keep the PLY loader out of the three supported loaders?

One philosophy of `three.js` is to keep the library as small as possible. If we start including `PLYLoader` into the core, we could also include `STLLoader`, `GLTF2Loader`, `FBXLoader` and so on. Because all these loaders are use case specific, it's basically better to keep the mentioned loaders out of the core.

**Comment by edap** [comment]
I see. Thanks
