### ISSUE TITLE
r85 Garbage Collection 

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#11258]
The current build (85) seems to have a bit of a problem with garbage collection. I am getting some pretty bad frame jitter compared to the 85dev version I have (file dated 2/7/17). I will work on setting up a fiddle once I figure out where to begin (my app is fairly involved) and get enough free time.

I did take these performance screenshots in chrome (58) on Win7 64. These tests involved running around in a circle in one of my game zones for 10 seconds. I've ran the same test 5 times for each version and the results remained consistent.

**r85dev** (as is on 2/7/17)
![85dev](https://cloud.githubusercontent.com/assets/6549763/25557672/9f47dbb0-2cdb-11e7-8df5-334af82a3ac3.PNG)

**r85**
![85](https://cloud.githubusercontent.com/assets/6549763/25557673/b09e2b4e-2cdb-11e7-80b7-642c6cd68e5a.PNG)

**r72** (my current production build)
![72b](https://cloud.githubusercontent.com/assets/6549763/25557738/0608aeaa-2cdd-11e7-8dc2-f1f4942a71fa.PNG)

**Comment by mrdoob** [comment]
A jsfiddle would be great! 👌

**Comment by titansoftime** [comment]
Working on it. I found what to demo now as I have narrowed the problem down to Skeletal Animations.

**Comment by titansoftime** [comment]
Fiddle: https://jsfiddle.net/titansoftime/9fya48rc/

Notes:
This fiddle demonstrates the reduced performance and much increased garbage collection frequency in r85 compared to a version of r85 dated 2/7/17 when using a variety of SkinnedMeshes.

If only using one type of geometry, a much higher model count is needed to reproduce performance issue. By default several geometry types are used. Model diversity can be modified adjusting line# 134 and 135. Total model count is adjustable on line#4.

Commenting out line#60 (plays animation) or line#254 (mixer update call) does not improve  performance. The presence of the SkinnedMesh in the scene is enough to cause the issue.

I have the r85dev source which performs great commented out in the html section.

**Comment by titansoftime** [comment]
I did further testing of the fiddle on my work PC (Intel integrated crap). Similar results.

**r85dev**
![85dev](https://cloud.githubusercontent.com/assets/6549763/25628323/6ab0cc02-2f2b-11e7-89c1-a2da927ea555.PNG)

**r85**
![85](https://cloud.githubusercontent.com/assets/6549763/25628331/75d60c3c-2f2b-11e7-8f84-445e5e5880bc.PNG)

**Comment by aardgoose** [comment]
Can you try reverting 0baf2633d45645454e6049c005c697874d225499 from three r85 from your copy.

A quick look at memory allocations shows a lot of Number objects being allocated by Matrix4.multiplyMatrices() in your fiddle, which now uses plain JS arrays of Numbers instead of a fixed size Float32Array object since the change above.

This change was on 2/9/2017 (US date format), which fits with your observations.

**Comment by aardgoose** [comment]
Issue easily observed in "Chrome/Devtools/Memory/Allocation Timeline"  with the example  "animation / skinning / morph".

with Matrix4() using JS Array for elements - steady allocation "rate"  50KB.
with Matrix4() using Float32Array() - steady allocation "rate" of 1KB.
(no other changes, manually changed elements allocation)


(Chrome 58.0.3029.96)

**Comment by Usnul** [comment]
mentioned commit, I'm not sure why usage of Float64Array was not considered.

**Comment by WestLangley** [comment]
@Usnul It was, actually. See https://github.com/mrdoob/three.js/pull/10702.

**Comment by titansoftime** [comment]
Unfortunately this commit degrades performance to the point where I cannot use this build. I hope this commit is reconsidered at some point.

**Comment by aardgoose** [comment]
@titansoftime  Does this issue also hit you with other browsers, I've only looked at Chrome.

**Comment by titansoftime** [comment]
@aardgoose Hmm. Firefox seems to be ok. I'm not super familiar with the Firefox memory profiler, but usage seems relatively consistent between 85dev and 85. Oddly though (maybe a separate issue) randomly (as I can tell) GC goes crazy in both versions in Firefox.  Haven't had time to look further into it.

Chrome definitely is having issues with this.

**Comment by aardgoose** [comment]
Since Chrome does not expose memory usage or GC stats to page scripts, I wonder if it is worth making some benchmarks that run in Node.js which does provide usable memory & GC stats to catch this sort of heap consumption regression?

Not something I have played with but could look at.

@titansoftime @mrdoob

**Comment by Usnul** [comment]
@aardgoose 
I'm not sure what stats you are referring to. To me it seems quite straight forward - run the renderer and collect a profile with native functions enabled:
![image](https://cloud.githubusercontent.com/assets/5939063/26330694/789728a2-3f4d-11e7-831c-680746bf7d0f.png)

![image](https://cloud.githubusercontent.com/assets/5939063/26330698/8137dbf0-3f4d-11e7-8f3c-72bdeb9a1f6a.png)

**Comment by aardgoose** [comment]
@Usnul  thanks, it really isn't garbage collection stats that I was looking at, rather than heap expansion rate, which Chrome makes visible with the memory allocation timeline devtool, which I don't think firefox has an equivalent to.

However, on the good news front...

/ping @titansoftime @mrdoob it appears that V8 in Chrome canary (v60 to be) is much better and the heap problems exposed with skinned meshes seem to have gone (from a quick look only) and heap use is similar to the typedArray matrix performance.

**Comment by titansoftime** [comment]
Google has released Version 60.0.3112.90 (Official Build) (64-bit)

Results:
![image](https://user-images.githubusercontent.com/6549763/29238803-d646d8dc-7f01-11e7-902b-2dfa459f949e.png)

Looks like everything is ok =]
