### ISSUE TITLE
Problem with smoothing groups in OBJ files

### ISSUE THREAD

**Issue by eng1neer** [mrdoob/three.js#11270]
I'm experiencing the problem with obj models exported from 3ds max when faces are shaded flat even though in the 3ds max they are smooth.

I noticed that in https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader.js#L618 smooth shading is applied only when smoothing group is exactly "1" or "on". Shouldn't it be smooth when any values is specified except "off"?

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kaisalmen** [comment]
Hi, I confirm the observation.
r85 now includes `OBJLoader2` which handles this correctly: Flat smoothing defined by "s 0" or "s off" is supported and Multi-Material is created when one object/group defines both smoothing groups equal and not equal to zero. See:
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader2.js#L600-L618
You can give it a try. Drop in replacement is possible for the simple load example, but it has additional options:
https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_obj2.html

@mrdoob and @jonnenauha shall we fix `OBJLoader`? What is your opinion on this?

**Comment by jonnenauha** [comment]
I think one loader doing it right should suffise :) Although sounds like a trivial fix, but I don't at least have time to tackle these atm.

**Comment by kaisalmen** [comment]
This is the fix:
```
state.object.smooth = ( value !== '0' && value !== 'off' );
```
But, the question is whether it works properly with complex smoothing group / material assignments in the OBJ and if it does not work how to proceed? I will investigate ...

**Comment by kaisalmen** [comment]
Investigations with cubes.obj/cubes.mtl revealed that `OBJLoader` does currently not allow to have flat and smooth shading within the same material definition for a specific object. Multi-materials are created if multiple usemtl are set during face definition of  an object, but if the smoothing group is altered it uses the last one defined and this results in either flat or smooth shading depending on the value.
`OBJLoader2` supports this distinction.

**Comment by chiragbhuva** [comment]
I am getting the surface shown in the picture that i am attaching below ,I want triangle with the same color and texture Could you please guide me on the same. 
and one more thing ,This is because the triangles are not oriented consistently which only makes sense if the output is a true oriented surface without any artifact.if any one suggest me which visualization tool where it shows the triangles without considering orientation in WPF, i have used helix toolkit in WPF but it gives same result [this is 3d model][1]
![capture](https://cloud.githubusercontent.com/assets/29192700/26774191/b3d5f0f2-49ec-11e7-837c-f680ff1885f1.PNG)
