### ISSUE TITLE
io_three armature exporting to much animation info

### ISSUE THREAD

**Issue by centerionware** [mrdoob/three.js#11395]
##### Description of the problem 
The exporter dumps all the pose animations into every objects geometry, even when the bones referenced in the pose animation aren't part of the armature for that particular object.
It doesn't appear to really cause problems other than bloat. (More multi-armature testing)

[multi_armature_test_scene.zip](https://github.com/mrdoob/three.js/files/1030211/multi_armature_test_scene.zip)

##### Three.js version

- [ x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by manthrax** [comment]
I've hit this as well.

For every mesh attached to an armature, a full set of all the armatures actions are exported for each mesh.

I have worked around this by writing my own preprocessor that imports the exported mesh, and saves out the animations and skeleton+meshes separately. and then in my engine, I load the animated mesh, and the animations separately.

This results in a pretty massive space savings, and also makes it easier to share animations amongst multiple characters/multiple exports.

For instance on one of our main characters, the default export was clocking over 100 megs...

Using the preprocessor, gets the size down to around 10 megs.

Making your own preprocesser also lets you preprocess some things like adjusting material settings, and culling other things you don't want.

But I agree this should be fixed in the exporter.

**Comment by donmccurdy** [comment]
Trying to test this sample model with https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/166 and can't get the animation to play in Blender at all... do I need to do something particular beyond selecting a mesh, action, and hitting play?

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
