### ISSUE TITLE
Binary FBX taking a very long time to playback

### ISSUE THREAD

**Issue by FuzzyWobble** [mrdoob/three.js#11398]
##### Description of the problem 

[example of bug](https://fuzzy.cc/ararar/three-dev/examples/webgl_loader_fbx.html).
I am using a custom FBX binary animation file I have created.
It eventually loads and works, but takes ages. (zoom out to see).
(my first day using three.js... so possible i am doing something dumb here...)

##### Three.js version

- [x ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by FuzzyWobble** [comment]
takes about 4mins after loading the model.
then console shows "/ararar/models/viv.fbx 1 1".
at which point it is drawing the animation.

**Comment by takahirox** [comment]
Do you have ascii version file?
I wanna clarify if it's a binary specific issue.

**Comment by FuzzyWobble** [comment]
@takahirox 
Sorry I do not. This file was exported directly from Mixamo as FBX Binary.

**Comment by FuzzyWobble** [comment]
[viv_ascii.fbx.zip](https://github.com/mrdoob/three.js/files/1033273/viv_ascii.fbx.zip)
@takahirox I was able to export ASCII from Blender. File size went WAY up 0__0

**Comment by takahirox** [comment]
Loading time is still very long with the ascii file?

**Comment by FuzzyWobble** [comment]
"TypeError: Cannot read property 'itemError' of undefined"
:(

**Comment by FuzzyWobble** [comment]
My first day using three.js... having a lot of weirdness trying to convert files in Blender *__*

FBX Binary is extremely desirable because the file size is so manageable.

**Comment by takahirox** [comment]
OK, let me check the binary later.

**Comment by FuzzyWobble** [comment]
@takahirox any luck with that Binary? :U thanks x1000

**Comment by takahirox** [comment]
@FuzzyWobble can you share the binary FBX file?

**Comment by jostschmithals** [comment]
@takahirox Since it seems in different places that you are currently working on the FBXLoader again I think it is better that I close [my PR for the same file](https://github.com/mrdoob/three.js/pull/11483) so that nothing will interfere.

So please consider these two issues in your next PR (error handling doesn’t work properly for two reasons):

1.	In the parse function `self` points to the window object, so that lines 103 and 110 don’t work. It seems that these two lines could be simply deleted (I understand @mrdoob’s [suggestion](https://github.com/mrdoob/three.js/pull/11483#discussion_r121542313) in this manner, too) because errors in the parse function are already caught in the load function.

2.	The url is not passed to the parse function, but it is used for the message in line 111 (and in lines 103 and 110, which can be deleted).

**Comment by FuzzyWobble** [comment]
@takahirox 
here is the fbx -> fuzzy.cc/ararar/models/viv.fbx

**Comment by takahirox** [comment]
Hm, seems like parsing bones spends a long long time.
Let me take a look closer...

**Comment by takahirox** [comment]
OK, I've confirmed changing bone parsing algorithm improves the performance a lot. I'll make a PR later.

**Comment by FuzzyWobble** [comment]
Just a general question. I was pursuing Binary FBX because it seemed to compress the best. Is this true? Or is there another format that will compress 3D/color/animation better?

**Comment by mrdoob** [comment]
Looks like #11587 fixed this 🎉

**Comment by takahirox** [comment]
@FuzzyWobble Sorry, I'm not familiar with many formats. You'd better to ask that in other places.
