### ISSUE TITLE
Blender exporter bug 

### ISSUE THREAD

**Issue by Flyover-ArtSk** [mrdoob/three.js#11403]
##### Description of the problem 

After i tryed to export my scene:
![image](https://cloud.githubusercontent.com/assets/1798696/26522943/40106b22-4314-11e7-94aa-e2dd2e81c710.png)

I got this:
![image](https://cloud.githubusercontent.com/assets/1798696/26522949/4d91739a-4314-11e7-9b2a-d6aacf76f5d3.png)
![image](https://cloud.githubusercontent.com/assets/1798696/26523008/5f964af6-4315-11e7-9672-f28c0e012001.png)

What the hell?
I got cylinder position/rotation hell after added Difference
I got cube position/rotation hell after extruded selection.

##### Blender version

- [x] 2.78

##### Three.js version

- [x] Dev
- [x] Master

##### Browser

- [x] Chrome

##### OS

- [x] Windows

##### FIles and code
[scene.txt](https://github.com/mrdoob/three.js/files/1033666/scene.txt)

```
var loader = new THREE.ObjectLoader();
loader.load( 'models/scene.json', function ( scene ) {
    var material = new THREE.MeshLambertMaterial({
        color: 0x00ffff
    });

    scene .traverse(function (child) {
        if (child instanceof THREE.Mesh) {
            child.material = material;
        }
    });

    scene = scene;
    scene.add(axis);
    render();
}
```

**Comment by Flyover-ArtSk** [comment]
Before i deffered cylinder in centre (and extruded cube) - all was ok

**Comment by daarong** [comment]
Other than the new bug #10804 I tend to have a pretty smooth workflow exporting from blender to threejs... however I always apply modifiers and "apply" position / rotation / scale before I export.  I even have a check in my javascript to throw errors when I forget to apply position / rotation / scale in blender.  If you can do those two things it might help alleviate issues

**Comment by Flyover-ArtSk** [comment]
Thx for answer! Can you say how to apply position / rotation / scale ?

**Comment by daarong** [comment]
To "apply" position / rotation / scale in blender...

1. select your object
2. ensure you're in object mode
3. in the main modeling panel (aka "3D View") go to the menu item Object > Apply

Note that doing "apply" is essentially destructive, because you lose non-nominal values for scaling, rotation and position.  If "apply" fixes your problem but P R or S info is necessary for your model in threejs, then you may have to get creative or do some extra transforms after importing into your threejs project.

**Comment by mrdoob** [comment]
> ```scene = scene;```

🤔

**Comment by Flyover-ArtSk** [comment]
Part of fast ad dirty code). It was written for test looking.
```
var scene = ...;
loader.load( 'models/scene.json', function ( scene ) {
   scene = scene;
});
```

**Comment by centerionware** [comment]
for loading without applying location - still needs applying rotation and scale: 
`scene.traverse(function(child){if(child is mesh or skinned mesh) child.rotateZ(3.14);......})`
See #11329

**Comment by manthrax** [comment]
I was just digging through the blender exporter.

There are a number of coordinate swaps and axis swaps that occur under different circumstances.

"Applying" your rotations, translations, and scalings, resets all the transforms to the identity, by transforming the actual geometry. This gets around these somewhat ambigouous transformation problems because all the parts are then exported with a position/rotation/scale of 0, 0, and 1.

I would really like to take a stab at removing all the coordinate swapping in the exporter, so that vertices and rotations map 1 to 1 with what is exported. I have a local branch where I have done this with good results. Let me know if there is still interest in fixing this.

**Comment by manthrax** [comment]
#11803

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
