### ISSUE TITLE
Using the sea3d loader in threejs

### ISSUE THREAD

**Issue by Shehrbanu** [mrdoob/three.js#11408]
This is the code i am using for saving the model of a mascot turtle,given in threejs examples.When I update the position of morph in render function, it sayya that the properties of var morph not defined.
```javascript
loader.load( './models/sea3d/mascot.tjs.sea');
loader.onComplete = function(e){
   morph = this.loader.getMesh("mascot");
   morph.position.set(0,0,0);
   scene.add(morph);
}
```

**Comment by Mugen87** [comment]
Try this:
```javascript
var mesh = this.loader.getMesh( 'Mascot' );
```
The name of the mesh starts with a capital letter. 

BTW: You can view all object names of the loaded model if you set a breakpoint right [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/sea3d/SEA3DLoader.js#L1504) and inspect `this.objects` in your debugger.

**Comment by Shehrbanu** [comment]
Still not working.

**Comment by Mugen87** [comment]
Actually morph is a bad choice for a variable name. This is better:
```javascript
var mesh = this.loader.getMesh( 'Mascot' );
console.log( mesh.position );
````
I've tested this on my computer and it works. So there are no problems with the model or the `. getMesh()` method. If you need help in order to understand `three.js` please use stackoverflow or the [forum](https://discourse.threejs.org/).
