### ISSUE TITLE
Three.js Error: no keyframes in track named [objectname].position

### ISSUE THREAD

**Issue by xbeat** [mrdoob/three.js#11427]
##### Description of the problem 

Exporting from Blender [this animation](https://sport.xbe.at/jsonPlayer/index.html) in three.js format i get this error: "Error: no keyframes in track named Mesh.position". [The Blender file](https://sport.xbe.at/jsonPlayer/Player_animated_separated.blend) have all the orphan data purged. I noticed that at bottom of [exported json file](https://sport.xbe.at/jsonPlayer/Player_animated_separated.json) there's a section with a empty animations:

    "animations":[{
        "tracks":[{
            "type":"vector3",
            "name":"Mesh.position",
            "keys":[]
        },{
            "type":"vector3",
            "name":"Mesh.scale",
            "keys":[]
        },{
            "type":"quaternion",
            "name":"Mesh.quaternion",
            "keys":[]
        }],
        "name":"default",
        "fps":30
    }]

If removed all worked correctly: it's a bug in the exporter or some parameters that i missing in the Blender file?

Parameters used for exportation:

![exportparams](https://cloud.githubusercontent.com/assets/20385856/26642657/df79ad64-462e-11e7-91df-554f2603c3e8.png)

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [x] Safari
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Awea** [comment]
@xbeat I got the same problem when trying to export a model with an armature animation children of the mesh:

![step1](https://user-images.githubusercontent.com/630023/33122273-12c0c186-cf77-11e7-9739-38e250b0d24b.png)

To fix this you can remove the animation from your mesh by selecting the mesh in Object Mode and click the X in the Action Editor while in Animation Layout:

![step2](https://user-images.githubusercontent.com/630023/33122415-73372726-cf77-11e7-84f7-6ebf92146de0.png)

**Comment by mrdoob** [comment]
Have you guys tried exporting to gltf instead?

**Comment by enjinstudios** [comment]
Any solutions to this? The keys in the tracks always shows up empty.

` "animations":[{
        "name":"default",
        "tracks":[{
            "type":"vector3",
            "name":"Gunnar.position",
            "keys":[]
        },{
            "type":"vector3",
            "name":"Gunnar.scale",
            "keys":[]
        },{
            "type":"quaternion",
            "name":"Gunnar.quaternion",
            "keys":[]
        }],
        "fps":24
    }]`

**Comment by donmccurdy** [comment]
> Have you guys tried exporting to gltf instead?

Tested this model in two Blender glTF exporters, with THREE.GLTFLoader:

https://github.com/KhronosGroup/glTF-Blender-Exporter/ — only the active animation exports, as [multiple actions are not yet supported](https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/112). But otherwise everything looks right.

https://github.com/Kupoman/blendergltf — all animations export correctly, if you select "all available" in the export settings. Unfortunately materials do not export correctly, I had to delete them to get the model to render. The author has been very responsive to issues, so if you file an issue you may get some help with that.

Once you have a model you can test the animations easily with https://gltf-viewer.donmccurdy.com/.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
