### ISSUE TITLE
Playing two animations on one mesh doesn't behave correctly

### ISSUE THREAD

**Issue by KyleNBurke** [mrdoob/three.js#11455]
##### Description of the problem 

There seems to be a bug with mixing different animations for one skinned mesh. Using blender I made a simple mesh with an armature.

![Imgur](http://i.imgur.com/5Jm5W7N.png)

Gave it an idle animation.

![Imgur](http://i.imgur.com/XNFGOhs.gif)

And a throw animation.

![Imgur](http://i.imgur.com/fKrb0mr.gif)

If the throw animation plays while the idle animation is playing, it seems to reset the idle action. Also, it's strange that the arm doesn't start all the way down like it should.

![Imgur](http://i.imgur.com/FRnKEjz.gif)

Here's is a minimal code example.

```
var scene = new THREE.Scene();
var camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

var renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

camera.position.set(2, 1, 0.5);
camera.lookAt(new THREE.Vector3(0, 1, 0));

var clock = new THREE.Clock();

var loader = new THREE.JSONLoader;
var mixer;
var idleAction;
var throwAction;
var set = false;

loader.load("./player.json", function(geometry) {
    var material = new THREE.MeshBasicMaterial({skinning: true});
    var skinnedMesh = new THREE.SkinnedMesh(geometry, material);
    scene.add(skinnedMesh);

    mixer = new THREE.AnimationMixer(skinnedMesh);
    idleAction = mixer.clipAction(geometry.animations[0]);
    throwAction = mixer.clipAction(geometry.animations[1]);
    throwAction.setLoop(THREE.LoopOnce);
    idleAction.play();
    set = true;
});

document.onmousedown = function() {
    throwAction.reset();
    throwAction.play();
}

function render() {
    if(set) {
        mixer.update(clock.getDelta());
    }

    renderer.render(scene, camera);
    requestAnimationFrame(render);
};

render();
```

And [here is the source](http://www.mediafire.com/file/o8n41evzo3t5uq3/animationMixTesting2.zip).

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jostschmithals** [comment]
This is not a bug in three.js. Seems that there went something wrong with the export to JSON (wrong settings?).

three.js does exactly what the JSON file says: There are keyframes for each bone in both animations. Hence the legs are reset in the throw animation, and the arms are rotated in the idle animation (BTW: Wouldn't it be better “walk” instead of “idle”?).

Here is a JSON file where I've simply emptied these keys: [player.zip](https://github.com/mrdoob/three.js/files/1057397/player.zip). It works as expected.

**Comment by KyleNBurke** [comment]
@jostschmithals Okay I see. What settings should be used with the exporter to ensure a proper .json file is created?

Also, yeah it would make more since to have the idle animation be a walk animation but I was just making some easy animations to simplify the problem, didn't think about it too much.

**Comment by jostschmithals** [comment]
I have no detailed experience with blender. So I only wanted to isolate the problem saying that it can’t be a bug in the three.js animation system, but must have to do something with the blender source or the exporter.

It could be 
- that your source file is not completely valid (it is quite common that problems, e.g. caused by a non-proper reset of the model before rigging, don’t occur already in the modeling software but only in the software to which the model is exported), 
- or that the export settings have to be adjusted (?), 
- or that the reason is a bug in the exporter.

Perhaps it would be the best if you close this issue, ask on http://discourse.threejs.org/ or stackoverflow, or, if this doesn't help and you assume it is an exporter bug, create a new bug report issue with a blender exporter related title.

**Comment by KyleNBurke** [comment]
@jostschmithals Okay thanks for the help!
