### ISSUE TITLE
Mesh.raycast ignores multimaterial

### ISSUE THREAD

**Issue by saviski** [mrdoob/three.js#11470]
##### Description of the problem 

The `checkIntersection` function inside `Mesh.checkIntersection` method only checks the material.side, ignoring the fact that the material can be an array.

This prevents the Raycaster from intersecting back faces when `material.side == DoubleSide` using a different material for each face

Having 
```
mesh.material = [material1, material2, ...]
mesh.material.side = THREE.DoubleSide;
```
solves the issue but is not ideal.

##### Three.js version

- [x] r85

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by TyLindberg** [comment]
Are you having this issue with both BufferGeometry and Geometry? Looking at the code, it seems like Geometry accounts for the possibility of multiple materials.

**Comment by saviski** [comment]
I was using a BufferGeometry

**Comment by Arnache** [comment]
Having the same problem on r86. Fix should be easy:

on line 150 of Mesh.js change
function checkIntersection( object, raycaster, ray, pA, pB, pC, point ) {
to
function checkIntersection( object, material, raycaster, ray, pA, pB, pC, point ) {

make line 153 empty

On line 351 replace
intersection = checkIntersection( this, raycaster, ray, fvA, fvB, fvC, intersectionPoint );
by
intersection = checkIntersection( this, faceMaterial, raycaster, ray, fvA, fvB, fvC, intersectionPoint );

on line 188 change
var intersection = checkIntersection( object, raycaster, ray, vA, vB, vC, intersectionPoint );
to
var intersection = checkIntersection( object, object.material, raycaster, ray, vA, vB, vC, intersectionPoint );

I have not tested, because I am using three.min.js and will not try to edit the minimized code.

**Comment by TyLindberg** [comment]
Fixed as of #11594?

**Comment by mrdoob** [comment]
I think so.

**Comment by Mugen87** [comment]
The raycast does not work with `BufferGeometry`, see #11860
