### ISSUE TITLE
SSAO bug on mobile

### ISSUE THREAD

**Issue by vchizhov** [mrdoob/three.js#11488]
There's a graphics artifact with the SSAO in the postprocessing examples (as well as bhouston's implementation of SAO) on older mobile devices. Both are caused due to lack of precision on some of these devices. The bug can be fixed by setting the depth sampler's precision to high. Here's a link to a similar issue with SSAO:  [ssao artifact](https://computergraphics.stackexchange.com/questions/2155/ssao-artefacts-on-iphone-opengl-es).

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x] Android

**Comment by hemant1612** [comment]
Hi I want to fix this issue.What I need to do!

**Comment by mrdoob** [comment]
On the referred link they propose this solution:

> Resolved by adding precision highp sampler2D to my shaders.

**Comment by vchizhov** [comment]
It only needs to be added for the depth sampler, also if you still see artifacts on some devices then float's precision also needs to be set to high.

**Comment by makc** [comment]
wait, we have ssao now? why #8576 is still open?

**Comment by vchizhov** [comment]
It's fake ssao as noted by bhouston. It's just called ssao in the three js postprocessing examples, but it's still screen space and approximates some kind of fake occlusion.

**Comment by cnspaha** [comment]
Don't know if it is the same issue but tested the SAO example with the iPhone 6 and iPhone X yesterday and got a bunch of artifacts, see image below.
![img_0002](https://user-images.githubusercontent.com/22448974/36411909-09089a82-1618-11e8-9677-12033d2870f4.jpg)

@vchizhov 
is this the same effect you mentioned or some other bug? Don't get this issue on my Android device (Sony Xperia Z5)

**Comment by vchizhov** [comment]
Yes, I believe this is also caused by lack of precision. You can see that the issue becomes more apparent the further away an object is from the camera, which has to do with the way depth is encoded (we have more precision for objects that are near, and less for objects further away). Try adding highp for the depth sampler in the shader and see if that fixes the issue, if not then set float's precision to high too in the shader.

**Comment by Mugen87** [comment]
Apart from the precision, the configuration of the `near` and `far` values also affects the quality of `SSAO`. In general, it's beneficial to have a small view frustum in order to achieve a better spread of the available precision in the depth buffer. 

In any event, since only older mobile devices are affected by this issue, I think it's better to close it. From my point of view, complex post-processing shaders like real-time ambient occlusion are not suitable for old devices. In this case, it's better to use baked AO.

BTW: #15243 introduces a new SSAO shader which produces a much better visual result than before.
