### ISSUE TITLE
Threejs's DayDream example crashes in firefox nightly with Oculus connected.

### ISSUE THREAD

**Issue by swomack** [mrdoob/three.js#11581]
##### Description of the problem 

Following example crashes in Firefox nightly with Oculus connected - 

https://threejs.org/examples/webvr_daydream.html

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Can you see any error messages in the browser console? And what about the other `three.js` WebVR examples? Are they working?

**Comment by swomack** [comment]
Others were working. It was just crashing, i could not see any error message. I believe only this example got the modifications of moving the VR related functionalities into `renderer`.

**Comment by Mugen87** [comment]
All examples were updated to the latest API, see 39dac1b64773c99b4ae09b2e3dfb4224f2880e80.

There might be a problem with the GamePad API because `webvr_daydream.html` is the only examples that uses `THREE.DaydreamController`. 

Can you try to remove all references to `DaydreamController.js` in `webvr_daydream.html` and check if the error still occurs? I think you have to remove the gampad instance and the corresponding helper object.

**Comment by Mugen87** [comment]
Sry, i can't do this myself. I don't have access to a Rift.

**Comment by mrdoob** [comment]
I wonder if it's related to this?
https://twitter.com/kearwoodgilbert/status/877661655437524992

**Comment by Mugen87** [comment]
@swomack Do you still get the error with 2017-06-23 Nightly?

**Comment by Mugen87** [comment]
The new FF Nightly build seems to solve the issue.
