### ISSUE TITLE
Quake 2 .map loader

### ISSUE THREAD

**Issue by HeadClot** [mrdoob/three.js#11604]
##### Description of the problem 

Hey everyone,

First off I know this will sound like weird request for an asset loader.
I am using the awesome free and open source map editor called [Trenchbroom](https://github.com/kduske/TrenchBroom) to make levels for a project of mine.

I would like to be able to load these maps as well as user defined parts of these maps into three.JS with their textures properly mapped and the level geometry fully intact.

Thank you for your time,

HeadClot

**Comment by donmccurdy** [comment]
Perhaps we should just use #5524 as the master list for loader requests?

Related:
- http://romsteady.blogspot.com/2015/04/handling-quake-1-map-files-part-1.html
- https://github.com/fzwoch/bsp2obj
- https://developer.blender.org/T35778
- http://andyp123.blogspot.com/2013/06/blender-quake-bsp-importer.html

**Comment by mcharytoniuk** [comment]
@HeadClot you can take a look at this, I coded `.map` loader, but it's a part of a bigger project: https://github.com/personalidol/personalidol . If you (or anyone) would like to help extracting this into the THREE.js loader, I would really appreciate that. :)

**Comment by mrdoob** [comment]
@mcharytoniuk I can take a look. Can you point me to the file that has the loading code?

**Comment by mcharytoniuk** [comment]
@mrdoob Sure. This is the best resource IMO on `.map` files:
http://www.gamers.org/dEngine/quake/QDP/qmapspec.html

In short terms:
`.map` files are divided into `entities`, each `entity` contains either metadata that is game related (for example which additional model needs to be loaded and place on the map or origin and intensity of a point light; some metadata may change a way in which the mesh should be rendered).
`entity` may contain `brush` (which is really a definition of a polyhedron).

`brush` is a collection of half-spaces defined by 3 clockwise points. You can get polyhedron vertices by intersecting all of those half-spaces. `Brushes` are defined that way because Quake used BSP to render scenes.

1. Parser that loads the `.map` file as plain text and extracts info about entities and brushes: https://github.com/personalidol/personalidol/blob/master/src/framework/classes/QuakeMapParser.js
2. Class that keeps entity metadata: https://github.com/personalidol/personalidol/blob/master/src/framework/classes/QuakeEntity.js
3. Class that generates `brush` vertices from half-spaces: https://github.com/personalidol/personalidol/blob/master/src/framework/classes/QuakeBrush.js
4. Class that creates geometries from vertices (uses `ConvexHull`): https://github.com/personalidol/personalidol/blob/master/src/framework/classes/QuakeBrushGeometry.js . It is worth to note that textures are using global coordinates and each face can contain a different texture.

I think that `.map` loader would require some custom loader, because it must not only create meshes, but also must provide a way to access the game metadata that may be attached to each object.

If you need me to prepare some PoC, or document something further I'd be happy to. I would be happy to help some more, but I do not want to declare any deadlines at the moment - time is my only issue now. :D

**Comment by Mugen87** [comment]
Merging into #5524.
