### ISSUE TITLE
Inconsistency between Object3D.getWorldRotation and Object3D.getWorldQuaternion

### ISSUE THREAD

**Issue by lukegravitt** [mrdoob/three.js#11767]
##### Description of the problem 

When trying to copy the rotation of an Object3D into a PerspectiveCamera, the result is inconsistent when using these two lines:

var object = new THREE.Object3D();
var camera = new THREE.PerspectiveCamera();

object.getWorldRotation(camera.rotation);  // Does not work
object.getWorldQuaternion(camera.rotation); // Works fine

Fiddle to demonstrate:

http://jsfiddle.net/akmcv7Lh/168/

##### Three.js version

- [X] r86

##### Browser

- [X] Chrome

##### OS

- [X] macOS

**Comment by WestLangley** [comment]
Yep... The fact that the object is a camera is irrelevant.

Does not work
```
object.getWorldRotation( object2.rotation ); // object2.quaternion is not updated
```
Works
```
var rotation = new THREE.Euler();
object.getWorldRotation( rotation );
object2.rotation.copy( rotation ); // object2.quaternion is also updated
```

The problem is this method is preventing the Euler-Quaternion synchronization required for objects:
```
getWorldRotation: function () {

	var quaternion = new Quaternion();

	return function getWorldRotation( optionalTarget ) {

		var result = optionalTarget || new Euler();

		this.getWorldQuaternion( quaternion );

		return result.setFromQuaternion( quaternion, this.rotation.order, false ); // <== HERE

	};

}(),
```
If you are interested, you can investigate, and see if `false` can be safely set to `true`, allowing the object's quaternion to be updated, too. I expect it can.

**Comment by Mugen87** [comment]
`Object3D.getWorldRotation()` has been removed #13481
