### ISSUE TITLE
Asset Garbage Collector

### ISSUE THREAD

**Issue by Fyrestar** [mrdoob/three.js#11769]
Although resource management isn't necessarily a render engine thing like in this case, it would be usefull to have it by default in THREE, to prevent memory leaks and uneffienct resource management with procedural resources and bigger content. Here's just a suggestion, i've implemented a similar mechanism in my engine i use on top of THREE. In this case it only is for unloading from the GPU, not completely freeing the asset.

It could be a simple reference counter on resources such as Geometry/BufferGeometry, Material etc. to let THREE know wich resources are used by a mesh, once the counter drops to zero it could trash the asset and hold it for a certain timeout/score, if it isn't used until then, disposing it.

**It requires**

It would require a explicit `setGeometry `and `setMaterial ` though (setter/getter would be bad on a frequent accessed properties such as geometry or material on mesh) to track the linking/unlinking what shouldn't be a problem since it's more often likely to pass material and geometry in the constructor. In my implementation i use a class on top of Mesh+SkinnedMesh and the manual assigments are abstracted away, but maybe there are other solutions for this to ensure compatibility to older code.

**Optionally**

The GC could be optionally in the render settings. Only if the GC is intended to be used, a `mesh.setGeometry(geometry)` instead a `mesh.geometry = cube` would be required.

**Settings**

 A `THREE.Geometry.prototype.gcTimeout` for instance could be used to control the behaviour, to dispose frequent generated ones immediately or "lazy" ones like for a large content rich world on a way more generous timout, that could be tracked and depending on the overall memory usage to optimize timeouts. A `THREE.Asset` baseclass would be useful here for materials, geometries, textures etc. the same way all object things extend from `THREE.Object3D`.

**Destroy method for THREE.Object3D**

A additional mesh.destroy would be then nice to remove it from it's parent and call `this.setGeometry(null)...` on the mesh and it's children.

The GC for THREE could be stored in `THREE.GC` and invoked at the end of a frame cycle by calling a `THREE.gc()` for example. It only requires to check if there are even trashed items to take futher actions, a more lightweight solution could use a worker for the GC and send messages on linking/unlinking assets.

**Comment by Mugen87** [comment]
Automated systems are always tempting however they usually have considerable amount of complexity and thus tend to be error-prone. I think the current resource management in `three.js` is sufficient regarding the overall architecture of the engine. `three.js` generally focuses on simplicity. Meaning software components build on top of `three.js` have to enhance certain aspects with custom, more complex solutions if required. An automated resource management is a good example for this. 

I vote to keep the current approach which means users have to work with the `dispose()` API on application level in order to _immediately_ free resources (read [this](https://github.com/mrdoob/three.js/pull/17242#issuecomment-521845876) to understand what I mean with  immediately).
