### ISSUE TITLE
OBJLoader + MTLLoader texture load problem

### ISSUE THREAD

**Issue by deokhae** [mrdoob/three.js#11811]
##### Description of the problem 

I have problem with load texture in [OBJLoader + MTLLoader]

I referred from this example(https://threejs.org/examples/webgl_loader_obj_mtl.html)

but in my case the OBJLoader won`t load texture files.

So, I tried set material in traverse, it might be working in type of single texture obj. like below

but does not working for multi texture type. Could you take a look for. Thank you

```js
var objLoader = new THREE.OBJLoader(manager);
				objLoader.setMaterials(materials);
				objLoader.setPath(settings.path);
				objLoader.load(obj_name, function(object){
					object.position.set(-0, 0, 0 );
					object.rotation.set(0, +Math.PI*0.5, 0 );
					object.traverse( function( object ) 
					{	
						object.castShadow = true;
						object.receiveShadow = true;		
						object.material = MeshPhongMaterials[0];
					} );
					addObject(settings.container, object);
				}, onProgress, onError);`
```

there I am attached some sample link and data of content 2388.

sample:
single type: http://3dbank.xyz:9021/viewer/viewer_hologram.do?conts_uid=2826
multi type: http://3dbank.xyz:9021/viewer/viewer_hologram_u.do?conts_uid=2388
[sample.zip](https://github.com/mrdoob/three.js/files/1161572/sample.zip)

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kaisalmen** [comment]
Hi @deokhae,
if I am not completely mistaken the problem is just related to how parameters are defined in the MTL file. Ambient, diffuse and specular color information are "combined" with the texture info. In your case this heavily alters the visual appearance.

I commented all diffuse, ambient and specular definitions for all materials in both MTL files used in your above examples and the result looks like this (I used OBJLoader2, but MTLLoader is identical)
![11811](https://user-images.githubusercontent.com/21079138/28462786-2114d814-6e1d-11e7-828e-dfe4ff5c5427.jpg)

Check yourself:
https://kaisalmen.de/proto/test/11811/main.src.html

3dbts103601T.mtl:
```
newmtl 3dbts103601_11
#Ka 0.100000 0.100000 0.402000
#Kd 0.470600 0.784300 1.000000
#Ks 0.564700 0.749000 0.996100
illum 0
map_Ka 3dbts103601T1.jpg
map_Kd 3dbts103601T1.jpg
map_Ks 3dbts103601T1.jpg

newmtl 3dbts103601_22
#Ka 0.160800 0.349000 0.000000
#Kd 0.188200 0.800000 0.298000
#Ks 0.149000 0.647100 0.239200
illum 2
map_Ka 3dbts103601T2.jpg
map_Kd 3dbts103601T2.jpg
map_Ks 3dbts103601T2.jpg
```
3dbpo10518T.mtl:
```
newmtl 3dbpo10518
#Ka 0.100000 0.100000 0.402000
#Kd 0.470600 0.784300 1.000000
#Ks 0.564700 0.749000 0.996100
illum 0
map_Ka 3dbpo10518T.jpg
map_Kd 3dbpo10518T.jpg
map_Ks 3dbpo10518T.jpg
```

Try to use shades of grey for ambient, diffuse and specular in the MTL or set after load and then start playing around with those values.

**Comment by deokhae** [comment]
Thank you, @kaisalmen .
I thought the problem should be in library. But it was not.
When I try your mtl file that was showed perfectly.
@mrdoob I think you can close this issue.
Thank you guys.

**Comment by kaisalmen** [comment]
@mrdoob then this can be closed! :smile:
