### ISSUE TITLE
"TypeError: Cannot read property 'x' of undefined" thrown when converting BufferGeometry to Geometry

### ISSUE THREAD

**Issue by andrevega3** [mrdoob/three.js#11851]
I have a non-indexed BufferGeometry that I am trying to convert to Geometry so I may compute line distances but I am running into a exception within the three.js code: 
![image](https://user-images.githubusercontent.com/13002697/28647117-de08e224-722a-11e7-940b-a21b25e65068.png)
The BufferGeometry contains a position attribute with a array of 6 values (2 vertices). Seeing that the error is thrown in computeFaceNormals, the problem seems to begin beforehand when the faces I are being added here: 
![image](https://user-images.githubusercontent.com/13002697/28647168-248fc55a-722b-11e7-9bcf-f0816ab99725.png)
Notice that since positions has the length of 6 then this loop will be iterated once, hence adding a face with 3 sides (0,1,2); however since there is only 2 vertices then the third vertex is undefined when being used here:
![image](https://user-images.githubusercontent.com/13002697/28647213-687d4ada-722b-11e7-936e-7f36f15b77b1.png)

With vC being undefined, it later throws the error in subVectors function where it tries to grab the x value of the first parameter.

Please help.

**Comment by WestLangley** [comment]
`Geometry.fromBufferGeometry()` may require at least 3 vertices.

Does your geometry represent a line, and consequently have no faces?

**Comment by Bsheridan12** [comment]
Followed along a few different threads while attempting to create dashed lines out of BufferGeometry and ended up here with the same issue as @andrevega3.

Speaking for myself here - yes the geometry does represent a line and so understandably does not have any faces causing this error to be thrown when attempting the conversion from BufferGeometry to Geometry.

Is this to say that line BufferGeometries cannot be converted to Geometries and consequently cannot be made into dashed lines?

Is there another conversion path we could follow so that we may use the 'computeLineDistances' on the Geometry object?
Or is there potentially another approach to creating dashed lines from BufferGeometry that we are both missing?

Sorry this may be a little off topic for this thread but it is related to a couple others. [#7013](https://github.com/mrdoob/three.js/issues/7013)

**Comment by makc** [comment]
> Is this to say that line BufferGeometries cannot be converted to Geometries and consequently cannot be made into dashed lines?

they can be, manually. something like
```javascript
var g = new THREE.Geometry;
var a = bg.getAttribute ('position').array;
for (var i = 0; i < a.length; i+=3) {
   g.vertices.push (new THREE.Vector3 (a[i], a[i+1], a[i+2];
```
there were some helper methods to set Vector3 from buffer attribute in 3js, but I forget where they are

**Comment by andrevega3** [comment]
The above solution fixed the problem! Seems adding the vertices manually takes care of the indices confusion.
