### ISSUE TITLE
blender exporter messes with hierarchy, doesnt it?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11935]
I see there is enough [problems with blender exporter](https://github.com/mrdoob/three.js/labels/Blender%20Exporter) to fill... something... large... so I am not sure if this was reported or not, but exporting armature is basically impossible. This is what I have in blender:
![screen shot 2017-08-12 at 21 13 14](https://user-images.githubusercontent.com/242577/29243634-1d10ee5e-7fa4-11e7-9b17-ee9b52a9744d.png)
and this is what I have in 3js editor:
![screen shot 2017-08-12 at 21 11 59](https://user-images.githubusercontent.com/242577/29243640-302daffe-7fa4-11e7-92f6-a7e8e80fc4cb.png)
of course it is possible for it to be editor issue, too... Idk.

**Comment by makc** [comment]
upd: after using fresh exporter from dev branch at least one checkboxes combination (scene on, hierarchy off) have produced correct hierarchy, but the pose is still incorrect:
![screen shot 2017-08-12 at 22 43 26](https://user-images.githubusercontent.com/242577/29244089-efbeef44-7faf-11e7-974e-4d0fafcb5e05.png)

**Comment by Mugen87** [comment]
Related #8422

I think this is one reason why the import in the editor fails.

**Comment by makc** [comment]
@Mugen87 there is no way bad parent-child relationship can be import problem, is it? I can imagine it possible, but how likely that non-bone objects would be not affected?

**Comment by manthrax** [comment]
@makc There were a lot of issues with hierarchy that I have solved in my recent forays into fixing the exporter, but I have not attempted to do a PR or merge my results yet, since there is a lot of cleanup and polish to be done... and my day job got in the way.. but if you would like to try exporting with it, and see if it improves some of your results, I would be super interested to learn if there is any improvement. :)
Here is a zip:
http://vectorslave.com/threexp/io_three.zip

**Comment by makc** [comment]
@manthrax the link expired

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
