### ISSUE TITLE
MTLLoader : Loader does not wait for textures to be loaded or updates the material when textures are loaded

### ISSUE THREAD

**Issue by carlosanunes** [mrdoob/three.js#12105]
##### Description of the problem 

When loading obj+mtl models using the MTLLoader, if the loading is fast enough the model is loaded and inserted into the scene without textures.

Simplifying a bit my usage, I use the OBJLoader2 + MTLLoader loaders to insert models into my scene. I set their onload function to a function that adds the model and redraws the scene. That is,
 the renderer is only called when an object is loaded and added (there is no animation loop).
If the loading process is fast enough, the model is added without textures.

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
It should also work if you use the `onLoad` callback of `LoadingManager`.

[code](https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_collada.html#L69-L73) and corresponding [live example](https://threejs.org/examples/#webgl_loader_collada). The model appears only after all assets are loaded.

**Comment by makc** [comment]
could this be related to #11899 ?

**Comment by carlosanunes** [comment]
@Mugen87, yes that is correct if you use the onLoad callback of LoadingManager instead of the onLoad callback of the MTLLoader itself it works.

**Comment by RemusMar** [comment]
Another solution is to use the onLoad callback of the OBJLoader inside of the onLoad callback of the MTLLoader.
See the source of this example:
http://necromanthus.com/Test/html5/Claire.html

**Comment by Mugen87** [comment]
@makc I think #11899 is something different.

**Comment by Mugen87** [comment]
@RemusMar Hey, this is Claire Redfield from Resident Evil, right? I really do love all of the Resident Evil girls. :blush:

**Comment by RemusMar** [comment]
> Hey, this is Claire Redfield from Resident Evil, right? I really do love all of the Resident Evil girls.

Yes.
Very good looking model for approx 10K poly count.
:heart:

**Comment by mrdoob** [comment]
> @Mugen87, yes that is correct, if you use the onLoad callback of LoadingManager instead of the onLoad callback of the MTLLoader itself it works.

Sounds like the solution is to use `LoadingManager` inside `MTLLoader` then.

**Comment by mrdoob** [comment]
But, that would have side effects. Maybe there are users that would prefer to see parts of the geometry being rendered while the textures load.

Maybe it would be better to use `LoadingManager` in your code as @Mugen87 suggested?

**Comment by carlosanunes** [comment]
@mrdoob 
The way my code is structured that's a 'hack' and the reason I am trying to avoid it. :P But still a valid solution, yes.

But having said that, the onLoad callback is not being called when the model is actually (completely) loaded. In that sense this is very clearly a bug.
The fix I submitted might not be the best solution, but that is and entirely different matter.

**Comment by Mugen87** [comment]
I've revisit the issue and i think that the respective PR is not an appropriate solution in order to solve the problem. All loaders of `three.js` fire the `onLoad` callback when a basic display of the model is possible (this means, the geometry data are parsed). If users want to wait for all related resources like textures, they have to use `LoadingManager`. 

It's important that a loader implementation actually utilizes the given loading manager when it creates additional `TextureLoader` or `FileLoader`. But `MTLLoader` is doing this. So i suggest to close the issue and the PR. The solution is the usage of  `LoadingManager`. But i admit that a note in the docs might help to clarify this situation.

**Comment by carlosanunes** [comment]
> But i admit that a note in the docs might help to clarify this situation.

If the expected/desired behaviour is what you describe the docs are just wrong, it is more than a need for clarification. 'onLoad' is not called when the model is loaded. The model and a basic representation of it are very different things.

I am actually a bit hard pressed to find a good use case for that. That is, a use case where I'm ok, or want, to use 'onLoad' while knowing that the model might not be fully loaded.

**Comment by makc** [comment]
> a good use case for that. That is, a use case where I'm ok, or want, to use 'onLoad' while knowing that the model might not be fully loaded.

since that loader's onLoad receives the reference to the Object3d, I take the opportunity to set whatever properties I need and add it to the scene. then, in manager's onLoad I only start the rendering. but there is no good reason to separate this, just out of habit.

**Comment by Mugen87** [comment]
I see what you mean. As i mentioned before, the thing is that loaders sometimes use other loaders in order to load resource like textures. It's important to highlight that the `onLoad` callback functions of loaders are not coupled in the first place. A superior management of the entire loading process is only possible with `LoadingManager` right now. If we want to change this situation, we need to redesign certain parts of loaders that utilize `TextureLoader` or `FileLoader`.

/cc @donmccurdy

**Comment by makc** [comment]
oh, btw, sometimes I only need the geometry, so I don't really care if textures fail to load. you can say, the model should not reference any textures, but in the context of quick job we have to work with what ever we have, it's not realistic to expect them to have 3d designer to re-do the model every now and then, sometimes you would have to wait for weeks. not sure if this amounts to good use case.

**Comment by Mugen87** [comment]
Looking back at the last years, there weren't more complains about the status quo. With the current approach, devs can have the best of both worlds. If they want to display the asset as fast as possible, they can use the  normal `onLoad()` callback of the loader. If they want to wait until all resources have been loaded, they can use `LoadingManager`.

I bet if we refactor `OBJLoader` at this point so it always waits until all resources have been loaded, there will be complains since certain devs rely on the current (faster) default behavior.
