### ISSUE TITLE
Bug in raycast for SkinnedMesh

### ISSUE THREAD

**Issue by madlexus** [mrdoob/three.js#12104]
##### Description of the problem 

I have a loaded Collada model with bones animation. The bindMatrix scale is 0.01, but this matrix isn't using in raycast function of Mesh, only matrixWorld. Therefore an intersection fires at any point of screen, because raycast seeing the model biggest than it actually renders. The bug is dissapear when multiply both matrices (matrixWorld * bindMatrix) at the begging of function.

##### Three.js version

- [ ] r87

##### Browser

- [ ] Chrome

##### OS

- [ ] Windows

**Comment by Mugen87** [comment]
see #6440

**Comment by madlexus** [comment]
Sorry, I think this is another issue. The SkinnedMesh have a raycast object, but world matrix calculation isn't include bindMatrix. After the following code modification https://gyazo.com/8a0d01893422545d721cd713f75bc251 raycast becomes to work with my 3d model properly.

**Comment by Mugen87** [comment]
The feature request is basically the same: Enabling raycasting for skinned meshes.

I assume your screenshot shows a modified `Mesh.raycast()`, right? Because `SkinnedMesh` is derived from `Mesh`, it's actually bad practice to write code like that. You access a member of skinned mesh in the superior mesh class, which means you violate basic inheritance rules. `Mesh` should not know something about its derived classes.

A proper way is to implement the feature request is to overwrite `.raycast()` in `SkinnedMesh` or to use a similar approach like in @makc's [fork](https://github.com/makc/three.js.fork/tree/skin-raycast)

**Comment by madlexus** [comment]
Thank you for your advice!
