### ISSUE TITLE
Review THREE.Pass specification

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#12115]
Hi

I started working this week on post processing effects for my project.

Noticed that there are a bunch of alternative projects for post processing in threejs (https://github.com/vanruesc/postprocessing, https://github.com/spite/Wagner) and that there is a lot of repeated code in  the "PostprocessingPasses" (creation of quad scene, rendering of depthbuffer, etc).

There is also some lack of flexibility since a EffectComposes is created the render a specific scene with a specific camera and renderer (for me this was the deal breaker).

We should also consider WebGL2 in these reviews (since we are going to have separate renderers probably EffectComposer, ShaderPass, etc should also have 2 versions?).

I think we should review the specification for THREE.Pass and THREE.EffectComposer and create a solid documented specification for new "Passes".

I have started doing some work on this matter to integrate post processing in my project. Im totally available to work on this.

Cumps

**Comment by WestLangley** [comment]
Related: https://github.com/mrdoob/three.js/issues/10144#issuecomment-261118347

**Comment by tentone** [comment]
One thing that could be also implemented is a set of "pre-passes" when adding a new Pass to the Composer the composer checks for pre-requirements (example, DepthBuffer RGBA, DepthBuffer, G-Buffer XPTO, etc)

The Effect composer renders all these pre-requirements and makes the results available to all passes, (if 2 passes need a depth buffer they can use the same buffer). With WebGL2 since we can generate most of these at the "same time" that should improve performance quite a bit.

(This was just an idea that occurred, i will try to implement this in nunuStudio and check if there is some real performance gains with the current renderer).

**Comment by tentone** [comment]
A fast way to fix the flexibility problem with THREE.Pass would be to simply add scene and camera parameters to render.

https://github.com/tentone/nunuStudio/blob/master/source/core/postprocessing/Pass.js

I'm also making some tests with the pre-passes for shared buffers.

**Comment by Usnul** [comment]
personally i see more suitability in a 2 data-structure approach:

- Pass
- Buffer

a pass would define input and output buffers. In "Postprocess" system simply provide some input buffers (or passes that without inputs) and declare what buffer you want to be rendered to screen. Whole thing with swapping is pretty fiddly.

**Comment by Mugen87** [comment]
`EffectComposer` and `Pass` will not be further refactored at this point since the new post processing system for `WebGPURenderer` follows a complete different approach and thus solves the fundamental issues of the previous composer. There is now built-in MRT support, buffer sharing (so passes do not generate their own depth or normal data anymore) and automatic shader combination for pass reduction thanks to TSL and node material. The usage of TSL also allows us to minimize the number of uniform data as well more flexibel options for customizing and combining effects. Since `WebGPURenderer` also supports WebGL as a fallback, the system supports a wide range of devices.
