### ISSUE TITLE
ObjLoader2 parse bug

### ISSUE THREAD

**Issue by luqiang** [mrdoob/three.js#12120]
##### Description of the problem 

This form is for three.js bug reports and feature requests only.  
This is NOT a help site. Do not ask help questions here.  
If you need help, please use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.  
A code snippet, screenshot, and small-test help us understand.

You can edit for small-test.  
http://jsfiddle.net/akmcv7Lh/ (current revision)  
http://jsfiddle.net/hw9rcLL8/ (dev)

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

this obj file include one mesh name is zjej_abm_f01_da_id008_004_r_a_000_000_T004 
I use ObjLoader parse right .  use ObjLoader2 parse wrong.  ObjLoader2 not find out     zjej_abm_f01_da_id008_004_r_a_000_000_T004 

I find ObjLoader2 parse mesh is right but name is wrong

[test.zip](https://github.com/mrdoob/three.js/files/1273562/test.zip)

**Comment by luqiang** [comment]
I fix bug 

		RawObject.prototype.verifyIndex = function () {
			var index = this.buildIndex( this.activeMtlName, ( this.activeSmoothingGroup === 0 ) ? 0 : 1 );
			this.rawObjectDescriptionInUse = this.rawObjectDescriptions[ index ];
			if ( ! Validator.isValid( this.rawObjectDescriptionInUse ) ) {

			
				this.rawObjectDescriptionInUse = new RawObjectDescription( this.objectName, this.groupName, this.activeMtlName, this.activeSmoothingGroup );
				this.rawObjectDescriptions[ index ] = this.rawObjectDescriptionInUse;

			}else
			{
//Fix:  sometimes same mtl but mesh is different so update names 
				this.rawObjectDescriptionInUse.objectName = this.objectName;
				this.rawObjectDescriptionInUse.groupName = this.groupName;
			}

		};

**Comment by kaisalmen** [comment]
Hi, the mesh name is dependent on the information stored in RawObject, The Parser re-creates it as soon as 'o ' or 'g ' is found in OBJ file. The error was that the name for the mesh was taken from the sub-objects (`RawObjectDescription`), I should change that name, btw) used to order data according material and smoothing groups ([see code](https://github.com/kaisalmen/three.js/blob/OBJLoader2_V2/examples/js/loaders/OBJLoader2.js#LL1127)). Rest of the code changes are just related to validate input and improve debug output.

@mrdoob It is fixed on branch for #12048. I am optimistic we get that agreed before release 88. Otherwise the change is easy to backport.

**Comment by kaisalmen** [comment]
@mrdoob This is fixed with merge of #12048 already!
