### ISSUE TITLE
BufferGeometry.MaxIndex unused

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#12251]
[`BufferGeometry.MaxIndex`](https://github.com/mrdoob/three.js/blob/680f499d6b227eae8764dcd7504ffa8d59a30173/src/core/BufferGeometry.js#L42) is currently unused after it was removed from the assignment below in `setIndex` (last line in snippet). Apparently it's been this way for some time, so no harm done I guess.  
But it's still referenced in the [docs](https://github.com/mrdoob/three.js/blob/e9359d5344553e6f3264ee83d4d6ac7563a9c103/docs/api/core/BufferGeometry.html#L179) and [WebGLRenderer.js](https://github.com/mrdoob/three.js/blob/cc14b96e27114e4645d50adaf9ba4894f82bb042/src/renderers/WebGLRenderer.js#L265) where it's increased to `uint32` levels.  
Dead code?
```js
BufferGeometry.MaxIndex = 65535;
  
 Object.assign( BufferGeometry.prototype, EventDispatcher.prototype, { 
  
 	isBufferGeometry: true, 
  
 	getIndex: function () { 
  
 		return this.index; 
  
 	}, 
  
 	setIndex: function ( index ) { 
  
 		if ( Array.isArray( index ) ) { 

 			this.index = new ( arrayMax( index ) > 65535 ? Uint32BufferAttribute : Uint16BufferAttribute )( index, 1 );  
```

**Comment by Mugen87** [comment]
I think the `BufferGeometry.MaxIndex` related code can be removed. The only thing that bothers me is the handling of `OES_element_index_uint`.

So when `Uint16BufferAttribute` is used in `BufferGeometry .setIndex()`, `gl.UNSIGNED_SHORT` represents the type of the values in the element array buffer (see [here](https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLAttributes.js#L31-L33)).

In the case of an `Uint32BufferAttribute`, `gl.UNSIGNED_INT` is used. But this approach is actually only valid if the extension `OES_element_index_uint` is available. 

Anyway, i think we don't need this check at all because the support of `OES_element_index_uint` is close by 100% (see https://webglstats.com/webgl/extension/OES_element_index_uint).
