### ISSUE TITLE
TubeBufferGeometry How to build top and bottom Faces

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#12390]
I am using TubeBufferGeometry to build a model similar to steel, if you can achieve the ExtrudeBufferGeometry source code inside the buildLidFaces method, thank you very much!

**Comment by WestLangley** [comment]
`TubeBufferGeometry` does not support end caps. You will have to do that yourself. Consider adding a `CircleBufferGeometry` at each end as a work-around.

**Comment by Usnul** [comment]
# identify vertices of the end
# create a Shape by itaversing those vertices in "nearest next" order
# create geometry out of the shape
# merge tube geometry with the cap

**Comment by jgphilpott** [comment]
> `TubeBufferGeometry` does not support end caps. You will have to do that yourself. Consider adding a `CircleBufferGeometry` at each end as a work-around.

@WestLangley @Mugen87 could this be a possible feature in the future? It would be really useful!

**Comment by Mugen87** [comment]
The idea of using `CircleGeometry` seems to be a sufficient workaround. Do you mind explaining why you can't use it?

**Comment by jgphilpott** [comment]
@Mugen87 well I did try that and visually it looks okay. However, my usecase here is for 3D printing, so when I export the scene to an STL file and go to slice it I run into errors. The resulting geometry here isn't properly merged, even though it looks okay in the scene, it wont slice successfully.

I've actually solved my problem my using an [extruded shape geometry](https://threejs.org/examples/#webgl_geometry_extrude_shapes) because its ends are always closed. This looks the same in the scene and will also slice without any issue.

Nonetheless I am of the opinion that the [tube geometry](https://threejs.org/docs/#api/en/geometries/TubeGeometry) **should** have built in support for end caps, in fact that's what I thought `closed` was at first. The vary fact that you call it a 'workaround' implies that there is a potential feature here that **should** be addressed.

**Comment by WestLangley** [comment]
>Nonetheless I am of the opinion that the tube geometry should have built in support for end caps

AFAIK, there has been no demand for that since the inception of three.js.

Can you 3D print cylinder geometry with end caps successfully?

**Comment by jgphilpott** [comment]
@WestLangley okay no problem, guess it's not an issue for everyone. Yes, printing a cylinder is easy, but the tubes i'm using are not in straight lines so I can't substitute cylinders :( ... its okay, the [extruded shape geometry](https://threejs.org/examples/#webgl_geometry_extrude_shapes) works well.

**Comment by WestLangley** [comment]
@jgphilpott  So cylinders print with end caps, but your tubes did not? Perhaps you did not merge the geometries?
