### ISSUE TITLE
ColladaLoader2 problem with geometries of type triangles. 

### ISSUE THREAD

**Issue by MohmadAyman** [mrdoob/three.js#12443]
##### Description of the problem 

We are trying to upgrade from Colladloader to Colladaloader2, but it seems like all the models that have their geometries type = triangles do not appear in the scene.

Are triangles not supported yet in the new loader?

For example [this mesh](https://bitbucket.org/osrf/gazebo_models/raw/2736659d92e2c1afe4098fb1c68cb2feb3a55484/house_2/meshes/house_2.dae) used to work with the old loader, now nothing appears.

Thanks.

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Triangles as primitive type should basically be supported by the loader. I will debug your file over the weekend.

**Comment by Mugen87** [comment]
I found the problem. Have a look at this part of your collada file:

```xml
<node>
  <matrix>1 0 0 133.1126 0 1 0 181.0321 0 0 1 -4.96994e-5 0 0 0 1</matrix>
  <instance_geometry url="#geom-Box005">
    <bind_material>
      <technique_common>
        <instance_material symbol="_4_-_Default_1" target="#_4_-_Default-material"/>
      </technique_common>
    </bind_material>
  </instance_geometry>
</node>
```
The actual problem is that the first `node` tag does not have an `id` attribute. Currently the loader expects an `id` attribute and can't process files without this information because it utilizes the id for identifying (organizing) nodes.

@mrdoob This is the problematic [part](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader.js#L2752-L2757) of the loader. Do you have an idea how we can handle nodes without `id` attribute? Could the loader generate/add this missing information in some way?

**Comment by Mugen87** [comment]
I just implemented a possible solution. The loader can now handle the problematic file.

**Comment by MohmadAyman** [comment]
Thanks!
