### ISSUE TITLE
Call onProgress, onError of duplicate requests in FileLoader

### ISSUE THREAD

**Issue by ngokevin** [mrdoob/three.js#12454]
##### Description of the problem 

Duplicate request handling in https://github.com/mrdoob/three.js/pull/12434

In case of an error on the request, we should notify the rest of the duplicate `.load()` callbacks (`onError`). Similarly, we can call `onProgress` to every duplicate `.load()` call callback.

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by takahirox** [comment]
And I've found another issue.
When `Cache.enabled` is `false`, duplicate requests isn't handled correctly because `cached` is always `undefined` here

https://github.com/mrdoob/three.js/blob/613499d8289501be67178a8a66aab64ac6ee32a2/src/loaders/FileLoader.js#L28

and `loading[ url ]` isn't deleted when callback function is called.

https://github.com/mrdoob/three.js/blob/613499d8289501be67178a8a66aab64ac6ee32a2/src/loaders/FileLoader.js#L193-L199

/cc @mrdoob
