### ISSUE TITLE
PointLights not working correctly with Lambert material

### ISSUE THREAD

**Issue by simsas18** [mrdoob/three.js#12457]
##### Description of the problem 
I am trying to create a scene lit by PointLights but the pointLights are not working as expected when using Lambert material. It looks like the lights only render where both lights reach the surface.

When I tried to use Phong material, it renders correctly.

Lambert material:
![screenshot 31](https://user-images.githubusercontent.com/23166657/31850449-745870e6-b65a-11e7-900b-7d0fa8507772.png)

Phong material:
![screenshot 32](https://user-images.githubusercontent.com/23166657/31850450-747df0fa-b65a-11e7-8a92-d1fc8fbaa045.png)

Here is my example: https://jsfiddle.net/aojnmspn/

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by takahirox** [comment]
Seems like `getShadowMask()` in `meshlambert_frag.glsl` masks with shadow (in the example case, masks with shadow generated by two point lights).

https://github.com/mrdoob/three.js/blob/f3cfc6e4c77e9fb4c111b77c4b9adc2e326b641a/src/renderers/shaders/ShaderLib/meshlambert_frag.glsl#L67

First, I'd like to know if this result is actually unexpected. I'm not very familiar with Lambert model with Shadow. Anyone knows about it?

**Comment by WestLangley** [comment]
This is not a bug. It is a limitation of `MeshLambertMaterial` due to the fact that it uses Gouraud shading -- the illumination calculation is computed in the vertex shader. Shadows are computed in the fragment shader, and there is no way to identify the light sources at that point.

For proper shadows, use, for example, `MeshPhongMaterial` or `MeshStandardMaterial`.

Also, I would advise using `MeshLambertMaterial` on a geometry (the plane) having only 4 vertices -- especially when the light is so close to the mesh. If you want to use `MeshLambertMaterial`, tessellate the geometry. Also, avoid setting the light intensity to 20. A typical value is 1.
