### ISSUE TITLE
Where is convert_obj_three.py ?

### ISSUE THREAD

**Issue by nikolas7892** [mrdoob/three.js#12515]
I need to convert an obj to .bin , I can't seem to find the convert_obj_three.py anywhere in the repository.. What are my options?

**Comment by Mugen87** [comment]
see 89cb329fec39cd7c570752b09352b70188cac89b

**Comment by nikolas7892** [comment]
This is a converter to JSON. I need .bin, there was a specific python script that converted the obj to a .bin file..

**Comment by moraxy** [comment]
The `convert_obj_three.py` that was removed in 89cb329 can produce .bin as well, via command line switch:
`-t ascii|binary   export ascii or binary format (ascii has more features, binary just supports vertices, faces, normals, uvs and materials)`
and
````
    - binary conversion will create two files:		
        outfile.js  (materials)		
        outfile.bin (binary buffers)
````

**Comment by nikolas7892** [comment]
What steps / commands do i need to run to convert the file?

**Comment by moraxy** [comment]
Convert with `python convert_obj_three.py -i wolf.obj -o wolf.js -t binary` (or the python3 version if you don't have python2 anymore) and you should get two files `wolf.js` and `wolf.bin`.

**Comment by nikolas7892** [comment]
Thank you, worked perfectly

**Comment by Mugen87** [comment]
I'd like to suggest an alternative workflow because `BinaryLoader` is from my point of view somewhat deprecated (it still outputs `Geometry`) and limited in its features.

If you don't want to load `OBJ` directly, try to convert your file to the standardized `glTF` format with this converter: https://github.com/AnalyticalGraphicsInc/obj2gltf

You can then load your file with `GLTFLoader` which is a much more up-to-date solution for your problem.

BTW: I think it was okay to remove all this python code since the JavaScript solution is way easier to maintain. Even if this means to drop binary support. There are enough alternatives like the `glTF` one.
