### ISSUE TITLE
Adding convertUpAxis() to ColladaLoader

### ISSUE THREAD

**Issue by MohmadAyman** [mrdoob/three.js#12526]
##### Description of the problem 
Hi,

Is there any reason why `options.convertUpAxis()` was removed from the new `ColladaLoader`?

RIP `convertUpAxis()` , you were a very helpful function :smile: 

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
The former implementation of somewhat messy because the conversion was hardwired in the code of the loader. Besides, we generally agreed that this functionality should actually part of exporters, not loaders. Read #11404 see  #11540 for the entire story 😉 

The new loader automatically performs a simple rotation of the entire scene, if necessary. This should be sufficient for most use cases.

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader.js#L3424-L3428

**Comment by MohmadAyman** [comment]
Okay I see, seems out meshes are not case :confused: 
Well it seems like that we need to exchange `Y_UP` and `Z_UP` all of the meshes -`gazebo meshes`- by an external script to have the correct rotation when upgrading to the new `Collada`, well this is not a very good thing for us.
So I would say exposing this functionality would still be useful.

**Comment by v1r0x** [comment]
Having the same problem with some collada files. I use `TransformControls` to build a simple editor. Other formats work fine, but using the gizmo on a collada object (in world space) moves the object on the wrong axis. I'm also confused, because I thought #11540 should re-add this method to `SceneUtils`.

A build-in solution to fix non y-up models would be great!
