### ISSUE TITLE
Feature request: Typings and constants

### ISSUE THREAD

**Issue by Itee** [mrdoob/three.js#12579]
Next to #12574 part 2

The proposal is to use "enum like" object instead of wild constantes, this will prevent user against change them by error. And gain in readability about what values are usable in the same 'enum'

Example: 

```javascript
// RENDERER
var CullFace = Object.freeze( {
    None: 0, 
    Back: 1, 
    ...
} );

// MATERIALS
var MaterialSide = Object.freeze( {
    Front: 0, 
    Back: 1, 
    ...
} );

// TEXTURES
var TextureMapping = Object.freeze( {
    UV: 0, 
    CubeReflection: 1, 
    ...
} );

...
```

instead of

```javascript
export var RepeatWrapping = 1000;
export var ClampToEdgeWrapping = 1001;
export var MirroredRepeatWrapping = 1002;  <= dude ! I need a new wrapping type
export var NearestFilter = 1003;
export var NearestMipMapNearestFilter = 1004;
export var NearestMipMapLinearFilter = 1005;
export var LinearFilter = 1006;
export var LinearMipMapNearestFilter = 1007;
export var LinearMipMapLinearFilter = 1008;  <= Or damned, i need a new filter type, i will need to increase all type bellow...
export var UnsignedByteType = 1009;
export var ByteType = 1010;
export var ShortType = 1011;
export var UnsignedShortType = 1012;
```

and the call become:

```javascript
material.blending = THREE.Blending.Normal
```

instead of

```javascript
material.blending = THREE.NormalBlending
```

**Comment by Itee** [comment]
/ping @mrdoob So what is your opinion ?

**Comment by mrdoob** [comment]
Hmm... I looked at this some years ago. I had the same solution you're proposing, but the migration it entails didn't feel like it was worth it.

**Comment by haroldiedema** [comment]
How about a migration period? 

Use ES6 getters (if at all possible) to show deprecation warnings and announce when old constants are being removed?

Or simply move them to a separate "compatibility/legacy" file.

I personally think that the pros outdo the cons in this case.

* These constants are really ENUMS (they pretty much all belong to a "group")
* They can be documented more easily since they are grouped together
* Any developer can see immediately what other types are available for a setting (as shown in OP post)

To be honest, aside from migration, I can't really see any reasons why we shouldn't do this.

**Comment by Itee** [comment]
About the backward compatibility we could set them inside three.legacy with getter like:

```javascript
var RepeatWrapping = function() {

    console.warn('RepeatWrapping is deprecated... blah blah... use THREE.Wrapping.Repeat instead');
    return 1000;

};
```

@haroldiedema i totally agreed ! 

We need to return the "old" value in case of hard coded check.

**Comment by haroldiedema** [comment]
That won't work @Itee. `RepeatWrapping` is referenced to like a variable, not a function call.

The only way to do this (as far as I know) is something along the lines of:
```javascript
Object.defineProperty(THREE, 'RepeatWrapping', { 
    get: function() { 
        console.warn( "THREE.RepeatWrapping is deprecated. Use ... bla bla ... instead." ); 
        return 1000;
    }
});
```

I'm not sure how we deal with browser compatibility, but I'm sure that this won't work on IE9 or below.

See [mdn page](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) for details.

I also have no idea about the performance implications.

However, for migration sake, I don't think it's a very big issue to do a global search/replace on projects as users of Three, since all these constant names with the `THREE.`-prefix are pretty unique.

**Comment by Itee** [comment]
Yes i don't care about the migration. And about performance i don't think it will be really significant for a migration.

About the implementation way, yes i maybe a bit tired ( in first i was thinking to an iife but the result will be the same... incorrect ). 

And i prefer the `Object.defineProperties` (note the 'ies' here), to declare all old variables in the same place.

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/12972#issuecomment-354334791
