### ISSUE TITLE
Improvement: Three parameters management

### ISSUE THREAD

**Issue by Itee** [mrdoob/three.js#12574]
This suggest/request/need is about the parameters management in three library. This "Issue" is composed by three parts ( ah ah ah ), which are different but with the same underlying topic, that's why i make a unique issue instead of three.

**1. Lacking documentation**

The last day i was searching some help in the threejs doc... and what was my surprise ! I was unable to known which value i could use for some parameters....

Me the last day, reading the doc:
> Ok... this is a string... That look like an ugly enum, but i don't known what are the enum values, damned ! Will i need to find it in the code ? Really ? 😭 

Things like that are really common with the current documentation. For a lot of params, class members etc... it is impossible to known which values can be used, even if the type can be deduce ( note the deduced here ! ) by default parameters.

Some example here:

```
.blendDstAlpha

The tranparency of the .blendDst. Default is null.
```
Ok transparency is an floating point number between 0.0 and 1.0...

```
.customDistanceMaterial

Same as customDepthMaterial, but used with PointLight. Default is undefined.
```
Right, so... should i use a MeshDepthMaterial ?

```
.getPointsHoles ( divisions )

divisions -- The fineness of the result.

Get an array of Vector2s that represent the holes in the shape.
```
Should i send 1/3 ?
Etc...

**Note that this is not a criticism of the big documentation about threejs** ! This is more a question if is it possible to have somethings like below, and if not why is this wanted by documentation design ?

```
.getPointsHoles ( divisions )

divisions - [Floating point number] - The fineness of the result. Default is 0.0

Get an array of Vector2s that represent the holes in the shape.
```

**2. Enums or not Enums**

Sometimes, during development i need a threejs constante. I have some memory trouble so i can't remember all of them, or other possibility in a range of values. And i won't have an open windows over the documentation, i prefer use the smart auto-completion of my IDE which is designed for that !

But with threejs constant i can't ! Is it possible to use some "real" enum like for a value in a set of values ?

Example:

In constant.js
```javascript
export var UVMapping = 300;
export var CubeReflectionMapping = 301;
export var CubeRefractionMapping = 302;
export var EquirectangularReflectionMapping = 303;
export var EquirectangularRefractionMapping = 304;
export var SphericalReflectionMapping = 305;
export var CubeUVReflectionMapping = 306;
export var CubeUVRefractionMapping = 307;
```
usage: 
```javascript
if ( this.mapping !== CubeRefractionMapping ) return;
```

could become:

```javascript
var Mapping = Object.freeze( {
    UV: 0, 
    CubeReflection: 1, 
    CubeRefraction: 2,
    EquirectangularReflection: 3,
    EquirectangularRefraction: 4,
    SphericalReflection: 5,
    CubeUVReflection: 6,
    CubeUVRefraction: 7
} );
```
usage: 
```javascript
if ( this.mapping !== Mapping.CubeRefraction ) return;
```

Notice here the numbering that start to 0 instead of use tricky(?) numbering. Because when we need to extend enum it will be easier for cases like this:

```javascript
export var RepeatWrapping = 1000;
export var ClampToEdgeWrapping = 1001;
export var MirroredRepeatWrapping = 1002;  <= dude ! I need a new wrapping type
export var NearestFilter = 1003;
export var NearestMipMapNearestFilter = 1004;
export var NearestMipMapLinearFilter = 1005;
export var LinearFilter = 1006;
export var LinearMipMapNearestFilter = 1007;
export var LinearMipMapLinearFilter = 1008;  <= Or damned, i need a new filter type, i will need to increase all type bellow...
export var UnsignedByteType = 1009;
export var ByteType = 1010;
export var ShortType = 1011;
export var UnsignedShortType = 1012;
```

**3. Please throw me away**

This is my bigger problem with threejs library ! The inconsistency of error return.
Sometimes, i make mistakes 🙈 ... But when i got the error this is absolutely not related to the root problem. And this is due to a real lack in parameters check !

One of the best error in my opinion is the NaN value get in spherical bounding box computation. 
Ok i have NaN values that break the bounding box computation... But WHY have i NaN values ??? I will need to pass 2 hours ( ok maybe 10min but... ) to find the real cause.

This type of headache could be easily resolve, with a very big gain for the library and ( especially ) for users ! We just need to check params in ctor and setters ( in fact all methods where monkeys could send a banana, and yes i'm a monkey too ! ). This will have a little performance impact, but a huge impact in terme of stability and safety of the library. The only part where this should be avoid are core types, and methods in render pipeline.

Earlier an error is raise better is !

A good things could be to have a Validator class for commun error case like in LoaderSupport.

I hope I am clear in my comments, and that we can find a satisfactory outcome.

**Comment by donmccurdy** [comment]
1. **Documentation** 

One feature that is easy to miss, you can mouse over most parameters to learn their type:

![parameter tooltip screencap](https://user-images.githubusercontent.com/1848368/32395953-8f8da2aa-c0a0-11e7-8abf-16fb83f3f22e.gif)

I agree it would be great to provide something more obvious and easier to read. Maybe that can be done just using some tweaks to the website rendering? There are also options like [documentation.js](http://documentation.js.org/), but I don't know that it would be necessary here.

2. Typings and constants

There are some projects that provide three.js autocomplete for popular editors, like https://github.com/blackjk3/threejs-sublime. Do you know why this doesn't work in your editor? I'm not sure I understand how your suggestions would make autocomplete start working in editors where it currently doesn't?

3. Performance, return types, optional targets, etc.

Always good to hear specific ideas for making three.js easy to use, thanks.

Checking for `NaN` and returning an error unfortunately can and will have high performance costs on some critical methods.. maybe there are some specific methods where it's OK, but it can't be done everywhere — especially in the Math code.

Would be curious what features you would like for a Validator class?

**Comment by Itee** [comment]
### 1. Documentation

Ok... i notice the mouse hovering... this is not obvious to guess... yet it's been over 4 years that I use threejs... Ahem ! 🐒 

### 2. Typings and constants

I will check for my IDE but i haven't much hope... Anyway ! This could helper because typing `Mapping.` my IDE will propose all potential values for this "enum". But the main purpose was to use enum instead of a sequence of variables that should be linked together with a more semantic way.

### 3. The NaN check was just a bad example ( my fault ) but the idea behind could be fully understand in #12231. I just want better parameters check in development environment to avoid headache ! And this will allow a more robust code for every users/developpers of threejs library !

**Comment by looeee** [comment]
**1. Documentation**

Agreed that the mouse hover for showing the type is not very clear - and I'm not sure how well it works on mobile. We discussed this before and didn't come up with a better solution though. 

I also agree that it would be good if docs could show the expected range as well as the default type where possible. Here is an example of wording [MeshPhongMaterial.bumpScale](https://threejs.org/docs/#api/materials/MeshPhongMaterial.bumpScale) - most parameters don't have hard set ranges, so something like "expected range" or "typical range" is best, except for in the couple of places where putting values outside these ranges will break things (camera near / far for example). I did spend some time on this, but it's a lot of work and experimentation to figure out what these ranges are  so I mainly resorted for just putting in the default value. 

**2. Typings and constants**

There is a reason the constants are organised that way. Currently we can do 

```js
material.blending = THREE.NormalBlending
```

instead of 

```js
material.blending = THREE.blendingConstants.NormalBlending
```

Which is cleaner.

It might be possible to refactor the file so that all the constants are zero-indexed without creating objects though. Also, a couple of comments in the file saying what the constants relate to would be good:

```js
// RENDERER
export var CullFaceNone = 0;
export var CullFaceBack = 1;
...

// MATERIALS
export var FrontSide = 0;
export var BackSide = 1;
...

// TEXTURES
export var UVMapping = 300;
export var CubeReflectionMapping = 301;
...
```

**3. Params check and Validation**

'the position attribute is likely to have NaN values...' - every three.js developers least favourite error message 😆  
But yeah, there's not much to be done here, that I can see. Adding checks all over the place to try and catch these errors would complicate the code and affect performance. 

I've been tempted to add [Flow](https://flow.org/) to my personal projects recently to see whether this will catch anything that Eslint misses.

**Comment by looeee** [comment]
BTW I just added three.js intellisense to VSCode with [this method](http://shrekshao.github.io/2016/06/20/vscode-01/) and it works really well. 

The final step:

> Now with 1.x.x VSCode, we need to generate a jsconfig.json file in the root of the project folder by clicking the light bulb button at the bottom right. 

doesn't work, you'll have to create `jsconfig.json` manually. Mine looks like:

```js
{
  "typeAcquisition": {
    "include": [
      "three"
    ]
  },
  "compilerOptions": {
    "target": "ES6",
    "module": "es6"
  },
  "exclude": [
    "assets/js/build",
    "assets/js/build-min",
    "assets/js/vendor",
    "node_modules"
  ]
}
```

**Comment by Itee** [comment]
@looeee 
## 1. Documentation
I'm sure this is a lot of work to put ranges in all doc where/when possible ! About the hovering, we already have the type so instead of popup it after few second, maybe it could be more clear to add a field just after the member, params. In this way it will be accessible on mobile too.

> divisions - The fineness of the result.  A Floating point number, in the range 0.0 - 1.0 with default to 0.0

No ?

## 2. Typings and constants

In fact it could become:

```javascript
material.blending = THREE.Blending.Normal
```

instead of 

```javascript
material.blending = THREE.NormalBlending
```

Reindexing the file will need a check against hard coded value ! But yes it could be smart to do this. With comment why not, if we gain in clarity this is good !

but i was thinking more a thing like that:

```javascript
// RENDERER
var CullFace = Object.freeze( {
    None: 0, 
    Back: 1, 
    ...
} );

// MATERIALS
var MaterialSide = Object.freeze( {
    Front: 0, 
    Back: 1, 
    ...
} );

// TEXTURES
var TextureMapping = Object.freeze( {
    UV: 0, 
    CubeReflection: 1, 
    ...
} );

...
```

In that way you will be immediately able to known all usable values for a "type" of constante. This could be easier for newcomers. And this pattern disallow end user to change constants value by mistake.

## 3. Params check and Validation

> Adding checks all over the place to try and catch these errors would complicate the code and affect performance.

I won't use "try catch" in the lib ! But i just want to be sure, when i call a setter or ctor, i'm sending the expected argument at least in dev ! And performance won't be so impacted see #12231 

As i known flow work with comments ? So i will unusable with threejs due to the fact that MrDoob won't too many comments in the code...

And about intellisense, i'm using WebStorm which have already it's own settings style/inspect/etc... for threejs.

It's not really difficult for me to write code with threejs. The main goal in my mind is to gain in semantic meaning of the code, for new comers ( based on difficults that i finded during learning threejs )

**Comment by looeee** [comment]
**1. Documentation**

> divisions - The fineness of the result. A Floating point number, in the range 0.0 - 1.0 with default to 0.0

Well, presuming you are talking about one of the [Curve.getPoints()](https://threejs.org/docs/#api/extras/core/Curve.getPoints) derived methods, that is actually wrong and should be similar to the description for that method:

> divisions -- number of pieces to divide the curve into. Default is 5.
> Returns a set of divisions + 1 equi-spaced points using getPointAt( u ).

But in general we should treat each parameter as needed, while sticking to the minimum amount of different and most technically correct of way of saying things. Hence, if there is no type checking involved and a user can actually put in whatever they like, it's not correct to say that the range is `[0,1]` - but it is correct to say that's the 'valid' or 'expected' or 'typical' range.

**2. Typings and constants**

> In that way you will be immediately able to known all usable values for a "type" of constante. This could be easier for newcomers. 

That's actually a good point. I would still say that using `Object.Freeze` is overkill though - and also I'm not sure if this is a good enough reason to break compatibility. We'd end up needing to add all the old constants to `Three.Legacy.js` ☹️ 

**3. Params check and Validation**

> I won't use "try catch" in the lib !

Sorry, I didn't mean literal use of "try-catch" clauses. I should be more careful in my language use. 
I meant that any means of validation checking beyond what there is now will result at the very least in more  complicated, harder to read code and also likely reduce performance too. 

**Flow** claims to be able to do a lot of it's magic even without adding the extra `function fname( param: type ) {}` stuff. But yeah I haven't noticed anything yet, and I was rather suggesting this for use in personal projects, not in the main library since that is where you are saying this lack of validation is a problem. 

By the way, for me at least talking about 3 different issues in a single post is kind of confusing - I'd find it easier to focus on one at a time 😛

**Comment by Itee** [comment]
I will split this Issus into 3...

Part 1 become: #12580
Part 2 become: #12579
Part 3 become: #12578 

So i close.
