### ISSUE TITLE
TextGeometry: Cannot clone text geometry.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#12655]
Demo: http://jsfiddle.net/donmccurdy/pvovcefc/

Cloning a `TextGeometry` instance returns an empty `Geometry` instance.

**Comment by Mugen87** [comment]
This happens to all geometry entities because the `.clone()` method in `BufferGeometry` (and `Geometry`) is implemented like this:
```javascript
clone: function () {

   return new BufferGeometry().copy( this );

}
```
So the geometry data are preserved (e.g `attributes`) but not the `type` or the `parameters` property. I'm not sure why the previous version of the method (currently commented out) was replaced with the above code.

**Comment by donmccurdy** [comment]
Oops, my main problem was that the `TextGeometry` object I was debugging was coming from [three-bmfont-text](https://www.npmjs.com/package/three-bmfont-text) and not actually THREE.TextGeometry. 😅 

The type change from TextGeometry to Geometry (https://github.com/mrdoob/three.js/commit/ae4c5198fdbaafb747e5c3739d4506c5b622c282) was just a red herring I guess, it does seem to all be working correctly in the demo.
