### ISSUE TITLE
FBXLoader: THREE.Material: 'map' parameter is undefined.

### ISSUE THREAD

**Issue by msimpson** [mrdoob/three.js#12682]
##### Description of the problem 

When attempting to load the FBX file contained within the example below, we are seeing the following error:

```
three.js:7693 THREE.Material: 'map' parameter is undefined.
```

Upon further investigation, it seems that on [line 489 of the `parseParameters` method](https://github.com/mrdoob/three.js/blob/r88/examples/js/loaders/FBXLoader.js#L489) the `map` parameter is set to `undefined` as the `relationship.ID` used is not found in the `textureMap`. So while the `textureMap` does contain the expected texture with its own ID, the relationship ID used seems to be of the diffuse color material instead.

Therefore, I'm unsure if this problem arises due to the makeup of this specific FBX file or if an issue exists with the loader. Also, the FBX file in question was exported from Cinema 4D R17 using FBX version 7.5.0 and then downgraded to 7.3.0 to match the FBX example for Three.js. However, both exhibited the same issue.

Live Example (Blue Wall w/o Texture):
https://fbx-test.staging.alextom.com/

Any help would be appreciated.

##### Three.js version

- [x] Dev
- [x] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Minimal.

**Comment by looeee** [comment]
The problem is that you are using a layered texture - here's how the material looks in 3DS Max:

![mat](https://user-images.githubusercontent.com/5307958/32976146-704f6f78-cc43-11e7-9cfd-70b5a333fefa.jpg)

Here's a section of the parsed FBX file

![console](https://user-images.githubusercontent.com/5307958/32976189-24acc20e-cc44-11e7-9ecb-03c343f4fcb5.png)

The layered texture has ID 2094787904, and that is what the parseParameters method is using to search for the texture on line 489, while the actual texture has ID 2156821328.

I'm not sure what the best solution is here since three.js doesn't support layered textures - there are two possibilities:

* display a warning that layered textures are not supported
* always use the first texture in the layer

The second option would probably give good results in most cases since Layer 1 is usually the main texture and subsequent layers are usually masks. But there is no guarantee of this. 

@msimpson can you try to re-export the file from Cinema 4D R17 without the layered texture?

**Comment by msimpson** [comment]
@looeee 
I'll work with my designer to try and remove that layered texture for now. However, I'd encourage adding support for them in the FBX loader given that Cinema4D is merely using the Autodesk FBX exporter and such textures are [standard aspects of that format](http://docs.autodesk.com/FBX/2014/ENU/FBX-SDK-Documentation/index.html?url=files/GUID-452768B5-7A4F-45BD-AC37-DC1A034DCF3B.htm,topicNumber=d30e10431).

**Comment by looeee** [comment]
@msimpson Way ahead of you 😉 #12694

Although bear in mind that it's more of a workaround as three.js doesn't support layered textures - this will just use the top layer and discard the rest.

**Comment by msimpson** [comment]
@looeee 
I think that's sufficient given the lack of support in the engine, itself.
