### ISSUE TITLE
Suggestion: Document for compatibility

### ISSUE THREAD

**Issue by keqingrong** [mrdoob/three.js#12698]
It would be nice to add a document for compatibility. 

Here is my notes. I hope this can help somenoe as a reference.

# three.js compatibility

## Browser Support

three.js supports most modern browsers, including Internet Explorer 9 and above. 

three.js provides WebGL, Canvas, SVG and CSS renderers. Different renderers may have different requirements of compatibility. In theory, three.js works on all browsers that support WebGL: Google Chrome 9+, Firefox 4+, Opera 15+, Safari 5.1+, Internet Explorer 11 and Microsoft Edge. More infomation can be found at [Can I use WebGL?](https://caniuse.com/#feat=webgl).

For Internet Explorer, the table below lists avaiable renderers.

| Renderer         | IE Version |
| ---------------- | ---------- |
| WebGLRenderer    | IE11+      |
| CanvasRenderer   | IE9+       |
| SVGRenderer      | IE9+       |
| CSS3DRenderer    | IE10+      |
| CSS2DRenderer    | IE9+       |

If you still need to support IE9, it's a good choice to use CanvasRenderer.

## ECMAScript Language Features or Web APIs Used in three.js

| Feature               | Use Scope | Modules       |
| --------------------- | --------- | ------------- |
| Typed Array           | Source    | BufferAttribute, BufferGeometry |
| WebVR API             | Source    | WebVRManager  |
| Blob                  | Source    | FileLoader    |
| performance           | Source    | Clock         |
| requestAnimationFrame | Source    | WebGLRenderer |
| Promise               | Examples  | GLTFLoader, GLTF2Loader, WEBVR  |
| Web Workers           | Examples  | WWOBJLoader2  |
| FileReader            | Examples  | GLTFExporter  |
| URL API               | Examples  | GLTFLoader    |

## Polyfills

Just import polyfills base on your requirements. Again, taking IE9 as an example, the following polyfills are necessary:
- Typed Array
- Blob
- performance
- requestAnimationFrame

### Suggested polyfills

- [core-js](https://github.com/zloirock/core-js)
- [Typed Array](https://github.com/inexorabletash/polyfill/blob/master/typedarray.js)
- [ES-Promise](https://github.com/stefanpenner/es6-promise/)
- [Blob.js](https://github.com/eligrey/Blob.js)
- [performance](https://gist.github.com/paulirish/5438650)
- [requestAnimationFrame](https://gist.github.com/paulirish/1579671)

**Comment by Mugen87** [comment]
@keqingrong Thanks for your effort. Of course a compatibility overview is a useful thing and might be good orientation especially for beginners.

However, i do not vote for an "official" detailed compatibility overview since it is a lot of work to maintain a comprehensive document. Right now, it is already hard for the core contributors to keep the project fairly up to date. I do not like the idea to document even more stuff.

Besides, i see some critical statements in your post:

> three.js supports most modern browsers, including Internet Explorer 9 and above.

I'm afraid this statement is misleading and produces wrong expectations. From my point of view, IE9 is not supported. Microsoft users should use at least IE11, the better option is Edge.

> If you still need to support IE9, it's a good choice to use CanvasRenderer.

No, this is not a good choice. `CanvasRenderer` only supports a small subset of `WebGLRenderer`'s features. Again, IE9 is a bad platform for graphic intensive web applications. 

> ECMAScript Language Features or Web APIs Used in three.js

You've missed some JavaScript APIs that are actually used in the core for example `WebAudio`. Besides, `requestAnimationFrame` is not only used in `WebGLRenderer` but e.g. in `VideoTexture`. Other API's that are used in the examples like `PointerLock`, `TextDecoder` or `fetch` are also not mentioned.

**Comment by mrdoob** [comment]
I agree with @Mugen87. However, I would be open to include this if @keqingrong agrees to be the main maintainer of that page.

**Comment by Mugen87** [comment]
Fair enough.

@keqingrong What do you think about @mrdoob suggestions?

**Comment by keqingrong** [comment]
@Mugen87 I am sorry for my late reply and thank you for pointing out the existing problems in my post. It is not sufficiently rigorous and comprehensive, which also reflects that why we need a document or wiki. 

Personally, I hate outdated browser and don't agree to support them. Unfortunately, in the company, the project I am working on need us to support IE9. We found that with some polyfills three.js can still work fine.😀

@mrdoob Thank you! Frankly speaking, I am bad at English, but I will try my best to refine it.

**Comment by mrdoob** [comment]
Feel free to do a Pull Request then 👌
