### ISSUE TITLE
ExtrudeGeometry: Used options.arrays in spite of being undefined

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#12721]
Inside of `if ( ! options.arrays )` the undefined value is used:

https://github.com/mrdoob/three.js/blob/ba37015a2f5d89f5c77d1e00e779b800c110fd83/src/geometries/ExtrudeGeometry.js#L750

Should be:

		this.addAttribute( 'uv', new Float32BufferAttribute( uvArrays, 2 ) );

The code path is probably not taken usually, as this makes the function to fail?

**Comment by Mugen87** [comment]
Good find! This wasn't noticed because `.addShape()` is normally only used by `ExtrudeBufferGeometry`. In this case `options.array` is never `undefined`. 

It is actually questionable if methods like `.getArrays()`, `.addShapeList()` and `.addShape()` needs to be public. The mentioned if-statement only exists because `.addShape()` could be used on an "empty" geometry object.  Not sure such an API is preferable...

Anyway, would you like to do a PR with your fix? That would be great 👍

**Comment by Mugen87** [comment]
But the correct name of the variable is `uvArray`.
