### ISSUE TITLE
My fbx file cant not play animation , but can see model

### ISSUE THREAD

**Issue by wardenfeng** [mrdoob/three.js#12935]
##### Description of the problem 

My fbx file cant not play animation , but can see model ..
I use 3dmax 2013 and export fbx file version 2013 ascii format
And I use 3DMAX 2013 to export the normal playback files you provide and can not play animation again.
my fbx file version 2013.1

##### Three.js version

- [x] Dev
- [ ] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Can you share the fbx file?

**Comment by wardenfeng** [comment]
[xsi_man_skinning.zip](https://github.com/mrdoob/three.js/files/1577799/xsi_man_skinning.zip)

**Comment by looeee** [comment]
Confirmed it's not playing the animation correctly. I'll take a look.

**Comment by wardenfeng** [comment]
@looeee  thanks

**Comment by looeee** [comment]
I've fixed the issue here: #12936. 
Hopefully successfully this time!

@wardenfeng the animation on your model still doesn't play, but loading it up in 3DS Max it doesn't lay correctly there either - it looks like your skin is not properly bound to the skeleton (the skeleton moves but the skin doesn't follow).
