### ISSUE TITLE
Unnecessary THREE.WebGLProgram: gl.getProgramInfoLog()  message

### ISSUE THREAD

**Issue by Prof-Abbott** [mrdoob/three.js#12946]
A trivial detail. I always get blank THREE.WebGLProgram: gl.getProgramInfoLog() warning messages from 18057 of 89 (and equivalents in earlier versions). These would disappear if you change
18055		} else if ( programLog !== '' ) {
to
18055		} else if ( programLog.trim() !== '' ) {

The trim() means we don't get warnings if the InfoLog is a blank space.

It's great to get rid of unnecessary warnings so I can concentrate on all those that are due to my errors.

Or maybe there's a reason why we should be warned if the log gives us a blank space, but I can't think why or what to do about it.

Thanks as always

Steven
##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [X ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Rift

**Comment by looeee** [comment]
This is an ongoing problem, see #11138, and the [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=711520).

Seems to be a case where Chrome people think it's a three.js problem and three.js people think it's a Chrome problem, but it's not a big enough problem for either side to care much.

Maybe it's time we made some more noise over there?

**Comment by Prof-Abbott** [comment]
Except that this is Firefox Quantum for my VR
And the trim() really does seem to be a nice simple fix!

**Comment by mrdoob** [comment]
It is tempting...

**Comment by Fabrice3D** [comment]
Patching this one and the very old json parse bug each new releases...

**Comment by haroldiedema** [comment]
As stated in the related [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=711520), the output of `gl.getProgramInfoLog()` is implementation dependent, meaning the output can differ per OS, per browser and/or even per driver. Applications running in a browser should _not_ depend on the output of this function. 

Since there is no spec that dictates the resulting output of this function, I think it's our problem to solve, since we decide to send this output to the console.

I vote we find the fastest `trim()` method available (also briefly discussed in #11138) and stick with that so we can put this discussion behind us.

**Comment by Mugen87** [comment]
I've created a PR to perform at least a simple trim on the info log messages. This is something we can safely do without any performance hits.
