### ISSUE TITLE
LensFlares : support logarithmic depth

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#13038]
Currently the flares are rendered in a special pass, the code being in the WebGLFlareRenderer. It checks if the lensflares are visible by rendering a depth mask.

However the depth mask shader does not handle the case of the logarithmic depth buffer, causing the flares to be hidden by objects behind them. 

I've started crafting solutions but didn't find something conclusive yet, opening this issue in case someone sees how to go for it.

**Comment by Mugen87** [comment]
FYI: `WebGLFlareRenderer` has been removed, see #13081

Any changes needs to be done in `examples/js/objects/LensFlare.js`

**Comment by Astrak** [comment]
I'd love to ! Will do in feburary if noone did earlier.

**Comment by Mugen87** [comment]
I recently realized that adding shader chunks to the lens flare shaders is not sufficient in order to support logarithmic depth buffer. All shaders are based on `RawShaderMaterial`. Hence, defines like `USE_LOGDEPTHBUF` and `USE_LOGDEPTHBUF_EXT` are not automatically set by the renderer. To be more precise, `WebGLProgram` does only set custom defines for materials of type `RawShaderMaterial`.

**Comment by Tazshelby2016** [comment]
What is the state of this issue? It seems to be stale, and possibly able to be closed.
