### ISSUE TITLE
Logarithmic depthbuffer not working correctly on devices that do not support EXT_frag_depth

### ISSUE THREAD

**Issue by Avocher** [mrdoob/three.js#13047]
##### Description of the problem

Surfaces "bend" and disappear after the latest update to support logarithmic depthbuffer on devices that do not support EXT_frag_depth with logarithmicDepthBuffer set to true.

https://jsfiddle.net/dz37428b/7/

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [x] iOS

**Comment by WestLangley** [comment]
>Surfaces "bend" and disappear

Can you provide a screenshot?

>after the latest update to support logarithmic depthbuffer

What "update" are your referring to? Did it work prior to that update?

>Chrome

Chrome only?

**Comment by Avocher** [comment]
Here's a screenshot from the fiddle ![screenshot](https://user-images.githubusercontent.com/4103154/34662513-e6c15b60-f459-11e7-9140-a043db205f19.jpg) 

I'm guessing it indirectly happened after this pull request https://github.com/mrdoob/three.js/pull/11995 

I only had chrome/safari on my test devices so i checked those, I can install firefox if you want.

**Comment by WestLangley** [comment]
OK, there is no "bending". What you are seeing are depth-buffer artifacts close to the near plane.

The issue is discussed [here](http://outerra.blogspot.com/2009/08/logarithmic-z-buffer.html), and the work-around is to tessellate your geometry -- both boxes in this case.

As stated in the title to this post, the logarithmic depth buffer artifacts occur on devices that do not support the `EXT_frag_depth` extension, and for which we are handling the logarithmic depth buffer in software.

Fiddle showing the issue: 
https://jsfiddle.net/ynom3pgu/ ( or for mobile viewing, https://jsfiddle.net/ynom3pgu/show )

three.js r.90dev

**Comment by Avocher** [comment]
I see, 
Sadly tessellation is not an option for me as I have little to no control over the assets, so I'll just fall back to linear depth buffer when needed. 

Thank you so much @WestLangley for helping me out.
