### ISSUE TITLE
object3D.getWorldRotation() does not callback to set the quaternion of the optional target

### ISSUE THREAD

**Issue by mysteryDate** [mrdoob/three.js#13076]
`object3D.getWorldRotation()` does not set the update flag to true for the target rotation. This results in some pretty weird behavior, as `object.getWorldRotation(target.rotation)` behaves differently than `object.getWorldQuaternion(target.quaternion)`:

  https://codepen.io/mysterydate/pen/mpXzad?editors=0010

  Changing the third argument to `true` here would fix it:

  https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L485

  Though I'm not sure if there's an explicit reason for not calling the callback here.

**Comment by WestLangley** [comment]
Thanks for this.

>Though I'm not sure if there's an explicit reason for not calling the callback here.

Maybe not, anymore...

There is another problem, though. Instead of this:
```javascript
return result.setFromQuaternion( quaternion, this.rotation.order, false );
```
it should be
```javascript
return result.setFromQuaternion( quaternion, undefined, true );
```
We do not want the change the rotation order here.

@mrdoob Maybe you recall, `object.rotation.order` used to be a separate property `object.eulerOrder.` There are remnants of that former design in the code. For example,
```javascript
Euler.setFromRotationMatrix( m, order, update )
Euler.setFromQuaternion( q, order, update )
Euler.setFromVector3( v, order )
```
I'm thinking `order `should no longer be an argument in these methods ( at least the first two ). It doesn't hurt, but I would implement it differently now.

**Comment by mrdoob** [comment]
Oh man... I hate this code... 😅

I kind of would prefer to find ways to remove `rotation` and `Euler` altogether than trying to fix it.

For this particular case... maybe we should remove `getWorldRotation()` and encourage `getWorldQuaternion()` usage instead?

**Comment by WestLangley** [comment]
>maybe we should remove getWorldRotation() and encourage getWorldQuaternion() usage instead?

Fine with me. I'm all for that!
