### ISSUE TITLE
Error when calling mixer.clipAction()

### ISSUE THREAD

**Issue by apostololeg** [mrdoob/three.js#13167]
I have my model `cube.gltf`, that contains some animations named “jump” and “rotate”.
Animations playing correctly, but when I use `mixer.clipAction('jump')`, the error is throwing:

**TypeError: Cannot read property 'length' of undefined**

![2018-01-24_14-35-03](https://user-images.githubusercontent.com/514713/35332669-d04394c8-011c-11e8-8932-9ad6496eabd7.png)

```js
// loop();
var delta = clock.getDelta();

mixer.clipAction('jump').setEffectiveWeight(.2);
mixer.update(delta);
```
[TEST REPO](https://github.com/apostololeg/gltf-animation-test/tree/master) includes tests-case for:
  * GLTFLoader from [master](https://github.com/apostololeg/gltf-animation-test/commit/da2c0dcf98449615811590f99b30fbae71d624df) and [dev](https://github.com/apostololeg/gltf-animation-test/commit/d42a29146b5448bb5256b1e42a28b1fa3a441587) branches
  * [LegacyGLTFLoader](https://github.com/apostololeg/gltf-animation-test/tree/LegacyGLTFLoader)

##### Three.js version
- [x] Dev
- [x] r89

##### Browser
- [x] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS
- [x] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
After looking at your code, i'm afraid to say that you are not using `AnimationMixer` correctly. If you call `mixer.clipAction( 'rotate' )`, the root object of the mixer needs the animations attached to its geometry or to itself. This is not the case in your application. You should do something like this:

```javascript
const object = gltf.scene;
object.animations = gltf.animations;

mixer = new THREE.AnimationMixer( object );

object.animations.forEach( animation => {

   mixer.clipAction( animation ).play();

} );
```
Your subsequent calls of `clipAction()` will work then. Besides, I can see multiple problems in your scene:

- You are not adding the loaded `glTF` object to the scene.
- Use `WebGLRenderer` instead of `CanvasRenderer`

Please visit the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by apostololeg** [comment]
Code, that you wrote, already [exist in my app](https://github.com/apostololeg/gltf-animation-test/blob/master/index.js#L54-L60).

> You are not adding the loaded glTF object to the scene.

fixed, but error still throwing

> Use WebGLRenderer instead of CanvasRenderer

for what ?
I changed my code to use WebGLRenderer, but error still throwing

**Comment by donmccurdy** [comment]
Please post to the forum, we can help there.
