### ISSUE TITLE
MTLLoader:preload -- support for callback

### ISSUE THREAD

**Issue by boyravikumar** [mrdoob/three.js#13336]
After loading the some.mtl from a location using MTLLoader, we call preload of MTLLoader to create materials and trigger loading of the textures if any. When doing so, we don't have a callback facility to let us know that the material textures are downloaded and ready. It would be great if we have a callback facility for the same

##### Three.js version

- [x] Probably all of them
- [ ] Dev
- [x] r89

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by arquilca** [comment]
You can look into setting a Loading Manager. Check out the [loading manager example on three.js docs](https://threejs.org/docs/#api/loaders/managers/LoadingManager).

**Comment by boyravikumar** [comment]
I went through the examples given there which are below.

[WebGL / loader / babylon](https://threejs.org/examples/#webgl_loader_babylon)
[WebGL / loader / fbx](https://threejs.org/examples/#webgl_loader_fbx)
[WebGL / loader / obj](https://threejs.org/examples/#webgl_loader_obj)
[WebGL / materials / reflectivity](https://threejs.org/examples/#webgl_materials_reflectivity)
[WebGL / postprocesing / outline](https://threejs.org/examples/#webgl_postprocessing_outline)
[WebGL / terrain / dynamic](https://threejs.org/examples/#webgl_terrain_dynamic)


None of the above have the MTLLoader example. 

Also, to my understanding, the Loading managers are available for loading obj , mtl, texture etc.. and is perfectly fine.

When its comes to MTLLOader, it returns MaterialCreator instance on loading. On this instance we call preload method to create the actual material. And my point is that this does not have callback support.

Hope i am clear on this.

**Comment by Mugen87** [comment]
> And my point is that this does not have callback support.

I think when you create an instance of `LoadingManager` and pass it to the constructor of `MTLLoader`, it's possible to use the respective `onLoad()` in order to wait until all resources are loaded.

Let's say you issue a single request to a `mtl` file. The `onLoad()` callback of `LoadingManager` only fires when the `onLoad()` callback of `MTLLoader` has completed. If you call `materials.preload();` inside the `onLoad()` callback of `MTLLoader`, new network requests are issued in order to load the corresponding textures. These requests will raise the internal request counter of `LoadingManager`. As soon as all textures are loaded, `onLoad()` callback of `LoadingManager` will fire.

Please give it a try and see what's happen :blush:

**Comment by Mugen87** [comment]
@boyravikumar The usage of `LoadingManager` should solve the problem. You can reopen the issue if you think that there is a bug. In this case, please provide a little [live example](https://jsfiddle.net/f2Lommf5/) to demonstrate the problem.

**Comment by boyravikumar** [comment]
@Mugen87 . Great that you have closed this. I tried with loading manager. Yes, by using Manager i am able to call onLoad after calling the preload method. Should we mention in documentation/ an example where its use absolutely demonstrated.
