### ISSUE TITLE
GLTF exported by Three.js cannot import into Facebook 3D post

### ISSUE THREAD

**Issue by Ben-Mack** [mrdoob/three.js#13380]
Facebook recently annouced 3D post, with ability to view GLTF file on new feed.

I tried this GLTF binary sample, it working fine ( https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMilkTruck/glTF-Binary )

But GLB file exported from this Three.js example ( https://threejs.org/examples/?q=gltf#misc_exporter_gltf ) is not working, Facebook return this error: 

> GLB File Invalid: 3D Model Not Posted | Your 3D model could not be posted as it contains features we don't support, is of a file type we don't support, or contains errors

_

GLTF model validation by Facebook: https://developers.facebook.com/tools/3d/validation

Tutorial on how to upload GLTF file to Facebook: https://developers.facebook.com/docs/sharing/3d-posts#creating-3d-posts

**Comment by donmccurdy** [comment]
Testing Editor exports with their validator, I'm seeing this:

| screenshot |
|---|
|  ![screen shot 2018-02-20 at 8 44 25 pm](https://user-images.githubusercontent.com/1848368/36463451-e6b4f1b2-167e-11e8-9f97-b44965ede7a7.png) |

Running the same model through the official validator, I see:

```
GLB_CHUNK_LENGTH_UNALIGNED | Length of 0x4e4f534a chunk is not aligned to 4-byte boundaries.
-- | --
```

... which was partially fixed with #13220, I guess there was another warning for GLB.  I'm a little surprised that's an issue though, as three.js can render it anyway, but let's try fixing that and see if it's the problem.

**Comment by donmccurdy** [comment]
Another validation warning when there is a camera, which our demo includes (but Facebook has stated in the FAQ they don't support cameras in the GLB, anyway) —

![screen shot 2018-02-20 at 8 49 36 pm](https://user-images.githubusercontent.com/1848368/36463573-a7a630ca-167f-11e8-92d9-638976696034.png)

**Comment by mrdoob** [comment]
Closing in favour of #13397
