### ISSUE TITLE
gl.clear not working with cached state masks

### ISSUE THREAD

**Issue by szhuchkov** [mrdoob/three.js#13448]
##### Description of the problem

gl.clear would not clear render target if state mask is currently set (i.e. by previous material)

https://github.com/mrdoob/three.js/blob/e2e6b079e00f811cf41755ee8342914ed77ea107/src/renderers/WebGL2Renderer.js#L101

##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Can you please provide sufficient context so the issue can be reproduced? A live demo would be helpful.

**Comment by Mugen87** [comment]
I've tried to create a fiddle of your code but i've realized you've missed to copy the corresponding vertex and fragment shader.

Please setup a live example so it's easier for us to debug your code: https://jsfiddle.net/f2Lommf5/

**Comment by szhuchkov** [comment]
https://jsfiddle.net/f2Lommf5/2184/

**Comment by Mugen87** [comment]
I revisited this issue and I think there is a bug in `three.js`. The problem is that the renderer executes `Scene.onAfterRender()` too. If users performs rendering operations in the callback, they overwrite the final settings for the depth and color buffer (see comment):

https://github.com/mrdoob/three.js/blob/20378c580057b6dde297dddc3f9e2064485a9757/src/renderers/WebGLRenderer.js#L1220-L1228

The problem is the OP performs a rendering with a material where `depthWrite` is set to false and thus overwrites the setting. Subsequent clears to not work properly anymore. The solution is to execute `Scene.onAfterRender()` a little bit earlier.

**Comment by Mugen87** [comment]
@szhuchkov Sorry that it takes over a year to fix the issue 😅 . Better late than never^^!
