### ISSUE TITLE
Best Importer - FAQ fill request

### ISSUE THREAD

**Issue by jfpferreira** [mrdoob/three.js#13508]
##### Description of the problem

In the FAQ section of the documentation, there is this question:

> Which Import Format/Exporter is best supported?

This question intrigued me, since there are so many available importers, so I tried to search for an answer to this question. After browsing a bit I saw that there were a couple of them available:

- https://github.com/mrdoob/three.js/issues/580
- https://stackoverflow.com/questions/11243689/preferred-3d-model-format-of-three-js

But these are a bit outdated, dating as far as 7 years ago. So I would like to know the answer to this question, and if possible, have this section of the documentation filled.

I think having this question filled, would also be valuable for a lot of developers using this library.

##### Three.js version

- [x] Dev
- [ ] r90
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
@looeee has written an interesting post some time ago. Maybe we can use this as a basis in order to answer the question.

https://discourse.threejs.org/t/advise-a-newbie-on-applications-that-can-be-used-to-prepare-models/899/2

Since the question "Which Import Format/Exporter is best supported?" is still marked as a todo, i'll consider this issue as a feature request.

**Comment by Mugen87** [comment]
We rephrased the question and added an answer. I hope user are now pointed to the right direction.
