### ISSUE TITLE
Bug when combining renderer.vr with clipping planes

### ISSUE THREAD

**Issue by hamishtodd1** [mrdoob/three.js#13535]
I have some clipping planes. Standard usage: array of planes, given to the material. Mostly works fine.

Problem: when I use it in VR, I get a different result for my left eye and right eyes! It is off to the "left" of my head. I am guessing this is not on my end, and happenning because the positions of the clipping planes are affected by the camera position.

http://jsfiddle.net/bar2jhbm/10/ - you might need to look down?

(thank you for being awesome)

**Comment by feiss** [comment]
:_(

**Comment by hamishtodd1** [comment]
My current workaround is to not use .vr. Instead I do it the 2015 way: THREE.VREffect, THREE.VRControls.js

**Comment by dmarcos** [comment]
@hamishtodd1 We are observing the same problem. Any downsides perf or otherwise when going back to THREE.VREffect and THREE.VRControls?

**Comment by hamishtodd1** [comment]
None I saw. Pretty sure they are equivalent behind the scenes!

**Comment by Mugen87** [comment]
It is definitely slower since `THREE.VREffect` processes the whole scene twice (or per eye). `WebXRManager`/`WebVRManager` avoid this CPU overhead by ensuring that many tasks are done only once per frame (update scene graph, render lists, shadow maps  etc.).

**Comment by dmarcos** [comment]
@Mugen87 Thanks or info. We're also considering accepting the trade off and temporary go back to VREffects and VRControls since there are several outstanding issues that affect us like this one, [premature clipping](https://github.com/mrdoob/three.js/issues/13236) or [postprocessing](https://github.com/mrdoob/three.js/pull/14274). Happy to help with any of those if you have any particular solution in mind. I have little experience on those areas.
