### ISSUE TITLE
WebVRManager variables undefined

### ISSUE THREAD

**Issue by flerokoo** [mrdoob/three.js#13739]
Hey!

I don't have a VR set compatible with Windows to check it in real conditions, but it seems that there's a problem with WebVRManager (i am using[ WebVR API Emulation](https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil))
 
```js
function onVRDisplayPresentChange() {

	if ( device !== null && device.isPresenting ) {

		var eyeParameters = device.getEyeParameters( 'left' );
		var renderWidth = eyeParameters.renderWidth;
		var renderHeight = eyeParameters.renderHeight;

		currentPixelRatio = renderer.getPixelRatio();
		currentSize = renderer.getSize();

		renderer.setDrawingBufferSize( renderWidth * 2, renderHeight, 1 );

	} else if ( scope.enabled ) {

		// currentSize and currentPixelRatio is undefined here
		renderer.setDrawingBufferSize( currentSize.width, currentSize.height, currentPixelRatio );

	}

}
```

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I guess this problem is related to the Chrome extension. In a normal setup, `currentSize` and `currentPixelRatio` can't be undefined since the code in the previous if statement is executed before. 

In other words: An application starts in "not-presenting" state. The mentioned problem is caused since (for whatever reason) the app starts in presenting state and goes to non-presenting. I think there must be a problem in the VR emulation...

**Comment by RemusMar** [comment]
> i am using WebVR API Emulation

These days the internet is bloated with all kind of "open source" projects and JS libraries.
In this case the developer email adress tells almost everything:
Developer Email:  hello@clicktorelease.com

**Comment by flerokoo** [comment]
Oh, for some reason I thought that this extension is `official` way to debug WebVR apps.
I guess this issue can be closed now.
