### ISSUE TITLE
Allow access to the same WebGLRenderer texture across multiple WebGLRenderer instances

### ISSUE THREAD

**Issue by funwithtriangles** [mrdoob/three.js#13745]
Currently, if we want to have two canvases in an application, they need to be rendered by two different renderers. There are some tricks that can be used [involving one large canvas](https://threejs.org/examples/webgl_multiple_elements.html) but this isn't always suitable (e.g. across different windows / complex UI interfaces).

If the two renderers want to share the same instance of a `WebGLRenderTarget`, it needs to be rendered two times, once for each renderer.

```javascript
// Single Render target
const renderTarget = new THREE.WebGLRenderTarget(width, height)

...

// Materials being used across different renderers, both using the same render target
const scene1Material = new THREE.MeshBasicMaterial({map: renderTarget.texture})
const scene2Material = new THREE.ShaderMaterial({
  vertexShader: vert,
  fragmentShader: frag,
  uniforms: {
    tDiffuse: { value: renderTarget.texture }
  }
})

...

// Render mainScene to renderTarget
renderer1.render(mainScene, mainCam, renderTarget)
// fooScene uses renderTarget for material
renderer1.render(fooScene, fooCam)
  
// Would be nice to not have to do this rendering again
renderer2.render(mainScene, mainCam, renderTarget)

// barScene uses renderTarget for material
renderer2.render(barScene, barCam)
```

It would be useful to make `renderTarget.texture` available to `renderer2` after it has already been rendered by `renderer1`.

[Live example of the issue](https://jsfiddle.net/vm4cs2ny/32/)

**Comment by Mugen87** [comment]
I guess this is not possible since `WebGLRenderer` caches stuff like the [WebGLTexture](https://developer.mozilla.org/en-US/docs/Web/API/WebGLTexture) object. I don't think it's a good idea if `WebGLRenderer` exposes its cache so another instance of `WebGLRenderer` can use it. Same for a shared cache. I suggest you try to find a solution with just a single renderer.

BTW: Have you seen these examples? They use not a single large canvas but multiple ones.

https://threejs.org/examples/#webgl_multiple_canvases_grid
https://threejs.org/examples/#webgl_multiple_canvases_complex

**Comment by funwithtriangles** [comment]
This is exactly what I needed, thanks. Hadn't really considered the idea of rendering then copying pixels to canvas A, rendering again then copying pixels to canvas B.

[Updated fiddle](https://jsfiddle.net/vm4cs2ny/49/) to show how this is done

**Comment by Mugen87** [comment]
Thank you for the updated fiddle and the useful comments!
