### ISSUE TITLE
GLTFLoader: Models created with COLLADA2GLTF+Draco fail

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#13870]
See @cx20's comment: https://github.com/donmccurdy/three-gltf-viewer/issues/70#issuecomment-366518635

```
DRACOLoader.js:188 THREE.DRACOLoader: Decoding failed: Failed to decode geometry data.
```

**Comment by donmccurdy** [comment]
Looks like an old version of Draco in COLLADA2GLTF: https://github.com/KhronosGroup/COLLADA2GLTF/issues/178.

**Comment by cx20** [comment]
I created a [Draco format file](https://github.com/KhronosGroup/COLLADA2GLTF/files/1935196/Duck_glTF-Draco.zip) with the [latest version](https://ci.appveyor.com/api/buildjobs/a6q3j6tw5e9uttky/artifacts/cmake-build%2FCOLLADA2GLTF-update-windows-Release-x64.zip) of COLLADA2GLTF and confirmed that it will be displayed in [Three.js](https://gltf-viewer.donmccurdy.com/) and [Babylon.js](https://sandbox.babylonjs.com/).
Because it is a problem of COLLADA2GLTF (version of included Draco library), it was not Issue of Three.js.

**Comment by jackcaron** [comment]
If you have UVs on your model, you have to select the right encoding method:
```javascript
encoder.SetEncodingMethod(
  encoderModule.MESH_SEQUENTIAL_ENCODING
);
```
otherwise the decoder always fails!
