### ISSUE TITLE
OBJLoader + MTLLoader texture VS color issue

### ISSUE THREAD

**Issue by ranbuch** [mrdoob/three.js#13923]
##### Three.js version

- [ ] Dev
- [ ] r92
- [x] r90

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

As @Mugen87 suggested [here](https://discourse.threejs.org/t/objloader-mtlloader-not-loading-texture-image/2534) I'm submitting this issue regarding Material color effecting the Texture color.

I can confirm that changing the THREE.Color RGB from (0,0,0) to (1,1,1) does resolve this issue but, as you can see on the link above, that issue does not occur on Blend4Web or Sketchfab.

I thought that the reason may be multiplying any value with 0 will always resolve in 0 but changing it (on debugger) to (0.01, 0.01, 0.01) didn't resolved this issue.

**Comment by ranbuch** [comment]
According to this [link](http://paulbourke.net/dataformats/mtl/):

```
Specifies that a color texture file or color procedural texture file is 
linked to the diffuse reflectivity of the material.  During rendering, 
the map_Kd value is multiplied by the Kd value.
```

Looks like everybody else has a bug and three-js is actually doing what it supposed to do.
0 multiplied by anything is 0 . . .
my `mtl` file:
```
newmtl Tshirt04:lambert1SG
illum 4
Kd 0.00 0.00 0.00
Ka 0.00 0.00 0.00
Tf 1.00 1.00 1.00
map_Kd 27.jpg
Ni 1.00
newmtl polySurface20SG
illum 4
Kd 0.00 0.00 0.00
Ka 0.00 0.00 0.00
Tf 1.00 1.00 1.00
Ni 1.00
newmtl polySurface20SG1
illum 4
Kd 0.00 0.00 0.00
Ka 0.00 0.00 0.00
Tf 1.00 1.00 1.00
Ni 1.00
```
As you can see in the `Tshirt04:lambert1SG` partition the `Kd` is `0.00 0.00 0.00`

@Mugen87 please close this issue if you agree with me.

**Comment by Mugen87** [comment]
> Looks like everybody else has a bug and three-js is actually doing what it supposed to do 

:tada:

**Comment by richard-smith-preservica** [comment]
I'm seeing this issue with more recent OBJ packages; I think there are still exporters out there which are doing this.

Although I accept that Three is technically correct and everyone else is wrong, I think it would be useful for Three's MTL loader to (at least optionally) detect situations where Kd=0 and a texture is specified (i.e. a map_Kd is present), and ignore the Kd values. That should be tightly enough specified to only catch this specific use case while allowing intentional blending with Kd, or a genuinely black non-textured material.

**Comment by richard-smith-preservica** [comment]
Oh, I just discovered you already did this :D 

    mtlLoader.setMaterialOptions( { ignoreZeroRGBs: true } );
