### ISSUE TITLE
Ammo js volume example works extremely slow

### ISSUE THREAD

**Issue by schechenkin** [mrdoob/three.js#14240]
https://threejs.org/examples/?q=ph#webgl_physics_volume
3-4 fps

##### Three.js version

- [ ] Dev
- [x] r93
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I'm unable to reproduce. The example runs with 60fps on my iMac (10.13.5) and Chrome 67.0.3396.79.

Do you have performance issues with other examples, too?

**Comment by Usnul** [comment]
please address ammo.js project for ammo.js related problems:
https://github.com/kripken/ammo.js

Alternatively, address bullet project if the issue is not related to c++ interface binding:
https://github.com/bulletphysics/bullet3

If the issue is not reproduceable with bullet - consider addressing emscripten project regarding cross-compilation issues:
https://github.com/kripken/emscripten

Finally, if you're looking for support - this ain't the right place.
