### ISSUE TITLE
THREE.OrbitControls set screenSpacePanning = true BUG???

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#14327]
When I set the screenSpacePanning property of OrbitControls to true, I use the mouse wheel to operate, but when I zoom in to a certain level, zooming and panning become very, very slow. Seeing the relevant documents can not find the answer, it seems that the property maxDistance = Infinity Setting it to infinite has no effect. I hope I can get an answer. Thank you very much!

**Comment by Usnul** [comment]
please make fiddle.js example or similar. Your explanation is not very clear.

Also, it seems from your text that you are asking for help, if that's the case please use support channels instead of writing a github issue.

**Comment by WestLangley** [comment]
@xjindf Regardless of the panning mode, it is true that the closer the camera is to the target, the slower panning will be. This is desirable.

Maybe the panning sensitivity as a function of distance from the target needs to be improved.

As a workaround, you can set `controls.minDistance` to prevent the camera from getting too close.

**Comment by indus** [comment]
I think the problem is that panning gets handled in in a seperate "panOffset" and there is no connection with what zooming does. Nevertheless you can make a similar move with both. But doing a move with one and doing the opposite move with the other doesn't cancle out.
Lets say you are zoomed in 95% to your target, then pan away from it and then try zoom back in to it you won't succeed . Right now this control can't be used to for e.g. to pan freely over a map. But thats what it says here in the deprecation notice: https://github.com/donmccurdy/THREE.MapControls

Another related effect is that you can easily over- or undershoot the min- and maxDistances properties by panning.
