### ISSUE TITLE
a problem about buffergeometry flatShading:true

### ISSUE THREAD

**Issue by zch1234qq** [mrdoob/three.js#14381]
I have producted a buffergeometry with the great js-lab.and,i set the material as "new THREE.MeshLambertMaterial({flatShading:true});",but,i found it didn't work.oh,hoping somebody can help me!

**Comment by Usnul** [comment]
Wrong place to come for help buddy, try forums, stackoverflow or discord instead.

**Comment by zch1234qq** [comment]
thank u,a guiding answer.

**Comment by Mugen87** [comment]
Here is the link to the forum: https://discourse.threejs.org/

**Comment by WestLangley** [comment]
Why is this considered a help question?

**Comment by Mugen87** [comment]
You mean because `flatShading` has not effect for `MeshLambertMaterial`?

**Comment by WestLangley** [comment]
Without expressing my opinion, I was just curious as to why this is considered a help question.

**Comment by mrdoob** [comment]
Should we do `delete this.flatShading;` in the `MeshLambertMaterial` so a warning gets displayer in the console if someone tries to set `flatShading`?

**Comment by Mugen87** [comment]
Or we delete the flag from `Material` and only add it to certain materials. In context of inheritance, it's the more valid approach from my point of view.

**Comment by WestLangley** [comment]
I think this is a reasonable question for a user to ask.

Since `MeshLambertMaterial` has a `flatShading` property, it is reasonable to expect it to work.

I think if a user is directed to a help site, a responsible person should go there and answer the question. It has been two months now, and the user still has no answer.

https://discourse.threejs.org/t/why-a-flatshading-true-dosent-work/3259

**Comment by Mugen87** [comment]
Sry, the question was overlooked. I've added an answer with a live example and a reference to #7130.
