### ISSUE TITLE
webgl_geometry_text.html needs to be revisited

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#14549]
`webgl_geometry_text.html` needs to be modified to use `TextBufferGeometry`. That's easy.

But normals are ["fixed"](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_geometry_text.html#L381-L423) in this demo for some reason.

Normals should be correct to begin with... one would think.

**Comment by Mugen87** [comment]
The problem is that `computeVertexNormals()` is called:

https://github.com/mrdoob/three.js/blob/6d492ed3ae5878fa1c670e8a8d2d69f08d39add4/examples/webgl_geometry_text.html#L381

This is done to avoid the flat shaded sides like in this screenshot:

![image](https://user-images.githubusercontent.com/12612165/43272973-8d24553c-90fb-11e8-8a99-09a8d0bd7b92.png)

Since the current code in the example is a hack, I would prefer to remove it. The flat shaded sides are not that bad...

**Comment by Mugen87** [comment]
Um, since the current code in the example is a hack, I think it would be better to remove it and accept the flat shaded sides.

**Comment by WestLangley** [comment]
Thanks, @Mugen87. So the hack was to remove the faceted sides... I wonder if text geometry can be improved so that (for the sides only) neighboring vertex normals are "the same" if the face normals are "close". Maybe add an experimental `smoothEdges` flag  or `edgeSmoothness` property.

It would be great if we could get rid of the faceted edges, without messing something else up.

**Comment by Mugen87** [comment]
Then I think the new flag should be placed in `ExtrudeBufferGeometry`.

https://jsfiddle.net/f2Lommf5/10321/
