### ISSUE TITLE
Materials: Consider to use mediump for all shaders

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#14570]
##### Description of the problem

Right now, the default precision for shader progams in `three.js` is `highp`. Issues like #14137 showed that this approach causes rendering problems especially on (older) mobile devices . Using `mediump` would solve these issues and also improve the performance of the shader execution on mobile, see https://github.com/mrdoob/three.js/issues/14137#issuecomment-397850032.

The problem is that certain materials like `MeshStandardMaterial` can not produce correct visual output with `mediump` right now, see https://github.com/mrdoob/three.js/issues/14137#issuecomment-397856954. Changing certain parts of the shader souce code is necessary to solve this issue.

##### Three.js version

- [x] Dev
- [x] r94
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by greggman** [comment]
`mediump` won't solve all issues AFAIK. I'm pretty sure (but could be wrong) if you check lighting using `mediump` you'll find things don't render correctly? At least that was my experience with my own shaders. For Phong shading passing the vertex viewPosition to the fragment shader in mediump means there's actually not enough resolution to do the math and what you see is not remotely correct.

It's not checkable on desktop because even putting mediump on desktop uses highp.

Of course maybe it's better than black. One solution is to use highp if it's supported, something like

```
#if GL_FRAGMENT_PRECISION_HIGH
   precision highp float;
#else 
  precision mediump float;
#endif
```

or other contortions so at least you don't get black?

**Comment by mrdoob** [comment]
> One solution is to use highp if it's supported

In the issue that @Mugen87 referenced, the devices supported highp but it had glsl bugs when using highp that the conformance test didn't cover.

**Comment by greggman** [comment]
If three defaults to mediump you'll basically get incorrect rendering on all phones because at the moment all phones (99%) will actually use mediump if you ask for it. At mediump the lighting will be wrong.

If it's just one bad phone then I'd suggest you ask the WebGL people to add a test and then blacklist that phone until they fix it (or get them to make that phone not report it can support highp).

**Comment by greggman** [comment]
Example:

highp correct lighting

<img width="1080" alt="highp-correct-lighting" src="https://user-images.githubusercontent.com/234804/43352753-6ed6b9f8-9263-11e8-9716-3819a8c92095.png">

mediump incorrect lighting (same scene)

![mediump-incorrect-lighting](https://user-images.githubusercontent.com/234804/43352759-7f9d1656-9263-11e8-8487-aa57d6092ff1.png)

**Comment by greggman** [comment]
Haha, actually testing three is already using the wrong lighting on iOS. My iPhoneX supports highp but three opts to use mediump anyway and gets the incorrect lighting. 😅

I'm guessing that was intentional?

**Comment by Mugen87** [comment]
Unity says for custom shader development:

_A general rule of thumb is to start with half precision for everything except positions and texture coordinates. Only increase precision if half precision is not enough for some parts of the computation._

https://docs.unity3d.com/Manual/SL-DataTypesAndPrecision.html

**Comment by Supernuija** [comment]
I can confirm what @Mugen87 said about using `mediump` as default would be a great idea! 
This is also an issue with Adreno 306 gpu phones and interestingly a newer of the same phone model, Samsung J5(2016) renders all materials black using `highp` and the older 2014 version with same Adreno 306 gpu renders them correctly. Also I did find that in an older Sony Xperia Z2 pad, `highp` rendered correctly with Chrome but not with Firefox. 
This seems to be an endless swamp, if three.js defaults to `highp` instead of `mediump`. No one knows how many users have either drivers, gpu:s or browser versions that will not support correct material rendering. With this simple setting many problems would be solved instantly IMHO.

**Comment by Mugen87** [comment]
I don't think the engine should implement such checks. If a device says it supports `highp`, the engine should rely on this support. Otherwise the device/driver needs a fix.

The idea of this issue is to investigate whether it is possible to add `mediump` support to materials. If this works, apps can configure `Material.precision` in order to force `mediump` on certain devices. This is currently not possible because of the above rendering issues.

**Comment by Supernuija** [comment]
Knowing closely how eager all mobile device manufacturers are to implement this kind of fixes on any older mobile devices, I would still try to ensure that three.js displays all content properly despite the mobile device hw/sw developers. 

If we would live in a perfect world, these kind of things would always be fixed. As long as the manufacturer's main business driver is to force users constantly buy new devices (designed obsolescense), any kind of fixes on older hardware drivers is practically none, especially in mobile devices. In order to guarantee functionality on as many devices as possible by default, no matter how badly others have done their homework, it would be strongly recommended that framework would probe in this case what is really possible and what's not.

**Comment by Supernuija** [comment]
Just found out that Adreno 330 has this same render black issue using `highp`, but only with Firefox, Chrome renders correctly.

**Comment by LeviPesin** [comment]
Maybe we can create a list of issues that appear when using `mediump`, like https://github.com/mrdoob/three.js/issues/25071 (maybe based on https://github.com/mrdoob/three.js/pull/22003) and then solve them one-by-one?

**Comment by mrdoob** [comment]
I'm thinking this is something that is not that relevant/needed nowadays...

**Comment by Mugen87** [comment]
Yeah, I think the amount of devices which only support `mediump` is not relevant anymore. 

However, there is the valid use case that application request `mediump` on mobile devices and things start to break. Maybe you can use the same strategy like for solving #25071: Identifying the code which is not compatible with `mediump` and explicitly define `highp` for the respective scope/variable.

**Comment by mrdoob** [comment]
That sound good 👍

**Comment by LeviPesin** [comment]
Related: https://github.com/mrdoob/three.js/pull/8353

**Comment by krei-se** [comment]
I have a device with this issue and would love a fix for this.

Adreno Chrome <-- hehe.

**Comment by mrdoob** [comment]
I don't think we'll end up doing this...
