### ISSUE TITLE
SoftwareRenderer: Add support for BufferGeometry

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#14581]
Is there demand for this?

**Comment by mrdoob** [comment]
I think so.

**Comment by Usnul** [comment]
what are thoughts on GLSL interpretation? Excluding extensions - it should be viable. As things stand, software renderer has quite a number of limitation already.

I wrote Sampler2D-like implementation in JS a while back to manipulate textures, main issue for me was filtering, but it was not that hard in general.

**Comment by mrdoob** [comment]
To be honest, I think I would prefer to start the `SoftwareRenderer` from scratch (back to spans?). The current code is probably the most efficient, but it's hard to maintain. Adding a glsl implementation would make things even harder... 😕

**Comment by Usnul** [comment]
@mrdoob 
Whenever glsl implementation would make things easier or harder depends on a few things. What I propose is streamlining the implementation of three.js. If you have a JS rasterizer that understands GLSL - you get many things for free and you can focus more effort on common parts of three.js, instead of maintaining 2 completely separate implementations. It's like Intermediate Representation languages - they take some effort to put in place, but they make support of different target platforms that much easier.

A full-blown WebGLContext emulation would be amazing, but getting to the point where we get more code re-use across different targets is already a use plus.

Having a software rasterizer need not be three.js effort entirely, it can be based on existing tools/libraries perhaps.

**Comment by mrdoob** [comment]
Wouldn't it be better to port SwiftShader to WebAssembly or something?

Just like with `CanvasRenderer` and `SVGRenderer`, I think it's better to explore what makes each render unique.

**Comment by Usnul** [comment]
This is divergence. Uniqueness is a wonderful thing, except it brings complexity and breaks ubiquity. Complexity is generally a thing most successful engineers try to avoid, it puts burden on your mind as a person doing the implementation and it puts burden on everyone down the line also, in form of complex documentation with gotchas etc. Ubiquity is quite similar, you say - "ok, i have my gltf model with BPR material and skinned animation, lets just switch to CanvasRenderer instead of WebGLRenderer" - whoops.... I don't think it's a bad thing to have various Renderer implementations, but if we could share shader code between them - it would be a tremendous benefit.

**Comment by mrdoob** [comment]
We actually have a bit of confusion already with people using `CanvasRenderer` for no reason (I think because they like one of the examples)...

**Comment by Mugen87** [comment]
Yeah. Especially since the docs explicitly say that `CanvasRenderer` is deprecated.

https://threejs.org/docs/index.html#examples/renderers/CanvasRenderer

 I would consider renderers like `CanvasRenderer`, `SVGRenderer` or `SoftwareRenderer` as experimental ways for rendering a 3D scene but not as serious alternatives for `WebGLRenderer`.

**Comment by donmccurdy** [comment]
Just noticed that in the docs — are there more details anywhere about CanvasRenderer being deprecated? Or is it really in the same example category as SVGRenderer or CSS{2,3}Renderer?

**Comment by Mugen87** [comment]
I think at the beginning of the project, `CanvasRenderer` was a nice fallback if WebGL was not available. Since the [WebGL support](https://webglstats.com/webgl) is very good now, `CanvasRenderer` lost in some sense its right to exist.

**Comment by mrdoob** [comment]
Yeah... It may be a good time to remove `CanvasRenderer`... 😥

**Comment by WestLangley** [comment]
@mrdoob Just to confirm... Remove `CanvasRenderer`, `SpriteCanvasMaterial`, CanvasRenderer references in the docs,  and all [ CanvasRenderer examples](https://threejs.org/examples/?q=canvas_)?

**Comment by mrdoob** [comment]
Ugh... Yes 😞
But we should probably port some of the examples to webgl.

**Comment by mrdoob** [comment]
I see a lot of people using this example:
https://threejs.org/examples/canvas_particles_waves.html

Also I think the ASCII Effect one is interesting too:
https://threejs.org/examples/canvas_ascii_effect.html

**Comment by WestLangley** [comment]
I ported the first one. I'll let someone else port the second one. :-)

**Comment by Mugen87** [comment]
>  I'll let someone else port the second one. :-)

Done :blush:
