### ISSUE TITLE
RaytracingWorker: Add support for BufferGeometry

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#14580]
I think that would be a valuable addition.

**Comment by mrdoob** [comment]
Agreed.

**Comment by zz85** [comment]
I'll try digging into it a little

**Comment by WestLangley** [comment]
@zz85 I think it would be OK in this case to remove support for legacy Geometry. At some point it will not be renderable anyway.

**Comment by zz85** [comment]
Just some updates from initial investigation - it seems like `BufferGeometry` has already some support in `RaytracingWorker`. `MeshBasicMaterial` works but not `MeshPhongMaterial`.

The reason is that `checkBufferGeometryIntersection()` in Mesh is not returning vertexNormals. could try modifying that method a little to see if that works.
