### ISSUE TITLE
Mobile Fog Bug

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#14736]
A recent update in the dev branch seems to have broken fog (at least FogExp2) on mobile devices using mediump and lowp shader precisions. It works fine on highp. Desktop does not appear to be affected.

My testing device is a Samsung Galaxy s7. I have tested both Chrome and Firefox.

https://jsfiddle.net/titansoftime/e1zLrv2s/

**Comment by greggman** [comment]
Well, just like lighting, since the fog is using world positions mediump is not enough to do distance fog. Could try to scale it but that sounds complicated to get right so just thinking can use a `#define/#if/#else#/endif` so if they opt into mediump they get the old z based fog. Otherwise they get the new distance fog?

highp

![img_3539](https://user-images.githubusercontent.com/234804/44301812-539c4580-a358-11e8-8b0c-c6715108c51a.PNG)

mediump

![img_3538](https://user-images.githubusercontent.com/234804/44301815-5bf48080-a358-11e8-9f30-dbf29c6d47a9.PNG)

**Comment by titansoftime** [comment]
It does not work at all for me.

![screenshot_20180818-125947_chrome](https://user-images.githubusercontent.com/6549763/44302018-d84e7b80-a2e6-11e8-8fe7-f7ab5ac76050.jpg)

**Comment by mrdoob** [comment]
Thanks for continuously testing the `dev` builds @titansoftime! 🙏
