### ISSUE TITLE
Dotted line in uv boundary when using equirectangular environment maps

### ISSUE THREAD

**Issue by majinge78467** [mrdoob/three.js#14759]
Mirror question: https://discourse.threejs.org/t/bizarre-dotted-line-in-uv-boundary-when-use-repeatwrapping/3758

Setting the `minFilter` of the texture to `THREE.LinearFilter` solves the problem. And I want to ask why and the underlying cause of the problem. Maybe some codes need to change in mipmap to fix this problem:

Test: https://jsfiddle.net/f2Lommf5/12110/

##### Three.js version

- [ ] Dev
- [x] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

**Comment by Mugen87** [comment]
I suggested to move the issue to github since you can see the mentioned seam in one of the official examples. You have to click on `Equirectangular` to see the glitch.

https://threejs.org/examples/#webgl_materials_envmaps

![image](https://user-images.githubusercontent.com/12612165/44454301-6da98280-a5fb-11e8-91ad-703c9d646003.png)

**Comment by mrdoob** [comment]
#8305

**Comment by mrdoob** [comment]
Further reading... #1621

**Comment by WestLangley** [comment]
The artifact is caused because the  lowest-resolution (blurriest) mipmap is selected when the UV changes from 1 to 0 at the seam. A workaround is to disable mipmapping:
```javascript
texture.generateMipmaps = fase;
texture.minFilter = THREE.LinearFilter;
```
