### ISSUE TITLE
GLTFExporter passing down map.format as THREE.RGBA for jpg textures

### ISSUE THREAD

**Issue by akashkuttappa** [mrdoob/three.js#14757]
I was using the GLTFExporter with AFRAME in order to export out certain models in my scene (or the whole scene itself). While doing so I encountered an issue where the exported GLB was 3/4 times larger than the original model. This is when I experimented with the same model with a different texture file type and had the following observations

_Model with the PNG texture resulted in the end GLB model being the same size as the original_
_Model with JPG textures resulted in the end GLB model being a greater size than the original_

This reminded me of the way Blender behaves with GLB models (directly choosing to export as PNG even though textures might be JPG) and that's when I looked into the Exporter and found this line

https://github.com/mrdoob/three.js/blob/a1daef37e5a6b80d0173af54edd000202b95fca5/examples/js/exporters/GLTFExporter.js#L640

And when I did a check there for the format which was being passed in from the map, the model with the JPG texture was being passed in as THREE.RGBA which was setting the mimeType as **image/png** when it instead had to be THREE.RGB. The PNG model was being passed down fine as THREE.RGBA and being exported out as the same size.

Another Issue I encountered with the models is that it constantly kept giving me an error saying
**Cannot convert undefined or null to object**
and that was at the following line 

https://github.com/mrdoob/three.js/blob/a1daef37e5a6b80d0173af54edd000202b95fca5/examples/js/exporters/GLTFExporter.js#L1204

I bypassed that issue by directly setting it to undefined for now. I've attached the project below and the same can be downloaded from the link below.

https://sharktest.surge.sh/

The Code can be downloaded at https://sharktest.surge.sh/code.zip and can be run locally.

##### Three.js version
 - github:supermedium/three.js#r90fixMTLLoader

**Comment by donmccurdy** [comment]
> the model with the JPG texture was being passed in as THREE.RGBA which was setting the mimeType as image/png...

Hm, `THREE.RGBA` is the default value. We can easily fix GLTFLoader to set RGB, but to really fix this bug you'd need all loaders, and any custom textures added in userland, to do the same... maybe there's another way to get the mime type of the image? The other way I'm aware of would be a [HEAD request](https://stackoverflow.com/questions/43467909/how-to-get-img-content-type-using-javacript-after-loading), and that feels hacky / won't always work either. :/

If you have some control over the way images might enter the scene, that seems best, we can at least ensure GLTFLoader sets the right `.format` so the model will export back out correctly.

> Another Issue I encountered with the models is that it constantly kept giving me an error saying `Cannot convert undefined or null to object`

I think this may be a result of using a newer version of GLTFExporter with an older version of three.js, what version are you on?

> This reminded me of the way Blender behaves with GLB models...

I think the issue in KhronosGroup/glTF-Blender-Exporter has been fixed in recent versions — could you file an issue if not?

**Comment by donmccurdy** [comment]
If you'll only support glTF, then I guess fixing the issue in THREE.GLTFLoader would be enough? I don't know if this can realistically be fixed for all loaders but for just the one it's probably manageable.

**Comment by donmccurdy** [comment]
I think this was partly fixed in r95 by https://github.com/mrdoob/three.js/pull/14505 already. The rest should be fixed by #14768.

**Comment by donmccurdy** [comment]
There are three cases for loading images in glTF:

1. `.gltf` with external image URL
2. `.gltf` with embedded data URI
3. `.glb` with embedded binary buffer

Cases (1) and (2) are [handled automatically](https://github.com/mrdoob/three.js/blob/e130516689497c163d6b9eab0d3239eb580525e0/src/loaders/TextureLoader.js#L34-L36) by THREE.TextureLoader, but because of a bug that wasn't working until r95 (fixed by #14505). Case (3) should be fixed by #14768.

I'm not sure what will happen when loading models at runtime from a `.ZIP` archive, but I think that should also still work.
