### ISSUE TITLE
DirectionalLightHelper is a frame late at best

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#14801]
##### Description of the problem

Manually calling `someHelper.update()` is usually a frame late because the helper users `matrixWorld` which isn't updated until rendering

http://jsfiddle.net/greggman/0oxvetb4/

This has other issues as well. If you make a directional light, set a target, **call update**, then render (never calling update again because you're never changing the light) the helper will never be correct.

http://jsfiddle.net/greggman/en0jco1g/

Should it maybe switch to using a `needsUpdate` style instead of an explicit call to `update`? That would let it sync with the scene. It would also mean nothing needs to be done for a static light

##### Three.js version

- [X] Dev
- [X] r95

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by arodic** [comment]
I've been noticing this problem with various helpers for a while but it's very subtle and easy to miss.

**Comment by arodic** [comment]
In your second fiddle there is a simple fix to call `light.target.updateMatrixWorld();` before the helper update. This can be added to helper's `update()` function.

In the first fiddle, however, target's parent also needs a matrix update so that won't do.

One solution I tried on my end is to implement custom `updateMatrixWorld()` function for the helpers, and do helper update there. Great thing about this approach is that you don't need to call update manually, renderer does it for you. The only problem is... you still need to make sure helpers are rendered **after** the rest of the scene.

Example:

```javascript
class Helper extends Object3D {
	updateMatrixWorld() {
		this.update(); // helper is updated automatically
		super.updateMatrixWorld();
	}
}
```
