### ISSUE TITLE
webgl_gpgpu_water example / Mesh height increasing

### ISSUE THREAD

**Issue by JeremieForge** [mrdoob/three.js#14800]
In the example https://threejs.org/examples/webgl_gpgpu_water.html,
the water mesh is slowly going up.

It takes a lot of time (~ 1/2 hr),  and the mouse cursor must be hovering the mesh and animating the surface the whole time (no hovering --> no problem)

to have continuons mouse data input I added a 'mouse simulator' in Iine 553

```
else{
	fakeX+=0.1;
	fakeY+=0.02;
	uniforms.mousePos.value.set( 100*Math.cos(fakeX), 100*Math.cos(fakeY) );
}

```
The problem is, when adding various cursor positions (I needed 5 points touching the water mesh independently), the water mesh is going up quickly (~10 mins).

Any idea about what could I do to fix this ?

**Comment by mrdoob** [comment]
Could you provide info about your system? browser, os, graphics card, etc

**Comment by JeremieForge** [comment]
I tried these 2 different setups:
• Intel NUC 7I7BNH (Intel Core i7-7567U) / Ubuntu 17.10 / Intel iris Plus Graphics 750 / Chrome 69 & Firefox 17.10
• Mac mini late 2012 / MacOs Sierra / Intel i7 2,6GHz / 2,6 GHz Intel Core i7 / Intel HD Graphics 4000 1536 Mo / Chrome 68

**Comment by Mugen87** [comment]
I'm unable to reproduce the problem on my iMac with Chrome 69.0.3497.100.

**Comment by Mugen87** [comment]
> the water mesh is slowly going up.

Do you mean the y-position of the mesh increases?

**Comment by JeremieForge** [comment]
yes

**Comment by WestLangley** [comment]
It is not clear why the simulation would be stationary (have no simulated drift) to begin with.

You could add a periodic self-correction to the simulation to prevent that.

**Comment by yomboprime** [comment]
I wish the real ocean water level was as easy to reset as this.

I've fixed the example by reading the current water volume with a shader and then applying the negated average height level in the main compute shader.

The reading of the average water level is a bit hacky with the `WebGLRenderer` (`gl.ReadPixels` is used) but it is instructive so I think it is worth it.

As WestLangley suggested it has some cost so I read every 2 seconds –but write the compensation gradually in each frame since an uniform added to the result has near no cost, and it is smoother.

BTW, I was looking to learn the Node Material System to make this example less hacky in the graphical part (the visual shader is copied from the core Phong shader and modified). I tried to, but was unsuccessful. Any help on this?

**Comment by WestLangley** [comment]
@yomboprime I bet you don't need to compute the volume and sum over all cells. Just compute the average value over time at one cell, and do so less frequently.

**Comment by yomboprime** [comment]
No. Then if there are big waves, the height compensation would also fluctuate vastly.

**Comment by yomboprime** [comment]
Ummm, no. I stay on my first statement. If you fix a point on the water to height 0, the movement of the point in the wave on the water will be transferred to the whole mass of water.

**Comment by yomboprime** [comment]
Well i got some time for this. Added a new commit to the PR. Actually it was easy to do and it worked. 
Now it samples only 1 point at the center of water and drains gradually every 2 seconds.

I tested only with a big `mouseSize` but I think it should be able to work as requested, please test it @JeremieForge 

Thanks @WestLangley
