### ISSUE TITLE
FBX Loader: Displaced Animation Playback

### ISSUE THREAD

**Issue by liz3** [mrdoob/three.js#14864]
Hello, im pretty new to three.js but getting into it was pretty easy with the quite extensive collection of examples.
Though i encountered a for me game breaking "bug"(In Quotes because it could be related to a wrongly exported file).

I am using the [FBX Example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_fbx.html) to display a FBX Model with a animation. But the animation is been displayed completely wrong.
After i noticed that, i loaded the in the example provided "Dancing Samba", this model worked without any issues.

So the issue has to be related with the (from Maya 2018) exported file.
I noticed that the "FBX binary version" of the example model is 7400 and my file was 7500, i then exported the file again with the 2014 fbx version, the displayed version changed to 7400, the bug is still there though.

I included both the 7500 and 7400 version of the file and a short mp4 video showing the working state first and then the non working, in the zip.
[Files.zip](https://github.com/mrdoob/three.js/files/2355126/Files.zip)
[Implementation Code](https://gist.github.com/liz3/95b9d73b217f5457dbe6cf6115043f76)

Info:
Browser: Chrome 68.0.3440.106
Three.js Version: (npm, bundled with webpack and babel): three-full 11.0.1
System: I7 8700K, GTX 1060

Regards,
Yann HN(Liz3)

**Comment by looeee** [comment]
Thanks for the thorough bug report. I suspect it's because the way transforms are implemented in Maya are quite different than in 3DS Max, and I've been concentrating on that while creating the animation system. I'll have to look into this a bit more and see if I can update the code to better support Maya transforms. 

Can you try exporting with the "bake animations" setting turned on and see if it works better with that? 

In the meantime as a workaround you could also try converting to glTF format using [FBX2glTF](https://github.com/facebookincubator/FBX2glTF). It's a command tool, and there are prebuilt binaries [here](https://github.com/facebookincubator/FBX2glTF/releases)

**Comment by liz3** [comment]
@looeee Though i havent get the gltf thing to work, if have some interesting fact:
I just imported the .fbx into blender and exported it again, that for some reason fixed the issue....so my theory that its related to export options is true, though by now i almost tried every possible setting, none worked until now.
I will comment if i find a option that fixes it.

**Comment by looeee** [comment]
> I just imported the .fbx into blender and exported it again(with default settings), that for some reason fixed the issue....

Blender uses the same transform as 3DS Max (at least when exporting FBX files). 

> so my theory that its related to export options is true

Possibly, but I would say my theory that it's related to the difference in how transforms are applied in Maya is more likely. Nonetheless, can you confirm that the issue is still there when exporting with "bake animations" on?

**Comment by liz3** [comment]
@looeee yes and also when using the FBX2glFT tool

**Comment by liz3** [comment]
Il try it and yes you can use these files, il comment again when i tested

**Comment by donmccurdy** [comment]
Actually FBX2glTF is working correctly, as far as I can tell. The animation in FBX Review looks the same as playing on https://gltf-viewer.donmccurdy.com/ — 

![050faf1d-ebc3-4061-af1b-7fda2e1ace2f-59407-0002d687a79a9ea2](https://user-images.githubusercontent.com/1848368/45533543-e049f000-b7ac-11e8-9f5b-f1212d5950a7.gif)

Is it not working for you? Note from the [docs](https://threejs.org/docs/#examples/loaders/GLTFLoader) that GLTFLoader returns a differently-structured result than FBXLoader.

**Comment by liz3** [comment]
@donmccurdy which arguments did you used in the convertion process and could you share the exact source of the threejs player playing the animation?

**Comment by liz3** [comment]
Note **For all**: The (for now) Workarround is to just export the fbx from maya, import it in Blender and re export it(no specific changes required)

**Comment by chinazaaa** [comment]
Please do i load two different fbx files with animation in Javascript

**Comment by donmccurdy** [comment]
@chinazaaa please use the forums (http://discourse.threejs.org/) or Stack Overflow for help.
