### ISSUE TITLE
Chrome 69 WebGLRenderTargetCube

### ISSUE THREAD

**Issue by Fyrestar** [mrdoob/three.js#14876]
Since the recent chrome update to 69 rendering to a WebGLRenderTargetCube suddenly results in a black texture without any warnings, while it still works for Firefox or Opera. Is there a changelist regarding WebGL anywhere? I can't drop a fiddle and it doesn't seems to appear in the examples, so i need to investigate at the changes, i can't seem to find any notes about WebGL.

##### Three.js version

- [x] Dev
- [x] r96
- [ ] ...

##### Browser

- [] All of them
- [ x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
This can be closed then?

**Comment by Fyrestar** [comment]
Yes, i don't know what has changed and if it's problematic though, but there are no other reports yet.

**Comment by JizZuS** [comment]
Since the release of Chrome 69, I'm having simmilar issues with bigger textures. Smaller textures are displayed normally, but one of my textures (3309x2339) -> resized to (2048x2048) is not rendered.

Before the release the texture rendering was just fine. This issue does not affect other browsers. This happens on Windows & Linux.

Google Chrome (70)
![image](https://user-images.githubusercontent.com/7282431/47290352-54bf4c80-d5ff-11e8-93a8-3063ae8c552b.png)

Microsoft Edge (42)
![image](https://user-images.githubusercontent.com/7282431/47290373-70c2ee00-d5ff-11e8-88d0-20f61cdd7daa.png)

For me the renderer is not set to `autoClearDepth = false`.

**Comment by Mugen87** [comment]
@JizZuS Please file a bug at the Chromium project. `three.js` can't fix browser issues.

https://bugs.chromium.org/p/chromium/issues/list
