### ISSUE TITLE
PLYloader error in loading little_endian geometry

### ISSUE THREAD

**Issue by amarchino** [mrdoob/three.js#14937]
Greetings

##### Description of the problem
I am using your library to render some PLY files generated from third party cameras. As such, I have little control upon the generated file.
The generated PLY is encoded in binary_little_endian format, and is a correctly generated PLY file (I can load it via MeshLab, or I can translate to a similar format such as Nexus without problems).
Yet, I cannot correctly load this file via the `PLYloader`.
More precisely: I am able to render the 'ascii'-ized version of the file (loaded into MeshLab, and saved in ascii format) with little problem, yet the binary file simply won't load.

This seems due to an error in the windowing of the underlying array buffer, for I get this error:
```js
RangeError: offset is outside the bounds of the DataView
```
I tried to alter the loader so that the offset cannot exceed the DataView boundary, but as expected this causes other errors downstream
```js
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values.
```

I'd like to ask for some informations on this case: is it an error of the loader, of the file, of the parameters I set in the program (an example of which is created in a JSFiddle)?

The fiddle has a reference to the PLY files, and I'll be happy to add any missing information.

Thanks for your product, and for the time spent in reading this.

* [jsfiddle r96](https://jsfiddle.net/n8xzLc1m/16/)
* [jsfiddle dev](https://jsfiddle.net/h7s2k9e1/)

##### Three.js version

- [x] Dev
- [x] r96
- [x] Possibly older ones, but I cannot find the version number

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by Mugen87** [comment]
`PLYLoader` should actually support binary files encoded in little endian format. There is a LE binary file in the repo and it loads fine 🤔  https://jsfiddle.net/n8xzLc1m/23/

**Comment by Mugen87** [comment]
I'm out of ideas 😞. I don't know why but the mentioned PLY file is processed fundamentally wrong by `PLYLoader`. For some reasons, the loader reads only zeros when processing the indices. Besides, I think the data in the position attribute are incorrect. Single vertices have values like this `(-37036072,1.4753827330473196e-35,-1.6501715689228802)`. These are definitely not the data I see in Blender when importing the mentioned PLY file. The result should actually look like this:

![image](https://user-images.githubusercontent.com/12612165/46552690-bb442b00-c8db-11e8-8ca2-5a46a6699845.png)

**Comment by amarchino** [comment]
Yes, the rendered image is actually flipped upside down relative to what was actually scanned (probably a bug of the tool that created the PLY, but should be inconsequent as long as I can rotate the image).

I thank you for the time you spent in trying to analyze the problem... I hope that someone can come up with some flash of idea that actually finds the problem (in the loader or in the PLY data), so that it can be patched.

**Comment by mrdoob** [comment]
How does it look like in meshlab?

**Comment by Mugen87** [comment]
It looks good 😊 

![image](https://user-images.githubusercontent.com/12612165/46820867-7e6aaf00-cd87-11e8-9693-0e37dd0ed761.png)

**Comment by amarchino** [comment]
If it may help: I tried to convert it by using the [Nexus library] (https://github.com/cnr-isti-vclab/nexus)... And the resulting file is loaded correctly by the loader for Three.js they developed together with the library.
I must admit that I don't actually understand C/C++ or the PLY format specifications well enough to understand what the compiling steps actually did to the code, but it sonhow worked.
I also tried with some other working (as in 'working with this loader') PLY files, and they too were compiled correctly.
...Well, yeah, probably this post is not actually helpful at all, but I thought that it may be a different take on the problem: the file looks corrupted by this loader, but may it be that other tools (the aforementioned Nexus, but also Meshlab) are actually some more 'fault tolerant' in respect to this format?

**Comment by Mugen87** [comment]
@algrs Do you might have any ideas why `PLYLoader` can't process the mentioned binary file? 

MeshLab internally used VCGLib in order to import PLY files. I've checked out the respective C++ [source code](https://github.com/cnr-isti-vclab/vcglib/blob/master/wrap/ply/plylib.cpp) but unfortunately I could not figure it out so far what they make different in order to load the problematic binary file.

**Comment by algrs** [comment]
The binary file in the fiddle appears to be slightly truncated at the very end. The header lists 432486 faces, but the file ends after face 432443. PLYloader is throwing a RangeError trying to read the last few faces, since there's no more data to be had, and the postProcess function where it writes the data into the geometry never gets called, which is why the geometry looks empty.

It appears that MeshLab is sensibly taking as many faces as it can get and not worrying about the file not having quite as many as the header promised. 

Fundamentally, the bug is with whatever is writing this file. I'd suspect that what's happening is that a few of the faces are invalid (by whatever definition the program that's doing the writing uses; maybe it's skipping faces that reference missing vertices, maybe it's skipping faces that have one vertex referenced twice; who knows...) and as it writes it's skipping the problematic faces. Thus at the beginning when it writes the header it thinks it's going to have 432486 faces, but a few don't get written along the way and it doesn't go back and update the header to reflect the 432443 faces it actually wrote. It's not an uncommon failure mode for PLY writers. Not a huge problem if it happens on the last element in the file, but if it happens on one of the earlier elements, then it corrupts the data in the following element (e.g. if you have a couple of missing vertices, then the first few faces will be incorrectly interpreted as vertices -- with an ascii ply you can usually detect that, but with a binary ply you just get a couple of garbage verts). 

If desired behavior is silently supporting slightly malformed files like this, the way MeshLab does, it should be easy enough to wrap the call to binaryReadElement in parseBinary to catch the RangeError and ignore it.

As a side note, if you're looking to validate a ply implementation, [RPLY](http://w3.impa.br/~diego/software/rply/) is probably the canonical C implementation and the code is fairly straightforward.

**Comment by Mugen87** [comment]
> but if it happens on one of the earlier elements, then it corrupts the data in the following element 

How is it possible to detect this error situation? Even if you avoid the mentioned `RangeError` of the initial post, the buffer data processed so far seemed to be wrong. Like mentioned before, there are parsed vertices with values like `(-37036072,1.4753827330473196e-35,-1.6501715689228802)` which are obviously malformed. The bounding box calculated in Blender has much smaller bounds.

**Comment by algrs** [comment]
Interesting -- so it turns out that the issue was actually an off-by-one error having to do with whitespace in the ascii header... Fix is https://github.com/mrdoob/three.js/pull/15099  I'm still puzzling over why that problem was causing the data to appear truncated, since if anything there should have been one extra byte left over after everything was read.

**Comment by amarchino** [comment]
Thank very much to all of You!!

**Comment by geyang** [comment]
I have the following file that is also resulting into parse error, where position and normal are both all NaNs. What would be the solution in this case? 

https://drive.google.com/file/d/1xAl9mgXWWrvoT4g1u0pi0gbSL6l8pKrD/view?usp=sharing

**Comment by Mugen87** [comment]
I can import the file without issues into the [three.js editor](https://threejs.org/editor/).

<img width="903" alt="Bildschirmfoto 2023-12-20 um 10 29 02" src="https://github.com/mrdoob/three.js/assets/12612165/e6a2e093-9c28-46ac-b8a1-818feccce56d">

No signs of parsing errors.
