### ISSUE TITLE
Exporting GLTF from Editor does not export Roughness/Metalness Map

### ISSUE THREAD

**Issue by colinfizgig** [mrdoob/three.js#14940]
Creating a model in Three.js/editor and exporting with roughness or metal maps to GLB or GLTF will not export the rough/metal maps whether they are combined as a single file AO/Rough/Metal RGB or as individual images.

I'm trying to apply these images in the Editor and export them as a gltf file.  However when the exporter ignores them because it says they are not the same image (even though they are in the case of a hand merged file.

When I reimport the glb in the editor the images are not their, but if I exported the AO map (same image) it is exported.

Is there a way to check that the user is trying to apply a merged image or the same image and go ahead and export the metal roughness maps?

here is a shot of the editor before export...

![beforeexport](https://user-images.githubusercontent.com/7503097/45763708-10572000-bbff-11e8-8bbc-7c37897b053d.JPG)

And here is a shot after import with a console log showing the export problem.

![importglb](https://user-images.githubusercontent.com/7503097/45763780-37155680-bbff-11e8-956e-b0facd07db61.JPG)

##### Three.js version
version r.96

##### Browser
Chrome

##### OS
Windows 10

**Comment by colinfizgig** [comment]
@donmccurdy 

Here is the glb file as it was converted from Maya which has the same textures.. opening and exporting this works fine.  In addition I'm including a scene .json that I exported after I loaded the same texture for both metal and roughness on the shield.

The references to the textures are different as seen in this screencap of the material in the json.
![jsonmaterialsetup after loading the same image for each map](https://user-images.githubusercontent.com/7503097/45822391-5cff3180-bcb9-11e8-80a2-35ec6713980a.JPG)

So yes I think "deduplicating" the textures by checking to make sure the textures are the same would be good.  Not sure how that could be done?  Maybe store the source that was uploaded as a variable and if it has not changed and is the same source between the Metallic and the Roughness then set them to be the same texture within the scene.  This won't solve actually using different textures and trying to combine them on export, but it could work as a temporary fix until different textures can be used and combined on export per the gltf spec.

Here is a link to the zip of the json and glb files on my github component page.  (too big to include here).  https://github.com/colinfizgig/aframe_Components/blob/master/Models.zip

Let me know if you need anything else.  I can also confirm that this shows up in the exporter for Aframe as well.

**Comment by donmccurdy** [comment]
Per https://stackoverflow.com/questions/30006231/detecting-if-the-user-drops-the-same-file-twice-on-a-browser-window, it seems to be very difficult to verify that two textures are the same if they've been added in the editor's UI separately. When adding the same image again after refreshing the page, I actually get a different Data URI. ☹️

Instead of trying to detect duplicates, I think we should implement logic in GLTFExporter to "merge" AO/metal/rough texture channels when they don't appear to be the same image. So:

1. If metal/rough textures are different and have different sizes, use one, skip the other, and log a warning.
2. If only one of metal/rough is present, export that.
3. If AO has the same size as the (combined) metal/rough, merge its red channel into that image.

/cc @fernandojsg

**Comment by colinfizgig** [comment]
This stack overflow poses an interesting possibility if you are willing to use some Html5 and canvas as a way to check the image matching.  
https://stackoverflow.com/questions/9136524/are-there-any-javascript-libs-to-pixel-compare-images-using-html5-canvas-or-any

If you went this route you could check the differences of scaled down version of each image using the RMS method in the stack overflow thread.  If the images were within a certain tolerance range 1-10 you could use the first image for each map that matched it on export.

This is not as elegant as merging a channel from each image into a single image and using the merged image, but could be a useful workaround if merging images is problematic.

**Comment by fernandojsg** [comment]
Merging metal/rough/AO textures on the same texture on different channels is something we had in our plan for features to support in the GLTFExporter since the beginning. Actually I had it on my backlog but I have not had time yet to take a look at it :)
So I agree with @donmccurdy on the proposal as something we should support soon:

> - If metal/rough textures are different and have different sizes, use one, skip the other, and log a warning.
-  If metal/rough textures are different and have the same size: combine them
> - If only one of metal/rough is present, export that.
> - If AO has the same size as the (combined) metal/rough, merge its red channel into that image.

And I'll add to the wishlist two things:
- An option as `convertSizeWhenCombineTextures` so it will try to combine them by reescaling the ones with different size.
- Comparing images to detect duplicates. This could be added on the exporting process itself or as a postprocess action including it on GLTFEXporter.Utils

**Comment by dineshsalunke** [comment]
> Per https://stackoverflow.com/questions/30006231/detecting-if-the-user-drops-the-same-file-twice-on-a-browser-window, it seems to be very difficult to verify that two textures are the same if they've been added in the editor's UI separately. When adding the same image again after refreshing the page, I actually get a different Data URI. ☹️

There is a PR for having a texture's panel, a way to import textures and then assign them to maps in material #21369 I think that should solve this problem right ?
