### ISSUE TITLE
Texture loading failure on iPad

### ISSUE THREAD

**Issue by aansel** [mrdoob/three.js#15004]
##### Description of the problem
Starting in version r83, there is an issue on iPad with the TextureLoader. Loading a texture fails for me, and I am pretty sure that this is because the cookies are not sent (the texture is access-protected so I need the cookies to be sent).

There is no problem on Chrome/Firefox/Anything else. Just on iPad.
I am using the function loader.setWithCredentials(true); (which has disappeared in latest versions).
In version 0.82.1, it works. It starts failing on iPad in version 0.83.0, and it still fails in the latest version (0.97.0).
I am using an iPad Air with iOS version 10.3.2.

##### Three.js version

- [x] r97
- [x] r83 
- [ ] r82.1

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
iPad Air with iOS version 10.3.2.

**Comment by Mugen87** [comment]
> I am using the function loader.setWithCredentials(true); (which has disappeared in latest versions).

`ImageLoader.setWithCredentials()` was available for a period of time since the loader internally used `FileLoader`. This was removed for various reasons, see #10439.

Do you have the same problem when you just make a simple HTML page and show a picture via HTML5 image API? Something like this:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

**Comment by Mugen87** [comment]
Closing. Let's reopen the issue if the OP provides a fiddle that demonstrates the issue.
