### ISSUE TITLE
TubeGeometry: Different length of the tube when geometry is closed

### ISSUE THREAD

**Issue by dytmh** [mrdoob/three.js#15019]
r96 Chrome MacOS

var path = new CurvePath();
path.add( new LineCurve3( new Vector3( 0, 0, - distance / 2 ), new Vector3( 0, 0, distance / 2 ) ) );
var tube = new TubeGeometry( path, 64, this.radius, 32, true );

if closed is true, length is error.

if closed is false, result is ok.

<img width="1125" alt="wx20181007-161702 2x" src="https://user-images.githubusercontent.com/4333197/46579894-8a373800-ca4c-11e8-9117-3f9a369fc1fb.png">
<img width="317" alt="wx20181007-161719 2x" src="https://user-images.githubusercontent.com/4333197/46579896-8dcabf00-ca4c-11e8-8c7c-e04149790189.png">
<img width="396" alt="wx20181007-161732 2x" src="https://user-images.githubusercontent.com/4333197/46579897-8e635580-ca4c-11e8-93e6-a0893fc10b03.png">

**Comment by Mugen87** [comment]
This is the intended behavior of the implementation. If the geometry is not closed, the last row of vertices is generated at its actual position. But when the geometry is closed, the first row of vertices is duplicated in order to connect the geometry so it is actually continuous (the duplication is necessary since the first and last row of vertices have different uvs). 

The current implementation ensures that the amount of vertices is equal for both types of geometries (closed vs. not closed). This makes it easier to generate indices and uvs later in the generator.

BTW: Using  `TubeGeometry` with a line and set close to `true` does actually not make sense. The implementation does not generate caps (like `CylinderGeometry` does). It connects both ends of the tube what has no real benefit for a line.

**Comment by Mugen87** [comment]
Fiddle for reproduction: https://jsfiddle.net/f2Lommf5/15141/
