### ISSUE TITLE
WebGLRenderer: Add support for multiple shader programs with a single material.

### ISSUE THREAD

**Issue by gero3** [mrdoob/three.js#15047]
It would be necessary to have multiple multiple webglprogram on a single material to solve #11400.

This would require several steps to be taken to get this done:
 - [x] Figuring out what parameters are necessary to generate a webglprogram and use a single parameter source to create it. (#18279)
 - [ ] Build single parameter source from 4 parameter sources: material, object, renderer, scene.
     - [ ] Material parameter: gets regenerated when needsUpdate is true
     - [ ] Renderer parameter: gets regenerated every render    
     - [ ] Scene parameter: gets regenerated every render
     - [ ] object parameter: gets regenerated every ??
 - [ ] Create keys based of the 4 parameter sources to figure out if something changed.
 - [ ] Use single parameter source as key to figure out if program needs to be created.
 - [ ] Use single parameter source as key to figure out which program to use.

We would also need to track which program gets used by which material to make sure that the programs get deleted when the material gets disposed of.

**Comment by Mugen87** [comment]
> Create keys based of the 4 parameter sources to figure out if something changed.

I'm actually afraid that generating a key per renderable item per frame will worsen the performance of the renderer because it would have to check a lot of scenarios in order to assign the correct program. Essentially, you need the logic from `WebGLPrograms.getParameters()` and `WebGLPrograms.getProgramCacheKey()` which is currently only executed in `WebGLRenderer.initMaterial()`. And this method is only called if a material needs an update (so it's currently not a hot spot when rendering). 

Even if you optimize the code, the renderer will produce more overhead than before. An interesting side effect: `Material.needsUpdate` should become obsolete. If we compute the program key per renderable item and per frame, the renderer can always figure out if a new program or a recompile is necessary.

**Comment by Mugen87** [comment]
I've experimented in this context for a while and came up with the following minimal solution: https://github.com/Mugen87/three.js/commit/e0099e56abd3cb573c46144096deb70e249a5108

It actually solves the ping-pong effect in certain scenarios e.g. when rendering to a render target with different output encodings (#19056). However, the general performance gets worse since the renderer has to compute a program key per frame for each object right now. This becomes to a problem when rendering scenes with a lot of objects:

https://raw.githack.com/Mugen87/three.js/dev51/examples/index.html#webgl_lights_pointlights2
https://threejs.org/examples/#webgl_lights_pointlights2

I'm trying to figure out a solution to avoid unnecessary calls of `getProgram()`.
