### ISSUE TITLE
SpriteMaterial depthTest = false has no effect

### ISSUE THREAD

**Issue by lp249839965** [mrdoob/three.js#15058]
##### Description of the problem

r97, set spriteMaterial's depthTest  = false has no effect.  use WebGLRenderer. 

##### Three.js version
r97

##### Browser
Chrome
Safari

##### OS
 macOS

**Comment by lp249839965** [comment]
> Can you please demonstrate the issue in a live example? https://jsfiddle.net/f2Lommf5/

Hi, i have write a live example in https://jsfiddle.net/f2Lommf5/15236/ , it looks like if i set the box's material.transparent = true, then the sprirteMaterial's depthTest will lose effect

**Comment by Mugen87** [comment]
Opaque objects are rendered fist, then transparent objects. If the material of the mesh is transparent, it is rendered along with the sprite. Transparent object are rendered in back to front order. So objects farther away from the camera are rendered first.

That means the sprite is rendered first since it has a higher depth value. The cube is rendered last. Deactivate the depth test for the sprite has no effect in this scenario since it is the first element of the scene that is rendered.

You can easily verify this by setting `sprite.renderOrder` to 1. This will force to render the sprite first. If you now deactivate the depth test, you will see the sprite:

https://jsfiddle.net/f2Lommf5/15242/

**Comment by Mugen87** [comment]
Opaque objects are rendered fist, then transparent objects. If the material of the mesh is transparent, it is rendered along with the sprite. Transparent object are rendered in back to front order. So objects farther away from the camera are rendered first.

That means the sprite is rendered first since it has a higher depth value. The cube is rendered last. Deactivate the depth test for the sprite has no effect in this scenario since it is the first element of the scene that is rendered.

You can easily verify this by setting `sprite.renderOrder`. This will force to render the sprite last. If you now deactivate the depth test, you will see the sprite:

https://jsfiddle.net/f2Lommf5/15242/

**Comment by lp249839965** [comment]
> Opaque objects are rendered fist, then transparent objects. If the material of the mesh is transparent, it is rendered along with the sprite. Transparent object are rendered in back to front order. So objects farther away from the camera are rendered first.
> 
> That means the sprite is rendered first since it has a higher depth value. The cube is rendered last. Deactivate the depth test for the sprite has no effect in this scenario since it is the first element of the scene that is rendered.
> 
> You can easily verify this by setting `sprite.renderOrder`. This will force to render the sprite last. If you now deactivate the depth test, you will see the sprite:
> 
> https://jsfiddle.net/f2Lommf5/15242/

ok, thank you
