### ISSUE TITLE
webgl_lights_physical: Scale seems off

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#15262]
##### Description of the problem
The text at the top of webgl_light_physical ([master](https://threejs.org/examples/webgl_lights_physical.html), [dev](https://rawgit.com/mrdoob/three.js/dev/examples/webgl_lights_physical.html)) says
> Brick cube is 1 meter in size. Light is 2 meters from floor. Globe is 25 cm in diameter

But the globe is twice the size of the cubes and the light moves from `cube-height` to `4 * cube-height`, so neither ending at nor centered around `2 * cube-height` as it suggests.
![scale](https://user-images.githubusercontent.com/4936897/48625549-e4161080-e9af-11e8-9c81-243b5baa4b39.png)

In [early commits](https://github.com/mrdoob/three.js/blob/b93ba5ed566bc43885749232bd89613f26307ff0/examples/webgl_lights_physical.html) the numbers fit(`1`, `2` and `0.1213`), but then the text never got updated it seems ([git blame](https://github.com/mrdoob/three.js/blame/dev/examples/webgl_lights_physical.html#L39-L40)) Is the ratio of `1 unit:1 m` still correct here?

Somewhat related: #7636 and #6259 (both about unit scale) and #8260 (original PR)

##### Three.js version

- [x] Dev
- [x] r98

**Comment by Mugen87** [comment]
I think the parameters of the geometry generators do not fit to the description:

https://github.com/mrdoob/three.js/blob/5360a81b8c557ed255e97b87c49e7d00b546b795/examples/webgl_lights_physical.html#L221

Instead of `0.5` you would have to pass in `0.125` since it's the radius.

https://github.com/mrdoob/three.js/blob/5360a81b8c557ed255e97b87c49e7d00b546b795/examples/webgl_lights_physical.html#L228

The parameters for the box should be all `1`. Or you just omit them.

However, the example looks a bit odd with such parameters. I would do just this:
```js
var ballGeometry = new THREE.SphereBufferGeometry( 0.25, 32, 32 );
```
and change the description to:
```
Brick cube is 50 cm in size.  Globe is 50 cm in diameter.
```

@moraxy Would you like to do a PR with the change?
