### ISSUE TITLE
Disappearing model parts

### ISSUE THREAD

**Issue by EtagiBI** [mrdoob/three.js#15293]
Hello,

I experience a weird problem when rotating some models in three.js. Under certain angles of view some parts of a model become invisible. The problem is definetely has nothing to do with `material.side`. 

Front view:
![image](https://user-images.githubusercontent.com/20855725/48829741-d805c680-ed94-11e8-9184-daa97fe15420.png)

Back view ('good' angle):
![image](https://user-images.githubusercontent.com/20855725/48829806-02f01a80-ed95-11e8-8ab2-22eccc15f767.png)

Back view ('bad' angle):
![image](https://user-images.githubusercontent.com/20855725/48829886-2ca94180-ed95-11e8-98d7-757df462ca58.png)

Sample model:
[Sample_GLTF.zip](https://github.com/mrdoob/three.js/files/2603453/Sample_GLTF.zip)

##### Three.js version

- [ ] Dev
- [x] r98
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by moraxy** [comment]
Not sure if this is a bug in [gltf viewer](https://gltf-viewer.donmccurdy.com/), the library or the sample model, but there seems to be a general issue with the rendering order if you turn on the grid in the viewer:
![renderbug](https://user-images.githubusercontent.com/4936897/48832882-7cc6da80-ed7a-11e8-96fd-665228b96268.gif)

**Comment by donmccurdy** [comment]
You can hack this to look right from certain angles by fiddling with sorting and depthWrite, but the robust "transparency is perfect from any angle" solution is nontrivial. Related: https://github.com/mrdoob/three.js/issues/9977.

**Comment by Mugen87** [comment]
Closing in favor of #9977.

In general, you can always mitigate this issue by defining a custom render order via [Object3D.renderOrder](https://threejs.org/docs/index.html#api/en/core/Object3D.renderOrder) or by setting [Material.depthWrite](https://threejs.org/docs/index.html#api/en/materials/Material.depthWrite) as mentioned by @donmccurdy. However, these approaches represent no holistic solution. They might fix rendering issues only in particular cases.

You can also mitigate the issue during the modeling phase by reducing the mesh count and by avoiding the usage of multiple materials per object. The mentioned glTF asset has 60 mesh definitions which seems a bit high for such a model. A nice side effect by this optimization is a better rendering performance since you lower the amount of draw calls. You can also merge meshes in your app via [BufferGeometryUtils.mergeBufferGeometries()](https://github.com/mrdoob/three.js/blob/12aeaace0ac36470f1a46eef7420c12c7f9fdb04/examples/js/utils/BufferGeometryUtils.js#L192), but it's a bit easier to do this in a DCC tool.

**Comment by WestLangley** [comment]
>Closing in favor of #9977.

What? They are separate issues. And OIT is not a panacea.

This is also not a duplicate.

You can close this if you claim it is a modeling issue, and not a three.js issue.

**Comment by looeee** [comment]
I agree with @WestLangley, there's a couple of questions we should answer here before closing this:

1. How do other WebGL engines compare to three.js when it comes to transparency? From what I've seen Sketchfab in particular seems to handle transparency better than three.js. 
2. What sorting algorithms do other engines use?
3. Can we document workarounds and solutions better? 
4. How much will OIT improve things, and at what performance cost? We can discuss this one in #9977

**Comment by Mugen87** [comment]
Okay okay, reopening^^. I've seen in the past that we closed such issues and referred to OIT or modeling instead.

**Comment by WestLangley** [comment]
So, do you think this is a loader issue that we need to address, or is it a modeling issue -- in which case this isssue can be closed again? :-)

**Comment by donmccurdy** [comment]
Also related – https://github.com/mrdoob/three.js/issues/16055.

This isn't a loader issue. Careful modeling can avoid the problem, but there are probably things we could do within threejs to handle more (but not all) similar cases, and documentation would be a nice addition.

I think this can remain closed, given the other threads that exist.

**Comment by looeee** [comment]
@WestLangley, what do you mean by 'modeling issue' here? Also, I've raised some additional questions that will be to be addressed before this is closed again.

**Comment by looeee** [comment]
@donmccurdy, apologies, I think we posted at the same time. If you think this is covered in other issues adequately it's ok to close this one, but could you link the other ones here?
