### ISSUE TITLE
envmap maxMipLevel bug with Android

### ISSUE THREAD

**Issue by MagicLM** [mrdoob/three.js#15311]
##### Description of the problem

value of maxMipLevel is undefined on Android platform.

* [codepen](https://codepen.io/magiclm/pen/WYJBNY?editors=1111) (live demo)

In the outcome of the demo：
 black means maxMipLevel = 0（default value）;
 red means maxMipLevel != 0
##### On iOS and PC platform
It's going to be red

##### On Android platform
It's going to be black

Find the relevant code
```
if ( material.envMap ) {
     uniforms.envMap.value = material.envMap;
     // don't flip CubeTexture envMaps, flip everything else:
     //  WebGLRenderTargetCube will be flipped for backwards compatibility
     //  WebGLRenderTargetCube.texture will be flipped because it's a Texture and NOT a CubeTexture
     // this check must be handled differently, or removed entirely, if WebGLRenderTargetCube uses a CubeTexture in the future
     uniforms.flipEnvMap.value = ( ! ( material.envMap && material.envMap.isCubeTexture ) ) ? 1 : - 1;
     uniforms.reflectivity.value = material.reflectivity;
     uniforms.refractionRatio.value = material.refractionRatio;
     uniforms.maxMipLevel.value = properties.get( material.envMap ).__maxMipLevel;
}
```

Insert the code below
`alert(uniforms.maxMipLevel.value ) `
or 
`alert( properties.get( material.envMap ).__maxMipLevel)`;

##### On iOS and PC platform
The result is 10

##### On Android platform
The result is undefined

**Comment by Mugen87** [comment]
There is a problem with your fragment shader. Instead of:
```
 gl_FragColor = vec4( float( maxMipLevel ), 0.0, 0.0, 1.0 );
```
this works for me on Android 9 (Pixel):
```
gl_FragColor = vec4( max( 1.0, float( maxMipLevel ) ), 0.0, 0.0, 1.0 );
```
You should not assign color components greater than `1.0` to `gl_FragColor`.

Updated code pen: https://codepen.io/anon/pen/RqJaEY?editors=1111

**Comment by Mugen87** [comment]
I can reproduce the black plane with Chrome and FF on Android 9 (Pixel).

**Comment by Mugen87** [comment]
I've revisited this issue and I think I know now why this happens. Here is a fiddle with some updated code where `maxMipLevel ` is not `undefined`: https://jsfiddle.net/yghb4sp9/

In the original code snippet, `gl_FragColor` was overwritten. When this happens, the shader compiler seems to optimize the code on Android and discard the `envMap` uniform. Hence, `setTextureCube()` is never called and `maxMipLevel` never computed.  

If you do not overwrite `gl_FragColor` but multiply `vec4(float(maxMipLevel),1.0,1.0,1.0);`, this optimization does not happen and the result is as expected.

You can easily verify this logic by chaning
```js
gl_FragColor *= vec4(float(maxMipLevel),1.0,1.0,1.0);
```
to 
```
gl_FragColor = vec4(float(maxMipLevel),1.0,1.0,1.0);
```
On desktop, the box becomes white. On Android it becomes cyan since `maxMipLevel` is undefined.
