### ISSUE TITLE
Feature Request: Support raycasting against BufferGeometry with morph targets

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#15346]
I assume we want to support this...

**Comment by Mugen87** [comment]
Hint: `Mesh.raycast()` already supports this with `Geometry`. It is therefore all the more important to provide this feature in context of `BufferGeometry`.

**Comment by Mugen87** [comment]
I suggest for now to add support for morph targets to `BufferGeometry.computeBoundingBox()` and `BufferGeometry.computeBoundingSphere()`. Both methods would compute the maximum extend of the geometry.

**Comment by manthrax** [comment]
The tricky part of supporting these kinds of operations is that they are dependent on the animation data.

For instance lots of skinned characters I encounter in the wild have vertices that are immediately transformed to a completely different volume by the first frame of animation.. so without the context of the animation and its current frame of playback.. you can't really compute anything meaningful in terms of a bounding box or sphere. Additionally, any automagic computation or updating of boxes, would then preclude the animation being done on the GPU, and incur a cost proportional to number of transformed vertices, to update that bounds.

The problem is also compounded by the fact that some characters are composed/exported as multiple meshes separated by material but bound to the same skeleton.

That said, having a version of computeBoundingBox and computeBoundingSphere that did the heavy/accurate version for a given frame, would be super useful.
I would then probably make a 1 frame animation of the character, stretched out to their largest anticipated range of motion.. compute the boundingbox of that frame in my app, expand it by some fixed padding amount, and just use that, and forgo having super optimal frustum culling in favor of simplicity with just using conservative bounds.

As it stands now, I'm pretty much having to hand define a default bounding for each new character I import.

**Comment by WestLangley** [comment]
>I'm pretty much having to hand define a default bounding for each new character I import.

@manthrax Or you could set
```js
mesh.frustumCulled = false;
```
