### ISSUE TITLE
Stereo Camera does not inherit near and far properties

### ISSUE THREAD

**Issue by vendra95** [mrdoob/three.js#15427]
##### Description of the problem

When using a `StereoCamera` with any of the available Effects, the `StereoCamera` does not
inherit the previous camera properties, such as `near`, `far`, `aspect `and `zoom`, nor there are getters nor setters for those properties.

##### Three.js version

- [x] Dev
- [ ] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by Mugen87** [comment]
> the StereoCamera does not inherit the previous camera properties, such as near, far, aspect and zoom,

When a stereo camera is updated, it does honor the mentioned properties when computing the projection matrices for the right and left eyes.

> nor there are getters nor setters for those properties.

Since `StereoCamera` is actually intended for the usage inside of effect classes, the camera does not have to provide access to these properties. What matters are the projection matrices for rendering. So the idea is to access camera properties from your scene camera.
