### ISSUE TITLE
Lensflare is visible from both side of the sun

### ISSUE THREAD

**Issue by Fgeniy** [mrdoob/three.js#15456]
##### Description of the problem
Lensflare is visible from both side of the sun, when scene background color was change.  

https://threejs.org/examples/webgl_lensflares.html

http://recordit.co/C7j9CidjcD - video with bug

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome 71.0.3578.98
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows 7 64bit
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Fgeniy** [comment]
We got rid of this effect by ```	this.frustumCulled = true;```

**Comment by Mugen87** [comment]
It's possible reproduce the bug if you directly set a background color of `0xaaaaaa`. It's not necessary to change it after the application start.

Um, I think it's safe to set `frustumCulled` to `true` since `three.js` can compute a bounding sphere from the interleaved geometry which is necessary for the frustum intersection test.

@mrdoob How about removing the following line? Do you think this is safe?

https://github.com/mrdoob/three.js/blob/19b01b2add4146f689cfb7622f828e3b501797d8/examples/js/objects/Lensflare.js#L11

**Comment by WestLangley** [comment]
Alternatively, in `Lensflare.onBeforeRender()`, I expect you could test if the position in camera space has a negative z-coordinate.

**Comment by Mugen87** [comment]
That works, too! If the `z` value of the lensflare's position in view space is positive, `Lensflare.onBeforeRender()` can perform an early out. Let's do a PR...

**Comment by Mugen87** [comment]
@Fgeniy Can you please test if the PR fixes your problem?

I wondering now which approach is faster...If the view frustum test culls the lensflare, `onBeforeRender()` is also not called.

**Comment by mrdoob** [comment]
Opsss 😇
