### ISSUE TITLE
Add standalone GLTF 2.0 Loader

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#15488]
Blender for some time has let you export only GLTF 2.0, using the [gltf-blender-exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter), now built-in in blender itself as a addon.

Currently, the way to import a  GLTF 2.0 file, is through the DRACOLoader, an example is showcased in this really useful repo: https://github.com/donmccurdy/three-gltf-viewer/blob/master/src/viewer.js

The only issue is that, if you're using any sort of bundler, you have to copy and paste the decoders in your project public folder, and tell the draco loader where to go get them so he can fetch those:

https://github.com/donmccurdy/three-gltf-viewer/blob/5998675b6e5375bc17e851387cbcb34ededf3991/src/viewer.js#L16

This is really painful and I think there should be a `GLTF2Loader` that works the same as the `GLTF2Loader`. Or just update the `GLTFLoader` to support GLTF 2.0 since it's backwards compatible.

In my project I'm using [this GLTF2Loader](http://takahirox.github.io/sparkles/examples/js/loaders/GLTF2Loader.js) I found googling around, and it would be better if I could reuire it directly from Three.js

**Comment by donmccurdy** [comment]
three.js provides two loaders:

- GLTFLoader (glTF 2.0)
- LegacyGLTFLoader (glTF 1.0)

There was a temporary `GLTF2Loader` during the 1.0 —> 2.0 transition, but 2.0 is the default everywhere now.

Both can be used standalone, without any other files other than threejs. You only need DRACOLoader and its decoders if you've applied compression to a glTF 2.0 file — Blender doesn't do this itself, that's usually a manual optimization you can choose to do with something like [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/). In that case, the glTF file contains compressed data requires the Draco libraries to uncompress. The Draco library cannot be bundled easily, because it needs to switch between WASM and JS depending on browser capabilities.

I'd recommend avoiding external forks of the loader, like [GLTF2Loader.js](http://takahirox.github.io/sparkles/examples/js/loaders/GLTF2Loader.js), unless you can see that they've been updated recently.

See: https://threejs.org/docs/#examples/loaders/GLTFLoader

**Comment by marcofugaro** [comment]
Hey thanks for answering @donmccurdy!

You're right it says it in the subtitle 😅

<img src="https://user-images.githubusercontent.com/7217420/50542795-d9ad8000-0bc5-11e9-8edb-b03d2b63e313.png" width="250">

I didn't know about this, I assumed it was only a GLTF 1.0 loader because I tried loading both a 1.0 and 2.0 file, and only the 2.0 was broken.

In more details, here is what happens if I try to load a simple file exported from **blender** (**2.8**, but tried also in 2.79 and there is no change) without fiddling around much in blender or in the gltf-exporter settings. I am using **three v0.99**:

![image](https://user-images.githubusercontent.com/7217420/50542791-c0a4cf00-0bc5-11e9-9369-b339930ddce4.png)

And the model of course is broken.

Tried using that unmantained `GLTF2Loader` loader I found and it works fine, it works fine also in your gltf-viewer, so with the draco loader.

This is the file if you want to take a look, it doesn't look compressed, but I don't know much about gltf files:

https://github.com/marcofugaro/shrimpcat/blob/a72fa0ccd56a9eb42316e422bfb3598c5f7c94d9/public/assets/van.gltf

**Comment by donmccurdy** [comment]
My viewer is using three.js r99's GLTFLoader, without any modifications, so I think there may be something about your scene setup that isn't quite right — could you share a demo with the error? Viewing the model you linked to is working:

https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/marcofugaro/shrimpcat/a72fa0ccd56a9eb42316e422bfb3598c5f7c94d9/public/assets/van.gltf

However, that file looks like it has been downloaded directly from Sketchfab and not Blender — are you sure that's the same file giving the error? The file is not compressed.

**Comment by marcofugaro** [comment]
@donmccurdy You're also using the draco loader [here](https://github.com/donmccurdy/three-gltf-viewer/blob/5998675b6e5375bc17e851387cbcb34ededf3991/src/viewer.js#L188). I am not using in my setup since I am not importing compressed files, like it says in the three.js docs:

```js
// Optional: Provide a DRACOLoader instance to decode compressed mesh data
THREE.DRACOLoader.setDecoderPath( '/examples/js/libs/draco' );
loader.setDRACOLoader( new THREE.DRACOLoader() );
```

[Here is my loading setup if you want to take a look at it](https://github.com/marcofugaro/shrimpcat/blob/a72fa0ccd56a9eb42316e422bfb3598c5f7c94d9/src/lib/AssetManager.js#L146-L148)

But more simply the error is reproducible if you try to load the file like it says in the documentation, but without the draco loader:

```js
// Instantiate a loader
var loader = new THREE.GLTFLoader();

// Load a glTF resource
loader.load(
	// resource URL
	'models/van.gltf',
	// called when the resource is loaded
	function ( gltf ) {

		scene.add( gltf.scene );

		gltf.animations; // Array<THREE.AnimationClip>
		gltf.scene; // THREE.Scene
		gltf.scenes; // Array<THREE.Scene>
		gltf.cameras; // Array<THREE.Camera>
		gltf.asset; // Object

	},
	// called while loading is progressing
	function ( xhr ) {

		console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );

	},
	// called when loading has errors
	function ( error ) {

		console.log( 'An error happened' );

	}
);
```

Refarding the file process, I have downloaded the file from Sketchfab in `.fbx` format, imported in blender 2.8, ideally make some modifications to it, and exported it in gltf 2.0.

**Comment by donmccurdy** [comment]
> You're also using the draco loader.

I am including it, so that people can view compressed models, but the model you linked to is definitely not compressed, and will not use any of the Draco files.

> I have downloaded the file from Sketchfab in .fbx format, imported in blender 2.8, ideally make some modifications to it, and exported it in gltf 2.0.

The file you linked to has not been exported from Blender — if you're asking for help debugging a problem with a file exported from Blender, can you please provide that file?

**Comment by marcofugaro** [comment]
@donmccurdy I'm positive that file is exported from blender, just to be sure I re-exported it and uploaded it here, so this is 100% exported from blender.

[van.zip](https://github.com/mrdoob/three.js/files/2717447/van.zip)

However I was able to know the source of this issue, it's related to the [three-webpack-plugin](https://github.com/wildpeaks/package-three-webpack-plugin) I was using.

Thanks for your clarifications anyway!
