### ISSUE TITLE
Uniforms-types page in the wiki is very out of date

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#15509]
It hasn't been updated since 2014, but there have been quite a few changes since - in particular, "type" is no longer required.

~~https://github.com/mrdoob/three.js/wiki/Uniforms-types~~

**Comment by Mugen87** [comment]
Just for the interested reader^^:

When `WebGLUniforms` was introduced via #8606, `Uniform.type` was no longer necessary. `WebGLRenderer` now uses the information from the [WebGLRenderingContext.getActiveUniform()](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getActiveUniform) call in order select the correct [WebGL API method](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniform) for specifying a value for a particular uniform. This means the renderer just needs the compiled shader program to derived the uniform type information.

Because of this, I suggest to delete the entire wiki page. The existing documentation page about uniforms already covers the most important information:

https://threejs.org/docs/index.html#api/en/core/Uniform

We might want to enhance the documentation with a small guide about how to use structured uniforms, see #10759

**Comment by mrdoob** [comment]
@Mugen87 sounds good 👍

**Comment by Mugen87** [comment]
Okay, the page and the links to it are now gone.

**Comment by Mugen87** [comment]
I think this issue can be closed now since #10759 already tracks the enhancement of the documentation.

**Comment by looeee** [comment]
Sweet! Thanks @Mugen87 😁
