### ISSUE TITLE
ParametricBufferGeometry: Using multiple materials does not work.

### ISSUE THREAD

**Issue by 93Alliance** [mrdoob/three.js#15515]
##### Description of the problem
ParametricBufferGeometry use two materials that do not work.

```
var frontMaterial = new THREE.MeshLambertMaterial({ side: THREE.BackSide });
var backMaterial = new THREE.MeshLambertMaterial({ side: THREE.FrontSide });
var geometry = new THREE.ParametricBufferGeometry(surfaceFunction, width - 1, height - 1);
var targetMesh = new THREE.Mesh(geometry, [frontMaterial, backMaterial]);
scene.add(targetMesh)
```
##### Three.js version

- [ ] Dev
- [x] r96
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
If you want to have different materials for the front and back sides, create two meshes and apply the materials separately. This approach does not make any difference in performance since you have the same amount of draw calls.

The geometry generators will not provide a set of groups to accommodate this use case.
