### ISSUE TITLE
example request: load SVG files as DOM nodes that have position in 3D scene.

### ISSUE THREAD

**Issue by bpetar** [mrdoob/three.js#15528]
##### Description of the problem

ATM, three.js documentation has example how to load SVG file as geometry that behaves like plane in 3d scene - zoom rotate etc (https://threejs.org/examples/?q=svg#webgl_loader_svg). 
Also there is sandbox example how to load SVG shape as DOM element - look at the 'circle' with document.createElementNS (https://threejs.org/examples/?q=svg#svg_sandbox)
But there is no example how to load SVG file as DOM element. I want SVG icon to be positioned in the scene, but to behave like overlay that is always facing the camera and keeps the same scale, that you can easily attach CSS attributes to and mouse click/hover events.

If you can extend sandbox example with one SVG file loaded there that behaves like that red circle that would be perfect.

##### Three.js version

- [x] Dev
- [ ] r100
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by bpetar** [comment]
This example works great! Thank you for quick help.

Here is some royalty free svg urls that you can use:
https://upload.wikimedia.org/wikipedia/commons/b/b0/NewTux.svg
https://openclipart.org/download/219211/options_icon.svg

**Comment by Mugen87** [comment]
If created a custom SVG file (a hexagon) that fits nicely into the existing geometries.

**Comment by bpstrngr** [comment]
When we add some svg as SVGObject in an SVGRenderer scene, i notice they get placed as last children of the domElement, regardless of their set positions. Isn't it a concern that they are not kept in perspective as the camera moves? I have been trying to overcome this by making them <pattern> elements and referencing them in Sprite path fill values as url(#patternid), but it's quirky and meet limitations that i wouldn't have if the depth of the positioning was respected. It might even be considerable a bug because SVGObjects are legit Object3D citizens. I am on the verge of editing the library to make this work, but i wanted to ask if anyone has objections or can fix it more quickly than me who's relatively new to the library? thanks!
