### ISSUE TITLE
modifying the vertices of geometry  in animation is not working

### ISSUE THREAD

**Issue by chinazhaghai** [mrdoob/three.js#15540]
##### Description of the problem

modifying the vertices of geometry in animation is not working , the value remains the origin value;

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/chinazhanghai/78wn2ye0/13/) (latest release branch)

##### Three.js version

- [ ] Dev
- [x] r100
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Fixed your code here: https://jsfiddle.net/6845op3d/

First, when you modify the vertices of an instance of `SphereGeometry`, you have to set `Geometry.verticesNeedUpdate` to `true`. Besides, your `for` loop was wrong. If you want to iterate over an array, you have to determine its length via `Array.length`. You coded `sphere.vertices` instead of ``sphere.vertices.length`.
