### ISSUE TITLE
Missing DirectionalLight example

### ISSUE THREAD

**Issue by ieskudero** [mrdoob/three.js#15589]
I have realized that there is no DirectionalLight example, and I can't find an issue explaining why that is, if there is a reason for it or maybe because no one took care of it yet.

**Comment by Mugen87** [comment]
There is also no example for `THREE.AmbientLight` since it's a very basic type of light. `THREE.DirectionalLight` is used all over the place. `webgl_loader_fbx` demonstrates a nice setup with shadows.

https://github.com/mrdoob/three.js/blob/70438028775dd4d539ebdfdaf1aafd6fbcac43c7/examples/webgl_loader_fbx.html#L85-L92

**Comment by ieskudero** [comment]
I see both lights differently in terms of complexity, especially when you need to set the shadows in the DirectionalLight. Anyway, it is true that many example uses directionalLight.

**Comment by Mugen87** [comment]
> I see both lights differently in terms of complexity, especially when you need to set the shadows in the DirectionalLight.

That's true. If you like to add a new example similar to `webgl_lights_hemisphere`, go for it^^.
