### ISSUE TITLE
Support vertex tangents

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#15692]
via @ondys –

***

A simple cube mode with normal map that simulates flat shading:
[normal_map_flat-20190201T224012Z-001.zip](https://github.com/mrdoob/three.js/files/2823602/normal_map_flat-20190201T224012Z-001.zip)

The cube has smooth geometry normals (no normal seams on cube edges) + a normal map that simulates flat shading.

| threejs flat | babylonjs flat |
|----|----|
| ![three_js](https://user-images.githubusercontent.com/1848368/52153615-93699780-262f-11e9-8559-8fbc74765557.png) | ![babylon_js](https://user-images.githubusercontent.com/1848368/52153625-9cf2ff80-262f-11e9-89c5-b27ae6a780f1.png) |

Babylon.js rendering seems to work correctly but three.js produces a weird looking result (cesium viewer also seem to work correctly)

For comparison, if normal map is set to a constant value (128, 128, 255), the resulting geometry is smooth for both three.js and babylon.js:

| threejs smooth | babylonjs smooth |
|---|---|
| ![three_js_smooth](https://user-images.githubusercontent.com/1848368/52153654-b4ca8380-262f-11e9-85d2-97265bb75ad6.png) | ![babylon_js_smooth](https://user-images.githubusercontent.com/1848368/52153644-ab411b80-262f-11e9-95ec-2cbd4942afad.png) |

Cube with constant normal map is here:
[normal_map_smooth-20190201T224029Z-001.zip](https://github.com/mrdoob/three.js/files/2823609/normal_map_smooth-20190201T224029Z-001.zip)

**Comment by makc** [comment]
maybe because the normals are shared between vertices?

**Comment by donmccurdy** [comment]
Testing with MeshNormalMaterial, the vertex normals look right, but the normalMap difference persists:

| vertex normals only | with normalMap |
|---|---|
| <img width="623" alt="screen shot 2019-02-04 at 9 41 40 am" src="https://user-images.githubusercontent.com/1848368/52226207-2e958380-2861-11e9-9e8d-a711b9058704.png"> | <img width="563" alt="screen shot 2019-02-04 at 9 40 33 am" src="https://user-images.githubusercontent.com/1848368/52226213-30f7dd80-2861-11e9-8b23-5ed73467365f.png"> |

**Comment by WestLangley** [comment]
Please see if you can get the OP to provide an example with a plane only.

**Comment by ondys** [comment]
OP here. 
Could the issue be that the GLTF contains custom tangents that are being ignored? I looked at the normal mapping code [here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl.js) and it looks like three.js is computing the tangents in the shader .. but maybe I'm looking at a wrong shader.

**Comment by donmccurdy** [comment]
threejs does compute tangents in the shader, ignoring custom tangents in the model, yes. I'm not sure how to isolate whether that is the cause... omitting the tangents, will babylonjs still render correctly?

**Comment by ondys** [comment]
When I delete the tangent attribute, it introduces some color variance on the cube faces but the result still looks much "flatter" compared to three.js (see image below). Looking at the three.js code, it doesn't look like the algorithm for generating tangents corresponds to the Mikktspace algorithm prescribed by GLTF spec (in case tangents are not present). Specifically, in Three.js, tangents seem to be completely independent on vertex normals which would explain the results from above. If that's the case, the best solution would be to add support for tangent attribute to Three.js otherwise it would be rather challenging to use GLTF normal mapping.

![image](https://user-images.githubusercontent.com/12868933/52233807-e3856b80-2874-11e9-951d-be91fa50f8d4.png)

**Comment by WestLangley** [comment]
>Could the issue be that the GLTF contains custom tangents that are being ignored?

Yes. three.js ignores attribute tangents.

**Comment by WestLangley** [comment]
Related: #15428

**Comment by ondys** [comment]
Yeah, seems to be the same issues (tangents nor propagated to Three.js from GLTF and Three.js not using tangents attached to the geometry). It would be nice if this could get fixed to make three.js GLTF compliant.

**Comment by donmccurdy** [comment]
I have a branch (https://github.com/mrdoob/three.js/compare/dev...donmccurdy:feat-attribute-tangents-v2) that appears to be working. The DamagedHelmet example (it had similar issues in the past, which we solved differently) looks fine as well. But it will take some time to test this change more thoroughly, and at the moment I don't have much bandwidth, so it could be a while before I can get to a PR.

| without normal map | with normal map |
|---|---|
| ![screen shot 2019-02-07 at 11 56 26 am](https://user-images.githubusercontent.com/1848368/52439881-7cb0be00-2ad1-11e9-8623-3d9b4dd1f6b2.png) | ![screen shot 2019-02-07 at 11 56 51 am](https://user-images.githubusercontent.com/1848368/52439882-7de1eb00-2ad1-11e9-8160-754766cf151b.png) |

**Comment by WestLangley** [comment]
Vertex tangents are 4-component, no? It appears you are treating them as 3-component.

**Comment by donmccurdy** [comment]
@WestLangley see the table under the [glTF • Meshes](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#meshes) section – the `w` component is a sign value (+1/-1) that can be ignored except in calculation of the binormal, to my understanding.

**Comment by WestLangley** [comment]
>The vertex attribute is a `vec4`, but vTBN only (directly) depends on the `.xyz` components.

I would say the matrix depends on `.xyzw`, but I see you are, in fact, using the 4th component to set the correct bi-tangent vector, which was my concern.

Since your `vTBN` matrix will be interpolated in the fragment shader, and will no longer be orthonormal, it may be preferable to pass varyings ` vec3 vNormal`, ` vec3 vTangent`,  and `vec3  vBitangent`, instead, and construct the orthonormal TBN matrix in the fragment shader.

However it is typically done is fine...

And thanks for this!  :-)

**Comment by ondys** [comment]
Thanks Don and everyone else for adding this feature so quickly!
