### ISSUE TITLE
Issue with Display of fbx file

### ISSUE THREAD

**Issue by jogibear9988** [mrdoob/three.js#15745]
##### Description of the problem

FBX File displayed correctly in Microsoft 3D viewer:

![2019-02-08 21_50_45-modell 190207 fbx - 3d-viewer](https://user-images.githubusercontent.com/364896/52505458-d9a09700-2beb-11e9-80ad-d263e56330f4.png)

and wrong with ThreeJS ( https://discoverthreejs.com/apps/loader/ )

![2019-02-08 21_51_25-quickly load and test your models with three js](https://user-images.githubusercontent.com/364896/52505450-d3aab600-2beb-11e9-9be6-2b77306fcae8.png)

[Modell 190207.zip](https://github.com/mrdoob/three.js/files/2846823/Modell.190207.zip)

##### Three.js version

Version of  https://discoverthreejs.com/apps/loader/

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Do you know which program this was exported from?

**Comment by jogibear9988** [comment]
yes, Demo3D

**Comment by jogibear9988** [comment]
@looeee why do you ask? is anything wrong in the file?

**Comment by jogibear9988** [comment]
tested now with bleder, it works also correct

**Comment by jogibear9988** [comment]
seems the biggest issue is the rotation wich got lost when using fbx

**Comment by mrdoob** [comment]
Can you try converting to GLTF using [FBX2GLTF](https://github.com/facebookincubator/FBX2glTF) and loading it with the GLTFLoader?

**Comment by mrdoob** [comment]
Ah, sounds like you already did something like that. #17393

**Comment by mrdoob** [comment]
This reminds me to the Three.js Blender exporter. We never managed to get the orientation of objects robust enough and eventually we removed it.

Sounds like no one is actively working on trying to fix the FBXLoader so it may be a good idea to also remove it and recommend FBX2GLTF from now on...

**Comment by jogibear9988** [comment]
Is it so hard to get the orientation from this format?

**Comment by mrdoob** [comment]
Seems like it is.

**Comment by looeee** [comment]
> Is it so hard to get the orientation from this format?

Yeah, unfortunately. There's two official methods of specifying transforms in FBX, 3DS Max style and Maya style. You can see them [outlined here](https://help.autodesk.com/view/FBX/2017/ENU/?guid=__files_GUID_10CDD63C_79C1_4F2D_BB28_AD2BE65A02ED_htm). 

### 3DS Max

`WorldTransform = ParentWorldTransform * T * Roff * Rp * Rpre * R * Rpost -1 * Rp -1 * Soff * Sp * S * Sp -1` 

### Maya 

`WorldTransform = ParentWorldTransform * T * R * S * OT * OR * OS` 

Each item in the transforms is a transformation matrix, and the whole transform has to be mapped to just two matrices in three.js: `object.matrix` and `object.matrixWorld`.

That wouldn't be so bad, except for a couple of snags: 

1. there's no way to tell which transform type is being used in a file (that I've found) 
2. there are loads of FBX exporters, and while most of them use 3DS max style some may use Maya style - and some implement the transforms incorrectly so we have to deal with bugs as well. 

That's not even considering bone transforms which are equally tricky and which definitely have a few edge cases we haven't solved yet. 

However, as far as I can can tell, all files from 3DS Max and Maya do work. All the bug reports we are getting here regarding transforms seem to be from other programs (Demo3D, Daz3D, Cinema4D etc.). Ideally we'll fix the loader to work for these as well at some point, but it's as likely to be bugs in the exporter as the loader so that makes these very tricky to fix.

**Comment by looeee** [comment]
> Sounds like no one is actively working on trying to fix the FBXLoader so it may be a good idea to also remove it and recommend FBX2GLTF from now on...

The FBXLoader is still very useful for anybody working with DCC tools that don't have glTF exporters, since it allows quick prototyping. It's quite frustrating to have to export to FBX  and then convert to glTF - for large models this process may take several minutes and prototyping often involves making many small changes. Also, as I mentioned above, the loader works fine with files from most major FBX exporters. 

My recommendation when using a DCC tool that only exports FBX is to use FBX for development and glTF for production.
