### ISSUE TITLE
Feature suggestion: Add a PositionalAudioHelper

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#15741]
It's pretty hard to visualise the effect of a `PositionalAudio` node, especially when it comes to adjusting the cone set by [PositionalAudio.setDirectionalCone()](https://threejs.org/docs/#api/en/audio/PositionalAudio.setDirectionalCone). 

A `PositionalAudioHelper` would be very useful in this case. What do people think of adding this?

**Comment by Mugen87** [comment]
Sounds good!

**Comment by Mugen87** [comment]
I've created a first draft of `PositionalAudioHelper`: https://jsfiddle.net/2z7f0opq/

Using an approach similar to `SpotLightHelper` is problematic since directional cones can have large angles like 360 degrees. A flat approach works in this case, too.

BTW: The green part of the cone represents the area with no volume reduction. However, the volume is reduced in the yellow part. In this example, there is no sound outside of the cone.
