### ISSUE TITLE
Shared BufferAttribute serialization

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#15811]
##### Description of the problem

`BufferAttribute` can be shared among geometries (or even it can be referenced twice or more in one geometry). But `.toJSON()` creates the same data many times for such a shared buffer attribute. That leads to non-efficient serialized data and shared buffer attribute will become many duplicated buffer attributes through serialization.

What do you think of adding `attribute` field to serialized json data like this?

```
{
    metadata: { ... },
    attribute: [
        {
            array: [ ... ],
            ....
        },
        {
            array: [ ... ],
            ....
        },
        {
            array: [ ... ],
            ....
        }
    ],
    geometry: [
        {
            data: {
                attributes: {
                    position: 0, // BufferAttribute doesn't have uuid so using index instead?
                    normal: 1,
                    uv: 2
                }
            },
            ....
        },
        {
            data: {
                attributes: {
                    position: 0,
                    normal: 1,
                    uv: 3
                }
            },
            ....
        }
    ]
    ....
}
```

Pros:
- Efficient data in case attribute is shared
- Reproduce the shared attribute even through serialization

Cons:
- Break compatibility if there is any users who exported serialized json data to external file/storage.

##### Three.js version

- [x] Dev
- [ ] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
In the meanwhile, I'm not convinced this feature will provide much benefit since in almost all real-world use cases buffer attributes are _not_ shared between geometries. 

Besides, if the feature is not implemented backwards compatible, existing JSON won't load anymore. Overall, I don't believe the resulting complexity in the library is worth the addition. Especially since `BufferGeometryLoader` will be noticeable more complex than before since it will be not able to deserialize standalone geometries. It would be required to inject shared attributes from external code which I don't think is a good architecture.

I vote to close this issue.

**Comment by takahirox** [comment]
Yes, we need to consider these three things for shared attributes serialization

- JSON data efficiency
- Backward compatibility
- Serialization/Deserialization design change

I must agree that there may not be immediate real-world big benefit while sacrifying a lot of things because shared attribute may not be major use case so it may be ok to make it low prioritized.

But I sometimes hear shared attributes use case. So I'm not sure if we can ignore this use case. And even if we close this issue, probably someone requests one day.

So I'd like to suggest to 1. keep this issue opened or 2. write a note about this limitation and the reason somewhere (maybe in the document or inline comment would be good).
