### ISSUE TITLE
Editor: all colors/textures washed out in r102

### ISSUE THREAD

**Issue by peteshea** [mrdoob/three.js#15903]
In latest version of three.js/editor    materials & textures are appearing very washed out as if overly lit or gamma set way too high. This occurs both with lit materials like Phong and with BASIC material with no lights in scene.

Existing scenes we have been using for prototyping & testing lighting now have very washed out looking textures/materials as of version r102.

##### Three.js version
- [ x] r102 Editor

##### Browsers
- [x ] Chrome
- [x ] Firefox

##### OS
- [ x] macOS 

##### Hardware Requirements (graphics card, VR Device, ...)
Mac Book Pro OSX 10.11.6
2.8 GHz Intel Core i7
Intel HD Graphics 3000 512 MB

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/pull/15858.

@mrdoob for `gammaOutput=true` to be a good default in the editor, we'll need more settings available or set by default:

- color maps should use sRGB encoding
- hex colors provided in the UI should be considered sRGB

Without that, I get different results dragging in a glTF model (which sets encoding correctly) as opposed to adding the texture through the Editor UI manually (which provides no option for this).

![screen shot 2019-03-04 at 10 26 58 am](https://user-images.githubusercontent.com/1848368/53754360-97741980-3e68-11e9-994e-af299f8b7b6c.png)

As discussed in https://github.com/mrdoob/three.js/issues/11337, I actually think both of the changes above would be beneficial to the library itself, not just the editor. But because that is a complex change, a temporary fix in the Editor – or reverting this change – may be needed.

**Comment by mrdoob** [comment]
@donmccurdy 

I think I would prefer keeping the current change but also implement:

1. sRGB to Linear to sRGB conversion automatically in the UI.
2. Treat maps as sRGB by default (except normal, etc)
3. Script (either accessible from UI or pasteable in console) that fixes current scenes.

**Comment by donmccurdy** [comment]
Ok 👍

> sRGB to Linear to sRGB conversion automatically in the UI.

I'd like to see this eventually be implicitly part of `THREE.Color`, perhaps with some `colorManagement` flag to disable it. When the user provides a hex code, it's implicitly sRGB, whereas `fromArray()` etc. would implicitly be linear. This will make it easier to match CSS colors and get more intuitive lighting values.

**Comment by WestLangley** [comment]
Just a few clarifications...

`scene.background` is currently affected by `gammaOutput` _only if it is a texture_.

`gammaOutput` will be renamed `outputEncoding` or `outputColorSpace` at some point.

**Comment by Usnul** [comment]
I got caught out by this too. Still trying to figure out the whole color space conversion flow. It's a bit of a nightmare so far, trying to adapt my old ShaderMaterial. Would be nice if there was a bit of an explanation on this. Here's my trouble, might help others:
https://stackoverflow.com/questions/55077909/faded-color-in-shadermaterial-due-to-encoding-frament/55081355#55081355

**Comment by makc** [comment]
@Usnul I assume RawShaderMaterial is not affected?

**Comment by Usnul** [comment]
> @Usnul I assume RawShaderMaterial is not affected?

That's correct, I haven't seen this issue in RawShaderMaterial. In fact, I have only seen this when trying to write ShaderMaterial using shader chunks from three.js

**Comment by Mugen87** [comment]
@Usnul This is the related question at stackoverflow, right?

https://stackoverflow.com/questions/55077909/washed-out-color-in-shadermaterial

**Comment by Usnul** [comment]
@Mugen87 yeah, I still don't really understand what's going on there. My basic understanding is that there are interlocking hooks between pieces of standard material shader and the renderer itself so when you try to use them in a custom ShaderMaterial - things just don't work. One example is code injection for texture encoding mentioned in that stack-overflow post.
