### ISSUE TITLE
GLTFLoader: multiple cache entries for same embedded image

### ISSUE THREAD

**Issue by audionerd** [mrdoob/three.js#15952]
Because [GLTFParser.prototype.loadTexture](https://github.com/mrdoob/three.js/blob/27811881f61e647ae2b8b009e3032f62739c2c25/examples/js/loaders/GLTFLoader.js#L2009) passes an Object URL to `loader.load`, the image is added to THREE.Cache with an Object URL (a random UUID string each time) as the key.

After loading the same .glb file three times, THREE.Cache.files will look like:

```
blob://96EC1B8D-B513-4858-A051-EDE713598B4C
blob://FCDAAA03-9C00-467C-B3FF-C230551A8C92
blob://ABDE21C5-F197-4108-B1CA-CF874BEC125A
```

Each time, the data is converted from an ArrayBuffer again, e.g.:

`source.bufferView -> Blob -> URL.createObjectURL -> loader.load`

What if the image could instead be cached with a key representing the source .glb file + a "fragment" if the image filename is known? e.g.:

`path/to/scene.glb#embedded-texture-image.jpg`

Then there would not be duplicate cache entries for the same image.

Demo:
https://codepen.io/audionerd/pen/bZodea

A similar issue happens with embedded data uris in GLTF files where cache key is the full data URI (e.g.: `data:image/png;base64,iVBORw0KGg....`). Cache works, but the key is very long.

##### Three.js version

- [x] Dev
- [x] r102

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Do you see measurable load time problems from the additional ArrayBuffer->Blob->Image steps? Frankly I'm not sure what the browser does behind the scenes here, or if the binary data even has to be copied at all in that process. One performance issue that will result of this, however, is that texture memory is duplicated on the GPU.

Unfortunately this is hard to fix, and means GLTFLoader would need its own special cache instead of `THREE.Cache`, or else `THREE.Cache` may have be modified for all loaders, which I'd rather avoid. As you might imagine, "loading the same .glb file three times" is not an advisable thing to do, and there are other issues (e.g. Draco decoding, mesh GPU memory) that will similarly be redundant.

If we could create the texture from the ArrayBuffer without using `URL.createObjectURL` at all, that's worth considering. Otherwise I'm not sure this should be changed.

**Comment by donmccurdy** [comment]
Closing, this probably isn't actionable unless (1) we can measure some impact of the local Blob URLs being duplicated in the cache, and (2) there's an alternative to the current approach.
