### ISSUE TITLE
glTF model is not loaded correctly

### ISSUE THREAD

**Issue by JL-Vidinoti** [mrdoob/three.js#15984]
##### Description of the problem

I downloaded a 3D model from Sketchfab in glTF format and I would like to display it using threejs. I have used the gltf loader code sample from the demo but the model is not displayed properly. I tried to import it in the threejs editor, same problem.
I have tried to load it using CesiumJS and it works correctly
See below.

Expected output:
![expected_output](https://user-images.githubusercontent.com/35372626/54425727-57d5e900-4716-11e9-9d19-57043a17f14d.png)

Actual output:
![actual_output](https://user-images.githubusercontent.com/35372626/54425792-7c31c580-4716-11e9-9e55-7801978f1450.png)

Code sample:
[threejs_sample.zip](https://github.com/mrdoob/three.js/files/2970576/threejs_sample.zip)

##### Three.js version

- [ ] Dev
- [ x] r102
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Your model doesn't look right on the windows 3D builder app either

![test](https://user-images.githubusercontent.com/5307958/54426716-7f977200-4753-11e9-8e7a-0c0b0efeace3.png)

**Comment by donmccurdy** [comment]
This model seems to have some precision issues, and appears broken in Blender and BabylonJS too. Its world scale is roughly in a 1x1 area, but within that it has wrapper objects with a small scale:

```
[ 0.00006332528573693802, 0.00006332529301289469, 0.0000633252857369379 ]
```

around other wrapper objects with large scale:

```
[ 44470.0967128166, 39142.26717924787, 49605.95214651602 ]
```

Running it through validation shows related errors:

<img width="820" alt="Screen Shot 2019-03-15 at 5 13 55 PM" src="https://user-images.githubusercontent.com/1848368/54467976-fa599080-4745-11e9-98be-e915a4f6f994.png">

All of this will cause floating point errors that differ between platforms. It might be worth asking for help from Sketchfab (if it appears correctly in their platform, maybe they can fix the export?) but otherwise I think it requires help from a modeler to fix the file.

**Comment by JL-Vidinoti** [comment]
I understand. Thank you for your support.
