### ISSUE TITLE
Examples: Add outline/stroke/border to a transparent PNG sprite

### ISSUE THREAD

**Issue by Josema** [mrdoob/three.js#16029]
This is a feature request. Would be great the ability to add an outline to a transparent PNG sprite.

**Comment by Mugen87** [comment]
Can you please share a screenshot of what visual result you are looking for? Besides, it is your use case for this feature request? Could you prepare your PNGs before using them in your app?

**Comment by Josema** [comment]
![outline](https://user-images.githubusercontent.com/1819888/54820765-8583da80-4ca0-11e9-8c95-98efe81aeb79.png)

> Why don't you prepare your PNGs according to your needs before using them in the app?

Yes, that's what I've done so far. But using this technique has three disadvantages.

1. More work using my design tool and preparing sprites.
2. More KB for the final user when downloading.
3. Difficult to manipulate inside of Three.js. I have to create a group, import two sprites and make visible the border or not depending on needs.

I see a clear benefit adding this feature inside of Three.js

**Comment by Mugen87** [comment]
Ah I see. I have to admit that such outline effects on sprites are quite common. Maybe it would be a good idea to add a new sprite example that demonstrates how to enhance `SpriteMaterial` with the respective shader code. After a quick search, there seems to exist a few tutorials about that topic.

**Comment by makc** [comment]
doing multiple texture reads in the shader all the time instead of creating the 2nd texture once is hardly good idea. if you don't want to spend extra 2 minutes in photoshop, why not add the code [like this](https://stackoverflow.com/questions/28207232/draw-border-around-nontransparent-part-of-image-on-canvas) to create the canvas with the effect, and then wrap it into THREE.Texture?

**Comment by Josema** [comment]
> wrap it into THREE.Texture?

How do you wrap that canvas into a THREE Texture? I don't see it as an elegant solution.

**Comment by Mugen87** [comment]
You can use [THREE.CanvasTexture](https://threejs.org/docs/index.html#api/en/textures/CanvasTexture) for this.

https://github.com/mrdoob/three.js/blob/f5d3dd917e08bf35098579c8fde26f64b1364d50/examples/webgl_materials_texture_canvas.html#L102

**Comment by Josema** [comment]
Still, create a new canvas and apply that snippet for each sprite is not a good solution in terms of performance IMO.

**Comment by Mugen87** [comment]
I think it's a nice option if the amount of sprites is manageable. If you have many (animated) sprites or the outline effect will vary in color and size, a shader-based solution is more flexible. Another scenario is to use the outline effect in order to highlight selected sprites. Preparing everything beforehand seems inconvenient to me.

**Comment by WestLangley** [comment]
I do not think this is the responsibility of three.js.

**Comment by makc** [comment]
for that many sprites you could use a single canvas + [getImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) + THREE.DataTexture-s, just a tiny bit more code

**Comment by Mugen87** [comment]
I have created a topic for this issue at the forum and a basic fiddle that demonstrates a simple enhancement of `THREE.SpriteMaterial`. Instead of adding a new example, let's experiment at the forum with the code until there is a more sophisticated solution. @mrdoob can still decide then if it's worth to have a new example with the code.

https://discourse.threejs.org/t/how-to-create-a-simple-outline-around-a-png-sprite/6921

I think it's better to continue the discussion there and close the issue for now.
