### ISSUE TITLE
EdgesGeometry.toJSON not working correctly

### ISSUE THREAD

**Issue by Ozymandias1** [mrdoob/three.js#16087]
i try to make a edgesgeometry object and save by json.

but, it can't EdgesGeometry.toJSON() function are work but something weird, 

it is show by type's are EdgesGeometry, but generator are BufferGeometry.toJSON, and any vertex or index data not converted json(it's empty).

![threerr](https://user-images.githubusercontent.com/25314753/55137537-95a22b00-5174-11e9-8ece-2e25682af2d3.jpg)

can i fix it?

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
i7-4790, 16gbRam, Geforce GTX 1060 3gb

**Comment by Mugen87** [comment]
Yes, this is a current limitation of the library. There was already a PR (#14357) to solve the issue but it was not accepted. The problematic part is restoring the helpers during the deserialization process since they depend on other objects. I guess my proposed solution at that time was not convincing since the necessary logic in `ObjectLoader` needs an additional step and introduces some redundancies  😇

**Comment by Mugen87** [comment]
Closing in favor of #16340.
