### ISSUE TITLE
JSM: Documentation for importable examples

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#16220]
It'd be great to have 'how to import this' near the top of documentation for example files, as we add support for them. Like:

```js
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
```

We get enough questions here and in the forums where people are surprised something isn't part of the core library, and this might help with some of that.

**Comment by Mugen87** [comment]
There is also: https://threejs.org/docs/index.html#manual/en/introduction/Import-via-modules

Notice the section at the end of the page:

> Currently it's not possible to import the files within the "examples/js" directory in this way. This is due to some of the files relying on global namespace pollution of THREE. For more information see 

How about adding information about JSM right there?

**Comment by donmccurdy** [comment]
Definitely adding it there would make sense. 👍 I would also be glad to see it on per-file documentation, as the fact that a given file is not part of the core library is a common source of confusion.

**Comment by mrdoob** [comment]
You know what... I think we should start converting all examples to `<script type="module">` 😁

Compatibility seems to be there: https://caniuse.com/#feat=es6-module

We just lose IE11. But we kind of lost it already when using promises in `GLTFLoader` and using the loader in many of the examples. We may want to have a couple of examples using `nomodule` for testing.

**Comment by donmccurdy** [comment]
I'm happy with converting examples to ES modules gradually, but just to mention the option – all of the GLTFLoader examples can be made IE11-compatible just by adding a single script tag to the example with a Promise polyfill. 

As far as I can tell, 'polyfilling' modules for IE11 is not so simple and would result in code that doesn't demonstrate real-world use.

**Comment by garyo** [comment]
Not that my opinion necessarily carries any weight, but as a new three.js user, I'm writing 100% typescript and ES modules. I expect most new projects are at this point. Webpack and other tools can transpile back and add some polyfills for older browsers when needed (I think a lot of people care less & less -- YMMV).

**Comment by looeee** [comment]
> You know what... I think we should start converting all examples to <script type="module"> 😁

I've been doing this for development in my own projects for about a 6 months now, and I'll be using this style for demonstration for most of Discover three.js. 

IMO it's the simplest way of demonstrating something very close to how real world JS projects are written these days, without all the problems of setting up a bundler. People can then take the exact JS code from an example as a starting point and run it through their preferred bundler for their own apps.

We do lose IE11 support, but I suspect this will turn out to be a very small issue now, and it will only get smaller over time. The GLTFLoader examples have not worked on IE11 for at least a year now and nobody has ever complained, that I know of!

> As far as I can tell, 'polyfilling' modules for IE11 is not so simple and would result in code that doesn't demonstrate real-world use.

I've looked into this previously and I don't think polyfilling modules is something we should consider for the examples. It adds too much overhead. If we do make this change, we should officially state that the examples don't support <IE11 - aside from  a couple of legacy examples or `nomodule` examples.

**Comment by mrdoob** [comment]
>As far as I can tell, 'polyfilling' modules for IE11 is not so simple and would result in code that doesn't demonstrate real-world use.
>
> That being the case, do we still want to convert example HTML files to use ES modules?

I think so. Yes.

**Comment by oparisy** [comment]
So @mrdoob pointed me to this issue since coincidentally, I have been prototyping a script aiming at converting `examples` HTML files to JSM-importing ones.

This is a follow up to the manual conversion of a glTF loader example to JSM imports (PR #16072), which I used as a template for required conversions.

### What's the point?
Similarly to `utils/modularize.js`, the goal is to avoid any error prone manual conversion and, more importantly, double maintenance. Even if not all examples may be amenable to automatic conversion, this provides us with a significant set of tests for JSM-converted `examples/js` tools.

It also lessen the need to choose between classic JS and JSM modules, since both could be available at minimal extra cost.

### What are the results so far?
As of now, 91 out of 371 examples are converted. The great majority of those work without any further adjustment, which is promising.

### How does it work?

The generic idea is to parse the HTML to extract `<script>` tags. The main one is rewritten as a `module`, and the others replaced by JSM `import`. Should some `examples/js` tools not be available as modules (or an unexpected construct be met), conversion will not take place.

A filtered `files.js` is also generated with successfully converted examples, for easier testing.

### How can I test it?
This is very much a work in progress! As of now the script can be found [in this fork](https://github.com/oparisy/three.js/tree/ModularizeExamplesHTML), at `utils/modularize_html.js`.

Once cloned :
1. Do an `npm install` (some dev dependencies were added for parsing purpose).
1. Copy `examples` to `examplesJSM` (yes, it's ugly; see discussion below).
1. Run the script: `cd utils && node ./modularize_html.js`.
1. Copy `examples/jsm/html` contents to `examplesJSM` (including `files.js`).
1. Use your favorite [one liner](https://gist.github.com/willurd/5720255) to serve three.js (let's say on port 8000).
1. Browse to `http://localhost:8000/examplesJSM`.

### What now?
I'm interested in improving the conversion rate, then contributing this as a pull request if it suits @mrdoob.

But there are points to be discussed first, the main one being: how can the current folders hierarchy be adapted to host the converted HTML files? I'm quite reluctant to update resource paths through my script (it's already complex enough), so it would be best for the original and converted HTML to be at the same level.

I see two ways to get there:
 * Put the current examples in an `examples/html` folder, and the converted ones in `examples/jsmhtml` or something similar. But that would involve manually updating all resource paths in the original files, yuck.
 * Put the converted files in `examples`, next to the original ones, with an appropriate naming convention. I guess the format of  `files.js` could be adapted to host a reference to both files then.

Obviously I think the second approach makes the more sense, but I'd like to discuss it (or any other suggestion really) beforehand.

**Comment by oparisy** [comment]
@looeee This is exactly my experience, and what makes me want more modules support in three.js.

The orbit camera and the glTF loader are two typical examples very useful to build upon. Being now able to import them directly from modern, module-based code, without any need for a packer or compilation phase, nicely reduces the barrier to prototyping.

**Comment by donmccurdy** [comment]
Thanks @oparisy!

I would rather not maintain two versions of the same HTML examples. Let's convert them in place, incrementally, and leave only a couple examples that do not use imports. If your script can help do that more quickly, getting rid of the old versions, all the better. :)

**Comment by oparisy** [comment]
@donmccurdy Indeed that would be much simpler than my proposals above! Something along the line of: converting a bunch of examples using the script, manually checking they behave properly, then overwriting the corresponding, non-JSM ones? Would that be OK with you @mrdoob?

I won't change the existing behavior then (write converted HTML to `examples/jsm/HTML`) and focus instead on improving the conversion rate and readability of generated HTML.

If there is some kind of "big bang" instead of conversions on a regular basis, maybe I should not do a PR for the script but instead for the HTML examples I will be able to convert? It would also give me more freedom in the introduction of dev dependencies and modifications on the original examples to aid their conversion, since those would stay on my branch.

**Comment by donmccurdy** [comment]
> If there is some kind of "big bang" instead of conversions on a regular basis....

It will be little-by-little. Even if the script is just a gist that developers can copy that's OK i think.
