### ISSUE TITLE
Feature suggestion: Doppler effect for PositionalAudio

### ISSUE THREAD

**Issue by RickyRomero** [mrdoob/three.js#16289]
##### Description of the problem

I was interested in contributing a Doppler effect for `PositionalAudio` in three.js. However, to calculate that, we need vectors representing the trajectory and velocity of the objects in the scene (including the audio observer).

As far as I can tell by looking through the code, three.js doesn't really deal with that kind of information today... the closest related code I could find was [an add-on utility for velocity](https://github.com/mrdoob/three.js/blob/40651f3fa6e6b12a2ae145cf3de14efde04065d3/examples/js/nodes/utils/VelocityNode.js), presumably for use in demos.

Avoiding these physics-based calculations seems like an intentional design decision. That makes sense – I could see it being a slippery slope to adding physics to the library. Do you think I should bolt this on top of `PositionalAudio` in my own implementation instead? Or... would this work better as an addition to the demos?

**Comment by looeee** [comment]
I think this will work best at the app level, rather than added to the core. It would be a good example though, and if you can implement it nicely I would support the addition.

Have you seen this [HTML5Rocks article](https://www.html5rocks.com/en/tutorials/webaudio/positional_audio/)? They give some example code for three.js Doppler effect: 

> Tracking the velocity can be done by getting the object's previous position, subtracting it from the current position and dividing the result by the time elapsed since last frame. Here's how to do it in Three.js:

``` js
...
var dt = secondsSinceLastFrame;

var p = new THREE.Vector3();
p.setFromMatrixPosition(object.matrixWorld);
var px = p.x, py = p.y, pz = p.z;

object.position.set(newX, newY, newZ);
object.updateMatrixWorld();

var q = new THREE.Vector3();
q.setFromMatrixPosition(object.matrixWorld);
var dx = q.x-px, dy = q.y-py, dz = q.z-pz;

sound.panner.setPosition(q.x, q.y, q.z);
sound.panner.setVelocity(dx/dt, dy/dt, dz/dt);
...
```

**Comment by mrdoob** [comment]
@RickyRomero How were you going to implement the doppler effect? WebAudio used to support it natively but they removed it.

**Comment by yomboprime** [comment]
You only need the value of speed of sound in the current medium (i.e. air) and of course the objects and listener velocities to do the doppler calculations which would affect sound pitch.
From [Wikipedia](https://en.wikipedia.org/wiki/Doppler_effect#General):
```
v: The speed of sound
vl: Speed of the listener in the direction towards the sound source (negative if getting farther away)
vs: Speed of the sound source in the direction towards the listener (negative if getting closer to it)

pitch = soundSampleBasePitch * ( v + vl ) / ( v + vs )
```
And for sure it is needed to clamp the pitch to its min and max values. Besides that, I would do a smoothing filter across time on the pitch, to prevent glitches (hard sudden changes which sounds bad).

Sound delays due to propagation are harder to implement and best done in application.

I think it is better to have explicit velocity vectors, perhaps in `object3D.userData.velocity`, instead of relying on position differentiation, which IMO can introduce glitches and audible imprecisions. But it is just my opinion. Anyway having the vectors in userData lets you compute the velocity as you desire.
