### ISSUE TITLE
Missing Object3D.updateWorldMatrix() in the document

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#16291]
##### Description of the problem

No `updateWorldMatrix()` in `Object3D` document.

##### Three.js version

- [x] Dev
- [ ] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
It is an undocumented feature I added to replace a method that does not work correctly.

**Comment by looeee** [comment]
Is it intentionally undocumented or just an oversight?

**Comment by WestLangley** [comment]
It was intentional on my part.

**Comment by gkjohnson** [comment]
@WestLangley Is there a plan for changing the behavior of the documented function or to add this one to the docs in the future? I'm using the function for my work now to make sure just a specific node in a deep hierarchy is up to date.

**Comment by WestLangley** [comment]
@gkjohnson To be honest, I have been trying to get `updateMatrixWorld()` replaced since at least 2015 -- likely longer than that.

`updateMatrixWorld()` does not do what its name implies. It also updates children -- needlessly in many cases -- and isn't even guaranteed to do that correctly.

I believe `updateWorldMatrix()` should be the method that replaces it.

If you are interested, you can help by supporting #16292 as a start.

**Comment by sciecode** [comment]
By the way, this was fixed with #17109
