### ISSUE TITLE
Array clone on DispatchEvent

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/three.js#16408]
I just noticed that in the `DispatchEvent` function from the `EventDispatcher` the listeners array is cloned on every call https://github.com/mrdoob/three.js/blob/dev/src/core/EventDispatcher.js#L71.
That doesn't look like nice for the GC. 
Is there any specific reason that I may be missing why this is working that way instead of just removing that line and iterate directly on `listenerArray`? 
/cc @mrdoob

**Comment by Mugen87** [comment]
> Is there any specific reason that I may be missing

Maybe because one or more event listeners could remove themselves via `removeEventListener()` when an event is dispatched. Like in `onGeometryDispose()`.

https://github.com/mrdoob/three.js/blob/98c70132390300b8fefc3043e34d6638234a0de2/src/renderers/webgl/WebGLGeometries.js#L31

To avoid the clone, you would have to iterate in back-to-front manner. However, this would revert the order of execution. Not sure if this would be a problem.

https://jsfiddle.net/x9pkzb28/3/

**Comment by fernandojsg** [comment]
That makes sense yep, what about using `unshift` instead of `push`? That will make the order correct even if iterating back-to-front 
https://jsfiddle.net/8nwqaept/

**Comment by gkjohnson** [comment]
It could be possible for one of the callbacks to remove _any_ of the other ones, right? Not just itself? So no matter what order you traverse the callbacks in you'll wind up changing the behavior of the class in some cases if you don't clone the array.

**Comment by Usnul** [comment]
listeners: `ABCDE`

imagine we have handled A and B, and we're currently handling C, inside C we remove A and E.

listeners: `BCD`

C's index used to be 2, now it's 1. Indices of all other handlers have changed also, regardless if you traverse forward or backward. This is just one simple example why it's important to have a snapshot of your listener array.

**Comment by mrdoob** [comment]
It has been many years since I wrote that code but I remember it being very fragile. If I find some time I may try to do a test suite for it in its own repo... 😇
