### ISSUE TITLE
Examples: Useless code in index.html

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#16453]
This code is useless. I am not sure it should be deleted or be setted `display: none;`.
https://github.com/mrdoob/three.js/blob/f1bac07f2214fea4ed3a2dad547c67401b1bfd50/examples/index.html#L58-L61

**Comment by sciecode** [comment]
This select tag is there because of the new interface coming on r105. It makes it easier to navigate between docs and examples. Inside docs, this select is used!

Simply deleting or hiding it would make this disappear when changing it from docs to examples.

I, personally, don't believe it should changed. If anything, just remove "zh" option. But even that might mislead users into thinking there are no translations, when, in fact, there are.

**Comment by mrdoob** [comment]
I agree that it should be removed, it was added by mistake.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/18f79c9edba3b063e5929a771797c56ce0b16d68
