### ISSUE TITLE
make EllipseCurve useable as extrudePath

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#16514]
Currently, if I do something like
```javascript
	var circle = new THREE.EllipseCurve (0, 0, 567, 567);
	var geometry = new THREE.ExtrudeBufferGeometry (new THREE.Shape (points), {
		extrudePath: circle, bevelEnabled: false, steps: 100
	});
```
it fills geometry with NaN-s, because circle.getPoint returns Vector2 and somewhere along the code the cross product involving this vector is calculated.

This patch makes it work:
```javascript
circle.getPoint = function (t, optionalTarget) {
	var point = THREE.EllipseCurve.prototype.getPoint.call (this, t, optionalTarget);
	return new THREE.Vector3 (point.x, point.y, 0);
};
```

but, come on, we want this ootb.

**Comment by mrdoob** [comment]
A jsfiddle could be nice to have 🙏

**Comment by makc** [comment]
[Really?](https://jsfiddle.net/hvcng0kp/)

**Comment by Mugen87** [comment]
The `NaN` values are created in `Curve.computeFrenetFrames()` since this method requires 3D vectors. In general, the extrude path of `ExtrudeBufferGeometry` or `TubeBufferGeometry` has to be a 3D curve like `CatmullRomCurve3`.

`EllipseCurve` is similar to `LineCurve`, `QuadraticBezierCurve` or `CubicBezierCurve` a 2D curve and I think it's no good idea to change `getPoint()` in the mentioned way. It _should_ produce 2D points. I'm afraid everything else is just wrong.

**Comment by makc** [comment]
@Mugen87 
> I think it's no good idea to change getPoint() in the mentioned way.

well then you could change computeFrenetFrames or whatever to fill in missing ".z" before doing cross product. or you could just do nothing, fine by me. ended up using LatheBufferGeometry because ExtrudeBufferGeometry generates flat normals and there is no way to hack good normals in.

**Comment by bigmistqke** [comment]
It would be nice if there was a way how you could convert `Line<Vector2>` into `Line<Vector3>`. 
The current set-up severely limits the use-cases of `THREE.EllipseCurve` and other `Line<Vector2>`.
