### ISSUE TITLE
Lensflare bug with multisampled FBO.

### ISSUE THREAD

**Issue by shawn0326** [mrdoob/three.js#16685]
##### Description of the problem

Lensflare used _Renderer.copyFramebufferToTexture_ method. but this will cause bug when i use MSAA because [Can’t read pixels from multisampled FBO](https://community.khronos.org/t/cant-read-pixels-from-multisampled-fbo/67893).

Maybe we should use **blitFramebuffer** instead if it's a **MultisampleRenderTarget** ?

##### Three.js version

- [x] Dev
- [x] Master

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by aardgoose** [comment]
Sadly it is not that simple. blitFramebuffer doesn't provide the directly equivalent to the existing texture copy operation for multisampled framebuffers.  It can only copy/resolve the whole buffer, not the 16x16 patches that the lensflare example.

You _could_ render the lenflares on a second pass after the initial render has resolved the MSAA framebuffer to a normal texture, but its a bit clunky.

**Comment by Mugen87** [comment]
I suggest to mark this issue as `Won't fix` since the implementation of `Lensflare` primarily depends on how `WebGLRenderer.copyFramebufferToTexture()` and thus `copyTexImage2D()` work. 

`copyTexImage2D()` can't be directly used with multisampled FBOs and I see no obvious way to solve this issue in `Lensflare`. It might be necessary to use a completely different approach (without relying on `copyTexImage2D()`) if you want to use lens flares with multisampled FBOs.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人："Mr.doob" <notifications@github.com>
发送时间：2020-05-15 10:51
主题：Re: [mrdoob/three.js] Lensflare bug with multisampled FBO. (#16685)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #16685.
