### ISSUE TITLE
Cannot serialize scene with WebGLRenderTargets

### ISSUE THREAD

**Issue by jsantell** [mrdoob/three.js#16763]
##### Description of the problem

Previously, serializing a WebGLRenderTarget texture was a noop. Introduced in #16651, the serializer attempts to turn a simple object with width/height into a data URL, which fails: 

```
three.js:2740 Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
 ```

Some solutions are:
* Properly serialize render targets (https://github.com/mrdoob/three.js/issues/16762) (:+1:)
* Go back to stubbing out render targets in the serialized form
* Move image info added in #16651 elsewhere (:-1:) 

As of now, this prevents serialization of any scene with a render target texture in use anywhere.

Reproducible here via `scene.toJSON()`: https://threejs.org/examples/webgl_loader_gltf.html Requires patching #16764 to get around scene.background issue, but the environment map used here throws

**Comment by Mugen87** [comment]
This was fixed via #17745. 

`serializeImage()` in the `Texture` class now reports a warning when a texture can't be serialized. A runtime error does not occur anymore.

Because of https://github.com/mrdoob/three.js/issues/16762#issuecomment-504718551, `WebGLRenderTarget`'s `texture` is not supposed to be serialized.
