### ISSUE TITLE
TypeScript  TS2339: Property 'setValues' does not exist on type 'Material | Material[]'.   Property 'setValues' does not exist on type 'Material[]'.

### ISSUE THREAD

**Issue by jiawenquan** [mrdoob/three.js#16770]
##### Description of the problem

TypeError: mesh.material.setValues is not a function
    at 

TypeScript   `Material  `   Can't use `setValues`  `clone`  `copy`  and so on.

```
      if (mesh.material) {

        mesh.material.setValues({wireframe: true, transparent: true, opacity: 0.9});

      }

```

##### Three.js version

- [x] r105

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
That's strange since these methods are actually defined in the TS declaration file:

https://github.com/mrdoob/three.js/blob/79fd2d728c8a6c424bab50534177286f824787bf/src/materials/Material.d.ts#L284
https://github.com/mrdoob/three.js/blob/79fd2d728c8a6c424bab50534177286f824787bf/src/materials/Material.d.ts#L266
https://github.com/mrdoob/three.js/blob/79fd2d728c8a6c424bab50534177286f824787bf/src/materials/Material.d.ts#L260

**Comment by jiawenquan** [comment]
I found out why,I forgot to import `Material `
import { Material } from 'three';
