### ISSUE TITLE
Undepricate SVGRenderer

### ISSUE THREAD

**Issue by TakodaS** [mrdoob/three.js#16884]
While I understand the main purpose of three is for graphics applications, another use is in scientific publications where the ability to output vector graphics is extremely valuable. I thus request that SVGRenderer be included in the main package of three.

**Comment by Mugen87** [comment]
Just because `THREE.SVGRenderer` is located in the examples directory, it does not mean that it is deprecated. 

`THREE.SVGRenderer` will definitely no part of the core since we would have to include many other files for consistency reasons. Besides, since `THREE.SVGRenderer` is now available as a module in the JSM directory, it's more straightforward than in the past to use the file in a more complex project setup. Read the following guide for more information about that topic:

https://threejs.org/docs/#manual/en/introduction/Import-via-modules
