### ISSUE TITLE
Support for gradients in SVGRenderer

### ISSUE THREAD

**Issue by TakodaS** [mrdoob/three.js#16908]
Would it be possible to apply gradients to SVG objects? Has anyone made an example of SVG compatible textures?

Thank you in advance!

Follow up from https://github.com/mrdoob/three.js/issues/1456

**Comment by donmccurdy** [comment]
SVGRenderer cannot support material textures because of the constraints of SVG itself – textures in threejs and other engines use UV coordinates to map parts of the image to parts of the mesh, and that requires per-pixel shader logic that SVG can't provide.

It looks like SVGRenderer does support [sprites](https://threejs.org/examples/?q=sprite#webgl_sprites) though, which are like textures but they can't be wrapped around an object. Not sure if there is any example of that...

**Comment by Mugen87** [comment]
It's also possible to freely define the `SVG` node of a `THREE.SVGObject`.

https://github.com/mrdoob/three.js/blob/abbb75c6e6adfe24264ebb16a7f213680a94fdd4/examples/svg_sandbox.html#L185-L198
