### ISSUE TITLE
About the help site

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#17071]
Suggestion:

1. Create `help.threejs.org` and have it redirect to `discourse.threejs.org`.

2. Refer to it as the three.js "Help Site".

3. Change the issue label to: `Help (please use help.threejs.org).`

I think that "help" is a better word to use in this case than "discourse" or "forum" -- especially for users less-fluent in English.

**Comment by looeee** [comment]
I agree, it's kind of unfortunate we didn't set up a redirect from `discourse.` in the first place. 

However, it's a forum, not simply a "help" site. The Question category is the most popular, but we have other categories too, such as Showcase, Jobs, Resources etc. How about this:

1. Create forum.threejs.org and have it redirect to discourse.threejs.org

2. Refer to it as the "three.js forum" (I think most people are already doing this anyway)

3. Change the issue label to: Help (please use https://forum.threejs.org/c/questions).

Also, 'forum' is the canonical word for discussion sites on the internet, we don't need to worry about non-native speakers not understanding that.

**Comment by Mugen87** [comment]
I personally see no demand for action in this context. It would be new to me that users think the forum is not the right place for getting help.

**Comment by EliasHasle** [comment]
I just tried clicking "Issues" and "New issue" for no other reason than seeing how I am directed to use the forum or StackOverflow if I am looking for help. I only found a Markdown-coded section in the issue text box. You know the kind of preinserted text that it is most tempting to just delete because it alone tells nothing about what _you_ want to say. Does Github offer any alternatives, such as a page/box that pops up when a user clicks "New issue", or a "pinned" issue on top of the list? Anyway, if help requests are a minor problem, it does perhaps not matter much.

StackOverflow contains many old three.js questions, but apart from that, is the forum now considered the main channel for help? I think that is a good idea, anyway, to strengthen the informal ties in the wider user community. StackOverflow is of course a good format for questions and answers, but it is strict, not very social (in the QA part, at least), and also very general (although known three.js names often show up on three.js questions).

**Comment by looeee** [comment]
> Does Github offer any alternatives

The markdown you see is called an 'issue template', and it's by default it's possible to have 'bug report' and 'feature request'. 

The first thing you'd see then when you click new issue is two buttons, for bug or feature request. I think we can set that up without adding more files to the repo. 

Beyond that, we can add custom buttons. It could be useful to add a third 'help request' template, that would then just instruct users to go to the forum instead of posting here.

Further discussion of this probably deserves its own thread though.

> StackOverflow is of course a good format for questions and answers, but it is strict, not very social...

StackOverflow is frustrating as hell. I've been a member there for years and I still can't do basic things like vote on answers. I only gained the ability to comment a few months ago. For this reason I certainly prefer to recommend the forum to new users, it's much more welcoming.

>  I think that is a good idea, anyway, to strengthen the informal ties in the wider user community. 

Agreed, community building is an important aspect of having a forum.

**Comment by WestLangley** [comment]
>I've been a member there for years and I still can't do basic things.

Hmm... I have had no problems with SO.

>I certainly prefer to recommend the forum to new users.

Why then, should I continue maintaining 1300+ [answers](https://stackoverflow.com/search?q=%5Bthree.js%5D+user%3A1461008)?

**Comment by EliasHasle** [comment]
You clearly have very different experiences with SO, and the effort invested may be somewhat relevant...

>I've been a member there for years and I still can't do basic things like vote on answers. I only gained the ability to comment a few months ago. 

I agree that the "50 rep to comment" limit on SO/StackExchange is frustrating. (0 rep to ask/answer, I think!)

> Why then, should I continue maintaining 1300+ answers?

That is an impressive achievement! I suggest having a pinned topic on top of the question forum, asking users to search SO first.

**Comment by looeee** [comment]
> I suggest having a pinned topic on top of the question forum, asking users to search SO first.

[We already do](https://discourse.threejs.org/t/about-the-questions-category/24). Feel free to suggest any changes you think might be appropriate by [opening a thread here](https://discourse.threejs.org/c/site-feedback). 

> 1300+ answers?

Wow, that's an amazing  achievement! Of course, we should keep telling users to search Stackoverflow, and the forum, to see if their question has already been asked. I'm not suggesting otherwise - just that we recommend the forum as the place to ask new questions.

**Comment by WestLangley** [comment]
>1300+ answers

Quite frankly, it has been 7 years, and I would be happy not to have to maintain those answers. :-)

**Comment by EliasHasle** [comment]
> > I suggest having a pinned topic on top of the question forum, asking users to search SO first.
> 
> [We already do](https://discourse.threejs.org/t/about-the-questions-category/24). Feel free to suggest any changes you think might be appropriate by [opening a thread here]

Your link works, but I do not see the thread when I go to the site and visit the Questions category, and nothing show up when I begin a new thread either... But OK. I may suggest changes to the forum on the forum, if that is better.

> Quite frankly, it has been 7 years, and I would be happy not to have to maintain those answers. :-)

You can perhaps just add an API disclaimer to all of them, and refer to the docs and migration guide.

**Comment by looeee** [comment]
>  I do not see the thread when I go to the site and visit the Questions category

The default Discourse behaviour is to unpin topics once a user has viewed them. I guess we could change the setting.

> nothing show up when I begin a new thread either...

I don't think that's possible to change.

**Comment by WestLangley** [comment]
Closing due to lack of traction.

**Comment by EliasHasle** [comment]
At least this issue resulted in a change to staticallly pinned posts on the forum. :-)
