### ISSUE TITLE
WebGLShadowMap not handling context loss/restore?

### ISSUE THREAD

**Issue by evodabas** [mrdoob/three.js#17161]
##### Description of the problem

We're seeing an issue where when the WebGL context is lost, WebGLShadowMap.render is dying with this call stack:
```
Uncaught TypeError: Cannot read property 'type' of undefined
    at WebGLIndexedBufferRenderer.setIndex (three.js:15584)
    at WebGLRenderer.renderBufferDirect (three.js:23376)
    at renderObject (three.js:19222)
    at renderObject (three.js:19234)
    at WebGLShadowMap.render (three.js:19064)
    at WebGLRenderer.render (three.js:23781)
    at render (webgl_shadowmap.html:406)
    at animate (webgl_shadowmap.html:378)
```
This can be reproduced in the webgl_shadowmap example. I've attached a modified version from r104 (I'm having trouble testing in Dev due to 'Strict MIME type checking for module scripts' errors) that adds a button to lose/restore the context. You might have repeat the loss/restore cycle a couple times before the error shows up.

[webgl_shadowmap.zip](https://github.com/mrdoob/three.js/files/3462630/webgl_shadowmap.zip)

##### Three.js version

- [ ] Dev 
- [x] r104

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This is actually a bug in the renderer. The problem is a dependency of `WebGLShadowMap` to `WebGLObjects`.

- The renderer's instance of `WebGLObjects` is passed to the ctor of `WebGLShadowMap`.

https://github.com/mrdoob/three.js/blob/8efec888c2c95f294d0637ceaedf94aa688d8be5/src/renderers/WebGLRenderer.js#L320

- When the WebGL context is restored, the function `initGLContext` is called which creates a new instance of `WebGLObjects`.

https://github.com/mrdoob/three.js/blob/8efec888c2c95f294d0637ceaedf94aa688d8be5/src/renderers/WebGLRenderer.js#L288

- However, this new instance is never used in the existing instance of `WebGLShadowMap`. It still refers to the previous one which causes very strange behaviors.

Right now, I think there are two solutions.

- Assign the instance of  `WebGLObjects` to the public interface of `WebGLRenderer` and directly use it in `WebGLShadowMap`. In this way, the shadow map related code never uses an obsolete object.
- Recreate the instance of `WebGLShadowMap` in `initGLContext` . However, since `WebGLShadowMap` is accessible via `renderer.shadowMap` it's necessary to copy over all public properties like `enabled` or `type`.

**Comment by mrdoob** [comment]
@Mugen87 I vote for option 1 too.

**Comment by Mugen87** [comment]
> Replacing public object references seems no good idea to me.

Um, we are already doing this with `WebGLInfo`. I've created a new PR that avoids a change of `WebGLRenderer`s public API and also fixes a potential issue with `WebGLInfo`.
