### ISSUE TITLE
THREE.ColladaLoader: Animation transform type "translate" not yet implemented.

### ISSUE THREAD

**Issue by i-fuyun** [mrdoob/three.js#17181]
##### Description of the problem
**I use the case of webgl_loader_collada.html , replace the model , like the image.**

![image](https://user-images.githubusercontent.com/5111701/62526749-775be280-b86c-11e9-9e1f-362ccbcf5e27.png)

**Then , preview , error , like the image.**

![image](https://user-images.githubusercontent.com/5111701/62526707-64e1a900-b86c-11e9-9534-5bdd1ea1f0cb.png)

**What can I do to solve these problems .**

##### Three.js version

- [x] Dev
- [x] r107

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> What can I do to solve these problems .

You would have to extend the loader since since it does not support the mentioned transformation types. However, this will be extremely challenging since this part of the Collada specification is really hard to map on `three.js` internals. I've tried to implement this once but decided to stop since the resulting code was a nightmare.

If possible, try to convert your Collada files to `glTF` since (at least from my side) there will no support for this feature.

BTW: Are you using the old `pump.dae` asset from this repository? It was actually the only file I found that uses `translate`, `rotate` and `scale` as animation transform types.

**Comment by i-fuyun** [comment]
> > What can I do to solve these problems .
> 
> You would have to extend the loader since since it does not support the animation of the mentioned transformation types. However, doing so will be extremely challenging since this part of the Collada specification is really hard to map on `three.js` internals. I've tried to implement this once but decided to stop since the resulting code was a nightmare.
> 
> If possible, try to convert your Collada files to `glTF` since (at least from my side) there will no support for this feature.
> 
> BTW: Are you using the old `pump.dae` asset from this repository? It was actually the only file I found that uses `translate`, `rotate` and `scale` as animation transform types.

Yes, the  `pump.dae` asset from this repository of 107dev.

Well, I'll try something else format, like fbx, gltf.
Thank you.
