### ISSUE TITLE
Does the library only work in Chrome?

### ISSUE THREAD

**Issue by yvital** [mrdoob/three.js#17219]
This example: 
https://threejs.org/examples/#webgl_loader_sea3d_bvh
does not work in Firefox, Internet Explorer

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x] Windows

**Comment by Mugen87** [comment]
Since I'm on macOS, I can only test with Firefox. However, the example runs fine on my system with all tested browser (Chrome, Firefox and Safari).

> Does the library only work in Chrome?

No, `three.js` is intended to work with all browsers that support WebGL. Although the official examples do not work in IE11 anymore (because of the usage of ES6 modules), the library itself should still work.

Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by RemusMar** [comment]
> Although the official examples do not work in IE11 anymore (because of the usage of ES6 modules),

Using the ES6 modules was a bad move in my opinion.


> Does the library only work in Chrome? 

The following sample includes most of the THREE best features and it works just fine in all the popular browsers (Chrome, Firefox, Edge, IE11, etc)
https://necromanthus.com/Test/html5/testA_bloom.html

**Comment by mrdoob** [comment]
@RemusMar Sounds like any changes that we do are bad ideas. Gamma defaults, PBR instead of Phong, ES Modules, ... 😉

**Comment by RemusMar** [comment]
They are all good changes Ricardo.
But the backwards compatibility is a MUST.
At least in my opinion ...

cheers

**Comment by mrdoob** [comment]
I agree that backwards compatibility would be ideal but it also increases the complexity of maintaining and evolving the project.

**Comment by yvital** [comment]
Friends! The issue is resolved.
The script did not work Firefox in the old Windows 7 (32-bit)
Windows (64-bit) 10 everything works.
