### ISSUE TITLE
The image texture is fine on the computer and blurry on the phone

### ISSUE THREAD

**Issue by 948911908** [mrdoob/three.js#17258]
The image texture is fine on the computer and blurry on the phone
![微信图片_20190815120050](https://user-images.githubusercontent.com/19320137/63072056-6ab64900-bf54-11e9-8696-972589988165.png)
![微信图片_20190815120057](https://user-images.githubusercontent.com/19320137/63072057-6ab64900-bf54-11e9-9ebd-4d2e9c9b9ba2.jpg)

this is my code:

![微信图片_20190815120427](https://user-images.githubusercontent.com/19320137/63072159-e7e1be00-bf54-11e9-90b3-7cba730378ee.png)

**Comment by Mugen87** [comment]
It seems you are not setting the device pixel ratio in your app. Doing so will sharpen the visual result on retina displays since you are going to render in the full native resolution. Use the following code after you have created the instance of `WebGLRenderer`.
```js
renderer.setPixelRatio( window.devicePixelRatio );
```
Please use the [forum](https://discourse.threejs.org/) if you need more help.
