### ISSUE TITLE
FBXLoader with TGALoader result with bad opacity and UV map

### ISSUE THREAD

**Issue by bpetar** [mrdoob/three.js#17260]
##### Description of the problem

I purchased some fbx models with TGA texture and they load fine in Blender, but in Three.js texture looks transparent and uv maps are off.

I modified fbx loader example a bit to include my model and TGALoader and here is live example (takes some time to load because texture is 60MB):
http://www.dominos.mystic-peanut.com/webgl_loader_fbx.html

This is my result:
http://www.dominos.mystic-peanut.com/assets/barrel.JPG

This is expected:
http://www.dominos.mystic-peanut.com/assets/CaptureBarel01.JPG

##### Three.js version

- [x] Dev
- [x] r107
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
> takes some time to load because texture is 60MB

That's a lot for a barrel! Is it possible to convert the textures to jpg?

**Comment by bpetar** [comment]
Its one texture for 50+ models, barrel is just one of them. All models have
embedded link to this tga file. Yes I can change texture to another format,
and if i edit fbx file to point to new texture this works. Barrel uv looks
good with png texture.

**Comment by looeee** [comment]
Ok, I'll take a look at this sometime, but I'd recommend you use PNG or JPEG anyway unless you have a good reason otherwise.

**Comment by bpetar** [comment]
I would have to modify 50+ fbx files to use png. I would like if this can
be resolved other way around, but I understand if you can't look into it
right now.

**Comment by looeee** [comment]
> I would have to modify 50+ fbx files to use png. 

If you want your app to run on mobile you'll probably have to do that anyway. Models that you buy will rarely be ready to use without work, unless they are advertised as game-ready or lightweight or something similar.

**Comment by Mugen87** [comment]
I've revisited this issue and found out the barrel asset applies the TGA texture not just as a diffuse map but also as an alpha map as well. When I remove the alpha map and set `transparent` back to `false`, the asset is rendered as expected:

<img width="1063" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/925416ac-866e-4a03-b249-a0135315efa6">


I've evaluated the asset in Blender and this was the result:

<img width="524" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/4942beec-cacb-428e-abe9-700ecd6511d3">

The shading looks broken as well since Blender also uses the TGA as a texture and misconfigures the blending. To fix the rendering, I have to remove the alpha map and set the blend mode back to opaque.  

Since even Blender can't properly display it out of the box, I suggest to consider this as a modeling issue.
