### ISSUE TITLE
Issue with Display of glb file 

### ISSUE THREAD

**Issue by jogibear9988** [mrdoob/three.js#17393]
##### Description of the problem

GLB File displayed correctly in Microsoft 3D viewer:

![image](https://user-images.githubusercontent.com/364896/64062050-b28ad080-cbe2-11e9-847c-df8b99edd217.png)

and wrong with ThreeJS ( https://discoverthreejs.com/apps/loader/ )

![image](https://user-images.githubusercontent.com/364896/64062056-bfa7bf80-cbe2-11e9-8e8d-1dd49be6dfc8.png)

[untitled.zip](https://github.com/mrdoob/three.js/files/3562284/untitled.zip)

##### Three.js version

Version of  https://discoverthreejs.com/apps/loader/

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jogibear9988** [comment]
model was created using this fbx: https://github.com/mrdoob/three.js/issues/15745 and using blender to convert to glb

**Comment by fernandojsg** [comment]
I just try opening it on the editor (https://threejs.org/editor/) and it seems to work as expected. I just needed to add a light, maybe you are missing one light there and that's why everything is black.

![image](https://user-images.githubusercontent.com/782511/64062186-dc90c280-cbe3-11e9-8c26-e4d33f3b2ed8.png)

**Comment by jogibear9988** [comment]
ahhh sorry... ;-(

then only fbx is not working correctly
