### ISSUE TITLE
THREE.Audio getVolume() always gives 1 on Firefox

### ISSUE THREAD

**Issue by SirSilverCharles** [mrdoob/three.js#17404]
myAudio= new THREE.Audio(listener);
myAudio.setVolume(0.5);
myAudio.getVolume(); //always gives 1

THREE.WebGLRenderer 104

**Comment by Mugen87** [comment]
The volume is not directly assigned. Instead,  [AudioParam.setTargetAtTime()](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/setTargetAtTime). So the volume is gradually changed over a certain amount of time.

**Comment by SirSilverCharles** [comment]
Sorry if my example was wrong, but I always get audio.getVolume() = 0 even waiting, in firefox, this wroke some code that was functional on chrome.

**Comment by mrdoob** [comment]
Did this broke after updating Firefox? After updating Three? ...?

**Comment by Mugen87** [comment]
> but I always get audio.getVolume() = 0 even waiting,

Can you still hear the audio?

**Comment by SirSilverCharles** [comment]
> Did this broke after updating Firefox? After updating Three? ...?

I usually use chrome so I only noticed after opening the project on firefox for the first time.

**Comment by SirSilverCharles** [comment]
> > but I always get audio.getVolume() = 0 even waiting,
> 
> Can you still hear the audio?

Sorry I mean audio.getVolume() = 1, edited.
Yes, the sound works, you can even change the volume and it does change, but is getVolume the thing that is broken.

**Comment by Mugen87** [comment]
I've prepared a live example: https://jsfiddle.net/kavs8bL4/1/

Indeed, it does work in Chrome but FF (68.0.2) always reports a volume of `1`. Looks like a browser issue...

**Comment by mrdoob** [comment]
@hoch are we doing something wrong?

**Comment by hoch** [comment]
@mrdoob @Mugen87 Can you pinpoint where `audio.getVoume()` happens?

**Comment by mrdoob** [comment]
@hoch Here you have:

https://github.com/mrdoob/three.js/blob/dev/src/audio/Audio.js#L330-L334

**Comment by hoch** [comment]
I can see what the problem is.

Chrome changed the behavior a while ago so the query to `.value` always returns the computed parameter value from the automation. The original (old) behavior is to return the value set by the setter. I think `setTarget()` doesn't really fit into that category so you get the value that is previously set by the setter.

Here's a link to the relevant discussion:
https://github.com/WebAudio/web-audio-api/issues/1788

Specifically this is Audio WG's decision on this issue:
https://github.com/WebAudio/web-audio-api/issues/1788#issuecomment-468345987

So Chrome's behavior is based on the spec and I expect other browsers will follow the spec change soon.

**Comment by Mugen87** [comment]
Good to hear that! Thanks for the explanation 👍
