### ISSUE TITLE
WebGLRenderer missing setClearDepth() and setClearStencil()

### ISSUE THREAD

**Issue by amsXYZ** [mrdoob/three.js#17435]
##### Description of the problem

``WebGLRenderer`` is missing two main functions to grant developers control over how the internal buffers are cleared every frame: ``setClearDepth(depth: number)`` and ``setClearStencil(stencil: number)``. This functionality can be accessed through the ``WebGLState``, but this is rather confusing for various reasons:

* ``WebGLRenderer`` has already ownership of the clearing operations with function like ``clear(color: boolean, depth: boolean, stencil: boolean) : null`` and properties like ``autoClearDepth`` and ``autoClearStencil``, but cannot control the value it clears depth/stencil to.
* Similar functions ``setClearAlpha(alpha: number)`` and ``setClearColor(color: Color, alpha: number)`` already exists to expose the color buffer clear state, which makes us wonder why the depth and stencil buffer are treated differently.

Getters for these values should also be implemented and, ideally, these values should be configurable on construction, avoiding this [hardcoded clear statement](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLState.js#L395) on initialization and better matching every application needs:

``` javascript
// init
colorBuffer.setClear( 0, 0, 0, 1 );
depthBuffer.setClear( 1 );
stencilBuffer.setClear( 0 );
```

**Comment by Mugen87** [comment]
> which makes us wonder why the depth and stencil buffer are treated differently.

I think because most users would never use this API. Even `setClearColor ()` and `setClearAlpha()` has more an internal relevance since it's mostly used in context of post processing. The project actually promotes using `Scene.background` if users want to configure an opaque clear color (which is actually sufficient for most use cases).

I think it's totally fine if advanced users like you directly work with `renderer.state`.  The mentioned hard coded values are a bit unfortunate but I think it's difficulet to change this now. Creating an instance of `WebGLRenderer` also creates the instance of `WebGLState`. So you can't configure default values via setters which are used in the init routine. You would have to pass them into the renderer's ctor (whose signature is reserved for `WebGL` context parameter).

**Comment by amsXYZ** [comment]
I think having this methods could clean up some uses advanced cases without cluttering the API too much. It's true that no new functionality would be included, but I think it'd allow advance users to write a tiny bit nicer code that goes along the usual best practices...

Maybe I do the PR myself if I have time one of these days to showcase how it could be done ;)

PS: I'm just writing a reversed depth camera and it's just pains me a bit that I have to go through ``renderer.state`` for such a trivial feature 🤠

**Comment by Mugen87** [comment]
Let's reconsider this if more developers request the same feature.
