### ISSUE TITLE
GLTFLoader: Support map in LineBasicMaterial

### ISSUE THREAD

**Issue by lappy4711** [mrdoob/three.js#17511]
Was there a significant change in the GLTFLoader in version 90? We're having problems with gltf/glb files that we export from Paraview, the colors are not visible in our viewer. If changing the version to version 89, the colors are visible. Here is an example file:
[005.zip](https://github.com/mrdoob/three.js/files/3619423/005.zip)

**Comment by mrdoob** [comment]
Do you mind sharing screenshots?

**Comment by lappy4711** [comment]
Here you go.

V92:
![v92](https://user-images.githubusercontent.com/15850938/64980841-0112bd00-d8bb-11e9-95db-7d0aa2d9cc1d.png)

V89:
![v89](https://user-images.githubusercontent.com/15850938/64980890-21427c00-d8bb-11e9-9d16-aece1bbc4a6f.png)

Note, not my codepen. All I did was to paste in my file in the loader and change the version numbers.

The original codpen is https://codepen.io/siouxcitizen/pen/QroPwJ

**Comment by lappy4711** [comment]
A colleague saw the images and said "that looks looks like a color space issue". It seems that the default color space in Paraview is "diverging". My best guess right now is that the Paraview UI export code converts to rgb before exporting and that we must do that as well in python. Don't know though why v90 and above is more unforgiving regarding color space (if this is correct). Will update when our Paraview script guy has implemented explicit conversion to rgb.

**Comment by donmccurdy** [comment]
@lappy4711 have you seen the *Textures* section under the [THREE.GLTFLoader](https://threejs.org/docs/#examples/en/loaders/GLTFLoader) documentation? If you aren't using those renderer settings, you will see color space issues, but I don't think that's the cause here.

@mrdoob @takahirox the change was caused by https://github.com/mrdoob/three.js/commit/b965ef12c922af2778d3238b9267919828e333e0. With that commit we began using LineBasicMaterial for lines, which doesn't support a base color `.map`, instead of MeshStandardMaterial or MeshBasicMaterial. Would we want to add texture support for LineBasicMaterial, or is that out of its scope? 🤔

**Comment by mrdoob** [comment]
GLTF support a texture for lines? Does it also have uvs?

**Comment by lappy4711** [comment]
@donmccurdy I have tested
renderer.gammaOutput = true;
renderer.gammaFactor = 2.2;

I don't think
texture.encoding = THREE.sRGBEncoding;
is applicable since I'm not loading any textures (and neither is the codepen example I used for illustration of the issue)

**Comment by donmccurdy** [comment]
@lappy4711 this model does contain a texture, attached below. Those settings are good to use, generally, but they aren't the problem in this case.

![0050](https://user-images.githubusercontent.com/1848368/64994190-d9a4fb80-d88c-11e9-9cab-72658bced10f.png)


@mrdoob because glTF uses PBR materials, the section on materials for lines and points is [pretty sparse](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#point-and-line-materials).  But yes, this model contains both a texture and UVs on a Lines primitive.

**Comment by lappy4711** [comment]
Adding some more info....the colors are visible with three.min.js versions 90 and above...but if change GLTFLoader.js to 90 and above it is all white.

**Comment by mrdoob** [comment]
> Adding some more info....the colors are visible with three.min.js versions 90 and above...but if change GLTFLoader.js to 90 and above it is all white.

How's that possible? We never supported textures in `LineBasicMaterial` 🤔

**Comment by donmccurdy** [comment]
In r90 GLTFLoader switched from using MeshStandardMaterial to LineBasicMaterial for lines.

**Comment by mrdoob** [comment]
Oh... Can Lines have normals too in GLTF?

**Comment by donmccurdy** [comment]
Hopefully no one will be shocked if their normals don't there, but yes, glTF does not prohibit lines and points from having normals, tangents, skinning weights/indices, morph targets, or custom vertex attributes.

**Comment by mrdoob** [comment]
I guess we may need a `LineStandardMaterial`? What about `Points`?

**Comment by donmccurdy** [comment]
Just getting LineBasicMaterial closer to feature parity with MeshBasicMaterial would be enough, I think. A PBR shading model for lines is more than anyone has asked for. Pretty much just supporting `.map`, along with emissive and AO perhaps?

Although if MeshStandardMaterial already 'just works' with lines, and LineStandardMaterial can reuse that implementation without duplicating much code, that's great. I'd be curious how things work in NodeMaterial now; I still want to add a `gltfLoader.setUseNodes( true )` option.

**Comment by Mugen87** [comment]
> I still want to add a gltfLoader.setUseNodes( true ) option.

Just for reference: #14572

**Comment by lappy4711** [comment]
So what is the advice? Wait or fix or use the r89 loader?
Thanks

**Comment by donmccurdy** [comment]
@lappy4711 I don't know what the fix is yet, on when it will be ready. If you need to apply textures to lines, in the meantime, you'll need to either use r89 or load the texture separately from the rest of the model.

**Comment by lappy4711** [comment]
@donmccurdy we just realised that we should add a "Tube" filter to the streamlines in Paraview. We now have colors, so I can keep using the latest loader.
