### ISSUE TITLE
Homepage and examples broken in Internet Explorer

### ISSUE THREAD

**Issue by rypskar** [mrdoob/three.js#17524]
##### Description of the problem
I wanted to check out how the examples worked in IE to compare with my project and found that  https://threejs.org/ and all pages under is broken in IE. IE do not support css var() and ES6 Import, so would require polyfills or changes to the build. 

Example image from the documentation section
![image](https://user-images.githubusercontent.com/2808460/65123388-679af680-d9f3-11e9-9156-49d70f4fc315.png)

Maybe at least put up a banner asking users to change to Firefox or another modern browser?

##### Three.js version

- [ ] Dev
- [ x] r108
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Yes, the examples do not support Internet Explorer anymore because of the migration to ES6 modules. I guess when the documentation was not tested with IE when the redesign was done.

> Maybe at least put up a banner asking users to change to Firefox or another modern browser?

I do not vote for spending time in doing this since IE is completely out of date. It should be clear to users that this browser is not a good option in 2019 anymore.

**Comment by donmccurdy** [comment]
Might be worth showing a banner or error message, pointing users to https://browsehappy.com/ or something similar.
