### ISSUE TITLE
Suggest: Use GitHub Actions to CI for three.js

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#17688]

**Comment by mrdoob** [comment]
What are the benefits?

**Comment by Mugen87** [comment]
Closing for now. Working with Travis CI makes no trouble so far. 

@linbingquan Please open such an issue only if you can explain the benefits for doing this change. Otherwise the project maintainers spend time in stuff which is currently not necessary. Time which is then missing to review PRs or develop new features.
