### ISSUE TITLE
logarithmicDepthBuffer broken on NVidia 10x series ( at least )

### ISSUE THREAD

**Issue by olivierchatry** [mrdoob/three.js#17791]
##### Description of the problem

logarithmicDepthBuffer is broken on NVidia hardware.
Repro : On 1080 and 1070 ( only nvidia GPU I have ), launch the logarithmicDepthBuffer sample, 
weird artifacts happens.

This is **not** happening on 108 ( so only master / 109 ).
Works on Radeon ( RX570 and Vega56 ), did not test on intel.

##### Three.js version

- [x] Dev
- [x] r109

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
- [x] NVIDIA GPU ( only tested on  1080, and 1070, latest driver )

**Comment by Mugen87** [comment]
Do you see any warnings/errors in the browser console?

**Comment by looeee** [comment]
> weird artifacts happens

Can you provide a screenshot of the artefacts?

**Comment by olivierchatry** [comment]
Actually, exactly the same as :
https://github.com/mrdoob/three.js/issues/17623

**Comment by gkjohnson** [comment]
@olivierchatry It sounds like the same issue as #17623 like you mentioned. Does this still happen on the current dev branch? I would expect #17631 to have fixed it.

**Comment by olivierchatry** [comment]
Yes it does. Cloned the repos, build it, same error. I will try again
today, just to be sure.

**Comment by gkjohnson** [comment]
I just upgraded to a 2070 and am able to reproduce the issues from #17623 with this hardware but the problem is resolved in latest dev. I tested using the "camera / logarithmicdepthbuffer" example in the repo. Just run `npm start` in the root of the repo and navigate to http://localhost:8080/examples/index.html?q=log#webgl_camera_logarithmicdepthbuffer.

Here's a before and after of what I see on the current three js examples website (left) and what I see when running the example locally with the latest dev branch (right):

![image](https://user-images.githubusercontent.com/734200/67361883-a9e9b300-f51e-11e9-90df-64b483abe8a3.png)

So for me the issue is addressed in dev. If it is still broken for you do you mind posting a screenshot of what you see when running locally on dev?

**Comment by olivierchatry** [comment]
Also if that change anything ( but I don't think it should ), I accessed
the sample directly through
http://localhost:8080/examples/webgl_camera_logarithmicdepthbuffer.html

**Comment by olivierchatry** [comment]
Yup, my mistake, I was checking out `master` which is r109. Once I checked out `dev` bug disappeared. Really sorry for the mistake. Closing.
