### ISSUE TITLE
Multiview breaks oculus browser

### ISSUE THREAD

**Issue by wizgrav** [mrdoob/three.js#17829]
##### Description of the problem

Oculus browser reports the OVR_multiview2 extension even on a webgl1 context enabling multiview which then tries to use WebGL2 methods and fails. Workaround for now is to enable antialiasing, which will disable multiview, but we should check for webgl2 presence specifically

##### Three.js version

- [x] Dev
- [x] r109
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Oculus browser
##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [x] Oculus

##### Hardware Requirements (graphics card, VR Device, ...)
Oculus quest

**Comment by fernandojsg** [comment]
This should be a bug on the oculus browser, as OVR_multiview2 should not be listed on WebGL1 contexts /cc @Artyom17

**Comment by wizgrav** [comment]
@fernandojsg yeah I agree, but it wouldn't hurt to check for WebGL2 as well

**Comment by Artyom17** [comment]
@fernandojsg @wizgrav @mrdoob  OVR_multiview2 should be fixed in just released Oculus Browser 6.2 (check out Oculus Store). OVR_multiview2 is also enabled by default since this version. Refer to https://developer.oculus.com/documentation/oculus-browser/latest/concepts/browser-multiview/ for more details.

**Comment by fernandojsg** [comment]
@Artyom17 that's great! thanks for the info!
