### ISSUE TITLE
Cars example broken?

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#17824]
##### Description of the problem

Maybe this was intentional but the car looks extremely flat. There's no evn map, the interoir looks flat shaded

Before:

![car-old](https://user-images.githubusercontent.com/234804/67666954-36c5be00-f9b0-11e9-918d-63d77fd002fe.jpg)

After: 

![car-new](https://user-images.githubusercontent.com/234804/67666981-404f2600-f9b0-11e9-9986-5c16cd0084c8.jpg)

It might be hard to see between those examples but if you try them it's like the environment map and/or the specular highlights are missing in the newest version. If that was intentoinal sorry .

##### Three.js version

- [ ] Dev
- [X] r109
- [ ] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
> There's no evn map

The environment map is actually applied. Apart from the brighter lighting , I don't see much a difference compared to `R97`:

https://rawcdn.githack.com/mrdoob/three.js/r97/examples/webgl_materials_cars.html

Feel free to tweak the material parameters if you like to optimize the appearance.

**Comment by looeee** [comment]
Two changes were made to this example post R97:

* Shadows (ambient occlusion, that is) are now [a transparent PNG](https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/ferrari_ao.png) attached to the car, rather than a shadow map. 
* The `DirectionalLight` and `HemisphereLight` were removed, all lighting is now from the PMREM

Regarding the lighting, the PMREM is generated using an LDR environment map. That's the reason for the lack of specular highlights. 

I think that it's not valid to use a LDR cubemap to generate the PMREM, but I'm not 100% sure of that. In any case it would give better results to switch to a HDR map, especially when it's the sole source of lighting in the scene.

**Comment by mrdoob** [comment]
That's right. The real issue here is the fact that it was using a LDR cubemap.

I've just did a second pass at beautifying it... https://github.com/mrdoob/three.js/commit/93eb40d06fb17748cc66e6c4c26f94dbc68f1969

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_cars.html 

This is how the car looks like in red now:

<img width="846" alt="Screen Shot 2019-11-08 at 4 10 32 PM" src="https://user-images.githubusercontent.com/97088/68518760-57a8d180-0242-11ea-88be-a977ca7538c0.png">

**Comment by mrdoob** [comment]
Inspired by the photo 🤓

![image](https://user-images.githubusercontent.com/97088/68519456-04d11900-0246-11ea-8713-1e58932b1418.png)

**Comment by mrdoob** [comment]
Hard to see, but with the new `PMREMGenerator` the rough areas of the car (the interior mainly) have more contrast.

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_car.html

<img width="898" alt="Screen Shot 2019-12-04 at 1 51 31 PM" src="https://user-images.githubusercontent.com/97088/70185092-06073180-169e-11ea-8da6-931bcf8dc7e7.png">
