### ISSUE TITLE
Feature Request: GCode Exporter

### ISSUE THREAD

**Issue by LetsPrint3D** [mrdoob/three.js#17981]
ThreeJS is widely used across a range of web based tools for 3D Printing, CNC, etc. and utilizes the STLLoader / GCodeLoader and STLExporter for a variety of operations.

However, GCode is the necessary file type that 3D Printers actually read, where an exporter would drastically enhance the potential capabilities of these tools. Ultimately allowing for 3D model conversions from a number of other file types, although most commonly from an STL import -> GCODE export.

For a more detailed explanation of G-Code commands...
http://marlinfw.org/docs/gcode/G000-G001.html
https://reprap.org/wiki/G-code

As a whole, the primary command is "G1" which is simply used to move between coordinates. I have attached a sample G-Code file of a cube for reference.
[cube.zip](https://github.com/mrdoob/three.js/files/3878415/cube.zip)

**Comment by Mugen87** [comment]
Isn't using using 3MF more future-proof? According to this [article](https://all3dp.com/a-new-format-for-the-age-of-3d-printing/):

> At the moment, your CAD software usually works with other formats than .stl for a variety of reasons. Most construction software can actually output .stl files though. Your printing software takes the .stl files and slices them, in most cases to G-code format; these sliced files which can have numerous endings, such as .mpt, .mpf .nc and others. **The .3mf format will put an end to the variety of files needed for the whole process of construction, modification and manufacturing of 3D models, according to the consortium.**

**Comment by LetsPrint3D** [comment]
3MF will likely become more widely adopted in the next couple of years, but it's barely a consideration for the average person right now. The most popular 3D Model file sharing sites like [Thingiverse](https://www.thingiverse.com) and [MyMiniFactory](https://www.myminifactory.com) have hundreds of thousands of freely available designs, almost all posted as STL files.

Over time I could see the format change and be replaced by something like 3MF, but we're a long way out from that still. Certain software (ex: Cura) and sites (ex: PrusaPrinters) have recently added support, but widespread adoption of this hasn't caught much attention.

**Comment by mrdoob** [comment]
So basically you're asking us to write a slicer in js, right?
Doesn't sound super easy, but maybe someone would like to give it a go.

**Comment by LetsPrint3D** [comment]
As there is already a G-Code Loader for ThreeJS, I was under the impression it would be relatively straight forward to make an exporter as well. I'm sure that is a naive way to look at it, but was hopeful.

I have very limited experience working with 3D space, can only comment in regards to G-Code itself. In a nutshell though, it basically picks a starting vertex at the base of the mesh and moves around the X/Y axis, writing each individual point to file with the "G91 X0.0 Y0.0" move command. When it gets back to the start point, it raises the Z axis by whatever increment is specified (layer height) with "G91 Z0.0" for example, and then repeats until completed.

The only complexities I can really see would be Start/End scripts. Basically a set of various commands inserted in the head/foot of the file that run before and after the print. I would imagine just taking a parameter array of startCommands and endCommands would be sufficient.

**Comment by mrdoob** [comment]
Sounds like you are halfway there then. Would you like to give it a go using the loader as reference?

**Comment by Mugen87** [comment]
In the meanwhile, I see this issue similar to #18984.

I guess it's okay to add an example by using an external library. But the library itself (which implements the actual G-code export) should not be part of this repository.

**Comment by jgphilpott** [comment]
@LetsPrint3D has there been any progress on this since 2019? I'm also very interested in this feature and willing to help out if possible!

**Comment by mrdoob** [comment]
We now have [`three-mesh-bvh`](https://github.com/gkjohnson/three-mesh-bvh) which should make things much easier:

https://gkjohnson.github.io/three-mesh-bvh/example/bundle/clippedEdges.html

**Comment by jgphilpott** [comment]
Okay thanks @mrdoob I will take a closer look at it over the weekend. It still feels like an enormous task to generate machine usable Gcode from this but I will press onward.

Currently im exporting my scene to an STL or OBJ file and then slicing it with software like Cura or GoSlice. But I want to be able to do it all in the browser for a more seamless user experience. Considering the size of the 3D printing industry im surprised how hard it is proving to find a decent slicing library for the browser.

**Comment by gkjohnson** [comment]
I know nothing of the GCode format but from the [loader example](https://threejs.org/examples/?q=gcode#webgl_loader_gcode) it looks like it's just a series of nozzle movements for each 3d printed layer of the object. As @mrdoob mentioned the three-mesh-bvh example can be used to very quickly derive the series of outline edges for each layer and then they can be sorted into coherent sets of connected lines for each layer.

The hard part, though, seems like optimizing the line order for speed, safely generating the paths to move the printhead between points to start / stop printing, and generating an internal structure for hollow models so they don't collapse or are at least solid. For that last point three-mesh-bvh can be used to determine the inside and outside of the model quickly (see [the voxelization example](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/voxelize.html)) which may help. It would be worth looking into how some existing tools generate the structures for this.

@yomboprime may have some more insight here since they've worked on [generating 3d print files previously](https://twitter.com/yombo/status/1441432395211841536), as well.

**Comment by yomboprime** [comment]
@gkjohnson You're right, a GCode slicer (FDM technology) is way more complex than a resin print slicer (which is what I did on that tweet). There are a lot of parameters involved in generating GCode. Just take a look at the configuration menus of Prusa Slicer or Cura Slicer. For many years new complex algorithms have been developed, like new infill patterns and the recent Arachne technique. They're way beyond my capabilities.

**Comment by jgphilpott** [comment]
Okay @mrdoob i've taken a closer look at this and [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh) definitely looks like an essential tool for anyone wanting to develop Gcode slicing software in JS. I'm also interested in [three-bvh-csg](https://github.com/gkjohnson/three-bvh-csg) since the tool im working on already uses [csg](https://github.com/evanw/csg.js), @gkjohnson thanks for these!

@yomboprime your [MinceSlicer](https://github.com/yomboprime/MinceSlicer) is essentially what i'm looking for except with FDM support and without the GUI. I have an Ender 5 Pro and I want to be able to export directly from my three.js scene to a Gcode that I can use on it. Thus eliminating the need for intermediary file formats like STL and OBJ as well as other slicing software like Cura.

It's definitely possible, if you start with very simple objects like a small cube or cylinder. Then gradually scale up the complexity and number of settings you can support, but undoubtedly an enormous task with many unforeseen challenges!

**Comment by Mugen87** [comment]
Closing. A GCode exporter is too specific for this repository. This should be maintained in a separate one and then an external example can be added like with `IFCLoader`.

**Comment by jgphilpott** [comment]
FYI, for anyone who comes across this thread. I am working on this issue [here](https://github.com/jgphilpott/polyslice), but im not very far along yet. Between work, family and my other projects it's hard to find the time but ill keep working on it and im also very willing to contribute to another project that's further along. Im focusing on FDM cuz thats what I have but it would be awsome to have a universal slicer that's three.js compatible!

**Comment by LittleSound** [comment]
My 3MF exporter might be able to help you：https://github.com/mrdoob/three.js/issues/18984#issuecomment-2801135048

**Comment by jgphilpott** [comment]
**Hey everyone, I know it's been a couple years but I finally have some progress to show here. I put a [YouTube video](https://www.youtube.com/watch?v=V2h3SiafXRc) together to demo my Polyslice slicer. It’s just a little over 30 min, don't feel like you have to watch all of it but I actually think you might find it interesting.**

@Mugen87, you mentioned in your closing comment that it would be a possibility to include an external example here while the code is maintained in a separate repo. I am working on a [draft PR](https://github.com/mrdoob/three.js/pull/32502) that would include an example of how to use Polyslice as a G-code Exporter. I would appreciate your guidance/advice on exactly how this should look/work!

@yomboprime my slicer currently only supports FDM printing but I would love to add support for resin printing and other techniques as well. I prompted copilot to study your MinceSlicer repo and provide some advice/recommendations on how it could help to add resin printing support to Polyslice. [This is the PR](https://github.com/jgphilpott/polyslice/pull/90) it produced, if you're interested in collaborating at all this could be a starting point perhaps?

@gkjohnson your code in three-mesh-bvh was inspiring and helped me a lot with the plane-triangle intersection needed to create the outer walls, so thanks for all your awesome work!

@LittleSound I didn't use your 3MF exporter in this project but I think I might include it in another project of mine ([Polysmith](https://github.com/jgphilpott/polysmith)) that is more of a design software rather than a slicer, so thanks for sharing!

@mrdoob thanks for the star, it was a big encouragement!

@LetsPrint3D are you still alive?

**Comment by GitHubDragonFly** [comment]
@jgphilpott just for the sake of trying I did create a simple [GCODE Exporter](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/5f3483e5f3d61011ed1e0035a2b01eb16c59b45c/viewers/static/jsm/exporters/GCODEExporter.js) using your library.

I don't have access to a 3D printer for testing and the overall code approach might be inaccurate so feel free to make any correction suggestions by responding here.

Several of my viewers currently include this exporter but probably the easiest testing could be done via my [PLY+STL Viewer](https://githubdragonfly.github.io/viewers/templates/PLY%20Viewer.html), just load some simple PLY or STL file and try exporting it to GCODE.

Units and positioning might be off so inspect the exported file before doing any 3D printing.
My exporter is currently set for Ender3 and GenericPLA but these could be eventually changed (there is no routine in my viewers to do this currently).

As an FYI, the last line of the exported gcode file looks like this:
- "M300 P1000 S420M117 Print complete!", not sure if the "M117 Print complete!" should go to the next line

**Comment by jgphilpott** [comment]
Wow @GitHubDragonFly! I'm thrilled to see that someone is using the package already! Great catch on the missing new line char, I pushed a [new commit](https://github.com/jgphilpott/polyslice/commit/5e386b24f0f58df75fbe3de50fedc3682136e6e1) to fix this already. I see your exporter is currently locked into `v25.12.8`. If you change it to just `https://cdn.jsdelivr.net/npm/@jgphilpott/polyslice/dist/index.browser.esm.js` you should get the latest version (`v25.12.9`) that I just published and it includes your fix 👍

Your [PLY+STL Viewer](https://githubdragonfly.github.io/viewers/templates/PLY%20Viewer.html) looks interesting, I have something similar with my [G-code Visualizer](https://jgphilpott.github.io/polyslice/examples/visualizer/visualizer.html). Not having access to a 3D printer is not necessarily going to be a limiting factor, lots can still be done without one! If you can identify and fix problems with the G-code that you see visually (or manually as you have already done) then it can be tested/verified by someone else that does have access to a printer, like me. **I would love to discuss further but I think future discussion should move to the Polyslice repo, please don't hesitate to [open an issue](https://github.com/jgphilpott/polyslice/issues), even just general (non technical) comments/questions are welcome as topics!**
