### ISSUE TITLE
StandardNodeMaterial alpha input compile issue

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#18038]
##### Description of the problem

/ping @sunag 

I found an issue with the alpha input of StandardNodeMaterial.
The alpha layer is not properly compiled at first and it requires to render the scene twice to get it right.

Every time the alpha input is updated and the needsCompile flag is set to true, the same issue reappears.

![alpha](https://user-images.githubusercontent.com/45501180/69921263-2b0c7080-14f5-11ea-80f6-6a8dd678d7da.jpg)

* [jsfiddle](https://jsfiddle.net/aqzdLwh7/1/) (r111)

Uncomment the last line - renderer.render() to see the difference.

##### Three.js version

- [x] r111

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by sunag** [comment]
`material.setBlending` is called before of `material.onBeforeCompile` it could be inverted the call order?

/ping @Mugen87

**Comment by Mugen87** [comment]
> material.setBlending is called before of material.onBeforeCompile it could be inverted the call order?

Can you please show the code in the renderer you are referring to?

Um, I've debugged the issue a bit and it seems the first call of `render()` does not render the cubes in the correct order. The rendering is front to back although it should be the other way around. That happens because the cubes are interpreted as opaque and thus are placed in the wrong render list.

For some reasons, the `transparent` property of `StandardNodeMaterial` is `true` during the first render.

**Comment by sunag** [comment]
> Can you please show the code in the renderer you are referring to?

Yes, of course. Do you see any problem if I call `setMaterial` after `setProgram`? Thus `onBeforeCompile` is executed first and (`setBlending`, `setPolygonOffset` and `setFlipSided`) after.



https://github.com/mrdoob/three.js/blob/441fefadc017ebafd2d10089b6d48e1cd28795c2/src/renderers/WebGLRenderer.js#L716-L718

**Comment by Mugen87** [comment]
Okay, now I understand the issue. `onBeforeCompile()` can change material properties like `transparent` which are relevant in context of `WebGLState.setMaterial()`. So if the latter method is executed too early, WebGL state settings could be wrong.

Right now, I can't think of a reason why executing `WebGLState.setMaterial()` after `setProgram()` should raise issues. If this change actually solves the issue, we should give it a try.

**Comment by sunag** [comment]
@njarraud Exist 2 ways to fix this for now.
1. Compiling scene before render using `renderer.compile(scene, camera)`
2. Building material before render using `material.build()`

@Mugen87 I apply the code seems work done, but not fix the problem completely because `WebGLRenderList` sort opaque objects as `painterSortStable` for the culling optimization `GPU Z Test`. I think that this will be more hard to fix "automatically way" now...

**Comment by njarraud** [comment]
@sunag Thank you for looking into it. For some reason, manually rebuilding the material with `material.build()` doesn't work but `renderer.compile(scene, camera)` does. Is it expensive to compile the renderer before rendering or is it only changing the order of things?
Otherwise I just render twice whenever the material requires to be recompiled.

**Comment by sunag** [comment]
`renderer.compile` only build (initialize) all `shaders` in the scene, this is a process is done in `render` too, the mainly difference is that in `renderer.compile` not is rendered in screen only the materials is initialized.

Hmm, I add `material.build()` after set the parameters and apparently work me https://jsfiddle.net/xcvd3071/

You can use `material.build()` or `renderer.compile` not need use the two in same time.

**Comment by njarraud** [comment]
From what I tried, it seems that it works when the material is first initialised like in your example. However, if you change the alpha input later and rebuild manually, the material is not rendered updated at all. Anyway it is not really important as I made it work until a clean solution is found.

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/18363#issuecomment-1046793023
