### ISSUE TITLE
GLTFLoader doesn't retain unknown extensions on primitives

### ISSUE THREAD

**Issue by sleroux** [mrdoob/three.js#18043]
##### Description of the problem

I'm putting together a quick prototype for the FB_material_variant extension issue I filed here https://github.com/mrdoob/three.js/issues/17808 and ran into an issue where unknown `extensions` on `primitive` types are not retained like they are with `node` [[1](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L3053)] or `materials` [[2](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L2329)]. I wasn't sure if this was intended or a bug as the glTF 2.0 spec allows for extensions on primitives but retaining unrecognized extensions is a behaviour of three.js. Is this something that would make sense in adding?

##### Three.js version

- [ ] Dev
- [x] r111
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
It's not directly intended, and a fix would be welcome, but there is one obstacle – if a GLTF.Mesh contains multiple GLTF.Primitive objects, we'll create:

- THREE.Group
  - THREE.Mesh
  - THREE.Mesh
  - ...

If there's only one GLTF.Primitive, there is no THREE.Group, and the loader returns a single `THREE.Mesh` instance. So in that case, any extensions on the GLTF.Mesh and GLTF.Primitive objects would need to be merged or overwritten.

Otherwise, it looks like this line should be using the primitive definition instead of the mesh definition? 

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L2569

**Comment by donmccurdy** [comment]
Proposed fix in https://github.com/mrdoob/three.js/pull/20679.
