### ISSUE TITLE
Suggestion: Documentation for typescript

### ISSUE THREAD

**Issue by TakesTheBiscuit** [mrdoob/three.js#18158]
##### Description of the problem

Three.js doesn't currently have a typescript section to the docs (that i could see, certainly).

Describe the bug or feature request in detail:

We should look to add an MVP doc for typescript to the docs which can list common issues and some more detail about how it works.

At the moment the typescript documentation is spread across the web on SO and in closed issues here in this repo

##### Three.js version
 r111 ^

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by looeee** [comment]
Do you mean that you want to add a manual page like "How to use three.js with Typescript"?

**Comment by Mugen87** [comment]
I agree it would be good to have a guide about Typescript usage with `three.js` which e.g. explains how to create a basic project setup. This seems to be a frequently asked question at the forum.

**Comment by donmccurdy** [comment]
Is there a general “how to use typescript in a new project with some dependencies” tutorial we could point at? Is using threejs with TS different from any other library?

**Comment by Mugen87** [comment]
> Is using threejs with TS different from any other library?

There is still the issue with duplicated imports of `three.js` in the final bundle. A sample project configuration that shows how to avoid this issue and that detects the correct `three.js` typings would be helpful for starters.

**Comment by kmturley** [comment]
Can we also add recommend ways to import multiple modules?

This doesn't work:
`import { DRACOLoader, GLTFLoader } from 'three/examples/jsm/loaders';`

This does work:
```
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
```

**Comment by donmccurdy** [comment]
^TBH, since that's not really TypeScript-specific, I would love to see an ESM import in every examples/ (non-core) API doc page. 😇 Mockup:

<img width="1056" alt="Screen Shot 2019-12-16 at 3 10 47 PM" src="https://user-images.githubusercontent.com/1848368/70950726-422f8000-2016-11ea-9e70-73086425696a.png">

**Comment by TakesTheBiscuit** [comment]
Sorry for abandoning this - this looks hopeful - i had a conflict between TS version and threejs TS version and package.json hell - managed to sort it out after some trial and error (mainly error!)

**Comment by DavidPeicho** [comment]
Regarding the doc, I think we should just states that it's better to setup the `tsconfig.json` file to use the Node resolution algorithm. Otherwise people that aren't completely understanding TypeScript will not understand why they can't import an example (like `import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader';` will fail).
I just tried right now and nothing more than that is really needed.

Also, it could be good to note that using the Node algorithm, the typings are resolved in `node_modules/three/src/**/.dt.s`. So TS imports those typings, but your code technically import `node_modules/three/build/three.module.js`. It feels a bit counter-intuitive like that, but it works.

**Comment by TakesTheBiscuit** [comment]
See i imagine even this thread is going to be helpful - that comment @DavidPeicho  about the import makes so much sense to read.
Docs are like gold dust :)

**Comment by kmturley** [comment]
@DavidPeicho It is strange that TypeScript definition points to the src folder:
`import { abc } from '../../../src/Three';`

But the javascript file points to the build folder:
`import { abc } from "../../../build/three.module.js";`

I believe it cant result in accidentally compiling two THREE.js versions into the same minified file? if you import a source Class and an example Loader?
```
import { Object3D, Scene } from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
```

or maybe it's closure compiler doing something funky on my end
