### ISSUE TITLE
Oculus Quest VR: texImage3D is not a function

### ISSUE THREAD

**Issue by Donitzo** [mrdoob/three.js#18159]
##### Description of the problem

When calling render with 
`renderer.vr.enabled = true;`
on Oculus quest, you get the error:

```
Error message: Uncaught TypeError: texImage3D is not a function
URL: three.js 
Line Number: 22118
```

This appears to be related to multiview which I presume is used for VR now.

This issue is very recent. Yesterday before my Oculus Quest automatically updated itself, I was able to run my VR game fine on it. After the update, I had to switch to using XR instead. I downloaded the latest build of three.js. Now whenever vr.enabled === true I get this error.

##### Three.js version

- [x] Dev

##### OS

- [x] Android

**Comment by mrdoob** [comment]
Do you get that error with these examples too?
https://threejs.org/examples/?q=webxr_vr

**Comment by Donitzo** [comment]
Some of the examples still work, like ballshooter. Others don't, like multiview.

I don't have remote debugging right now so I can't tell what the error message is.

**Comment by mrdoob** [comment]
Do you mind being a bit more specific? Which ones do not work?

**Comment by Donitzo** [comment]
I tried them all. All but the multiview/panorama and video examples work.

**Comment by Mugen87** [comment]
I've also tested all VR examples on a Quest an the following do not work:

- `webxr_vr_multiview`
- `webxr_vr_panorama`
- `webxr_vr_panorama_depth`
- `webxr_vr_video`

**Comment by Mugen87** [comment]
@fernandojsg Do you think this is an implementation problem of the Oculus browser?

**Comment by fernandojsg** [comment]
I haven't checked the latest update on the Oculus Browser when they enabled WebXR, not sure if that's related. Maybe they enabled OVR_multiview2 somehow by default?
I'll try it on the quest and see if I can find something
/cc @Artyom17

**Comment by fernandojsg** [comment]
It seems that both `OCULUS_multiview` and `OVR_multiview2` are enabled by default on Oculus Browser, and by the log that you shared it seems that both are using multisampled fbo, when just the `OCULUS_multiview` should be using multisampled fbo.

**Comment by timothyallan** [comment]
My whole site croaked the other day for all my customers using Ouclus HMDs after Oculus pushed that update. It affects Go's as well. I had to do an emergency patch where I simply did the ol' classic:
`function WebGLMultiview( renderer, gl ) {
  function isAvailable() {
    return false;
.....
`
Until I can sort something a bit more solid out :)

**Comment by fernandojsg** [comment]
I just noticed they are also exposing `OVR_multiview2` in WebGL1 contexts which shouldn't be the case as that extension is defined to be used just with WebGL2 contexts, that's you get the `texImage3D` errors as you are using WebGL1 but it shows `OVR_multiview2` defined so it just jump on the multiview code to create the texture array.
So I believe we should not patch the code and just wait for oculus to fix it on their browser.

**Comment by Artyom17** [comment]
Let me check really quick, I'll report back.

**Comment by Artyom17** [comment]
@Donitzo: can you try to disable multiview in chrome://flags and try again? This should mitigate the issue for now. I am investigating.

**Comment by timothyallan** [comment]
Here's some version numbers from the Go, as well as confirmation that OVR_multiview2 is showing up in WebGL1... check out the very bottom.
![Screen Shot 2019-12-16 at 5 08 27 PM](https://user-images.githubusercontent.com/1995135/70953545-dc97bf80-2026-11ea-8b1b-e9090c30ccc5.png)
![Screen Shot 2019-12-16 at 5 08 05 PM](https://user-images.githubusercontent.com/1995135/70953546-dd305600-2026-11ea-933b-249a74401308.png)

**Comment by Artyom17** [comment]
Ok, I've fixed the original issue with the texImage3D and other non-working samples, and yes, that was a bug (reporting OVR_multiview2 as supported for WebGL 1).

However, the multiview test case still doesn't work because seems like blitFramebuffer is called on a multisampled framebuffer. It seems like a bug in three.js at the moment, but I am still investigating.

**Comment by Artyom17** [comment]
Ok... For the blitFramebuffer issue. This is a bit confusing one. The issue is that the Browser "thinks" that it is composing into a multisampled framebuffer, even, though, the context was clearly setting "antialiasing" attribute to false in webxr_vr_multiview.html. The reason why it is doing that is this line in WebXRManager.js:

`session.updateRenderState( { baseLayer: new XRWebGLLayer( session, gl ) } );`

And here is the default values for initializer object for XRWebGLLayer (from https://www.w3.org/TR/webxr/#xrwebgllayer-interface):

`
dictionary XRWebGLLayerInit {
  boolean antialias = true;
  boolean depth = true;
  boolean stencil = false;
  boolean alpha = true;
  boolean ignoreDepthValues = false;
  double framebufferScaleFactor = 1.0;
};
`

The default value of 'antialias' for the layer is true! And check the step #9 [here](https://www.w3.org/TR/webxr/#xrwebgllayer-interface), it suppose to take the AA attribute from the init object, not from the context ("composition disabled" is set to false in this case).

What should be done here is to change that line in WebXRManager.js to something like this:

`session.updateRenderState( { baseLayer: new XRWebGLLayer( session, gl, { antialias: gl.getContextAttributes().antialias } ) } );
`
See PR https://github.com/mrdoob/three.js/pull/18178

CC /@mrdoob @fernandojsg

**Comment by fernandojsg** [comment]
@Artyom17 nice catch on the layers' attributes! It totally makes sense.
thanks for looking into this so quickly 👍

**Comment by Artyom17** [comment]
@fernandojsg, I've uploaded a 7.1.2 build into BETA channel (you are on that channel, afaics), you may test the "multiview in webgl 1" fix with the Panorama example.

**Comment by fernandojsg** [comment]
> @fernandojsg, I've uploaded a 7.1.2 build into BETA channel (you are on that channel, afaics), you may test the "multiview in webgl 1" fix with the Panorama example.

Yep, I see it on "My previews apps" as "installed" but when I launch the browser it's still on v7.0 Any idea how can I upgrade it?

**Comment by Artyom17** [comment]
@fernandojsg, go to "Store", find "Oculus Browser", click on it, select "View app details", this should open a browser's info page and there should be a button "Update" there.

**Comment by fernandojsg** [comment]
That was I was trying to do, but I just see "Start" no "Update" there :-\ 
![com oculus vrshell-20191217-113453](https://user-images.githubusercontent.com/782511/70988255-c8ed6700-20c1-11ea-96c7-5c90e54860fc.jpg)
![com oculus vrshell-20191217-113519](https://user-images.githubusercontent.com/782511/70988254-c8ed6700-20c1-11ea-9345-2abc06db16f1.jpg)
![com oculus vrshell-20191217-113528](https://user-images.githubusercontent.com/782511/70988252-c854d080-20c1-11ea-82ad-fa1b55992899.jpg)

Sorry for hijacking the thread with this :)

**Comment by fernandojsg** [comment]
Maybe I'm on the alpha channel and this one has been released on the beta channel, or the other way around?

**Comment by Artyom17** [comment]
No, you are on beta. Weird, my Store looks different. Don't really understand why. If you go to "Library", do you see Oculus Browser in "Updates" tab?

I am also sending you the APK to your gmail email.

**Comment by fernandojsg** [comment]
> Weird, my Store looks different

fwiw I'm on v12 (System Version 43426000...)

> If you go to "Library", do you see Oculus Browser in "Updates" tab?

Nop

> I am also sending you the APK to your gmail email.

Thanks! I'll try that

**Comment by fernandojsg** [comment]
I just tested the apk and I can confirm `OVR_multiview2` is not exposed in the WebGL1 context, and multiview is working as expected with non-multisampled antialias (Using this PR: https://github.com/mrdoob/three.js/pull/18178).
I have tried also the rest of the examples and all of them works fine on the v7.1 
Thanks @Artyom17 👍

**Comment by Artyom17** [comment]
7.1 should be released this week, btw.
