### ISSUE TITLE
Plane and line intersection calculation error

### ISSUE THREAD

**Issue by washstar** [mrdoob/three.js#18246]
##### Description of the problem
To determine if a plane and a line intersect, they should, but the calculation returns no.When I switch the starting point and the ending point and do the calculation again, the result is still disjoint
```js
var p1=new THREE.Vector3(5,0,0);
var p2=new THREE.Vector3(0,0,0);
var l=new THREE.Line3(p1,p2);
var p=new THREE.Plane(new THREE.Vector3(1,0,0),2);
var result=p.intersectLine(l,new THREE.Vector3());
```

##### Three.js version

-[x] all
- [ ] Dev
- [ ] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Live example: https://jsfiddle.net/dfyhzr2v/

TBH, I'm not sure what your code should demonstrate. The plane and the line clearly do no intersect.

https://jsfiddle.net/3bvnw910/1/

**Comment by Mugen87** [comment]
Closing until the OP clarifies its post.

**Comment by washstar** [comment]
Thanks, I misunderstood the meaning of constant parameter

**Comment by 6XGate** [comment]
For anyone else who has issues trying to figure out how this works, since I too did not understand the Hessian Normal Form.

The distance moves the plane in the opposite direction of the normal. This means a positive distance will always move the plane in a way that keeps the front of the plane facing the origin. A negative distance will move the plane in a way that keeps back of the plane facing the origin.

Example. If you want a plane that faces up and is two units up from the origin (x:0,y:2,z:0). Then your normal will be UP (x:0,y:1,z:0) and your distance will be -2.
