### ISSUE TITLE
HDR and EXR Environment map examples not working

### ISSUE THREAD

**Issue by kaplarkv** [mrdoob/three.js#18253]
Environment map examples are not loading. 

It seems like HDR example is failing on line 167
generatedCubeRenderTarget = pmremGenerator.fromScene( envScene, 0.04 );

https://threejs.org/examples/?q=env#webgl_materials_envmaps_hdr
https://threejs.org/examples/?q=env#webgl_materials_envmaps_exr

##### Three.js version

- [x] r112

##### Browser

- [x] All of them

##### OS

- [x] Windows

Graphics card: 
It works on GeForce MX150 but when graphics is switched to integrated Intel UHD 620 it stops working.

**Comment by Mugen87** [comment]
> It works on GeForce MX150 but when graphics is switched to integrated Intel UHD 620 it stops working.

Do you see any errors or warnings in the browser console?

**Comment by kaplarkv** [comment]
Previous release examples are working.

Here is screenshot of console output from new one.

![console](https://user-images.githubusercontent.com/10552425/71522171-e4c3ea80-28c3-11ea-9813-2eab7403b1ef.png)

**Comment by Mugen87** [comment]
I've checked this issue today with a Windows 10 gaming laptop. When using the Nvidia GPU (RTX 2070 MaxQ), everything works fine. But even if I switch to hybrid mode, both demos work as expected. The laptop is using a Intel UHD Graphics 630 in this case (CPU is Intel Core i7-9750H).

The posted warnings are related to DirectX and probably not relevant forthe issue. I see them in the EXR example, too. The context lost entry however is problematic. This might indicate a device issue. I suggest you try to update the Intel drivers to the latest version. 

If a driver update does hot help, we not somebody else who can verify this issue since I'm unable to reproduce.

**Comment by mrdoob** [comment]
FYI @elalish

**Comment by kaplarkv** [comment]
It works after driver update. I'm closing this issue. Thank you.

**Comment by Mugen87** [comment]
Phew! 😊
