### ISSUE TITLE
New MeshStandardMaterial in r112 has banding artifacts on some GPUs

### ISSUE THREAD

**Issue by toji** [mrdoob/three.js#18265]
As of r112 the default MeshStandardMaterial (in this case specifically as it's used when loading glTF files, but probably in other scenarios as well) is exhibiting banding artifacts on some GPUs. Specifically, I have see this issue on a Pixelbook and every generation of Pixel phones. The issue does not occur on the Nvidia desktop GPUs I have tried, nor on an Oculus Go or Oculus Quest.

It should also be noted that I've observed the material's new shader incurred a noticable performance hit relative to r111 for my particular application on various mobile devices, including ones that don't exhibit the rendering artifacts.

The artifacts look like this (Rendered with Three.js r112 on a Pixelbook)

![Screenshot 2019-12-29 at 9 15 19 PM](https://user-images.githubusercontent.com/805273/71569200-4e89f300-2a82-11ea-820a-a07c6542ef09.png)

The expected output looks like this (Rendered with Three.js r111 on the same Pixelbook)

![Screenshot 2019-12-29 at 9 24 31 PM](https://user-images.githubusercontent.com/805273/71569215-78431a00-2a82-11ea-84ee-6231bfa7dfb6.png)

Live link, currently using r112: https://xrdinosaurs.com

All of the dinosaurs on that page exhibit the issue, but ones with large areas of flat or smooth colors (like the TRex's belly) tend to stand out more.

The material in the screenshot (pasted in full below) uses the glTF extension "KHR_materials_pbrSpecularGlossiness", and has a diffuse, normal, and specular/glossiness textures.

```json
    {
      "doubleSided": true,
      "emissiveFactor": [
        0,
        0,
        0
      ],
      "extensions": {
        "KHR_materials_pbrSpecularGlossiness": {
          "diffuseFactor": [
            0.46512957319999998,
            0.46512957319999998,
            0.46512957319999998,
            1
          ],
          "diffuseTexture": {
            "index": 4,
            "texCoord": 0
          },
          "glossinessFactor": 0.27610518290000002,
          "specularFactor": [
            0.92244664629999995,
            0.92244664629999995,
            0.92244664629999995
          ],
          "specularGlossinessTexture": {
            "index": 6,
            "texCoord": 0
          }
        }
      },
      "name": "TRex",
      "normalTexture": {
        "index": 5,
        "scale": 1,
        "texCoord": 0
      }
    }
```

**Comment by Mugen87** [comment]
I can confirm the glich on my Pixel (1). However, the artifacts only seems to occur when `KHR_materials_pbrSpecularGlossiness` is used.

#18042 introduced geometric anti-aliasing. However, `GLTFLoader` replaces the code of the `lights_physical_fragment` shader chunk with the following:

https://github.com/mrdoob/three.js/blob/3ba0553208cfc9113152f5f39b4036a448cf3f25/examples/js/loaders/GLTFLoader.js#L683-L688

@toji Can you please modify the `GLTFLoader` copy of your app by replacing the above code with:
```js
var lightPhysicalFragmentChunk = [
	'PhysicalMaterial material;',
	'material.diffuseColor = diffuseColor.rgb;',
	'vec3 dxy = max( abs( dFdx( geometryNormal ) ), abs( dFdy( geometryNormal ) ) );',
	'float geometryRoughness = max( max( dxy.x, dxy.y ), dxy.z );',

	'material.specularRoughness = max( 1.0 - glossinessFactor, 0.0525 );// 0.0525 corresponds to the base mip of a 256 cubemap.',
	'material.specularRoughness += geometryRoughness;',
	'material.specularRoughness = min( material.specularRoughness, 1.0 );',
].join( '\n' );
```

**Comment by elalish** [comment]
@Mugen87 Yes, for sure. I'll see if I can repro on my Pixel 3 as well.

**Comment by elalish** [comment]
@toji I do not repro on my Pixel 3 with Android 10, so at least it's not *all* Pixels...

Driver bug? I'm not sure which line is triggering it though. The presence/absence of geometric anti-aliasing wouldn't make that type of artifact anyway, I'm pretty sure.

**Comment by elalish** [comment]
@toji I also just tried my dedicated crappy tester phone (an Alcatel that's about $30 from Target). I don't get the banding artifacts, though I noticed the sky is black. As for perf: it's not exactly buttery, but it's not bad. Honestly that 3D view responds better than the 2D keyboard UI on this phone. Go figure.

**Comment by elalish** [comment]
Ugh, the black sky actually means the PMREM generation failed entirely, and it's due to this weird bug and workaround we found: https://github.com/GoogleWebComponents/model-viewer/pull/920. I'd meant to get this into r112, but it slipped by me. Likely unrelated to the OP's bug though.

**Comment by plut0nist** [comment]
I reproduced OP's error on my OnePlus 5T in both Chrome and Firefox.

**Comment by toji** [comment]
Thanks! Applied the patch to `GLTFLoader` and observed that the banding artifact was reduced, but not eliminated.

Before patch:

![Screenshot 2019-12-30 at 12 11 36 PM](https://user-images.githubusercontent.com/805273/71599111-58e9d280-2afe-11ea-8f34-395555a9dce0.png)

After patch:

![Screenshot 2019-12-30 at 12 10 35 PM](https://user-images.githubusercontent.com/805273/71599124-643cfe00-2afe-11ea-8b83-6e86b4726581.png)

Basically, it looks like it fixed one of the bands. :) (Screenshots taken on a Pixelbook, but also observed on a Pixel 4 XL. Don't have other test devices on me at the moment.)

Happy to patch in any other changes you want to test, or you could check out https://github.com/toji/xr-dinosaurs if you want to test it locally. (Doesn't require any server component.)

> As for perf: it's not exactly buttery, but it's not bad.

Thank you. 😁 Been working hard of performance. In this case during the update to r112 I noticed the perf regression and asked @mrdoob about it. He suggested it may be the new, more accurate standard shader and suggested swapping some materials out with `MeshLambertMaterial` to verify. Since the environment model didn't have properly configured PBR materials anyway I force it to Lambert and left it there, which gained back any perf regressions and then some (since it takes up a large chunk of the viewport.) Left the dinosaurs with the standard material since they're the "hero" asset.

**Comment by Mugen87** [comment]
Sidenote: `Scene.environment` does currently not work when `GLTFLoader` loads meshes using specular/glossiness materials since the renderer checks `isMeshStandardMaterial`. (`GLTFLoader` creates a `ShaderMaterial` for each specular/glossiness material).

https://github.com/mrdoob/three.js/blob/dd81aad5513d66e35e51f3a3b42555bc8aef5cbc/src/renderers/WebGLRenderer.js#L1633
https://github.com/mrdoob/three.js/blob/dd81aad5513d66e35e51f3a3b42555bc8aef5cbc/src/renderers/WebGLRenderer.js#L1539

**Comment by Mugen87** [comment]
I cannot reproduce the banding artifacts when no environment map used. Everything looks good on a Pixel (1) with a simple lighting setup like an ambient and a point light.

**Comment by Mugen87** [comment]
Um, there seems to be some more issue with physical materials using an environment maps. Check out how the following examples looks on a Pixel 1.

https://threejs.org/examples/webgl_materials_envmaps_exr

![Screenshot_20200106-111923](https://user-images.githubusercontent.com/12612165/71812234-f43af480-3076-11ea-85ba-2ef7d29ec76d.png)

https://threejs.org/examples/webgl_materials_physical_clearcoat

![Screenshot_20200106-111856](https://user-images.githubusercontent.com/12612165/71812244-fd2bc600-3076-11ea-9cae-5f594e509900.png)

https://threejs.org/examples/webgl_materials_envmaps_hdr

![Screenshot_20200106-111809](https://user-images.githubusercontent.com/12612165/71812270-0d43a580-3077-11ea-8be8-4757b3cddd19.png)

I can't reproduce the issue on my iMac.

**Comment by sciecode** [comment]
Something pretty weird is happening on my machine, I'm able to reproduce these artifacts on all examples that utilize the new `PMREMGenerator`. But only when running them locally; when viewing them online ( from threejs.org page ) they all appear correct. 

I've never experienced such issue and I'm completely lost as to what causes it. 

I'm running a Windows 10 with a GeForce GTX 750 TI, so I don't think this is a device-specific issue.

**Comment by Mugen87** [comment]
> But only when running them locally; when viewing them online ( from threejs.org page ) they all appear correct.

Be aware that the `dev` version has changed which are not present in `prod` yet. Can you please checkout the current `master` branch and then perform a local test?

**Comment by sciecode** [comment]
> Can you please checkout the current master branch and then perform a local test?

First thing I've tried after noticing this behavior, same results. Really curious.

**Comment by Mugen87** [comment]
Can you please test with incognito windows? Sometimes stuff might be cached or extensions interfere which can be really confusing

**Comment by sciecode** [comment]
Tried with incognito, same results :(

I believe I know why this banding is occurring tho. 
During mip generation, my local (incorrect) version is creating a black band that doesn't exist on live version.

![local](https://user-images.githubusercontent.com/3927951/71836693-50ac0d00-3093-11ea-8048-a379ac0f3340.png)
![online](https://user-images.githubusercontent.com/3927951/71836697-51dd3a00-3093-11ea-899e-5a07f01c2fbc.png)

This is replicated to lower mip levels as well.

This is likely happening due to some incorrect coordinate sampling, I've experimented with manually disabling anisotropic filtering, but the problem remains. It's hard to pin-point exactly what is happening, especially because I can't wrap my head around why it presents two different behaviors on the same machine.

**Comment by sciecode** [comment]
@elalish after running some tests on multiple examples, I was able to pinpoint the actual cause of these artifacts. Contrary to what I said on my previous post, the root cause of the problem is not related with incorrect coordinates sampling, but with the way `PMREMGenerator` is handling `devicePixelRatio`. 

On devices with nominal floating point `pixelRatio` we are getting "bad" mipmap coordinates on the generated texture. So there are small gaps and overlapping regions. I also discovered that my machine has different `devicePixelRatios` depending if I'm viewing and example locally (0.899..) or online (1) and that's why I was only experiencing these artifacts locally.

I've setup a simple test by disabling `setPixelRatio` and it seems to solve the problem, if that's the case for others, Then it would be best to refactor the way `PMREMGenerator` is handling it.

@toji @plut0nist mind checking the following examples on the devices that presented these artifacts?

[DEV Example](https://threejs.org/examples/?q=hdr#webgl_materials_envmaps_hdr)
[TEST Example](https://rawcdn.githack.com/sciecode/three.js/7a6d66a6b90719f1316e3321b8a0f1159c9966b4/examples/webgl_materials_envmaps_hdr.html)

**Comment by elalish** [comment]
@sciecode Thank you so much for figuring out the root cause! I'll see if I can work up a solution.

**Comment by toji** [comment]
@sciecode: Verified on my devices. The DEV Example test exhibits a very obvious black line in the environment map while the TEST Example does not. Awesome debugging, thanks!

I'm was extremely curious why `PMREMGenerator` needed to account for `devicePixelRatio` at all, so I went digging. It turns out it's because `renderer.setViewport()` automatically factors the DPR into any values you send it, which feels like it's clearly the wrong behavior for render targets other than the default framebuffer, which are allocated with exact pixel values that don't account for the pixel ratio at all. I'd suggest the "right" behavior here is that internally `rendere.setViewport()` should be using `getTargetPixelRatio()`, which returns `1` when the active render target is anything other than the default. I can definitely see how that could introduce backwards compat issues, though.
