### ISSUE TITLE
shadowMap 'cannot read property matrixWorld of undefined' since version 0.108.0

### ISSUE THREAD

**Issue by Nodeocrat** [mrdoob/three.js#18304]
##### Description of the problem
I have just updated my three.js version on an old project. I have isolated the issue to shadowMap, specifically on versions 0.108 and up, where I get the following error:

<img width="683" alt="Screenshot 2020-01-04 at 18 32 11" src="https://user-images.githubusercontent.com/10661106/71770156-71545580-2f21-11ea-91fe-7160b351eb9d.png">

My repository is here: https://github.com/Nodeocrat/threejs-test/tree/threejs-issue-18304

Observe the error. But when you change the version to 0.107.0 or lower, it works fine. All my Three.js content is in src/Game/index.js.

The offending bit of code seems to be on lines 53-55:

```
 //shadows
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
```

When I remove this, the error is no longer present, but of course, there's no shadows. I notice from the r108 release notes, there were changes to shadowMaps, so I assume it's related to that.

##### Three.js version
0.108.0 and higher

##### Browser

- [ ] All of them
- [X] Chrome
- [X] Firefox
- [X] Safari
- [unable to test] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
It's because of this line:
```js
light.shadow = new THREE.LightShadow( new THREE.PerspectiveCamera( 90, 1, 1, 1000 ) );
```
It's not intended to do that since `LightShadow.updateMatrices()` is not compatible with `PointLight`. This type of light has its own `PointLightShadow` implementation. However, this class is not in the `THREE` namespace.

There is no reasons to create a new `shadow` object anyway. Just delete the line and configure the existing object.

Please use the [forum](https://discourse.threejs.org/) if you need more help.
