### ISSUE TITLE
Editor can not display displacementmap model, ask displacementmap example gltf do?

### ISSUE THREAD

**Issue by WREQI** [mrdoob/three.js#18333]
Editor can not display displacementmap model, ask displacementmap example gltf do?
![image](https://user-images.githubusercontent.com/35467304/71953536-7ebd5880-321d-11ea-8def-e329bdb0cc70.png)
![image](https://user-images.githubusercontent.com/35467304/71953559-97c60980-321d-11ea-9840-976598cc7360.png)

**Comment by Mugen87** [comment]
I'm not sure why you are mentioned `glTF` here since this is a `OBJ` asset. If you just load it, there are no maps applied yet. Doing so will lead to a better result:

![image](https://user-images.githubusercontent.com/12612165/71971258-87f0fa00-320a-11ea-8c8c-bfed16d77c5f.png)

BTW: You have to scale down the model a bit. Otherwise it is out of view. Try it with a scale value of `0.050`.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
