### ISSUE TITLE
Material version increases with every frame when rendering to a renderTarget

### ISSUE THREAD

**Issue by brianpeiris** [mrdoob/three.js#18355]
##### Description of the problem

Rendering a scene to a WebGLRenderTarget causes all material versions to increment with every frame. This doesn't really cause a performance issue, but I thought it was worth reporting. Possibly related to https://github.com/mrdoob/three.js/issues/18354. 

Simplified reproduction, see the material version in the top right of the output: https://jsfiddle.net/brianpeiris/t9oskmg7/ 

##### Three.js version

- [x] Dev
- [x] r112

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
That happens because the app renders to the render target with a different camera. This leads to two internally render states  and thus two different instances of `WebGLLights` with two different versions. (Reminder: Light uniforms depends on the view matrix. Hence, the camera is an import part of the current render state). Hence, the following block always evaluates to true when rendering:

https://github.com/mrdoob/three.js/blob/a8e93ecf28e593a478ae1da4d4710813e8075564/src/renderers/WebGLRenderer.js#L1671-L1673

The renderer knowns that a shader compilateion is not necessary however an update of the light uniforms. Instead of calling `material.needsUpdate = true;`, we could `initMaterial()` directly in the above if block. Otherwise we need a bit of refactoring in order to sort this issue out.
