### ISSUE TITLE
Angular 8 + Three.js build error. Typescript version 3.5.3

### ISSUE THREAD

**Issue by omararturo** [mrdoob/three.js#18377]
ERROR in node_modules/three/src/core/BufferAttribute.d.ts:21:6 - error TS1086: An accessor cannot be declared in an ambient context.

21  set needsUpdate( value: boolean );
        ~~~~~~~~~~~
node_modules/three/src/core/InterleavedBufferAttribute.d.ts:20:6 - error TS1086: An accessor cannot be declared in an ambient context.

20  get count(): number;
        ~~~~~
node_modules/three/src/core/InterleavedBufferAttribute.d.ts:21:6 - error TS1086: An accessor cannot be declared in an ambient context.

21  get array(): ArrayLike<number>;

**Comment by Mugen87** [comment]
> Typescript version 3.5.3

You have to use a higher version of TypeScript, see  https://stackoverflow.com/questions/58802463/types-sequelize-error-ts1086-an-accessor-cannot-be-declared-in-ambient-context

Upgrading to 3.7.*  should solve this issue.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.

**Comment by romanzenka** [comment]
Is it a good idea to force anyone using three.js to upgrade to newest typescript? 
Was it essential for three to use typescript 3.7 instead of 3.6? 
Does it provide genuine, substantial value to three?

As soon as you touch typescript 3.7, the incompatibility they introduced starts infecting all the projects that touch your code. I think that was a big oversight from the typescript community, and the most prudent way of dealing with that would be (IMHO) to steer clear of newest typescript until they figure out a backwards compatible way of extending it.
