### ISSUE TITLE
Object3D.getWorld*() with cameras do not work when WebXR is presenting.

### ISSUE THREAD

**Issue by omgitsraven** [mrdoob/three.js#18448]
##### Description of the problem

If an object has an onBeforeRender function which calls getWorldPosition on the `camera` argument, and the user is in VR, then that object (and any rendered after it) will stick to the user's face, as though the VR camera jumped to the origin mid-render.

Example: https://ravenworks.ca/temp/threeOBRcamerabug/

##### Three.js version

 r112 (and some earlier, though I'm not sure exactly where it broke; this used to work in 2017, but it doesn't now.)

##### Browser

my demo only runs in Chrome because of Three dropping WebVR support, but the same bug happens in Firefox if using A-Frame (that's how I discovered the bug)

##### OS

only tried on Windows 10

##### Hardware Requirements (graphics card, VR Device, ...)

Oculus Rift

**Comment by Mugen87** [comment]
There is an unfortunate dependency when using `Object3D.getWorldPosition()` in this context. This method enforces a recomputation of the local and world matrices which will produce a wrong result since these matrices are actually set by `WebXRManager`.  Since `position`, `rotation` and `scale` are not correctly set (they are in fact out-of-sync), a recomputation produces wrong results (um, I'm having a déjà vu here).

You can avoid this problem by doing this in your `onBeforeRender()` callback:
```js
cameraWorldPosition.setFromMatrixPosition( camera.worldMatrix );
```
or by setting `matrixAutoUpdate` to `false` in your app. However, if you do this, you have to manually call `Object3D.updateMatrix()` by yourself whenever you transform the camera via `position`, `rotation` and `scale`.

Besides, do not create an instance of `Vector3` per method call. Declare `cameraWorldPosition` once and reuse it.

**Comment by omgitsraven** [comment]
Ahh, thank you for the workaround!

(And yeah, I just put that Vector3 there so the demo would be as brief as possible…)
