### ISSUE TITLE
DirectionalLight low-res shadows rendering issue on moving objects

### ISSUE THREAD

**Issue by Priler** [mrdoob/three.js#18521]
##### Description of the problem

Hi.
I'm having this issue with DirectionalLight shadows.
Moving models cast shadows that twitches/flickers.
This happens only if shadows are low-res (i.e. 128/128 or even 1024/1024).

Bigger shadow mapSize (such as 2048/2048) renders good enough (flickering is not visible).

Video of issue: https://youtu.be/GIdIc__i8eE

##### Three.js version

- [ ] Dev
- [x] r113

##### Browser

- [x] All of them
- [ ] Chrome 79.0.3945.130
- [ ] Firefox

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Can you please share the configuration of your directional lights shadow camera?

**Comment by Priler** [comment]
> Can you please share the configuration of your directional light's shadow camera?

Here:
```
let ALight = new THREE.AmbientLight(0x404040, 2.4);
scene.add( ALight );

let DLight = new THREE.DirectionalLight( 0xffffff, .5 );
let DLightTargetObject = new THREE.Object3D();
DLight.position.set(50,30,2);
DLight.target = DLightTargetObject;
DLightTargetObject.position.set(-25,-10,0);

DLight.castShadow = true;
DLight.shadow.radius = 0;

/*
 @TODO
 Shadows lower than 2K triggers twitches/flickers on moving objects.
 Better fix this later;
 */
DLight.shadow.mapSize.width = 1024 * 2;
DLight.shadow.mapSize.height = 1024 * 2;

DLight.shadow.camera.scale.x = 4;
DLight.shadow.camera.near = 0;
DLight.shadow.camera.far = 100;

scene.add(DLight);
scene.add(DLightTargetObject);

if(config.camera.helper) {
	scene.add(new THREE.CameraHelper(DLight.shadow.camera));
}

**Comment by Mugen87** [comment]
Do you mind demonstrating the issue with a live example: https://jsfiddle.net/hyok6tvj/

BTW: What is the purpose of this line?

```js
DLight.shadow.camera.scale.x = 4;
```

**Comment by Priler** [comment]
> Do you mind demonstrating the issue with a live example? https://jsfiddle.net/hyok6tvj/
> 
> BTW: What is the purpose of this line?
> 
> ```js
> DLight.shadow.camera.scale.x = 4;
> ```

Live example: https://jsfiddle.net/948tjhL6/

`DLight.shadow.camera.scale.x = 4;`
I've used this property to scale camera frustum.

**Comment by Mugen87** [comment]
Thanks for sharing this live example! It actually illustrates what happens if the resolution of your shadow map is too low^^. 128x128 is just not appropriate compared to the size of the shadow camera's frustum. From my point of view, the result gets much better by using the default resolution 512x512:

https://jsfiddle.net/6cumr8fb/

So what you seeing is essentially a conceptual limitation of shadow maps. Increasing the shadow map resolution is one way to mitigate this issue, tighten the shadow camera's frustum another one. You could also consider to bake the lighting into a light map although this mostly works best with static scenes (see https://threejs.org/examples/webgl_materials_lightmap).

Another approach from game development which works well for characters is the usage of so called shadow projectors which produces a blob shadow on the character's respective position (see https://docs.unity3d.com/Manual/class-Projector.html). However, `three.js` does not offer something like that out-of-the-box so far so this is something you have to develop by your own.

> I've used this property to scale shadow camera frustum.

Consider to use the `top`, `left`, `right`, and `left` properties of the shadow camera.

**Comment by Priler** [comment]
> Thanks for sharing this live example! It actually illustrates what happens if the resolution of your shadow map is too low^^. 128x128 is just not appropriate compared to the size of the shadow camera's frustum. From my point of view, the result gets much better by using the default resolution 512x512:
> 
> https://jsfiddle.net/6cumr8fb/
> 
> So what you seeing is essentially a conceptual limitation of shadow maps. Increasing the shadow map resolution is one way to mitigate this issue, tighten the shadow camera's frustum another one. You could also consider to bake the lighting into a light map although this mostly works best with static scenes (see https://threejs.org/examples/webgl_materials_lightmap).
> 
> Another approach from game development which works well for characters is the usage of so called shadow projectors which produces a blob shadow on the character's respective position (see https://docs.unity3d.com/Manual/class-Projector.html). However, `three.js` does not offer something like that out-of-the-box so far so this is something you have to develop by your own.
> 
> > I've used this property to scale shadow camera frustum.
> 
> Consider to use the `top`, `left`, `right`, and `left` properties of the shadow camera.

For me 2048x2048 shadow map size works good, cuz I'm using .vox models created in Magica Voxel.
Anything lower renders too bad if the object is moving, see BoxGeometry example https://jsfiddle.net/ysonhftb/
I was just curious if it's a bug or a glitch, so I've reported an issue.

**Comment by Mugen87** [comment]
No problem. Consider to use the [forum](https://discourse.threejs.org/) if you need more help or guidance.

**Comment by Priler** [comment]
Dunno why issue is closed.
It's not about help, I've managed to find somewhat I can call a solution (bigger shadow map size) by myself earlier on (even before I've posted this issue).
But shadow flickers/twitches even if you set big shadow map size (just it's not visible as good as with small map size).

I did not asked for help, I've reported this issue as a bug.

**Comment by Mugen87** [comment]
Like mentioned before, it's not a bug but limitation of the approach.

**Comment by Priler** [comment]
I think it's a render issue.
Cuz in Unity for example (as you mentioned it before), there is no such problem with low-res shadows.

**Comment by Mugen87** [comment]
Can you please demonstrate this with an export Unity app? It also need some study to verify how Unity implements their shadows. Otherwise we compare apples with pears.

**Comment by Priler** [comment]
I believe it's about shadow projection, in Unity there are two options available: close fit & stable fit.
Is there something like that in THREE.js?
Could be good improvement.

**Comment by Mugen87** [comment]
AFAICS, Unity uses CSM. You might wanna try #18481 although is not yet merged.

**Comment by vtHawk** [comment]
@Priler What makes you believe that shadow mapping doesn't work as intended? It is a fairly simple and easy-to-implement technique, and the implementation in three.js seems to give expected results. 

Of course, you can introduce more advanced technique if you know how to implement it. Unity's documentation mentions briefly close fit and stable fit, but lacks any detailed explanation.

However, I think your issue can be partially fixed by moving DirectionalLight in small fixed steps, calculated using frustum size, shadow resolution and other optional parameters. Of course, this approach wouldn't work with constantly moving meshes (like the sphere in your example).

**Comment by Priler** [comment]
> @Priler What makes you believe that shadow mapping doesn't work as intended? It is a fairly simple and easy-to-implement technique, and the implementation in three.js seems to give expected results.
> 
> Of course, you can introduce more advanced technique if you know how to implement it. Unity's documentation mentions briefly close fit and stable fit, but lacks any detailed explanation.
> 
> However, I think your issue can be partially fixed by moving DirectionalLight in small fixed steps, calculated using frustum size, shadow resolution and other optional parameters. Of course, this approach wouldn't work with constantly moving meshes (like the sphere in your example).

As I learned during this discussion with @Mugen87, they are working as intended.
But utilizes stable fit algorithm by default, and there's no choice for close fit yet.

p.s. Although I did not yet tested what @Mugen87 provided about CSM.

**Comment by Mugen87** [comment]
@Priler Feel free to make a comment at #13908. We use this thread to track feature request on improving shadows in `three.js`.
