### ISSUE TITLE
Breaking Change in R104 not in migration guide

### ISSUE THREAD

**Issue by ThreeDfish** [mrdoob/three.js#18541]
When the change in R104 to applyMatrix was made to change it to update the matrix by default, it broke my app.

This needs to be noted in the migration guide.  I had to do a file compare between R103 and R104 and put in breakpoints to figure out why my code broke when migrating to R104 from R103

This was a fundamental change to the behavior of Three JS and is a BREAKING change and it should be in the migration guide.

**Comment by Mugen87** [comment]
Are you referring on this PR: #16250?

Can you please explain in more detail how this change broke your app? In any event, how about this sentence?

> Object3D.applyMatrix() now updates the local matrix if `matrixAutoUpdate` is set to `true`.

**Comment by ThreeDfish** [comment]
Actually it should say:

Object3D.applyMatrix() now updates the local matrix unless matrixAutoUpdate is set to false, matrixAutoUpdate defaults to true.  This is a change from the previous behavior where Object3D.applyMatrix() did not update the local matrix.  To keep the old behavior, set Object3D.matrixAutoUpdate to false before calling Object3D.applyMatrix().

This is a breaking change and can cause code that worked in R103 to no longer work with R104 until the code is modified.

-----------

I don't know the exact reason why, but the result with it auto-updating is completely different from when it is not auto-updating, which resulted in objects not getting placed into the scene properly, or even not getting placed at all, and causing other errors.  Which all went away when I turned off auto-updating before I used applyMatrix.   So the end result makes R104 to NOT be backward compatible with R103.

**Comment by Mugen87** [comment]
We are normally not putting migration notes into the documentation. The existing documentation about [Object3D.matrixAutoUpdate](https://threejs.org/docs/index.html#api/en/core/Object3D.matrixAutoUpdate) makes clear that the default is `true`. So no need to repeat this elsewhere.

> This is a change from the previous behavior where Object3D.applyMatrix() did not update the local matrix.

This sentence is actually redundant since the first one already says that there is a change.

> To keep the old behavior, set Object3D.matrixAutoUpdate to false before calling Object3D.applyMatrix().

I'm afraid this is not a good advice since setting `Object3D.matrixAutoUpdate` to `false` will not only affect `Object3D.applyMatrix()` but a lot of other places in the code. Note that the old behavior was changed since users modified `Object3D.position`, `Object3D.rotation` and `Object3D.scale` and then used `Object3D.applyMatrix()` but without updating `Object3D.applyMatrix()` beforehand. This produced obviously a wrong result since computation were done with an outdated local matrix.

**Comment by Mugen87** [comment]
Migration guide is now updated: https://github.com/mrdoob/three.js/wiki/Migration-Guide#r103--r104

**Comment by ThreeDfish** [comment]
Well, that is better than nothing...  although isn't the document called "Migration Guide"?  I would think that would be the place for migration notes -- that is the first place I looked to find out why upgrading from R103 to R104 broke the app.

@Mugen87 On a somewhat related subject, do you ever do code review on existing ThreeJS based projects?

**Comment by Mugen87** [comment]
Sorry, that we've missed to note this change in the first place!

> On a somewhat related subject, do you ever do code review on existing ThreeJS based projects?

Yes, I do. Just write me a PM (email see github profile) if you are interested.
