### ISSUE TITLE
After the gamma changes in r112, how to make colors look the same as before?

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#18588]
##### Description of the problem

<img width="700" alt="Screenshot 2020-02-10 at 08 52 26" src="https://user-images.githubusercontent.com/2223602/74130648-d36c3e80-4be2-11ea-81c0-cbb44b172b15.png">

I get why the change was made and most things look better, i'm just trying to update some old projects and for some i can't figure out how to get the contrast back.

r109: https://codesandbox.io/s/r3f-particles-ii-pjcc1

Colors are rich and deep.

r113: https://codesandbox.io/s/r3f-particles-ii-rnp2c

Washed out and bland.

The original didn't specify any settings for gamma and tonemapping. In the second sandbox (r113), where the canvas is created down below, there's a onCreated callback where all the encondings can be set. I have tried mostly everything but couldn't make it work.

```jsx
      onCreated={({ gl }) => {
        gl.gammaFactor = 2
        gl.toneMappingExposure = 1
        gl.toneMappingWhitePoint = 1
        gl.toneMapping = THREE.LinearToneMapping
        gl.outputEncoding = THREE.LinearEncoding
      }}>
```

**Comment by Mugen87** [comment]
I'm afraid this issue has nothing to do with color spaces. Your original code did not set `gammaOutput` to `true` so your app uses linear color space. This is still true in your R113 code.

The root cause for the deviation is the fact that the default values for metalness/roughness have changed in R112 (see https://github.com/mrdoob/three.js/wiki/Migration-Guide#r111--r112). By using the previous values, the result looks good again.

https://codesandbox.io/s/r3f-particles-ii-6qkfe

**Comment by drcmda** [comment]
I must've overslept that guide, sorry for wasting your time, and thanks so much! 🎉
