### ISSUE TITLE
Mipmaps are not generated if minFilter is set to NearestFilter or LinearFilter

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#18861]
At the moment even when `Texture.generateMipmaps` is set to true mipmaps are not generated if [minFilter is set to NearestFilter or LinearFilter](https://github.com/mrdoob/three.js/blob/6f86fda4d312996e3f4281ceccc02f0419e55c0d/src/renderers/webgl/WebGLTextures.js#L118-L123). However when using the [shader_texture_lod](https://developer.mozilla.org/en-US/docs/Web/API/EXT_shader_texture_lod) extension to enable the `texture2DLodEXT` function in shaders (available by default in WebGL2) it doesn't work as expected because mipmaps aren't available even if you've explicitly set `generateMipmaps = true`.

**Comment by Mugen87** [comment]
I have thought about this issue a couple of times. We could remove the linear and nearest filter check from `textureNeedsGenerateMipmaps()` or alternatively provide a new method in `WebGLRenderer` for manual mipmap generation. If we do nothing, we should be aware that it's a bit clumpy to implement a workaround on app level (`WebGLTextures` is not exposed so the users has to work with `WebGLState` and the raw WebGL context).

The good think is that `Texture.generateMipmaps` has proper default values in all texture classes. Meaning for all data textures and textures of render targets, `Texture.generateMipmaps` is `false`. Only for normal textures, cube textures and canvas textures `Texture.generateMipmaps` is set to `true`.

So if we remove the check, there might be uses cases where mipmaps are generate without using them. That happens when the user e.g. just loads a texture via `TextureLoader` and then set `minFilter` to `LinearFilter` or `NearestFilter` but does not set `generateMipmaps` to `false`.

It's hard to tell how often this scenario appears in the wild. The thing is that the current implementation of `textureNeedsGenerateMipmaps()` is indeed a bit confusing since the engine tries to be smart at this point and performs an optimization. However, this breaks other use cases like the one of @gkjohnson.

If I had to make a decision I would probably remove the check and implement the function like so and make a note in the migration guide:
```js
function textureNeedsGenerateMipmaps( texture, supportsMips ) {

    return texture.generateMipmaps === true && supportsMips === true;

}
```
Looking at the examples, it seems only a few demos rely on the current behavior. So it would be necessary to add `generateMipmaps` to `false` at a few places.

**Comment by gkjohnson** [comment]
> If I had to make a decision I would probably remove the check and implement the function like so and make a note in the migration guide

I agree with this change. I think it was a good check and smart optimization before but with the texture LoD shader function now being available it's confusing that mipmaps are not generated when `generateMipmaps = true`. And you're right it can't really be worked around.

> Looking at the examples, it seems only a few demos rely on the current behavior. So it would be necessary to add generateMipmaps to false at a few places.

How are the demos relying on this behavior? As far as I understand it removing the above check would result in extra texture memory being generated in some cases but it shouldn't have any impact on the result, right? I agree it's good to update examples to demonstrate best practice, though.

One other thing we might want to change are some of the loaders and how they load textures. In GLTFLoader, for example, if a texture is defined to use `LinearFilter` or `NearestFilter` it should set `generateMipmaps` to false by default.

**Comment by Mugen87** [comment]
> As far as I understand it removing the above check would result in extra texture memory being generated in some cases but it shouldn't have any impact on the result, right?

That's what i meant 😇 . E.g. [webgl_materials_texture_filters](https://threejs.org/examples/webgl_materials_texture_filters) would require an update.

> One other thing we might want to change are some of the loaders and how they load textures. In GLTFLoader, for example, if a texture is defined to use LinearFilter or NearestFilter it should set generateMipmaps to false by default.

Good point!

**Comment by Mugen87** [comment]
@mrdoob If you think it's worth doing this change, I'll update `WebGLRenderer`/`WebGPURenderer` (the same logic is used in context of WebGPU, too) and change the example code.
