### ISSUE TITLE
Horrible render performance when using Water + MeshStandardMaterial + sRGBEncoding

### ISSUE THREAD

**Issue by n2k3s2it** [mrdoob/three.js#18893]
##### Description of the problem

I'm experiencing horrible render performance when using the combination of the Water.js shader, a plane with a MeshStandardMaterial and the renderer.output using sRGBEncoding.

Recreated [water example](https://threejs.org/examples/#webgl_water) in jsfiddle and added `renderer.outputEncoding = THREE.sRGBEncoding` (line 119) in the fiddle: https://jsfiddle.net/4esfwtkh/

The performance does not dip:
- By not setting render.output to sRGBEncoding and using MeshStandardMaterial it will run ok (comment line 117)
- By setting render.output to sRGBEncoding but using MeshBasicMaterial it will run ok (comment line 55 and uncomment line 56)
- When the water is not visible in the camera frustum (i.e. by looking from below)

##### Three.js version

- [x] Dev
- [x] r114
- [x] r113

**Comment by Mugen87** [comment]
#18894 should fix the issue. Similar to `Reflector` and `Refractor`, you have to specify the encoding when creating the object like so:
```js
water = new Water( waterGeometry, {
	color: params.color,
	scale: params.scale,
	flowDirection: new THREE.Vector2( params.flowX, params.flowY ),
	textureWidth: 1024,
	textureHeight: 1024,
        encoding: THREE.sRGBEncoding
} );
```

**Comment by Mugen87** [comment]
Consider the PR as a workaround. There will be maybe a solution that automatically sets the right encoding under the hood.

**Comment by n2k3s2it** [comment]
> 
> 
> Consider the PR as a workaround. There will be maybe a solution that automatically sets the right encoding under the hood.

Alright make sense, thanks for the quick answer and work around!

**Comment by WestLangley** [comment]
>you have to specify the encoding when creating the object like so:

To be clear, you have to specify a _specific_ encoding -- not any encoding -- for the work around to work.

**Comment by WestLangley** [comment]
Setting the encoding -- in this case to `sRGB` -- is a work around that prevents the renderer from recompiling the material every frame.

In fact, the material must be decoded back to linear when it is used as a texture.

Hopefully there will be a proper solution that prevents the renderer from recompiling the material every frame.

**Comment by Mugen87** [comment]
> In fact, the material must be decoded back to linear when it is used as a texture.

I'm not sure this is correct. Let's take `Reflector` as an example: When the reflector renders the scene from its view, it should do this with the same color space than the actual render pass since the internal render target is just projected onto the reflective surface (e.g. a plane). The current default shader of the reflector does no color space conversion at all. It just ensures to correctly map the render target via projective texture mapping.

I think there are two solutions: When using `Reflector`, `Refractor` or `Water2`, it is required to render in linear space and perform color conversion to `sRGB` via post processing (if required). Otherwise the internal render targets hold color values with in the same space like defined by `WebGLRenderer.outputEncoding`.

I think we can actually set the encoding in the respective `onBeforeRender()` methods 🤔
