### ISSUE TITLE
Decreasing Three.js repo size

### ISSUE THREAD

**Issue by munrocket** [mrdoob/three.js#18929]
##### Description of the problem

1) Since we have screenshots they polluting github repo. Every new commit that changes screenshot increasing overall repo size. Probably exists a way how to decrease it in future with `.gitattributes && git lfs`. Any suggestions?

2) Somebody complain that `puppeteer` is too big. But who installs full three.js from git? Only three.js contributes? This is a problem?

**Comment by makc** [comment]
@munrocket we had this talk 5 years ago #6922 they said no.

**Comment by munrocket** [comment]
I am agree but in current situation with screenshots in repo it can increase much faster, so probably somebody know some solution.

**Comment by Mugen87** [comment]
> Every new commit that changes screenshot increasing overall repo size.

Looking at the last couple of weeks, it does not seem this this happens quite often.

In any event, I don't think the repo size is an issue. It's mostly relevant to devs and you normally clone the repo only once per device.

**Comment by finnbear** [comment]
Consider downloading the npm package (https://www.npmjs.com/package/three) which has everything you need for production purposes at only 21MB.

**Comment by looeee** [comment]
It's fair to note that the repo size can be an issue for people with slow speed or small data caps. 

However, I think the conclusion in #6922 is still OK. There's an extra 70mb added due to these screenshots which I don't think is a big deal since it's a one time download. 

Note the [comment from @bhouston](https://github.com/mrdoob/three.js/issues/6922#issuecomment-126539013) suggesting you do shallow clone if repo size is an issue.

**Comment by munrocket** [comment]
Looks like this is cool git feature:
```
git clone --depth 1 <url>
```
I will close this issue, if you have any complains please just open a new one.
