### ISSUE TITLE
Incorrect texture with VideoTexture and InstancedMesh

### ISSUE THREAD

**Issue by novogrammer** [mrdoob/three.js#18999]
This issue will occur only in Chrome on Mac.
Chrome on Windows works fine.

macOS 10.14.6
Chrome 80.0.3987.149
Chrome Canary 83.0.4099.2

##### Description of the problem

https://codepen.io/novogrammer/pen/VwLqywr?editors=0010
https://www.youtube.com/watch?v=dKl4kenkIYY

##### Three.js version

- [x] Dev
- [x] r115
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by FMS-Cat** [comment]
I have confirmed the issue on my Windows (Razer Blade 15, GTX1060 Max-Q) and Mac (MBP13 Mid 2014, Iris Graphics)

**Comment by Mugen87** [comment]
I can reproduce the issue with Chrome 80.0.3987.149 and Chrome Canary 83.0.4100.0 on maxOS. However, it works with latest Firefox and Safari.

I did not find open issue at https://bugs.chromium.org/p/chromium/issues/list so it probably makes sense to report it there.

@novogrammer Do you mind filing a bug at the Chromium bug tracker?

**Comment by novogrammer** [comment]
thank you, @Mugen87. 
I reported this issue. 
https://bugs.chromium.org/p/chromium/issues/detail?id=1066413

**Comment by Mugen87** [comment]
If you can still edit the issue, please ensure it's added to the component `Blink>WebGL `. This will make it easier for the Chromium team to analyze the issue.

Besides, I suggest you change the title since it also happens on Windows (see this comment https://github.com/mrdoob/three.js/issues/18999#issuecomment-606384339).

**Comment by kenrussell** [comment]
Could the Chrome team get a little more help from the Three.js team reducing this test case? The problem seems to be specifically the use of InstancedMesh per http://crbug.com/1066413 . I don't know whether there's an emulation path for InstancedMesh that might be being taken in Safari and maybe even Firefox. Any help from the Three.js experts in identifying the problematic code paths and WebGL API calls in Three would be greatly appreciated.

**Comment by Mugen87** [comment]
>  I don't know whether there's an emulation path for InstancedMesh that might be being taken in Safari and maybe even Firefox.

The underlying code path of `InstancedMesh` is equal for all browsers. It seems the problem is the usage of a video texture in combination with instanced rendering. 

Maybe it would be a good idea to enhance the following unit test for instanced rendering with two additional testes using textures (a normal and a video texture).

https://www.khronos.org/registry/webgl/sdk/tests/conformance/extensions/angle-instanced-arrays.html?webglVersion=1&quiet=0&quick=1

**Comment by Mugen87** [comment]
BTW: An instance of `VideoTexture` is just normal texture that indicates a texture upload like so:
```js
if ( video.readyState >= video.HAVE_CURRENT_DATA ) {

     this.needsUpdate = true;

}
```
This check is performed per simulation step. `video` is the internal video element and the `needsUpdate` notifies the renderer to perform the texture upload. Apart from that, there are no differences to ordinary textures.

**Comment by mrdoob** [comment]
Seems like this doesn't reproduce on MacOS 11.2.3 + Apple M1.

**Comment by novogrammer** [comment]
It seems to be fixed.
thanks.

**Comment by kenrussell** [comment]
Note that upon re-triaging http://crbug.com/1066413 it's no longer reproducible on the same hardware (a 2017 dual-GPU MacBook Pro still running 10.15.7). Chrome's Media team did many refactors of the video-to-texture upload paths over the past year and it looks like one of them fixed this.

**Comment by mrdoob** [comment]
Can't reproduce on MacOS 10.15.7 + Intel Iris Graphics 550 either 🎉
