### ISSUE TITLE
PixelPerfect Sprite (feature request)

### ISSUE THREAD

**Issue by Josema** [mrdoob/three.js#19003]
I love three.js but it amaze me that we are not able to render images in a scene without changing it's properties.

![image](https://user-images.githubusercontent.com/1819888/78000587-ccd18c00-7334-11ea-9078-9bf3950a1e18.png)

On the left side the best result I could get with this config:
```
SpriteMaterial.sizeAttenuation = false
texture.minFilter = THREE.NearestFilter
sprite.scale = 0.008
```

On the right side the actual PNG pasted in Photoshop. I can achieve the result I want by overlapping a div and using CSS/HTML but I see this as a dirty solution.

**Comment by Mugen87** [comment]
Can you please demonstrate the issue with a live example? https://jsfiddle.net/hyok6tvj/

**Comment by Josema** [comment]
Let me know if this is a valid example https://jsfiddle.net/9v7xefuh/2/

**Comment by Josema** [comment]
I have the same size in both images because I ajjusted the scale to my screen. Maybe you should adjust the sprite scale according to your screen. https://jsfiddle.net/hunmr8e4/

Ideally we should not have to change the scale of the sprite when sizeAttenuation is false. Don't know why is this behavior.

**Comment by Mugen87** [comment]
You can only achieve the intended result if you render the sprite like HUD elements (similar to the red sprites in this [example](https://threejs.org/examples/?q=sprite#webgl_sprites)).

https://jsfiddle.net/swkvgyoL/

To do so, you have to render the sprites with a separate scene and orthographic camera. It's then not necessary to manually define a scale value since it can be computed from the image dimensions. I don't think it's possible to achieve a equivalent exact output with a perspective camera on all possible devices.

**Comment by Josema** [comment]
Still blurry in my screen. 
![image](https://user-images.githubusercontent.com/1819888/78015515-cc8fbb80-7349-11ea-84ce-a49f52727038.png)

Also the two cameras makes my code more complex. Will a 256x256 image and then scaling it with an PerspectiveCamera solve this issue?

**Comment by Mugen87** [comment]
> Still blurry in my screen.

I don't see a noticeable difference on my system.

> Will a 256x256 image and then scaling it with an PerspectiveCamera solve this issue?

It's not a matter of resolution. The problem is the way how perspective projection works.

**Comment by Josema** [comment]
Can you please show a screenshot?

**Comment by Mugen87** [comment]
![screenshot](https://user-images.githubusercontent.com/12612165/78039416-61a4ab80-736e-11ea-8bfe-3b417d329aec.png)

Left is HTML element, right is the sprite.

**Comment by Josema** [comment]
![image](https://user-images.githubusercontent.com/1819888/78040004-2060cb80-736f-11ea-974c-8a812d3224b7.png)

Looks the same in my macbook too. The other one was Chrome and Windows. Weird.

By the way, do you know how to combine the ortographic camera with the OrbitControls? If this task is not posible I can't use this solution.

**Comment by Mugen87** [comment]
> By the way, do you know how to combine the ortographic camera with the OrbitControls?

Um, what do you mean by that? `OrbitControls` definitely supports orthographic cameras.

**Comment by Josema** [comment]
Something like this:
`controls = new OrbitControls( [camera, cameraOrtho], renderer.domElement );`

I'm using a PerspectiveCamera with OrbitControls. The idea of using this technique is having two cameras that both moves at the same time when using the orbitcontrols. And of course that sprite must be represented in the correct position of the PerspectiveCamera.

**Comment by Mugen87** [comment]
Sorry, you can't use `OrbitControls` like that. Besides, I don't think what you are looking for is possible. What I have showed you assume the sprites are used as HUD elements (in screen space) and are not arbitrarily positioned in 3D scene.

**Comment by Josema** [comment]
Just wondering games solve this task with other engines. Look a this example from League Of Legends.

![image](https://user-images.githubusercontent.com/1819888/78044097-81d76900-7374-11ea-85d8-368cf06609d8.png)

I just want to achieve more or less the same. They represent the life the same way, like a Sprite that does not change the size when zooming.

Wouldn't be a good feature to add in Three.js?

**Comment by Mugen87** [comment]
I'm sorry but this is not a real feature request since you can implement annotations or status bars with existing library features like sprites _or_ the CSS renderers. I suggest you search in the forum for more information about this topic. Especially the following post explains how to implement health bars like in your screenshot in a web-based game:

https://discourse.threejs.org/t/sphere-health-bar/11890/5?u=mugen87

Classes like [CSS2DRenderer](https://threejs.org/docs/index.html#examples/en/renderers/CSS2DRenderer) might be helpful in this context.

**Comment by Josema** [comment]
Imagine that Three.js is ported in the future to a smart-tv device that support WebGL but does not have CSS+HTML. I don't think Unity or any other 3D engine use CSS+HTML to solve this issue.
