### ISSUE TITLE
Feature request: uniform random rotation sampling

### ISSUE THREAD

**Issue by cdalizadeh** [mrdoob/three.js#19047]
I'd like to be able to apply a random rotation to an object. There are a couple of ways I initially thought to do this: random euler angles, random (normalized) rotation matrix values, and random (normalized) quaternion values.

The problem is, none of these random rotation methods sample uniformly from SO(3), the set of all 3D rotations. From the (admittedly, limited) research I've done, it appears that there are two methods that do sample uniformly from SO(3):

1. Generate a random point along the surface of a unit sphere, convert the point to a vector, and combine the vector with a random rotation 0 < u < 2*PI to form an axis-angle rotation representation. For generating a random point on the surface of a unit sphere, see the following: https://mathworld.wolfram.com/SpherePointPicking.html

2. Generate a random quaternion. The method described in the link below samples uniformly from SO(3): http://planning.cs.uiuc.edu/node198.html

Method 2 seems easy enough, and I plan to use it in my application.

Reading through some of the discussion in https://github.com/mrdoob/three.js/issues/18996, it seems like this may be a compelling enough use case to either:

1. Add a random method to the quaternion class that implements the logic described in method 2 above, or

2. Add this logic to ```examples/jsm/math/Sampling.js``` or ```examples/jsm/math/Random.js```, as discussed in https://github.com/mrdoob/three.js/issues/18996#issuecomment-606243878

What do you all think? I'd understand if you think it's too application-specific, but I figured I'd raise the idea anyway. I'd be happy to write a PR for either solution if you'd like.

All the best,
Cameron

**Comment by mrdoob** [comment]
@WestLangley We could also add `random()` to `Euler`?

```js
	random: function () {

		this._x = Math.random() * Math.PI * 2;
		this._y = Math.random() * Math.PI * 2;
		this._z = Math.random() * Math.PI * 2;

		this._onChangeCallback();

		return this;

	}
```

**Comment by makc** [comment]
that would be non-uniform, @mrdoob

**Comment by cdalizadeh** [comment]
I'll try to find a proper source for this soon, but I believe makc is correct. That method would result in non-uniform sampling of SO(3).

**Comment by speigg** [comment]
+1. I literally just came across the need for this.

**Comment by speigg** [comment]
https://demonstrations.wolfram.com/SamplingAUniformlyRandomRotation/

**Comment by Mugen87** [comment]
I suggest to make `examples/jsm/math/Random.js` and treat it like Unity's [Random](https://docs.unity3d.com/ScriptReference/Random.html) class. In this way, different routines for generating random data can be added. 

Instead of creating random euler angles, I would prefer creating quaternions instead. And then have a method with and without uniform distribution (which is not always necessary). So `Random.rotation()` and `Random.rotationUniform()`.

**Comment by WestLangley** [comment]
I doubt most user knows what a "uniform quaternion" is -- and what they think it is, is not correct. It is also incredibly application-specific.

We need a compelling use case. https://github.com/mrdoob/three.js/issues/18996#issuecomment-606243878.

**Comment by DefinitelyMaybe** [comment]
> I doubt most user knows what a "uniform quaternion" is -- and what they think it is, is not correct. It is also incredibly application-specific.

tehe

**Comment by makc** [comment]
@WestLangley they might not know fancy math terms, but they can tell good distribution from shitty distribution at a glance.
![glance](https://mathworld.wolfram.com/images/eps-gif/SphericalDistribution_900.gif)

I dont know why are you pushing for simple code instead of the code that produces good results. This is 2nd ticket where you do this now.

**Comment by DefinitelyMaybe** [comment]
at a guess, it's for all the other people when they look into the code and want to make changes. if the code were complex then making the changes is not so approachable ... for everyone, even the ones that know a bit of math.

**Comment by makc** [comment]
the change to this code will not be approved any way, because it would increase the complexity.

**Comment by speigg** [comment]
How is this complicated?

**Comment by brianpeiris** [comment]
This has come up enough times for me to be an annoyance (having to find the math again and again). 

I'd support the creation of a `examples/jsm/math/Random.js`, or adding to `src/math/MathUtils.js`, or just a method on Vector3.

I don't really see how this is application-specific -- sure you might want to craft some specific randomization for your particular application, but picking a point on a sphere uniformly is a very common need, so it makes sense to me to add a common utility function for it, especially since the math for doing it correctly is not intuitive. If specificity is a really concern, then give it a very clear function name.

I've been using this implementation, which is derived from the Wolfram article linked above.

```js
function uniformRandomUnitVector(vec) {
  const u = (Math.random() - 0.5) * 2;
  const t = Math.random() * Math.PI * 2;
  const f = Math.sqrt(1 - u ** 2);
  vec.x = f * Math.cos(t);
  vec.y = f * Math.sin(t);
  vec.z = u;
}
```

Here's a codepen that illustrates the difference between this distribution and the `vector.random().subScalar(0.5).normalize();` version mentioned in #18996.

https://codepen.io/brianpeiris/pen/bGRpxGx?editors=0010

See the clumping in the red instanced mesh, those would have been the corners of the simple random vector distribution.

![Fhb0eBxcjV](https://user-images.githubusercontent.com/79419/131728608-de4e653f-f811-4aca-ab0b-c7061387299f.gif)

**Comment by DefinitelyMaybe** [comment]
love the gif. my guess is go for the `examples` folder. Space/size in `src` is a hot topic.

**Comment by Mugen87** [comment]
@brianchirls Would you be willing to create a PR with your code? 

I suggest to put it into a new file `examples/jsm/math/Random.js` and name the method `onUnitSphere()` (similar to Unity). Instead of creating a class with static methods, I would organize the file similar to `MathUtils`. So just a module with function exports.

If we manage to get your PR merged, other useful methods could be added to `Random.js`, too.

**Comment by brianchirls** [comment]
@Mugen87 I'm honored to be included, but I assume you meant @brianpeiris 😉

**Comment by brianpeiris** [comment]
:) Happy to be mistaken for the other Brian. 
Thanks for the guidance, I'll work on a PR soon.

**Comment by Mugen87** [comment]
I'm sorry. Autocomplete can be evil^^.
