### ISSUE TITLE
WebGLRenderer: WebGL fallback from WebGL2 does not honor context attributes

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#19040]
Consequently, the attributes must be repeated to take effect.
```js
var canvas = document.createElement( 'canvas' );

var context = canvas.getContext( 'webgl2', { alpha: true } );

renderer = new THREE.WebGLRenderer( { canvas: canvas, context: context, alpha: true } );
```
- [ x ] Dev
- [ x ] r115

**Comment by mrdoob** [comment]
This is messy... Maybe it's time to start supporting WebGL2 by default?

**Comment by finnbear** [comment]
Agree that a change needs to be made (default webgl2 sounds great) but, until then, it is possible to use ES6 syntax to work around the issue:
```javascript
const canvas = document.createElement( 'canvas' );
const params = {alpha: true, antialias: true, stencil: true};
const context = canvas.getContext('webgl2', params);
const renderer = new THREE.WebGLRenderer({canvas, context, ...params});
```

**Comment by WestLangley** [comment]
/ping @Mugen87 
/ping @mrdoob 

What is your recommendation?

**Comment by Mugen87** [comment]
In #13717, it was discussed how the WebGL 2 rendering context should be created. It was decided to shift the logic to app level since it was not clear what the renderer should do when the context creation fails. Regarding this decision it's the task of the user to implement a correct fallback like demonstrated with your code.

I guess this is a good opportunity to rethink the design and let the engine handle the context creation. One way to implement this is the introduction of new parameters to control the creation workflow like described [here](https://github.com/mrdoob/three.js/pull/13717#discussion_r179073553) or [here](https://github.com/mrdoob/three.js/pull/13717#discussion_r179077377).

I think I vote for this type of change since enabling WebGL 2 rendering by default will break a lot of apps with custom shader code.

**Comment by WestLangley** [comment]
Either our examples need to do something intelligent, or the renderer needs to do something intelligent. 

I would be inclined to leave it up to the apps (i.e., the examples), but let's pick one or the other. We need proper examples for the users to follow.

**Comment by Mugen87** [comment]
How about introducing a new parameter `webgl2`?

```js
const renderer = new THREE.WebGLRenderer( { webgl2: true } );
```
If set to `true`, the renderer tries to create a WebGL 2 rendering context. If it fails, it uses WebGL 1. The context parameter handling is then encapsulated.

**Comment by WestLangley** [comment]
WebGL 2 will be the standard, so I think this would make more sense if you want to go that route:
```js
const renderer = new THREE.WebGLRenderer( { webgl1: true } ); // force webGL 1
```
Otherwise, it tries WebGL 2, with WebGL 1 as the fallback. The app can then decide how it wants to proceed.

**Comment by Mugen87** [comment]
The device support for WebGL 2 is still limited on mobile devices. However, if @mrdoob thinks the time is right for this change I'm okay with it. It's just important to mark this change very clear in the migration guide since all users who have written custom shader programs have to set `webgl1` to `true`. Otherwise their code won't work anymore.

**Comment by mrdoob** [comment]
Maybe doing a `new THREE.WebGL2Renderer` that extends `THREE.WebGLRenderer`?

**Comment by Mugen87** [comment]
I'm not this works without some code duplication in order to implement a correct WebGL 2 context creation. E.g. you also want to attach the context lost and restore handlers at the right time:

https://github.com/mrdoob/three.js/blob/9b247071c2be06d68d4eab44ba4d6ce13551325c/src/renderers/WebGLRenderer.js#L203-L206

**Comment by Mugen87** [comment]
Should be solved now.
