### ISSUE TITLE
AnimationMixer existingAction should use _actions

### ISSUE THREAD

**Issue by Dockyardb** [mrdoob/three.js#19155]
##### Description of the problem

In the current version when you call `mixer.existingAction('action')` you need to have all the animationClips on the rootObject for this animation. 

This is caused by the  `AnimationClip.findByName` called in `existingAction`. 

But because the actions should be already registered in the mixers `_animations` i would suggest to use something like this: 

```
 _getClipFromActions: function (clipName) {
	    const action = this._actions.find((action) => {
	        return action.getClip().name === clipName;
        });

        return action ? action.getClip(): undefined;
    }




existingAction: function ( clip, optionalRoot ) {

		var root = optionalRoot || this._root,
			rootUuid = root.uuid,

			clipObject = typeof clip === 'string' ?
                this._getClipFromActions(clip) : clip,

			clipUuid = clipObject ? clipObject.uuid : clip,

			actionsForClip = this._actionsByClip[ clipUuid ];

		if ( actionsForClip !== undefined ) {

			return actionsForClip.actionByRoot[ rootUuid ] || null;

		}
	return null;
}
```

If i misunderstood something in the meaning of  `existingActions` please let me know.

##### Three.js version

- [ ] Dev
- [x] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> But because the actions should be already registered in the mixers _animations

There is no property or variable called `_animations` in `AnimationMixer`. Are you referring on `_actions`?

**Comment by Dockyardb** [comment]
> There is no property or variable called _animations in AnimationMixer. You are referring on _actions, right?

Yes i meant the _actions. 

> If I read the code correctly, this should be no issue if you pass in the clip instead of the clip's name, right?

Yes there should be no issue.

In the mentioned Documentation is also written :

> The first parameter can be either an AnimationClip object or the name of an AnimationClip.

So i thought i has been forgotten in the types since it is available in the mixer itself.

In my use case i created for each gltf i load into my scene a mixer which creates AnimationActions via `.clipAction`. Later when i wanna use this action it would be nice if i just call something like `mixer.existingAction('run')` because i would prefer not to safe the references to the clips somewhere else.

I hope you cant understand what iam aiming for. If not please let me know.

**Comment by Mugen87** [comment]
> The first parameter can be either an AnimationClip object or the name of an AnimationClip.

Oh, I've only checked the type of the parameter `clip` (which is only `AnimationClip`) and not the description. There are indeed some inconsistencies regarding this method...

**Comment by Mugen87** [comment]
May I ask: Why is it a problem for your app to store the animations in the root object? In this way, you could also use `AnimationMixer.clipAction( 'run' )`.

**Comment by Dockyardb** [comment]
It's not a problem of the app its rather personal preference and it feels a bit hacky since my root object is an Object3D and there is no property for `animations `in the definitions. 

Also i think it would be a bit redundant to have the clips on the root object and in the actions of the mixer.

**Comment by Mugen87** [comment]
Sorry, for asking all these questions^^. I just wanted to understand your view on this issue and how you use the API. And thanks for sharing the code example.

There is currently an assumption in `AnimationMixer` that you are somewhat hitting in your application: The animation clip lookup by name only works if the animations are stored in the 3D object or the geometry. 

If the missing definitions of `animations` is the problem, well, this can easily be fixed. However, I'm not sure it's worth to change the above assumption because the current design does not "fit" into your application code.

**Comment by Dockyardb** [comment]
> Sorry, for asking all these questions^^. I just wanted to understand your view on this issue and how you use the API. And thanks for sharing the code example.

No problem, iam realy happy that you take your time for this and not just decline/accept it withought questioning it.

> The animation clip lookup by name only works if the animations are stored in the 3D object or the geometry.

I understand that i need to do it in the current state but really don't understand why i would need to do it since the Mixer already got all infromation about the actions/clips that are available to this particular mixer.

So as i said it seems redundant for me to have this information safed at multiple locations. Or do you want get Clips from other Mixers in this method?

**Comment by Mugen87** [comment]
> Or do you want get actions from other Mixers in this method?

Definitely no^^. Yes, the mentioned assumption feels redundant when just using `AnimationMixer.existingAction()`. TBH, I'm not sure how to judge this issue right now. There are pros and cons for your solution and keep things as they are. I'm undecided...

**Comment by Dockyardb** [comment]
> There are pros and cons for your solution and for keeping things as they are. I'm undecided...

May i ask you what the cons are? Do you benefit from the clips on the Object in other Functions?

**Comment by Mugen87** [comment]
One the one hand, it's a matter of consistency. Users could argue: Why can I use the clip name in `existingAction()` but not in `clipAction()` without  adding animations to the object?

Besides, I'm not happy with the current way animations clips are stored in `three.js` entities. `Object3D.animations` is not properly documented although the animation system and `ObjectLoader.parse()` use it. I think I would like to couple animations tighter to 3D objects so it's easier to look them up and serialize/deserialize. Against this backdrop, I see no reason for allowing animations

**Comment by Dockyardb** [comment]
> One the one hand, it's a matter of consistency. Users could argue: Why can I use the clip name in existingAction() but not in clipAction() without adding animations to the object?

That makes sense but you could remove the code for strings in clipAction() since it could be used as initialization for actions and existingAction() could be used to get any initialized action from the mixer.

> Against this backdrop, I would not voote for changing the mentioned policy of AnimationMixer.

As sad this is, you are much deeper in this code and if you think this not an improvement i have to accept this.

But nevertheless atleast the docs and types should be updated so there is no more confusion.

Thanks for the Discussion and fast replies :)

**Comment by shaunco** [comment]
The _"The first parameter can be either an AnimationClip object or the name of an AnimationClip."_ part just threw me off for an hour or so as well... In my case I have Group objects that contain several identical Mesh objects (think stacked extruded shapes), where each Mesh has a single child that is an EdgesGeometry/LineSegments wireframe. 

I have a single AnimationMixer(scene) and was trying to use one generically created animation clip that would simply set fade out the opacity of the wireframes (binding of: "shape/wireframe.material.opacity") rather than creating one animation per wireframe uuid. At group creation I still called `mixer.clipAction(genericClip, group)`, expecting to be able to find it later by name in a call to clipAction or existingAction, but the issue described here popped up: findByName fails because the group doesn't have a geometry.animations or a .animations. I was expecting .animations to be created by the first call to clipAction with a root specified, but it looks like .animations is only created in the various loaders.

I will switch to keeping my own array of clips and passing the right clip/root combo to clipAction (instead of name/root), but the current docs are definitely misleading...

**Comment by Mugen87** [comment]
In the meanwhile, animations are now tighter coupled to `Object3D`. `Object3D.animations` was introduced together with the respective type definitions, see:

https://github.com/three-types/three-ts-types/blob/db2494891d6f4ade675afc3b4c17b9e77693d15d/types/three/src/core/Object3D.d.ts#L155-L159

In order to keep the API in `AnimationMixer` consistent, `clipAction()` and `existingAction()` will keep using `AnimationClip.findByName()`. The solution for this issue is to assign animations to their dedicated place `Object3D.animations`. Certain loaders like `ColladaLoader` and `FBXLoader` already store object animations in this property.

If you are planning to serialized/deserialize your scene, you need to do this anyway.
