### ISSUE TITLE
SVGLoader doesn't support use and defs tags

### ISSUE THREAD

**Issue by eulertour** [mrdoob/three.js#19168]
##### Description of the problem

As described in the title, SVGLoader doesn't support the `<use>` and `<defs>` tags. As a result, SVGs like this one are rendered incorrectly:
[664e80e8d8d98482.txt](https://github.com/mrdoob/three.js/files/4498806/664e80e8d8d98482.txt)

##### Three.js version

- [x] Dev
- [x] r115

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)

None

**Comment by eulertour** [comment]
This is also true of the viewBox and viewPort attributes for the `<svg>` tag.

**Comment by WestLangley** [comment]
Related #14569, #18104.

**Comment by Mugen87** [comment]
> SVGLoader doesn't support use and defs tags

Should be solved via #20209.

However, the test file is not yet rendered correctly. Probably a different issue.

**Comment by yomboprime** [comment]
> However, the test file is not yet rendered correctly. Probably a different issue.

Yes, must be a different issue.

I've removed the ```defs``` and ```use```, spread the letters programmatically in the html, and they show wrong. So the issue is not with the ```defs``` tag.

![imagen](https://user-images.githubusercontent.com/2453652/98974296-0a2a0900-2515-11eb-9429-9755040102f1.png)

```mesh.position.x += i * 10;```


[latextest_without_defs.txt](https://github.com/mrdoob/three.js/files/5532195/latextest_without_defs.txt)

**Comment by yomboprime** [comment]
With #21380 (and probably other PRs related to number parsing) now it is solved. It looks like this:

![imagen](https://user-images.githubusercontent.com/2453652/110257414-15121900-7f9e-11eb-903f-a47270914145.png)
