### ISSUE TITLE
PointLight complains about maximal texture size despite setting shadow.mapSize properly

### ISSUE THREAD

**Issue by kpeeters** [mrdoob/three.js#19181]
##### Description of the problem

Despite setting the shadow map size to the maximal supported texture size, three.js's `PointLight` complains about the size being larger than the supported maximal texture size:

    var maxsize = renderer.capabilities.maxTextureSize;
    light.shadow.mapSize.set(maxsize, maxsize);

produces

    THREE.WebGLShadowMap: jf has shadow exceeding max texture size, reducing

##### Three.js version

r115
[
##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Differs by hardware; the above error is produced on an integrated Intel UHD 620, but not on an nVidia GTX 1050 (these, of course, have different maximal texture sizes, but that should not make a difference for the above code sample).

**Comment by Mugen87** [comment]
Live example demonstrating the issue: https://jsfiddle.net/tdj8wvxs/

This issue seems related to `LightShadow._frameExtents` which was introduced in #17228 (/cc @supereggbert). The default value is `(1,1)` and has thus no effect on the final shadow map's size. However, `PointLightShadow` sets the value to `(4, 2)`. As shown in the following code section of `WebGLShadowMap`, this will trigger the warning and the respective resize.

https://github.com/mrdoob/three.js/blob/5ee6e857635ffe0c0642587668b770cfe07b47ba/src/renderers/webgl/WebGLShadowMap.js#L114-L116

**Comment by Mugen87** [comment]
@mrdoob Do we really need this warning at all? Before the @supereggbert's PR, the shadow map's size was silently adjusted without notifying the user.

https://github.com/mrdoob/three.js/blob/d311942498623dec5e1eb26f1dd84d9ceb97fbf7/src/renderers/webgl/WebGLShadowMap.js#L135

The current warning is similar to the texture warning that notifies the user after a resize. However, since `LightShadow.mapSize` does not determine the final map size, the log does not reflect the actual behavior of the engine.

**Comment by mrdoob** [comment]
I think we can revert to silently adjusting the size 👍
