### ISSUE TITLE
EditorControls is unavailable via NPM

### ISSUE THREAD

**Issue by amioren10** [mrdoob/three.js#19219]
Since version r109 EditorControls were moved to editor directory.
Now it is impossible for me to access this class in my project via npm.
This is because the editor dir is not a part of the npm package.

Please move EditorControls back to the previous dir or add it to the npm package
because it is very useful.

Please keep doing a great job,
Ami

**Comment by DefinitelyMaybe** [comment]
Hey Ami,

I can't find the issue's/PR's related to moving the editor into the separate dir but I don't think it was a bad idea. If you were using a specific version of three, how come the change?

There are probably a couple of things that can be done to get the scripts you'd like but that's a discussion better suited to the [forums](https://discourse.threejs.org/)

**Comment by Mugen87** [comment]
See https://github.com/mrdoob/three.js/pull/17479#issuecomment-530927300

I don't think `EditorControls` it makes sense to move the controls back to the examples since it the class was specifically designed for the editor. It should have been located in `editor/js` from the very beginning.

If you need the class, copy the code into your own project.
