### ISSUE TITLE
PDBLoader: Problems with "TER" record processing.

### ISSUE THREAD

**Issue by acx70** [mrdoob/three.js#19225]
I wrote a complete description of the problem in this thread: https://discourse.threejs.org/t/error-in-pdb-loader/14648

**Comment by Mugen87** [comment]
The code crashes because your `PDB` files contains `TER` (or termination) records which are not yet parsed by `PDBLoader`.

**Comment by Mugen87** [comment]
@acx70 After #19242, your file should load. However, I'm not sure the loader evaluates `TER` records correctly? Do you know the purpose of this records? TBH, it's not clear for me from the official documentation how this records should effect the parsed asset.

https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html

**Comment by Mugen87** [comment]
Okay, found something [here](https://pdb101.rcsb.org/learn/guide-to-understanding-pdb-data/dealing-with-coordinates):

>  Most molecular graphics programs look for this TER record so that they don't draw a bond to connect different chains. 

Since the example only renders bonds defined via `CONECT` records, it seems this issue can be closed.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Michael Herzog <notifications@github.com>
发送时间：2020-04-26 20:11
主题：Re: [mrdoob/three.js] PDBLoader crash (#19225)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

The code crashes because your PDB files contains TER (or termination) records which are not yet parsed by PDBLoader.
