### ISSUE TITLE
DragControls don't change cursor

### ISSUE THREAD

**Issue by Dragon3DGraff** [mrdoob/three.js#19290]
##### Description of the problem
I made changing of manipulate mode by keys. "d" switches on drag mode.
If drag mode is on and cursor on dragable object when I switch off drag mode and move cursor from object it don't change to "auto" and stay "pointer"
(_domElement.style.cursor = 'pointer'; in sourse three.js)
you can see it in [video](https://youtu.be/mvJxBStt4tI)

[source code](https://github.com/Dragon3DGraff/TertiusAxis/blob/master/src/Actions.js)

you can try it here
[https://dragon3dgraff.ru/TertiusAxis/](https://dragon3dgraff.ru/TertiusAxis/)

##### Three.js version

- [ ] Dev
- [x] r116
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
If you call `DragControls.deactivate()`, the controls will remove all its event listeners. That means if you position the mouse over a 3D object and then deactivate  `DragControls`, the internal `onDocumentMouseMove()` event handler is not called anymore and thus unable to update the cursor's style.

We could consider to add the following line of code to `DragControls.deactivate()` in order to ensure a style reset.
```js
_domElement.style.cursor = 'auto';
```

**Comment by Dragon3DGraff** [comment]
@Mugen87  Thank you, I added 
`taScene.dragControls.deactivate();

labelRenderer.style.cursor = 'auto';`
But now if I switch on DragControls and cursor is on the object it not change, only after it go away from object and come back again or move this object. You can see it on video
[video](https://youtu.be/OXNWltXPB3I)

**Comment by Mugen87** [comment]
`DragControls.activate()` could also check if `_hovered` is not null and then update the cursor's style. Unfortunately, this is not something you can fix on app level since `_hovered` is a private variable.

**Comment by Mugen87** [comment]
Fixing `DragControls.activate()` is actually more complicated than I thought. Just checking `_hovered` is not sufficient. The logic in `onDocumentMouseMove()` has to be executed at least once in order to know whether the cursor is over a 3D object or not. However, just calling `onDocumentMouseMove()` does not work since event data are required. 

@Dragon3DGraff Can you fix the issue by using the following code in your app right after calling `activate()`:
```js
domElement.dispatchEvent( new Event( 'mousemove' ) );
```
`domElement` is the element you have passed into the ctor of `DragControls`.

**Comment by Dragon3DGraff** [comment]
[https://youtu.be/oskiDobIKtw](video)
@Mugen87 it seems nothing cnahged

**Comment by Mugen87** [comment]
Have you computed proper values for `coordX` and `coordY`? They represent the current mouse coordiantes.

**Comment by Dragon3DGraff** [comment]
> Have you computed proper values for `coordX` and `coordY`? They represent the current mouse coordiantes.
@Mugen87 it works properly, thank you! [https://youtu.be/JXDOFiyzSBQ](https://youtu.be/JXDOFiyzSBQ)

**Comment by Mugen87** [comment]
Glad to hear that! 

Since you can only get the current mouse position via an event, it's not possible to add this code to `DragControls.activate()`. Hence, fixing the cursor state when the controls are activated needs to be done on app level.

**Comment by Dragon3DGraff** [comment]
@Mugen87 I tried to fix in DragControls
I put `_domElement.style.cursor = 'pointer';` right after checking `if ( _intersections.length > 0 ) {`
![image](https://user-images.githubusercontent.com/51860375/81852533-d9681780-9563-11ea-8a85-6c22cb701e3b.png)
[https://youtu.be/LGq9ZG5zemM](https://youtu.be/LGq9ZG5zemM)
it's seems works properly

**Comment by Mugen87** [comment]
I don't think just adding this code is sufficient. The even listener needs to run at least once so `DragControls` can update its internal state.
