### ISSUE TITLE
Suggestion: Add list of external three.js plugins to documentation

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#19353]
For the most part three.js extensions are stored and maintained in the `examples` directory of this project and it wouldn't surprise me if a lot of users think this is how new packages can or should be built to extend three.js. There are some benefits but more broadly it seems unsustainable because it more or less passes the burden of maintaining the packages onto the maintainers of this repo. There may be other reasons people can't or don't want to include their library in this project, too. I think it would be great to create a page documentation page that links to externally maintained libraries that plug into three.js (or even just can be used with three.js).

I think this would encourage people to make more packages and make other packages people do maintain more discoverable. [This thread on SDF text rendering](https://discourse.threejs.org/t/troika-3d-text-library-for-sdf-text-rendering/15111) specifically is what prompted the idea. I was looking for a three.js-compatible SDF implementation awhile ago but I wasn't able to find this. Even when you know what you want packages aren't always so findable.

I think the page would ultimately just be a list of github repos to start with and an optional short description. If the list becomes long enough we could organize a bit more. I know I have some projects I'd add to the list.

**Comment by marquizzo** [comment]
I see lots of people asking in the forums for "what physics engine should I use?" so I started gathering [this list of physics libraries](https://discourse.threejs.org/t/preferred-physics-engine-cannon-js-ammo-js-diy/1565/9?u=marquizzo) for that same reason. The problem is that it's buried 9 comments deep in an obscure thread. Would be great to have something similar in a place with higher visibility, where everyone can contribute to it to keep it up to date.

**Comment by DefinitelyMaybe** [comment]
:tada:

**Comment by looeee** [comment]
I think the list should be a bit broader than strictly "three.js plugins". 
For example, cannon.js, tween.js, stats.js, dat.gui, GSAP are all commonly used with three.js, and it would be good to include them on the page, but they are not three.js plugins. 
Maybe we can call the list "Tools and Plugins"? That should be sufficiently broad to add anything we want. 

Some possible categories (we don't have to include all of these, and other suggestions are welcome):

#### Frameworks and Libraries

cannon.js, tween.js, stats.js, dat.gui, GSAP, Ecsy, ...

#### Tools Built-on three.js

react-three-fiber, A-Frame, Meep, ...

#### three.js Plugins

troika 3D text, ...

#### Standalone Applications 

(maybe just free/open source tools here? otherwise the list will be huge)

Blender, Paint3D, Clara.io, ...

**Comment by gkjohnson** [comment]
> I think the list should be a bit broader than strictly "three.js plugins".

Agreed. I think it makes sense to evolve the list as it grows. Depending on how many items there are it might make sense to have other subheaders, too.

And to respond to your forum post:

> The problem is that third party plugins often start out good but are not maintained, then after a couple of years they stop working. We could add the list with a disclaimer “these are not maintained by three.js and may need to be updated before you can use them with the latest version of three.js”.

I think a disclaimer is good. Ultimately its going to have to be up to the user to determine if the external project is suitable for them. Increasing the visibility of some projects may help encourage more maintenance, as well, or new users to pick up and modernize out of date packages.

@mrdoob if this is agreeable I can add a page that lists a few packages and then we can leave it to the community to add more.

**Comment by Fyrestar** [comment]
I'm not sure if that fits to this, but i've been recently working on a portal for THREE that should be ready soon, it's basically similar to asset stores Unity or Unreal have, though without being focused on commercial items nor selling.

It's rather to share projects, libraries, plugins, engines, examples, books and other resources around THREE at one spot, as currently everything outside the core is rather hidden. Submitted items only need to get reviewed, they can get reviewed and get a status, that can be suggested by users too, so items might be WIP, in active development, maintained or abandoned, which i think helps a lot making decisions as a lot projects been laying around untouched since months with no hint if it's abandoned.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Marquizzo <notifications@github.com>
发送时间：2020-05-14 04:38
主题：Re: [mrdoob/three.js] Suggestion: Add list of external three.js plugins to documentation (#19353)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

I see lots of people asking in the forums for "what physics engine should I use?" so I started gathering this list of physics libraries for that same reason. The problem is that it's buried 9 comments deep in an obscure thread. Would be great to have something similar in a place with higher visibility, where everyone can contribute to it to keep it up to date.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Rawr <notifications@github.com>
发送时间：2020-05-14 05:50
主题：Re: [mrdoob/three.js] Suggestion: Add list of external three.js plugins to documentation (#19353)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

🎉

**Comment by pailhead** [comment]
I've been thinking about this topic for years. My 2 cents:

>I think the list should be a bit broader than strictly "three.js plugins".

I disagree with this in general, explanation to follow.

>For example, cannon.js, tween.js, stats.js, dat.gui, GSAP are all commonly used with three.js, and it would be good to include them on the page, but they are not three.js plugins.

I want to say that these are generic web/js libraries. Sure dat.gui can be used with three.js, but can also with any other library, graphics or not. It's by no means a **three.js plugin**, it's a dev/debugging/ui tool for building web apps. While it's pretty self explanatory that it can be used with three.js since most of the examples use it for a rudimentary UI, it may not be immediately obvious that the widget in some corner of the screen _is_ `dat.gui`. I'd mention it as a useful _tool_ but rather than choosing some docs, there could be a link on the example itself. In other words, it makes way more sense to answer the _frequently_ asked question of **what is that widget that i see in a lot of three.js examples** then in any way indicate that dat.gui, or tween are somehow related to three. I believe that this can help build a mental model better. 

IMHO this is a bit of a problem with three, i believe that a new comer can conflate a lot of these libraries, when for example both tween and dat.gui take something like an instance of `Vector3` and *mutate it* - which is exactly what the user does when they don't involve these libraries. 

> Maybe we can call the list "Tools and Plugins"? That should be sufficiently broad to add anything we want.

I would thus not conflate these two categories by no means. IMHO, the problem that this issue is pointing out is that most things three tend to be put into the same bucket. Explanation to follow. 

>**Frameworks and Libraries**

As mentioned above. 
- These are three agnostic. 
- At a minimum it doesn't have anything to do with this particular issue (_plugins_). 
- Examples cover all of these _(they don't exist in relation to three without examples - if no one writes an example of using three with cannon, cannon might as well not exist as far as three is concerned)_
- This most likely wouldn't scale, and would probably suffer from the same problems as three.js examples do - they are all examples, but some are more equal than the others. It's impossible to mention any JS package that could possibly be used with three.js, and it would leave the burden of picking this group and maintaining it. (Although, i guess this sort of section/doc could mention **all of the libraries used in examples** and solve this).

>**Tools Built-on three.js**
> react-three-fiber, A-Frame, Meep, ...

- I believe that this suffers from similar problems. 
- Would one track every opensource project that is built on three.js?
- Would any project be eligible to be mentioned in this official resource list?
- These feel like they would come in all shapes and sizes, like A-frame - almost warrants it's own category in any case, 
- I think that these are essentially, at it's core, examples of what can be built with three.js.

>**Standalone Applications**
>(maybe just free/open source tools here? otherwise the list will be huge)

- I would most definitely advise against this. 
- I think it may lead to problems of a beauty contest - "why is my app not there".

> **three.js Plugins**

- I want to argue that many if not all of the examples could find themselves in this category.
- An example that ceases to be maintained, may be picked up by someone and hosted in it's own repo. 
- `OrbitControls` to me feel like they are a plugin for three.js - it's mutating some properties on a core `Object3D` (a camera), using three's core math objects. 


While not this topic, i feel that this is directly related to the issue - semantic versioning :)
IMHO if three had a "stable" version, something that "plugins" can be based on, this issue could become a non issue for the library. NPM would simply take the burden off of having to mention and link anything.

**Comment by pailhead** [comment]
@Fyrestar 

>Submitted items only need to get reviewed, they can get reviews by user and a status, that can be suggested by users too, so items might be WIP, in active development, maintained or abandoned, 

I think npm already does this, it can track how many people are using the package, when was the last publish, indexes readmes if im not mistaken. There is no review process though, it's all open, anyone can publish, anyone can search.

**Comment by mrdoob** [comment]
> @mrdoob if this is agreeable I can add a page that lists a few packages and then we can leave it to the community to add more.

I think that sound good to me.

**Comment by gkjohnson** [comment]
@pailhead my goal in making a page like this would be to enable users to find packages that solve or can be used to solve common problems when using three.js (physics, effects, text, 3d ui, etc). To that end I think projects that don't necessarily _only_ support three.js are okay. Three.js also brings in a lot of people who are otherwise unfamiliar with 3d development and projects like AFrame or R3F might be approachable for this kind of user. If we can point them at a project that looks more comfortable to get started then that seems great to me.

@mrdoob Awesome -- I'll put together a page some time in the next week or two!
