### ISSUE TITLE
Use of environmentBlendMode is incorrect

### ISSUE THREAD

**Issue by Manishearth** [mrdoob/three.js#19386]
##### Description of the problem

Three.js currently has the following check to see if it should render a background:

https://github.com/mrdoob/three.js/blob/617ea9ae91acb02af95178361b33a6113e29e736/src/renderers/webgl/WebGLBackground.js#L36-L40

environmentBlendMode is not an indication of the session mode, the session mode used at creation should be held on to (perhaps by creating a `.mode` field on the `XRSession`) if we want this check.

Now, if we switch the check to be `xr.mode == "immrsive-ar"`, this will stop rendering the background on opaque-display VR devices that claim to support AR mode. This seems ... okay to me; as far as I understand it no browser has made this choice yet, but if it were to it would likely be to make it possible to tsst out AR-specific content on VR devices, in which case we should probably have things render as close to that as possible.

If we _do_ want to render the background even on opaque-display VR displays claiming to be AR, this check should instead check for _either_ `"additive"` or `"alpha-blend"` blend modes

##### Three.js version

- [x] Dev
- [ ] r116
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
What do you think @toji?

**Comment by toji** [comment]
I agree with @Manishearth's general assessment. I'll also add that `additive` blend mode won't show up on phone AR, for instance, and that's still an situation where you'd want to omit the background. So yeah, the right thing to look at is whether or not the blend mode is `opaque` and only draw the background if that's the case.

Testing for `additive` could still be considered in some cases, especially things like drawing shadows on the (real) ground, since additive displays have no way of showing black and therefor trying to darken part of the scene is wasted pixels. That seems rather content dependent, though.

**Comment by Mugen87** [comment]
Seems this has been resolved via #25781.
