### ISSUE TITLE
after change timeScale then change AnimationAction.time it does not work 

### ISSUE THREAD

**Issue by scyuan** [mrdoob/three.js#19535]
##### Description of the problem

> step 1:

change timeScale

```
const clipDuration = clip.duration;                  // eg: 20s
this.animationAction = this.mixer.clipAction(clip, this.character);
// change timeScale
this.timeScale = clipDuration / duration;         // eg: 20s/10s = 2
this.animationAction.setEffectiveTimeScale(this.timeScale);
```

> step 2:

change time

```
// duration is from 0 to 20;
this.animationAction.time = 10;
```

##### expected

Start playback from the correct time

##### The actual situation

Will not end normally

##### Three.js version

- [x] r117

##### Browser

- [x] Chrome

##### OS

- [x] macOS

**Comment by Mugen87** [comment]
I've tried to provide a fiddle for your use case right here: https://jsfiddle.net/8xcfgnhw/2/

Can you please explain the problem by describing the expected behavior in more detail using the fiddle?

**Comment by scyuan** [comment]
> I've tried to provide a fiddle for your use case right here: https://jsfiddle.net/pby2afwo/
> 
> Can you please explain the problem by describing the expected behavior in more detail using the fiddle?

if delay play function
```
setTimeout( () => {	
    clipAction.play(); 
}, 2000 );
```
set time it would be effective

**Comment by scyuan** [comment]
> I've tried to provide a fiddle for your use case right here: https://jsfiddle.net/pby2afwo/
> 
> Can you please explain the problem by describing the expected behavior in more detail using the fiddle?

I can't reproduce it in this example.but When I use bvh format animation, it will reappear

**Comment by scyuan** [comment]
here is a example: https://codesandbox.io/s/quirky-tdd-mk5tm?file=/src/index.js
the clip duration is 2.5s, I set timescale=0.5 and set duration=5s.
when set action time=4s. and it does not animate!(because the time is larger than 2.5s?)

**Comment by Mugen87** [comment]
Sorry for the late reply but fortunately I have encountered the same issue in another support request.

The problem is that `timeScale` only effects the final time delta value. Meaning if the value is `0.5`, time delta values are halved which duplicates the playback duration.

However, the value of `AnimationAction.time` and `AnimationClip.duration` are not affected by time scaling. So in your case if you use set `AnimationAction.time` to `4`, the update logic assumes the animation clip has already finished (because it only lasts 2.5s).

To me, this is not necessarily a bug but a misunderstanding of the existing concepts. `timeScale` does only affect the advance in time (and thus the time delta values). But no the actual duration value of animations.

I guess the confusion comes from `Animation.setDuration()` which effectively sets `AnimationAction.timeScale`. If I could start from scratch, I would probably not add this method to the API.
