### ISSUE TITLE
Using gltf to export tube geometry reload without parameters

### ISSUE THREAD

**Issue by WREQI** [mrdoob/three.js#19723]
Using gltf to export tube geometry reload without parameters
No parameters can be modified when I load the tube again
How to convert it to tubebuffergeometry after loading
![image](https://user-images.githubusercontent.com/35467304/85522736-9efc9a80-b638-11ea-807a-e053c9ab365b.png)
![image](https://user-images.githubusercontent.com/35467304/85522746-a2902180-b638-11ea-8e89-2b8f0e20f63f.png)

**Comment by Mugen87** [comment]
When you export to `glTF`, all types of geometry have to be represented as just geometries. The specific type information (box, sphere, tube geometry) gets lost since `glTF` does not know these types. Hence, when you import the tube, it's just a normal `BufferGeometry`.

You should be able to solve this issue if you export to the `three.js` JSON format instead.

**Comment by WREQI** [comment]
I've tried to export it as JSON, but not in any other format. Can I provide an option for the exporter to choose whether to export parameters

**Comment by Mugen87** [comment]
> Can I provide an option for the exporter to choose whether to export parameters

Sorry, it's not clear what you mean by that. Can you please explain in more detail?

**Comment by donmccurdy** [comment]
Only the three.js JSON format knows about all of three.js's custom geometry types. All other formats are not specific to three.js, and when you import the model back from these formats it will be a generic BufferGeometry without these parameters.
