### ISSUE TITLE
Suggestion to add functions getPoints() and getVetices()

### ISSUE THREAD

**Issue by Dragon3DGraff** [mrdoob/three.js#19749]
##### Suggestion

I suggest to add two functions to BufferGeometry. Like this

getPoints() gets points of geometry

       function getPoints( mesh ) {

		let pointsArray = mesh.geometry.attributes.position.array;
		let itemSize = mesh.geometry.attributes.position.itemSize;
	
		let points = [];
	
		for (let i = 0; i < pointsArray.length; i += itemSize ) {
	
			points.push( new THREE.Vector3( pointsArray[i], pointsArray[i+1], pointsArray[i+2]));
	
		}
	
		return points;
	
	}

getVetices() gets unique vertices from points

    function getVertices( points ) {

	  let vertices = [];

	  points.forEach( ( indexPoints ) => {

		let equal = false;

		vertices.forEach( ( indexVertex ) => {
			
			if (indexPoints.equals( indexVertex) ){

				equal = true;
				return;

			}

		})

		if ( !equal ) {

			vertices.push( indexPoints );

		}

	})

	return vertices;

    }

I think it will be very useful

**Comment by donmccurdy** [comment]
Although the functions you describe may be convenient, creating a Vector3 instance for every vertex in a Mesh is very inefficient for performance and memory purposes. It is much better to work with the BufferGeometry's [BufferAttribute](https://threejs.org/docs/#api/en/core/BufferAttribute) instances and do something like this:

```js
const v = new THREE.Vector3();

for ( let i = 0; i < geometry.index.count; i++ ) {

  v.fromBufferAttribute( geometry.attributes.position, geometry.index.getX( i ) );

  // do something with vertex, 'v'

}
```

Generally we want to make it easy to do things efficiently, rather than making it easy to accidentally do something that's very slow without realizing the cost. This is why methods like `fromBufferAttribute` are preferred.

For identifying unique vertices in a mesh, the [BufferGeometryUtils.mergeVertices](https://threejs.org/docs/#examples/en/utils/BufferGeometryUtils.mergeVertices) method may be useful.

**Comment by Dragon3DGraff** [comment]
Ok, thank you for your explanation. I think this issue may be closed  =)
