### ISSUE TITLE
r115 -> r118 breaks extensions derivatives

### ISSUE THREAD

**Issue by luruke** [mrdoob/three.js#19754]
##### Description of the problem
Just upgraded my project from r115 to r118 (mainly to exploit the VAO support).
My shaders fails compiling due the use of `dFdx|dFdy`.

The `GL_OES_standard_derivatives` doesn't seems to be loaded, even though I have:

```
  extensions: {
    derivatives: true,
  },
```

Is the syntax changed or something?

##### Three.js version

- [ ] Dev
- [x] r118
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
[SAOPass](https://threejs.org/examples/webgl_postprocessing_sao) enables derivates too and everything seems to work fine. Can you please demonstrate the issue with a live example?

**Comment by luruke** [comment]
@Mugen87 , it makes sense,  but i would imagine that your fixed fiddle won't work in case `WebGLRenderer` fallbacks for WebGL1, right? (for example on Safari)

So, the correct best-practice would be to submit the right set of shaders (vert + frag) when using RawShaderMaterial/ShaderMaterial depending if using webgl1 vs webgl2?

If there a way to know if WebGLRenderer is using WebGL2 context or fallback to 1?

**Comment by Mugen87** [comment]
> If there a way to know if WebGLRenderer is using WebGL2 context or fallback to 1?

You can check this via [WebGL.isWebGL2Available()](https://github.com/mrdoob/three.js/blob/25d16a2c3c54befcb3916dbe756e051984c532a8/examples/jsm/WebGL.js#L25-L38) before creating the renderer. 

> So, the correct best-practice would be to submit the right set of shaders (vert + frag) when using RawShaderMaterial/ShaderMaterial depending if using webgl1 vs webgl2?

Yes, since `three.js` somewhat expects GLSL 3.0 code when using WebGL 2 although this coupling is technically not necessary (meaning you can use GLSL 1.0 with WebGL 2). But the engine does not execute certain logic (e.g. enabling extensions like `GL_OES_standard_derivatives`) with a WebGL 2 rendering context.

In your particular case, I suggest to use `WebGL1Renderer`. For existing projects it makes only sense to invest the migration effort if you want to utilize a WebGL 2 exclusive feature like multisampled render targets. Otherwise you don't benefit from any migration effort right now.

**Comment by luruke** [comment]
@Mugen87 , thanks makes sense.
In my case I will just force WebGL1.
