### ISSUE TITLE
The Joys of Performant Debugging (Optional logs / warnings)

### ISSUE THREAD

**Issue by mjurczyk** [mrdoob/three.js#19822]
##### Description of the problem

Related to https://github.com/mrdoob/three.js/issues/7112, https://github.com/mrdoob/three.js/pull/5791, https://github.com/mrdoob/three.js/pull/19309 and a few more.

Is there any reason why we can't suppress warnings from Three? Adding `Three.warn / Three.log` seems like a 5 minute PR with kinda 0 deprecation issues and 100% happiness increase of any CPU 🤔  ..?

--- 

![Screen Shot 2020-07-09 at 16 21 25](https://user-images.githubusercontent.com/9549760/87052567-36e5b100-c201-11ea-9060-39fbda6eea33.png)

Short story long, I understand that deprecation warnings are there originally to help with debugging, and so are possibly any other warnings - but when Chrome tries to render (even hidden) 20k warnings right out of the door (it is a bit of a specific project case, as it generates a lot of materials on the go, but it still *is* a case.) the app and console freeze for 30 seconds.

Add hot reload plus `Preserve Logs`, it freezes until next calendar year :') 

![Screen Shot 2020-07-09 at 16 25 06](https://user-images.githubusercontent.com/9549760/87054047-f7b85f80-c202-11ea-9a6d-819e21c71ac1.png)

While none of the things mentioned in warnings are mandatory or breaking at this moment (fixing required vector targets can wait until the version release, and materials won't break on `undefined` in these specific cases.) the logs that the rest of the application spits out are important, very helpful for debugging, and also lost among 20k three.js warnings (hence [this workaround](https://github.com/mrdoob/three.js/pull/19309#issuecomment-631226503) isn't really an option.)

##### Three.js version

- [x] Latest

##### Browser

- [x] Chrome

##### OS

- [x] All of them

**Comment by mjurczyk** [comment]
(As before - I can do the PR, just would like to know if there's any reason behind not having it already :) )

**Comment by Mugen87** [comment]
Sorry, but this topic was discussed multiple times in the past and I see no reason why to start over again.

You can monkey-path the behavior of `console.warn` on application level.

**Comment by mjurczyk** [comment]
Yep, that's why I linked them and ask why we wouldn't do that, except for opinionated statements that "why would someone not want logs?"

Hacks like that don't work if app itself uses warns, and removing them by hand from three's source makes three un-upgradable - so something that's supposed to help does exactly the opposite.

Is there really any reason besides stubbornness?

**Comment by looeee** [comment]
A workaround if you are using build tooling and don't want to monkey patch built-ins is to strip out console log for your production build. For example, in Rollup there is [@rollup/plugin-strip](https://github.com/rollup/plugins/tree/master/packages/strip) or for webpack you can use [Terser](https://webpack.js.org/plugins/terser-webpack-plugin/#remove-comments).

**Comment by mrdoob** [comment]
> and 100% happiness increase of any CPU 🤔

Are you saying `console.warns()` consume CPU? Have you measured it? If so, can you share the results?

**Comment by mrdoob** [comment]
Also, the screenshot you shared has nothing to do with deprecation warnings.
Seems like misusage of the API to me 🤔

**Comment by mjurczyk** [comment]
I'm not sure if closing an issue, again, without solving it is a good practice. Workarounds aren't a solution, and it will just appear again in the future. 

@looeee Yes, I did work around it, but my point is ***why*** do we need a workaround in the first place, when a simple proxy for console solves the issue. There are other challenges in development to focus on, that's why I ask if there's any real reason besides stubbornness - I have no issue with logs, as long as they don't jam the browser when debugging.

@mrdoob 
1. There are also warnings about vector targets, just somewhere above in this 20k records (ex. `getHSL()` after last update I did). If with new version some util gets a new warning that in the future it will require new prop, or something similar, it adds more.
2. I don't think it's a misusage - rather a misinterpreted value in Three. The workaround for it was to convert all `undefined` to `null`, since the warning is triggered [exclusively by undefined values](https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L102) - the effect is the same as the value is just ignored later.
3.  As for CPU / performance jamming via the console, you can open the dev console (can be in this tab, doesn't matter) and paste:
```const i = () => requestAnimationFrame(() => { Array(60).fill(1).forEach(_ => console.warn(_)); i() }); i();```
After a few seconds you should get ~5k records - which, even if hidden, start slowing down the console. By 20k it's not usable anymore.

Once again, I 100% do realise it's an edge case of generating stuff on the go, but why do we refuse to fix it?

**Comment by mrdoob** [comment]
> 2. I don't think it's a misusage - rather a misinterpreted value in Three. The workaround for it was to convert all `undefined` to `null`, since the warning is triggered [exclusively by undefined values](https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L102) - the effect is the same as the value is just ignored later.

These properties accepted values are `null` or `Color`/`Texture`.`undefined` is not valid there thus it's a misusage of the API.

We try our best helping users with warning when they're passing invalid values wherever we can. The solution is to fix your code not to ask the library to hide the warnings. The renderer can break if you don't provide the right values.

> 3. As for CPU / performance jamming via the console, you can open the dev console (can be in this tab, doesn't matter) 

You're talking about devtools performance. If you don't open devtools `console.warn()`s do not consume CPU.

**Comment by mjurczyk** [comment]
` If you don't open devtools console.warn()s do not consume CPU.`

Ok, sorry, I'm siding with @Mugen87 there's no point in continuing the discussion.

**Comment by kylebakerio** [comment]
Man, I finally broke down and decided to figure out wtf is going on because my combination of libraries is causing my entire OS to crash when I open devtools because of a deprecation warning on a RAF call to invert() from THREE.

I've now spent hours falling down the rabbit hole of figuring out what is going on. I finally ended up reading various pull requests and issue threads to completion here.

I've finally ended up here, the most recent one as far as I can tell.

This is insane. How can such an advanced, cutting edge library have such a backwards approach to logging? I feel like I'm reading a Kafka novel going through these comments.

I'm tempted to write a bot that maintains a fork of THREE with this one change, pulling all updates and maintaining this one thing. I wonder how many people would switch over to it? I bet it would be interesting to see.

If someone else did it, you can be sure I'd switch to it. Unfortunately, I'm using A-Frame, which bundles it, but I'd still gladly include a line overwriting the built-in THREE rather than hack the console.

When I open the console, it's to do work, and choosing what goes in my console and what doesn't at any given time should be my choice. Making extra work for me (which chasing down this issue for a few hours in an attempt to fix correctly once and for all counts as, as is maintaining a hack to a built-in like console.log/warn/error) is not something I want from my libraries.

**Comment by mjurczyk** [comment]
Yes, it do be like that (and can be a bit frustrating.) While I kinda learned to live with it, I'd still opt in for creating `THREE.Console` or a similar helper that'd allow to override / disable Three using the default `console.log` 😔

**Comment by kylebakerio** [comment]
I just want to comment that that solution is not adequate. Because I have thousands of console.warn() calls per minute from THREE's deprecation warning because of one library interacting with the packaged version of THREE in another library (`aframe-physics-system` interacting with the latest `aframe`), even the seemingly 'light' check to see if 'THREE' are the first five letters of the warning being called that often incurs significant overhead.

I'm going to go ahead and fork `aframe-physics-system` and make the change myself, but if I make a pull request and they accept it, the newest version becomes incompatible with versions of A-Frame prior to the absolute latest version.

This library, `aframe-physics-system`, is depended on by other major libraries, like `aframe-physics-extras`, and `superhands` (both of which I'm using).

This situation is ridiculous.

I'm in full support of THREE.js being aggressive with their update cycle and not worrying about backwards compatibility, and of the nice convenience of being informed that old method names are being called that are being deprecated, but frankly with just a little update that many of us would be glad to contribute, THREE could have a 'deprecation warn' mode that could be flipped on or off... or just, you know, sane logging like the rest of the JS world.

I mean, this isn't trivial. Their logging is literally breaking my app. Not only is THREE the one library in the JS ecosystem that refuses to allow you to turn logging off, it's also the single noisiest library I've ever seen in JS land.

Please, @mrdoob, does hearing about a breaking app issue affect your opinion on this? Yes, console may not incur CPU (?) when the console isn't open, but people using THREE need the console open... if it breaks for developers, it's still an important breaking problem, isn't it?

**Comment by Mugen87** [comment]
> I'm in full support of THREE.js being aggressive with their update cycle and not worrying about backwards compatibility,

This is new to me...

**Comment by kylebakerio** [comment]
That's how I've heard it referred to elsewhere. I've done more reading _about_ THREE than actual diving into THREE itself--I've gone into the THREE docs only for working with positional audio stuff myself, otherwise I just use tools that rely on THREE underneath. Apologies if I was misinformed. (What I've read is that the policy in THREE is 'target one version of THREE with your app and package it with it, because we maintain the right to break things with new versions, and if we focus on taking care of prior stuff constantly the project will eventually die because that always becomes too much overhead in the long run', which I think is a perfectly reasonable approach.)

**Comment by donmccurdy** [comment]
Part of the problem with the A-Frame <-> three.js interaction here is that A-Frame is often used as a global script, and so aframe-physics-system can't have a peer dependency on a particular version of three.js. If it did, it could reasonably pin to a particular version.

We spend a lot of time maintaining backwards compatibility, trying to minimize breaking changes, documenting any breaking changes in the release notes, and maintaining warnings to help users migrate from one version to the next. Anyone saying that three.js maintainers are not worried about backwards compatibility is incorrect. That said, (a) we do not have LTS releases like some larger projects, and (b) each monthly release is semantically equivalent, and could potentially contain breaking changes. The files under `examples/{js,jsm}` are less stable than the core library.

***

If we don't want to maintain a custom logging API, how about exporting a reference to the `console` variable and letting users swap it out? This would let them change where three.js logs go without needing to monkey-patch the global `console` object. For example:

```js
// three.js
export let logger = console;
export const setDefaultLogger = (_console) => {
  logger = _console;
};

// DeprecatedLoader.js
import { logger } from 'three';
logger.warn('this loader is deprecated');

// app-with-no-logs.js
import { setDefaultLogger } from 'three';
setDefaultLogger({
  log: function() {},
  warn: function() {},
  error: function() {},
});
```

**Comment by mrdoob** [comment]
@donmccurdy I think that sounds good to me 👍 `setCustomConsole` maybe?

**Comment by gsimone** [comment]
Hi, would a PR for this be welcome?
