### ISSUE TITLE
NaNs in 3D fonts?

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#19874]
##### Description of the problem

This might not be a bug just passing it on.

I added checks for the data passed to `bufferData` and `bufferSubData` to the [webgl helper](https://github.com/greggman/webgl-helpers#webgl-gl-error-checkjs) I'm working on. If the data is a `Float32Array` then I check for NaN. 

It found some NaNs are being passed for the font geometry in [https://threejs.org/examples/webgl_camera_logarithmicdepthbuffer.html](https://threejs.org/examples/webgl_camera_logarithmicdepthbuffer.html).

##### Three.js version

- [X] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
The `NaN` values are produces for the last two very large text geometry that have a scale of `1.135e21` and `9.46e23`. `BufferGeometry.computeVertexNormals()` is not able to compute proper normal data and this produces unusable values.

A simple fix is to remove the last two labels since they are not rendered correctly anyway. I don't think there is a sensible way to fix this in `computeVertexNormals()`.
