### ISSUE TITLE
Sprites not displayed on Chrome with no hardware acceleration

### ISSUE THREAD

**Issue by filippomc** [mrdoob/three.js#19883]
##### Description of the problem

When hardware acceleration is disabled, sprites are not displayed on Chrome.

Should see a big rubber duck the following examples, while it's all black on Chrome without HA.

* [jsfiddle](https://jsfiddle.net/fledda/bwghmqrs/12/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/fledda/mhLapwsf/5/) (dev branch)

##### Three.js version

- [x] Dev
- [x] r118

##### Browser

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
No graphic card (e.g. virtualized environment) or hardware acceleration set to off on Chrome.

**Comment by Mugen87** [comment]
I bet there is a lot of more stuff that does not work if you disable hardware acceleration.

In general, the engine assume hardware acceleration  is enabled and there is no support without it.

**Comment by filippomc** [comment]
Thanks @Mugen87 for your thoughts. In my (little) experience with threejs, other basic features works quite well without hardware acceleration. The contrary may be a big limitation considering the wide use of cloud virtualized environments in the industry.

**Comment by Mugen87** [comment]
Um I do not follow this argumentation. A virtualized environment can also have GPUs.

**Comment by mrdoob** [comment]
The root of the problem is this line:

```js
sprite.scale.set(50, 50);
```
`sprite.scale` is actually a `Vector3`, so it expects 3 arguments, but you're passing 2.

That results in:

```js
sprite.scale.x = 50;
sprite.scale.y = 50;
sprite.scale.z = undefined;
```

Then, `sprite.matrix` becomes `[50, 0, 0, 0, 0, 50, 0, 0, NaN, NaN, NaN, 0, 0, 0, 0, 1]`.

Seems like SwiftShader (the renderer used when hardware acceleration is disabled) breaks when passing NaNs.

I think the solution here is to implement more default parameters:

```js
	set: function ( x = 0, y = 0, z = 0 ) {

		this.x = x;
		this.y = y;
		this.z = z;

		return this;

	},
```

Another solution would be to try to do `this.scale = new Vector2()` in the `Sprite` constructor...

**Comment by Mugen87** [comment]
Interesting! Right now, the library assumes `set()` methods are always called with all parameters. According to this policy, it's a user error.

> I think the solution here is to implement more default parameters:

I would expect that `z` would be unchanged if I call `scale.set( 50, 50 )`. With default parameters, its value is always set to `0`.

Related discussion: #17845

**Comment by filippomc** [comment]
Thanks @mrdoob you nailed it! Actually https://jsfiddle.net/fledda/bwghmqrs/13/ uses a third parameter as you suggest and works also without acceleration enabled.

**Comment by c0d1f1ed** [comment]
> Then, sprite.matrix becomes [50, 0, 0, 0, 0, 50, 0, 0, NaN, NaN, NaN, 0, 0, 0, 0, 1].
> 
> Seems like SwiftShader (the renderer used when hardware acceleration is disabled) breaks when passing NaNs.

@mrdoob I assume this is a vertex transform matrix, passed directly to the shaders as a uniform variable? For the API side, the following [spec](https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf) quote applies:
```
Any representable floating-point value is legal as input to a GL command that
requires floating-point data. The result of providing a value that is not a floating-
point number to such a command is unspecified, but must not lead to GL interrup-
tion or termination. In IEEE arithmetic, for example, providing a negative zero or a
denormalized number to a GL command yields predictable results, while providing
a NaN or an infinity yields unspecified results.
```
As for how they should be handled by [GLSL](https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf) shaders:
```
Operations and built-in functions that operate on a NaN are not required to
return a NaN as the result.
```
It's not clear to me that SwiftShader "breaks" when passing it NaNs. It's quite likely that it propagates NaNs in a more IEEE 754 recommended manner, while most GPUs treat them as zero, or inifinity, and this just-so-happens to produce a more desirable output. But it can fail at any time on GPUs or drivers that adhere more closely to IEEE 754. It would be great if someone could take a deeper look at where things start to deviate from expectations.

In any case, one should avoid NaNs to achieve reliable results.

> I bet there is a lot of more stuff that does not work if you disable hardware acceleration.
> 
> In general, the engine assumes hardware acceleration is enabled and there is no support without it.

@Mugen87 While this currently uses the OpenGL ES driver implementation, SwiftShader has a [certified](https://www.khronos.org/conformance/adopters/conformant-products#submission_403) conformant Vulkan 1.1 implementation for the CPU. If something doesn't work it's not uncommon to be an application or engine bug. If a SwiftShader bug is suspected, please [file an issue](https://g.co/swiftshaderbugs).

**Comment by filippomc** [comment]
> Um I do not follow this argumentation. A virtualized environment can also have GPUs.

@Mugen87 there's a difference of costs in cloud provisioning with hardware acceleration and may be a problem to make the upgrade for a single web application. Another difficulty is to set up a virtualized environment using a graphic card with Linux, this is not a common set up as far as my experience tells me.

**Comment by Mugen87** [comment]
@c0d1f1ed Okay, good to know. I was not aware that `SwiftShader` has this level of compliance.

@mrdoob I can't figure out a solution for changing `set()` so everybody is happy^^. I've worked with a C++ library some time ago that also provide a `set()` methods for its math classes. The respective parameters are all mandatory:

https://github.com/juj/MathGeoLib/blob/d7a41cad953907a13a1dbc87f3ecfd20b2e246cf/src/Math/float3.cpp#L774-L783

I think this policy is the best one for making a consistent behavior. However, JS allows invocating this method in a way it's not intended. I would rather suggest to put a console warning to set methods in order to warn about missing arguments than changing its semantics.

**Comment by mrdoob** [comment]
> I would rather suggest to put a console warning to set methods in order to warn about missing arguments than changing their semantics.

I can see this decision eventually propagating to the rest of the math classes.

So, do we want to

1. Add `if ( arguments.length < n ) console.warn()` everywhere?
2. Set default arguments?

Option 1 would be the nicest for the user but may uglify the code quite a bit.
Option 2 is in between; It is cleaner code but may produce confusing results but less confusing than what we may produce now.

**Comment by Mugen87** [comment]
I think I vote for option 1. IMO, default parameters are intended to ensure optional parameters have proper values. Setters or computational methods like `add()` or `sub()` have mandatory parameters the user has to provide. If this is not the case, the library is not used correctly. 

In some sense, this problem is more related to the programming language which does not allow to enforce more strict rules. Ideally, `scale.set( 50, 50 )` should not even compile. I'm not sure I would start to put `if ( arguments.length < n ) console.warn()` to every method that has mandatory arguments. Maybe just referring to the documentation is sufficient?

**Comment by WestLangley** [comment]
This is a user error. Let's not go down the path of validating args. Our policy has been not to do that.

BTW, the default value for scale should be 1, not zero.

**Comment by mrdoob** [comment]
> This is a user error. Let's not go down the path of validating args. Our policy has been not to do that.

I'm inclined to agree...

So, it would be more suitable to somehow turn `scale` into a `Vector2` in `Sprite`. But we would also need to overwrite `updateMatrix`...

> BTW, the default value for scale should be 1, not zero.

Then we would need a `ScaleVector3` that overwrites the `contructor` and `set()`...

**Comment by filippomc** [comment]
> So, it would be more suitable to somehow turn `scale` into a `Vector2` in `Sprite`. But we would also need to overwrite `updateMatrix`...

The error came from expecting to set 2 dimensions on a 2d object rather than 3: the Vector3 was unexpected there and the fact that kind of magically works on most hardware drivers is subtle.

**Comment by mrdoob** [comment]
I ended up making an exception for this case.
