### ISSUE TITLE
Remove @author from files

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#19945]
Github displays the contributors for each file so it seem like the @author info is redundant.
It's also out of date most of the time...

<img width="587" alt="Screen Shot 2020-07-28 at 5 22 09 PM" src="https://user-images.githubusercontent.com/97088/88686004-8d277f00-d131-11ea-9b01-6c18cc9b156a.png">

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/4944e56c06ed284abe11b7654348fb1ea3ac04d4

**Comment by fernandojsg** [comment]
I like the idea. I never really liked @author in the files as they were not accurate and in any case, like I'd encourage to check the contributors to the file instead of just the @author.
In any case if you want to do a more explicit ownership of files for reviews or so we could always include a CODEOWNERS (https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) but I believe currently the recommendation logic on the github suggestion for reviewers do a great job at that.

**Comment by mrdoob** [comment]
We also have this: https://github.com/mrdoob/three.js/wiki/Owners

**Comment by Mugen87** [comment]
It seems the source files in the `animation` and `extras` directory still have the author information.

**Comment by pailhead** [comment]
This is a great idea. I always saw authors as kind of the `original author who submitted the file`, this information was really confusing over the years as illustrated by the first post - out of 161 people who worked on this file, only 5 are mentioned as authors. This in turn made me feel that some authors are more equal than others :) (Orwell). This is a great improvement.

**Comment by pailhead** [comment]
>We also have this: https://github.com/mrdoob/three.js/wiki/Owners

I think github can consume `CODEOWNERS.md` or something like that as suggested above, and be more fancy when setting up PRs, ie. be more explicit.  But as mentioned, i think it does a good job of it now based on who contributed to files the most or something like that.

**Comment by Mugen87** [comment]
I vote to remove `@author` comments, too. As said above, author information is available via git.

**Comment by mrdoob** [comment]
@Mugen87 It was an easy search and replace 😇

**Comment by Mugen87** [comment]
Okay, the code base should be cleared now^^.
