### ISSUE TITLE
WebGL2 '#version 300 es' is not prepended when using RawShaderMaterials with 'defines' option

### ISSUE THREAD

**Issue by J-Rojas** [mrdoob/three.js#19959]
##### Description of the problem

When using RawShaderMaterial with the `defines` option, the `#define` definitions are prepended to the vertex/fragment program source code. However this becomes incompatible with WebGL2 shaders since the first line of these shader must be `#version 300 es`.

A proposed fix is to check for the `#version XXX` string as the first line and add the `#define` definitions after it.

##### Three.js version

- [X] Dev
- [X] r119
- [X] r118

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Did this work with `r118`? Notice that the following PR is new in `r119`. #19889

**Comment by Mugen87** [comment]
For reproduction: https://jsfiddle.net/hns8etfr/

BTW: This did not work in earlier version, too.

**Comment by Mugen87** [comment]
I guess this will be a bit hacky to solve since the engine expects that`#version 300 es` is defined in user code.

**Comment by J-Rojas** [comment]
I'm going to need a solution to this since another open source project relies on the defines to readjust the shaders dynamically, and that project can't upgrade to WebGL2 shaders without this change. 

I'll send a PR with the proposed solution: check the user program for the `#version 300 es` and append the defines after it.

**Comment by Mugen87** [comment]
I've already filed a PR: #19965

**Comment by J-Rojas** [comment]
@Mugen87 thanks for the quick work with that!

**Comment by mrdoob** [comment]
I heard that using GLSL 1 in WebGL 2 may be buggy.

So, I think it may be better if the renderer added `#version 300 es` to `RawShaderMaterial`s by default (so you don't have to). And in cases that you need GLSL 1 then you can force WebGL 1 by doing `new THREE.WebGL1Renderer()`.

Would this work?

**Comment by Mugen87** [comment]
> Would that work?

Basically yes. But since users already have `#version 300 es` in their shader code, they would have to perform a migration task. Otherwise the qualifier is added twice (which produces a shader which does not compile).  #19965 avoids a breaking change though.

**Comment by J-Rojas** [comment]
> 
> So, I think it may be better if the renderer added `#version 300 es` to `RawShaderMaterial`s by default (so you don't have to). And in cases that you need GLSL 1 then you can force WebGL 1 by doing `new THREE.WebGL1Renderer()`.
> 

@mrdoob There are more breaking changes if you add `#version 300 es` to a shader. The shader has to be migrated to support `in/out` modifiers for examples. So automatically prepending it can cause unintentional breaking changes. 
https://webgl2fundamentals.org/webgl/lessons/webgl1-to-webgl2.html

**Comment by mrdoob** [comment]
> #19965 avoids a breaking change though.

Yes, but it also complicates the code... 😕

I think it's fair to change this now even if it's a breaking change. It's pretty early days for this code path.

**Comment by Mugen87** [comment]
I've tested to always add `#version 300 es` on my system but encountered a problem. Consider the code in:

https://threejs.org/examples/webgl_buffergeometry_rawshader

It's GLSL 1 code. If the engine should enforce GLSL 3.0 for `RawShaderMaterial`, the following code must be executed otherwise shader won't compile:

https://github.com/mrdoob/three.js/blob/1213e0f8a73f6cb9e74be0c04ba6730da423c3a0/src/renderers/webgl/WebGLProgram.js#L675-L703

So the fix would be remove the `! parameters.isRawShaderMaterial` check. Do you think it's okay if this code (meaning the GLSL 1.0 to 3.0 conversion) is also executed for `RawShaderMaterial`?

**Comment by Mugen87** [comment]
Oh wait, it seems #19889 indeed had an effect. Check out this code:

`r118.3`: https://jsfiddle.net/1q3gs0a6/1/

A custom `ShaderMaterial` written as GLSL 3.0. Notice how it's required to define `outColor` since `gl_FragColor` can't be used. After #19889, two out colors are now defined which breaks the code.

`r119.1`: https://jsfiddle.net/1q3gs0a6/2/

**Comment by Mugen87** [comment]
> Hmm, the fix for that particular case should be to use new THREE.WebGL1Renderer() in the example.

Okay. So the policy would be:

- A `RawShaderMaterial` with GLSL 1.0 code has to use `WebGL1Renderer`.
- A `RawShaderMaterial` with GLSL 3.0 code has to use `WebGLRenderer` (and thus WebGL 2).

Does that sound right?

**Comment by Mugen87** [comment]
And the renderer does append `#version 300 es` to the code but performs no GLSL 1.0 to 3.0 conversion.

**Comment by Mugen87** [comment]
Updated #19965 as suggested in https://github.com/mrdoob/three.js/issues/19959#issuecomment-667036281 👍

**Comment by mrdoob** [comment]
> Does that sound right?

Yes, that's the idea. Sounds manageable to me.

**Comment by Mugen87** [comment]
Just for the record: https://github.com/mrdoob/three.js/issues/19959#issuecomment-667214812 does not work since engine code using `RawShaderMaterial` (like PMREM) needs to work with WebGL 1 and 2. Thus exclusively using GLSL 3.0 with `RawShaderMaterial` and WebGL 2 does not work. GLSL 1.0 must be also supported.

**Comment by J-Rojas** [comment]
@mrdoob and @Mugen87 could have a look at PR #20005? It should cleanly handle the prepending and solve this bug for new code changes without breaking existing code.

To summarize, for GLSL 3.0 shaders, the 'glslVersion' property of the ShaderMaterial should be set. This will apply the version string correctly to the top of the file. If it is not set, then no action is taken. It is assumed the shader code accounts for the version number in this case. This is independent of the gl version of the context so any version of GLSL can be used in the shader code.

**Comment by J-Rojas** [comment]
The Harp.gl has modified their code to support WebGL2 and they are waiting for this bug to be resolved. See [this PR](https://github.com/heremaps/harp.gl/pull/1756). Will you review and merge PR #20005 to solve this bug?

**Comment by Mugen87** [comment]
I've tested your PR in detail today and provided feedback here: https://github.com/mrdoob/three.js/pull/20005#issuecomment-674378445

Implemented the suggested code should make the PR ready to merge.
