### ISSUE TITLE
Object3D.getWorld*() should call updateWorldMatrix(true) instead of updateMatrixWorld(true) ?

### ISSUE THREAD

**Issue by shawn0326** [mrdoob/three.js#19962]
When we call Object3D.getWorld*(), we want object.parent.matrixWorld to be updated, but not it's children. is this a bug?

##### Three.js version

- [x] r118

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
I guess it makes sense to update these methods similar like `Object3D.attach()`. Meaning replacing:
```js
this.updateMatrixWorld( true );
````
with
```js
this.updateWorldMatrix( true, false );
```
Sidenote: It's in general questionable if `Object3D.getWorld*()` methods should update the world matrix each invocation. Right now, it is the only way to ensure an up to date world matrix. However, there are use cases were this computation is redundant because the transformation of the objects and/or its ancestors has not changed. The engine is currently not able to detect this (see #14138). Instead the user has to do this and extract transformations in world space differently. E.g. via:
```js
worldPosition.setFromMatrixPosition( this.matrixWorld );
```

**Comment by WestLangley** [comment]
This is a known issue. See #16292.
