### ISSUE TITLE
Unable to create/modify shader materials in editor

### ISSUE THREAD

**Issue by jespertheend** [mrdoob/three.js#20197]
##### Description of the problem

When trying to modify a shader material in the threejs editor, the changes do not actually get applied.
The following error appears in the console:
```
Uncaught ReferenceError: glslprep is not defined
    at Script.js:230
    at runInOp (codemirror.js:3182)
    at CodeMirror.operation (codemirror.js:5312)
    at validate (Script.js:145)
    at Script.js:84
```

To replicate:
- go to https://threejs.org/editor/
- add a box
- go to the material tab and select shadermaterial from the drop down  menu
- click the vertex button to start modifying the fragment shader
- change the color value in the fragment shader.

**Comment by Mugen87** [comment]
Can confirm this. Although `glslprep` was removed, there is still some usage of it.

**Comment by Mugen87** [comment]
@mrdoob The `Script` class in the editor uses `glslprep` to parse the given GLSL and check for syntax errors. Since 64f316202d9bc6812c57a7feb8fb8ab610dcd5d3 removed the library, this check is not possible anymore. There are two options now:

- Restore the library
- Remove the `glslprep` from `Script.js` and don't validate shader code anymore

**Comment by jespertheend** [comment]
To be fair I often modify shaders with the console open anyway, because if I remember correctly the editor doesn't always report every error that causes a shader to fail.

**Comment by Mugen87** [comment]
Well, in this case it's probably better to remove the usage of `glslprep`. Let me file a PR.
