### ISSUE TITLE
Decal example is not working

### ISSUE THREAD

**Issue by Ben-Mack** [mrdoob/three.js#20205]
The original decal example is not working anymore on r120: https://threejs.org/examples/#webgl_decals

Nothing happened when clicking on the object, no error reported in console.

**Comment by sciecode** [comment]
Same underlying issue as #20191. Fix PR already filed on https://github.com/mrdoob/three.js/pull/20194

**Comment by Mugen87** [comment]
@mrdoob Please let merge #20194 for now since I'm afraid it won't take long until projects hit into this issue.

**Comment by mrdoob** [comment]
@Mugen87 I'll have a look at this today. I hope we don't have to revert.

**Comment by chilmers** [comment]
I ran into similar issues with 1.2.0 where it seemed like the upgrade (probably OrbitControls) ate my mousemove events while panning (i.e. while the mouse button was down I no longer got any mousemove events).

When I changed my code to listen 'pointermove' (as the OrbitControls does) instead of 'mousemove' it started working again.
Not sure if it helps with this particular issue but it might be a clue.

Could it be that if a pointermove eventlistener is triggered, then the browser would not trigger the mousemove event for some reason since they are almost the same?

**Comment by Mugen87** [comment]
> Could it be that if a pointermove eventlistener is triggered, then the browser would not trigger the mousemove event for some reason since they are almost the same?

It's explain in the MDN: https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent

> If you use pointer events, you should call event.preventDefault() to keep the mouse event from being sent as well.

The problem is that `OrbitControls` and `TrackballControls` use `event.preventDefault()` in certain event listeners which is responsible for this breakage.

**Comment by chilmers** [comment]
I guess you are referring to this part of the doc?
> If you use pointer events, you should call event.preventDefault() to keep the mouse event from being sent as well.

I thought the event would still be propagated to my event listener since the OrbitControls isn't doing event.stopPropagation but this might explain why i got no mousemove and also why changing to pointermove worked (since I guess that one is still propagated).

Interesting, thanks!

**Comment by mrdoob** [comment]
Fixed: https://github.com/mrdoob/three.js/commit/2b477f0cca8463a4b7f81eeecf9fe53f54877b91

This also never worked on mobile before either.

**Comment by mrdoob** [comment]
Seems like in order to update to `r120`, users will need to change their mouse events to pointer events...

**Comment by marcofugaro** [comment]
@mrdoob have you considered removing the `preventDefault()` from the `pointerdown` event? I couldn't find any reason why it is there.

**Comment by mrdoob** [comment]
@marcofugaro Just because `mousedown` used to have it. I'll give it a try and test things tomorrow 👍

**Comment by mrdoob** [comment]
@marcofugaro That ended up being not the problem and I didn't pursue the investigation.
