### ISSUE TITLE
WebGL Renderer | Output of Vertex Shader `color` not read by fragment shader

### ISSUE THREAD

**Issue by shaun-scale** [mrdoob/three.js#20259]
##### Description of the problem

Describe the bug or feature request in detail.
I'm receiving very transient/rare reports of users ( < 0.001% )  experiencing WebGL crashes inside of our application.

It seems that this error message is consistently shown in the console upon a crash being observed:
![image](https://user-images.githubusercontent.com/58447835/92075357-2e2ada80-ed6d-11ea-81df-998bd33bc56e.png)

![image](https://user-images.githubusercontent.com/58447835/92075372-3551e880-ed6d-11ea-9952-24706912adb8.png)

I don't have a solid set of reproduction steps yet which is what is making this issue so hard to identify. 

##### Three.js version

0.102.1

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Output of `chrome://gpu`
[webgl_chrome_gpu.txt](https://github.com/mrdoob/three.js/files/5166402/webgl_chrome_gpu.txt)

**Comment by Mugen87** [comment]
> Output of Vertex Shader `color` not read by fragment shader

When this warning pops up, it just means that a varying is not used in the fragment shader. This is normally no reason for crashing a shader program. Nevertheless, the engine should avoid such warnings with built-in materials.

First of all, please check if this problem still exist with the latest version of `three.js`. A few things happened since `102.1`.

If the problem still occurs, please share a live example demonstrating the issue. Otherwise it won't be possible to investigate this issue.

**Comment by mrdoob** [comment]
Closing until then.
