### ISSUE TITLE
SelectionBox: Add support for pixel-perfect selection.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [mrdoob/three.js#20530]
P.S. it is not question, it is feature request for `frustum.intersectsGeometry(mesh.geometry)`

I mean not bounding box and bounding sphere, but exactly pixel perfect, I mean.

Maybe shader or special renderer? Give different colors to different meshes, and by rendered colors detect what objects were selected?

After three days of googling, I haven't found a single answer on the Internet.

For example, this Box should not be selected:

![image](https://user-images.githubusercontent.com/69426460/96425556-d1905b80-1204-11eb-9425-814808112fb3.png)

**Comment by Mugen87** [comment]
As suggested at [stackoverflow](https://stackoverflow.com/questions/64422556/how-to-select-objects-by-mouse-selection-rectangle), the official `SelectionBox` example seems sufficient to me.

https://threejs.org/examples/misc_boxselection

I understand that you would like to see `SelectionBox` pixel perfect but I'm not sure the additional complexity and overhead would be acceptable.

**Comment by MaxmaxmaximusAWS** [comment]
@Mugen87 
![image](https://user-images.githubusercontent.com/69426460/96430124-75c8d100-120a-11eb-8a74-a6042d31c2f7.png)

How does Blender do it? If I select many objects, he clearly understands what I have selected. Do you have any ideas about their algorithm?

May be we can paint objects in the scene in different colors, and render the scene, and then use the pixel colors to understand what colors are visible?

**Comment by gkjohnson** [comment]
> Maybe we can paint objects in the scene in different colors, and render the scene, and then use the pixel colors to understand what colors are visible? And so we exploit the parallel nature of the graphics card? Its like raycasting, but by every selection pixel.

This would make selection asynchronous which might not be desirable. Copying render target data from the GPU to to the CPU can also be a slow operation and will scale based on canvas size / pixel density. GPU picking for raycasting is a bit more consistent because you only need to render / copy a single pixel.

> How does Blender do it? If I select many objects, he clearly understands what I have selected. Do you have any ideas about their algorithm?

Blender may have extra underlying acceleration data structures to facilitate performant interactions like this that three.js doesn't provide out of the box. With simple geometry performance may not be all that bad though. For all the meshes you want to check selection for you could perform a triangle / selectionbox frustum intersection for every triangle in the mesh to see if it is selected. If the bounding box / sphere of a mesh is completely contained in the frustum you could skip the triangle check and just mark it as selected. Supporting all the corner cases of instanced, skinned, etc meshes may get complicated, though.

If performance turns out to be an issue you could only run the selection check when the user releases the mouse rather than on every frame. For particularly complex meshes you could use some kind of spatially indexed data structure like a quad tree or bvh which there are some libraries for.

**Comment by Mugen87** [comment]
After thinking about this issue again, I have the feeling the feature request is a bit out-of-scope. The possible solutions explained in https://github.com/mrdoob/three.js/issues/20530#issuecomment-712432533  are complex to implement and would require a lot of code, especially when all types of `Object3D` should be supported. 

I would prefer to keep `SelectionBox` simple and move a more advanced implementation to a third-party repo.

**Comment by gkjohnson** [comment]
In terms of alternatives in other projects something similar (lasso selection of individual triangles) was requested a bit ago in [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh) and I've created an example for it [here](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/selection.html). It uses the bounds tree to accelerate selection but you can disable it to see the difference in performance (ms displayed in bottom left). The core the approach involves projecting the triangles to screen space and performing the [line-crossing algorithm](https://en.wikipedia.org/wiki/Bentley%E2%80%93Ottmann_algorithm) to determine triangle intersection so you don't need an acceleration structure to implement it. If you're limiting selection to a box you can use the projected frustum shape and check every triangle, instead, which might be a bit faster / simpler.

Anyway it might be at least a start for someone looking to implement this in a project. Other relevant discussions in three-mesh-bvh issues [109](https://github.com/gkjohnson/three-mesh-bvh/issues/109) and [112](https://github.com/gkjohnson/three-mesh-bvh/issues/112).

![image](https://user-images.githubusercontent.com/734200/115592905-af959580-a288-11eb-8e5d-c1f07a5461c7.png)

**Comment by raksha1991** [comment]
@Mugen87 - I have similar issue. Could you please help? I have posted my question here:
https://discourse.threejs.org/t/three-js-improve-performance-on-drag-select/25971
