### ISSUE TITLE
AnimationGroupObject doesn't animate objects re-added after being removed with .uncache

### ISSUE THREAD

**Issue by Noobulater** [mrdoob/three.js#20555]
**Describe the bug**

When I remove an object using `AnimationGroupObject.uncache(object)` and then re-add the object using `AnimationGroupObject.add(object)` the object is no longer animated. If I do the same with `AnimationGroupObject.remove(object)` instead of `AnimationGroupObject.uncache(object)` the object does reanimate

***Live example***
https://jsfiddle.net/noobulater/71y6sakv/30/

**Expected behavior**

I expect my model to re-animate

**Comment by Noobulater** [comment]
https://jsfiddle.net/noobulater/71y6sakv/34/

When I add another model, the original model will resume animation as expected. Can anybody clarify why this might be happening?

**Comment by Mugen87** [comment]
The problem is that the logic in `uncache()` seems not to work properly if only a single object is used with `AnimationGroupObject`. 

At first sight, this use case does actually not make sense anyway since you can directly pass the 3D object to the animation mixer. What is your use case for using just a single object with `AnimationGroupObject`?
