### ISSUE TITLE
composer render drop fps after upgrade to r120

### ISSUE THREAD

**Issue by mshamaseen** [mrdoob/three.js#20607]
**Describe the bug**

I was using r112 and everything was ok, after upgrading to r120 I noticed a huge drop in fps when using composer render rather than the normal render.

there are 7 objects, 2000 instanced objects.

I know that 2000 sounds a big number, but it works well with normal rendering, and it was working well too in composer renders in r112!

***Live example***

https://jsfiddle.net/xuqws0Lg/

you can switch between composer render and normal render in the animate function to see the diff

**Expected behavior**

the expected behavior is that the composer renders in the same performance as normal render do.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: r120

**Comment by Mugen87** [comment]
`r112`: https://jsfiddle.net/jd3xcu7h/1/
`r122`: https://jsfiddle.net/jd3xcu7h/3/

When I change the view so I can see all objects, I have 12 FPS in both fiddles using post processing.

Have you considered to use `InstancedMesh`?

> the expected behavior is that the composer renders in the same performance as normal render do.

This is unrealistic since the additional passes produces a certain amount of overhead.

**Comment by mshamaseen** [comment]
@Mugen87 strange, I am sure that it was working before on 60 fps, I just upgraded three js and changed the objects, may that because the new objects have more than one material in every object?

and can `InstancedMesh` be used for objects with multiple materials on it (even multiple meshes on the object)?

I am now using object.clone() to clone the primary object, I don't think that makes a new material, isn't it?

**Comment by RemusMar** [comment]
> may that because the new objects have more than one material in every object?

Yes.
More materials per object ---> more draw calls ---> more processing power needed

p.s.
I didn't notice any FPS drop from r112 to r122

**Comment by Mugen87** [comment]
> and can InstancedMesh be used for objects with multiple materials on it (even multiple meshes on the object)?

All instances of an `InstancedMesh` share the same material. 

> I am now using object.clone() to clone the primary object, I don't think that makes a new material, isn't it?

Correct. `Object3D.clone()` reuses the same material and geometry. However the more objects you clone, the more render calls you have which is a usual root cause for performance issues. When devs use `Object3D.clone()` to put multiple copies of the same object in the scene, its usually a good use case for `InstancedMesh`.

Please use [forum](https://discourse.threejs.org/) if you need more help in this context. This issue will be closed since no bug or performance regression was demonstrated.

**Comment by mshamaseen** [comment]
@Mugen87 in order to enhance the FPS I made only the object that I currently need visible, the rest I set visible = false, but that didn't enhance the FPS!
then I set the visibility of all objects to false, but also the composer rendering is refusing to enhance, looks like the calculation are made on objects even if they are not visible.

please recheck it from here
https://jsfiddle.net/bzdL4qga/3/

**Comment by Mugen87** [comment]
The mentioned post-processing performance issue is a duplicate of #20401.
