### ISSUE TITLE
Safari 14 Rendering Issue

### ISSUE THREAD

**Issue by santiagojerez** [mrdoob/three.js#20670]
We have implemented Three.js in a web project successfully. The model, the textures and the meshes render correctly on Chrome,Firefox, Opera and older versions of Safari but not on Safari 14. 

- We load our model using GLTF files exported from Blender.
- The web app is written in React.
- Using react-three-fiber (https://github.com/pmndrs/react-three-fiber)

**To Reproduce**

1. Go to https://www.versanthealthoe.com/
2. Click on 'Start the experience' once the button gets enabled.
3. Move yourself around the model and will notice flicks on some textures (see video attached)

***Live example***

* https://www.versanthealthoe.com/

**Expected behavior**

The movement should be smooth, similar to other browsers.

**Screenshots**

[three1.mov.zip](https://github.com/mrdoob/three.js/files/5524066/three1.mov.zip)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Safari 14
 - Three.js version: 0.121

**Comment by Mugen87** [comment]
It's better to report such browser issues to the actual browser vendor.  In such cases, there is usually nothing we fix on engine level.

In any event, I can reproduce the rendering issues with Safari 14. Even with Safari Technology preview with enabled WebGL 2.

Looking at the issue, it's seems to me the flicker is precision related z-fighting. It disappears when I move the camera closer to the affected objects. Decreasing the size of your camera's view frustum might mitigate the issue. You can do this by lower the `far` value of the camera.

Since you have not demonstrated a `three.js` bug, this issue will be closed. Please use the [forum](https://discourse.threejs.org/) if you need more help. This can be reopen if a `three.js` bug can be demonstrated.
