### ISSUE TITLE
SSAARenderPass affects color and contrast when increasing the sampleLevel

### ISSUE THREAD

**Issue by Fluqz** [mrdoob/three.js#20681]
**Describe the bug**

SSAARenderPass will affect color on dark materials. I suppose it should only do antialiasing. Using the gammaCorrection as well, increases the effect drastically.
The problem seems to be the sampleLevel property. When set to 1, it is not noticable, but when increasing the value, pretty fast contrast increases as well

**To Reproduce**
https://jsfiddle.net/em3crz91/2/

```
  SSAA = new THREE.SSAARenderPass(scene, camera, 0x000000, 0);
  SSAA.sampleLevel = 4;
```

**Expected behavior**

Should not affect any color or material. Its for antialiasing only

 - Device: Desktop
 - OS: Windows, MacOS
 - Browser: Chrome, Firefox, Safari
 - Three.js version: r122

**Comment by mrdoob** [comment]
Please, use the provided template for reporting bugs.

**Comment by Mugen87** [comment]
This precision related issue is caused by render target's default texture type . You can mitigate the issue by strictly using `THREE.FloatType`. Check out the difference here:

https://jsfiddle.net/wh9kojde/

This issue was also discussed at the forum: https://discourse.threejs.org/t/effect-composer-gamma-output-difference/12039

**Comment by Fluqz** [comment]
https://discourse.threejs.org/t/ssaa-gammacorrection-dark-colors-issue/15321/11

**Comment by gkjohnson** [comment]
@Mugen87 Should the SSAAPass example be updated to use a float type rendertarget, then?

**Comment by Mugen87** [comment]
Floating point render targets might not be necessary for all use cases. In context of depth textures, we also use not the best quality texture type but the one with the broadest support (`UnsignedShortType`). So for now, I would keep the example as it is.

**Comment by gkjohnson** [comment]
@Mugen87 

I'm just suggesting that the [SSAARenderPass example](https://threejs.org/examples/?q=saa#webgl_postprocessing_ssaa) may be a bit misleading. It side steps this problem a bit by using a textured mesh basic material whereas this issue is most prominent with rendering that has smooth gradients. The examples should demonstrate the best practices for common use cases, no? Here's what the example looks like using a lit sphere and different gradient levels:

| 4 samples | 8 samples | 16 samples | 32 samples |
| --- | --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/734200/100182699-19547380-2e92-11eb-8846-c9411bffa51d.png) | ![image](https://user-images.githubusercontent.com/734200/100182705-1e192780-2e92-11eb-80fa-89aaac350716.png) | ![image](https://user-images.githubusercontent.com/734200/100182714-22dddb80-2e92-11eb-8117-71f404920120.png) | ![image](https://user-images.githubusercontent.com/734200/100182723-27a28f80-2e92-11eb-8ffc-a2d72e47cd2b.png) |

Using a float type or a half float type fixes this issue (unsigned short type seems to fail here). Alternatively there's an `unbiased` flag that seems to mitigate the issue with 8 bit buffers, as well:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/postprocessing/SSAARenderPass.js#L115-L124

**Comment by gianoseduto** [comment]
> This precision related issue is caused by render target's default texture type . You can mitigate it by strictly using `THREE.FloatType`. Check out the difference here:
> 
> https://jsfiddle.net/wh9kojde/
> 
> This issue was also discussed at the forum: https://discourse.threejs.org/t/effect-composer-gamma-output-difference/12039

The solution in the fiddle present the same problem I am experiencing right now with SSAARenderPass: it makes all the scene white if active, even with low sample value. I don't understand why and how to fix it, the [example]( https://threejs.org/examples/?q=ssaa#webgl_postprocessing_ssaa) seems to be workink, am I missing something?

I redefined a renderTarget with `type: FloatType` but nothing changed.
