### ISSUE TITLE
Failed to execute 'linearRampToValueAtTime' on 'AudioParam'

### ISSUE THREAD

**Issue by admazzola** [mrdoob/three.js#20718]
What in the world causes this error on the .animate() method ?  :(
  "three": {
      "version": "0.120.1",
      "resolved": "https://registry.npmjs.org/three/-/three-0.120.1.tgz",
      "integrity": "sha512-ktaCRFUR7JUZcKec+cBRz+oBex5pOVaJhrtxvFF2T7on53o9UkEux+/Nh1g/4zeb4t/pbxIFcADbn/ACu3LC1g=="
    },

Failed to execute 'linearRampToValueAtTime' on 'AudioParam': The provided float value is non-finite.
    at AudioListener.updateMatrixWorld (three.module.js?5a89:42648)
    at Object3D.updateMatrixWorld (three.module.js?5a89:6982)
    at Scene.updateMatrixWorld (three.module.js?5a89:6982)
    at WebGLRenderer.render (three.module.js?5a89:25548)
    at VueComponent.animate (GameCanvas.vue?9d0d:614)

**Comment by Mugen87** [comment]
We are not able to investigate this issue with a live example demonstrating it.

**Comment by mrdoob** [comment]
Please use the provided template when reporting bugs.

**Comment by cjbailey** [comment]
I get this too, whenever I change the volume on my laptop.  Very odd.

Did anyone ever get to the bottom of it?

**Comment by Mugen87** [comment]
I was never able to reproduce the issue. Without debugging, it's hard to find out what's going wrong...

**Comment by cjbailey** [comment]
Okay, so as far as I can tell there seems to be something odd going on in AudioListener.updateMatrixWorld.

When I change the volume on my laptop it fails in AudioListener on the following line:

`listener.positionX.linearRampToValueAtTime( _position.x, endTime );`

Because _position.x is NaN.... in fact matrixWorld appears to have all elements set to NaN...

`this.matrixWorld.elements
(16) [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]`

And this seems to be only after it calls "super.updateMatrixWorld" and not before, so I'm guessing something going on in there.

The other oddity is that it only occurs when I use the hardware volume button (or media key) and not if I change the volume using the software slider..... AND.... only when I've requested pointer lock?!!?!?

I'll keep digging to see if I can get to the root of it, but any thoughts in the meantime?

**Comment by cjbailey** [comment]
p.s. it occurs in both Chrome and Edge.  Not tried Firefox.

I'm just baffled as to how the volume buttons are causing matrixWorld to become invalid.  Utterly bizarre... and could very well not be an issue with Three.js directly.... would still like to get to the bottom of it though.

**Comment by Mugen87** [comment]
> I'm just baffled as to how the volume buttons are causing matrixWorld to become invalid.

If `NaN` values are responsible for the glitch, it's important to find out at which point in your code base a computation fails. I suspect the matrix is produced by `Matrix4.compose()` which works on an invalid `position`, `quaternion` or `scale` property. You probably want to set a breakpoint in `Matrix4.updateMatrix()` and then check the call hierarchy for issues.

**Comment by cjbailey** [comment]
![image](https://user-images.githubusercontent.com/3026800/177656223-1321a9dd-a5e8-4dd2-bd19-e77ee1eac91a.png)

So, apparently, the hardware volume buttons on a Surface Book 2 trigger the "mousemove" event?!?!  
It's inside this event that I'm setting pitch and yaw based on the mouse movement... which of course is non-existent since it wasn't the mouse that triggered the event.  The pitch and yaw is later used in a Matrix4.compose which explains where the NaN comes from.

Crazy!

**Comment by mrdoob** [comment]
> So, apparently, the hardware volume buttons on a Surface Book 2 trigger the "mousemove" event?!?!

😂
