### ISSUE TITLE
FlatShading materials are rendered strange on orthographic camera with large zoom.

### ISSUE THREAD

**Issue by bianyunzhi95** [mrdoob/three.js#20806]
https://jsfiddle.net/57nvgdhr/15/

flatShaded materials are rendered strange on orthographic camera with large zoom.
I found that it happens with orthographic camera with large zoom. Could you tell me what the origin of this issue is and how we can fix this, please? 

Thank you.

**Comment by Mugen87** [comment]
This could be a precision related issue which causes issues with other materials, too. E.g. I see the same artifacts when using `MeshPhongMaterial`.

It's best if you try to avoid large view frustums e.g. by scaling the scene down. Also avoid large zoom values as a workaround. Since this is not fixable with a logarithmic depth buffer, I doubt there is an obvious solution.
