### ISSUE TITLE
Add opacity attribute to vertices

### ISSUE THREAD

**Issue by chubei** [mrdoob/three.js#20846]
**Is your feature request related to a problem? Please describe.**

In our project we have a mesh generated on the fly and wish to make it partially transparent. The easiest way to do this seems to be adding an opacity attribute to the vertices.

**Describe the solution you'd like**

I drafted an implementation [here](https://github.com/chubei/three.js/tree/opacity). But it breaks backwards compatibility of THREE.Geometry. It’s not intended to be merged as is. Just a POC.

**Describe alternatives you've considered**

Of course we can use alpha map for transparency, only that in our case it’s not trivial to generate texture coordinates and texture in real-time.

**Additional context**

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/14008 and https://github.com/mrdoob/three.js/issues/16403 for more information on this, you may want to comment on the latter. I suspect that if this feature were added to the library, it would use the 4th component of the vertex color attribute, rather than a new attribute. It may also targeted to the recommended BufferGeometry class rather than Geometry.

> Of course we can use alpha map for transparency, only that in our case it’s not trivial to generate texture coordinates and texture in real-time.

You might consider [generating a 256x1 greyscale gradient](https://github.com/donmccurdy/glTF-Transform/blob/490db1cdaa16b4493874cd2d62871c4af72f4adb/packages/lib/src/ao.ts#L24-L31). Then your model's vertex UVs can simply be...

- `0.5,1` for `alpha=0.5`
- `0.6,1` for `alpha=0.6`
- `0.7,1` for `alpha=0.7`, etc.

... no need to generate a real UV unwrapping. 🙂

**Comment by mrdoob** [comment]
Actually, adding `opacity` as a supported `BufferGeometry` attribute sounds like an interesting idea. Other options I was thinking was adding a `color4` attribute, but `opacity` seems simpler.

@chubei would you like to do a PR with your changes? Don't worry about supporting `THREE.Geometry` I'm planning on removing it from core this month.

**Comment by donmccurdy** [comment]
@mrdoob I'm OK with the `opacity` idea, but note that it will load slower in GLTFLoader than other attributes, because we'd need to iterate over all vertices copying from `color.a` -> `opacity`.

**Comment by mrdoob** [comment]
Ah... GLTF stores alpha for vertex colors? Always?
If so maybe the `color4` approach would be better? Or `coloralpha`, `coloropacity`, ...

**Comment by donmccurdy** [comment]
If the file contains per-vertex alpha, that information will always be in the `.a` channel of a vertex color attribute. This saves space, since vertex attributes have to align with 4-byte boundaries anyway, and reduces the total number of vertex attributes consumed.

That said, most glTF files containing vertex colors contain only color, and not alpha, information.

**Comment by donmccurdy** [comment]
Why a new name, and not reuse `color`? Is that for user clarity, or so we can detect when the alpha is there? I was thinking `attribute.itemSize === 4` would be enough.

**Comment by chubei** [comment]
I wasn’t aware of the attribute alignment requirement. As @donmccurdy suggested, we can use the same attribute name for both rgb and rgba, with a shader macro as the switch. This looks better to me.

This way the users have to ensure that their material flags are consistent with the data in geometry. Is this what you’re worrying about? @mrdoob

**Comment by mrdoob** [comment]
> Why a new name, and not reuse `color`? Is that for user clarity, or so we can detect when the alpha is there? I was thinking `attribute.itemSize === 4` would be enough.

Oh, that's true. Much simpler!
