### ISSUE TITLE
Geometry does not update if Material.wireframe === true

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#20933]
**Describe the bug**

When updating a geometry's index buffer using `setIndex` the new geometry does not update if material.wireframe = true. It updates correctly if wireframe = false.

**To Reproduce**

- Create a mesh with a geometry and material with wireframe set to true
- Render the mesh once
- Change the geometry's index buffer using `setIndex`
- Render the geometry again
- Geometry is not updated

***Code***

```js
geometry = new THREE.PlaneBufferGeometry( 0.2, 0.2, 1, 1 ).toNonIndexed();    
material = new THREE.MeshBasicMaterial( { side: 2, wireframe: true } );

geometry.setIndex( [ 0, 1, 2 ] );
setTimeout( () => {
    
  geometry.setIndex( [ 3, 4, 5 ] );
    
}, 1000 );
```

***Live example***

https://jsfiddle.net/fqx1mp3a/

_NOTE: Set wireframe to `false` to see the expected behavior (updated geometry renders)._

**Expected behavior**

The geometry is rendered with the updated index buffer whether or not wireframe is true.
**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r123

**Comment by mrdoob** [comment]
Have you tried without the `.toNonIndexed();`?

**Comment by gkjohnson** [comment]
Same thing happens:

```js
geometry = new THREE.PlaneBufferGeometry( 0.2, 0.2, 1, 1 );
material = new THREE.MeshBasicMaterial( { side: 2, wireframe: true } );

geometry.setIndex( [ 0, 1, 2 ] );
setTimeout( () => {
    
  geometry.setIndex( [ 1, 2, 3 ] );
    
}, 1000 );
```

**Comment by Mugen87** [comment]
As a workaround, do not use `setIndex()` twice, see https://jsfiddle.net/vkqLecdm/.

I've assumed first that it is a regression because of the VAO change. But it does not work with older `three.js` version, too. E..g `r110` shows the same behavior: https://jsfiddle.net/9c81k470/

**Comment by Mugen87** [comment]
Okay, I think I can implement a fix however it feels a hacky. The problem is this code in `WebGLGeometries`:

https://github.com/mrdoob/three.js/blob/bdedccfcef3f22de66912a3030e67ac763933223/src/renderers/webgl/WebGLGeometries.js#L185-L189

It only compares versions to decide whether an update is necessary or not. If you exchange the index, it has the same version as before. And thus no update of the wireframe's index.

So it would be necessary to track which buffer attribute is the data source for the wireframe's index attribute. You have then the version comparison AND an additional check to test for a new attribute. However this only works if we store the reference to the index in a new weak map.

@mrdoob Do you want this additional complexity for this use case? Or should we state that it's required to update the existing index  buffer? The latter one is my preference.

**Comment by gkjohnson** [comment]
Thanks for the work around @Mugen87  -- the index I'm using dynamically changes so I've decided to just preallocate a large buffer and change the indices and draw range whenever it needs to be updated for now.

I understand where the issue is now. It seems problematic to just check the version of an attribute without also verifying that it's the same attribute as before and seems like not a robust pattern. Some way to guarantee that the version is globally unique would help rather than having version numbers increment per attribute. A random number or global version index would do the trick. `version` could be set to the global version on update and on instantiation of the buffer:

```js
let globalVersion = 0;

// BufferAttribute.needsUpdate

set needsUpdate() {
    globalVersion ++;
    this.version = globalVersion;
}
```

I don't know enough about the internal workings of buffer attribute updates but at a high level this seems like it could work? Are immediately sequential, 0-indexed versions relied on anywhere? This seems like a problem that could crop up elsewhere, as well.

**Comment by Mugen87** [comment]
The pattern:
```js
geometry.setIndex( [ 0, 1, 2 ] );
setTimeout( () => {
    
  geometry.setIndex( [ 3, 4, 5 ] );
    
}, 1000 );
```
is problematic for another reason. Since WeakMaps are internally used, there should be a memory leak however the correct and recommended approach would be to use `dispose()` before using `setIndex()` again. When looking at the examples and the previous usage of `setIndex()`, it's not intended to call this method multiple times but just once (and then update the existing attribute if necessary).

Apart from that, I'm not sure introducing a global version counter is appropriate just to solve this use case. If not more users run into this issue, I tend to consider it as a `Won't fix`. Besides, your current solution is actually the recommended approach for working with buffers that vary in size.

**Comment by gkjohnson** [comment]
> Since WeakMaps are internally used, there should be no memory leak however the correct and recommended approach would be to use dispose() before using setIndex() again. 

There's no `dispose` function on `BufferAttribute`, though. Are you suggesting disposing the entire geometry? It can be an expensive operation to reupload it if the geometry is large so it doesn't seem like a great recommendation. I recall in the past that the `BufferAttribute.setArray` function for resizing the buffer was removed with the recommendation being to instead just create a new `BufferAttribute` so it's been recommended in the past to replace buffer attributes like this.

I understand if this is a bug that can't / won't be fixed immediately because it just affects the wireframe material but disposing of the geometry doesn't seem like a great recommendation. The resizing of the buffer is a find (and better) workaround for now. And I know it's best to explicitly dispose of the geometry / buffer attributes where possible but we rely on the garbage collector for a lot of things and it should be up to the user to rely on that behavior or not depending on the situation considering the project is built with the GC in mind.

Hopefully these types of issues can be addressed with a WebGPURenderer! Thanks!

**Comment by Mugen87** [comment]
It was planned to introduce `BufferAttribute.dispose()`. Since VAOs are used, however, it becomes much harder to introduce this feature, see https://github.com/mrdoob/three.js/pull/17063#issuecomment-737993363. So you actually have to work on geometry level.

> Hopefully these types of issues can be addressed with a WebGPURenderer! 

The won't be 100% flexibility since certain information about the vertex buffers are part of the render pipeline descriptors. E.g. when you add a new attribute, you also need a new render pipeline descriptor. Ideally, you manage your geometries in a way to avoid this operations as much as possible.

**Comment by Mugen87** [comment]
Closing. As stated above using `setIndex()` multiple times to update the values of an index is a user error. The only valid approach is to update the _existing_ index. If the range of data varies over time, it's the responsibility of the application to allocated large enough buffers in the first place and use `drawRange` to define the effective drawing range of the geomtry.
