### ISSUE TITLE
three.js 124版本加载FBX异常

### ISSUE THREAD

**Issue by ghlhj** [mrdoob/three.js#21037]
异常信息：THREE.FBXLoader: Cannot find the version number for the file given.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. This log is an error usually caused by wrong backend configurations.

https://discourse.threejs.org/t/three-fbxloader-cannot-find-the-version-number-for-the-file-given/9262
https://stackoverflow.com/questions/57042206/fbxloader-cant-find-version-number-of-fbx-file
