### ISSUE TITLE
Getting "WEBGL_depth_texture" has stopped working 

### ISSUE THREAD

**Issue by fahadm** [mrdoob/three.js#21092]
**Describe the bug**
I updated from version 117 to 124, it seems that renderer.extensions.has("WEBGL_depth_texture") and renderer.extensions.get("WEBGL_depth_texture") always returns false.

Last working version : r117.
(working r117 : https://jsfiddle.net/xmptg1c7/3/) and stopped working in r118 (https://jsfiddle.net/xmptg1c7/4/)

**To Reproduce**
Try accessing the depth texture extension

1. Open the fiddle (https://jsfiddle.net/xmptg1c7/1/)
2. See the error in the console

***Code***

```js
renderer = new THREE.WebGLRenderer();

depth_texture_support = renderer.extensions.get("WEBGL_depth_texture");
if (!depth_texture_support)
{
  console.log("No Depth texture support");
}
...
```

***Live example***
(on r124)
https://jsfiddle.net/xmptg1c7/1/
**Expected behavior**
The depth texture extension should be available, as it was in the previous versions (<= 117) of three.js.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: r124

**Comment by Mugen87** [comment]
Since `r118` `three.js` uses by default a WebGL 2 rendering context. That means depth textures are available by default and there is not need to use an extension.

When using [WebGL1Renderer](https://threejs.org/docs/index.html#api/en/renderers/WebGL1Renderer), the fiddle works as expected: https://jsfiddle.net/3yufcm0L/

**Comment by fahadm** [comment]
Thank you for the quick reply I should have read the documentation more closely.
