### ISSUE TITLE
Meshstandardmaterial and lightmaps

### ISSUE THREAD

**Issue by PaulMitch** [mrdoob/three.js#21121]
If I add a lightmap to my standardmaterial then the envmap still appears to light that mesh

1 Create a simpe screne in blender lit by a HDR
2 Bake out lightmaps for that scene to use in Three JS
3 Load the screne and HDR using Three JS. Add the baked lightmap to the scenes standard material.
4 Observe that the envmap is still lighting the scene as well as providing reflections

Expected result is that the lightmap should be the only thing lighting the scene and the envmap used for reflections only.

**Comment by Mugen87** [comment]
Sorry, but implementing light maps that way would not be correct. Light maps are additive to the total (indirect) diffuse light. Using them does not mean other parts of the lighting equation are canceled out.

**Comment by daniele-pelagatti** [comment]
This issue is more complicated than it might seem. 

@Mugen87 I'd like to add a use case scenario and ask for a possible solution. 

I model a scene in blender, add an HDR background, bake the lightmaps using the nice image based lighting provided by blender and export everything to a gltf scene. 

Now back in threejs, I import the scene and apply the lightmaps: all good! Metallic materials have no reflections though. 

I convert my original hdr (which I used in blender to bake light) into a cubemap and set it as envMap in threejs: wrong result.

The envMap was already used by blender in order to bake lights and its contribution is already accounted for in the lightmaps. I only want it to provide reflections to my metallic objects and I don't want it to add more (duplicate) light to the scene.

How do you propose we solve this problem?

Anyway, thanks for all the work you guys did in threejs, this is just a use case of like to be addressed.

**Comment by mrdoob** [comment]
@daniele-pelagatti would setting `envMapIntensity` to 0 in the relevant materials work?

**Comment by daniele-pelagatti** [comment]
> @daniele-pelagatti would setting envMapIntensity to 0 in the relevant materials work?

Well no, not exactly: as far as I understand setting `envMapIntensity: 0`  would prevent the relevant materials from having metallic envMap reflections. What I would like to achieve is completely the opposite.

I have a scene which I illuminated with IBL in blender, this scene uses PBR materials and metals do reflect the environment, now I bake the lightmaps and export the GLTF.

Now I'd like to import said scene in threejs , apply my lightmaps (which already contain the IBL illumination result + secondary light bounces etc), and apply the same envMap I used to bake to these PBR materials so they reflect the environment.

See, I think here the problem is the definition of Lightmaps. In my opinion Lightmaps can be baked in many ways and can have many uses, among witch (as far as I understand):

- **shadows only**, [like in your example](https://threejs.org/examples/webgl_materials_lightmap.html), in which case IBL illumination from threejs envMaps makes sense. Lightmaps are only used to "darken" some parts of a mesh. 
- **indirect lighting + shadows** in which case IBL illumination from the threejs envMaps still makes sense, I guess? in which case Lightmaps are used to (in addition to provide shadows) add indirect lighting to static meshes.
- **complete lighting**, in which case the lightmaps were rendered with direct + indirect lighting, all baked: envMap EXR/HDR was **already** used as a source of light in the baking phase. It shouldn't add its own lighting in threejs but only provide reflections (IMHO)

Let me know if this makes sense

**Comment by mrdoob** [comment]
@daniel-nth Hmm, sound like `MeshBasicMaterial` may do the trick?

**Comment by mrdoob** [comment]
@daniele-pelagatti Hmm, sounds like `MeshBasicMaterial` may do the trick?

**Comment by daniele-pelagatti** [comment]
I prepared a reproducibility case for this, it might be simpler to just show what I'm talking about.
[Here is the scene I want to replicate from blender to threejs with the help of lightmaps](https://monogrid-deliveries.s3.eu-central-1.amazonaws.com/threejs-lightmaps-repro/render_blender.png)

Both the car and the ground are MeshStandardMaterials with albedo+roughness+metalness+normal+AO, textures are in KTX but I assure you the result doesn't change with normal PNG or JPG textures.

I baked the lightmaps [here](https://monogrid-deliveries.s3.eu-central-1.amazonaws.com/threejs-lightmaps-repro/Lightmaps_sdr/car_denoised.png) and [here](https://monogrid-deliveries.s3.eu-central-1.amazonaws.com/threejs-lightmaps-repro/Lightmaps_sdr/ground_denoised.png) in blender, I used [The Lightmapper](https://github.com/Naxela/The_Lightmapper) which is excellent.

[The whole reproducibility ZIP (blender scene, textures, lightmaps, etc) is here.](https://monogrid-deliveries.s3.eu-central-1.amazonaws.com/threejs-lightmaps-repro/repro.zip)

[My first try was something like this, using the original shaders from threejs](https://monogrid-deliveries.s3.eu-central-1.amazonaws.com/threejs-lightmaps-repro/original.html), as you can see, the ground is very washed out and the shadow from the car is very faint.

I realized that the envmap I loaded (same one used in the blender scene) was adding its own lighting to a scene which was, in theory, already illuminated (baked).

[I then tried to lower the endMapIntensity but with no real success](https://monogrid-deliveries.s3.eu-central-1.amazonaws.com/threejs-lightmaps-repro/original_tentative_fix.html), the shadows were still very faint and the glare from the reflections were fainter too.

I then tried to modify the thereejs shaders and I ended up commenting line 21 in `lights_fragment_maps.glsl.js`
```
iblIrradiance += getLightProbeIndirectIrradiance( /*lightProbe,*/ geometry, maxMipLevel );
```
[This is the result](https://monogrid-deliveries.s3.eu-central-1.amazonaws.com/threejs-lightmaps-repro/index.html), I multiplied the `lightmapIntensity` by 4 for some reason as the scene was  originally much darker and if I raise the `toneMappingExposure` the background gets washed out.

I also added some code that dampens the `reflectedLight.indirectSpecular` component in the MeshBasicMaterial based on the brightness of the lightMap: it is similar to the code used in `aomap_fragment.glsl.js` where the indirectSpecular is modulated by the ambientOcclusionMap so that reflections do not appear (for example) under the car.

Bear in mind this absolutely far from ideal or perfect but it still accomplishes a closer result to the original blender scene.

My point is: 

- MeshBasicMaterial is not what I want, I want the full PBR material that reacts to (eventually) also dynamic lights that I add to the scene.
- Lowering envMapIntensity sort of solves something but it is not the ideal solution

The concept here is to **completely delegate** the responsibility of lighting a scene to the lightmaps and, if present, an envMap **should not add light again**, that light was already baked in the lightmap.

I know this could be probably considered an edge case but I think this workflow opens the door to very nice pre-baked scenes with PBR materials, realtime shadows on top of the baked ones, etcetera.

Lightmaps are very powerful but I cannot find a good use case of the current threejs implementation.

**Comment by ramirofages** [comment]
Sorry to revive this, but is this possible now? I just got stuck with the same issue, I want light contribution only from the lightmaps, and use the cubemaps for reflections only
