### ISSUE TITLE
Implementing the ability for the Textureloader to load MediaStream object

### ISSUE THREAD

**Issue by asarra** [mrdoob/three.js#21222]
**Is your feature request related to a problem? Please describe.**

My problem is that I want to replace the texture of my imported 3D model's plane with a livestream of a window.

I figured out how to do a livestream with MediaStream and assign it to video.srcObject.

**Describe the solution you'd like**

All I need to find is a way to make the textureloader load from this Stream object.

**Describe alternatives you've considered**

I've considered creating an image every second and then loading it and doing in a loop for every second but that would be very inefficient.
Take too long and unnecessary hard disk  operations.

Then I thought about doing it in the RAM itself, but the loader doesn't support that if I read the documentations correctly.

**Additional context**

**Comment by Mugen87** [comment]
Seems you want to use [VideoTexture](https://threejs.org/docs/index.html#api/en/textures/VideoTexture). 

Since you want to apply a stream as a texture, I suggest you study how `VideoTexture` is used in combination with the video feed of a webcam in this official example.

https://threejs.org/examples/webgl_materials_video_webcam

BTW: All loaders in the repository are downloading an asset at once and then fire the `onLoad()` callback. This is not something you want to do with a stream. It was considered once to add a `VideoTextureLoader`(see #14298) but too many conceptual issues blocked the addition.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you have questions about `VideoTexture`.
