### ISSUE TITLE
Make Release Version More Obvious in Build Output

### ISSUE THREAD

**Issue by gbroques** [mrdoob/three.js#21274]
**Is your feature request related to a problem? Please describe.**

~~Currently in the [build output](https://threejs.org/build/three.js) (e.g. `three.js`), there's no way to tell what the version of three.js is.~~

**EDIT:** Currently in the [build output](https://threejs.org/build/three.js) (e.g. `three.js`), it's not immediately obvious what the release version or "revision" is.

**Describe the solution you'd like**

I would like to see some version information included at the top of [the source file](https://threejs.org/build/three.js).

```js
// threejs.org/license
// version: 0.125.2
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
        ...
```

For example, we could reference `version` in `package.json` at the time of the build.

An example proposal would be in [utils/build/rollup.config.js](https://github.com/mrdoob/three.js/blob/r125/utils/build/rollup.config.js#L258-L270):

```js
import pkg from "../../package.json";

...

function header() {

	return {

		renderChunk( code ) {

			return (
                             '// threejs.org/license\n' +
                             `// version: ${pkg.version}\n` +
                             code
                        );

		}

	};

}
```

**Describe alternatives you've considered**

We could potentially use information from git like the latest tag or commit hash.

There may be a Rollup plugin we can include for this purpose:
https://www.npmjs.com/package/rollup-plugin-version-injector

The point is to include some indication of the version in the build output `.js` file.

Any thoughts on this?

**Comment by Mugen87** [comment]
> Currently in the build output (e.g. three.js), there's no way to tell what the version of three.js is.

That's not entirely true. There the following line which is also present in the build files.

https://github.com/mrdoob/three.js/blob/350f0a021943d6fa1d039a7c14c303653daa463f/src/constants.js#L1

**Comment by gbroques** [comment]
> > Currently in the build output (e.g. three.js), there's no way to tell what the version of three.js is.
> 
> That's not entirely true. There the following line which is also present in the build files.
> 
> https://github.com/mrdoob/three.js/blob/350f0a021943d6fa1d039a7c14c303653daa463f/src/constants.js#L1

Nice! I did not realize that. Thank you for pointing this out.

Then this proposal becomes to make this more obvious by including it at the top. :)

I can close if we don't feel like there's a ton of value in this.

**Comment by gonnavis** [comment]
Maybe add an alias `VERSION = REVISION` or include a comment such as `export const REVISION = '125'; // VERSION` will be more useful. I also worked hard to find the version number at the beginning.

**Comment by Mugen87** [comment]
Changing the position of the mentioned line in the build file is problematic since you normally have no control how the build tool merges your code together. And since the build config is already complex, I do not vote to change something to accommodate this issue.

You have 125 results when you are searching for `version` (in contrast to 6 when searching for `revision`). So I'm not sure if adding a comment will provide much benefit. 

Have you considered to install [three dev tools](https://chrome.google.com/webstore/detail/threejs-developer-tools/ebpnegggocnnhleeicgljbedjkganaek) in your browser? When you enable the tool in the browser dev tools, it shows you the used `three.js` version in the console.

![image](https://user-images.githubusercontent.com/12612165/107855799-ce108800-6e24-11eb-9a95-b1307048f3cb.png)

**Comment by gonnavis** [comment]
Hello @Mugen87 , thank you for reminding me of this plug-in, I remember that there is a way to automatically print out REVISION, but I can't recall it.

I currently have no difficulty finding the version number from the source code. But I think as a newbie, will probably look for VERSION instead of REVISION, and should not know the existence of three.js developer tools, at least that's how I was at the beginning.

How about add such as `export const VERSION = REVISION;` as an alias at `constants.js` line 2?

**Comment by gbroques** [comment]
> Changing the position of the mentioned line in the build file is problematic since you normally have no control how the build tool merges your code together. And since the build config is already complex, I do not vote to change something to accommodate this issue.
> 
> You have 125 results when you are searching for `version` in `build/three.js` (in contrast to 6 when searching for `revision`). So I'm not sure if adding a comment will provide much benefit.
> 
> Have you considered to install [three.js developer tools](https://chrome.google.com/webstore/detail/threejs-developer-tools/ebpnegggocnnhleeicgljbedjkganaek) in your browser? When you enable the tool in the browser's dev tools, it shows you the used `three.js` version in the console.
> 
> ![image](https://user-images.githubusercontent.com/12612165/107855799-ce108800-6e24-11eb-9a95-b1307048f3cb.png)

That is super handy! I had no idea this existed.

Thank you again for you helpfulness!

> How about add such as export const VERSION = REVISION; as an alias at constants.js line 2?

@gonnavis This seems reasonable, but I'm not very concerned with it. I do appreciate your input here as well!

For context, I'm completely new to Three.js, but I wouldn't look for the version to be re-defined by a source code variable.
I searched for "**r125**" originally in the file, and failed to search for "125".

I'm more than satisfied with the responses and help from @Mugen87. :)

Feel free to re-open if anyone wants more discussion.
