### ISSUE TITLE
Material.side ignored when wireframe is true

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#21288]
Material.side ignored when wireframe is true

1. Go to https://threejs.org/editor/
2. Create an object.
3. Set the material `wireframe` property to `true`.
4. Notice that changing `side` property makes no effect.

**Comment by mrdoob** [comment]
As far as I remember (we looked into this in 2011)... OpenGL doesn't know how to face cull `gl.LINES` because, unlike `gl.TRIANGLES`, there's no winding order. So I guess `gl_FrontFace` is not there either?

The only way I'm aware is doing a custom shader on triangles:
https://threejs.org/examples/webgl_materials_wireframe.html

But that approach has its own issues (thinner wireframe on the edges).

**Comment by arodic** [comment]
Interesting I thought it was a bug but I guess it makes sense it not really possible. Thanks.
