### ISSUE TITLE
Controls break events due to stopPropagation

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#21339]
for reference: https://github.com/pmndrs/drei/issues/171

```jsx
	function onMouseDown( event ) {

		event.preventDefault();
		event.stopPropagation();
```

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/TrackballControls.js

three jsm controls take away the users ability to raycast properly or use events in general, because events are stopped by the control. depending on what the user does, our own event either work, work sometimes, or don't work at all. it is a race condition, which is more dangerous for app stability. 

imo preventdefault and especially stoppropagation in a control is a bad idea. i read a little back and found what made you merge it, it appeared to fix some problem but [even the authors back then admitted it was an accidental hack](https://github.com/mrdoob/three.js/pull/14619#issuecomment-411528942) (due to the race condition) and would like to remove it. they saw an issue fixed, but now caused a problem for everything else that uses events.

but as it stands, if any control is used, they take over and prevent the user from interacting with the scene.

**Comment by drcmda** [comment]
ps. cameracontrols don't have this behaviour. i have never seen these before, is this the way forward? it seems like a good solution to me to consolidate controls like that, but the "experimental" seems scary.

**Comment by Mugen87** [comment]
> imo preventdefault and especially stoppropagation in a control is a bad idea.

How would you solve this if calling `preventDefault()` would be removed: https://github.com/mrdoob/three.js/pull/18612#issuecomment-585607781

**Comment by drcmda** [comment]
basically this:

```jsx
new THREE.OrbitControls({ preventDefault: true })
```

or flipped, if you want to keep the default without breaking behaviour.

**Comment by DefinitelyMaybe** [comment]
In terms of `dev/examples/jsm/...` I'd look into reimplementing `controls/TrackballControls.js` as meets your use case.

We're working through updating the code base to use classes which will make doing so much simpler in future, but we're not there yet.

If your use case doesn't need to change much else then making it conform to:
```javascript
new THREE.OrbitControls({ preventDefault: true, preventDefault: true })
```
should be easy enough?

**Comment by drcmda** [comment]
You mean I should fork the class? We did that once with catastrophic results. Now we would have to maintain it, getting it up to date and worry about breaking changes. Btw im asking on our users behest, I'm making react-three-fiber and I would be glad if three fixes its bugs,l.

The controls three offers literally block events from propagating and there's no reason why they should.

**Comment by DefinitelyMaybe** [comment]
you'd be surprised but this is actually how I got into contributing to three.js as well.

"Hey guys, love your work, I have a simple earnest use case but currently would need to copy the whole thing into my personal project and then do one small tweak to make it work for me"

I'm unaware of the on-goings within react-three-fiber.

As far as anything in the `examples` folder is concerned, if I'm remembering correctly, they're meant to be adapted by users within their applications, hence the name `examples`. That being said, I share your sentiment here, particularly for `controls`, again because this was what I wanted to originally adjust as well.

**Comment by drcmda** [comment]
wouldn't it make more sense in that case to completely separate "examples" from the main repo so that users get the chance to actually fix problems and progress and iterate on these classes? i've asked about this many times. you're sitting on a gold mine, but it gets treated it like a dumping ground. there is so much potential, but i often get the feeling that no one really cares about it here and that is so, so strange.

here's something i start to be worried about more and more, now that VR is getting mainstream you already know that facebook and co aren't going to use three, they will cook their own to maintain control. if three wants to compete when that happens it has to open up to the community. there's a point where it will not be able to move forward if it doesn't trust the community enough to give it some stake.

**Comment by Mugen87** [comment]
Sorry, I'm afraid @DefinitelyMaybe posts have driven this conversation quickly off-topic.

Investigating to stop the usage of `stopPropagation()` is indeed a good thing. I'm sure there were situations were it was just added on spec. I think it's important to understand why these calls exist and remove them if possible.

**Comment by drcmda** [comment]
this thread is a good read: https://github.com/mrdoob/three.js/pull/14619#issuecomment-411528942

they merged it because they wanted to fix transformcontrols + orbitcontrols, so that that one doesn't interfere with the other. stop propagation appeared to "work" but that is no solution at all, it is accidental, and they realized it later on and regretted it.

transform + orbit does not need a fix at all. it can and should be solved in user-land by listening to the "dragging-changed" event. here is a working example: https://codesandbox.io/s/r3f-drei-transformcontrols-forked-w5kn9

**Comment by Mugen87** [comment]
AFAICS, `stopPropagation()` was originally added provide a more deterministic control behavior. However, as soon as you use more controls or processing events on application level, this pattern is indeed problematic.

E.g. `OrbitControls` calls `stopPropagation()` inside its `wheel` event listener. If users add a `wheel` event listener to `document` on application level, the listener does not fire. Which is indeed a confusing side effect. Example: https://jsfiddle.net/xqL0mvw2/1/

What I find even more confusing is the fact that there is no real pattern in the usage of `stopPropagation()`. Some event listeners use it, some not. And there is no real explanation why it is necessary at some place.

It's probably best to remove these calls altogether from the controls and see what happens. I've tested this change on by local branch and the examples seems to work fine. And yes, users should define which controls are enabled or not. Some controls provide events for supporting this task like `TransformControls`. I'm not sure we need such events everywhere since controls like `FlyControls` or `FirstPersonControls` constantly modify the camera. A combination with other controls seems unlikely to me.

@mrdoob If you like, I can make a PR so we can test this on `dev` for `r127`.

**Comment by drcmda** [comment]
> What I find even more confusing is the fact that there is no real pattern in the usage of stopPropagation(). Some event listeners use it, some not. And there is no real explanation why it is necessary at some place.

i agree. as a rule of thumb, think of stopPropagation as a user-land means to control event flow. but if a lib calls it, it breaks the apps event flow. 

as for preventDefault - this im not sure, i also don't like it but three may have a reason due to do it. and defaults on a canvas are not that important. though this will also break some things, like context menus.

**Comment by Mugen87** [comment]
Let's focus with this issue on `stopPropagation()`. I'd like to handle `preventDefault()` after that (since it is a more complicated topic).

**Comment by mrdoob** [comment]
> @mrdoob If you like, I can make a PR so we can test this on `dev` for `r127`.

Merged. Lets see how it goes 👍

**Comment by drcmda** [comment]
it is still broken it seems. i think the problem really is preventdefault. you can see it here: https://codesandbox.io/s/focused-paper-fme44?file=/src/App.js

once orbitcontrols are present outer events are broken. if i comment out preventdefault it works. i still think it should not be [orbit]controls responsibility to handle browser defaults but the users.
