### ISSUE TITLE
VR - Oculus Quest 2 hand-bone orientation changes

### ISSUE THREAD

**Issue by Honga1** [mrdoob/three.js#21666]
While working on the Oculus Quest 2, we have just found that the bone positions given by XRJoint are no longer correctly mapping to the mesh.

**To Reproduce**
1. Use Oculus Quest 2
2. Go to https://threejs.org/examples/?q=vr#webxr_vr_handinput_profiles
3. View hands with hand tracking

**Video**
https://user-images.githubusercontent.com/33930602/115038901-41d81b00-9ed0-11eb-8486-5de53a566b0c.mp4

**Screenshot**
![image](https://user-images.githubusercontent.com/33930602/115039829-173a9200-9ed1-11eb-9704-a4622b9ef3a1.png)

**Expected behavior**
Hand models shouldn't be warped.

**Quick Fix**
XRHandOculusMeshModel.js

https://github.com/mrdoob/three.js/blob/f2086ff617a42a40c57977c06ab81544e9d4b648/examples/jsm/webxr/XRHandOculusMeshModel.js#L125

```js
bone.position.copy( position.clone().multiplyScalar( 100 ) );
bone.quaternion.copy( XRJoint.quaternion );
// bone.scale.setScalar( XRJoint.jointRadius || defaultRadius );

if(this.handedness === 'left') {
	bone.rotateY(Math.PI/2);
	bone.rotateX(Math.PI);

} else {
	bone.rotateY(-Math.PI/2);
}
```

**Platform:**
- OculusBrowser/15.1.0.2.46.283931095 SamsungBrowser/4.0 Chrome/89.0.4389.105
 - Device: [Oculus Quest 2]
 - Three.js version: [r125.2, r127]

**Comment by Mugen87** [comment]
@cabanier What do you think about the proposed fix?

**Comment by cabanier** [comment]
Does this code hardcode the meshes? 
If not, it would be better to wait for updated models.

**Comment by Mugen87** [comment]
> If not, it would be better to wait for updated models.

/pint @fernandojsg

**Comment by jameshdougherty** [comment]
Here is a screen shot using the Quick Fix method above - it's better, though still a little rough looking:
![Quick rotate joint solution on left](https://user-images.githubusercontent.com/30966050/116955441-87cb0800-ac60-11eb-9123-6c967a5d372c.jpg)
On the new hands, downloaded new XRHandModelFactory.js,  XRHandOculusMeshModel.js, left.glb, right.glb and the old fbx files from the list on https://github.com/mrdoob/three.js/pull/21743/files - so far unable to get that to show new hand model. just blank.  Here's the screen shot, with the right hand OK using spheres - the left hand would be at the bottom of the left ray:
![Left hand, new model missing](https://user-images.githubusercontent.com/30966050/116958498-dda3ae00-ac68-11eb-9f05-bcf18a0f02f7.jpg)
Any idea what I'm missing? Thank you

**Comment by jameshdougherty** [comment]
For Quick Fix, add this.handedness = handedness; to top of constructor if left fails because this.handedness undefined
For new hands, in my test hand rays are pointing up too far and won't point down:
![New Hands Now working with Correct Path](https://user-images.githubusercontent.com/30966050/117017436-972e6d80-acc1-11eb-8521-abf8ad8d3e89.jpg)
If there a way to not show rays with hands, and still have them available when the physical controller is used? Stuck on 126.1 until/unless I can figure out how to work around this

**Comment by cabanier** [comment]
The Oculus browser changed to orientation of the joints to match OpenXR.
Is it possible that this is changing the ray's direction?

**Comment by jameshdougherty** [comment]
Hard to tell which joint it's aligning to - oddly at some Y rotations, nothing seems to allow the ray to point more than a few degrees below horizontal, while when pointing in a different direction, it works almost as expected. This ray was set up originally for the controller, not the hand directly. Since v. 127 that ray/controller moves to the hand when the controller is set down, so that may affect its alignment. 

Here's my work-around for hiding unwanted hand rays altogether:

In XRHandModelFactory.js, just below:

controller.addEventListener( 'connected', ( event ) => {
const xrInputSource = event.data;

add this:

// hide rays 
if ( xrInputSource.hand) {
var ray1 = window.scene.getObjectByName('ray1');
if (ray1)
ray1.visible = false;
var ray2 = window.scene.getObjectByName('ray2');
if (ray2)
ray2.visible = false;
// stop ray click
window.isIndexTip1 = true;
}

The lines for the rays were named ray1 and ray2 when they were set up and added to the controllers. Also window.inIndexTip1 is used to prevent ray clicks, in this case by stopping my two ray action functions, rayClick and rayDown, for example:

function rayClick(event, userId, threeJs) {
if(window.isIndexTip1)return false; ...

The rays are restored just under:

controller.addEventListener( 'disconnected', () => {

with:

// show rays
var ray1 = window.scene.getObjectByName('ray1');
if (ray1)
ray1.visible = true;
var ray2 = window.scene.getObjectByName('ray2');
if (ray2)
ray2.visible = true;
// re-allow ray click
window.isIndexTip1 = false;

This allows the rays to be visible and work when the controller is picked up, and hidden and not fire accidentally when the controller is set down and hands are being used. A more elegant solution would be to have a settable option to hide the hand rays, then find, hide and disable them without having to name them ahead of time or make special provision to stop actions after they've started. In my case, all the click, mouse down, selectstart and selectend actions are consolidated into the rayClick and rayDown function, so they're relatively easy to block when needed. I'm sure someone can think of a better solution.

**Comment by fe1ixz** [comment]
The hand ray in oculus quest sometimes doesn't point down is a known issue, it is currently emulated in a way that assumes the UI is always in front of the user (not above or below). We can definitely propose change to this, but it would not be ideal to just disable the ray while not in controller mode, as a couple of examples are actually using this ray.
