### ISSUE TITLE
npm run test fails on the latest Node.js

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#21727]
**Describe the bug**

`npm run test` fails on the latest current Node.js v16.0.0. But it passes on the LTS Node.js v14.16.0.

**To Reproduce**

1. Install the current Node.js (v16.0.0)
2. `$ npm ci`
3. `$ npm i --prefix test`
4. `$ npm run test`
5. See errors

**Expected behavior**

No error.

**Error log**

```
$ node -v
v16.0.0

$ npm run test

> three@0.128.0 test
> npm run lint && npm run test-unit


> three@0.128.0 lint
> eslint src --ext js


> three@0.128.0 test-unit
> npm run unit --prefix test


> test-deps-intaller@1.0.0 unit
> rollup -c rollup.unit.config.js && rimraf node_modules/three && qunit -r failonlyreporter -f !-webonly unit/build/three.source.unit.js


unit/three.example.unit.js → unit/build/three.example.unit.js...
created unit/build/three.example.unit.js in 1.9s

unit/three.source.unit.js → unit/build/three.source.unit.js...
created unit/build/three.source.unit.js in 1.6s
not ok 260 Source > Core > Clock > clock with performance
  ---
  message: "Died on test #1     at Object.<anonymous> (C:\Users\Takahiro\Documents\three.js\test\unit\build\three.source.unit.js:33432:10)
    at processModule (C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:1208:17)
    at Object.module$1 [as module] (C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:1233:4)
    at Object.<anonymous> (C:\Users\Takahiro\Documents\three.js\test\unit\build\three.source.unit.js:33376:9)
    at processModule (C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:1208:17)
    at Object.module$1 [as module] (C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:1233:4)
    at Object.<anonymous> (C:\Users\Takahiro\Documents\three.js\test\unit\build\three.source.unit.js:33374:8)
    at processModule (C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:1208:17): self is not defined"
  severity: failed
  actual: "null"
  expected: undefined
  stack: "ReferenceError: self is not defined\n    at mockPerformance (C:\Users\Takahiro\Documents\three.js\test\unit\build\three.source.unit.js:33380:5)\n    at Object.<anonymous> (C:\Users\Takahiro\Documents\three.js\test\unit\build\three.source.unit.js:33441:5)\n    at runTest (C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:3054:32)\n    at Test.run (C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:3042:8)\n    at C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:3259:15\n    at processTaskQueue (C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:2649:26)\n    at C:\Users\Takahiro\Documents\three.js\test\node_modules\qunit\qunit\qunit.js:2653:12"
  ...
1..1613
# pass 697
# skip 0
# todo 915
# fail 1
```

**Appendix**

I'm not so familiar with Node.js but it seems the test fails because of undefined `self` in the unit test. Should `self` be defined by default in Node.js? Can this error be caused by Node.js bug?

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Three.js version: r129dev
 - Node version: v16.0.0

**Comment by codrakai** [comment]
Quick note on this:

This is related to the `mockPerformance` method at https://github.com/mrdoob/three.js/blob/5b6a46bdaf4892262d8c0872b287fa857ae233de/test/unit/src/core/Clock.tests.js#L9-L28 and the call to that method in https://github.com/mrdoob/three.js/blob/5b6a46bdaf4892262d8c0872b287fa857ae233de/test/unit/src/core/Clock.tests.js#L65-L72

Both before v16 and in v16, `self` is not defined.

However, prior to v16, because there is no global `performance`, the condition on line 65 passes, the function returns early, and `mockPerformance` is never called, so we never hit the undefined `self` in that method.

In v16, we get a truthy `performance`, so we call `mockPerformance`, and we hit the undefined `self`.

For Node, it would work to use `global.performance` instead of `self.performance`, but I'm not familiar enough with this project from a dev angle to know if there's another context where we'd be counting on a `self`.
