### ISSUE TITLE
Octree - sometimes some triangles will not be found for some of the subtrees

### ISSUE THREAD

**Issue by SnoekJim** [mrdoob/three.js#21755]
**Is your feature request related to a problem? Please describe.**

Using octree, it is sometimes possible to move through faces of Axis Aligned 3d objects such as a wall.
Due to small floating point inaccuracies in the order of one millionth of a millimeter, in practice some triangles would not be found for some of the subtrees.

**Describe the solution you'd like**

To fix this, make each subtree slightly larger to make sure that all relevant triangles are found.

**Describe alternatives you've considered**

There are no alternative solutions we've considered.

**Additional context**

The project we're working on aims to let customers experience their buildings in 3d using first person controls.

**Comment by WestLangley** [comment]
Please provide a simple example to demonstrate the issue.

**Comment by SnoekJim** [comment]
Yes, I will try to provide an example, hopefully as soon as tomorrow. Otherwise it will be later this week

**Comment by Mugen87** [comment]
While working at #21834, I've noticed that the collision detection in `games_fps` is not very reliable. With a low framerate (e.g. 30 fps) it only takes a few tries and the player can pass the walls of the round tower in the middle of the map. With a higher framerate, the glitch is less visible.

I assume that happens because of larger time delta values and thus larger translations of the player. This results in situations where the players "passes through obstacles" because in one frame the player's bounding volume is before a triangle and in the next frame completely behind it. The distance between previous and current position is not honored.

Other approaches for restricting the player's movement like navigation meshes is much more reliable since they account for such scenarios.

Besides, to ensure that small objects like bullets do not pass through obstacles without effect, you normally setup a ray or line segment that represents the distance between the previous and current position. You then test if this ray intersects with an object. In this way, you always detect intersections no matter how big the time delta value is.

**Comment by Mugen87** [comment]
Closing. If there is an issue with floating point inaccuracies, a live example is required for verification.

The restrictions mentioned in https://github.com/mrdoob/three.js/issues/21755#issuecomment-842570740 a more of conceptual nature and only fixable with different approaches.
