### ISSUE TITLE
poor performance with some gltf files

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#21819]
so this file here has some 120K tris and 3 x 2K textures, however when I drop it into 3js editor fps goes out the window. I get much better performance in https://sandbox.babylonjs.com/ with the same model.

@donmccurdy  could it be related to the fact that, for some reason, 3js loader duplicates the textures for each map in every material across the model? here, we have 4 identical materials with 5 maps, 3 of them being same texture, but 3js creates 20 textures for this:
![Screen Shot 2021-05-12 at 16 06 17 ](https://user-images.githubusercontent.com/242577/117990031-11539780-b33d-11eb-8bea-e0ff9bb5a577.png)
![Screen Shot 2021-05-12 at 16 06 36 ](https://user-images.githubusercontent.com/242577/117990039-131d5b00-b33d-11eb-98c1-881c56920fba.png)

glb file in zip below:
[three_js_problem_model.glb.zip](https://github.com/mrdoob/three.js/files/6466747/three_js_problem_model.glb.zip)

**Comment by mrdoob** [comment]
Does performance goes out of the window when dropping it in https://model-viewer-tester.glitch.me/?

**Comment by donmccurdy** [comment]
There's a minor issue in this file where each texture defines a `KHR_texture_transform` extension, containing only a redundant texCoord index:

```js
"texCoord": 0,
"extensions": {
  "KHR_texture_transform": {
    "texCoord": 0
  }
}
```

Normally that extension is supposed to define a _transform_ (offset, rotation, scale) and so we preemptively clone the texture, but in this case the extension is doing nothing. @makc would you be able to report this to the babylon.js 3DS Max exporter with the source file if possible? It'd be great if they could omit this extension where it isn't actually used.

In the meantime #21821 should work around the issue here.

**Comment by makc** [comment]
@mrdoob it does (
@donmccurdy nice, thanks!
