### ISSUE TITLE
emissiveIntensity range?

### ISSUE THREAD

**Issue by liuyug** [mrdoob/three.js#21849]
Default value of emissiveIntensity is 1 and not any description about range.

The emissiveFactor range in gltf is 0..1

In GLTFExporter.js  the emissiveFactor will be calculated by emissiveColor * emissiveIntensity.

Have no any range checking so it will be generated a ERROR gltf file.

**Comment by Mugen87** [comment]
Related https://github.com/KhronosGroup/glTF/issues/1083.

**Comment by Mugen87** [comment]
Yes, it seems this part of the exporter is not spec compliant. Since `GLTFLoader` does this:

https://github.com/mrdoob/three.js/blob/3eaf19a090b4931530f087195ea136d63351248d/examples/jsm/loaders/GLTFLoader.js#L2945

`GLTFExporter` could do something similar and not honor `emissiveIntensity` for now.
