### ISSUE TITLE
Missing rel. path to three in examples

### ISSUE THREAD

**Issue by derCodemeister** [mrdoob/three.js#21853]
when instaling r128 with npm the files in examples/jsm/ seem to import like this:
import {
  ....
} from 'three';
instead of a relative path (../../../build/three.modules.js) (as it is done in r127)
Hence Browsers complain, that three is not a relative path and do not load anything.

However, I cannot find the problem in the current code base on github - which uses the relative path. I checked out the master-branch, and it also uses the relative path.

However, if I use npm install three, the relative path is replace by "three" in files which were moved to ES6 class syntax.
My specific case was with "examples/jsm/curves/NURBSCurve.js", but the problem seems to permate many more files.

**Platform:**

 - Device: Desktop
 - OS: Linux (Windows)
 - Browser: checked with Vivaldi (Chrome based), Firefox
 - Three.js version: r128

**Comment by Mugen87** [comment]
This is actually intended. It was changed with `r128`, see #21654.

The change was done in order to solve #17482. Also read #21707 for more information.

**Comment by kbarros** [comment]
Javascript newbie here. I spent a lot of time confused by this, so maybe it will help others to document my current understanding. Per https://github.com/mrdoob/three.js/issues/22008#issuecomment-863277387, the answer seems to be _"loading modules in web apps from node_modules is not supported anymore."_ Looking at the [migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide#127--128), it is suggested to use https://cdn.skypack.dev to load modules. For example, this seems to work:

```
import * as THREE from 'https://cdn.skypack.dev/three';
import { OrbitControls } from 'https://cdn.skypack.dev/three/examples/jsm/controls/OrbitControls';
```

As far as I can tell, there is no way to get `npm install --save three` to work without using a bundler (one of: Webpack, Rollup, ...), and [the bundler setup seems to be quite complicated](https://sbcode.net/threejs/module-specifiers/).

Without a bundler this complains:
```
import * as THREE from './node_modules/three/build/three.module.js.; // OK
import { OrbitControls } from './node_modules/three/examples/jsm/controls/OrbitControls.js'; // Fails
```
As the original commenter says, the problem is that `OrbitControls.js` tries to load from the `three` module directly, but that doesn't work because `three` hasn't been bundled.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) is you need help regarding your development process and module usage.
