### ISSUE TITLE
Unable to trigger wrapper element events when set orbitcontrols enabled

### ISSUE THREAD

**Issue by xiaopohaier** [mrdoob/three.js#21889]
**Describe the bug**

Unable to trigger wrapper element events when set orbitcontrols enabled

**To Reproduce**

1. Create 3d scene, and add orbitcontrols on it
2. Bind some events on canvas wrapper element
3. Wrapper element will trigger only when set orbitcontrols disabled

***Live example***
https://codesandbox.io/s/suspicious-wilson-brekt?file=/src/App.js

**Expected behavior**
Canvas wrapper element events will trigger whatever orbitcontrols is enable or not 

**Platform:**

 - OS: [MacOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [0.128.0]

**Comment by Mugen87** [comment]
This is due to the usage of `preventDefault()` in control classes. It was considered to remove them but there are side effects like https://github.com/mrdoob/three.js/pull/18612#issuecomment-585607781.

**Comment by Mugen87** [comment]
BTW: Here is a modified codesandbox without any calls of `preventDefault()`: https://codesandbox.io/s/still-dew-527ew?file=/src/App.js

**Comment by xiaopohaier** [comment]
I think its not orbitcontrols responsibility to handle browser defaults, users handle it by themself

**Comment by Mugen87** [comment]
> It was considered to remove them but there are side effects like #18612 (comment).

`preventDefault()` is called at various places and it's important to understand why the calls exist.

- `onContextMenu()`: `preventDefault()` is used to prevent the context menu. This call is definitely required since the controls rely on the right mouse button.
- `onMouseWheel()`: `preventDefault()` exists to avoid scrolling. Since it is not possible to prevent the wheel scrolling with CSS, `preventDefault()` is also required here.
- `handleKeyDown()`: Also required for the same reason like `onMouseWheel()`. If removed, the page will scroll (assuming `controls.listenToKeyEvents( window );` has been used).
- `onTouchStart()` and `onTouchMove()` use the function to prevent scrolling. AFAICS, this is only an issue when the canvas is embedded in iFrames or divs around other HTML content (like in [webgl_multiple_elements](https://threejs.org/examples/webgl_multiple_elements.html)). If the calls of `preventDefault()` are removed, it would be necessary to add `touch-action: none;` to the container elements to avoid page scrolling.
- `onMouseMove()` and `onMouseDown()`: Not sure why `preventDefault()` is used here. 

At first sight, it should be doable to remove `preventDefault()` from `onMouseMove()`, `onMouseDown()`, `onTouchStart()` and `onTouchMove()`. However, adding `touch-action: none;` in certain scenarios would be required when the touch listeners are changed.

**Comment by xiaopohaier** [comment]
I understand your consideration and its required at certain places indeed

> * `onMouseMove()` and `onMouseDown()`: Not sure why `preventDefault()` is used here.

But is it possible prioritize the above case? It looks more serious

**Comment by Mugen87** [comment]
IMO, finding out the purpose of `preventDefault()` in `onMouseMove()` and `onMouseDown()` should be the next step. If that is clear, we can consider to remove `preventDefault()` from certain event listeners.

**Comment by Mugen87** [comment]
Should be fixed via #21972.
