### ISSUE TITLE
GLTFLoader: Support InstancedMesh / 'EXT_mesh_gpu_instancing'

### ISSUE THREAD

**Issue by felixmariotto** [mrdoob/three.js#21937]
It would be nice if `GLTFLoader` automatically created `InstancedMeshes` from a GLTF file including instanced meshes.

Here is an exemple file : [instanced_cube.glb](https://felixmariotto.s3.eu-west-3.amazonaws.com/instanced_cube.glb)

![Screenshot_1](https://user-images.githubusercontent.com/46470486/120330936-96ebb700-c2ed-11eb-8b44-c33c0ccc341f.jpg)

Blender lets us reuse a mesh ( like other modeling softwares I'm sure ), here is the hierarchy in Blender : 

![Screenshot_2](https://user-images.githubusercontent.com/46470486/120330905-8d624f00-c2ed-11eb-858c-7bba0e288f6e.jpg)

I would like `GLTFLoader` to (optionaly?) create an `InstancedMesh` of this cube, instead of making several identical `Meshes`, because : 
- Manually removing the created `Meshes` to replace them with an `InstancedMesh` is tedious.
- It takes memory for nothing. ( potentially a lot )

Some context :

A GLTF file can reuse meshes, this is what the `GLTFLoader.parse` get after reading the file above : 

![01](https://user-images.githubusercontent.com/46470486/120332185-c6e78a00-c2ee-11eb-8afd-d6b68148c365.jpg)

**Comment by mrdoob** [comment]
@donmccurdy tried to implement this in https://github.com/mrdoob/three.js/pull/18913 and seems like @takahirox is working on it these days: https://github.com/mrdoob/three.js/pull/18913#issuecomment-809759353

**Comment by donmccurdy** [comment]
The implementations @takahirox and I have worked on would require that the model be pre-processed to identify which instances should be grouped with InstancedMesh, applying the `EXT_mesh_gpu_instancing` extension. This has some advantages over automatically using InstancedMesh for all meshes appearing more than once:

1. Flexibility to group instances into cells (e.g. a large forest might use 100 InstancedMesh objects in a 10x10 grid in order to take advantage of frustum culling).
2. Scene graph provided by glTF file is not changed without user's knowledge.
3. Simpler for GLTFLoader to support.

An implementation of the necessary pre-processing is provided by the gltf-transform tool ([CLI](https://gltf-transform.donmccurdy.com/cli.html) or [JavaScript function](https://gltf-transform.donmccurdy.com/functions.html#instance)), or by [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf#-gltfpack).

**Comment by felixmariotto** [comment]
I see, so if @takahirox is already working on it I suppose we could close this issue ? Or do you want to keep it open as a reminder ?

**Comment by donmccurdy** [comment]
Let's keep it open, good to have an issue open to track the feature request I think!

**Comment by takahirox** [comment]
Some additional notes...

As @donmccurdy explained, our work requires pre-processing for `EXT_mesh_gpu_instancing`. And I already released the glTF loader plugin at

https://github.com/takahirox/three-gltf-extensions/tree/main/loaders/EXT_mesh_gpu_instancing

You can use it now, but note that I didn't test well yet. Some glTF or Three.js functions may not work (e.g. animation). And that's the reason why I didn't move it into the Three.js repo yet.

I don't think of automatically converting the regular meshes to instanced mesh. If you still want to automatically do that, you may write your own plugin with the plugin API (Three.js glTF loader extensibility mechanism). We haven't written the plugin API document yet, so please refer to the plugins for the API in

https://github.com/takahirox/three-gltf-extensions/tree/main/loaders/

**Comment by mrdoob** [comment]
I have not heard anything nope...

**Comment by takahirox** [comment]
Sorry for slow progress because I have been a bit too busy...

Recently I have fixed some improtant problems in the plugin which I really wanted to resolve before moving it into GLTFLoader.

There is still lack of some supports, SkinnedMesh and better custom instance attributes handling, but they are advanced features. We may be able to start to consider to move the plugin into GLTFLoader as built-in plugin and can think of advanced feature supports later.

If it sounds good, I want to make a PR hopefully soon.

**Comment by NeluQi** [comment]
Well, how is it?

**Comment by shantzis1962** [comment]
Hello all, I had actually put together an implementation for this at work before I even knew that this issue had been present. Hopefully my PR helps and doesn't muddy the waters. If it does, I'd be glad to contribute to getting this feature done in whatever way I can. thanks.

**Comment by takahirox** [comment]
@shantzis1962

Thanks for interesting in and working on it. I will comment to your PR.
