### ISSUE TITLE
Certain gltf models display incorrectly in three.js

### ISSUE THREAD

**Issue by JustASquid** [mrdoob/three.js#21996]
**Describe the bug**

Certain models now display incorrectly.
These models used to display correctly.
I noticed the change when updating from 0.108.0 to 0.121.1, however the issue appears to still happen in the latest three.js version.
Some gLTF models display incorrectly in three.js since a recent update.

**To Reproduce**

[car.zip](https://github.com/mrdoob/three.js/files/6660911/car.zip)

Open this model in [this three.js based gLTF viewer](https://gltf-viewer.donmccurdy.com/) to see the problem.
![brave_bwuQfrrkDJ](https://user-images.githubusercontent.com/11645696/122173927-9e9e8480-cec5-11eb-9f86-3ecad1e58469.jpg)

The model displays fine in [this alternate gLTF viewer](https://3dviewer.net/).
<img width="941" alt="brave_T9LKSNQ3xz" src="https://user-images.githubusercontent.com/11645696/122173939-a1997500-cec5-11eb-81a5-9be37237366b.png">

***Code***

```js
// code goes here
```

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: latest

**Comment by donmccurdy** [comment]
https://github.com/mrdoob/three.js/pull/18235 is the relevant change here. Despite the result you're seeing here, it was a necessary and correct change. The model attached has two materials (output from `gltf-transform inspect car.gltf`) ...

| # | name          | instances | textures         | alphaMode | doubleSided |
| - | ------------- | --------- | ---------------- | --------- | ----------- |
| 0 | `Material #582` | 1         | baseColorTexture | BLEND     |             |
| 1 | `window`        | 1         | baseColorTexture | BLEND     |             |

... note that both, not just the window material, are using alpha blending (or `material.transparent = true`). The change above fixed a number of issues with materials are actually transparent, while unfortunately making it much more obvious when something that isn't really transparent is marked for the alpha blend pass anyway, because it can create sorting issues.

Fortunately the workarounds are pretty easy:

- **A.** In Blender, switch from "Alpha Blend" to "Opaque" for these materials, or...
- **B.** In three.js, manually set `.transparent = false`, or ...
- **C.** use a script to patch the file:

```typescript
import { NodeIO } from '@gltf-transform/core';

const io = new NodeIO();
const document = io.read('car.gltf');

for (const material of document.getRoot().listMaterials()) {
	if (material.getName() !== 'window') {
		material.setAlphaMode('OPAQUE');
	}
}

io.write('car-patched.glb', document);
```

Fixed version attached:

[car-patched.glb.zip](https://github.com/mrdoob/three.js/files/6661133/car-patched.glb.zip)

**Comment by mrdoob** [comment]
@donmccurdy I guess you saw it already but `car-patched.glb` gets this:

<img width="820" alt="Screenshot 2021-06-16 at 12 50 21" src="https://user-images.githubusercontent.com/97088/122206255-0db1b400-ce99-11eb-81ec-ca8d79c7929d.png">

**Comment by mrdoob** [comment]
> The model displays fine in [this alternate gLTF viewer](https://3dviewer.net/).

That viewer also uses Three.js 🤔

**Comment by mrdoob** [comment]
@donmccurdy Do we still need to set `depthWrite = false` after #21967?

**Comment by donmccurdy** [comment]
> ... I guess you saw it already but car-patched.glb gets ['image/tga' error]

Yeah, the file contains a TGA texture, which glTF doesn't really allow. I'm not sure why it says the "recognized image format" is PNG. Appears to be a bug in the Babylon.JS 3DS Max exporter not converting that.

> Do we still need to set depthWrite = false after #21967?

I think it's still best to do so. Or at least to recommend it as the default choice, and to enable it automatically in GLTFLoader. Certainly there are cases where the user might want to switch to `depthWrite=true`, and that's fine. Another common case where `depthWrite=false` makes a difference is two geometries centered at the same point, or interlocking in some way. Sorting by the AABB rather than the center might help with the former.
