### ISSUE TITLE
Editor: Changing antialias invalidates equirectangular env maps.

### ISSUE THREAD

**Issue by q750831855** [mrdoob/three.js#22075]
HI! When I turn off the anti-aliasing option，Equirect Ineffective!
![HDR](https://user-images.githubusercontent.com/31579609/124209901-076c3a80-db1d-11eb-8f4a-dc3a869cba97.jpg)

**Comment by Mugen87** [comment]
The problem is that changing `antialias` requires to create a new instance of `WebGLRenderer`. Creating a new renderer means that converted equirectangular environment maps are lost since they are internally cached as cube maps.

The easiest way to solve this issue is to remove the `antialias` option from the GUI and create the renderer only once.

**Comment by Mugen87** [comment]
The problem is that the editor uses an instance of `PMREMGenerator` to prepare the environment map for rendering. If a  new renderer is created because `antialias` is changed, the preprocessed environment map becomes invalid since it belongs to an outdated WebGL context. 

One way to fix the issue is to remove the `antialias` option and only create the renderer once. Otherwise the editor needs to recreate the environment map again when a new renderer is created.

**Comment by Mugen87** [comment]
> One way to fix the issue is to remove the antialias option and only create the editor's renderer once.

@mrdoob Are you okay if I change the editor in this way?

**Comment by mrdoob** [comment]
Hmm...

I think the right fix is the be able to set a equirectangular texture as `scene.environment` and then do the PMREM inside the renderer.

**Comment by Mugen87** [comment]
> (like we're doing with scene.background).

Um, but `PMREMGenerator` is not yet internally used. #20463 tried to solve this. Or do I overlook something?
