### ISSUE TITLE
WireframeGeometry generates duplicate edges

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22094]
`WireframeGeometry` generates duplicate edges for both indexed and non-indexed buffer geometry.

This is true by inspection, as the code does not test for duplicate xyz-coordinates.

A simple non-indexed example is:
```js
const geometry = new THREE.TetrahedronGeometry( 1, 0 ); // 6 unique edges

const wireframe = new THREE.WireframeGeometry( geometry ); // 12 edges
```

`BoxGeometry( 1, 1, 1 )` is a simple indexed example.

Duplicating an edge is not a problem most of the time, but when using dashed lines, it is a problem.

---

EDIT: Actually, instead of "duplicate edges", they should be referred to as "coincident edges": A -> B  =  B -> A.

**Comment by Mugen87** [comment]
> but when using dashed lines, it is a problem.

Indeed, that does not look right: https://jsfiddle.net/dhq9zrx8/2/

> as the code does not test for duplicate xyz-coordinates.

There is [BufferGeometryUtils.mergeVertices()](https://threejs.org/docs/index.html?q=bufferge#examples/en/utils/BufferGeometryUtils.mergeVertices) but it is currently no part of the core.

**Comment by Mugen87** [comment]
> as the code does not test for duplicate xyz-coordinates.

Implementing an equality test for vertices is tricky since it's necessary to use an epsilon value. Finding such a threshold rises two questions:

- Do we need a new second ctor parameter that allows to define a custom threshold (similar to `BufferGeometryUtils.mergeVertices()`)?
- What would be a proper default value?

**Comment by WestLangley** [comment]
@Mugen87 Thanks for looking at this.

`EdgesGeometry` appears to work correctly. It uses a hardwired precision value and compares vertex coordinates.

TBH, I was surprised a threshold is used at all. In a well-formed geometry, there may be repeated vertices, but if the coordinates are not _exactly_ equal, then, well, they are not repeat values.

**Comment by Mugen87** [comment]
The problem is you can only guarantee _exactly_ equal numbers with integers. Since `three.js` and every other 3D/game engine I know work with floating point, you _normally_ want to use an epsilon whenever you compare numbers. We don't do this for simplicity in the project. But from an academical point of view, it would be more correct to honor this circumstance.

I have no problems however to stick to the current policy and don't introduce an epsilon. We might want to continue the discussion about the epsilon values in #11449.

**Comment by WestLangley** [comment]
>The problem is you can only guarantee exactly equal numbers with integers

Typically, there is no computation involved. The coordinates are stored in a file. If they are equal in the file, they will be equal in memory.

I can't think of a use case where a vertex is "repeated", and the coordinates are not identical due to roundoff... But even if it happens, the worse case is a duplicate edge.

So, I still do not see a reason for a tolerance parameter. It was required in `EdgesGeometry` only because of the hash.

**Comment by WestLangley** [comment]
With semi-transparent Fat Lines, you can see the overlapping dashes in the duplicated edges.

<img width="523" alt="Screen Shot 2021-07-06 at 5 07 09 PM" src="https://user-images.githubusercontent.com/1000017/124666891-ab871600-de7c-11eb-83f0-b383dc576b85.png">

**Comment by Mugen87** [comment]
@WestLangley Are you going to have a go on this? 😇
