### ISSUE TITLE
[Feature request] Add per-instance visibility support to InstanceMesh

### ISSUE THREAD

**Issue by FoolHen** [mrdoob/three.js#22102]
**Is your feature request related to a problem? Please describe.**

In the project I'm working on (a 3d editor) we have objects in the form of AABB boxes. We have all objects invisible by default and show them when highlighted or selected. The problem arises when selecting a group with many children, which should become visible. Instancing is a perfect solution for this, but we would need a way to show/hide them individually. I'm not sure how possible this request is, or if there's a way to do this that I missed.

**Describe the solution you'd like**

A way to set visibility of each instance, like currently exists for color. ``setVisibilityAt()`` and ``getVisibilityAt()``, for example.

**Describe alternatives you've considered**

I've tried setting the scale to zero, but I need to use the raycast on those invisible objects (in the editor objects are highlighted on hover and selected on click). 

**Additional context**

This is what I want to achieve https://gfycat.com/QuestionableOilyLeech

**Comment by WestLangley** [comment]
See this comment and related discussion: https://github.com/mrdoob/three.js/pull/18256#issuecomment-839769285.

I would advise against waiting for a feature to be implemented. Instead, follow the pattern in `webgl_instancing_modified.html`.

**Comment by Mugen87** [comment]
> A way to set visibility of each instance, like currently exists for color. setVisibilityAt() and getVisibilityAt(), for example.

Notice that an additional instanced attribute that controls visibility will not improve the performance. It would be a pure convenient method. It might be preferable to organize your instances in a way such that the visible instances are defined first and after that the invisible ones. In this way, you can use the [count](https://threejs.org/docs/index.html?q=instan#api/en/objects/InstancedMesh.count) property to decrease the effective draw range. 

This will produce the same result and you will have better performance. Of course you have to do more work at app level.

**Comment by Mugen87** [comment]
Closing. The existing solutions seems sufficient for this use case.

**Comment by FoolHen** [comment]
@Mugen87 thanks, your idea works prefectly 😄

**Comment by ttiimmaacc** [comment]
Didn't suit my case. Count doesn't offer enough flexibility. +1 for support for per-instance visibility.

**Comment by WestLangley** [comment]
@ttiimmaacc 

As I said above, follow the pattern in `webgl_instancing_modified.html`.

A pattern similar to the following will get you started:
```js
geometry.setAttribute( 'visible', new THREE.InstancedBufferAttribute( new Uint8Array( visiblilty ), 1 ) ); // visibility attribute

const visibilityChunk = [
	'vViewPosition = - mvPosition.xyz;',
	'gl_Position = mix( vec4( 0, 0, - 1, 1 ), gl_Position, visible );' // move outside of clip space
].join( '\n' );

shader.vertexShader = shader.vertexShader
	.replace( '#include <common>', colorParsChunk )
	.replace( '#include <begin_vertex>', instanceColorChunk )
	.replace( 'vViewPosition = - mvPosition.xyz;', visibilityChunk );
```

**Comment by FoolHen** [comment]
@ttiimmaacc alternatively [here is how I solved it](https://github.com/BF3RM/MapEditor/blob/development/WebUI/src/script/modules/InstanceManager.ts), with a manager class that moves instances in the array so that the visible ones are all at the beggining and then the invisible ones, and updating count accordingly with the number of visible instances.

**Comment by aminick** [comment]
This is my solution:
```
// emptyMatrix = [0, 0, 0]
meshRef.current.setMatrixAt(id, emptyMatrix)
```

**Comment by likethemammal** [comment]
Using `[0, 0, 0]` didnt work for me. But an empty `Matrix4` did.

```
const emptyMatrix = new THREE.Matrix4();
meshRef.current.setMatrixAt(id, emptyMatrix);
```

**Comment by bergden-resonai** [comment]
Really sorry to revive such an old discussion but I encountered it while searching for a solution to my problem and I want to add some more comments:
- Empty matrix as suggested [here](https://github.com/mrdoob/three.js/issues/22102#issuecomment-1207288786) didn't work for me since sometimes the instances would appear on [0, 0, 0] - I'm not sure why, if I understand correctly they were supposed to have 0 scale...
- So far I used some "hide matrix" that would throw away the instances to somewhere far enough to never bother me:
`new Matrix4().makeTranslation(Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY)`
But upon upgrading threejs to one of the recent versions (I'm not sure which) this hack started causing very severe performance issues when raycasting on the instancedMesh (much worse than when all instances are visible)
(should this be reported?)

- Upon re-reading on the issue it seems this suggested solution is best: https://github.com/mrdoob/three.js/issues/22102#issuecomment-877004180
Which is also referenced here: https://discourse.threejs.org/t/how-to-show-and-hide-an-instance-in-instance-mesh/28198/15
