### ISSUE TITLE
Object spread operator not supported by older browsers

### ISSUE THREAD

**Issue by ChrisBuergi** [mrdoob/three.js#22139]
The object spread operator "{...obj}" introduced with the fix for #20328 does not work in older, [supported browsers](https://threejs.org/docs/#manual/en/introduction/Browser-support). The object spread operator got introduced with ECMAScript 2018.

This is especially a problem for the built version, since the spread operator is kept (search for "...this.texture.image").

Not sure if that should be resolved in [the code](https://github.com/mrdoob/three.js/pull/21719/files) or build process.

**Comment by Mugen87** [comment]
The support for `spread in object literals` is sufficiently good: 

https://caniuse.com/mdn-javascript_operators_spread_spread_in_object_literals

If users have to support older browsers, they have to prepare respective builds on their own. This can be accomplished by updating the project's [.babelrc.json](https://github.com/mrdoob/three.js/blob/dev/utils/build/.babelrc.json) file and running the build.

**Comment by Mugen87** [comment]
@mrdoob TBH, it's a maintenance nightmare to list all JavaScript language features in the [browser support page](https://threejs.org/docs/#manual/en/introduction/Browser-support) and keep it up-to-date. I vote to remove the page especially since the original developer @keqingrong did not maintain it over time, see https://github.com/mrdoob/three.js/issues/12698#issuecomment-346244867.

**Comment by mrdoob** [comment]
@Mugen87 I agree 👍
