### ISSUE TITLE
Editor settings get corrupted after duplicating tab

### ISSUE THREAD

**Issue by tfreifeld** [mrdoob/three.js#22131]
I believe this bug has various scenarios for happening, but I've managed to pinpoint just one:

When opening the editor, (only) after adding some object, and duplicating the tab, some settings get corrupt. At the least the keyboard shortcuts are corrupted, but I have reason to believe it may be more than that.

https://user-images.githubusercontent.com/31798283/125646841-3c06b6fc-60a9-4f31-ac73-3bf6a31bc948.mp4

 - Device: Desktop

**Comment by Mugen87** [comment]
There are also a bunch of runtime errors in the second tab:

![image](https://user-images.githubusercontent.com/12612165/125655044-b466b704-f32f-48a2-b435-979497499ee9.png)

I don't think multiple tabs targeting the same editor URL is valid since all apps operate on the same local storage and IndexedDB. What is your use case for this workflow?

**Comment by tfreifeld** [comment]
Well, I don't have a use case for this workflow. My team have extended the editor for our own needs, and have encountered a corruption of these settings sometimes , though we didn't manage to find what causes this. But in the middle of my research into this, I found that one of the scenarios which causes this is duplicating a tab, and then found that this also happens in the official editor version, and not only in our custom version. That is why I've opened this issue. If you don't consider this an issue, then apologies :-)

**Comment by tfreifeld** [comment]
Though, actually, I do sometimes have a need to open two editor tabs at once. I have some cases where I want to compare two models for example.

**Comment by Mugen87** [comment]
Opening the second tab as an incognito window should actually work.

**Comment by tfreifeld** [comment]
> Does it work if the second tab is opened as an incognito window?

Yeah. In fact, even if I manually open the editor in a new tab in the same (non-incognito) window, everything will be fine. It gets messed up when duplicating. I'd like to emphasize that I personally don't mind that just duplicating doesn't work well. I just think it may be a symptom of another (perhaps bigger) problem.

**Comment by Mugen87** [comment]
Cloning the tab in Firefox seems not messing up the UI. However, I see errors in the browser console, too:

![image](https://user-images.githubusercontent.com/12612165/125921942-1c0caea4-493c-4a4e-b6ad-581de4217dc0.png)

**Comment by Mugen87** [comment]
After some debugging it seems that when a tab is duplicated certain input elements trigger a `change` event. The new values do not seem to make sense though and certain event listeners crash since they expect that `editor.selected` refers to a 3D object. However, on application start this variable is always `null`. This circumstance explains the above runtime errors.

Interestingly, the mentioned `change` events are not fired when the editor is started normally or after a reload. I don't know the reasons why these events exist but they seem to be the cause of the corrupted UI state.

My guess is the browser tries to be smart and fills out input elements in advance when duplicating a tab. You can check out this behavior with https://www.w3schools.com/html/html_forms.asp. Change the first name, duplicate the tab and you will see the browser applies the value to the new tab. I think the same happens with the editor. Let me try to fix this with a PR.

**Comment by mrdoob** [comment]
> My guess is the browser tries to be smart and fills out input elements in advance when duplicating a tab. 

Good detective work!

**Comment by Mugen87** [comment]
> Good detective work!

This issue did not let me go so I really had to find out what's going on 😅  .

**Comment by tfreifeld** [comment]
Thanks!
