### ISSUE TITLE
Depth sorting issue in SVGRenderer

### ISSUE THREAD

**Issue by sophiehuiberts** [mrdoob/three.js#22150]
**Describe the bug**

When using SVGRenderer, the depth sorting can't always correctly tell whether a line should go above or below a triangle.

**To Reproduce**

1. Create a cube, say the axis-aligned cube centered at the origin of edge length 1
2. Draw a line not intersecting the cube, say from  (1,0,0) to (0,0,2)
3. Rotate the scene around and observe that not every viewing angle gets rendered correctly.

***Live example***

* [minimal example](https://vigilant-gates-df4ed3.netlify.app/)
* In the initial view, the blue line should pass in front of the cube.
* You can use the TrackballControls, moving the mouse vertically, to verify that the blue line should pass in front of the cube and does not intersect the cube.
* Moving the mouse horizontally, we can observe that the issue does not always affect both triangles of a single face of the cube at the same time.

**Screenshots**

This is the geometry in the linked minimal example. Note that the line does not intersect the cube.
![Screenshot_20210719_003214](https://user-images.githubusercontent.com/1057007/126085030-97cc35e3-1ebd-4fe9-8acf-9d81028afe23.png)
Here is one angle that shows off the bad depth sorting
![Screenshot_20210719_011349](https://user-images.githubusercontent.com/1057007/126085056-e43aec2f-ef2e-4b27-9c2e-4614cfa216df.png)

**Platform:**
Tested on
 - Device: Desktop
 - OS: ubuntu
 - Browser: Chrome, Firefox
 - Three.js version: 0.130.1

**Comment by Mugen87** [comment]
This happens because of how `Projector` computes the `z` value for a line primitive. The relevant code section is:

https://github.com/mrdoob/three.js/blob/d6fcfa5606539967a77b6b84fbab239206054d14/examples/jsm/renderers/Projector.js#L271-L307

In WebGL depth testing normally happens as a part of the fragment operations. There is no performant/easy way to emulate this process in software. Hence, `Projector` has some limitations.

If you need more precise rendering, please use `WebGLRenderer`.
