### ISSUE TITLE
Material: Deprecate material.morphTargets=true and material.morphNormals=true?

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#22166]
Similar to https://github.com/mrdoob/three.js/pull/22146 and https://github.com/mrdoob/three.js/pull/21788, both properties could be inferred from the parent Mesh, without requiring separate boolean flags on the material. Along with the recent removal of `.skinning`, this should help avoid situations where the user replaces a material provided by a loader and doesn't understand why the model stops animating.

Earlier threads proposed removing other properties that could be inferred (e.g. flatShading, vertexColors), but there has been some push-back against removing those and I don't feel strongly either way.

**Comment by WestLangley** [comment]
Hmm... so a material can no longer be compiled without a geometry. We started down that path with `vertexAlphas`... 🤔

**Comment by Mugen87** [comment]
Actually `vertexAlphas` was not the first step in that direction. You actually need information from many entities (renderer, scene, 3D object, material and geometry) in order to compile a shader program. In WebGPU renderer we maintain a node builder per 3D object in order to determine the correct shader program right from the beginning.

Removing `morphTargets` and `morphNormals` is only a logical consequence after #21788. If @mrdoob agrees, I can try to provide a PR with the removal.
