### ISSUE TITLE
InstancedMesh and USDZ Export

### ISSUE THREAD

**Issue by petasHUB** [mrdoob/three.js#22203]
I would love to use InstancedMeshes in my project, but looks like they are not exported to USDZ for AR usage on Apple devices.

I had no chance to test GLTF export for Android devices with Scene Viewer. But would be great if it would be also supported there.

**Comment by Mugen87** [comment]
Most 3D formats do not support the concept of instancing since it's a technology in context of rendering. You can use the utility function [SceneUtils.createMeshesFromInstancedMesh()](https://threejs.org/docs/index.html?q=sce#examples/en/utils/SceneUtils.createMeshesFromInstancedMesh) to convert instances meshes to a group of normal meshes before performing the export.

We have decided in #18572 to not add this logic to exporters but handle it the app to prepare the scene graph for exporting.

**Comment by petasHUB** [comment]
Thanks for the info! Helps a lot!

**Comment by Mugen87** [comment]
@d3tr0id Please use the [forum](https://discourse.threejs.org/) for such questions.
