### ISSUE TITLE
GLTF animation gets applied to the wrong node

### ISSUE THREAD

**Issue by rawnsley** [mrdoob/three.js#22204]
**Describe the bug**

[This GLB file](https://github.com/mrdoob/three.js/files/6893034/animation-bug.zip) contains two scenes with a node in each. The first node is a simple cube mesh and the second is a node with no mesh. An animation targets the empty node in the second scene. Instead of being static, the cube in the first scene is animated.

**To Reproduce**

1. Check the model in GLTF Viewer or another application using three.js, such as Mozilla Hubs.

**Expected behavior**

The cube model should not be affected.

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r129 (in GLTF Viewer)

**Notes**

The same problem occurs if you delete the second scene definition completely. The problem goes away if you include the empty node in the set of nodes for the first scene. The animation is applied to all objects in the scene, presumably because it is being applied to root of the scene as a fallback when it fails to find the target node.

**Comment by donmccurdy** [comment]
There are a couple ways to view what is happening here. 

1. My glTF viewer (https://gltf-viewer.donmccurdy.com/) displays the first scene in a glTF file (or default scene, if set), and plays the first animation. It doesn't check whether the first animation affects anything in that scene, mostly because glTF files very rarely have multiple scenes.

2. As you mentioned, THREE.PropertyBinding falls back to the root node if it can't find a match for the given animation target:

https://github.com/mrdoob/three.js/blob/f952a0e4f9838f89c34e12acd5308220074b5084/src/animation/PropertyBinding.js#L110

https://github.com/mrdoob/three.js/blob/f952a0e4f9838f89c34e12acd5308220074b5084/src/animation/PropertyBinding.js#L426

**Comment by donmccurdy** [comment]
I'm not sure why (2) is using that fallback... presumably (1) is the case in my viewer and in Hubs because files with multiple scenes are very rare. If there were no fallback to the root node, this would just mean the 1st animation is playing but nothing is happening in the first scene, which is not unreasonable.

I don't think there's anything we can do differently in THREE.GLTFLoader here, it's probably a question of whether we want to remove the fallback from THREE.PropertyBinding or consider this a viewer bug?

**Comment by donmccurdy** [comment]
I think that I consider this a "viewer bug" rather than a bug in three.js, but would be open to other suggested fixes.
