### ISSUE TITLE
PMREMGenerator.fromScene() is not using the correct background color

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22326]
This is a continuation of https://github.com/mrdoob/three.js/issues/22286#issuecomment-896503667.

`PMREMGenerator.fromScene()` is rendering with a background color that differs from the specified background color.

In the furnace test, set the environment background color to `0x202020` and the spheres render more brightly than with `0xcccccc`.

This was not an issue in three.js r124.

 - Three.js version: r.131

**Comment by gkjohnson** [comment]
I believe this is happening due to #21034 which switched to using a mesh to render the background color to avoid implicit clear color changes from the premultipliedAlpha setting. The target render texture is set to use RGBE color which is automatically converted to from linear in the MeshBasicMaterial shader. However we were already converting to RGBE in PMREMGenerator before rendering which means we were running the RGBE conversion twice resulting in incorrect colors.

Here's a diff with @Mugen87's branch for #22318:

https://github.com/Mugen87/three.js/compare/dev6...gkjohnson:pmrem-color-fix?expand=1

If this looks good I can make a PR after the #22318 changes are merged or you can merge it into your `dev6` branch @Mugen87.

**Comment by WestLangley** [comment]
@gkjohnson Thanks! It appears to be working. Ship it!
