### ISSUE TITLE
USDZExport creates an empty (visually) USDZ file from a GLTF created in the browser

### ISSUE THREAD

**Issue by jeffscottward** [mrdoob/three.js#22454]
Continuation from [previously filed issue](https://github.com/mrdoob/three.js/issues/22453#issue-982195479)

**Describe the bug**

Trying to create a GLTF in the browser and convert it to USDZ without needing to download a GLTF file first.
TLDR; On-the-fly-USDZ creation and download

It successfully creates a GLTF in memory, loads the GLTF after wrapping in blob, and exports the usdz file (in theory).

I can see the object as GLTF in the Three.js editor and Apple's Reality Convertor but not in any QuickLook view (phone or Finder)

<img width="788" alt="gltf-w-r3f" src="https://user-images.githubusercontent.com/1263486/131265852-20c67f51-e2bb-462d-a6fe-02118c323b5b.png">
<img width="893" alt="rc" src="https://user-images.githubusercontent.com/1263486/131265853-500e7adb-795c-4ae8-8235-45b99e3c59d4.png">
<img width="837" alt="usdz-empty" src="https://user-images.githubusercontent.com/1263486/131265854-15cdce62-bf48-4a54-9780-47080a1fee66.png">

Source of export here:  https://github.com/jeffscottward/r3f-to-ar/blob/main/src/exporters/usdzExporter.js
Repo here: https://github.com/jeffscottward/r3f-to-ar

**To Reproduce**

```
git clone https://github.com/jeffscottward/r3f-to-ar/
yarn && yarn start
```

Click the model - it should download 2 files, 1 gltf and 1 usdz

Platform:

Device: Laptop
OS: MacOS
Browser: Chrome
Three.js version: "^0.132.2"

**Comment by Mugen87** [comment]
> I can see the object as GLTF in the Three.js editor and Apple's Reality Convertor but not in any QuickLook view (phone or Finder)

Wouldn't it be better to report the issue to Apple instead? 

Besides, you should always share the asset your are trying to load within an issue. So next time, please add the USDZ file.

**Comment by jeffscottward** [comment]
GLTF shows up fine in Reality Convertor
USDZ does not. 
I don't know what can be gleaned from a binary file type like USDz but here you go.
Maybe the GLTF can help.

(Had to send a link because the file uploader doesn't like either file)

https://github.com/jeffscottward/r3f-to-ar/blob/main/public/scene.gltf
https://github.com/jeffscottward/r3f-to-ar/blob/main/public/scene.usdz

Again here is the exporter code. Just a wraping and loading via blobURLs.
https://github.com/jeffscottward/r3f-to-ar/blob/main/src/exporters/usdzExporter.js

<img width="486" alt="Screen Shot 2021-08-30 at 9 17 47 AM" src="https://user-images.githubusercontent.com/1263486/131345152-04196194-6747-4dc8-ad07-b1c9cec2c1e6.png">

**Comment by Mugen87** [comment]
It seems it does not work because you assign `MeshBasicMaterial` to the mesh. However, only `MeshStandardMaterial` is supported. If I change the material type in the editor and then export to UDSZ, the preview works. Here is the resulting model:

[model.usdz.zip](https://github.com/mrdoob/three.js/files/7077011/model.usdz.zip)

**Comment by mrdoob** [comment]
I'll take care of this 👍

**Comment by jeffscottward** [comment]
Great! I figured it wasn't me given the simplicity.
I suspect there are other materials that could be problematic - I think I had a problem with phong too? Idk if that one makes sense. Forgive me on this, Im a super newbie with what actually makes sense to export. I just imagine this popping up more probably unless every base is covered.

**Comment by mrdoob** [comment]
USDZ only supports `MeshStandardMaterial`.

**Comment by mrdoob** [comment]
But we can, kind-of, fake `MeshBasicMaterial` support.

**Comment by jeffscottward** [comment]
Hmm without docs, or a pointer to USDz native docs, I wouldn't know thats the case.

**Comment by Mugen87** [comment]
Maybe we can add a warning somewhere at the following place to inform users if they are exporting materials with an unsupported material?

https://github.com/mrdoob/three.js/blob/183ae6afcdb6323d6a2075811073ed8767d6c2fc/examples/jsm/exporters/USDZExporter.js#L20

**Comment by jeffscottward** [comment]
that would be the best - feature detection warnings/errors in console.

**Comment by jeffscottward** [comment]
@Mugen87 is this an enhancement (assuming meaning low priority) or a bug?
This is a showstopper for my intended use case. Would help expedite if I could.

**Comment by jeffscottward** [comment]
Any progress on this?

**Comment by Skyswimsky** [comment]
Some sort of warnings or a bare-bone documentation would be nice. Does it help to voice my support for it?

I've had a similar issue with this. Had a MeshPhonMaterial and had to create a GLTFBlob to make the USDZExport not turn out empty. However, the (test) object in question is a group of multiple objects which, upon export, would reset their position back to 0, 0, 0 of the world coordinates. Or in other words instead of this:
![image](https://user-images.githubusercontent.com/8056740/135293751-bd30a8d0-f5a4-416a-a6c5-32f50689c57a.png)

I would get this:
![image](https://user-images.githubusercontent.com/8056740/135293948-770309ad-08ba-4746-b276-4a8d0aff24de.png)

Changing the material fixed pretty much everything. Though I spend a lot of time trying to fix it before checking the issues listed here.

Also rather new to most of this, so apologize for anything inappropriate.

**Comment by mrdoob** [comment]
> Maybe we can add a warning somewhere at the following place to inform users if they are exporting meshes with an unsupported material?
>
> https://github.com/mrdoob/three.js/blob/183ae6afcdb6323d6a2075811073ed8767d6c2fc/examples/jsm/exporters/USDZExporter.js#L20

Done. https://github.com/mrdoob/three.js/commit/6e4f7a5fa7f1944e941019a655ae50868f2a883a
