### ISSUE TITLE
glTF conformance: khronos-TextureLinearInterpolationTest

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#22483]
I've finally updated our <model-viewer> fidelity tests and three.js is looking quite respectable (with the exception of sheen), but I did notice a clear failure: https://modelviewer.dev/fidelity/#khronos-TextureLinearInterpolationTest

This [warning](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureLinearInterpolationTest) looks like it may be directed at us. I also notice many of our renders are subtly darker than the others if you look through these fidelity tests. Considering the exposures and tone mappings have been carefully matched, I wonder if this might be the cause?

**Comment by donmccurdy** [comment]
I've been a little skeptical of this test (https://github.com/KhronosGroup/glTF-Sample-Models/pull/297#issuecomment-836869424) and wrote the warning above (https://github.com/KhronosGroup/glTF-Sample-Models/pull/313), but if it really is making our renders subtly darker than baselines that would be much more motivating... 🤔

The workaround is to use `EXT_sRGB` in WebGL 1.0 (on by default in WebGL 2.0) instead of doing texture colorspace conversions in the fragment shader... I'm not sure what the support looks like for that extension, but I think we'd at least need to keep a fallback to the current GLSL for as long as we support IE11, is that worth the effort? Or is there a target date we might drop IE11 support? (EOL is currently June 15, 2022).

**Comment by Mugen87** [comment]
Can someone explain why the usage of `EXT_sRGB` produces a different result than the GLSL inline sRGB conversion? I've thought using the extension would only provide a minor performance benefit (since the texture is decoded once instead of every frame).

**Comment by mrdoob** [comment]
Not sure texture colorspaces conversion is the issue the renders are darker.

I can see many samples that don't use textures and are still dark:

https://modelviewer.dev/fidelity/#khronos-BrainStem
https://modelviewer.dev/fidelity/#khronos-Fox
https://modelviewer.dev/fidelity/#khronos-GearboxAssy
https://modelviewer.dev/fidelity/#khronos-ReciprocatingSaw
https://modelviewer.dev/fidelity/#khronos-RiggedFigure
https://modelviewer.dev/fidelity/#khronos-BoxAnimated

And on this one the shine is still too bright:

https://modelviewer.dev/fidelity/#khronos-RiggedSimple

**Comment by WestLangley** [comment]
three.js is not glTF-compliant. AFAIK, I am the only one working on trying to make it so.

It is too early for conformance testing... Maybe in a month, assuming an organized and concerted effort.

**Comment by mrdoob** [comment]
> AFAIK, I am the only one working on trying to make it so.

I'm trying to solve `alphaMode` 💪

**Comment by donmccurdy** [comment]
> Can someone please explain why the usage of EXT_sRGB produces a different result than the GLSL inline sRGB conversion?

There's a difference in whether color interpolation happens before or after sRGB decoding...

> The second sphere samples its color as an interpolated value from a `2x1` texture. When interpolation happens after sRGB decoding, the final emissive value should also be about `0.5` green.

... it's clear in this example (the example is designed for that) but I'm not sure how much visual effect it has generally.

**Comment by Mugen87** [comment]
I've tried adding support for `gl.EXT_sRGB` today but noticed something unfortunate. With WebGL 1, it is not possible to use the extension in combination with mipmap generation which makes `gl.EXT_sRGB` impractical. The following error occurs:

> [.WebGL-000075BE002A8600] GL_INVALID_OPERATION: Texture format does not support mipmap generation.

Mipmap generation is supported with WebGL 2 but only with RGBA textures (meaning `gl.SRGB8_ALPHA8`). It does not work when using RGB textures which results in `gl.SRGB8`. I believe the reason for this is the fact that `SRGB8_ALPHA8`  is color-renderable but `SRGB8` isn't. And `gl.generateMipmap()` only works with texture filterable AND color-renderable textures.

So unless the engine always uses RGBA for colors textures during a sRGB workflow, the sRGB texture formats will be hard to use.

**Comment by Mugen87** [comment]
I've created a branch with my code: https://github.com/Mugen87/three.js/tree/dev17

With `gl.SRGB8_ALPHA8`: https://raw.githack.com/Mugen87/three.js/dev17/examples/webgl_loader_gltf.html
Current: https://threejs.org/examples/webgl_loader_gltf

The examples look different. The `gl.SRGB8_ALPHA8` looks brighter in certain areas.

**Comment by WestLangley** [comment]
@Mugen87 Those examples are very helpful. It looks like the subtle differences are related to the emissive map... somehow...

One thing I did not try was to turn off ACESFilmic.

**Comment by Mugen87** [comment]
> So unless the engine always defines color textures as RGBA during a sRGB workflow, the sRGB texture format will be hard to use.

Switching the texture format to RGBA does easily work with images, image bitmaps or a canvas. However, I've realized today that it is not that easy with data texture since the applied array buffer would have a too small size. If the engine should support data textures, it would mean to internally create a bigger array buffer, copy the data with additional alpha values and also update the buffer  every time the user sets `Texture.needsUpdate` to `true.` That is tedious.

Would it be possible to exclude RGB data textures? It seems sRGB textures are normally loaded via `TextureLoader` . Are there occasions where loaders produce an instance of `DataTexture` with `encoding` set to `THREE.sRGBEncoding`?

**Comment by Mugen87** [comment]
After investigating the issue more closely, it seems that using `LinearMipmapLinearFilter` or `LinearFilter` darkens the texture. The better the filtering, the darker the output. Meaning `LinearMipmapLinearFilter` produces the darkest image:

`NearestFilter`, sRGB: https://jsfiddle.net/d0xs7wnr/
`LinearFilter`, sRGB: https://jsfiddle.net/fyu70vm2/1/
`LinearMipmapLinearFilter`, sRGB: https://jsfiddle.net/9dL5rhm4/

This also happens when using linear color space.

`NearestFilter`, linear: https://jsfiddle.net/c35txr9v/
`LinearFilter`, linear: https://jsfiddle.net/08r2qzeb/
`LinearMipmapLinearFilter`, linear: https://jsfiddle.net/f6g97a5c/

When using `gl.SRGB8_ALPHA8`, this effect does not appear. The brightness is consistent:

`NearestFilter`, sRGB, `SRGB8_ALPHA8`: https://jsfiddle.net/we2v9xob/
`LinearFilter`, sRGB, `SRGB8_ALPHA8`: https://jsfiddle.net/1fy9xed6/
`LinearMipmapLinearFilter`, sRGB, `SRGB8_ALPHA8`: https://jsfiddle.net/pwk48n7h/

**Comment by WestLangley** [comment]
It seems to me that this code block

https://github.com/mrdoob/three.js/blob/89ca03db9e391af6057f525f3255ec97f6f9c034/src/renderers/shaders/ShaderChunk/emissivemap_fragment.glsl.js#L4-L6

is doing precisely what the [Linear Interpolation Test](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureLinearInterpolationTest) hopes to prevent.

three.js interpolates first and decodes second -- and does so for all nonlinear maps.

Perhaps the code injection can be removed for WebGL 2.

**Comment by mrdoob** [comment]
> Perhaps the code injection can be removed for WebGL 2.

That makes sense to me 👍

**Comment by mrdoob** [comment]
Hmm, but what are we supposed to do with all the other encodings?

https://github.com/mrdoob/three.js/blob/89ca03db9e391af6057f525f3255ec97f6f9c034/src/renderers/webgl/WebGLProgram.js#L22-L48

**Comment by Mugen87** [comment]
In the first step, I would suggest to only bypass the inline decode for sRGB encoded textures in WebGL 2. 

Encodings like RGBE or RGBM can't be handled by WebGL so without a inline decode in GLSL the texture data have to be converted to linear space before they are uploaded to the GPU. Eventually there will be different code paths for sRGB and all other encodings.

**Comment by Mugen87** [comment]
I guess I have something ready for a closer review: https://github.com/Mugen87/three.js/commit/c767a1fe96725f0d54bb68964768e19484bcb332

One requirement for using `gl.SRGB8_ALPHA8` is the usage of `RGBAFormat`. So various places had to be changed where `RGBFormat` was previously used. Considering https://github.com/mrdoob/three.js/pull/22293#discussion_r696763207, it's probably a nice simplification anyway.

**Comment by donmccurdy** [comment]
> With WebGL 1, it is not possible to use the extension in combination with mipmap generation which makes gl.EXT_sRGB impractical.

Ouch... does this also occur in WebGL 1 with gl.SRGB8_ALPHA8?
