### ISSUE TITLE
WebGLRenderer: Use faster program cache key computation.

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#22530]
I've recently did a profile of my project, haven't done that in 4-5 months, since then three.js version has been upgraded several times. Currently on `0.132.2`

So, profile shows up that `getProgramCacheKey` takes up close to 20% of the entire time: 
![image](https://user-images.githubusercontent.com/5939063/132960860-3f9515fa-c08b-4301-ae20-0b75ce0b45e9.png)

For a bit more context, this is in the scope of the entire game, with particle simulation, IK, sound and a bunch of other stuff going on. Not just pure rendering. Here's a screenshot of what's being rendered:
![image](https://user-images.githubusercontent.com/5939063/132960916-5ed6cb6a-2b72-47e0-bab1-5807cebc23e2.png)

Here's the `WebGLRenderer.info`:
![image](https://user-images.githubusercontent.com/5939063/132960939-ab48901f-5918-46e8-b32d-af5a174fd977.png)

If you have a look at the cache key computation code, there's a lot wrong there. It's building an array of strings, that's a lot of allocation, and then there's `array.join()` which results in another string being created. All of that, just to throw the result away in the end (since no new materials are created during profiling period). 

I propose offering an override for the cache keys, or building keys in a way that avoids much of the allocation effort. Also, doing equality check on material against what's already cached can be done without materializing this "cache key" at all. I understand that it's "simple" to do what's currently being done, and I understand that doing what I propose is less easy, but we're talking about 20% of the CPU time being wasted on an application that's hardly pure rendering.

As an alternative - perhaps offer an override for cache key computation, something like "customComputeMaterialCacheKey", that would be dirty, but it would allow users like me to work around the issue.

**Comment by Mugen87** [comment]
> something like "customComputeMaterialCacheKey"

It's not a material but a program cache key. And identifying the correct program depends on many factors. I doubt it makes sense to implement the key computation on app level since you have to honor all the information from the rendering process like the engine currently does. Out of curiosity: Can you please share a live example that demonstrates how you would implement a callback like `customComputeMaterialCacheKey()`?

>  or building keys in a way that avoids much of the allocation effort.

We often thought about this but could not came up with a different solution. Can you please make a concrete suggestion how this could be implemented differently?

**Comment by donmccurdy** [comment]
If I understand correctly, `getProgramCacheKey` is not meant to be invoked on every frame — but with numbers like those, either it's taking >50ms to initialize _each_ material, or it's being invoked repeatedly. Perhaps something in the application is triggering unnecessary `getProgram` calls with newer three.js versions?

**Comment by Usnul** [comment]
> I doubt it makes sense to implement the key computation on app level since you have to honor all the information from the rendering process like the engine currently does.

I agree, I think having a custom key computation solution is a gapstop that lets people solve the problem themselves, but opens up an avenue for people to shoot themselves in the foot. 

> Out of curiosity: Can you please share a live example that demonstrates how you would implement a callback like customComputeMaterialCacheKey()?

Sure, there are plenty of shaders that are not affected by light/shadow, for example post-process shaders or various compute shaders (transform feedback). Even for standard materials, I can keep track of their equality, and when a "new" material is created - I can simply return an incremented integer. Think "hash map", similar to the current implementation in the sense that it keeps a key, but unlike three.js solution which has to be generic and doesn't know when a material changes - I have full knowledge of how my app works, so I can decide when to update the key.

> Can you please make a concrete suggestion that explains how the cache key computation could be implemented differently?

something like this:
```
class MaterialFingerprint{
 ....
 match(material:Material):boolean // check if a given material/shader matches the fingerprint
 fromMaterial(material:Material):void // populate fingerprint from a material/shader
}
```

where `MaterialFingerprint` is your a slightly more semantically rich version of `MaterialCacheKey` concept. You could then keep a map of `Map<Material, MaterailFingerprint>` and validate the material against its last known fingerprint before usage, which would be way faster. After that you use fingerprint the same way as before.

**Comment by Mugen87** [comment]
The important question is how would you compute the program key differently. I'm afraid that is not yet clear from your post.

**Comment by Usnul** [comment]
> The important question is how would you compute the program key differently. I'm afraid that is not yet clear from your post.

For my own app? - I wouldn't. I'd keep something like an object ID and re-dupe shaders myself.

For generic three.js solution? - there are many options. One step would be to separate existing giant array into logical pieces, assign those to separate fields of the `MaterialFingerprint` class so you can compare those logical pieces to the respective values from a shader in `match` implementation. 

here's roughly how the key is being computed now:
```js
const key_array : string[] = [];

const part_a : string = compute_program_property_A(program);
key_array .push(part_a);

const part_b : string = compute_program_property_B(program);
key_array .push(part_b);
...

const key_string = key_array.join();
``` 

One simple optimization here is not to build the last string and not to create the array. How? like so:

```js
class MaterialFingerprint{
	private property_a:string
	private property_b:string
	...
	
	match(program){
		if(this.property_a !== compute_program_property_A(program)){
			retunr false;
		}
		
		if(this.property_b !== compute_program_property_B(program)){
			retunr false;
		}
		
		return true;
	}
}
```

You get early rejection and don't have to materialize the key every time,

**Comment by Usnul** [comment]
Here's a small addition to what was already mentioned, here's the memory allocation trace for similar scene:
![image](https://user-images.githubusercontent.com/5939063/133850338-c557c49b-db8f-4859-b302-2456dc47a87f.png)

You'll see that **68.5**% of the garbage generated throughout normal running of the app comes just from that single area.

**Comment by donmccurdy** [comment]
We can make the function faster presumably, but if it's being called 5,000 times in 20s then something else seems wrong. Is it possible to tell if it was invoked the same number of times in the earlier there.js version?

**Comment by Usnul** [comment]
I don't know if this is a regression issue. I don't keep backwards compatibility generally. Sorry.

**Comment by donmccurdy** [comment]
I can reproduce a similar issue on the [WebGL | Animation | Keyframes](https://threejs.org/examples/#webgl_animation_keyframes) example, tracking back to https://github.com/mrdoob/three.js/pull/21788 (r129) and probably similar removals like `vertexTangents`. These changes allowed greater reuse of a Material, with the library managing associated shader programs automatically. 

In `WebGL | Animation | Keyframes`, the same material is reused by a Mesh and a SkinnedMesh; that wasn't supported before. But a side effect of the new support is that the material's `needProgramChange` flag is hit one or more times per frame, as we render the material with a different mesh...

https://github.com/mrdoob/three.js/blob/7f6a0990feec2946225147ab2a4fbcaf69dcb359/src/renderers/WebGLRenderer.js#L1565-L1567

...invoking `getProgramCacheKey` each time — causing the additional CPU time shown above (and probably some GC cycles not shown above). I think the same thing is likely happening with @Usnul's application; there may be other similar cases like reusing a Material on meshes with and without vertex tangents.

So realistically there are two problems here:

1. `getProgramCacheKey` is expensive
2. three.js now invokes `getProgramCacheKey` more often

I do think I like the @Usnul's suggestion in https://github.com/mrdoob/three.js/issues/22530#issuecomment-918270143. It would certainly result in less GC, and might also be faster. But I am hoping we can find a way to avoid calling `getProgramCacheKey` at all, if the materials themselves have not changed since the last render. As it is, this does represent a performance decrease in r129.

**Comment by donmccurdy** [comment]
I'm little worried about the added complexity of multiple cache keys, but one option might be to keep a cheaper "fastProgramCacheKey" to map a single material to its program variants. Since there are not many possible combinations there, it could just be a cheaper bit mask instead of a string. For example:

```js
const cacheKey = SKINNING & VERTEX_TANGENTS & MORPH_TARGETS;
```

**Comment by WestLangley** [comment]
@donmccurdy is correct. `getProgramCacheKey()` is called (multiple times) every frame in certain uses cases. There appear to be many use cases that suffer from this.

Starting in r130, transparent, double-sided materials appear to suffer from this, for example.

**Comment by mrdoob** [comment]
Something I was considering after [the introduction of the `transmision`, `sheen`, ... getters/setters](https://github.com/mrdoob/three.js/blob/8ea885cd81a5932fa9c28dcbdba208c69f533966/src/materials/MeshPhysicalMaterial.js#L96-L148) is to do the same for *all* the maps.

Doesn't solve the particular problem being talked about here, but it helps a bit by moving out of the renderer the logic of deciding when a shader needs to be recomputed.

**Comment by Usnul** [comment]
getters/setters updating version would help.
You could then make a reliable assumption that the unique state of a material is describable by its ID and the version. Keep the private values out of the documentation and if someone touches the `_values` directly - that's on them.

**Comment by dbuck** [comment]
Just coming across this here also, specifically notable in larger 3d-tiles tilesets with custom shaders, each new tile/material allocating the string-concat key adds up QUITE quickly with thousands of tiles when unable to share material instances.

Is there a reason that something like the [NodeMaterial.getHash](https://github.com/mrdoob/three.js/blob/HEAD/examples/jsm/nodes/materials/NodeMaterial.js#L72-L83) wouldn't work as a lighter weight key than .joining the full fragment/vertex shaders?

**Comment by gonnavis** [comment]
Hello, looking forward for a fix.
I'm facing severe performance issue in project which has many bone/skins.
https://github.com/mrdoob/three.js/issues/23106

**Comment by donmccurdy** [comment]
Continuing from #23106...

> Sorry that update to r136 does not reduce the call many, still get 13 ~ 17 times.
Not the same as r129 which only 8 times.

Note that https://github.com/mrdoob/three.js/pull/22960 and https://github.com/mrdoob/three.js/pull/23022 should improve the _performance_ of `getProgramCacheKey`, but won't reduce the number of times it is called back to the previous number. I'm not sure whether that is necessarily a goal. Do we have an example that still has a clear framerate regression in r136 vs r128?

**Comment by gonnavis** [comment]
At first, I think it's very easy to test through my demo, just change the `mutants=` queryString and check the stats.
But turned out that no very big difference between them, though the r136 has more calls of `getProgram/CacheKey`.
So just duplicate the same many times should not related to this problem.
![image](https://user-images.githubusercontent.com/10785634/147607759-b49f5995-b6be-465f-a12f-d54b649475c1.png)
![image](https://user-images.githubusercontent.com/10785634/147607807-412404f5-426d-4975-895a-61e209abe83b.png)

But on another more complex project, I really even get worse performance, lower fps after upgrade from r133 to r136, but hard to publish demo.

**Comment by gero3** [comment]
@gonnavis I'll have a look at your example to see what's going on between version r129 vs r136.

**Comment by gero3** [comment]
@gonnavis I've looked into your example and noticed that you've added console.log call in the getProgramCacheKey function. console.log is a not very performant function. This function can take up to 100 microseconds for each call to 'console.log' when the devtools are open.

Testcase => [link](https://jsben.ch/R3mGM)

This is my result without devtools open.
![image](https://user-images.githubusercontent.com/155535/147613789-52dba26a-32bd-437e-b49f-57b3a0fedcdc.png)

This is my result with devtools open.
![image](https://user-images.githubusercontent.com/155535/147614082-1ebb6e0f-9ad0-49ef-8eba-f25ef993c62b.png)

I hope this shows that calling console.log has a big impact on the performance of javascript.

So I've updated your examples to remove the call to console.log & to me it seems r129 and r136 perform a lot better than r135.

[r129 example](https://raw.githack.com/gero3/annihilate/threejsR129GetProgram/index.html?mutants=100)[comparision source code](https://github.com/gonnavis/annihilate/compare/threejsR129GetProgram...gero3:threejsR129GetProgram)
[r135 example](https://raw.githack.com/gero3/annihilate/threejsR135GetProgram/index.html?mutants=100)[comparision source code](https://github.com/gonnavis/annihilate/compare/threejsR135GetProgram...gero3:threejsR135GetProgram)
[r135 example](https://raw.githack.com/gero3/annihilate/threejsR136GetProgram/index.html?mutants=100)[comparision source code](https://github.com/gonnavis/annihilate/compare/threejsR136GetProgram...gero3:threejsR136GetProgram)

PS: the reason I don't look at the profiles of javascript is that they are inherently unreliable for comparison between codebases. The javascript profiler causes functions to deoptimize which make their performance drop a lot compared to other functions. As far as I could tell getProgramCacheKey, getShaderStage and getProgram in r136 are of those functions that are unoptimized.

You can see this clearly when profiling the following example [Webgl_performance_shader](https://threejs.org/examples/webgl_performance_shader.html). This example for me drops from a stable 60FPS to an unstable 45-46fps.
the drop in the middle is when I created a javascript profile.
![image](https://user-images.githubusercontent.com/155535/147617223-8c13e6b0-38c0-4e9d-be56-22581333e2e1.png)

**Comment by gonnavis** [comment]
Oh, I somewhat forgot the influence of devtool. I'll continue to test both projects, as well as your examples, and keep an eye on the impact of devtool.
Thank you very much for your testing!

**Comment by donmccurdy** [comment]
I was under the impression that the regression was introduced _in_ r129 – if that's correct, the goal of this issue would be to get back to performance on this code path similar to r128, not r129? If #22960 and #23022 have fixed those issues then perhaps this can be closed.

**Comment by gero3** [comment]
> I was under the impression that the regression was introduced _in_ r129 – if that's correct, the goal of this issue would be to get back to performance on this code path similar to r128, not r129? If #22960 and #23022 have fixed those issues then perhaps this can be closed.

Like you said before, there were 2 issues surrounding getProgramCacheKey.
- getProgramCacheKey is expensive
- three.js now invokes getProgramCacheKey more often

Both #22960 and #23022 only resolve the fact that getProgramCacheKey was very expensive in r135. This was also the target of the example [webgl_performance_shader](https://threejs.org/examples/webgl_performance_shader.html). 

The amount of calls to getProgramCacheKey is still more often than r129 and earlier versions.

**Comment by gonnavis** [comment]
Added an r128 version, and adopted gero3's improvment to all version examples:

r128: `getProgramCacheKey` got called most 0, sometimes 2 ~ 15 times.
https://raw.githack.com/gonnavis/annihilate/threejsR128GetProgram/index.html?mutants=100

r129: around 35fps, `getProgramCacheKey` got called most 8 times.
https://raw.githack.com/gonnavis/annihilate/threejsR129GetProgram/index.html?mutants=100

r135: `getProgramCacheKey` got called most 17 ~ 19 times.
https://raw.githack.com/gonnavis/annihilate/threejsR135GetProgram/index.html?mutants=100

r136: `getProgramCacheKey` got called most 17 ~ 19 times.
https://raw.githack.com/gonnavis/annihilate/threejsR136GetProgram/index.html?mutants=100

Tough the call count of `getProgramCacheKey` very different, but the fps all round 35fps on my pc when not open devtool.
Seems no perfromance difference between all versions of this example.

> I was under the impression that the regression was introduced in r129

It should be, by my test results.

**Comment by Mugen87** [comment]
I see no difference in FPS when using the above links.

TBH, the shared URLs are not good test case for profiling the program cache key overhead since way too many things happen in your app. Please use an updated version of the simplified `webgl_performance_shader` to demonstrate performance regressions.

In general, the number of times `getProgramCacheKey()` varies due to changes in the engine. The sole number of invocations is no indicator for better or worse performance.

**Comment by gonnavis** [comment]
Still surprised why the profiling of chrome devtool is sooo wrong, misleading me and Usnul to the wrong direction.

> PS: the reason I don't look at the profiles of javascript is that they are inherently unreliable for comparison between codebases. The javascript profiler causes functions to deoptimize which make their performance drop a lot compared to other functions. As far as I could tell getProgramCacheKey, getShaderStage and getProgram in r136 are of those functions that are unoptimized.

> ![image](https://user-images.githubusercontent.com/10785634/147741403-fb35cdb0-c0fc-4fb1-9de3-a14fe4d06bab.png)

> ![image](https://user-images.githubusercontent.com/10785634/147741437-bca9a8d5-efd3-44d4-aba3-d6eb3b7056da.png)

**Comment by Mugen87** [comment]
@gero3 did a great job in `r136` in improving the performance of `getProgramCacheKey()`. This improvement is also clearly measurable with `webgl_performance_shader`.

I'm not surprised that the world matrix update routine consume a lot of time, especially in complex scene graphs. However, this issue is know and was discussed multiple times in the project. The current recommendation is to set `matrixAutoUpdate` to `false` and manually trigger matrix updates if necessary.

However, I'm not a fan of this policy because it is complicated and thus error-prone. The engine should solve this issue and not delegate this task to apps. Unfortunately, solving this issue requires changes in the engine which are not accepted by all project members. I doubt that we can make progress in this issue anytime soon.

**Comment by gonnavis** [comment]
Oh, I'm focused on the chrome devtool profiles' wrong result of `getProgramCacheKey`,
`updateMatrixWorldTime` is just used for comparison

**Comment by gonnavis** [comment]
Made another example https://raw.githack.com/gonnavis/annihilate/GetProgramCacheKeyTimeVsUpdateMatrixWorldTime2/index.html
Once again proved that the chrome devtool profiles have extremely serious errors.
This is the screenshot on my current pc status, not sure if the same on yours
![bddeb4d56619cb0cd425879f35695f0](https://user-images.githubusercontent.com/10785634/147750548-9df747de-e6ce-41b2-bef7-4b1e93c32193.png)

I found that `console.log()` will increase the inaccuracy, this example has so many `console.log()` so the deviation very obvious.
If delete some `console.log()`, the deviation will decrease.
But `console.log()` is not the only cause, because other projects that has not repeated `console.log()` also has serious deviation.

**Comment by mrdoob** [comment]
Seems like the issue has been addressed.
Better to discuss browser issues in a different place.
