### ISSUE TITLE
BufferGeometry loss translate when toJSON

### ISSUE THREAD

**Issue by wasabia** [mrdoob/three.js#22586]
```
var boxGeo = THREE.BoxGeometry(5,5,5);
boxGeo.translate(10, 20, 10);
boxGeo.toJSON()
```

**Comment by Mugen87** [comment]
Yes, this is done on purpose since we only serialize the parameters of geometry generators and not the resulting buffer data.

You can easily fix this by creating an instance of `BufferGeometry` and copy the respective buffer and group data before calling `toJSON()`. Or you do this little hack before calling `toJSON()` to force raw geometry output:
```js
delete boxGeo.type;
delete boxGeo.parameters;
```

Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by WestLangley** [comment]
>Yes, this is done on purpose...

Returning the incorrect answer on purpose?

I would consider this to be a bug -- even if it was implemented on purpose.

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/pull/22589#issuecomment-927332498

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/pull/22589#issuecomment-927333854

**Comment by Mugen87** [comment]
@WestLangley After reconsidering this topic I think your solution proposed in https://github.com/mrdoob/three.js/pull/22589#issuecomment-927971326 is the best way to fix this bug. The big advantage of introducing a flag in `BufferGeometry` is that it _defers_ any mutation to the object's type until a serialization happens. Many application never serialize so we don't break anything if they transform the geometry but rely on the original object type. Meaning checks on let's say `type='BoxGeometry'` will still work.

Next to `applyMatrix4()`, it's only correct when `computeVertexNormals ()`, `normalizeNormals()` and `computeTangents()` also set the flag to `true`. Considering what these methods to, we maybe want to name the flag `_dirty` or `_mutated`. I'm not feeling strong about the name so `_transformed` would be okay with me, too.

Are you willing to make a PR implementing this approach?
