### ISSUE TITLE
USDZExporter does not work with MeshoptDecoder

### ISSUE THREAD

**Issue by wallabyway** [mrdoob/three.js#22609]
There's an error when USDZExporter encodes a USDZ file based on a GLTF compressed with [MeshOpt](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression) compression.

For example, 
if I compress cube.glb with MeshOpt (gltfpack -I cube.glb -o cube.zeux.glb), then will preview correctly inside three.js.
When I click the AR button, it causes the following error.

![usdz-error](https://user-images.githubusercontent.com/440241/135382766-d8dcec8d-ff23-4c54-9b06-1664a2703945.jpg)

and the error refers to 

line 291:
```js
array.push( `(${ data[ i + 0 ].toPrecision( PRECISION ) }, ${ data[ i + 1 ].toPrecision( PRECISION ) }, ${ data[ i + 2 ].toPrecision( PRECISION ) })` );
```

**To Reproduce**

1. Compress `cube.glb` or `damaged-helmet.glb` with `gltfpack -I cube.glb -o cube.zeux.glb` 
2. Load the glb using 

```js
			import { MeshoptDecoder } from 'https://wallabyway.github.io/gltf-imaginate-test/jsm/meshopt_decoder.module.js';

...
				const loader = new GLTFLoader().setPath( 'glb/' );
				loader.setMeshoptDecoder(MeshoptDecoder);
				loader.load( 'output.glb', async function ( gltf ) {
```
3. Host and Open index.html on iPhone, and click on 'AR' button
4. Host and Open index.html on desktop browser, and click on 'AR' button, and refer to error in debug console.

***Live example***

* [jsfiddle-dev](https://jsfiddle.net/wallabyway/08hjdg2w/1/)

**Expected behavior**

Expect the compressed .glb to appear in Quicklook

**Screenshots**

![meshOpt-no-usdz-threejs](https://user-images.githubusercontent.com/440241/135383589-e86ecb44-3c99-496a-84d3-320d78f7a684.jpg)

**Platform:**

 - Browser: [Chrome]
 - Three.js version: [latest]

**Comment by donmccurdy** [comment]
The issue here is that USDZExporter accesses `attribute.array` on vertex attributes, which won't work for geometry with interleaved attributes:

https://github.com/mrdoob/three.js/blob/0a5fa7b69158a9e9beeab8904a8f31cdd9c44eaf/examples/jsm/exporters/USDZExporter.js#L287-L293

Using `attribute.getXYZ( ... )` instead should work fine. Also note that the vertex attributes will likely be normalized, I'm not sure whether USDZExporter accounts for this. You can recreate the same error with these models and the three.js editor:

[Archive.zip](https://github.com/mrdoob/three.js/files/7256588/Archive.zip)

^One model is interleaved, the other is not. Only the interleaved copy will have errors. Normalization and compression will be lost when converting to USDZ, so file size will increase.

**Comment by wallabyway** [comment]
That fixed it - thanks !
Loads very quickly.
https://github.com/wallabyway/quicklook-example
