### ISSUE TITLE
Rendering issues with shadow-casting, morphed meshes.

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#22619]
His shadow is working so hard but he just sits [there](https://threejs.org/examples/webgl_animation_multiple.html) motionless:

https://user-images.githubusercontent.com/242577/135541123-36ee92d3-a2d6-4c76-a661-dde9438d6b35.mp4

**Comment by Mugen87** [comment]
That is strange. On my Windows machine, the second parrot is completely missing.

I also see the following warning in Chrome:

> [.WebGL-00001F28000A6A00] GL_INVALID_OPERATION: Two textures of different types use the same sampler location.

This issue is related to the new morph target code. As a workaround, affected users can fallback to `WebGL1Renderer` if possible. 

It is strange that [webgl_shadowmap](https://threejs.org/examples/webgl_shadowmap) does not show this issue.

**Comment by Mugen87** [comment]
The E2E screenshot also shows the wrong result. There should be two parrots visible.

**Comment by Mugen87** [comment]
Um, an even simpler workaround is to clone the material of the second parrot.

@makc Can you please verify this by adding `clonedMesh.material = clonedMesh.material.clone();` right after:

https://github.com/mrdoob/three.js/blob/b1ede8160b5aefe18c7ec29f2af80f78b0ffd911/examples/webgl_animation_multiple.html#L152

**Comment by makc** [comment]
@Mugen87 
> adding clonedMesh.material = clonedMesh.material.clone();

has no effect whatsoever over here
