### ISSUE TITLE
webXR shows "AR session supported" on unsupported device

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22800]
**Describe the bug**
This phone does not have ar-core support , but the start ar buttons is present 
& `navigator.xr.isSessionSupported('immersive-ar')` returns true

but clicking on the button asks camera permissions then crashes (screenshot has error message)

**Expected behavior**

This device does not support google ar core , so `navigator.xr.isSessionSupported('immersive-ar')` should return false as
AR experiences on Android can only be run on an ARCore supported device. 

**Screenshots**
![XR](https://user-images.githubusercontent.com/6885294/140785318-23886562-ebdb-418b-8bab-eb8976c09765.png)

**Platform:**

 - Device: [Mobile: Samsung galaxy M30]
 - OS: [Android]
 - Browser: [Chrome]
 - Three.js version: [r135]

**Comment by asemanh** [comment]
Hi @optimus007 , do you have a repro link we can use to debug?

**Comment by Mugen87** [comment]
I guess you can use one of the official `three.js` examples. E.g. https://threejs.org/examples/webxr_ar_cones

**Comment by optimus007** [comment]
@samaneh-kazemi 

https://threejs.org/examples/?q=webxr#webxr_ar_cones
https://threejs.org/examples/?q=webxr#webxr_ar_hittest
https://threejs.org/examples/?q=webxr#webxr_ar_lighting
https://threejs.org/examples/?q=webxr#webxr_ar_paint

and the https://github.com/mrdoob/three.js/blob/master/examples/jsm/webxr/ARButton.js used to create the start AR button

**Comment by 1337816495** [comment]
### Summary
This error comes from WebXR API, not three.js (I think) .

### details
Based on my experience, 
When the test machine meets the following 2 conditions, `navigator.xr.isSessionSupported('immersive-ar')` will always return `true` (fulfilled) :
① phone
② https
Otherwise it will return false.

When I use a mobile phone (not supporting ARcore) to visit a WebXR site that uses https, the following events will occur in sequence:
① `navigator.xr.isSessionSupported('immersive-ar')` will return `true`(fulfilled)
② A pop-up box in the middle of Chrome asks me “whether to grant AR permissions to the site” (If the user has granted this permission to the site, this step will not appear) 
③ I allow to grant AR permissions to this site
④ The pop-up box at the bottom of Chrome says "ARCORE needs to be installed"
⑤ I click "install"
⑥ After a short loading animation, the phone jumps to the ARCORE download page of the App store (Some phones may not automatically redirect to the App store, this is most likely because ARCore is not listed on the App Store of this phone, at this time, you can only download ARcore on Google Play by yourself)
⑦ Install ARCore
⑧ The App Store pop-up prompts "The app is not adapted to your device, and abnormal conditions such as freezes and flashbacks may occur during operation. It is recommended to wait for the app developer to solve the adaptation problem before trying to install." (This is why you see "crashes")
⑨ Restart the site and start the AR program (immersive-ar) 
⑩ crashes
 
Obviously, this bug (`navigator.xr.isSessionSupported('immersive-ar')` will always return `true` on phone that do not support ARCore) comes from the WebXR API.

### Code

```js

check().then(is_supported => {

    if (!is_supported) {

        button.textContent = "Not Support";

        return;

    }

    button.textContent = "Open";
    button.addEventListener("click", _ => {

        navigator.xr.requestSession("immersive-ar", {}).then(session => {

            renderer.xr.setReferenceSpaceType("local");
            renderer.xr.setSession(session);

        });

    });

});

function check() {

    return (new Promise(function (resolve) {

        const is_support_https = _checkHttps();

        if (!is_support_https) {

            resolve(false);

            return;

        }

       _ checkImmersiveAr().then(resolve);

    }));

};

function _checkHttps() {

    return window.isSecureContext;

}

function _checkImmersiveAr() {

    return (new Promise(function (resolve) {

        if (!("xr" in window.navigator)) {

            resolve(false);

            return;

        }

        navigator.xr.isSessionSupported("immersive-ar").then(resolve);

    }));

}
```
Most of the code related to "three.js" is omitted

### Other
I have a device that supports ARCore, which can run the WebXR application built by the above code normally

**Comment by Mugen87** [comment]
Closing then. I'm not sure where it's best to report this issue but the browser vendor might be a good start.
