### ISSUE TITLE
DragControls: Expose raycaster. Reopen, another PR ?

### ISSUE THREAD

**Issue by draibolit** [mrdoob/three.js#22852]
My PR has a problem.

Related to  #22844, it needs the API assignment which I forgot.

I should put at the line 215 as following: 
```
		this.getRaycaster = getRaycaster;

```
Tested with my actual developing app.

Any solution?

PS: Anyway, this is quite a stranger way to work with javascript class, why not separate those APIs into class methods ?

**Comment by Mugen87** [comment]
I've fixed it directly on `dev`. c547a74f901d1e608d546deaa3c0be20b6f7d868

**Comment by Mugen87** [comment]
> PS: Anyway, this is quite a stranger way to work with javascript class, why not separate those APIs into class methods ?

When we converted the code base to classes, we've realized that it's complex to transform certain modules to a pure class syntax since the scoping of internal variables would be different. 

At least when `DragControls` was initially developed, JavaScript had no concept of private fields. So it was decided to use a design that easily enables private and public properties/methods.
