### ISSUE TITLE
power of 2, but non-square, compressed textures with provided mipmaps do not render

### ISSUE THREAD

**Issue by bunnybones1** [mrdoob/three.js#22875]
Some tools like BinomialLLC's crunch, or Google's ETC2Comp, don't create all the miplevels up to 1x1, for nonsquare textures.

WebGL seems to fail on textures that don't have all the mip levels up to 1x1.

This isn't really an issue with three.js necessarily, but when textures with mipmaps are loaded, but are missing the highest levels, could three.js be made to patch in some dummy levels to make them not break WebGL?

For instance, a texture with mip resolutions of 16x4, 8x2 and 4x1, could be made to work by adding in the missing 2x1 and 1x1.

Some related discussions:

https://github.com/BinomialLLC/crunch/issues/40

https://github.com/google/etc2comp/issues/31

**To Reproduce**

1. load the attached test texture 
[test-missing-mip-levels.s3tc.COMPRESSED_S3TC_DXT_EXT.ktx.zip](https://github.com/mrdoob/three.js/files/7584851/test-missing-mip-levels.s3tc.COMPRESSED_S3TC_DXT_EXT.ktx.zip)
2. try to use it in a material
3. See WebGL error

**Expected behavior**

The texture should render with supplied mipmaps

**Screenshots**

<img width="426" alt="Screen Shot 2021-11-20 at 12 31 02 PM" src="https://user-images.githubusercontent.com/453513/142947680-c1d9ab13-e9d7-4985-8dca-bc1d9bb916ef.png">

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: 134.0

**Comment by donmccurdy** [comment]
Unfortunately, this is a limitation of WebGL 1.0 – to use mipmaps with compressed textures, the textures must have square, power-of-two dimensions. Those mipmaps must be included with the texture, because we can't generate compressed mipmaps at runtime.

If I understand correctly WebGL 2.0 does allow more flexibility here, and https://github.com/KhronosGroup/WebGL/issues/3117 is the relevant issue. I'm not sure if there's work we would need to do in three.js to get this working with WebGL 2.0 or if that's all under the hood.

Related:

- https://github.com/KhronosGroup/KTX-Software/issues/345

**Comment by bunnybones1** [comment]
Yeah, completely understandable.

Interestingly though, Binomial's crunch has its own bug, where if you compress a texture that is wider than it is tall, it DOES generate the rest of the mips to 1*1, and those textures do load and render fine, even though they're nonsquare.

For our project, I'll try loading in a compressed line of pixels with mipmaps, that I can copy levels from, as other loaded textures exhibit the problem.

**Comment by Mugen87** [comment]
> I'm not sure if there's work we would need to do in three.js to get this working with WebGL 2.0 or if that's all under the hood.

Indeed 👍 .
