### ISSUE TITLE
dat.gui.min.js deleted

### ISSUE THREAD

**Issue by haehn** [mrdoob/three.js#22900]
**Describe the bug**

The three.js/examples/js/libs/dat.gui.min.js file was deleted 2 days ago. I understand the switch to lil-gui but please keep the old file at the old url for backwards compatibility.

**To Reproduce**

***Code***

***Live example***
**Expected behavior**

**Screenshots**

**Platform:**
All

**Comment by marcofugaro** [comment]
Even if it was advised years ago, it is not safe to rely on resources hosted on the three.js website, because it has no version control and APIs might change from release to release.

You can use [unpkg.com](https://unpkg.com/) instead, it has proper versioning and your examples won't break.

Replace the link with this:
https://unpkg.com/dat.gui@0.7.7/build/dat.gui.min.js

**Comment by Mugen87** [comment]
Indeed, it was decided that we don't want to retain such files for these use cases. 

Always use versioned CDN URLs like suggested by @marcofugaro .
