### ISSUE TITLE
MeshPhysicalMaterial: Scale-dependent volumetric attenuation?

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#22971]
**Describe the bug**

Color tone is big different between model-viewer and threejs sample

**To Reproduce**
Compare same transmission glb between model-viewer and threejs sample

**Expected behavior**

Color tone is similar

**Screenshots**

![image](https://user-images.githubusercontent.com/6780177/144884339-ad6ca662-4d7a-4374-879a-ff09e734eff6.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r135]

**Comment by donmccurdy** [comment]
The difference here is probably the scale of the scene. Some viewers (I'm not sure what the screenshot on the left is?) might resize the model to fit a bounding box the camera orbits around. Attenuation parameters are defined in meters and would be affected by that. Just for a quick test I made a version of the model scaled up by 10x and tested in https://gltf-viewer.donmccurdy.com/ – you can see it's even darker than the two above with that change:


![Screen Shot 2021-12-06 at 9 05 26 AM](https://user-images.githubusercontent.com/1848368/144889829-f9bb0f8f-c926-470e-a93b-2a4de2806093.png)

**Comment by whatisor** [comment]
That means Model Viewer tried to scale it and get unidentified color.
Leftside is orignal gltf without scale.

**Comment by whatisor** [comment]
I think Scale should not change "material".
Then we can assure design from gltf is kept when we export it from design tool.

**Comment by donmccurdy** [comment]
glTF's `attenuationDistance` property, or Blender's _Volume Absorption → Density_ (same thing, inverted), are both scale-dependent parameters because they represent the density of the object's interior. We can't match the expected result without also considering scale for volumetric effects.

That said, perhaps authors of viewers can do something to avoid this. /cc @elalish any ideas? There seems to be a lot of variance in different viewers on this one.

[DragonAttenuation.glb.zip](https://github.com/mrdoob/three.js/files/7665643/DragonAttenuation.glb.zip)

**Comment by elalish** [comment]
Hmm, no ModelViewer doesn't scale anything; the scale must be kept consistent from the file, especially for AR. I would  say the  other file must be applying  some scale factor; perhaps it thinks the file is not in meters? As for consistency, we actually have pretty  decent renderer consistency  on this: https://modelviewer.dev/fidelity/#khronos-DragonAttenuation

There was much discussion of this behavior in the glTF working group  and we decided it should be this way since we do  physically-based rendering. The fact is, a larger object made of the  same material *will* look darker. Artists have been ignoring scale for quite some time, but especially now that we have AR, physical scale is critical. All glTFs are in meters. Care has even been taken that if a single mesh is reused  at different scales it will have appropriate physical color (i.e. larger ones are darker).

**Comment by donmccurdy** [comment]
Thanks @elalish! 

@whatisor since the comparison at https://modelviewer.dev/fidelity/#khronos-DragonAttenuation shows that three.js (represented by `<model-viewer>`) does render this model correctly, there is presumably something different in the left-hand screenshot. If you can share code that is not scaling the scene in any way, but still doesn't render the expected result, I'm happy to re-open this issue and investigate.

Also note that quantization or meshopt compression may decrease the scale of a mesh, applying an inverse scale to the vertex data for the same final size. Since scaling the mesh mesh affects material parameters and scaling the vertex data does not, some care needs to be taken by tools implementing quantization or meshopt compression to output the correct `material.thickness` value.
