### ISSUE TITLE
Support 64bit float in PLY loader

### ISSUE THREAD

**Issue by christianbrugger** [mrdoob/three.js#23006]
**Is your feature request related to a problem? Please describe.**

In our projects points are very large and we need 64 bit float precision to properly display them.

When using the PLY loader the files are correctly parse, however at the end the arrays are converted to `Float32BufferAttribute`. 

This makes the data unusable.

**Describe the solution you'd like**

Make the PLY loader use `Float64BufferAttribute` in the `postProcess` function ([Source](https://github.com/mrdoob/three.js/blob/c8753221b3e6b0580b79a899159a6901014e501c/examples/jsm/loaders/PLYLoader.js#L317-L362))

**Describe alternatives you've considered**

Create an option to output the data as 32 bit or 64 bit buffers.

**Additional context**

I changed locally the attribute and the class works still perfectly.

**Comment by christianbrugger** [comment]
We are using [Potree](https://github.com/potree/potree) to render the imported PLY. It uses three.js as a backend and gives us access to the scene object. When I add it to that it gets properly rendered. I don't know how they adapted the pipeline to accommodate for that, but it seems to work with the `Float64BufferAttribute`.

What else

**Comment by mrdoob** [comment]
@m-schuetz any pointers at how we should handle this?

**Comment by m-schuetz** [comment]
Models with large coordinates are typically handled as follows in Potree:

* Compute the minimum position
* Subtract the minimum from all positions. Afterwards, the position buffer can be turned into a Float32Array
* Use the minimum as the position of the SceneNode, so that the vertices get moved back to where they are supposed to be.

For this to work, the worldView matrix must be computed on javascript side in double precision. The huge coordinates of the world matrix and the reversely huge components of the view matrix will cancel each other out, and the resulting worldView matrix can then be cast to a Float32Array and used in a shader. 

I can't remember if I did anything to the PlyLoader to make it work in Potree. Do you have an example available, @christianbrugger ?

**Comment by Mugen87** [comment]
@christianbrugger Sorry, but this issue needs to be solved on application level. Loaders in general return vertex position data as FP32 which is sufficient for most use cases. Besides, we can't work with higher precision on the GPU anyway.
