### ISSUE TITLE
postprocessing: logarithmic depth value to linear depth value

### ISSUE THREAD

**Issue by ligaofeng0901** [mrdoob/three.js#23072]
**Is your feature request related to a problem? Please describe.**

When I use this example https://threejs.org/examples/webgl_postprocessing_ssr.html in my project，it doesn't work as I expected. Then I found this is becasue I enable logarithmicDepthBuffer in WebGLRenderer. In ssr post pass, it reconstructs view position from depth buffer, but it needs a linear depth value. Is it possible converting the logarithmic depth value to an accurate linear depth value?

**Describe the solution you'd like**

For now, only to disable the logarithmicDepthBuffer can get a correct result. This is not ok in a large open world, when camra is too far, the z fighting issue occurs.

**Comment by WestLangley** [comment]
@ligaofeng0901 I assume you are requesting help modifying the fragment shader of `SSRDepthShader` to support a logarithmic depth buffer. Is that correct?

Are you able to read and post on the [three.js forum](https://discourse.threejs.org)?

**Comment by ligaofeng0901** [comment]
> @ligaofeng0901 I assume you are requesting help modifying the fragment shader of `SSRDepthShader` to support a logarithmic depth buffer. Is that correct?
> 
> Are you able to read and post on the [three.js forum](https://discourse.threejs.org)?

Sorry, I don't think that's what all I want.  `SSRDepthShader` is just to visualize the depth value on screen, the real depth value is written by WebGLRenderTarget by passing the option `depthTexture`, then in the postprcocessing fragment shader, we can read the depth value by `texture2D(tDepth, uv).x`. The depth value is useful for some situations, like computing view position, world position, etc. Thus we can do raymarch to implements ssr.
I have searched for solutions for a while both in the repository and forum. 
https://discourse.threejs.org/t/reconstruct-world-position-in-screen-space-from-depth-buffer/5532 in this post, there is a solution for reconstruct world position by depth value, and I have tested that it works fine in linear depth.
https://discourse.threejs.org/t/logarithmic-depth-value/11003 in this post, the author looks for a way to convert logarithmic depth to linear depth, and there's no reply. 
And I tried to get world position in postprocessing when using logarithmic depth, and it never result a correct value. So If it's can be resolved, I hope there's a built-in shader function like 'logarithmicDepthToLinear', or 'getWorldPositionByDepth'.

**Comment by ligaofeng0901** [comment]
Finally, I found https://stackoverflow.com/questions/40373184/world-space-position-from-logarithmic-depth-buffer,  it solved my problem. just like below
`
float linearize_depth(in float depth){
    float a = cameraFar / (cameraFar - cameraNear);
    float b = cameraFar * cameraNear / (cameraNear - cameraFar);
    return a + b / depth;
}

float reconstruct_depth(const in vec2 uv){
    float depth = texture2D(tDepth, uv).x;
    return pow(2.0, depth * log2(cameraFar + 1.0)) - 1.0;
}

float getDepth(vec2 uv) {
    #if defined( USE_LOGDEPTHBUF ) && defined( USE_LOGDEPTHBUF_EXT )
        return linearize_depth(reconstruct_depth(uv));
    #else
        return texture2D(tDepth, uv).x;
    #endif
}
`
maybe it can help others😁.

**Comment by Yincognyto** [comment]
@WestLangley , @Mugen87 

Why aren't the functions mentioned by @ligaofeng0901 [above](https://github.com/mrdoob/three.js/issues/23072#issuecomment-1000840541) (or a suited version of them) already integrated in the [packing](https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/packing.glsl.js) shader chunk and the matter is closed as completed? The code should be merged with the library, there shouldn't even be a PR asking for it, since it's along the lines of other functions there and it allows the handling of logarithmic values.

Example (naming functions could be better, I just tried to follow the way other functions were named in the [packing](https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/packing.glsl.js#L47) chunk):
```js
float logarithmicToStandardDepth( const in float logDepth, const in float near, const in float far ) {
  return pow(2.0, logDepth * log2(far + 1.0)) - 1.0;
}

float standardToPerspectiveDepth( const in float stdDepth, const in float near, const in float far ) {
  return far / (far - near) + far * near / (near - far) / stdDepth;
}
```
And then the user would do in his shader (this is what worked for me to port some BabylonJS shader to ThreeJS):
```js
float obtainDepth( sampler2D deptharray, vec2 coordinates, const in float near, const in float far ) {
  float depth = texture2D(deptharray, coordinates).x;
  #if defined( USE_LOGDEPTHBUF ) && defined( USE_LOGDEPTHBUF_EXT )
    return viewZToOrthographicDepth(perspectiveDepthToViewZ(standardToPerspectiveDepth(logarithmicToStandardDepth(depth, near, far), near, far), near, far), near, far);
  #else
    return viewZToOrthographicDepth(perspectiveDepthToViewZ(depth, near, far), near, far);
  #endif
}
```
Or in a slightly different fashion:
```js
float obtainDepth( sampler2D deptharray, vec2 coordinates, const in float near, const in float far ) {
  float depth = texture2D(deptharray, coordinates).x;
  #if defined( USE_LOGDEPTHBUF ) && defined( USE_LOGDEPTHBUF_EXT )
    depth = standardToPerspectiveDepth(logarithmicToStandardDepth(depth, near, far), near, far);
  #endif
  return viewZToOrthographicDepth(perspectiveDepthToViewZ(depth, near, far), near, far);
}
```

I was lucky to find this and solve porting some code from BabylonJS, but I doubt other users have the inspiration to look for this here. I was baffled to see something like this isn't yet included in the library, the only reason I could think of was that the value of the [logDepthBufFC](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1631-L1632) constant could be subject to change in the future (hence the log to std formula would change as well)...
