### ISSUE TITLE
Clarify the language on the webXR button failure cases

### ISSUE THREAD

**Issue by brandelf** [mrdoob/three.js#23099]
I have found that the language on the default webXR button is misconstrued by many users to experiences I create. When they visit on a browser that says "VR NOT SUPPORTED," they often conclude that it's the _page_ that doesn't support it, rather than the device/browser.

**Describe the solution you'd like**

While I'm able to make my own modifications to the VR button capability, I think the defaults matter. Revising the language to indicate that it's the _device_ that doesn't support XR would encourage users to visit on a device that does. It would be helpful to auto-generate the QR code for the URL for easy access via camera, but updating the wording is the start.

**Describe alternatives you've considered**

Giving the ability to specify custom text through passing in a config object would be useful too, but clarifying the default is important.

**Additional context**

I'm a huge fan of the library and I'm really excited about where it will go in the future - it strikes an amazing balance between configurability and ease of use that I recommend to anyone I can!

**Comment by Mugen87** [comment]
To me, the current default sounds fine since it is generic. There is not way to describe the real reason for not being able to use VR in a brief manner. In general there are three:

- The browser does not implement WebXR API
- The OS does not support XR
- The user does not have the appropriate hardware

I think it's the task of the app to explain the user these details if necessary.

> Giving the ability to specify custom text through passing in a config object would be useful too,

The `options` parameter was removed from `createButton()` in order to keep the implementation simple. I suggest to keep this policy and not introduce your suggestion text configuration. If we would do this, it would be necessary to make all texts configurable (`VR NOT SUPPORTED`, `WEBXR NEEDS HTTPS`, `WEBXR NOT AVAILABLE`, `ENTER VR` and `EXIT VR`) which seems to be an overkill to me.

The solution for your issue is to create a copy of `VRButton` and modify it according to your custom requirements.

**Comment by mrdoob** [comment]
Maybe we can say `VR NOT AVAILABLE` instead of `VR NOT SUPPORTED`?
