### ISSUE TITLE
WebGLRenderTarget doesn't seem to work in WebVR

### ISSUE THREAD

**Issue by ZengRun** [mrdoob/three.js#23234]
**Describe the bug**

I modified the [crossfade example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_postprocessing_crossfade.html)  to support WebVR by simply adding an  VRButton. But in WebVR, there is no crossfade when the scenes are switched, instead a black screen.
I tried to follow the suggestion in issue [15614](https://github.com/mrdoob/three.js/issues/15614) by disabling and re-enabling VR when rendering the buffer scene，but it didn't work。
<img width="1017" alt="企业微信截图_303109a2-f6fa-46b3-aa2c-611cc61761e4" src="https://user-images.githubusercontent.com/10266846/149474876-e959b2a0-3b66-4838-9528-c2d51620fb79.png">

How can I fix this problem.

**Screenshots**
![CPT2201141627-1091x888](https://user-images.githubusercontent.com/10266846/149475818-fad06138-379b-45bf-b56e-e5410b4980ac.gif)

**Platform:**

 - Device: [Desktop]
 - OS: [ MacOS]
 - Browser: [Chrome]
 - Three.js version: [r135]

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by claytonrothschild** [comment]
@ZengRun did you ever solve this?

your immediate problem is likely that you are rendering Orthographic Projection for the transition in WebXR and it doesn’t work easily. This is likely why you were referred to the forum, as your problem was approach rather than a bug. 

But, even with proper architecture I am seeing weird behavior. For example, it works in WebXR emulator well but not in actual Oculus. 

I need to demonstrate this issue by building a codepen. But perhaps you already have one I can work off of? Thanks
