### ISSUE TITLE
PMREM in WebGL1Renderer seems to fail on samsung/pixel mobiles

### ISSUE THREAD

**Issue by Domenicobrz** [mrdoob/three.js#23432]
**Description**

PMREM seems to generate a black texture with `WebGL1Renderer` on some Samsung / Pixel devices
The problem is not visible with `WebGLRenderer`

**To Reproduce**

Using browserstack, this is the result of opening the first link in the live-example section with a Samsung S20:

![Immagine 2022-02-05 000927](https://user-images.githubusercontent.com/25647854/152616377-dccd4551-711e-4db2-9df5-c57270765fae.jpg)

And console report:

![Immagine 2022-02-05 000943](https://user-images.githubusercontent.com/25647854/152616395-f1fdef0a-35cf-4dbd-838f-c0d83b8cbb9f.jpg)

VS the expected result using the second link, which uses WebGLRenderer:

![Immagine 2022-02-05 001038](https://user-images.githubusercontent.com/25647854/152616475-4b90ec97-7a77-45cc-9681-465f8219854f.jpg)

The code is very simple and is visible in the links below

**Live example**

Here's a simple implementation of PMREM usage with WebGL1Renderer:
https://domenicobrz.github.io/temp/issue/index-wg1.html

Same code here, but with WebGLRenderer:
https://domenicobrz.github.io/temp/issue/index-wg2.html

This wasn't a problem with version r132, I updated to the latest version to use the new sheen shader, I wonder if that has something to do with the issue

**Platform:**

 - Device: [ Mobile, Samsung Galaxy s21/s20/s10/s10+  /  Pixel 6 ]
 - OS: [ Android ]
 - Browser: [ Chrome ]
 - Three.js version: [ r137 ]

Doesn't seem to be a problem on iOS

**Comment by elalish** [comment]
Yes, I recall this was an intentional choice. This feature requires rendering to half-float textures, which we decided was supported on iPhones in WebGL1 and on Android in WebGL2, and between those on nearly all devices. We've been doing this for at least 6 months in MV (in another feature that would break rendering if it wasn't supported) and we haven't gotten any complaints, so I believe it's pretty safe. I guess we're kind of saying WebGL1 is deprecated on Android for PBR.
