### ISSUE TITLE
css3DRender appear offset when it's father Node has offsetTop

### ISSUE THREAD

**Issue by yasuomang** [mrdoob/three.js#23458]
![image](https://user-images.githubusercontent.com/62331159/153548516-7d6bcb9b-de15-4827-bff6-5d2bfac50888.png)
![image](https://user-images.githubusercontent.com/62331159/153548530-c4943e5a-166e-49a6-96ad-1f4e3fd73abd.png)
father Node 
![image](https://user-images.githubusercontent.com/62331159/153548575-83910e5d-295f-4413-a109-916e2e843771.png)
if i set 0 to top,this bug will disappear

**Comment by Mugen87** [comment]
Sorry, but the issue you have reported is not clear.

Please fill out the issue template and also share a live example that demonstrate the issue. When this is done, the issue can be reopened.

**Comment by yasuomang** [comment]
> Sorry, but the issue you have reported is not clear.
> 
> Please fill out the issue template and also share a live example that demonstrate the issue. When this is done, the issue can be reopened.

I am done,please reopen my issue

**Comment by Mugen87** [comment]
Your codepen is not valid since you have mixed library files from different releases. Besides mixing module imports with global scripts is also not valid. And you should always use the latest release for reproducing issues.

Apart from that...it seems to me the behavior is as expected. If you offset the container that holds the canvas, the transformation influences all child elements.

Updated code: https://jsfiddle.net/fm8y1j2s/
