### ISSUE TITLE
(docs) Missing changelog/docs for r126 WebGLRenderTarget.setTexture

### ISSUE THREAD

**Issue by nyan-left** [mrdoob/three.js#23466]
r126 introduced `setTexture` within `WebGLRenderTarget`. This is not documented in the [release](https://github.com/mrdoob/three.js/releases/tag/r126).  Looks like there's no mention of it in the [docs](https://threejs.org/docs/#api/en/renderers/WebGLRenderTarget) either.

The release notes + docs should be updated to reflect this addition.

Relevant commit [here](https://github.com/mrdoob/three.js/commit/e1e5ce7d119619e4b7c71b3e7d66ef3931d0e9ae#diff-98476907723f20d8a0af2a90a172439c3f4523e405f811d84e005b22047ea048L44).

Happy to help out with the docs if needed. Thanks!

**Comment by Mugen87** [comment]
This method is only used at one place in `webgl2_rendertarget_texture2darray`.

https://github.com/mrdoob/three.js/blob/507459cd67d30bda1b2f25212f615705a73ec65d/src/renderers/WebGLRenderTarget.js#L42-L52

I wonder if we could remove the method and solve the use case in the example differently.

**Comment by Mugen87** [comment]
I wonder if it isn't better to introduce `WebGL3DRenderTarget`. It could have a boolean that allows to specify whether the render target should be considered as an array of data or not.

The current way of assigning a custom texture to `WebGLRenderTarget` feels like a hack to me. The texture reference of  a render target should not be replaced.

**Comment by gkjohnson** [comment]
I've used the `setTexture` function to render to a texture 2d array but it felt like a bit of a hack to me, too, if only because it's undocumented. Adding `WebGL3DRenderTarget` and `WebGL2DArrayRenderTarget` seem like good solutions that line up with the other three.js classes. If `setTexture` is going to be kept I think the name of the function to be improved to better reflect it's behavior -- like `setStorageTexture` or something and be documented.

**Comment by mrdoob** [comment]
@DavidPeicho FYI
