### ISSUE TITLE
WebGLRenderer.getContext has wrong returned type in docs

### ISSUE THREAD

**Issue by hschwane** [mrdoob/three.js#23555]
**Describe the bug**
In the online documentation as well as the typescript types `WebGLRenderer.getContext()` is said to return a `WebGLRenderingContext` when in reality it returns a `WebGL2RenderingContext`. This is very confusing when one wants to work with functionality that was not available in webgl 1.

**Expected behavior**

Show the correct return type in the online docs as well as the typescript types.

**Comment by Mugen87** [comment]
Depending on the system, `getContext()` returns a `WebGL2RenderingContext` or a `WebGLRenderingContext`. However, the documentation does currently not support to define more than one return type. For simplicity I would choose `WebGL2RenderingContext` since it is the more common one.

The TS type declaration files are not maintained in this repo. They have to be fixed here: https://github.com/three-types/three-ts-types
