### ISSUE TITLE
Values useRenderToTexture and __useRenderToTexture seems never be set

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#23642]
While browsing through the sources I have come across a thing I do not understand: in function `useMultisampledRTT` there is a reference to a value `renderTargetProperties.__useRenderToTexture`, but no such value is used anywhere in the code.

Is this something user is supposed to set somehow?

Does `useMultisampledRTT` ever return true?

There is also a reference to value `renderTarget.useRenderToTexture` in `setRenderTargetTextures`. The value is only set to false there and never used. Is this some kind of relic?

**Comment by OndrejSpanel** [comment]
I am afraid I still do not understand how is this supposed to work. Where is `__useRenderToTexture` set to true?

The fix only changes `setRenderTargetTextures` from setting `__useRenderToTexture` to `false` instead of `useRenderToTexture`. The value is never set to true, at least I cannot find any such place.

**Comment by OndrejSpanel** [comment]
Note: `useRenderToTexture` was set to `true` in `WebGLMultisampleRenderTarget`, which was been removed recently (#23455).

What is the functionality this should implement? How can it be tested the functionality works as intended?

**Comment by Mugen87** [comment]
The flag is only relevant in context of `WEBGL_multisampled_render_to_texture`. 

When the extensions is available, a separate code path is taken which does not require an explicit resolve of multisample data. The function `useMultisampledRTT()` detects this.

However, there is an [edge case](https://github.com/mrdoob/three.js/blob/f9c68e393a4176e18be6fe0b0a00192f3652c63a/src/renderers/WebGLRenderer.js#L1816-L1823) when `useMultisampledRTT()` should return `false` although mutlisampling should be used and `WEBGL_multisampled_render_to_texture` is available. In this case, `__useRenderToTexture` is set to `false`. It does not matter if it never holds `true` or any other value because the check is `renderTargetProperties.__useRenderToTexture !== false`.

**Comment by OndrejSpanel** [comment]
Thanks for the explanation. JS `undefined` rules are still not a second nature to me.

**Comment by donmccurdy** [comment]
Does any device+browser support `WEBGL_multisampled_render_to_texture` today? I've been trying a few modern devices and can't find it.

**Comment by Mugen87** [comment]
From Twitter:

> The Quest browser supports this extension. Without it, we can't have multisampled support with foveation.
