### ISSUE TITLE
Postprocessing - Outline Pass rendering issue

### ISSUE THREAD

**Issue by Pourfex** [mrdoob/three.js#23701]
**Describe the bug**

Outline pass add rendering issue - black and white stripes

**To Reproduce**

Take the webgl post processing outline example. Load a gltf model. When model is in view, you'll see bacl and white stripes on the model.

***Code***

See source at : https://front-threejs-debug.netlify.app/examples/webgl_postprocessing_outline

***Live example***

https://front-threejs-debug.netlify.app/examples/webgl_postprocessing_outline

**Expected behavior**

Outline pass should not affect rendering with black and white stripes

**Screenshots**

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/25880714/157670519-b502894a-0b22-4c07-be97-bb961daaf759.png">

**Platform:**

 - Device: Desktop
 - OS:  MacOS (v12.1 ; v12.1.2)
 - Browser: [Chrome, Firefox, Safari]
 - Three.js version: [master, r138]

**Comment by Mugen87** [comment]
I've verified your model in the `three.js` editor and it seems the asset is poorly designed. I see a lot of overlapping faces (visible as gray areas in the below screenshot) which produces by z-fighting. This issue is unrelated to post-processing.

<img width="1778" alt="image" src="https://user-images.githubusercontent.com/12612165/157684352-d5b32e8b-725a-4545-8786-35ea7795d025.png">

The complexity of your model with 3.5 Mio vertices is also questionable. I suggest you optimize your model first and ensure that it properly renders without post processing.

Use the [forum](https://discourse.threejs.org/) if you need help with this task.

**Comment by Mugen87** [comment]
Okay, the new model indeed shows the issue more clear. 

Not sure why this is happening but maybe you can try the following: Can you please update the your live app by using a modified version of `OutlinePass`? The idea is to create all render targets as FP32 ones like so:
```js
this.renderTargetDepthBuffer = new WebGLRenderTarget( this.resolution.x, this.resolution.y, { type: FloatType } );
```
Does this approach mitigate the issue?

**Comment by Mugen87** [comment]
Besides, create the renderer just like so:
```js
renderer = new THREE.WebGLRenderer();
```

**Comment by ketourneau** [comment]
Issue still present in chrome with your proposition, url to test :
https://outline-pass-issue.netlify.app/examples/?q=draco#webgl_postprocessing_outline_draco_glb

Source code:
https://github.com/bloc-in-bloc/three.js/blob/outline_rendering_issue/examples/webgl_postprocessing_outline_draco_glb.html

Three.js version: [dev, r138]
Chrome 99.0.4844.51

**Comment by SachinGanesh** [comment]
Hi @ketourneau, were you able to find a solution?

**Comment by sdarpeng** [comment]
It seems one of the stupid Chinese goverment 'Digital Twin' projects. Just junk artist and junk programmer making useless junks. They even do not know what is topology and shadowmap.

**Comment by Mugen87** [comment]
Latest changes to `EffectComposer` seems to improve the situation:

<img width="2536" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/4196c255-73a9-487b-80bb-31964bac91bc">

This screenshot was done without additional configurations or changes to the composer or render targets (the composer uses half float render targets by default now). I've just imported the test asset into `webgl_postprocessing_outline`, updated the camera/control settings and removed the additional basic geometries. 

It is important however to set `logarithmicDepthBuffer` to `true` because the asset has such a large scale. Without this, rendering is broken even without using `OutlinePass`.
