### ISSUE TITLE
Weird sparse pointcloud on intel integrated gpu

### ISSUE THREAD

**Issue by lihk11** [mrdoob/three.js#23887]
**Describe the bug**

When using intel integrated gpu, such as UHD 630, the point cloud displayed goes sparse.
iGPU:
![image](https://user-images.githubusercontent.com/4299373/162959739-e33e099b-34b8-4490-a4a8-4081155f8ecc.png)

Normal(Nvidia GPU, or disable hardware accelaration for chrome):
![image](https://user-images.githubusercontent.com/4299373/162959692-b4cd1b74-f384-4ffe-a6bb-c6429d7a1202.png)

**To Reproduce**
1. load a large pointcloud contains over 1M points
2. Just use Intel integrated gpu to render

**Platform:**

 - Device: Desktop
 - OS: Linux,
 - Browser: Chrome, Firefox, Edge
 - Three.js version: [r139]

**Comment by lihk11** [comment]
@Mugen87 Thanks for your reply. It does look like a GPU driver related issue. But why? The behavier of VTK or OSG to show the same pointcloud is normal. The following is the output of "chrome://gpu". 
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Direct Rendering Display Compositor: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
OpenGL: Enabled
Rasterization: Hardware accelerated
Raw Draw: Disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Video Encode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated

**Comment by lihk11** [comment]
someone also experencing similar problem:
https://stackoverflow.com/questions/53059744/why-three-js-pointcloud-is-not-same-rendering-between-mac-and-windows-intel-hd

**Comment by lihk11** [comment]
increasing the point size do look better, but the sparse problem still remains

**Comment by Mugen87** [comment]
> The behavier of VTK or OSG to show the same pointcloud is normal.

Both projects are not based on WebGL so it's a bit problematic to use them as a reference. 

Do you see a correct output with another WebGL libraries like BabylonJS or maybe with plain WebGL? If so, we could potentially fix something in `three.js`. 

Next to the driver issues there is another problem. Rendering points with consistent size across all platforms is tricky since the `size` property of `PointsMaterial` is in pixels and devices have different pixel densities. If you need points with a size > 1 pixels, one could consider to render for each point a simple plane mesh based on instanced rendering. Each frame, you orient the planes towards the camera similar to sprites/billoards.

**Comment by Mugen87** [comment]
Can you please make two screenshots. One with the Intel and one with the Nvidia GPU?

**Comment by lihk11** [comment]
With Nvidia GPU(gtx 1660):
![image](https://user-images.githubusercontent.com/4299373/163146235-0370d7c8-a173-425e-8244-6dbee9c5b45c.png)
With Intel GPU(UHD 630):
![image](https://user-images.githubusercontent.com/4299373/163146270-933860da-db7c-4870-9c2e-bcbfa7c664ad.png)
Both tested on Ubuntu 20.04, Chrome 100.0.4896.75

**Comment by Mugen87** [comment]
I've tried to port the demo's code to `three.js`: https://jsfiddle.net/pa4zsqnj/1/

Can you please make a screenshot again for each CPU?

**Comment by lihk11** [comment]
Thanks a lot, Mugen87. Your code runs fine on my intel machine(just see the following screenshot). And I find out when i set sizeAttenuation property of PointsMaterial to false, and not setting ‘size’ property would solve my problem. But I don't know how those properties do this magic. Could you give me some hints? Thanks again.
![image](https://user-images.githubusercontent.com/4299373/163303635-e6bd5b5a-9a57-446a-a1de-4e418621c575.png)

**Comment by lihk11** [comment]
And I test the same code on a windows machine with Intel GPU only. No matter what values I set of ‘’size‘ and ‘sizeAttenuation’, it just run normally. It may be a platform related problem.

**Comment by Mugen87** [comment]
Good to hear that! Setting `sizeAttenuation` to `false` and not changing `size` will indeed produce a more consistent result since the point size is always 1 pixel. This size is the best supported one across all devices.

Also notice that in the future with WebGPU points can only be rendered with a size of 1 pixels.
