### ISSUE TITLE
Materials take care of needsUpdate by itself

### ISSUE THREAD

**Issue by benzsuankularb** [mrdoob/three.js#24039]
**Is your feature request related to a problem? Please describe.**

I have a question about the design of `needsUpdate` property in materials.
As far as I know, `needsUpdate` property aimed to recompile the shader before the next render.
However, my thought is that it shouldn't be the case for users to know when they need to use `needsUpdate`.
Because material internally should have knowledge itself about their shader and when needs to be recompiled.
BTW, I'm just curious why it needs to be designed this way.

**Describe the solution you'd like**

`needsUpdate` be managed internally by each type of material.

----

P.S. Please close the topic if this issue already exists or if the problem is actually not valid.

**Comment by Mugen87** [comment]
A design without `needsUpdate` requires additional management logic in the materials since they have to maintain an internal state. This kind of logic always comes with an overhead which can be produce performance issues in certain use cases. Besides, it increases the complexity and thus maintainability of the materials (you can clearly see this with `MeshPhysicalMaterial` where certain property access increases the internal `version` counter).
