### ISSUE TITLE
new THREE.Vector3(0, 0, 0).angleTo(new THREE.Vector3(0, 0, 0)) should be undefined

### ISSUE THREAD

**Issue by manake** [mrdoob/three.js#24112]
`new THREE.Vector3(0, 0, 0).angleTo(new THREE.Vector3(0, 0, 0))` should be `undefined` instead of `Math.PI / 2`?

If vector has no length then how can it have an angle?

It seems the logic is to make it point to z-axis positive values by default but I think it should behave more according to standard math.

**Comment by WestLangley** [comment]
three.js does not validate inputs. It is your app's responsibility to do that.

**Comment by looeee** [comment]
> three.js does not validate inputs. It is your app's responsibility to do that.

This should be added to the FAQ because it's asked a lot. 

https://threejs.org/docs/#manual/en/introduction/FAQ

Q: Why does Three.js sometime return strange results for invalid inputs? 
A: For performance reasons, Three.js doesn't validate inputs in most cases. It's your app's responsibility to make sure that all inputs are valid.
