### ISSUE TITLE
Points unaffected by object hierarchy scale

### ISSUE THREAD

**Issue by kumavis** [mrdoob/three.js#24176]
**Expected behavior**

Expected Points with `{ sizeAttenuation: true }` on the `PointsMaterial` to have its render size to be affected by object hierarchy scale. Own scale or parent scale, etc.

**Live example**

1. Go to https://jsfiddle.net/98u1j5x3/
2. see render function
3. observe behavior

**Platform:**

 - Three.js version: dev

**Comment by Mugen87** [comment]
`Object3D.scale` does have an effect on the points transformation. Unfortunately, it becomes not visible in your fiddle. If you offset on of the point clouds and then scale their group, you will see an effect: https://jsfiddle.net/ve3t0r27/

However, `Object3D.scale` does not affect the _rendered size_ of the points. This needs to be defined via `PointsMaterial.size`. 

`Object3D.scale` influences the visual appearance of meshes since scaling something up or down influences the size of triangles. This is not true for point clouds since they have a size of 1 pixel by default (or in other words they are infinitely small like lines). The spatial extension of points is implemented in the shader via `gl_PointSize` which is unrelated to the model's transformation matrix.

Also keep in mind that with WebGPU, points will always have the size of 1 pixel and something like `sizeAttenuation` is not supported anymore. You have to work with instanced planes/sprites instead if you need point-like shapes with a size greater 1 pixel.

**Comment by kumavis** [comment]
https://github.com/gpuweb/gpuweb/issues/332

**Comment by mrdoob** [comment]
@Mugen87 

> Also keep in mind that with WebGPU, points will always have the size of 1 pixel and something like `sizeAttenuation` is not supported anymore.

Hmm, we may need to render `THREE.Points` using instanced planes facing the camera in WebGPU.
Otherwise `THREE.Points` will not be very useful...

**Comment by Mugen87** [comment]
Yeah, this is one of the open points in context of WebGPU. Meaning how to treat `THREE.Points`. Right now, the renderer uses the `point-list` primitive for rendering but that will break many existing use cases considering how `THREE.Points` is used in WebGL.

**Comment by mrdoob** [comment]
We'd still need a way of being able to use the `point-list` primitive for those that need it.
In the context of WebGL I was thinking `THREE.GLPoints` but I guess the name doesn't work for WebGPU...
`THREE.RawPoints` maybe? 🙃
