### ISSUE TITLE
OBJLoader loses information about Vertex ID.

### ISSUE THREAD

**Issue by T4G2** [mrdoob/three.js#24361]
While I was working on my bachelor thesis, I needed to create a Half Edge Structure for any 3D model that was loaded. For this I needed after Loading. as you can see in issue  **Half Edge Structure for Custom Models.** #24360 ,
I will need to create a Half Edge structure more effectively a way to extract original vertex id from *.obj* files.

The way to extract would be quite simple, I would have to only store Vertex ID information into new List, and then I would return so the user can do anything they want with given structure (For example they could feed it into HalfEdge Structure to create a Half Edge Map).

There is an alternative to generate HalfEdge Representation of Mesh without this step, but it would be very ineffective as we would have to manually test, if there are points with the same vertex position to match them.

This Issue is related to this issue:  **Half Edge Structure for Custom Models.**#24360

**Comment by donmccurdy** [comment]
Could you share an example of an OBJ file that contains Vertex IDs? I'm not aware that the format supports something like that. If it's not part of the OBJ format then I think you might need to serialize this data structure another way.

**Comment by gkjohnson** [comment]
By the nature of the OBJ format the way vertex information is stored is incompatible with the way the WebGL API needs vertex data to be formatted. It would be best to use a different format like glTF that stores vertex indices. Alternatively you could just use the `BufferGeometryUtils.mergeVertices` function to generate an index buffer if that's what you need. Otherwise I think this is an overly specific use case to handle in the OBJLoader.

**Comment by T4G2** [comment]
@Mugen87 , yeah, that looks promising, thank you
