### ISSUE TITLE
Half Edge Structure for Custom Models.

### ISSUE THREAD

**Issue by T4G2** [mrdoob/three.js#24360]
As I was working on my bachelor thesis, I needed to create a Half Edge Structure for any given model. I had problems that I had no way to access already created `HalfEdge` Class in [/examples/jsm/math/ConvexHull.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/math/ConvexHull.js). Also the problem is that this structure is only used in `ConvexHull.js` however it could be used to create HalfEdge structure from any 3D Model. )
**Describe the solution you'd like**
- I suggest to move `HalfEdge` Class to new file `HalfEdge.js`.
- Create a new Class `HalfEdgeStructure` with this very simple structure 
```
this.mesh = mesh
this.halfEdgeMap = new **Map()**
```

This Issue is related to following Issue:  **OBJLoader loses information about Vertex ID.** #24361

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/24359#issuecomment-1188847789

**Comment by erasta** [comment]
Excuse me for intervening, but I also needed the `HalfEdge` and `Face` classes from [ConvexHull.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/math/ConvexHull.js), but since they're not exported, i had to copy them to my own repo.
Would it be possible to export those by changing [the last line](https://threejs.org/docs/index.html#examples/en/math/convexhull/HalfEdge) from `export { ConvexHull };` to `export { ConvexHull, Face, HalfEdge, VertexNode, VertexList };`?
This will also better reflect the [documentation](https://threejs.org/docs/index.html#examples/en/math/convexhull/HalfEdge), as those classes are shown there.
Thank you.

**Comment by Mugen87** [comment]
Exporting these classes is okay. Would you like to make a PR?

**Comment by erasta** [comment]
Yes, thank you, will do shortly.
