### ISSUE TITLE
OrbitControls events strange behaviour

### ISSUE THREAD

**Issue by sovetski** [mrdoob/three.js#24437]
**Describe the bug**

I am using "Orbitontrols" and these 3 events which are "start", "change" and "end".
When we click just on the screen without changing the camera position etc. the "start" and "end" events are hired, which is strange because we dont do any mouse "hold" click etc. And some times (randomly, difficult to reproduce) when we click the 2nd time on the screen, the "change" event is also fired..

**To Reproduce**

1. Use these 3 events
2. Click on the screen, only 1 click without any mouse hold etc.
3. See at the console, you will see the messages fired by events
4. Click a 2nd time and if you have a chance, "change" event will be also fired

***Code***

```js
	let controls = new OrbitControls(homeThreeJS.camera, homeThreeJS.renderer.domElement);
	controls.minPolarAngle = 0;
	controls.maxPolarAngle = Math.PI * 0.5;
	controls.enablePan = false;
	controls.target.set(0, 0, 0);
	controls.minDistance = 2.9;
	controls.maxDistance = 3;
	controls.update();

	controls.addEventListener("start", function () {
		console.log("Change started");
	});

	controls.addEventListener("change", function () {
		console.log("Changed!");
	});

	controls.addEventListener("end", function () {
		console.log("Change end!");
	});
```

***Live example***

* [https://codesandbox.io/s/03-repeat-texture-coordinates-forked-p1ljqy?file=/src/Gl.js](https://codesandbox.io/s/03-repeat-texture-coordinates-forked-p1ljqy?file=/src/Gl.js)

**Expected behavior**

"Start" and "end" events should be fired only if we click and hold the mouse to change the camera position

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r143

**Comment by LeviPesin** [comment]
I think this is related to https://github.com/mrdoob/three.js/issues/23874?

**Comment by Mugen87** [comment]
>  And some times (randomly, difficult to reproduce) when we click the 2nd time on the screen, the "change" event is also fired..

The change event might be fired because the mouse registers a tiny displacement which triggers `pointermove`. 

The current behavior of `OrbitControls` is actually intended. According to the documentation, `start` is fired _when an interaction was initiated_. And `end` when an _interaction has finished_. A simple click is an interaction so the events are triggered as expected.

What you are describing is `changestart` and `changeend` which is not supported by any control class in `three.js`. If you need such specialized events, it's best if you modify `OrbitControls`.
