### ISSUE TITLE
show the Moire pattern when using  WebGL1Renderer

### ISSUE THREAD

**Issue by cavencj** [mrdoob/three.js#24468]
when I use the `WebGL1Renderer` to render the scene , the model show the `Moire pattern`，also change the materail texture `minFilter`  param ,it still not work，the pic ： 
![image](https://user-images.githubusercontent.com/33321375/183345174-52f4c72d-dcdb-422f-b4fb-e5f01f83f941.png)

later i change  the  `WebGL1Renderer` to `WebGLRenderer` , the `Moire pattern` is not  show , the pic :
![image](https://user-images.githubusercontent.com/33321375/183345328-478f0582-da9e-43fb-bcc6-f73630204599.png)

has any way to reduce the `Moire pattern` when use  the  `WebGL1Renderer`

**Comment by Mugen87** [comment]
You share way to less information for investigating this issue.  I suggest you use the [forum](https://discourse.threejs.org/) to find out the root cause of the moire pattern. If it turns out to be a bug in the engine, the issue can be reopened.

When creating a topic at the forum, share a [live example](https://jsfiddle.net/f2Lommf5/) that demonstrates the issue. Screenshot alone are not sufficient.

**Comment by cavencj** [comment]
@Mugen87  

i write a demo the link is https://jsfiddle.net/cavencj/aoz6je5L/120 , Reproduced the phenomenon

**Comment by Mugen87** [comment]
What you see is a WebGL 1 limitation in context of sRGB workflows. `EXT_sRGB` can not be used with mipmap generation so `THREE.LinearFilter` is the best texture filtering you get. You can only avoid this by using WebGL 2 or by avoiding a sRGB workflow: https://jsfiddle.net/Lt7r4o5d/1/
