### ISSUE TITLE
Could not transform imported 3D object

### ISSUE THREAD

**Issue by fengxinming** [mrdoob/three.js#24536]
**Describe the bug**

Could not transform imported 3D object from the file "SimpleSkinning.gltf"。

**To Reproduce**

1. git clone [https://github.com/mrdoob/three.js](https://github.com/mrdoob/three.js)
2. cd three.js
3. npm install
4. npm run dev

***Code***

https://github.com/mrdoob/three.js/tree/dev/editor

***Live example***

https://github.com/mrdoob/three.js/tree/dev/editor

**Expected behavior**

3D object can be transform.

**Screenshots**

![threejs-object2](https://user-images.githubusercontent.com/6262382/186378130-0b1d9956-0e4d-4f7a-bfdb-2f6fe046c4cd.gif)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome, Firefox, Safari, Edge
 - Three.js version: 0.143.0

**Comment by Mugen87** [comment]
You have to select the root element of the glTF if you want to transform it. The selection works best if you use the outliner.

Also notice that #24529 produces runtime errors with skinned meshes. This will be fixed with the next release. For now, you can work with the dev version of the editor:

https://raw.githack.com/mrdoob/three.js/dev/editor/index.html

**Comment by fengxinming** [comment]
@Mugen87 I think I absolutely select the root element to transform it, please look at that gif picture above.

https://user-images.githubusercontent.com/6262382/186378130-0b1d9956-0e4d-4f7a-bfdb-2f6fe046c4cd.gif

**Comment by Mugen87** [comment]
You can see at the outliner that you select a skinned mesh which is not the root object.
