### ISSUE TITLE
AnimationUtils.MakeClipAdditive should calculate clip fps instead of assuming 30 as default

### ISSUE THREAD

**Issue by Dadibom** [mrdoob/three.js#24576]
Instead of assuming 30 fps, calculate fps based on the track times.

For example:

`fps = 1 / (tracks[0].times[1] - tracks[0].times[0]);`

**Comment by Mugen87** [comment]
I'm not sure this computation is right. You just subtract the time value of two subsequent keyframes which does not represent the FPS.

**Comment by donmccurdy** [comment]
The method defaults to 30fps, but you can override it if you know the framerate —

https://github.com/mrdoob/three.js/blob/68daccedef9c9c325cc5f4c929fcaf05229aa1b3/src/animation/AnimationUtils.js#L229-L234

Each AnimationClip contains _keyframes_; these are not the same as _frames_. One 30 second track authored at 30fps might only contain two keyframes, one at the beginning and one at the end. So we cannot assume the time between two sequential keyframes indicates the framerate, as authors do not always include all frames, and optimizers may remove them.

**Comment by Dadibom** [comment]
Very true, I did not consider missing keyframes. But the information has to be in the clip somewhere, right? Otherwise, if actual frames or fps aren't really a thing in the engine, perhaps it would make more sense to use a referenceTime instead of a referenceFrame?

For our use case we simply want the midpoint of the animation to be the reference, no matter what the frame count or fps is.
Looking at the snippet above, I guess we could simply pass `fps = 0.5` and `referenceFrame = clip.duration` to get the midpoint since it just converts it to a time anyway, so it's not really an issue but it looks very hacky.

**Comment by donmccurdy** [comment]
> But the information has to be in the clip somewhere, right?

Maybe in some formats, but not reliably available no.

In the case of `AnimationUtils.subclip( ... )` we use an offset in frames and an optional `fps` argument because this tends to be how artists work — they design a "walk" or "run" cycle that occupies a certain number of frames in the authoring tool. And then need to slice out those frames for a separate clip at runtime. This was common in FBX, which doesn't support multiple animations very well.

For `makeClipAdditive` I am not sure whether frames or time are more useful to artists. I guess the good news is that if you know the reference time you want, it doesn't actually matter what the framerate is. You can just pick an arbitrary framerate and use it to convert your known time to frames.

/cc @c-morten may have some other ideas here.
