### ISSUE TITLE
HDRI not working with ShaderMaterial

### ISSUE THREAD

**Issue by coramat** [mrdoob/three.js#24617]
Hi Everyone,

I am having issues using an environment map with ShaderMaterial.

I am loading the envMap using `THREE.CubeTextureLoader`, which works perfectly with `MeshStandardMaterial` but has no effect if I use instead `ShaderMaterial`, as you can see in this fiddle example: [https://jsfiddle.net/3jo6Ldpf/2/](https://jsfiddle.net/3jo6Ldpf/2/) . 

The cube on the right has a ShaderMaterial applied and the HDRI is not showing up.
In the same example, I tried using the option: (line 51)

```
materialShader.defines.ENVMAP_TYPE_CUBE_UV = ''
```
and  I get the following error:

```
ERROR: 0:484: 'CUBEUV_MAX_MIP' : undeclared identifier
ERROR: 0:485: 'CUBEUV_TEXEL_WIDTH' : undeclared identifier
ERROR: 0:486: 'CUBEUV_TEXEL_HEIGHT' : undeclared identifier
ERROR: 0:523: 'CUBEUV_MAX_MIP' : undeclared identifier
```

There is a function in [WebGLProgram.js](https://github.com/mrdoob/three.js/blob/59247fa177b9b3637bd64835c8b0ea4218a63010/src/renderers/webgl/WebGLProgram.js#L374) called `generateCubeUVSize` that is suppose to compute the values of CUBEUV_MAX_MIP, CUBEUV_TEXEL_WIDTH, and CUBEUV_TEXEL_HEIGHT, and then automatically generating the corresponding definitions(defines), so I was puzzled why it was not working in this case.

When I tried manually defining those options by adding in the same fiddle example these lines of code:
```
  materialShader.defines.CUBEUV_MAX_MIP = '4'
  materialShader.defines.CUBEUV_TEXEL_WIDTH = '0.03'
  materialShader.defines.CUBEUV_TEXEL_HEIGHT = '0.03'
```
I got this error:
```
'textureCubeUV' : no matching overloaded function found
```
regarding the shader chunk `envmap_physical_pars_fragment.glsl.js`.

This gave me the hint that `envMap` passed in the function `textureCubeUV` is not the sampler2D uniform expected by the function but something else. The type of envmap seems to derive from the shaderChunk `envmap_common_pars_fragment.glsl.js`, which define envmap as `uniform samplerCube envMap;` rather than `uniform sampler2D envMap;` if `ENVMAP_TYPE_CUBE` has been defined.

So I wanted to understand who defines `ENVMAP_TYPE_CUBE`, since in the fiddle code I defined `ENVMAP_TYPE_CUBE_UV`, and in [WebGLPrograms.js](https://github.com/mrdoob/three.js/blob/59247fa177b9b3637bd64835c8b0ea4218a63010/src/renderers/webgl/WebGLPrograms.js) 
I found this piece of code:
```
const environment = material.isMeshStandardMaterial ? scene.environment : null;
const envMap = ( material.isMeshStandardMaterial ? cubeuvmaps : cubemaps ).get( material.envMap || environment );
const envMapCubeUVHeight = ( !! envMap ) && ( envMap.mapping === CubeUVReflectionMapping ) ? envMap.image.height : null;
```
where it seems that if you do not have a `MeshStandardMaterial` you cannot have cubeuvmaps.

This code  could also explain why I was getting the error about CUBEUV_MAX_MIP etc not being defined, because those defines are happening only if `envMapCubeUVHeight` is not null.

Is there a way to have an HDRI working with `ShaderMaterial`?

 I am not a threejs expert so I might be not considering something trivial.
 I just tried to debug as much as I could until I got stuck to avoid bothering you folks <3 

----------------------------------

 - Device: [PC]
 - OS: [Windows, MacOS]
 - Browser: [Chrome]
 - Three.js version: [r143] (but I am getting the same error even in previous versions, up to 132)

**Comment by Mugen87** [comment]
Can you please update your fiddle since your are not loading a HDR environment map. Try using `RGBELoader` or `EXRLoader`.

**Comment by Mugen87** [comment]
Updated fiddle: https://jsfiddle.net/fk6h3o9L/2/

If you copy the code from `MeshStandardMaterial` to a custom shader, you should know that you can't use an environment map in the cube map or equirectangular. Only the cubeUV format works which is generated by using `PMREMGenerator`.

I suggest you only create shader materials from built-in material shader code if you know the internals. Otherwise I recommend to use `onBeforeCompile()` and extend a built-in material with custom logic.

If you have more questions, please use the [forum](https://discourse.threejs.org/).

**Comment by coramat** [comment]
> Nit: You are not using a HDR environment map in your fiddle. Try using `RGBELoader` or `EXRLoader`.

You are right, I am using an HDR in my project and I forgot to update that part in the fiddle.

Thanks a lot for the quick help!

**Comment by arpu** [comment]
@Mugen87  would it be possible to direct use the scene.enviroment Texture for a ShaderMaterial? 
updated the example https://jsfiddle.net/rudcsb16/3/

**Comment by max-sym** [comment]
@arpu I'm also trying to create a shader including scene.environment (or scene.background) as envMap.
@Mugen87 can you explain a bit on how defines get automatically passed in your initial updated fiddle (https://jsfiddle.net/c5hjnpzm/1/) ? The one OP provided included defines but yours doesn't and it works.. How can that also be applied for ShaderMaterial + scene.environment as envMap. Thanks!

**Comment by Mugen87** [comment]
> would it be possible to direct use the scene.enviroment Texture for a ShaderMaterial?

No, that does not work since `Scene.environment` only affects PBR materials. And you can not guarantee that a custom shader material is always PBR conform.

> can you explain a bit on how defines get automatically passed in your initial updated fiddle

The environment map defines are automatically generated when the renderer encounters the `envMap` property when processing a material. The original fiddle did not work since the env map type was wrong.

**Comment by Mugen87** [comment]
Please ask at the [forum](https://discourse.threejs.org/) for such help requests.

**Comment by pailhead** [comment]
FWIW if anyone runs into this, one of the above mentioned hacks could be:

```

const material = new ShaderMaterial({
  vertexShader,
  fragmentShader,
  uniforms: {
    envMap: { value: null },
    envMapIntensity: { value: 2 },
    roughness: { value: 1 },
    //hack begins
    ambientLightColor: { value: null },
    lightProbe: { value: null },
    directionalLights: { value: null },
    directionalLightShadows: { value: null },
    spotLights: { value: null },
    spotLightShadows: { value: null },
    rectAreaLights: { value: null },
    ltc_1: { value: null },
    ltc_2: { value: null },
    pointLights: { value: null },
    pointLightShadows: { value: null },
    hemisphereLights: { value: null },
    directionalShadowMap: { value: null },
    directionalShadowMatrix: { value: null },
    spotShadowMap: { value: null },
    spotLightMatrix: { value: null },
    spotLightMap: { value: null },
    pointShadowMap: { value: null },
    pointShadowMatrix: { value: null },
    opacity: { value: null },
    diffuse: { value: null },
    metalness: { value: null },
    envMapRotation: { value: new Matrix3() },
    flipEnvMap: { value: null },
    reflectivity: { value: null },
    ior: { value: null },
    refractionRatio: { value: null },
  },
  defines: { STANDARD: '' },
})
```

Unfortunately followed by:
```
const envMapRotation = new Euler(0, 0, 0)
Object.defineProperties(material, {
  envMap: {
    get() {
      return this.uniforms.envMap.value
    },
    set(v: Texture | null) {
      this.uniforms.envMap.value = v
    },
  },
  isMeshStandardMaterial: {
    get() {
      return true
    },
  },
  opacity: {
    get() {
      return 1
    },
    set(v: number) {
      //noop
    },
  },
  envMapRotation: {
    get() {
      return envMapRotation
    },
    set(v: Euler) {
      envMapRotation.copy(v)
    },
  },
  envMapIntensity: {
    get() {
      return 1
    },
  },
  roughness: {
    get() {
      return this.uniforms.roughness.value
    },
  },
})
```

This seems to be the minimum to trick the `WebGLRenderer` into doing its under the hood PMREM conversion. 
`isMeshStandardMaterial` is what triggers the cubemap to cubeuv conversion thingie. This then causes a cascade of issues, for example, even if you explicitly say `lights = false` it will be ignored. So to not have the refresh uniforms logic throw, one has to add all these light uniforms. And so on for the rest of the refresh stuff.

Whats kinda funny and interesting is this last `roughness` entry - it already exists as a uniform, but because the renderer handles it specifically, it has to have a `{ value }` for the uniform already available. If `material.roughness` is undefined, youll get a 0 in your uniform, because `WebGLRenderer` will just override it. 

So essentially that last line does ` uniforms.roughness.value = uniform.roughness.value` :/
