### ISSUE TITLE
OutlinePass v0.144.0 not working

### ISSUE THREAD

**Issue by jedhelmers** [mrdoob/three.js#24610]
**OutlinePass throws an error**

I've been pulling my hair out trying to figure out why OutlinePass was not working. Downgrading from **0.144.0** to **0.143.0** seems to fix it.

I followed the example in **examples/webgl_postprocessing_outline.html** exactly but it would not work. I kept getting this error:
```
three.module.js:18762 THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: Vertex shader is not compiled.
�
VERTEX

ERROR: 0:156: 'worldPosition' : undeclared identifier
ERROR: 0:156: '=' : dimension mismatch
ERROR: 0:156: 'assign' : cannot convert from 'highp 4X4 matrix of float' to 'out highp 4-component vector of float'
�

  151: 	#endif
  152: 	worldPosition = modelMatrix * worldPosition;
  153: #endif
  154: 
  155: 					vPosition = mvPosition;
> 156: 					projTexCoord = textureMatrix * worldPosition;
  157: 
  158: 				}
```

**To Reproduce**

1. `npm install three`
2. follow outline example from github.com/mrdoob/three.js/blob/dev/examples/webgl_postprocessing_outline.html
3. OutlinePass shouldn't work and the aforementioned error should be in console.

***Code***

[github.com/mrdoob/three.js/blob/dev/examples/webgl_postprocessing_outline.html](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_postprocessing_outline.html)

**Screenshots**

<img width="767" alt="Screen Shot 2022-09-08 at 7 17 11 AM" src="https://user-images.githubusercontent.com/33405434/189108984-ebd7d62d-7241-41c0-aec3-c488ddd4c248.png">

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]
 - Three.js version: [dev, r0.144.0]

**Comment by Mugen87** [comment]
Since the [official example](https://threejs.org/examples/webgl_postprocessing_outline) is working for me, I suggest you ask for help at the [forum](https://discourse.threejs.org/). If it turns out to be a bug in the pass, we can reopen this issue.

**Comment by zhouchengshi** [comment]
The following code must be added to work properly:
 
```
    renderer.shadowMap.enabled = true;
    const light = new THREE.DirectionalLight( 0xddffdd, 0.6 );
    light.castShadow = true;
    scene.add(light);
```

**Comment by jedhelmers** [comment]
Thank you @zhouchengshi. That fixed it! What the heck? haha

The new light source was casting a light I didn't want. Fortunately, changing the intensity to 0.0 kills the light while keeping the OutlinePass. Thanks again!

**Comment by isimonsm** [comment]
I stumbled upon the same issue when updating three.js to 0.144.0.
Adding a directional light as suggested by @zhouchengshi resolves the issue, but even with an intensity of 0.0, the light will cast a shadow that we would like to avoid in our scene.
We are already using a directional light to cast shadows that is attached to an object in our scene that will rotate with gravity (specified by the user). This way, the shadow is always cast from "above" as intended. I can resolve the OutlinePass issue by attaching the light to the scene itself instead of the object, but that obviously fixes the direction of the light in space.
Adding another directional light with intensity 0.0 and castShadow=false does not work, unfortunately. This seems like a bug since it only occurs since version 0.144.0. If you think otherwise, do you have any suggestion to fix the issue without changing the behavior of the directional light?

**Comment by jedhelmers** [comment]
@isimonsm interesting. Have you tried setting the color to black `new THREE.DirectionalLight( 0x000000, 0.0 )`?

**Comment by isimonsm** [comment]
@jedhelmers Yes, it still casts a shadow, unfortunately. Though I assume that the directional light casting a shadow is the reason it fixes the issue in the first place. Thanks for the suggestion though!
