### ISSUE TITLE
VRML file loaded Error.

### ISSUE THREAD

**Issue by XMZOVO** [mrdoob/three.js#24644]
This is the roughly correct result I get when I open it in blender.
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/11494827/190349580-dc601d08-af36-40f9-ae34-d50bdcbb4f26.png">
But inside theejs the result is this, all spherical points are gone.
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/11494827/190349347-b11a3e10-77d1-425c-9a92-4ffecf1ab28a.png">
I get these error messages below：
<img width="987" alt="image" src="https://user-images.githubusercontent.com/11494827/190349512-7ce86c3d-3d77-40dd-8706-b636327174f0.png">

this is my file：
[g4_01.wrl.zip](https://github.com/mrdoob/three.js/files/9573210/g4_01.wrl.zip)

**Comment by Mugen87** [comment]
It seems the file contains some `Anchor` definitions which the loader does not support.

Any chances to export the VRML asset from Blender as a glb file? 

I doubt there will be full support for the `Anchor` node since it represents URLs to other VRML files that are fetched when you click on the node. This part of the VRML spec is controversial and I think it's better to not add support to it.

**Comment by XMZOVO** [comment]
This is a file automatically generated by the Geant4 toolkit, I can't manually convert the format every time I run it, unfortunately, if it can't be adapted in theejs, I have to keep it as it is or wait for the Geant4 version update.
