### ISSUE TITLE
Chaining multiple onBeforeCompile

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#25229]
### Description

Maybe that exists somewhere already, wondering if that would be useful for everyone.

Some libs uses onBeforeCompile to pass custom uniforms / defines to material ( like cascading shadow etc.. ), but what if onBeforeCompile is already defined somewhere / already extending built-in materials already in the current app ? 

### Solution

Would it be correct to pass onBeforeCompile as an array of functions ? so that it executes all it needs ?  

### Alternatives

.

**Comment by marcofugaro** [comment]
You can currently save the existing `onBeforeCompile` and call it in the new one:

```js
const oldOnBeforeCompile = material.onBeforeCompile
material.onBeforeCompile = (program) => {
  oldOnBeforeCompile(program)
  // other modifications to the shaders...
}
```

However this is a bit confusing since users don't know if a lib ([three-csm](https://github.com/StrandedKitty/three-csm) like you pointed out) is already using onBeforeCompile.
A better api other than onBeforeCompile be ideal.

**Comment by Mugen87** [comment]
What @marcofugaro suggested is an appropriate workaround.

If `onBeforeCompile` is already assigned by an app or external lib, I would assume it is also responsible for handling the mentioned issue. I mean any built-in property or callback function like the transform properties or `Object3D.onBeforeRender()` could be in use by library or application logic. This issue is not specific to `onBeforeCompile()`.

> A better api other than onBeforeCompile be ideal.

That would be the upcoming node material.

**Comment by marcofugaro** [comment]
> That would be the upcoming node material.

Cool! Ah I see now the discussion in #22504, but I am curious to get some feedback from @Samsy, we don't know what he is trying to do.

@Samsy would this be a better solution for your use-case in the future?
This example uses wgsl, for the `color` value, but you get the idea.

https://github.com/mrdoob/three.js/blob/044d7b292e35409d883de79ac80950261864cc0f/examples/webgpu_materials.html#L161-L172

**Comment by Mugen87** [comment]
Closing since the feature request itself (array of callbacks) is not going to be implemented.

But feel free to continue the discussion regarding https://github.com/mrdoob/three.js/issues/25229#issuecomment-1371006529.
