### ISSUE TITLE
Add a VertexNormals check to Mesh()

### ISSUE THREAD

**Issue by dcromley** [mrdoob/three.js#25285]
### Description

I think I now have my understanding correct: Re: Mesh(geometry, material)

o) If the geometry is BufferGeometry then the VertexNormals are not initially calculated.
o) If the material is MeshNormalMaterial with flatShading:false (default) then the VertexNormals are needed.
o) With this combination, Mesh(geometry, material) will not result in a visible object.
I just went through finding why my object was "non-visible".

### Solution

My suggestion is: 
to add a step to Mesh() which would check if VertexNormals are needed and not present, and if so, to call .calculateVertexNormals().

### Alternatives

Add a note in the BufferGeometry doc that says to call .calculateVertexNormals() if you don't have flatShading:true.

### Additional context

Happy new year -- keep up the good work!

**Comment by Mugen87** [comment]
There is already `BufferGeometry.computeVertexNormals()`. However, it's no good idea to add this call automatically to the `Mesh` constructor when a `MeshNormalMaterial` is used and no normals are defined. Simply because materials can be changed at a later point, too, e.g. from `MeshBasicMaterial` to `MeshNormalMaterial`. If you have no vertex normals, you run into the same issue again. The engine also generates no texture coordinates if you want to use textures but have no `uv` coordinates. 

Automatic generation of vertex data in such situations are not always possible and lead to unexpected or unwanted behavior. It's really up to the user to generate these data if necessary. Or create the upfront when designing the asset in a tool like Blender.
