### ISSUE TITLE
GroundProjectedEnv naming is confusing as it's a background, not an environment

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#25287]
### Description

Since #24311 there is a way to make a ground projected environment - which works great! 

But the naming is now somewhat confusing:
- in three, generally "background" is something visible behind the scene and "environment" is used for e.g. IBL and reflections
- see the docs: https://threejs.org/docs/#api/en/scenes/Scene.environment vs. Scene.background
- now, "GroundProjectedEnv" has nothing to do with some PMREM/IBL environment - it should probably be a GroundProjectedBackground and not Env (?)
- in the sample, it does use the environment and not the background map, which adds to the confusion when someone actually uses a separate background and environment cubemap 

### Version
latest

**Comment by Mugen87** [comment]
We went for `GroundProjectedEnv` because the technique behind the class is called "ground projected environment maps". According the my personal experience up to this point, `GroundProjectedEnv` as a class name had a good acceptance so far since especially experienced devs know the technique and thus understand the purpose of the class.

> it should probably be a GroundProjectedBackground and not Env (?)

As you have mentioned `GroundProjectedEnv` is not assigned to `Scene.background` so I would find this name actually worse. The current one at least describes the technique. But I admit there is a the conflict with `Scene.environment`...

Maybe `GroundProjectedSkybox`?

**Comment by melMass** [comment]
Glad I finally found this issue, I was only seeing references of GroundProjectedEnv everywhere, my IDE wasn't complaining but vite was (@types/three is outdated)
