### ISSUE TITLE
Changing mesh material from opaque to transparent stopped working since r.148

### ISSUE THREAD

**Issue by timmevandermeer** [mrdoob/three.js#25307]
### Description

Hi,

I am running into a regression / change that happend in r.148. When a mesh is initialized with an opaque material, that material doesn't correctly update when set to transparent. If you check the live example, it works fine in r.147.

### Reproduction steps

1. Initialize a mesh with an opaque material
2. Set `opacity` to < 1 and set `transparent` to `true`

### Code

See live example

### Live example

Click the cube to change from opaque to transparent object. The example uses @react-three/fiber, but I don't think that is the cause.
- [Working example on r.147](https://codesandbox.io/s/three-js-r147-opaque-to-transparent-u7y2nc?file=/src/canvas/ExampleBox.tsx)
- [Broken example on r.148](https://codesandbox.io/s/three-js-r148-opaque-to-transparent-44eeut?file=/src/canvas/ExampleBox.tsx)

### Version

r148

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Do you mind demonstrating the issue without `@react-three/fiber`? It's in general notgood to reproduce engine issue by using third party libraries.

We add fiddles to the issue template that should provide a proper foundation for reproduction cases.

**Comment by donmccurdy** [comment]
Seems to be related to DoubleSide vs. TwoPassDoubleSide —

https://codesandbox.io/s/three-js-r148-opaque-to-transparent-forked-fb78yo?file=/src/canvas/ExampleBox.tsx

**Comment by Mugen87** [comment]
Normally, you have to set `needsUpdate` to `true` if you change the `side` property after the first render of a material so defines like `DOUBLE_SIDED` or `FLIP_SIDED` are correctly set in the shader. 

This was not necessary when the two pass rendering for `THREE.DoubleSide` was introduced since internally it was handled with two passes and `needsUpdate` was correctly set by the renderer.

This happens now for `THREE.TwoPassDoubleSide`. So this is actually an issue in `@react-three/fiber`. The library should set `needsUpdate` to `true` when the properties are changed like in the live example.

**Comment by drcmda** [comment]
> bug was actually a problem in the above code.
> So this is actually an issue in @react-three/fiber. The library should set needsUpdate to true when the properties are changed like in the codesandbox.

@Mugen87 only writing since i fear more issues will be made: fiber _is_ threejs. it doesn't wrap or bind to three, it doesn't change how it works. `<mesh />` is `new THREE.Mesh()`. there is zero code on top of that. this is generally the difference with renderers and bindings. if something needs a flag in three, the same flag needs to be there if expressed declaratively.

**Comment by donmccurdy** [comment]
For future readers, one way to express this in R3F is —

```jsx
<meshStandardMaterial
  side={DoubleSide}
  transparent={transparent}
  opacity={transparent ? 0.5 : 1.0}
  onUpdate={(self) => (self.needsUpdate = true)} />
```

**Comment by Mugen87** [comment]
> fiber is threejs

Sorry, but I don't agree with this statement.

**Comment by donmccurdy** [comment]
I think he's just saying that any time three.js requires `needsUpdate = true`, fiber will need that too. It's fair to ask that examples be written in plain three.js here, but this is the right place for the issue report. R3F developers cannot be expected to answer about how DoubleSide / TwoPassDoubleSide affects needsUpdate in r147 vs r148.

**Comment by Mugen87** [comment]
We have a migration guide for that: https://github.com/mrdoob/three.js/wiki/Migration-Guide#147--148

Granted, the change was not noted until some days ago so that oversight was of course a mistake.

**Comment by timmevandermeer** [comment]
I don't think the migration guide covers it sufficiently. I created a new vanilla three.js example (with some comments to point out behavior): https://codesandbox.io/p/sandbox/ecstatic-grass-8d60o7?selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A119%2C%22startColumn%22%3A25%2C%22startLineNumber%22%3A119%7D%5D&file=%2Fsrc%2Fmain.ts

Using `TwoPassDoubleSide` does not recreate old behavior (it doesn't render double side when opaque) and `DoubleSide` stopped rendering transparency at all when not initialized as such (unless setting `needsUpdate`, presumably).
