### ISSUE TITLE
Docs: Specify output encoding responsibilities when using ShaderMaterial.

### ISSUE THREAD

**Issue by Giwayume** [mrdoob/three.js#25432]
### Description

When using ShaderMaterial, the `outputEncoding` property on the renderer appears to just do nothing. 

The [color management](https://threejs.org/docs/?q=color#manual/en/introduction/Color-management) page is helpful, but it does not mention the behavior or responsibilities when using ShaderMaterial.

It also appears any textures consumed in ShaderMaterial are in linear RGB, irregardless of the `encoding` property. Though I may be misunderstanding how this works.

### Reproduction steps

1. Create a ShaderMaterial, have it output anything that would make color space conversion obvious, such as a gradient.
2. Observe that switching between `sRGBEncoding` and `LinearEncoding` on the renderer does nothing to change the output color for this material.

### Code

This writes the top half of a square with gamma corrected output, bottom half no correction.

```frag
varying vec2 vUv;  
void main() {
  float intensity = vUv.x;
  vec3 gradient = vec3(intensity, 1.0 - intensity, 0.0);
  if (vUv.y > 0.5) {
    gl_FragColor = vec4(pow(gradient.rgb, 1.0 / vec3(2.2)), 1.0);
  } else {
    gl_FragColor = vec4(gradient.rgb, 1.0);
  }
}
```

### Live example

https://jsfiddle.net/b896ukLg/1/

### Screenshots

**GIMP Output:**
TOP - Gradient tool blending in linear RGB
BOTTOM - Gradient tool blending in perceptual RGB

![image](https://user-images.githubusercontent.com/4075314/216758658-81518992-a7ae-4a10-9ed0-7c2580af1286.png)

**ThreeJS Output**
TOP - Gamma 2.2 conversion in shader for gl_FragColor
BOTTOM - Raw output of color

![image](https://user-images.githubusercontent.com/4075314/216758684-82461cb3-6afe-4063-9611-a8f6450b4f1c.png)

### Version

r149

**Comment by Mugen87** [comment]
> It also appears any textures consumed in ShaderMaterial are in linear RGB, irregardless of the encoding property. Though I may be misunderstanding how this works.

Since the engine uses `SRGB8_ALPHA8` for sRGB encoded textures, WebGL takes care about color space conversion. The only point where a manual color space conversion is required is when writing to the default framebuffer (screen). Hence, you only have to add the `encodings_fragment` shader chunk to your fragment shader to fix the issue. 

I would have updated the fiddle but it seems the service is down right now. Essentially you need this line at the end of your fragment shader main function:
```
#include <encodings_fragment>
```
The problem is this code might not always be the final line of the fragment shader since other stuff (like premultiplied alpha) has to come later. And we don't know in advance how the custom shader looks like so it's not easy to document this.

**Comment by Mugen87** [comment]
@Giwayume Do you think a general statement in the guide would be okay as well? Something like:

> Custom materials based on `ShaderMaterial` and `RawShaderMaterial` have to implement their own output color space conversion.

This paragraph could be added to the `Output color space` section.

**Comment by Giwayume** [comment]
That sounds good, I'd also mention the encoding fragment bit for ShaderMaterial since I'm not sure where else someone would find that information.

**Comment by epreston** [comment]
Could you test swapping `sRGBEncoding` and `LinearEncoding` on this example ?  You should see a difference.

https://github.com/epreston/template-web-threejs

I might have an update for you.  Need a moment to adjust the fiddle you linked.
