### ISSUE TITLE
OrbitControl can not pan with right mouse button

### ISSUE THREAD

**Issue by steve3d** [mrdoob/three.js#25609]
### Description

I have an application which still use 0.146 version, yesterday, I updated threejs to 0.150, then I found out that orbitcontrol can not pan with the right mouse button.

I did some digging, the `onMouseMove` and `onMouseDown` completely ignored the right mouse button, and the `onContextMenu` is just preventDefault by now.

So, I'm wondering if this is a designed change or a bug?

### Reproduction steps

1. using r150 
2. create an scene with orbitcontrols
3. right mouse pan didn't work, some kind of strange dolly action instead.

### Code

no need, just checkout this example, and use right mouse button to pan:

https://threejs.org/examples/#webgl_animation_keyframes

### Live example

https://threejs.org/examples/#webgl_animation_keyframes

https://threejs.org/examples/?q=orbit#misc_controls_orbit

### Version

r150

**Comment by Mugen87** [comment]
`webgl_animation_keyframes` disables panning on purpose by setting `enablePan` to `false`. `misc_controls_orbit` works as expected on my Windows machine.

> and the onContextMenu is just preventDefault by now.

The context menu is prevent since the beginning. 

It's probably best if you ask for help at help at the [forum](https://discourse.threejs.org/) first. If it turns out to be a regression, this issue can be reopened.

**Comment by steve3d** [comment]
sorry, my bad, I forgot that my mouse has customized button settings.
