### ISSUE TITLE
Missing `AnimationAction` export

### ISSUE THREAD

**Issue by krispya** [mrdoob/three.js#25674]
### Description

It appears that the `AnimationAction` export is missing. Attempting to import it will only get undefined. When I check the raw build files, like cjs, it is missing there. 

### Reproduction steps

1. Import `AnimationAction` and attempt to use it.

### Code

See below.

### Live example

Here is a sandbox: https://codesandbox.io/s/missing-animationaction-export-rplgk0

### Version

150.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by linbingquan** [comment]
In `AnimationAction` API Docs: https://threejs.org/docs/#api/en/animation/AnimationAction
has this note:

Note: Instead of calling this constructor directly you should instantiate an AnimationAction with [AnimationMixer.clipAction](https://threejs.org/docs/index.html#api/en/animation/AnimationMixer.clipAction) since this method provides caching for better performance.

Calling this `AnimationAction` maybe has performance problem.
That why it does not export. https://github.com/mrdoob/three.js/pull/25676 maybe to close.

**Comment by linbingquan** [comment]
In [AnimationAction](https://threejs.org/docs/#api/en/animation/AnimationAction) API Docs has this note:

Instead of calling this constructor directly you should instantiate an AnimationAction with [AnimationMixer.clipAction](https://threejs.org/docs/index.html#api/en/animation/AnimationMixer.clipAction) since this method provides caching for better performance.

Calling this `AnimationAction` maybe has performance problem.
That why it does not export, https://github.com/mrdoob/three.js/pull/25676 maybe to close.

**Comment by krispya** [comment]
Thank you for pointing that out. It may be the reason.
Our use case was to do `instanceof` checks using `AnimationAction`. Is there an alternative way to type check objects to ensure they are instances of `AnimationAction` that three suggests?

**Comment by LeviPesin** [comment]
Maybe we can add `.isAnimationAction` flag similar to how it is done for other Three.js' classes.
