### ISSUE TITLE
Version bump in toJSON after changes in ColorManagement 

### ISSUE THREAD

**Issue by repalash** [mrdoob/three.js#25989]
### Description

Since version r149, the files loaded pre-r149 look different since the color space used is different when exporting the files. But there is no way to distinguish between the JSON files loaded before and after this change. 

### Solution

Bumping the json metadata version number in the `toJSON` functions in `Material`, `Object3D`, `Node` etc, would make it possible to handle this case while loading the files in our applications using the defaults.

### Alternatives

An alternative would be to also save the color space with the JSON in either the metadata or the color value.
Or another alternative is to change the default color space in three.js JSON to linear, to remain consistent with earlier versions (and color values in GLTF specification) and remove the need to eyeball the values again.

### Additional context

Continuation of https://discourse.threejs.org/t/updates-to-color-management-in-three-js-r152/50791/38

**Comment by donmccurdy** [comment]
> files loaded pre-r149 look different since the color space used is different when exporting the files...

Sorry to be picky here — three.js previously saved colors in whatever color space was given by the user. This would have been sRGB _or Linear-sRGB_ depending on the application. With the new defaults, we can now say the hex code in the JSON is always defined to be sRGB. It is very important that we know which is which.

> Or another alternative is to change the default color space in three.js JSON to linear...

The default ["working color space"](https://threejs.org/docs/#manual/en/introduction/Color-management) in three.js is Linear-sRGB. Renderer operations like lighting all operate on Linear-sRGB values, and THREE.Color objects' RGB components are also Linear-sRGB. 

> ... to remain consistent with earlier versions (and color values in GLTF specification) and remove the need to eyeball the values again ...

The change you're probably referring to is that we now interpret hexadecimal and CSS colors as sRGB. Colors are sRGB by default in HTML, CSS, and virtually all color pickers, so this is a consistent choice. When given an sRGB color, we must convert it to the working color space, Linear-sRGB. There is no need to convert colors from glTF, because they are already Linear-sRGB.

I would advise against trying to eyeball colors while migrating to r152 in any case – precise conversions are quite possible.

***

With that context — Yes, I would be comfortable with putting something into the JSON schema to help applications differentiate between files pre/post r152. But as I mentioned above, your colors may have been sRGB before and after r152 anyway, it depends on the application producing these files.

Incrementing the version (4.5 → 4.6) might be the simplest thing. I would prefer that over trying to make claims about the color space your application might be using, and your application can use the version number however is right for you. 

@Mugen87 @WestLangley does this sound OK?

**Comment by Mugen87** [comment]
I'm fine with that 👍 .

**Comment by Mugen87** [comment]
Yes, as suggested by @donmccurdy.
