### ISSUE TITLE
WebGPURenderer compile failed

### ISSUE THREAD

**Issue by lovelori** [mrdoob/three.js#25997]
### Description

[CD.zip](https://github.com/mrdoob/three.js/files/11411103/CD.zip)

I tried to show this model using _webgpu_loader_gltf_compressed.html_
It showed warning messages and failed to show

> D3D compile failed with: C:\Program Files\Google\Chrome\Application\113.0.5672.64\Shader@0x00006B080EAB0800(6,9-21): error X4601: the size of constant buffer cbuffer_tint_symbol_2 is 4708 16-byte entries, which exceeds maximum allowed size of 4096 entries
> 
>  - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor]).

But it works well using _WebGLRenderer_ 

### Reproduction steps

1.copy the CD.glb model to the \three.js\examples\models\gltf\ folder and modify webgpu_loader_gltf_compressed.html to load it
2.open the page in browser and it fail to show with the waring message above

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![image](https://user-images.githubusercontent.com/17640406/236595687-96de9b49-f18f-47aa-bf64-9e1ecbdbfb51.png)

### Version

r152

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by sunag** [comment]
The problem was found and I'm working I'm already working on a solution. It is related to the instances, the problem that WebGPU does not accept `Matrix4` attributes ( `mat*` [vertex format in WebGPU](https://www.w3.org/TR/webgpu/#vertex-formats) context ). The instance has to be moved to attributes, currently I think I was a bit optimistic in leaving it in uniforms, to build a `Matrix4` I have to send 4 `Vector4`, the solution will be to create a `bufferAttribute` that uses `Instanced-InterleavedBufferAttribute`, I won't implement this last class but the support for WebGPU.
