### ISSUE TITLE
GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.

### ISSUE THREAD

**Issue by crystalthoughts** [mrdoob/three.js#25990]
### Description

I notice this error message was mentioned  in a closed ticket, under a different scenario. It looks like the transmission shader is causing issues. Is it safe to ignore or is it preventing proper functionality?

As an aside, is this shader the same as in the GLTF example?

### Reproduction steps

See the fiddle. Turning off transparency on the material will prevent the error.

### Code

I have a HDRI loaded (inside my init function):

Adding this to my scene causes the title error:

```
    const donut = new THREE.TorusKnotGeometry
    
    const glass = new THREE.MeshPhysicalMaterial( {
        color: 0xffffff,
        // transmission: 1,  // turning this on is the issue
        opacity: 1,
        metalness: 0,
        roughness: 0,
        ior: 1.5,
        thickness: 0.01,
        specularIntensity: 1,
        specularColor: new THREE.Color(0xffffff) ,
        envMapIntensity: 1,
        side: THREE.DoubleSide,
        transparent: true
    } );
    const donutMesh= new THREE.Mesh(donut,glass);
```

    
 I assume it's related to the refraction code?

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/danvenn/q1o7k69w/57/)

### Screenshots

![image](https://user-images.githubusercontent.com/6608960/236394280-1278655f-3cdc-4fdc-9301-8a082ff9d1e6.png)

### Version

0.15.2 (latest)

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
I don't know why but enabling anti-aliasing fixes the issue: https://jsfiddle.net/kd0jf95y/

Can you please confirm this on your side?

**Comment by crystalthoughts** [comment]
Yes, this prevents the errors. How strange.

**Comment by Mugen87** [comment]
I guess we should report this to the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list). It's strange that the anti-aliasing setting makes a difference.

BTW: Safari 16.4 on macOS does not show a warning.

**Comment by crystalthoughts** [comment]
Is aa handled by chrome? What should the ticket look like ?

**Comment by Mugen87** [comment]
> Is aa handled by chrome?

Passing `antialias: true` to `WebGLRenderer` enables the default anti-aliasing by WebGL. So it is not implement on engine-level.

> What should the ticket look like ?

It would be good to track the issue further down so we can provide a more simple example to the Chromium bug tracker.

**Comment by Mugen87** [comment]
Investigated the issue a bit more and the the warning pops up with `r151` the first time: https://jsfiddle.net/1r83edh0/1/

When reverting #25502, the warning goes away. So it seems the two pass rendering of transmissive objects introduces the issue.

**Comment by Mugen87** [comment]
> When reverting https://github.com/mrdoob/three.js/pull/25502, the warning goes away. So it seems the two pass rendering of transmissive objects introduces the issue.

The problem is indeed this part:

https://github.com/mrdoob/three.js/blob/90858b213dcab40509d6b98f776c5e9a4b29dd83/src/renderers/WebGLRenderer.js#L1392-L1406

Meaning when the transmissive objects are rendered with their back side (which is done to achieve proper inner reflections). The transmissive objects use an environment map this is equal to the active render target which explains why the browsers complain about the feedback loop.

It would still be interesting to know why enabling anti-aliasing masks this issue.

**Comment by Mugen87** [comment]
> When reverting https://github.com/mrdoob/three.js/pull/25502, the warning goes away. So it seems the two pass rendering of transmissive objects introduces the issue.

The problem is indeed this part:

https://github.com/mrdoob/three.js/blob/90858b213dcab40509d6b98f776c5e9a4b29dd83/src/renderers/WebGLRenderer.js#L1392-L1406

Meaning then the transmissive objects are rendered with their back sides (which is done to achieve proper inner reflections). The objects are using a transmissive texture (`transmissionSamplerMap`) which is equal to the active render target which explains why the browsers complain about the feedback loop.

It would be still interesting to know why enabling anti-aliasing masks the issue.

**Comment by aardgoose** [comment]
@Mugen87 FWIW Looking at the FF source, the antialias path allocates a RenderBuffer object as a target while the non-AA path allocates a texture directly, presumably the same texture that is already in use. I presume the other browsers follow a similar pattern.

**Comment by Mugen87** [comment]
Good point! I think we have to re-evaluate the issue: The transmission implementation can be considered as broken since #25502 introduced a feedback loop in `renderTransmissionPass()`. The fact that the implementation works with enabled anti-aliasing is a side effect of how browser do anti-aliasing.

**Comment by Mugen87** [comment]
I've tried to fix the issue by copying the transmission render target into a texture (via `copyFramebufferToTexture()`) and use the texture for the back side pass, however, it did not work so far. The warning is gone but the transmissive object does not show up anymore.

**Comment by Mugen87** [comment]
> The fact that the implementation works with enabled anti-aliasing is a side effect of how browser do MSAA.

Clarification: The problem is not the anti-aliasing of the default framebuffer. It's the usage of multisampled render targets. If you always use `0` at the following line, you can trigger WebGL warning, even with `antialias` set to `true`.

https://github.com/mrdoob/three.js/blob/7cba91cee7ff1b36250c1535f717255555b6874b/src/renderers/WebGLRenderer.js#L1349

**Comment by AlexanderProd** [comment]
I'm getting the same warning when calling `renderer.render` twice in my render loop. 

```
function render() {
  requestAnimationFrame(render);

  update(0.01);

  renderer.setRenderTarget(renderTarget);
  renderer.render(scene, camera);
  renderer.setRenderTarget(null);
  renderer.render(scene, camera);
}
```  

Enabling AA didn't fix it for me.

**Comment by LukaTizic94** [comment]
I have the same problem. Did you find any solution? @AlexanderProd
