### ISSUE TITLE
package size and inlined dependencies

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#26236]
### Description

the published three package on npm currently carries around ~23mb, some of the weight comes from inlined dependencies.

this contributes to slow installs, slow dx, slow tooling and overall bloat of node_modules. a package should normally only contain runtimes and declare its dependencies.

but nothing inside, for instance, [examples/jsm/libs](https://unpkg.com/browse/three@0.153.0/examples/jsm/libs/) can even be used, you cannot fetch from within node_modules, these files get shipped for nothing.

the inlined packages also exist on npm on their own:

```json
    "chevrotain": "^10.1.2",
    "draco3d": "^1.4.1",
    "fflate": "^0.6.9",
    "ktx-parse": "^0.4.5",
    "mmd-parser": "^1.0.4",
    "opentype.js": "^1.3.3",
    "potpack": "^1.0.1",
    "zstddec": "^0.0.2"
```

### Reproduction steps

1. npm install three

### Code

```js
// code goes here
```

### Live example

* https://unpkg.com/browse/three@0.153.0/examples/jsm/libs/

### Screenshots

<img width="440" alt="Screenshot 2023-06-12 at 10 27 30" src="https://github.com/mrdoob/three.js/assets/2223602/025a2cf9-4b7a-4e9d-bc5a-e01b45ffc3be">

### Version

r0.153.0

### Device

Desktop, Mobile, Headset

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS, Linux, Android, iOS

**Comment by marcofugaro** [comment]
I believe we can do something similar to the [webgl_geometry_csg](https://github.com/mrdoob/three.js/blob/46ae256c89ec230bc7e9af322af0c2212201a485/examples/webgl_geometry_csg.html#L36-L37) example, for the examples on the website we can use import maps pointing to unpkg.com, whereas on npm we could declare the packages as optional peerDependencies.

However this comes with the burden of having to tell the user to install a specific version of `fflate` when using the `FBXLoader` for example. What's your view on this?

**Comment by LeviPesin** [comment]
> However this comes with the burden of having to tell the user to install a specific version of fflate when using the FBXLoader for example. What's your view on this?

I think that users already do this for packages like react-three-fiber, so it shouldn't be too much of an issue?

**Comment by donmccurdy** [comment]
> but nothing inside, for instance, [examples/jsm/libs](https://unpkg.com/browse/three@0.153.0/examples/jsm/libs/) can even be used

This claim is incorrect. _Static resources_ cannot be fetched from node_modules in most cases, but JavaScript modules certainly can. Any use of KTX2Loader is getting dependencies this way:

https://github.com/mrdoob/three.js/blob/ed2bfb2e56ee84077372735acdf4425d96549fea/examples/jsm/loaders/KTX2Loader.js#L61-L62

If I create a new react+next.js-based project with three.js, my dependencies are going to look something like this:

![next_deps](https://github.com/mrdoob/three.js/assets/1848368/074923b4-0d94-4cf4-8d4d-5f47ae48c8de)

That's obviously not great, but three.js is not a particularly bad offender on the list either. Is this such a major issue that we'd need to throw all of examples/jsm/libs out?

I understand the R3F community is using [`three-stdlib`](https://github.com/pmndrs/three-stdlib) rather than these files, and perhaps a more complete proposal could be made to change how we're structuring the project, but I don't feel this issue currently describes motivating reasons for such a change.

**Comment by drcmda** [comment]
yes, the javascript files can, but what's the point when each and every one of them is on npm? the binaries which have most of the heft cannot be used in any meaningful way, they are there for nothing.

**Comment by Mugen87** [comment]
>  Is this such a major issue that we'd need to throw all of examples/jsm/libs out?

Definitely no.

> perhaps a more complete proposal could be made to change how we're structuring the project, but I don't feel this issue currently describes motivating reasons for such a change.

Agreed.

**Comment by mrdoob** [comment]
Does anyone want to do a treemap to illustrate what contributes to the 23mb?
