### ISSUE TITLE
Basic deferred rendering

### ISSUE THREAD

**Issue by MPanknin** [mrdoob/three.js#2624]
Hi everybody, 

just finished a first version of a deferred rendering example using your lovely library. 

http://blog.mpanknin.de/?p=848

It currently supports point light sources as well as deferred shadow maps.

It does not yet support everything else such as spot lights, point light shadows, etc. There's still a lot to do, however it can already handle a decent amount of  point lights. I was able to render > 1000 point lights on a GTX560 this afternoon. Framerate was something around 50.  

The G-buffer has to be filled in two passes unfortunately. One for depth and another for normals. No support for multiple MRT's.

If you are interested then I'm sure that I can release the source sometime. However before doing that I need to clean up a couple of things as the code is a bit messy here and there.

What do you think?

**Comment by mflux** [comment]
2015 calling here. Is anyone actively working on a new WebGLDeferredRenderer at this point? I want to know before I dive into this rabbit hole; or, worst-case-scenario, abandon THREE altogether (please no) as unfortunately my project's visual design absolutely requires it.

Are there any known significant roadblocks due to the way THREE was re-engineered from R71->R72 that blocks the deferred rendering path?

**Comment by bhouston** [comment]
I think the issue is WebGL 1.0 doesn't really support multiple render targets except through the poorly supported WEBGL_draw_buffers extension (<50% of browsers, almost no mobile devices.)  Thus leading to deferred not really being easy to implement in a way that is efficient.  I think everything changes with WebGL 2.0, if and when that arrives.

**Comment by mflux** [comment]
That's good to know, thanks! 

As WebGLDeferredRenderer was always part of Extras, is the plan currently to make it into main WebGLRenderer when better support is available? We can use WEBGL_draw_buffers as-is for our projects since our target is not mobile, and even the previous version of the renderer offered decent performance already.

Anyway, if anyone has plans to do a deferred rendering pipeline down the road with THREE.js in WebGL 2.0 then I can just keep working as if nothing's changed on R71.

**Comment by won3d** [comment]
If you are willing to do some jiggery-pokery to pack multiple values into a
single floating-point render target, then you can do deferred rendering
without a huge hit. If you have a copy of WebGL Insights, then you can
check out my friend's (Nick Brancaccio of Floored, Inc., where I am also a
technical advisor) chapter on their production deferred renderer, Luma.

That chapter is the second best thing Nick wrote for that book -- the best
being his author blurb.
