### ISSUE TITLE
three/addons/loaders/GLTFLoader.js is missing

### ISSUE THREAD

**Issue by valera-rozuvan** [mrdoob/three.js#26500]
### Description

In the documentation https://threejs.org/docs/#manual/en/introduction/Installation - at the bottom of the page we have the section:

```text
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const controls = new OrbitControls( camera, renderer.domElement );
const loader = new GLTFLoader();
```

Upon closer inspection - the file `three/addons/loaders/GLTFLoader.js` is non existent, and it seems the entire folder `three/addons` is missing.

### Reproduction steps

See the provided URL. The documentation is wrong.

### Code

```
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
```

### Live example

![image](https://github.com/mrdoob/three.js/assets/2273090/e66fc98d-7f06-4665-b41c-b9cfb99b1eab)

### Version

r0.154.0

**Comment by marcofugaro** [comment]
It is a problem with typescript and specifically [three-ts-types](https://github.com/three-types/three-ts-types). I'd suggest you post the issue there.

With javascript + any bundler it works fine because of this redirect rule here:
https://github.com/mrdoob/three.js/blob/eeeffc87b472e43e99a95d5f7a5afec60803518c/package.json#L15
