### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by LeonardoDaLuz** [mrdoob/three.js#26536]
### Description

There is an error in the documentation.
It is not possible to import these modules, they do not exist in these folders:

import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

Page: 
https://threejs.org/docs/#manual/en/introduction/Installation

### Reproduction steps

Just enter in this link: https://threejs.org/docs/#manual/en/introduction/Installation

### Code

```js
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
```

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/80224694/848f7c31-a5f0-4b32-9b05-3bcb5181eb57)

The correct is:
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

And those are not detected by autoimport.

### Version

0.155.0

### Device

Desktop

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows

**Comment by Mugen87** [comment]
Importing should work since the `addons` alias is defined in the `exports` section in `package.json`:

https://github.com/mrdoob/three.js/blob/e5426b0514a1347d7aafca69aa34117503c1be88/package.json#L15

It seems your tool does not evaluate this entry.

When directly importing modules in the browser, you have to define an import map like explained in the guide. The import map makes sure imports with `three/addons/` can be resolved.
