### ISSUE TITLE
STLLoader: Add name to multiple solids 

### ISSUE THREAD

**Issue by AngyDev** [mrdoob/three.js#26537]
### Description

I'm working on an STL file with multiple solids and I'd like to have the name of the corresponding solid in the `geometry.groups`. In this way, would be possible for me to highlight the surface of the object and show a label with the corresponding solid name.

### Solution

It will be possible to get the name in the parsing of the STL file by adding a regex to check the name in the string and add it to the group. In this case, adding to the `BufferGeometry` `addGroup` method the param `name`.
This solution will be possible only for the ASCII STL file, not for the binary one.

I tried this solution and, it seems to work. If it's fine to add this functionality let me know, I'll try to work on it and then make a PR.

### Alternatives

I have no ideas for another possible solution, if someone has an alternative please let me know.

**Comment by Mugen87** [comment]
`BufferGeometry` has a `userData` property that could be used to store the name information. Would this be a valid option for you?

TBH, it's not 100% clear how we want to move on with `BufferGeometry.groups` so I would prefer a solution that does not require to change its API.

**Comment by AngyDev** [comment]
It can be a solution. The other solution is better because we have all the props together for each group, but I understand, if you want to change this, it's better don't change the group object.

Can I add the `userData` to the `STLLoader`?

**Comment by Mugen87** [comment]
> Can I add the userData to the STLLoader?

Yes. Other loaders use `userData` in a similar way so this would be a change that can be approved.

**Comment by AngyDev** [comment]
Thanks, I'll work on it

**Comment by Mugen87** [comment]
@AngyDev Let's assume `STLLoader` would be changed such that `BufferGeometry.groups` isn't used anymore. Instead, the loader would return a separate mesh for each solid and put these meshes into an instance of `THREE.Group`. 

Would your app run into issues when using this approach? It's essentially what `GLTFLoader` already does. The name for each solid could be easily assigned to `Object3D.name`. Besides, the performance would be identical since the number of draw calls does not change.

**Comment by AngyDev** [comment]
@Mugen87 I don't think so. Only a few questions.

1. This behavior will be for both ASCII and binary files? Because now you can only have groups with an ASCII file.
2. In my file the solids are part of the same mesh. The file is labeled, I mean, the solids indicate a group of faces that are together. When the loader returns the geometry, for example, I can highlight different parts of the mesh with different colors or show the name of the selected surface. Can the new implementation change this behavior?
Let me know if this second point is clear, it's not easy to explain 😅

**Comment by Mugen87** [comment]
> This behavior will be for both ASCII and binary files? Because now you can only have groups with an ASCII file.

Only the `BufferGeometry.groups` part would be updated.

> Can the new implementation change this behavior?

No, you can still highlight the individual parts of your asset. Since each group would be a mesh, you can still assign individual materials. You have actually more possibilities than before since you could configure properties of `Object3D` for each solid.

**Comment by AngyDev** [comment]
Perfect, thank you very much for the answers. I think there will be no problem.
