### ISSUE TITLE
Visual Artifacts when creating LineSegments from geometry with holes

### ISSUE THREAD

**Issue by ymarneth** [mrdoob/three.js#26557]
### Description

When attempting to create an outline with LineSegments for a mesh that contains holes, I have noticed that in some cases the outlines of the holes are connected. This problem only occurs on some of my meshes, but they seem to be consistently reproducible.

### Reproduction steps

1.  Create a Shape containing at least two holes
2.  Create a ShapeGeometry from the shape
3. Create a Mesh from the ShapeGeometry 
4. Create an EdgesGeometry from from the ShapeGeometry
5. Create LineSegments from the EdgesGeometry
6. Add the LineSegments to the mesh

### Code

[Example Repository](https://github.com/ymarneth/three-js-artifacts)

How my mesh is created:

```ts
export function createExampleObject(): Mesh {
	const shape = buildShape();

	const shapeGeometry = new ShapeGeometry(shape);
	const mesh = new Mesh(shapeGeometry, meshBasicMaterial);
	mesh.position.z = 0;

	const edgesGeometry = new EdgesGeometry(shapeGeometry);
	const outline = new LineSegments(edgesGeometry, lineBasicMaterial);
	mesh.add(outline);

	shapeGeometry.computeBoundingBox();

	return mesh;
}

function buildShape(): Shape {
	const shape = new Shape([
		new Vector2(-25333, 33190),
		new Vector2(-25333, -10808),
		new Vector2(25333, -10808),
		new Vector2(25333, 33190)
	]);

	shape.holes.push(new Shape([
		new Vector2(4663, 1191),
		new Vector2(4663, -2808),
		new Vector2(6663, -2808),
		new Vector2(6663, 1191),
	]));

	shape.holes.push(new Shape([
		new Vector2(14663, 1441),
		new Vector2(14663, 1191),
		new Vector2(18663, 1191),
		new Vector2(18663, 1441),
	]));

	return shape;
}
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
* [js-fiddle-bug-example](https://jsfiddle.net/himmelhund/a31dxgfr/7/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/62243662/31213299-5d86-4a14-adad-788ab8c579c8)

![image](https://github.com/mrdoob/three.js/assets/62243662/5ff25b12-5cb3-4873-a824-ac725d2d5438)

### Version

r155

### Device

Desktop

### Browser

Chrome, Firefox, Edge

### OS

Windows

**Comment by Mugen87** [comment]
Check out the following screenshot:

<img width="1095" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/9d521086-be91-4ed9-82b8-9a6859a9ce3f">

It shows the wireframe of the shape with focus on the left hole. The interesting part is the top side of the quad where you can see the narrow triangle that  goes to the right (it's actually the first triangle definition in `ShapesGeometry`). `EdgesGeometry` can't properly process the bottom edge of this triangle.

If you translate the second hole slightly upwards, the glitch goes away because the triangulation ends up differently and `EdgesGeometry` produces your intended output. https://jsfiddle.net/xprqv1ns/

The triangulation isn't wrong, imo. It's just not ideal input for rendering border edges with `EdgesGeometry`.

**Comment by Mugen87** [comment]
You might want to consider to detect the outline with a post processing pass like sobel. The edges would look like so:

<img width="1195" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/4682a0d1-6d48-4235-9588-d8205a5a7d72">

You could use this result to blend it with a custom shader over your beauty pass.

**Comment by Mugen87** [comment]
I don't think we can update the implementation in a reasonable way such that these use cases are supported. Let's consider this issue as a limitation of `EdgesGeometry`.
