### ISSUE TITLE
Add keyboard shortcuts for zoom in and out in OrbitControls.js

### ISSUE THREAD

**Issue by shelfmap** [mrdoob/three.js#26826]
### Description

For accessibility, the ability to use the keyboard is useful. Pan left/right etc is built-in, but not zoom in/out. Suggest using keyboard + and - for zoom in/out.

### Solution

Add keycodes PLUS: 107, MINUS: 109 to this.keys.
In function handleKeyDown, add extra case clauses 
                       case scope.keys.PLUS:
                                dollyOut( getZoomScale() );
                                scope.update();
                                break;
                        case scope.keys.MINUS:
                                dollyIn( getZoomScale() );
                                scope.update();
                                break;
works for me locally :)

### Alternatives

Not aware of any.

**Comment by Mugen87** [comment]
I like the idea of support keys for zoom but the suggested change does not work for me. E.g. on macOS the code for plus on the numpad is `NumpadAdd`.

**Comment by Mugen87** [comment]
`OrbitControls` like other control classes rely on `KeyboardEvent.code` which represents the physical key on the keyboard. This is ideal for all use cases where the user is supposed to control an object/camera with fixes keys on the keyboard (think of games which rely on WASD or arrow keys).

> Add keycodes PLUS: 107, MINUS: 109 to this.keys.

Regarding plus and minus, using the _numeric_ key code values doesn't work since the control classes check for `KeyboardEvent.code`. So the value `+` and `-` signs are e.g. `NumpadAdd` and `NumpadSubtract` when using the numpad. However, not all keyboards have a numpad so their plus and minus keys might be at different positions. I wonder if it is better to make a second `switch` statement in `handleKeyDown()` and check for `KeyboardEvent.key` instead. Meaning:
```js
switch ( event.key ) {

	case '+':

		dollyOut( getZoomScale() );
		needsUpdate = true;
		break;

	case '-':

		dollyIn( getZoomScale() );
		needsUpdate = true;
		break;

}
```
@felixmariotto Plus and minus signs are that established as WASD in context of gaming. It seems checking for the actual character seems better in this case, imo. What do you think about this?

**Comment by LeviPesin** [comment]
Wouldn't it be even better to replace all usages of `KeyboardEvent.code` with `KeyboardEvent.key`? The second would be more understandable because of comparing with the character instead of some abstract keycode.

**Comment by Mugen87** [comment]
`KeyboardEvent.code` is the better default for controls with has been approved in #21056. I don't think there is a need to question this policy. It definitely makes sense for many use cases. There are exceptions though like this issue.

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/26862#issuecomment-1768018822.
