### ISSUE TITLE
Fbx model not loaded as expected 

### ISSUE THREAD

**Issue by mcathena** [mrdoob/three.js#26918]
### Description

Hi I am using FBXLoader to load fbx in three.js. However, the fbx looks as shown in the image below. It's not in T pose and is not facing the camera. What is wrong with this? 
![image](https://github.com/mrdoob/three.js/assets/137363272/ca7acd7f-e063-4cc8-8ea2-36e347c65473)

### Reproduction steps

1. npm install
2. npm run dev

it will automatically load fbx.

### Code

[FBXLoader.zip](https://github.com/mrdoob/three.js/files/12840274/FBXLoader.zip)

### Live example

N/A

### Version

0.139.2

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
I can reproduce in the latest [three.js editor](https://threejs.org/editor/). 

The animation support is `FBXLoader` is fragile because there is no common way in FBX how bone matrices work, see #14204. I recommend you switch to a different format like glTF since I do not expect a fast fix in this context.

**Comment by Mugen87** [comment]
Merging this into #14204.
