### ISSUE TITLE
Both outlineEffect & MeshToonMaterial not compatible with iOS devices?

### ISSUE THREAD

**Issue by sdarpeng** [mrdoob/three.js#27038]
### Description

while I added any of these 2 feature into my page, the whole page rendered nothing on iPhone.
What is wrong?
What should I do?

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r157

### Device

Mobile

### Browser

Chrome, Safari

### OS

iOS

**Comment by Mugen87** [comment]
What version of iOS are you using? Do you mind sharing the generation of your iPhone, too?

Does this example also fail on your device? https://threejs.org/examples/webgl_materials_toon

**Comment by takahirox** [comment]
It's also very helpful if you can capture Browser console errors and share with us.

https://threejs.org/examples/webgl_materials_toon works fine on my iPadOS 16.6.1 + Safari, not iOS tho.

**Comment by sdarpeng** [comment]
Mine is iPhoneX , 16.16.1...I don't know why.

**Comment by sdarpeng** [comment]
![image](https://github.com/mrdoob/three.js/assets/55733077/8d464cc3-6819-4824-86c6-62eb7346fb11)
![image](https://github.com/mrdoob/three.js/assets/55733077/a96038db-8892-493a-946b-15eedd7d4fc7)

![image](https://github.com/mrdoob/three.js/assets/55733077/9746c350-348b-4cb2-93c9-b246870e9404)

Isn't google's DNS hijacking?

**Comment by CodyJasonBennett** [comment]
That script is for Google Analytics -- quite intentional. Am I correct in that no examples render on your device? We've seen a wave of issues when upgrading iOS (#26829, #26859) which I'm afraid this would fall under. The way we'd resolve this is by [reporting it to Apple](https://apple.com/feedback/safari.html) and waiting for a hotfix since it's too severe for us to dance around in three.js or elsewhere. I haven't updated my devices yet, but if you can't even render the [spinning cube example](https://jsfiddle.net/2nyxkmco/) then I wouldn't expect this to be a contrived reproduction at all.

**Comment by sdarpeng** [comment]
No. I can't render the cube. I don't know why my iOS is automatically upgraded since I always shut down auto upgrading option. 
![image](https://github.com/mrdoob/three.js/assets/55733077/fb3d479c-0344-4d62-87cd-1848a60adf0d)
It was 16.1.1 on 23rd,Sept. I took a screen shot at the system page at that day by chance.
![image](https://github.com/mrdoob/three.js/assets/55733077/819fc251-f4b3-4c2c-89bc-e2ab2ad9450c)

**Comment by Mugen87** [comment]
Okay even the simplest examples fail, then please report this to Apple. We can only that when more users complain, Apple will take more care of WebKit's WebGL implementation.
