### ISSUE TITLE
PointerLockControl Gets Mouse Skips From Time To Time

### ISSUE THREAD

**Issue by le0zheng** [mrdoob/three.js#27040]
### Description

This issue is seen even on the FPS examples provided by three.js [here](https://codepen.io/rafaelcastrocouto/pen/XmNjYe) and [here](https://codepen.io/viniciusSouza/pen/gOPVmKV). Every single application of PointerLockControls from established games like https://krunker.io/ to small time FPS examples on Github, I experience this issue as well.

After testing various mouse issue, it seems to have something to do with the polling rate. When my mouse's polling rate is set to 1000, there are instances where the camera "skips" or "teleports" which is unexpected. When my mouse's polling rate is set to 500, this happens but at a much lower rate. When my mouse's polling rate is set to 125, I rarely experience this.

Another factor in testing this was whether I was streaming or not. When I was streaming (I was streaming on Discord), this happened quite frequently. When I stopped streaming, this happened, but less frequently. (Note, previous polling rate experiments were done while streaming.)

Hardware Recreation:
- Windows 11
- Latest Version Of Chrome or Opera GX or Microsoft Edge
- Wireless mouse with adjustable polling rate (wired mouse was not tested, although I do not suspect it would make a difference)

### Reproduction steps

1. Enter PointerLockControl's locked state.
2. Move mouse around a lot.
3. From time to time, a random "jump" or "skip" or "teleport" happens.

### Code

N/A

### Live example

* https://codepen.io/rafaelcastrocouto/pen/XmNjYe
* https://codepen.io/viniciusSouza/pen/gOPVmKV
* https://venolabs.com/three-fps-demo/
* https://krunker.io/

### Screenshots

This is not my video, but a video of this in krunker.io:
https://youtu.be/oQRS7pAaxIc?t=16

Right at the end of the 16th second, his POV gets "teleported" to a different angle instantaneously. 
This also happens at the end of the 18th second as well.

---

Video revolving around fixing this issue seen in krunker (which I've also seen in FPS examples provided by three.js themselves) suggest to lower polling rate:
- https://www.youtube.com/watch?v=uPQ74xgc2Us&ab_channel=KrunkerDarez
- https://www.youtube.com/watch?v=sBqQ-O3JEb4&ab_channel=EffectiveTelevision

Reddit post with top comment suggesting to lower polling rate:
- https://www.reddit.com/r/KrunkerIO/comments/c03v2o/mouse_skipping/

This was how I found this connection between polling rate and PointerLockControl jumping.

### Version

N/A

### Device

Desktop

### Browser

Chrome, Edge

### OS

Windows

**Comment by gkjohnson** [comment]
If you can reproduce this consistently I would add logs for things like the mouse movement value or rotation values in [this onMouseMove function](https://github.com/mrdoob/three.js/blob/e070b99f0f0be152655572a729220caa3454de0c/examples/jsm/controls/PointerLockControls.js#L117-L136) to see what the source of the "jump" is - that might help determine whether the issue is a browser or device problem or not.

**Comment by le0zheng** [comment]
@gkjohnson Could you give what exactly within that function I should be logging? I am logging this `movementX` and `movementY` but I'm not seeing anything abnormal when it comes to these jumps.

**Comment by gkjohnson** [comment]
> Could you give what exactly within that function I should be logging?

You should log the intermediate and final variables that are used to drive the rotation of the camera. If the "jump" is caused by PointerControls you'll see larger "jumps" in values before and after you set the euler rotation, for example.

> When my mouse's polling rate is set to 500, this happens but at a much lower rate. When my mouse's polling rate is set to 125, I rarely experience this.

Can you also clarify what this means. How are you changing your mouse settings.

**Comment by Mugen87** [comment]
Can you also please test if this happens with non-Chromium browsers like Firefox?

**Comment by Mugen87** [comment]
Closing. Device issues like that can't be fixed on engine level.

**Comment by chuaml** [comment]
I faced similar issue as well. The _PointerLockControl_ mouse movement sometimes skip/jump/teleport around randomly, happen in Edge, Chrome, and FireFox. 
In FireFox, it feel more like something is pushing your mouse movement and move to wrong direction with smooth movement instead of teleporting and jumping around.

The issue seems kind of random, sometimes mouse movement will skip and jump around a lot, sometimes less often. But it happens enough to be noticeable.

The only workaround I found is to set the control `pointerSpeed` to 10 or higher value, which somehow result in much lesser chance (if not zero) on mouse teleporting and jumping around. But we are limited to use the super sensitive and fast mouse movement.

**Comment by welschmoor** [comment]
For me only on Chrome and only on Windows. I have tried different computers, different input devices, mac os. The mouse pointer skips quite a few pixels (a 100, 200, 300, sometimes I turn 180 degrees back) in the direction I am moving the mouse. 

This is a horrible issue, can't believe this exists in 2025. It's probably some Chrome bug. 

Update: setting the polling rate of the mouse to 125 solved the issue, any other value leads to bug

**Comment by doppl3r** [comment]
The most reliable solution I have found is to check the movement against the window width. This solution assumes the user will never exceed an extreme threshold (ex: 33% of view width).

```
document.removeEventListener('mousemove', event => {

  // Set threshold limits (33% of window)
  const isHorizontalSpike = Math.abs(event.movementX) > window.innerWidth / 3;
  const isVerticalSpike = Math.abs(event.movementY) > window.innerHeight / 3;
  
  // Check if mouse exceeds window threshold
  if (isHorizontalSpike || isVerticalSpike) {
    alert('THIS SOLUTION WORKED');
    return;
  }

  // The rest of your code

});
```

Source: https://stackoverflow.com/a/69672260/2510368
