### ISSUE TITLE
Big performance drop from version r154+

### ISSUE THREAD

**Issue by yaroslavnikiforov** [mrdoob/three.js#27108]
### Description

Version 0.154.0 brings a drop in the performance on the scene with `MeshPhysicalMaterial` and non-zero `transmission` property. This is also present in all later versions. 

As you can see from the provided screenshots it cuts fps significantly. With a similar setup as in the demo but a more complex model on the real scene, this causes crashes on mobile devices. 

### Reproduction steps

1. Open the demo in the provided sandbox in a browser with a disabled fps limit.
2. Change `three` from 0.153.0 to 0.154.0.
3. Compare the fps rate.

How to disable the fps limit in Mozilla Firefox:
1. Open `about:config`.
2. Search for `layout.frame_rate`.
3. Change the value from 1 to 0.

### Code

```js
const material = new MeshPhysicalMaterial({
    map,
    transmission: 0.5,
    opacity: 0
});
```

### Live example

* [codesandbox demo](https://codesandbox.io/s/zen-wood-vx5jrm)

### Screenshots

r153
<img width="351" alt="153" src="https://github.com/mrdoob/three.js/assets/42115630/ba0f5fc1-5108-409a-9df9-418f2f4f21be">

r154
<img width="351" alt="154" src="https://github.com/mrdoob/three.js/assets/42115630/43decba4-2088-499a-b07e-63ddd9bb16a3">

r158
<img width="351" alt="158" src="https://github.com/mrdoob/three.js/assets/42115630/267f0d17-139c-4480-85af-47df0efb5499">

r153 without transmission
<img width="351" alt="153 without transmission" src="https://github.com/mrdoob/three.js/assets/42115630/83ab070e-c0c2-4e29-b63e-55e2f0233e8b">

r154 without transmission
<img width="351" alt="154 without transmission" src="https://github.com/mrdoob/three.js/assets/42115630/3d0ce7a5-f11d-4104-b912-0e632c71853a">

r153 mobile
![Image from iOS](https://github.com/mrdoob/three.js/assets/42115630/30b08560-d945-47c9-aa88-bc6cccc44541)

r154 mobile
![Image from iOS (1)](https://github.com/mrdoob/three.js/assets/42115630/c48db4d1-8a70-4e9d-8a4d-0d10ca43db03)

### Version

r154

### Device

Desktop, Mobile

### Browser

Firefox, Safari

### OS

MacOS, Android, iOS

**Comment by Mugen87** [comment]
That is probably because of #26177. Multisampling is now active for all setups in order to avoid feedback loops.

**Comment by yaroslavnikiforov** [comment]
Is it possible to configure multisampling?

**Comment by Mugen87** [comment]
You definitely need it whenever you render double sided transmissive materials which is the common use case. 

> Is it possible to configure multisampling?

Right now, it is not possible. The configuration belongs to the transmissive render target so we can't introduce a material or object property. A new property would have to be on renderer level. This property would be problematic though since when not used correctly, you end up with WebGL warnings and broken renderings. 

Not sure how to proceed with this issue.

**Comment by yaroslavnikiforov** [comment]
Thank you for the answer, @Mugen87. Then I know that this is not a bug.

**Comment by Mugen87** [comment]
Closing for now.

**Comment by mrdoob** [comment]
> You definitely need it right now whenever you render double sided transmissive materials which is the most common use case.

Is the most common use case? Or is not the most common use case? 🤔

**Comment by Mugen87** [comment]
One [definition](https://www.digitizationguidelines.gov/term.php?term=transmissiveobject#:~:text=Term%3A%20Transmissive%20object&text=Definition%3A,way%20of%20the%20transmitted%20light.) of transmissive objects is:

> An object that is intended to be, or is generally, viewed or used in a manner that allows light to pass through from one side of the object to the other. The viewing or use of the object is by way of the transmitted light.

According to this, I would say transmissive objects should use double side rendering by default because you want render the back side of the opposing faces for achieving a plausible result.
