### ISSUE TITLE
Feature request: Add envMapIntensityNode for node materials

### ISSUE THREAD

**Issue by TobiasNoell** [mrdoob/three.js#27141]
### Description

ThreeJS already supports scaling the effect of the environment map by the `envMapIntensity` property of a material.
For the node materials, it would be very handy to also have a `envMapIntensityNode` property available to setup more complex intensity values rather than just a single float value.

### Solution

Add `envMapIntensityNode` property to `NodeMaterial`.

### Alternatives

Use existing `envMapIntensity`. However, this would only allow to hardcode to a static value per material.

### Additional context

In our context we want to scale down the environment intensity for `MeshPhysicalNodeMaterial`s having a high roughness value (use environment rather for highly reflective surfaces). The roughness is however provided as spatially-varying texture map and not as single float. So there really seems to be no other option, as far as I can tell?

**Comment by sunag** [comment]
In this case, wouldn't it just multiply the intensity of the map? 
cc @WestLangley

```js
const intensity = 2;

scene.environmentNode = cubeTexture( myCubeTexture ).mul( intensity );
```

**Comment by TobiasNoell** [comment]
But it would be required under WebGL (forgot to mention this 😄)

**Comment by TobiasNoell** [comment]
Also I would like to have the scaling individually per material, and not globally per scene.

**Comment by WestLangley** [comment]
Related: see https://github.com/mrdoob/three.js/issues/24665#issuecomment-1467130545 and the entire discussion that follows.

**Comment by TobiasNoell** [comment]
I already went ahead and tried to create a patch for it (https://github.com/TobiasNoell/three.js/commit/1a034204a009028b3eb5f825bc697a80bc0ee87b). However, it is currently not yet working (the scaling seems to do nothing, I guess the replacing in the shader is not applied). If anybody deeper into Three could give me a hint, I could open a PR for this feature.

**Comment by TobiasNoell** [comment]
It actually seems that there is a bug in `examples\jsm\renderers\webgl-legacy\nodes\WebGLNodeBuilder.js`
At the time the fragment shader is patched, it is not yet "expanded" fully, e.g. it still has `#include <lights_fragment_maps>` instead of the contents of `lights_fragment_maps`. Thus it will not find the `float envMapIntensityFactor = envMapIntensity;` to replace as it is one level "deeper".
I could lift the `envMapIntensityFactor` one level up, to make the replacement work. But it seems many other replacements are currently also not effective (e.g. `specularColorNode`), so I really guess this is a bug here rather @Mugen87?

**Comment by sunag** [comment]
> Related: see https://github.com/mrdoob/three.js/issues/24665#issuecomment-1467130545 and the entire discussion that follows.

Hmm... My doubt would be about the physical aspect, could multiplying the IBL map intensity like `cubeTexture( myCubeTexture ).mul( intensity )` be equivalent to `envMapIntensity`?

**Comment by sunag** [comment]
The new Node system does not allow `material.envNode` in `WebGLRenderer` only `WebGPURenderer`. In case of  `envMapIntensity` this could be done using `this._parseInclude( 'fragment', 'envmap_physical_pars_fragment', ... )`, but this is not a bug because it was not a planned feature. In particular, I don't think it's worth we develop IBL based on Nodes for `WebGLRenderer`, this is very complex and we would have many duplicate functions, `WebGLBackend` over `WebGPURenderer` should be the solution for this.

**Comment by TobiasNoell** [comment]
Ah brilliant, I had not seen that one had to to manually add the includes that need to be expanded to the `_parseInclude`arguments. thanks a lot for the hint 👍
I would still be very happy to open a PR after the testing as we cannot use WebGPU currently as it is not supported by all devices (yet).

**Comment by sunag** [comment]
Thanks for the feedback, in any case this should be done using a multiplier at the end, without needing to add another property, this way we can control the intensity of several IBL if necessary, as in this example:

```js
material.envNode = cubeTexture( myCubeTexture ).mul( intensity );
```
I believe that `envMapIntensityNode` will not be part of it because the expansion is being carried out for `WebGPURenderer` with a fallback for `WebGL`. The above tips would just be a workaround using `WebGLRenderer`.
