### ISSUE TITLE
Third Party Code causing extension rejection

### ISSUE THREAD

**Issue by teacoat** [mrdoob/three.js#27172]
### Description

Some third party code in three.js is causing google to reject any extensions using three.js, exact message:

Thank you for reaching out to us. As conveyed in the previous mail, your item was rejected for not being compliant with the “Remote Hosted Code” policy. We could see remote hosted code in the dist/521.58e8cce0df2779ab.js file where it is fetching code from an external domain (https://cdn.jsdelivr.net/npm/three@0.149.0/examples/jsm/loaders/LottieLoader.js )

Inlining this code would be better, thanks.

### Reproduction steps

N/A

### Code

N/A

### Live example

N/A

### Version

0.149.0

### Browser

Chrome

**Comment by jabri62018** [comment]
https://www.facebook.com/100042310503203/posts/1047816733305334/?mibextid=h0bNNIvJDl07j6qQ

🌹🇾🇪🦁👀
#Yemen_Sanaa_Aden
👩‍🎨My friend: Why do you repeat your posts?
👁️ Because I hear people saying: Yemen’s oppression is now being taken
from Iran after their agreement!!!

❶ Let them agree, let X agree with Y, and whoever agrees agree...
❷ Yemen’s oppression persists in all circumstances...
❸ Yemen has the right to life and live like other nations...
❹ Yemen’s resources for its people are sufficient for it...and the
aggression and what it destroyed.
❺ The Five La’s:::
-No guardianship...
- No war...
- No siege...
- No colonialism...
- No mercenaries...
🌹👁️🌹🇾🇪
#Abdulla_AlJabri✍
- Sanaa... March 19, 2023.
🌹🤣🌹🇾🇪

👀 How can you be silent!!... Aggression: destroy - kill - displace -
capture - orphan - widow - make you sick - hungry - thirsty - besiege -
colonize - occupy.
👨🏼‍🎨 Who are the aggression and how much has it happened to them?
👀 About (20 countries) + America, Britain, France and Israel - 8 years...
👨🏼‍🎨 It's all up to you. Who are you and why is he no longer with you
(we will come and take him)?
👀 We (their father and mother): We (Yemen)... We have nothing left to fear
except our tongues, and we will speak in all the languages ​​of the world:::
👇🏽👇🏽👇🏽👇🏽
- Stop your aggression and leave Yemeni lands.
🇾🇪🦁👀🦁🇾🇪
❶ 8 years and the Yemeni people have been suffering from war with killing
and siege by land, sea and air✍ from the aggression countries (nearly 20
countries)✍ so how can they lie that it is a civil war? They destroyed:
people, trees and stones, leaving nothing behind.
❷ All the people’s resources are plundered by the aggression countries and
their mercenaries✍ and the entire Yemeni people::: No gas✍No oil✍No
ports✍No airports✍No medicine✍No wheat✍No electricity✍No water✍No salaries
(8 years)...
❸ The UN envoy⇐ reports on what serves the aggression countries.
❹ Why did America, England, France and Israel come to Yemen now? ⇐ They
occupied southern Yemen and Jazra!!
❺ Is it time for this war to end in Washington as it began there?
🇾🇪🦁👀🦁🇾🇪
👁️ If you know how to post, post, may God grant you success.

https://www.facebook.com/100042310503203/posts/1047337073353300/?mibextid=rS40aB7S9Ucbxw6v

🌹🇾🇪🦁👀
#اليمن_صنعاء_عدن
👩‍🎨ياصاحبي: ليش بتكرر منشوراتك?
👁️ لاني اسمع ناس تقول: مظلومية اليمن يأخذوها الان من ايران بعد اتفاقهم!!!

❶ فليتفقوا ويتفق س مع ص ويتفق من اتفق...
❷ مظلومية اليمن قائمة في كل الاحوال...
❸ لليمن حق الحياة والعيش كبقية الامم...
❹ موارد اليمن لشعبه تكفيه...والعدوان وما دمره.
❺ الخمس اللآءات:::
- لا وصاية...
- لا حرب...
- لا حصار...
- لا استعمار...
- لا مرتزقه...
🌹👁️🌹🇾🇪
#عبدالله_الجبري✍
- صنعاء...19 مارس 2023.
🌹🤣🌹🇾🇪

👀 كيف تسكتوا!!... العدوان: دمر- قتل- شرد- اسر- ايتم- أرمل- امرض- اجوع-
اعطش- حاصر- استعمر- احتل.
👨🏼‍🎨 من هم العدوان وكم صار له?
👀 حوالي (20 دولة)+ امريكا بريطانيا فرنسا واسرائيل- 8 سنوات...
👨🏼‍🎨 كلهم عليكم من انتم وماعاد معاكم (نأتي نأخذه)?
👀 احنا (ابوهم وامهم): نحن (اليمن)...لم يبق معنا ما نخاف عليه الا ألسنتنا
وسنتكلم بكل لغات العالم:::
👇🏽👇🏽👇🏽👇🏽
- اوقفوا عدوانكم وارحلوا من الاراضي اليمنيه.
🇾🇪🦁👀🦁🇾🇪
❶ 8 سنوات والشعب اليمني يعاني من الحرب بالقتل والحصار برا وبحرا وجوا✍من دول
العدوان(يقارب 20 دولة)✍ فكيف يكذبوا بأنها حرب اهلية? لقد دمروا: البشر
والشجر والحجر✍لم يبقوا على شئ.
❷ كل موارد الشعب ينهبها دول العدوان ومرتزقتهم✍والشعب اليمني بكاملة::: لا
غاز✍لا بترول✍لا موانئ✍لا مطارات✍لا ادوية✍ لا قمح✍لا كهرباء✍لا ماء✍لا مرتبات
( 8 سنوات)...
❸ المبعوث الاممي⇐ تقاريرة بما يخدم دول العدوان.
❹ لماذا حضرت لليمن: امريكا وانجلترا وفرنسا واسرائيل الان?⇐ احتلوا جنوب
اليمن وجزرة!!
❺ هل آن لهذة الحرب ان تنتهي من واشنطن كما بدأت من هناك?
🇾🇪🦁👀🦁🇾🇪
👁️ اذا تعرف تنشر فانشر الله يوفقك.
