### ISSUE TITLE
Click Event in Drag Controls

### ISSUE THREAD

**Issue by psytron** [mrdoob/three.js#27393]
### Description

Drag Controls is amazing and a really important component of enabling interactivity in THREE.JS.  
Right now though there is no way to get a simple TouchDown or Click event.

### Solution

It would be great to utilize all the functionality that is already a part of DragControls and emit a Click / Touch event. 

### Alternatives

Other libraries?  Just figured most of the functionality is already in the lib. Would just be a matter of emitting a separate Click / TouchStart Event.

### Additional context
Right now the only events are: 
dragstart
drag
dragend
hoveron
hoveroff

Accomplishing all of the functionality of "dragstart" and "dragend" already requires the library to know a click has occurred, but it doesn't emit the event.  It would be great to simply emit the "click" as another event here.

**Comment by Mugen87** [comment]
I guess you want to know whether an object controlled by `DragControls` has been clicked or not, right?

A `dragstart` is essentially a click (or more precisely `pointerdown`) since there is no timeout that distincts between a pointer down and drag. If you study the code, you will see `dragstart` is dispatched right when an intersection is detected. That is the moment when the controls start the drag interaction.
