### ISSUE TITLE
GLTFLoader min/max accessor implementation

### ISSUE THREAD

**Issue by eXponenta** [mrdoob/three.js#27415]
### Description

Current loader of GLTFL has misunderstood treating of min/max values and spams to "console.warn" about it.

Follow to documentation: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_accessor_min.

min/max values is important only when accessor is sparsed.

Current GLTFLoader spam when this values not presented at:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L4502

This started from r111:
https://github.com/mrdoob/three.js/blob/r111/examples/jsm/loaders/GLTFLoader.js#L2348

### Reproduction steps

*

### Code

*

### Live example

*

### Version

r111+

**Comment by donmccurdy** [comment]
From the glTF 2.0 specification, [section 3.6.2.5](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#accessors-bounds) —

> Animation input and vertex position attribute accessors MUST have accessor.min and accessor.max defined. For all other accessors, these properties are optional.

The min/max is strictly required by glTF for vertex position attributes. When missing, the file is invalid, as the [glTF Validator](https://github.com/KhronosGroup/glTF-Validator) will report as well. We rely on the min/max in order to create a bounding box for the mesh, without having to slowly iterate over all vertices.

If GLTFLoader is writing warnings for missing min/max vertex position attributes, that is expected — if it's warning for other types of accessors, that might be a bug.
