### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by jvolker** [mrdoob/three.js#27526]
### Description

Any of the examples, for example, https://threejs.org/examples/#webgl_animation_keyframes, is not loading on a [Brightsign](https://www.brightsign.biz/) media player. 

I'm getting `Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".` I'm pretty sure this used to work in the past. It does work on my desktop Mac.

### Reproduction steps

1. open any of the examples on a Brightsign player.
2. open console, see error.
3. the example view on the right part of the website remains empty.

### Code

see example

### Live example

* https://threejs.org/examples/#webgl_animation_keyframes

### Version

r160

**Comment by Mugen87** [comment]
The internal browser does not seem to fully support import maps.

I suggest you file a feature request/bug report at the vendor. We are not going to revert the usage of import maps or add back a polyfill.

**Comment by jvolker** [comment]
Thanks for looking into it. 

Does this mean Threejs is unsupported on those devices, or just an issue with the packaging of the website examples? Thanks.

**Comment by Mugen87** [comment]
> Does this mean Threejs is unsupported on those devices, or just an issue with the packaging of the website examples?

This is just an issue of the examples since they are using import maps without a polyfill. To clarify, we are talking about the following specific code section:

https://github.com/mrdoob/three.js/blob/208f5e48adb750e15c4fb5167f492b414d8bd5bf/examples/webgl_geometry_cube.html#L10-L17

Apps don't have to use import maps though. If you are going to use a build tool and produce an ESM or UMD build file, you are not going to see import maps at all.

**Comment by mrdoob** [comment]
It's also possible to use a polyfill:

https://github.com/guybedford/es-module-shims
