### ISSUE TITLE
Invalidate materials uniforms during render

### ISSUE THREAD

**Issue by Inuniku** [mrdoob/three.js#27555]
### Description

While working on a solution on #27547. It would be nice to be able to change a materials uniforms during render.

#### Use Case

I want to display meshes with the same material, but change the materials properties ( uniforms like color or opacity) with onBeforeRender.

```javascript
const sharedMaterial = new MeshBasicMaterial( { transparent: true, opacity: 0.5 } );
const onBeforeRender1 = ( r, s, c, g, material) => {
    material.opacity = 0.3;
    // material.needsUpdate = true;
    // material.materialUniformsNeedUpdate = true;
}
const onBeforeRender2 = ( r, s, c, g, material) => {
    material.opacity = 0.5;
    // material.needsUpdate = true;
   // material.materialUniformsNeedUpdate = true;
}

const mesh1 = new Mesh(geom, sharedMaterial);
const mesh2 = new Mesh(geom, sharedMaterial);

mesh1.onBeforeRender = onBeforeRender1;
mesh2.onBeforeRender = onBeforeRender2;
``` 
![image](https://github.com/mrdoob/three.js/assets/16117001/1b2bcec2-b306-403e-92b7-0577726e7081)

However the material appears the same. 
There is no way to invalidate the used uniforms. (`needsUpdate` _doesn't_ work.)

### Solution

I would like to propose setting a flag in the material causes a `WebGLMaterials.refreshMaterialUniforms` during render.

`material.materialUniformsNeedUpdate = true;`

I can also provide a pull request with a working solution.

```javascript
	// Check for flag

	if ( refreshMaterial || material.materialUniformsNeedUpdate) { // <<<  NEW

		p_uniforms.setValue( _gl, 'toneMappingExposure', _this.toneMappingExposure );

		...

		materials.refreshMaterialUniforms( m_uniforms, material, _pixelRatio, _height, _transmissionRenderTarget );

		WebGLUniforms.upload( _gl, getUniformList( materialProperties ), m_uniforms, textures );

		material.materialUniformsNeedUpdate = false; // <<< NEW

	}
``` 

### Alternatives

Rework `material.needsUpdate` to work with this use case.

```javascript

    let refreshMaterial = false;

    if ( needsProgramChange === true ) {    // triggered by needsUpdate

        program = getProgram( material, scene, object );
        refreshMaterial  = true;
    }

    let refreshProgram = false;
//  let refreshMaterial = false;
    let refreshLights = false;

```

**Comment by Mugen87** [comment]
Um, there is already `ShaderMaterial.uniformsNeedUpdate`. I wonder if we could move the property to `Material` instead and evaluate it in `setProgram()`.

However, `WebGPURenderer` and the new node material offer a different solution for per-instance uniforms (see https://github.com/mrdoob/three.js/pull/27546#issuecomment-1890408603). Meaning we would add a property to our generic material class that has no usage in context of `WebGPURenderer`.

Notice that `ShaderMaterial` and `RawShaderMaterial` won't be supported by `WebGPURenderer` so these two material classes are an exception.

**Comment by Inuniku** [comment]
> Meaning we would add a property to our generic material class that has no usage in context of WebGPURenderer.

Would the proposed alternative then be acceptable? Changing the behaviour of `needsUpdate `wouldn't change the Api. I think it will only introduce a negligible overhead, since using `needsUpdate` most likely also causes the uniforms to refresh in almost all cases.

**Comment by Mugen87** [comment]
I need a closer look at this proposal. TBH, changing the semantics of `Material.needsUpdate` could have side effects for all users setting this property to `true`. So even if the change looks small on first sight, the performance consequences could be severe.

**Comment by Mugen87** [comment]
After a closer look and some testing I do not vote for changing the semantics of `needsUpdate`. I also do not recommend to change material properties in `onBeforeRender()` because you end up with unexpected side effects.

Granted, there isn't a performance difference when `refreshMaterial` is set to `true` during the version change since when `needsUpdate` is properly used, a uniforms update happens in any case. However, the usage of `onBeforeRender()` like demonstrated is error prone since you eventually have to add such a handler for all 3D objects using the same material to ensure the correct opacity value. Keep in mind that you have no control on how 3D objects are rendered unless you define a manual render order. That means you never know which objects are rendered first and how the material instance is configured. Since you might render objects with the wrong material setup, you need to add an `onBeforeRender()` callback for all objects and end up with a call of `needsUpdate` per object which is not good. If you use separate materials and share them along your objects, you end up with less state changes. 

Fortunately, the per-instance uniform feature in `WebGPURenderer` will implement this more flexible than what `WebGLRenderer` offers today. So once you migrate to `WebGPURenderer` in the future, this issue should go away automatically.
