### ISSUE TITLE
SSAARenderPass(TAA) make PerspectiveCamera aspect  invalid

### ISSUE THREAD

**Issue by ronancheng** [mrdoob/three.js#27571]
### Description

SSAARenderPass(TAA) make PerspectiveCamera aspect  invalid

### Reproduction steps

1.add PerspectiveCamera
2.add SSAA or TAA
3.update camera aspect

the aspect invalid, is default 1

### Code

```js
// camera
this.camera = new THREE.PerspectiveCamera(45, 0.8, 0.1, 3000);


// SSAA
const ssaaRenderPass = new SSAARenderPass(this.scene, this.camera!);
    composer.addPass(ssaaRenderPass);
    ssaaRenderPass.sampleLevel = 5;
```

### Live example

..

### Screenshots

when I set camera(aspect 0.8) without SSAA in scene, 
![Y7SLGZQQYK6@REG)XXTYO%P](https://github.com/mrdoob/three.js/assets/37335950/c8fa2e00-1883-4943-9dd5-40bfb0caaa0e)

when I add SSAA(TAA):
![4ZX O965ROK1LXSN82 JQ5M](https://github.com/mrdoob/three.js/assets/37335950/bcc00c30-05f1-4a6b-9c0a-979f89026deb)

### Version

^0.156.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Do you mind demonstrating with a live example what you are doing? Please use the following templates:

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

Instead of creating a new demo from scratch, you can also copy over the code from [webgl_postprocessing_ssaa](https://threejs.org/examples/webgl_postprocessing_ssaa) and then update it to show the issue.

**Comment by ronancheng** [comment]
@Mugen87

**Comment by ronancheng** [comment]
@Mugen87 
example: sfiddle.net/fdv4m1pe/34/
when you change the camera aspect with the ssaa disabled, you can see the view change
when you change the camera aspect with the ssaa enabled, you can't see the view change

**Comment by Mugen87** [comment]
Thanks for the live example.

You can't update the `aspect` value since it is overwritten of `setViewOffset()` which is used in `SSAARenderPass`. The aspect has to match the width and height of your canvas.
