### ISSUE TITLE
Transmission rendering doesn't respect viewport

### ISSUE THREAD

**Issue by toi333** [mrdoob/three.js#27592]
### Description

There seems to be a problem with viewports in `WebGLRenderer.renderTransmissionPass`.
This can be reproed by loading a gltf model that uses the transmission effect and rendering into a render target texture while having a custom viewport set in the renderer.
I've set up a live example on jsfiddle that loads `IridescentDishWithOlives.glb` and renders into a quarter of the render target and then copies the entire render target texture into canvas. This unexpectedly results with the entire canvas containing the full image, instead of only a quarter.
On the other hand, if you swap the model with a simple duck by changing the line `const model = 0 ? modelDuck : modelOlives;`, you should get the expected behaviour, only quarter of the canvas containing the image.

### Reproduction steps

See https://jsfiddle.net/z8uLgmn1/2/

### Code

```js
// see jsfiddle example
```

### Live example

https://jsfiddle.net/z8uLgmn1/2/

### Version

160

**Comment by Mugen87** [comment]
The viewport can be configured at two places. Via `WebGLRenderer.setViewport()` and via `RenderTarget.viewport`. Whenever you render to a render target with a custom viewport, you need to configure the render target. In other words, `RenderTarget.viewport` overwrites the renderer setting so the fiddle should ideally look like so:

https://jsfiddle.net/6fsv35cL/

That's because `renderTransmissionPass()` sets the transmission render target, renders transmissive objects and then restores the original render target. This overwrites the viewport configuration on app level via `setViewport()`.
