### ISSUE TITLE
Provide an iterative version of Object3D.traverse()

### ISSUE THREAD

**Issue by gewesp** [mrdoob/three.js#27639]
### Description

In our tests with Chrome 120.0.6099.234 (Official Build) (arm64), it appears that traverse() is ca. 15% faster when implemented iteratively.

Since this is a pretty common operation, it may make sense to specifically optimise it even though the code is slightly less nice.

We tested with a no-op callback on a scene containing a few 10k of objects.  It traverses ca. 6M objects per second on a Mac M1.

We didn't do performance testing with other browsers.

### Solution

Happy to share our iterative version in TypeScript:
```
const STACK: Object3D[] = [];

function pushToStack(obj: Object3D): void {
  STACK.push(obj);
}

function pushToStackIfVisible(obj: Object3D): void {
  if (obj.visible) {
    STACK.push(obj);
  }
}

/**
 * If visibleOnly is false: Applies callback to obj and all its descendants.
 * If visibleOnly is true: Applies callback to obj and all its descendants provided
 *                         they are visible.
 *
 * Measurements with an empty callback suggest that this function is about 15% faster
 * than the three.js recursive implementation.
 */
export function traverseIteratively(
  obj: Object3D,
  visibleOnly: boolean,
  callback: (obj: Object3D) => void
) {
  const push = visibleOnly ? pushToStackIfVisible : pushToStack;

  if (STACK.length !== 0) {
    // This can only happen if a callback throws an exception.
    console.error("traverseIteratively(): Stack not found empty");
  }
  STACK.length = 0;
  push(obj);

  while (STACK.length > 0) {
    // length > 0, therefore we have an object
    const node = STACK.pop() as Object3D;
    callback(node);
    node.children.forEach(push);
  }
}
```

### Alternatives

Find out why the recursive solution is slow-(ish).  This would rather be a topic for JS engine developers though.

**Comment by gkjohnson** [comment]
> ```js
>  if (STACK.length !== 0) {
>    // This can only happen if a callback throws an exception.
>    console.error("traverseIteratively(): Stack not found empty");
>  }
> ```

This will also happen if "traverse" is called recursively.

**Comment by Mugen87** [comment]
It seems confusing to add a separate version of `Object3D.traverse()` just with a different performance. If anything `Object3D.traverse()` should be updated.

> We didn't do performance testing with other browsers.

That is an issue since browsers have different runtime behaviors so at least Chromium, Safari and Firefox should be tested.

> Since this is a pretty common operation, it may make sense to specifically optimise it even though the code is slightly less nice.

`Object3D.traverse()` is normally no method you call per frame. So I would not say that performance is the most critical factor of an implementation. Simplicity, readability and the resulting advantages in context of maintainability have a high priority in this project. Looking at the suggested solution and the reported performance gains, I don't think the addition is worth it, tbh.
