### ISSUE TITLE
Please add three.js/three.min.js back

### ISSUE THREAD

**Issue by wesleyted00** [mrdoob/three.js#27763]
### Description

From r161, the build files build/three.js and build/three.min.js have been removed. We have to use ES Modules or alternatives. Some projects here do not support ES modules or Common JS modules yet.  Also,  some projects are running on NW.js, which makes it difficult to change all code to support modules.

### Solution

Please keep the three.js and three.min.js so we have the option to use the plain Three.js WITHOUT modules.

### Alternatives

The alternative solution is that we have to use r160 version.

### Additional context

Nowadays, many web applications run on Desktop environments, such as NW.js, Electron, etc. A plain Three.js and Three.min.js are very useful and flexible.

**Comment by Mugen87** [comment]
Sorry, but we won't add these builds back. 

You can configure a minified UMD build by yourself if you need one.

**Comment by nureyev** [comment]
@wesleyted00 For NW.js projects, add   
`"type": "module"
`
to the Node.JS package.json in your projects. You can either have a combined package.json or two separate package.json (one for Node.JS, the other for NW.js).

There should be no other actual changes needed if I recall offhand since the browser context will use ESM and the Node.JS context will still need modules to be imported using 'require' syntax.

To clarify, in browser context use 'import', in Node context use 'require'. If you were using 'require' everywhere this would have likely led to issues anyway since that was using NW.js mixed-mode context.

Importing three.js using import maps also works correctly in NW.js.
