### ISSUE TITLE
Show warning for undisposed geometries/materials using `FinalizationRegistry`?

### ISSUE THREAD

**Issue by josephrocca** [mrdoob/three.js#27882]
### Description

I'm wondering whether it's possible to make Three.js more user-friendly to newbies by using a [`FinalizationRegistry`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) callback to trigger a warning if a geometry/material/etc. was never disposed?

I guess there are two relevant sub-questions here:
1. If a geometry/material handle on the CPU side is garbage collected, does that mean that it is always appropriate to dispose?
2. Is `FinalizationRegistry` likely to present any problems (e.g. performance, memory usage, etc.) in real-world code?

### Solution

My guess at some pseudo-code:
```js
// Global instance of `FinalizationRegistry` (across whole THREE codebase)
const finalizationRegistry = new FinalizationRegistry(ref => {
  if(!ref.disposed) console.warn("Undisposed geometry/material [...]");
});

// For each thing that should be disposed:
class BufferGeometry extends EventDispatcher {
  constructor() {
    super();
    this._ref = {};
    finalizationRegistry.register(this, null, this._ref); // registry only holds weak reference to _ref object
    // ...
  }
  dispose() {
    this._ref.disposed = true;
    // ...
  }
}
```

### Alternatives

N/A

### Additional context

I think this is one of the "sharpest edges" for newbies in Three.js - at least from my perspective/experience. It's easy to accidentally forget to dispose things in random edge cases, since manual memory management is almost never required in other JS code. It'd be *really* cool if this were less of an issue due to some warnings (or even automated disposal if that were possible, but seems too good to be true).

I'm guessing that all of this is not possible, since it seems like a no-brainer, so please feel free to close this if there's not much to discuss here, of course. Figured I'd post just in case.

Thanks!

**Comment by Mugen87** [comment]
TBH, I don't think this change is necessary. The callback of `FinalizationRegistry` is triggered when the object is garbage collected. That can only happen if the engine and the app related code don't have any reference pointing to it anymore. 

Let's assume this is true and the object gets garbage-collected. When that happens, the respective WebGL resources are automatically freed by the runtime environment. Even without further actions of the engine.

Of course the explicit `dispose()` at the point in time when the app knows resources aren't required anymore is better. But the real issue is if object are not garbage collected at all (memory leak). `FinalizationRegistry` is not a help in this context.

**Comment by josephrocca** [comment]
>  When that happens, the respective WebGL resources are automatically freed by the runtime environment. Even without further actions of the engine. [...] But the real issue is if objects are unintentionally not garbage collected at all (memory leak). FinalizationRegistry is not a help in this context.

Oh, I might be misunderstanding how the internals work here. I thought that `geometry` and `material` must *always* be explicitly `.dispose()`ed by the app developer - i.e. they are never automatically garbage collected, even if the mesh itself was garbage collected. My assumption was that this had something to do with WebGL and JS not "sharing" underlying GC infrastructure, or something - a bit like how emscripten ports sometimes require manual memory management.

**Comment by Mugen87** [comment]
> Let's assume this is true and the object gets garbage-collected. When that happens, the respective WebGL resources are automatically freed by the runtime environment. Even without further actions of the engine.

Maybe this statement was too unspecific^^. 

Of course there are instances where calling `dispose()` is required otherwise a memory leak could occur. That's because the engine internally holds references to specific objects that are only removed if `dispose()` is called on app level. We've tried to use `WeakMap` for internal data structures whenever possible however their use is limited because you can't iterate over them. IMO, it would be confusing to explain users where calling `dispose()` is absolutely required and where not so the rule of thumb is use it on your app if available and when resources are not required anymore.

That said, `FinalizationRegistry` isn't a help here in any event so the issue can be still closed.

**Comment by josephrocca** [comment]
> `FinalizationRegistry` isn't a help here in any event

I was hoping for an explanation here :) You comment explained that all my assumptions were correct, but didn't address the central question ^^'

**Comment by Mugen87** [comment]
Sorry, but I don't understand how the issue isn't already clear yet^^.

**Comment by mrdoob** [comment]
> Your comment explained that all my original assumptions were correct, but didn't address the central question ^^'

What's the central question?

**Comment by josephrocca** [comment]
Basically "Is FinalizationRegistry useful here?"

I was hoping for more than "FinalizationRegistry isn't a help here" - but maybe I just don't understand, or maybe the answer is obvious/implied and so went over my head here.

This was my guess at why the answer would be "No":

> My assumption was that this had something to do with WebGL and JS not "sharing" underlying GC infrastructure, or something - a bit like how emscripten ports sometimes require manual memory management.

I.e. I was hoping for an explanation of why it is simply not possible to GC underlying resources based on GC'd references to those resources.

**Comment by mrdoob** [comment]
It's not something we can investigate at the moment.

But you're welcome to try implementing it, measure the impact and if you think it's worth it then you can create a PR including your findings.

**Comment by josephrocca** [comment]
Oh okay that's a different answer! (Or maybe Mugen87 knows something you don't). Anyway, thank you for your responses. I dream that one day other newbies will not have to go through this:

![image](https://github.com/mrdoob/three.js/assets/1167575/65846373-9b8e-41b4-a346-98b8e79b5776)
