### ISSUE TITLE
Wrong rotations when exporting a scene with Blender 2.64 exporter

### ISSUE THREAD

**Issue by eXacto** [mrdoob/three.js#2803]
the blender scene with rotated monkeys:

![blender scene](https://f.cloud.github.com/assets/3037862/12635/443a83de-45aa-11e2-8e6e-4249dfd23d4d.png)

export settings:

![export settings](https://f.cloud.github.com/assets/3037862/12638/8d5222c0-45aa-11e2-96f1-6ba912776760.png)

the converted scene displayed withexample page:
three.js-master/examples/webgl_loader_scene_blender.html

![Uploading exported json scene.png . . .]()

**Comment by user1095108** [comment]
No guys, you've had it all wrong. From what I've seen blender uses some time-tested "holy" code from Ken Shoemake for conversions to eulers. The code hails from the times when row vectors were still used, in other words, for XYZ eulers, people transformed a vector like this:
[x', y', z'] = [x, y, z] Rx^T(ax) Ry^T(ay) Rz^T(az)
in modern days, when column vectors are used, we do:
[x', y', z']^T = Rz^T(az) Ry^T(ay) Rx^T(ax) [x, y, z]^T
in order to convert R^T to R, we need to use negative angles, so finally we have
[x', y', z']^T = Rz(-az) Ry(-ay) Rx(-ax) [x, y, z]^T
The confusion is just a consequence of changing times, different conventions. For the other eulers, just adapt the provided recipe.

**Comment by mrdoob** [comment]
Good to know. A little too late though. We now rely on gltf.
