### ISSUE TITLE
GLTFExporter duplicates mesh vertices (from 6k to 2millions)

### ISSUE THREAD

**Issue by aymen157** [mrdoob/three.js#28133]
### Description

Here is the fulll description. at first i thought it was a blender bug. but it seems to be a three js
https://projects.blender.org/blender/blender/issues/120621

both the input and the output models are there.

### Reproduction steps

Convert from FBX to GLTF using THREE.GLTFExporter
(the example project is in the zip file, just drop an fbx and do ctrl+enter, you will see the verts exported are duplicated/high count)

### Code

```js
```

### Live example

[FbxToGLTF_threejs.zip](https://github.com/mrdoob/three.js/files/14970026/FbxToGLTF_threejs.zip)

### Screenshots

Screenshots can be seen in the blender issue.

### Version

140

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by mjurczyk** [comment]
Importers create non-indexed geometries, you can "re-index" them with [BufferGeometryUtils.mergeVertices](https://threejs.org/docs/index.html?q=bufferge#examples/en/utils/BufferGeometryUtils.mergeVertices).

**Comment by aymen157** [comment]
Yes that solves it. Weird though how GLTFExporter doesn't do that automatically?

**Comment by donmccurdy** [comment]
The “usual” answer to this question is that DCC tools like Blender represent vertex data differently than 3D engines. With or without an index — many loaders do create indexed geometry — that difference remains. See [_Vertex Count Higher in Engine Than in 3D Software_](https://shahriyarshahrabi.medium.com/vertex-count-higher-in-engine-than-in-3d-software-badc348ada66) for more on that.

However ... I think there's something else unexpected going on here. The file contains a lot of vertex arrays that are reused by multiple mesh primitives, so I think perhaps GLTFLoader is failing to reuse vertex arrays correctly. If I export from the latest three.js editor, the vertex count is much just 33K, matching what is loaded into three.js, and within the expected range given the differences mentioned above. So this appears to have been fixed since r140. Possibly by https://github.com/mrdoob/three.js/pull/27268.
