### ISSUE TITLE
WebGLProgram leaking (instances increasing)

### ISSUE THREAD

**Issue by A2H2** [mrdoob/three.js#28355]
### Description

WebGLPrograms are not correctly being disposed. I noticed this in my own project, but I can reproduce issue on official https://threejs.org/examples/#webgl_test_memory.
After each cycle of scene recreation (new mesh added / removed / disposed), there is extra +1 new WebGLProgram.

Number of instances seems to be capped at ~131 for my computer which is very strange.
Also then it seems like all above 131 will get deleted correctly which is even more weird.

Only way to correctly get rid of these additional instances is to recreate canvas which I know from my own project. (destroy and create new canvas). As an alternative it is possible to reuse the same instance of material to avoid this extra WebGLPrograms.

WebGLRenderer.info seems to show 1x Program, so either info or memory profiler is wrong.

### Reproduction steps

1. go to https://threejs.org/examples/#webgl_test_memory
2. (optional) Modify script so it only updates slower (for example once per sec)
I changed animate script to following:
function animate() {
   setTimeout( animate, 1000 );
   render();
}
3. Open Chrome Memory tab in developers console. Select first option - Heap snapshot
4. Do several snapshots as time progress and filter WebGLProgram
5. Notice that intances are increasing up to (also in compare mode you see those instances are not deleted)

### Code

One present at https://threejs.org/examples/#webgl_test_memory

### Live example

https://threejs.org/examples/#webgl_test_memory

### Screenshots

Live (unmodified) webgl_test_memory screenshot 1
![image](https://github.com/mrdoob/three.js/assets/126272684/985d080a-5397-4123-bb08-28e9a0679afa)

Live (unmodified) webgl_test_memory screenshot 2
![image](https://github.com/mrdoob/three.js/assets/126272684/61e35840-4ee0-4e63-a549-b8c507e09cb2)

Modified webgl_test_memory 1
![image](https://github.com/mrdoob/three.js/assets/126272684/5ae748e8-0f1b-4cb5-8ac5-3602cc64b3f5)

Modified webgl_test_memory 2
![image](https://github.com/mrdoob/three.js/assets/126272684/7a9f777f-59b2-4f88-b78f-a6021517dfd2)

### Version

i can reproduce on 159 and 164

### Device

Desktop

### Browser

Chrome version 124.0.6367.158 (Official Build) (64-bit)

### OS

Windows

**Comment by Mugen87** [comment]
This is unrelated. Render states have no references to programs.

**Comment by Mugen87** [comment]
> I also found some "similar" issue from that past. I am not sure if its related or not yet.
https://github.com/mrdoob/three.js/pull/19645

It is not related, imo. Render states have no references to programs.

**Comment by Mugen87** [comment]
I've checked the relevant code base again I don't think the root cause is on our side. Especially the behavior you have described here makes me think this is a browser related issue:

> Number of instances seems to be capped at ~131 for my computer which is very strange.
Also then it seems like all above 131 will get deleted correctly which is even more weird.

To me, this does not look like a memory leak. I suspect what we see is some sort of cashing mechanism of the browser to retain programs for a potential later use. Even if an app does not use a program for rendering anymore, it might be use it at a later point. Next to optimizations on engine levels, WebGL implementations apply optimizations as well to avoid unnecessary overhead. If the browser caching is implemented correctly, is a different question.

But to be honest, if there is no ongoing growing memory allocation that eventually slows down the app or crashes the tab, I would not worry about 131 instances of `WebGLProgram` retained somewhere in memory. If you insist to report it, do it here: https://issues.chromium.org/issues.

**Comment by A2H2** [comment]
I kind of agree with your conclusion. If I find some reason or evidence I will report it.
Also thanks for the link to chromium I will try to ask for advice / confirmation there.
