### ISSUE TITLE
SkeletonHelper is always in front.

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#28399]
### Description

https://github.com/mrdoob/three.js/assets/1063018/9b4e1fbf-703c-469c-8528-1e9b922012e2

The pointlighthelper and directionallighthelper aren't always in-front, while bounding box helper and armature helper are always in-front, I expected that the behavior should be consistent, but actually dont

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r164

**Comment by Mugen87** [comment]
Actually the result is as expected.

- The selection box should always be visible so it's easier to estimate the bounds of selected object. Depth testing is disabled for the selection helper on purpose in `Viewport.js`.
- The `SkeletonHelper` disables depth testing by default because the visualized skeleton is normally inside character models. If you would enable depth testing, you would simply never see the helper.

As you can see, it does not make sense to handle visibility in context of helpers uniformly. For some helpers like `PointLightHelper` or `DirectionalLightHelper` which visualize objects with no volume in 3D space, using depth testing is correct. For others it is not.

**Comment by ycw** [comment]
> you would simply never see the helper.

To clarify, I expect that the armature should be shown infront of the humanoid, but should not be always infront of anything, because there is no options toggle helper per object, so this is problematic when there're multiple armatures on scene: 

https://github.com/mrdoob/three.js/assets/1063018/3b214eef-ef88-48c8-bed3-31fc4b312d2b

**Comment by Mugen87** [comment]
This is not an editor specific issue. It happens in normal scenes as well: https://jsfiddle.net/9fowp5L2/

This is a side effect of how skeleton helper is implemented.

**Comment by Mugen87** [comment]
@ycw If you can't suggest a different approach for rendering the helper, I would suggest to close this issue and mark it as `Won't fix`.

**Comment by ycw** [comment]
> This is a side effect of how skeleton helper is implemented.

Ahh, I forgot to link #28421 to this issue 🙏🏻 ... that PR doesn't change the `SkeletonHelper` implement ... and it solved the root problem: "this is problematic when there're multiple armatures on scene", so this issue can be closed, sorry for that 🙏🏻
