### ISSUE TITLE
Documentation: `InstancedMesh` constructor docs omit array of `Material` possibility

### ISSUE THREAD

**Issue by finnbear** [mrdoob/three.js#28414]
### Description

The `InstancedMesh` constructor docs say:
> [material](https://threejs.org/docs/index.html#api/en/materials/Material) - an instance of [Material](https://threejs.org/docs/index.html#api/en/materials/Material). Default is a new [MeshBasicMaterial](https://threejs.org/docs/index.html#api/en/materials/MeshBasicMaterial).

But `InstancedMesh` also supports an array of materials, like `Mesh`.

### Reproduction steps

https://threejs.org/docs/#api/en/objects/InstancedMesh

### Code

```js
import * as THREE from 'three';

const camera = new THREE.PerspectiveCamera( 70, window.innerWidth / window.innerHeight, 0.01, 10 );
camera.position.z = 1;

const scene = new THREE.Scene();

const geometry = new THREE.BoxGeometry( 0.2, 0.2, 0.2 );
const material1 = new THREE.MeshBasicMaterial({color: 0xff0000});
const material2 = new THREE.MeshBasicMaterial({color: 0x0000ff});
geometry.addGroup(0, geometry.index.count / 2, 0);
geometry.addGroup(geometry.index.count / 2, geometry.index.count, 1);

const mesh = new THREE.InstancedMesh( geometry, [material1, material2], 1 );
mesh.setMatrixAt(0, new THREE.Matrix4());
scene.add( mesh );

const renderer = new THREE.WebGLRenderer( { antialias: true } );
renderer.setSize( window.innerWidth, window.innerHeight );
renderer.setAnimationLoop( animation );
document.body.appendChild( renderer.domElement );

function animation( time ) {
  mesh.rotation.x = time / 2000;
  mesh.rotation.y = time / 1000;

  renderer.render( scene, camera );
}
```
-> https://playcode.io/three

### Live example

Paste into https://playcode.io/three

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/20015102/b5f551d0-4a7d-4a25-abb0-40dd4934cbee)

### Version

r164 (latest)

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment]
I guess it wasn't documented because using multiple materials contradicts the idea of reducing draw calls. But technically, yes, it is possible to use multiple groups.

Regarding your code example: I was a bit confused that your code produced four render calls although your create only two groups. Be aware that `BoxGeometry` already generates own groups so you can assign a material per box side. Using `geometry.clearGroups()` right after the creation produced the expected result (2 draw calls).

https://jsfiddle.net/aw1gxbhz/1/
