### ISSUE TITLE
VolumeNodeMaterial only renders 1x1x1 

### ISSUE THREAD

**Issue by ulyssesdotcodes** [mrdoob/three.js#28579]
### Description

I'd expect VolumeNodeMaterial to render at the size of the box it's contained in, but it only renders at 1x1x1 size.

It looks like the hit test needs to adapt to the bounds of the object or use a material property? https://github.com/mrdoob/three.js/blob/7cb5fe43fa879d4fdc3e2de11873a534ec479606/examples/jsm/nodes/materials/VolumeNodeMaterial.js#L32

If that's all that's needed, I'm happy to do the work and raise a PR.

### Reproduction steps

1. Create a Mesh with a large BoxGeometry and VolumeNodeMaterial
2. Add in the appropriate material properties from the example

Expected:
3. The volume is rendered at the size of the box

Actual
3. The volume is rendered at 1x1x1

### Code

Adapt https://github.com/mrdoob/three.js/blob/master/examples/webgpu_volume_cloud.html

### Live example

https://codepen.io/ulyssesdot/pen/gOJxOwZ

### Version

r165

**Comment by aardgoose** [comment]
As an alternative to altering the material, is scaling the mesh object a solution for you? ie mesh.scale.set( sx, sy, sz);  That is a more efficient solution to modifying the shader.

**Comment by RenaudRohlinger** [comment]
That's the default behavior for Raymarching usually.

`mesh.scale.setScalar(2)` would fix your issue.

If one day we take the time to make a documentation (which I don't think will ever happen since AI fed with the codebase is just a lot better) we can specify that the geometry used is a 1x1x1 by default and the surface can be increased using the matrice.

I'd close this as it's technically not an issue and can be fixed by manipulating the transform matrice of the mesh.
