### ISSUE TITLE
Why functions like Box3.getSize() need a vector3 parameter ? 

### ISSUE THREAD

**Issue by getzelus** [mrdoob/three.js#28668]
### Description

Hello, 

This function calculates the size of a Box3 and return a vector3.
Why it needs a vector3 as parameter and change it ? 
It wouldnt be faster to wait nothing and just return a vector3 ?
There is the same logic for some other functions.

Here is the code of the function :

```
getSize( target ) {

		return this.isEmpty() ? target.set( 0, 0, 0 ) : target.subVectors( this.max, this.min );

}
```
in github file :
https://github.com/mrdoob/three.js/blob/dev/src/math/Box3.js

and in the doc : 
https://threejs.org/docs/?q=box3#api/en/math/Box3.getSize

Thanks for your attention

### Solution

```
getSize() {
       const size = new Vector3( 0, 0, 0 )
	this.isEmpty() ? return size : return size.subVectors( this.max, this.min );
}
```

### Alternatives

Or keep the function like that. 

### Additional context

Maybe i'm missing something.
And if we change that, we need to change all the functions with the same logic like Box3.getCenter() etc...

**Comment by richfwebb** [comment]
It's intentional that the functions avoid creating an object every time the function is called. Creating an object has a cost associated -- when that object goes out of scope, it must be garbage collected. Garbage collection is something you want to minimize. Instead pass in a parameter that you can re-use for many future calls, without creating any new objects.

**Comment by getzelus** [comment]
Hm ok I was not aware of that, thanks for your answer.
