### ISSUE TITLE
WebGPURenderer: AttributeNode: Vertex attribute "normal" not found on geometry

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#28939]
### Description

Cleaning up the examples a bit...

The following examples display the warning:

    AttributeNode: Vertex attribute "normal" not found on geometry.

Due to use of QuadMesh

	- webgpu_rtt.html
	- webgpu_multisampled_renderbuffers.html
	- webgpu_multiple_rendertargets_readback.html
	- webgpu_depth_texture.html

Due to Horse.glb

	- webgpu_instancing_morph.html

Due to RectAreaLightHelper

	- webgpu_lights_rectarealight.html

Perhaps the warning can be suppressed?

### Reproduction steps

see example list above

### Code

n/a

### Live example

see example list above

### Version

r167 dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Spiri0** [comment]
I know that when I create buffer geometries myself and don't create an attribute for "normal" because I create normal vectors myself in the shader. 
Since this is just a warning that never affected my app, I didn't see it as critical.

So the reason for this warning is that the corresponding geometry does not contain a “normal” attribute. 

I then simply solved this by creating a “normal” attribute for my custom geometries. However, not because it was necessary but in order not to confuse other users who download my repository because of the warning in the console.

A clean solution would be to check whether the attribute "normal" is present in the geometry. If not, it should not be used.

**Comment by WestLangley** [comment]
> AttributeNode: Vertex attribute "normal" not found on geometry.

Why is the renderer expecting a normal to be present?

**Comment by Mugen87** [comment]
There is an open issue with `MeshBasicNodeMaterial` which is responsible for most of the warnings.

`NodeMaterial.normals` controls whether the material process geometry normals or not. _Ideally_ it is set to `false` for `MeshBasicNodeMaterial` however this breaks cube map sampling. The current workaround is to not change `normals` to `false` but overwrite the `transformedNormalView` node instead, see #28839. However, this requires to always has normals present in the geometry which is of course not correct.

The one I'm not sure about is `webgpu_instancing_morph`. It uses `MeshStandardNodeMaterial` with flat shading and that should actually overwrite `transformedNormalView` and thus ignoring geometry data. It looks wrong when the material still complains about missing geometry data.
