### ISSUE TITLE
Mesh Bash Flickering on iOS ( webgpu enabled )

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#28978]
### Description

I just tested WebGPU examples on Safari iOS / iphone 12pro max and most of them worked excepted : 

https://threejs.org/examples/?q=batch#webgpu_mesh_batch

The batch keep flickering on webgpu , no problem on webgl backend.

### Reproduction steps

1. enabled webgpu on safari iOS
2. go on https://threejs.org/examples/?q=batch#webgpu_mesh_batch

### Code

X

### Live example

X

### Screenshots

X

### Version

r167

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by Mugen87** [comment]
I actually have a black screen with this example on macOS with Safari + enabled WebGPU. The root cause seems to be `stats-gl`. Can you reproduce the issue with this updated version of `webgpu_mesh_batch`?

https://rawcdn.githack.com/Mugen87/three.js/b80ba5c55b65c3d7a68479932bcceade1fd5482b/examples/webgpu_mesh_batch.html

**Comment by Makio64** [comment]
The new link you provide fix the bug.

Ps : I also had "webgl timer queries" to on which might avoid me the black screen.
