### ISSUE TITLE
Set An Object3D Global Matrix Manually

### ISSUE THREAD

**Issue by ehammons11** [mrdoob/three.js#29051]
### Description

Currently my understanding is that you cannot set the global matrix of an object. The matrix is read from the position, rotation, and scale. You can apply a matrix transform, but you cannot set the global matrix manually. 

### Solution

I would like the ability to set the matrix manually. AKA, switch the matrix from the driven property of the object to the driving property, perhaps through a flag. This would be advantageous for users who are not working with position and rotation directly but just with matrix operations. 

### Alternatives

Another approach would be to allow manual setting of the matrix whenever the `matrixAutoUpdate` flag is false. 

### Additional context

This would be awesome for developers who want their code to match closely with matrix transformation math prominent in certain industries like robotics.

**Comment by Mugen87** [comment]
> I would like the ability to set the matrix manually. 

In this case, set `Object3D.matrixAutoUpdate` to `false` and then directly assign values to `Object3D.matrix`.

When `Object3D.matrixAutoUpdate` is `false`, the position, rotation, and scale properties are ignored since the local matrix is not computed automatically via `updateMatrix()`.

Please use the [forum](https://discourse.threejs.org/) if you need more help regarding matrices and object transformations.
