### ISSUE TITLE
Alias-like artefacts in WebGL2 fallback in r168

### ISSUE THREAD

**Issue by boytchev** [mrdoob/three.js#29272]
### Description

In some very specific cases there is a significant difference in rendering between r167 and r168. Some alias-like (or pixelation) artefacts appear along the edge of objects.

The following four things make the difference show up:

- WebGL2 fallback (i.e. three.webgpu.js is used)
- high shininess (zero roughness, full metalness)
- high border curvature (object is flattened) 
- high contrast (light object, dark background, strong light)

I am not sure how to classify this issue: bug, side-effect or expected-behaviour.

When the contrast is not high (e.g. the light is weak), it is easier to see that r168 makes better shading of the interior areas, but the edges still appear pixelated.

The difference has been spotted while converting some r167 programs into r168. So far I have not found a solution, besides downgrading to r167.

### Reproduction steps

1. Open the live example in a non-WebGPU browser
2. Change the release number in line 5 - compare 168 against 167
3. optional step: compare r168/r167 when intensity is 1, not 10 (change in line 17)

### Code

```js
import * as THREE from "https://unpkg.com/three@0.168.0/build/three.webgpu.js";
:
var renderer = new THREE.WebGPURenderer( {antialias: true} );
: 
var light = new THREE.DirectionalLight( 'white', 10 );
:
var object = new THREE.Mesh(
   new THREE.TorusGeometry( 1, 0.4 ),
   new THREE.MeshPhysicalNodeMaterial( {
      roughness: 0,
      metalness: 1,
   } )
);	
object.scale.z = 0.05;
```

### Live example

[https://codepen.io/boytchev/pen/zYVJrPG?editors=0010](https://codepen.io/boytchev/pen/zYVJrPG?editors=0010)

### Screenshots

![image](https://github.com/user-attachments/assets/fd02e7ff-55f2-4dad-90bb-9f45722576ca)

### Version

r168

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by sunag** [comment]
I think is releated with this change in `getGeometryRoughness()` https://github.com/mrdoob/three.js/pull/29137/files#diff-e9be66566db37c59209d7243c1bb87b62a4d88d8ca3043307ce35f05f52581ff. 

When I analyze the WebGLRenderer code I noticed that it use `normal view` instead of `normal local`, I think that this fix open other issue related with Physical Lighing Model, I will analyze it.

**Comment by boytchev** [comment]
This issue is somewhat with lower priority, as it is very specific and very few users might experience it. Considering the WebGL2 backend as something temporary that is supposed to retire at some point, I'm not sure how much efforts are worth spending on this issue.

**Comment by sunag** [comment]
Hmm... This issue should affect both backends.

**Comment by sunag** [comment]
In `r167` we had a problem with roughness precision due to `getGeometryRoughness()`, this was fixed in `r168`, the expected result should be the current one, seen in WebGLRenderer too.


`WebGLRenderer`
![image](https://github.com/user-attachments/assets/e9f1fe6e-5920-4015-9670-f4860dfb521a)

`WebGPURenderer` after [this PR](https://github.com/mrdoob/three.js/pull/29280)
![image](https://github.com/user-attachments/assets/c2137336-8484-492e-9d06-847c0d838c83)
