### ISSUE TITLE
BufferGeometry.setFromPoints() incompatible with WebGPURenderer

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#29452]
### Description

With the ported `webgpu_modifier_curve` example, moving the line curve with the control ports is not correctly detected by the renderer, where this geometry's existing position attribute is replaced. (the renderer tracks the original attribute and does not detect the new attribute).

### Reproduction steps

1. Use geometry.setFromPoints() to change the vertices of an object.
2. No changes in resulting render.

exposed by `webgpu_modifier_curve` if available

### Code

n/a

### Live example

-

### Screenshots

![Screenshot 2024-09-20 102450](https://github.com/user-attachments/assets/993d1a38-4252-4b5a-b327-f4bccd21e329)

### Version

168dev

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
I'm not sure I would consider this issue as a bug anymore. Before https://github.com/mrdoob/three.js/pull/29696, buffer attributes were replaced which we do not recommend since we can't support `dispose()` methods on buffer attribute level. Overwritten attributes could eventually produce a memory leak. 

Buffer attributes should be created with sufficient space so they can hold up upcoming data. Updating data means updating the _existing_ buffer, not overwriting it. If a buffer attribute gets obsolete, `dispose()` must be called on the entire geometry and then created a new one.

`WebGPURenderer` does not have to support this use case even if `WebGLRenderer` does. The more strict behavior of `WebGPURenderer` might lead to better workflows on app level.
