### ISSUE TITLE
OrbitControl - provide the original event to the `start`/`end` events

### ISSUE THREAD

**Issue by erickskrauch** [mrdoob/three.js#29727]
### Description

I need to know the mouse's location when the rotation starts/ends. But I can't get this information without an original event.

### Solution

Call `dispatchEvent` inside of the OrbitControl with the original event.

### Alternatives

I can set a global mouse event listener and track the mouse position. But it would be easier if I could handle the start/end event in one place.

**Comment by Mugen87** [comment]
> I can set a global mouse event listener and track the mouse position.

You should not use mouse but pointer events since `OrbitControls` relies on the Pointer Events API. Besides, from a maintenance perspective it is not good if the controls expose the raw event objects since that makes apps like yours rely on it. If the controls ever move to a different event API, we would have to ensure backwards compatibility or simply break apps. None of this is great.

If you rely on start and end position I suggest you use custom `pointerdown` and `pointerup` event listeners.

**Comment by erickskrauch** [comment]
I understand your point of view. Unfortunately, I have no arguments to change your mind. If you think it is not worth sharing this event with the end developer, then this issue can be closed.
