### ISSUE TITLE
GLTFLoader ignores Geometry names

### ISSUE THREAD

**Issue by bobWinner** [mrdoob/three.js#29753]
### Description

It seems that GLTFLoader ignores Geometry names. It is very annoying.
The Geometry names are readables in the "meshes" part of the data into the .gltf file.
but the names are empty when loaded in threejs.

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

169

**Comment by donmccurdy** [comment]
Note that three.js BufferGeometry instances do not correspond to glTF meshes. A BufferGeometry may be reused with many materials, whereas glTF meshes contain >=1 glTF primitives, and each primitive is more like a three.js Mesh – each having 1 geometry and 0–1 materials. So we typically load glTF "mesh" types as THREE.Group instances containing one or more THREE.Mesh instances. When the THREE.Group would contain only one child, GLTFLoader skips the THREE.Group wrapper. So if the glTF mesh has a name, you will find a similarly-named Mesh or Group, not a BufferGeometry.

Related:

- https://github.com/mrdoob/three.js/issues/11944
- https://github.com/mrdoob/three.js/pull/12244

I wouldn't be opposed to revisiting the decision to flatten the node hierarchy, and to guarantee there's always a THREE.Group representing the glTF mesh (even if it has only one child) but I don't think there's any outcome where GLTFLoader could assign names to BufferGeometry instances, because there's no corresponding concept in glTF.

**Comment by bobWinner** [comment]
I understand.
I personally don't need geometry names as long as userData correctly matches the Custom Properties i set in Blender.
Thank you for the info.

**Comment by donmccurdy** [comment]
@bobWinner that should work — you may just need to check if the .userData comes through on the three.js Geometry or the Mesh.

**Comment by bobWinner** [comment]
> @bobWinner that should work — you may just need to check if the .userData comes through on the three.js Geometry or the Mesh.
The blender Custom properties assigned to Geometry are exported in the threejs Mesh.
This is an oddity.
But the data is exported and usable.

**Comment by donmccurdy** [comment]
Nothing in Blender or glTF corresponds directly to a three.js a BufferGeometry concept, so I think looking for your data on the Mesh is probably correct. But the fact that the names of the meshes in the glTF file appear nowhere in the resulting scene is not ideal, it's because GLTFLoader is collapsing the mesh/primitive concepts into one Mesh if the mesh has only one primitive. Aiming to create a simpler scene graph, maybe that's overly complicating things.

I've written up a reproduction of the issue and various complications in https://github.com/mrdoob/three.js/issues/29768, let's track the issue there, if that's OK.
