### ISSUE TITLE
Ability to set a custom size for a reflector render 

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#30210]
### Description

Currently, the reflector copies the resolution of the renderer on every update : 

[https://github.com/sunag/three.js/blob/87af669d9f8564bc906216c1c3f0db9cb7582ba0/src/nodes/utils/ReflectorNode.js#L291](https://github.com/sunag/three.js/blob/87af669d9f8564bc906216c1c3f0db9cb7582ba0/src/nodes/utils/ReflectorNode.js#L291)

Before we could pass options to set the target size directly

[https://github.com/mrdoob/three.js/blob/dev/examples/jsm/objects/Reflector.js#L52](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/objects/Reflector.js#L52)

### Solution

Pass options to set an resizeAutoUpdate: false, and expose the render target so it can be resized manually outside of the reflector 

### Alternatives

.

### Additional context

.

**Comment by Mugen87** [comment]
There is now a resolution property that allows to scale the resolution to an arbitrary value.

https://github.com/sunag/three.js/blob/87af669d9f8564bc906216c1c3f0db9cb7582ba0/src/nodes/utils/ReflectorNode.js#L223-L229

Since it's important to keep the aspect ration, a separate size property does not make sense, imo.

**Comment by mrdoob** [comment]
Agreed 👍
