### ISSUE TITLE
Attach object to bone (Skeletal animation)

### ISSUE THREAD

**Issue by trevex** [mrdoob/three.js#3187]
Previously I calculated a point on the mesh, I attached a box to, by using the morphtarget vertex data. Obviously this is quite straight forward, but how would I go about and do the same with a skeletal animated model?

As far as I know the animation-system was developed by @alteredq , but I couldn't fully figure it out, especially the bone texture. How is the current position of a bone calculated?

**Comment by makc** [comment]
This is an old thread to bump, but I've figured it is better then creating new one. I have this code to mirror skin vertices transformation:
```javascript
    var transformedSkinVertex = function (skin, index) {
        var skinIndices = (new THREE.Vector4 ()).fromAttribute (skin.geometry.getAttribute ('skinIndex'), index);
        var skinWeights = (new THREE.Vector4 ()).fromAttribute (skin.geometry.getAttribute ('skinWeight'), index);
        var skinVertex = (new THREE.Vector3 ()).fromAttribute (skin.geometry.getAttribute ('position'), index).applyMatrix4 (skin.bindMatrix);
        var result = new THREE.Vector3 (), temp = new THREE.Vector3 (), tempMatrix = new THREE.Matrix4 (); properties = ['x', 'y', 'z', 'w'];
        for (var i = 0; i < 4; i++) {
            var boneIndex = skinIndices[properties[i]];
            tempMatrix.multiplyMatrices (skin.skeleton.bones[boneIndex].matrixWorld, skin.skeleton.boneInverses[boneIndex]);
            result.add (temp.copy (skinVertex).multiplyScalar (skinWeights[properties[i]]).applyMatrix4 (tempMatrix));
        }
        return result.applyMatrix4 (skin.bindMatrixInverse);
    };
```
This works perfectly for T pose:
![screen shot 2015-07-24 at 22 47 04](https://cloud.githubusercontent.com/assets/242577/8884511/8377b480-3257-11e5-8245-ce029ad80cb2.png)

But with arms lowered some parts explode into angel-like shape:
![screen shot 2015-07-24 at 22 46 10](https://cloud.githubusercontent.com/assets/242577/8884536/b1ab7c38-3257-11e5-8a76-d6cc1a8369f9.png)

Here is arms placed slightly differently:
![screen shot 2015-07-24 at 22 55 46](https://cloud.githubusercontent.com/assets/242577/8884552/d384ab2c-3257-11e5-9cbf-0e6ba80d29cb.png)

My current theory is that this happens when there are > 2 bones. But... why?

**Comment by titansoftime** [comment]
Unless I am misunderstanding the OP... Since the original post date this has been made very straight-forward. The bones are now an ``Object3D`` so you can simply add a mesh to the bone in a ``mesh.skeleton.bones[someindex].add(mesh2)``.

This is how I add weapon objects to my character mesh in my app.

**Comment by makc** [comment]
true, but I need to know where the vertices are, but since 
> your answer seems to be the only comprehensive one out there
means I've found it on google, I'm here. perhaps I should echo this to stackoverflow.
