### ISSUE TITLE
Incremental loading and non-blocking parsing and rendering

### ISSUE THREAD

**Issue by benbro** [mrdoob/three.js#4397]
Hi,

I have large models > 20MB which blocks the browser when parsing and rendering them for several minutes.
In my case the 3D viewer is only part of the app and models are loaded in the middle of a session so showing a progressbar is not enough.

What part is the most expensive?
- Parsing string to JSON
- Parsing JSON object to three.js objects
- Rendering

Are there plans to improve the browser responsiveness when loading large models?
Or maybe I'm missing existing features?

Some thoughts:
- Break the JSON file to multiple chunks. Each file could be a separate geometry or the loader could load a large file with chunk encoding and parse and render geometries when it has enough data. (pdf.js does that).
- Use a web worker to load and parse the data and pass it as a transferable object.
  I'm not sure if IE11 support this feature but FF and Chrome do. (pdf.js uses this technique).

Progressive loading of PDFs 
    https://github.com/mozilla/pdf.js/pull/2719 
Worker with transferable objects
    https://github.com/mozilla/pdf.js/pull/3904
    http://updates.html5rocks.com/2011/12/Transferable-Objects-Lightning-Fast

**Comment by donmccurdy** [comment]
Some updates since this bug was last opened:

- GLTFLoader is largely non-blocking (bugs appreciated if you find issues)
- OBJLoader has Web Worker support (maybe some other loaders as well?)
- ImageBitmapLoader can be used to decode textures asynchronously (see #12456)

Closing this issue, as there is more recent discussion in #11746.
