### ISSUE TITLE
Cascading shadowmaps broken

### ISSUE THREAD

**Issue by jbaicoianu** [mrdoob/three.js#4507]
It looks like cascading shadows are broken, going back at least a couple builds.  Take a look at the morphtarget_md2_control example:

http://threejs.org/examples/#webgl_morphtargets_md2_control

I'm no expert in how shadowmapping works, but what it looks like to me is that the lowest-level shadowmap texture is being used for all levels, rather than each level being a separate texture.

**Comment by rchoetzlein** [comment]
What about:
depthKernel[0][0] = unpackDepth ( texture2D ( shadowMap[ i ], shadowCoord.xy + vec2(dx0,dy0) ) );

**Comment by mrdoob** [comment]
@rchoetzlein could you do a PR with a fix? 😇

**Comment by rchoetzlein** [comment]
@mrdoob.. 
There are two issues I see. The Linux/Intel index access issue, for which @KillerJim has a switch-based workaround (try using the '?' operator, usually better), and is most likely driver specific. The other is the 'jumping' issue seen in your youtube video on multiple hardware. @jbaicoianu sees "a frame or two lag", from which it's not clear if he's seeing the same jumping issue.
Since this is seen on multiple hardware, it may also be a run-time or app-level issue. In any case, if you can do some experiments (like killerjim did for the other issue), you should be able to determine where this is coming from.
If it turns out to be a linux/nvidia specific, I can help file it. But need to isolate the app code.

**Comment by rchoetzlein** [comment]
Ok, sorry, just found out what PR means on github.. I'm with nvidia, and PR can mean a driver patch for us, so I thought you were asking for a driver fix. The second bug issue may not be a driver issue, and isolating the app condition that triggers the 'jumping' is next step.. I'll take a look if I have time, and/or check back on this thread.

**Comment by mrdoob** [comment]
@rchoetzlein thanks!
