### ISSUE TITLE
Serialization as part of class implementation

### ISSUE THREAD

**Issue by kumavis** [mrdoob/three.js#4609]
Discussion has evolved, [see below](https://github.com/mrdoob/three.js/issues/4609#issuecomment-38750744)

Original tile: "serializing three.js objects"

---

Does the three.js library provide a means of serializing its objects? I don't mean exporting them to existing formats (`.obj` etc), but serializing them 'as they are' to json.

Three.js objects like Scene and Mesh are rich, and cannot be serialized with a simple `JSON.stringify` call. One of the reasons for this is the circular references e.g.: `.children[0].parent`. The objects also contain helper methods `.lookAt()` and rich properties like `Vector3`. How do we expose just the information needed to recreate the object using simple data structures?

If this is a solved problem, and the library contains a simple serialization method that I haven't discovered yet, please let me know! I suspect it is, because of [this json file](http://threejs.org/examples/scenes/test_scene.js) used in the scene loader example

If not, I suggest implementing a toJSON method on Three.js objects.

```
ECMA-262 defines toJSON as a method that, if exists and callable,
returns a value that JSON.stringify can use to convert an object into a JSON text. 
```

source: http://anton.kovalyov.net/p/tojson/

so the return value of toJSON is an object that is the JSON serialize-able data required to recreate that same object.

**Comment by DelvarWorld** [comment]
Old thread, but I'm looking at this too. I need to serialize and deserialize shaders which have three objects for uniforms (`THREE.Vector3`, `THREE.Matrix4`, etc). right now i'm re-inveting my own wheel.

It seems the loader for the editor [does this to some extent](https://github.com/mrdoob/three.js/blob/master/editor/js/Loader.js#L354), but it's not abstracted in any way. When you serialize a scene, it makes enough data to get the original object back:

	"materials": [
		{
			"uuid": "7B1D9239-40C0-4F20-B7F7-8DB56291ECF8",
			"type": "MeshPhongMaterial",
			"color": 11579568,
			"emissive": 0,
			"specular": 0,
			"shininess": 50
		},

My particular use case is that a value could be *any* THREE data type. It would be nice to pass a json object to a utility function and get back a correct three object.

**Comment by ianpaschal** [comment]
Annual revival time!

I'm having trouble with this as well and would like to see a way to save a mesh as JSON. I'm working on a game with an ECS structure and while in something like Unity, the entity would have a `position` and `rigidbody` component, I have a set up like `myEntity.model = a mesh`. Saving all the components and properties to JSON is fine, except for the pesky `.model` object. I'd not worry about it but to reload the object, the position and rotation of the model has to be known. Saving the actual mesh is not needed as it's referenced as an asset that many entities use. But the position and rotation are needed.

The two workarounds I'm looking at right now are:

1. Copy `myEntity.model.position` to `myEntity.position` before saving (Vector3s stringify just fine). Also for rotation. When reloading, the entity will copy the mesh back from the asset and set the mesh's position to its own `.position`. This feels very clunky to me though.

2. Make `myEntity.modelData = myEntity.model.toJSON();` before saving. Since I only really need the position and rotation, this feels very clunky. No need to write a tree model to disk 1000 times.

Any advice?

**Comment by mrdoob** [comment]
> I'm working on a game with an ECS structure and while in something like Unity, the entity would have a `position` and `rigidbody` component, I have a set up like `myEntity.model = a mesh`. Saving all the components and properties to JSON is fine, except for the pesky `.model` object.

Uh? What `.model` object?

**Comment by ianpaschal** [comment]
>Uh? What `.model` object?

Basically I have this:
```
var Entity = function( name, type, owner ) {
	this.name = name;
	this.type = type; // Reference to the asset which it will copy.
	this.model;
	this.owner = owner; // Player which entity belongs to.
	this.state = undefined; // State which entity is currently in.
	this.target = { /* Either a Vector3, or ID of object */ };
	this.components = {};
	return this;
};

//...

Entity.prototype.spawn = function( x, y ) {
	// Get model from asset and apply it to this entity:
	this.model = Boiler.assets[ this.type ].mesh.clone();

	// Set model position:
	this.model.position.x = x;
	this.model.position.y = y;

	this.model.name = this.id;
	scene.add( this.model );
};
```
Everything is able to save as JSON very easily, but having `Entity.model` in there, which is a `THREE.Mesh`, mucks everything up. I could do something like: `Entity.position = Entity.model.position` before saving but that feels really clunky.

**Comment by mrdoob** [comment]
I'm not sure how this relates to the library... 😶

**Comment by Mugen87** [comment]
#11266 is now the leading issue for `.toJSON()` and `.fromJSON()` methods.
