### ISSUE TITLE
Primitives generated by EdgesHelper, BoxHelper, WireframeHelper do not have position

### ISSUE THREAD

**Issue by pchasco** [mrdoob/three.js#4727]
Updating the position on EdgesHelper, BoxHelper or WireframeHelper has no effect. In order to update the position of these, one must first create a host Object3D node, then parent the helper to the host using Object3D.add. The position of the host may then be modified to move the helper mesh.

If this is not a bug, I feel the documentation should be updated to reflect these semantics.

**Comment by funwithtriangles** [comment]
I have recently come across this issue and would like to bring it up again. What are the disadvantages to decoupling the helper mesh from the original mesh? If you want them to share the same world space, surely you just need to do this:

```javascript
mesh.add(helperMesh);
```

That way there is more freedom to do what you want with this helper. Right now I am trying to keep some hierarchy in my scene. I'd love to have these edges as children of their original meshes so that I can select them easily in my code rather than having to rely on some sort of ID system.

**Comment by WestLangley** [comment]
@funwithtriangles Can you show a simple live example demonstrating exactly what you want to do and why the current approach is inadequate for your needs?

**Comment by funwithtriangles** [comment]
@WestLangley I'm not sure easily I can demonstrate what I need to do with a fiddle. I was just hoping there would be a way to add a wireframe as the child of a mesh rather than the scene, as it would help me structurally. It turns out this is possible, by undoing what the helper does in terms of matrices:

```javascript
parentMesh.add(edgesMesh);
edgesMesh.matrix = parentMesh.matrix; // undo helper
edgesMesh.matrixAutoUpdate = true; // undo helper
```

Perhaps there should simply be an option with the helper to stop this from happening?

**Comment by WestLangley** [comment]
@funwithtriangles OK, so you have a workaround. Good.

We likely want to keep the helpers simple, but we can see what @mrdoob thinks.

Helpers are not added as children because, for example, `VertexNormalsHelper` will not work correctly if it is a child of the mesh and the mesh is scaled non-uniformly.

**Comment by Wilt** [comment]
About geometries in sync: if the `THREE.EdgesHelper` would be also updated when the original geometry is updated would be like a dream  :+1: 

I could even imagine `visible` property in sync. We use `THREE.EdgesHelper` for showing outlines of the mesh. But when we hide the mesh we also want to hide the outlines (preferably automatically). That would in a way again plea for adding them to their parent object so it happens automatically. 

I think the problem is people have different expectations, but I am with @WestLangley here and would say a helper should be as much in sync as possible.
Updating geometries would be a nice feature for future development.

@funwithtriangles I don't totally understand your problem, if you don't want the matrix from the helper to be in line with the object why not create an `edgesObject`, you don't seem to need a helper?
````
var edgesObject = new THREE.LineSegments(
    new THREE.EdgesGeometry( object.geometry, angle ), 
    new THREE.LineBasicMaterial( { color: color } ) 
);
````
Now you have the same result but you can do whatever you want with it...

Would it be possible to pass a third parameter that defines whether the helper is for local or global space? For example we add `THREE.EdgeHelper` instances to our objects to show their outlines. 

I also once requested material param for `THREE.EdgesHelper` in an issue: https://github.com/mrdoob/three.js/issues/9123
Performance was not a relevant argument, but I would also like to be able to change material for all my edgesHelpers in one go (to change color). It could be a global variable in my application that I could set in a UI (in a way that is also syncing, but on application scale).

**Comment by mrdoob** [comment]
`EdgesHelper` and `WireframeHelper` are now `EdgesGeometry` and `WireframeGeometry`.
