### ISSUE TITLE
Refactor ExtrudeGeometry, Shape classes?

### ISSUE THREAD

**Issue by zz85** [mrdoob/three.js#4745]
Was trying to play around #4429 when I realized the way `ShapeGeometry`, `ExtrudeGeometry`, `Path.js`, `Shape.js`, `CurvePath` etc are probably a little too coupled together.

The first step might be to do the extraction of a Shape representation could be done outside the Geometry classes.

```
var points = [ shapePoints, holePoints, holePoints ];
var points = shapes.extractPoints();
```

The next step is to decide whether to take triangulation out of the Geometry classes so the geometries classes only accepts faces.

```
var faces = THREE.TriangulateUtils.pointsToFaces( bla );

shapeGeometry = new ShapeGeometry(faces);
extrudegeometry = new ExtrudeGeometry(faces, options);
```

This makes it more modular to have an external tessellation library, and also for the shape and ExtrudeGeometry to take in more generic inputs.

Of course, this feels like there's a lot of refactoring and work to be done...

**Comment by Mugen87** [comment]
The `Curve`/`Shape` classes were refactored and enhanced in the past (e.g. #12406 or #12797). We also changed the internal triangulation code (#12661 and #12725). 

I personally think it's okay if `ShapeGeometry` and `ExtrudeGeometry` accept shapes and not a more generic data structure, especially since the library is now able to serialize/deserialize shapes without redundancy. Because of this, I vote to close the issue.
