### ISSUE TITLE
Enhancement: Game SpriteHUD..Avoiding 2x-Render

### ISSUE THREAD

**Issue by erichlof** [mrdoob/three.js#4795]
Hi all,
I am a lone-wolf 3D game programmer working with three.js.  My most recent game project is a space shooter where some kind of HUD is needed.  I was recently looking at this thread for possible solutions: https://github.com/mrdoob/three.js/issues/1959 
and
https://github.com/mrdoob/three.js/pull/4121

However, @mrdoob and @WestLangley , your updated sprite example requires an orthographic camera (in addition to the perspective one) and a second rendering pass.

I was working on my game when I 'stumbled' upon a nice way to circumvent having to render the scene a second time with a second camera.  

The solution is instead of adding the sprites to the scene object as we normally do for everything else, we make the sprite a 'child' of the camera object.  Like so:
camera.add( crosshairSprite );

Now, whatever image you have loaded for 'crosshairSprite' will stick to the center of the screen no matter what.  No orthographic camera, no second rendering pass.

I threw together a basic demo showing off the new capabilities.  I positioned the 'redball' Sprites in the four corners of the webpage (a la your Sprite example) and I manipulate them in various ways.  Notice there should not be any performance hit while using this method.  

Press 'M' for MouseLook, Space to thrust, LMButton to Fire
http://erichlof.github.io/AsteroidPatrol3D/SpriteHUD.html

You can drag the browser-window's dimensions around, shrink, squash, stretch, etc.. - and the sprites and HUD objects positions will remain relative to their desired initial position on the webpage.

To further this method's usefulness, I created a simple formula to make the X and Y HUD coordinates available to the threejs user by specifying a percentage of the webpage (kind of like one of the various HTML-element positioning options):

var crosshairPercentX = 50; //middle horizontally 
var crosshairPercentY = 50; //middle vertically
var crosshairPositionX = (crosshairPercentX / 100) * 2 - 1;
var crosshairPositionY = (crosshairPercentY / 100) * 2 - 1;
crosshairSprite.position.x = crosshairPositionX * camera.aspect;
crosshairSprite.position.y = crosshairPositionY;
crosshairSprite.position.z = -1.5;

This way, you can specify the X percentage (0 being leftmost, 50 being middle, 100 percent being rightmost) of the webpage. Same for the Y percentage (0 being bottom, 50 being middle, and 100 being top of the webpage).  

This trick also works with 3D objects.  I put a slowly rotating Tetrahedron at the bottom of the HUD and it stays right there even when you change your player's ship rotation. Also, since they are rendered with the same camera as the rest of the scene/world, you can interact with them.  (Although raycasting a HUD/menu item with a mouseclick might require adding it to the 'scene' as well, as is traditionally done).

Hope this helps some of you game/threejs programmers out there looking to do quick HUDs!
-Erich

**Comment by trinketmage** [comment]
Hello,
I am quite new to threejs, don't be too harsh if i'm telling any wrong stuff :)
I was working on a crosshair for VR in three.js and it worked fine since the moment i have to move the location of my camera cause of the zBuffer rendering when i got closed to some objects. I tried to use set renderer.sortObjects to false, but with a lot object in the scene loaded from files.obj I got a lot of troubles reordering elements and children elements.
Like in this example where objects are messed up : http://jsfiddle.net/QHssJ/20/.
I believe that it might be a solution with reordoring with a "vector" from the camera but that this will cost pretty much ? 
Can anyone tell me tips to measure difference within two codes out of fps parameter please ?

To avoid to much struggling i opt for the two scenes rendering.
For VR, html rendering is not possible as its Orthographic (am i wrong ?) and VR need Perspective, so i came out with this solution : https://github.com/trinketmage/three.js-vr-hud.
I would appreciate much any feedback, to level up my code.

**Comment by mrdoob** [comment]
@trinketmage please use StackOverflow for help.
