### ISSUE TITLE
Consistent API for loaders and controls

### ISSUE THREAD

**Issue by benbro** [mrdoob/three.js#4877]
Hi,

Currently loaders and controls don't have the same API which makes it harder to interchange between different types and experiment.

Some of the loaders for example are missing progress events and callbacks for model and textures loading.
https://github.com/KhronosGroup/glTF/issues/226

If all controls will extend the same base class, it'll be easier for example to add support for pointer events (IE11).
I'm also missing documentation about differences between the controls and a demo comparing them side by side.

Can we start discussing the API here or do you prefer a separate issue for loaders and controls?

Thanks

**Comment by looeee** [comment]
The loaders can currently be roughly grouped into 3 types according to return object (ignoring texture and font loaders) : 

### 1. Returns a JavaScript object with various properties ( GLTFLoader, ColladaLoader, MMDLoader, ... )

 For example, the GLTFLoader returns this:

```
 glTF = {
    scene:,
    scenes,
    cameras,
    animations,
    asset,
    parser,
    userData
}
```

My suggestion is that we use this as a prototype for all loaders, with the addition or removal of properties as needed.

In the case of the FBXLoader, the return object would look like this:

```
fbx = {
    group,
    models,
    animations,
    cameras,
    lights,
    geometries,
    skeletons,
    materials,
    textures
}
```

The first property, `group`, would be included to maintain backwards compatibility and would be equivalent to the current return object. Currently all of the rest of the data from the FBX file are dumped into this `group`, which doesn't always make sense as FBX  files are often used to export things like skeletons with animations, and it's rarely useful to include cameras or lights in this way either. 

### 2. Returns an `Object3D`, `Group`, `Scene`, or `Mesh` (3DSLoader, 3MFLoader, AMFLoader, FBXLoader, PCDLoader, ...). 

The obvious advantage here that you can just do `scene.add( returnedObject )`. 

### 3. Returns a Geometry or Geometry and Materials array (PLYLoader, STLLoader, CTMLoader, ... )

### Exceptions: PDBLoader, Sea3DLoader, ?

 `PDBLoader` returns `pdb.geometryAtoms` and `pdb.geometryBonds`, and `SEA3DLoader` handles a lot of extra stuff like updating animations with a custom `THREE.Sea3D` object. I haven't exhaustively gone through all the loaders so there may be other exceptions. It would probably be OK to ignore these for now. 

Obviously, changing the returned object of loaders will be a breaking change. If we go ahead, we should do this for all loaders in a single release cycle - since we're close to the start of a cycle now it's a good time to discuss this. It should be a relatively simple change for most loaders.

**Comment by Mugen87** [comment]
In context of loaders we made some progress. All loaders are now derived from `THREE.Loader` which unifies the general API. However, the signature of `parse()` and `load()` is not consistent across all loaders (see https://github.com/mrdoob/three.js/commit/0d253f07a3f188d47ccdab1fa739c3a2d5782e93#r35111832) as well as the types of the mentioned callback parameters. So still some room for improvements 😇

**Comment by Mugen87** [comment]
Imo, the issue can be closed. Loaders and controls have a common upper class now and a more consistent interface compared to six or ten years ago.

It's best to discuss the remaining minor variations like different return types of loaders in separate issues if there is still a need for more consistency.
