### ISSUE TITLE
UV map of extruded geometry

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#4994]
ExtrudeGeometry seems to have a bug in UV mapping. Previous issue was nto clearly states, thanks to @mrdoob and @WestLangley this is more to the point.

When you extrude a shape, it's "face" gets mapped well, but some of the sides get erroneous stretched UVs.

http://codepen.io/travnik/pen/oAauG?editors=001
![2014-06-26 17_55_14-codepen - a pen by alex goldring](https://cloud.githubusercontent.com/assets/5939063/3401648/e0afdb22-fd52-11e3-874c-4c16acc88d21.png)

three.js : r67
browser: Crome Version 35.0.1916.153 m
OS: win 8.1 x64
graphics: nVidia GTX 660 Ti

**Comment by codrakai** [comment]
Was looking through old issues and came across this one. I agree with @WestLangley that UV generation should generally be up to the user; the space of possible geometries and texturings is just too broad. That said, I thought it was interesting that only some of the surfaces in the linked codepen exhibited extreme stretching. Looking closer, I saw that it was a result of the following code in the default UV generator (emphasis on the first line):

https://github.com/mrdoob/three.js/blob/55f98ce4938b652d082d13f536217352a6f1adc6/src/geometries/ExtrudeGeometry.js#L734-L752

In short, if the difference in the y-coordinates of the first two points in the face is close to zero (which I take to mean "if the surface is basically level i.e. normal is close to +z"), base the uv coords on the x and z of the vertices. Otherwise, use the y and z coordinates.

In the case that we see in the codepen, there are some surfaces that are just off level, but past the threshold in that condition. This causes them to use the y coordinates and the z coordinates to calculate the uvs. However, because the y coordinates are very close, it covers very little of the provided texture, which means that it gets stretched.

A solution that works (in the case of this codepen, at least), is to use different criteria for the switch between "level surface uv calculation" and "vertical surface uv calculation." Instead of asking "are the y coordinates very close?" we can ask "is the angle between a segment in the surface and z+ smaller than 45 degrees?" or "is the dot product of normalized vectors in those directions less than √2/2?" Using this criteria, we basically use of one our calculation methods for surfaces from level to diagonal and the other from diagonal to vertical.

Here's another shot of the before:
<img width="450" alt="Screen Shot 2021-05-21 at 10 54 47 PM" src="https://user-images.githubusercontent.com/59149612/119216262-9b130b80-ba87-11eb-8b22-117da4b308db.png">

And here's the after:
<img width="450" alt="Screen Shot 2021-05-21 at 10 54 30 PM" src="https://user-images.githubusercontent.com/59149612/119216259-964e5780-ba87-11eb-8163-6c26a3f2dc43.png">

Here's a look at the code that I'm using to replace the conditional above:
```javascript
    const vectorInFace = new Vector3(b_x - a_x, b_y - a_y, b_z - a_z);
    const up = new Vector3(0, 1, 0);

    const cos45 = 0.70710678;
    const isMostlyHorizontal =
      Math.abs(vectorInFace.normalize().dot(up)) < cos45;

    if (isMostlyHorizontal) {
```

[Here's a code sandbox](https://codesandbox.io/s/festive-banzai-revtc) based on the original codepen that allows you to switch between the default and the updated using a flag at the top of index.js.

Do folks think that something like this is a sensible change to the default uv generator? Does it sufficiently address the concern brought up in this issue? (And if not, what _is_ the goal for this issue?)

**Comment by WestLangley** [comment]
Before
![Screen Shot 2021-05-22 at 6 37 55 AM](https://user-images.githubusercontent.com/1000017/119223649-96bb1280-bac8-11eb-9cd3-bada8484d1a9.png)

Affter
![Screen Shot 2021-05-22 at 6 33 07 AM](https://user-images.githubusercontent.com/1000017/119223683-c0743980-bac8-11eb-906f-9b021ac4c345.png)

It seems like a reasonable thing to try. Would you like to file a PR?

**Comment by codrakai** [comment]
> It seems like a reasonable thing to try. Would you like to file a PR?

Will do! Excellent choice of texture for that test, too. 👌
