### ISSUE TITLE
Sprites Drawn Behind Things with 'logarithmicDepthBuffer'

### ISSUE THREAD

**Issue by Herst** [mrdoob/three.js#5133]
With logarithmicDepthBuffer enabled sprites are drawn behind things.

testcase: http://jsfiddle.net/Herst/384Q6/

(corrected title and text and added testcase)

**Comment by jonnenauha** [comment]
We would like to fix this with a PR, its affect one of our projects. Looks like the shader just needs to have the correct `ifdef` block and select the right depth math. https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/plugins/SpritePlugin.js#L291-L339 

This might be a bit more difficult as it does not use `THREE.ShaderMaterial` but constructs everything directly with the WebGL API https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/plugins/SpritePlugin.js#L100-L116

The logdepth boolean is known at the time when the plugin gets constructed, so it could create the correct shader. But would it make more sense to make the plugin use `THREE.ShaderMaterial` or is it not intentionally using it as its not part of the normal render pass?

Could @WestLangley @mrdoob suggest a good way to fix the shader and its defines so we could take a look at this?

ping @hyrppa95

**Comment by jbaicoianu** [comment]
Yeah, since this is creating its own material rather than using ShaderChunks, you'll need to duplicate some code from those into SpritePlugin.js.  I'm not sure how the #defines are handled for these custom plugins though.  The most important stuff is in the vertex shader:

https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/logdepthbuf_vertex.glsl

The fragment shader and the #ifdef USE_LOGDEPTHBUF_EXT stuff is optional, they provide better handling for certain scenes

**Comment by SntsDev** [comment]
I'm experiencing the same issue. Any plan to fix this?
Thanks!

**Comment by Neesnu** [comment]
This is still an issue.   =(
