### ISSUE TITLE
Selective lighting

### ISSUE THREAD

**Issue by goodsign** [mrdoob/three.js#5180]
I'm not sure whether this is already a planned feature or maybe even a finished one, so I'll try to explain the task first.

I need to do selective lighting for different rooms. For example, I have two rooms. One light must only affect objects and inner walls of one room. The second room must not be affected by this light.

Currently, if I add a light to the scene, it affects all objects in its distance. And I get strange effect when light comes "through the wall" of the second room.

So I think I need some kind of groups or channels for lighting, so that I could set the objects that are affected by one light source and objects that are affected by another.

I haven't found anything like that in either lights or objects, so I thought that maybe it could be a good feature to have.

And, btw, if it is not implemented yet, what is the recommended approach to solve such tasks using current state of three.js?

**Comment by makc** [comment]
holy crap how is this still not implemented? after +9999 from rohan )

**Comment by rohan-deshpande** [comment]
Haha my guess is that it's kind of hard to implement @tsone can you provide some info on that commit? Browsing on a phone client right now

**Comment by makc** [comment]
how is it hard to implement if these are just uniforms they pass to materials. all they have to do is substitude global list of lights with the one defined in material, if it exists, somewhere deep in webgl renderer.

**Comment by Zob1** [comment]
Here is a simple JSFiddle that tests the Dev branch's Layers implementation:
https://jsfiddle.net/Angrypickle/t8f7q3vo/4/
Unfortunately, as of this moment, it doesn't look as though it's working properly. Or am I doing something wrong?

**Comment by mrdoob** [comment]
Yes. Layers don't work with lights yet. They do work with camera/object though! 😊

**Comment by Zob1** [comment]
Roger that sir! Here is an updated JSFiddle that uses overlapping cameras to achieve selective lighting with layers:
https://jsfiddle.net/Angrypickle/t4a1eusL/
It seems to work properly on desktop and mobile. Anyone see anything profoundly bad with this approach? At least until lights are tied into the layers functionality?

**Comment by makc** [comment]
> Anyone see anything profoundly bad with this approach? 

of course it is bad. rather than having single camera navigating the scene, people will now have to do things `camera1.add( camera2 );` I mean this is WTF when I look at it. Like... what? camera in my camera? what if I have dozens of rooms that need to be individually lit? how many cameras do I need? and layers... there were no layers yesterday, right, and now I have to **l̲e̲a̲r̲n̲** about them.

rant over, not to say I have the perfect solution for this. e g alternativa3d people used to put lights on stuff that was in light's bounding boxes. this had an advantage of next-to-0 setup for end users, but it was falling apart when the border between lights had to be at the angle. but still, if I had to solve this problem in actual project right now, I would most probably resolve to scraping used standard materials into ShaderMaterial-s and passing the lights I want to by hand there.

**Comment by mrdoob** [comment]
@makc layers are actually super simple (and powerful)! @Zob1's approach is definitely not the right approach. Hopefully it won't take long until layers also work with lights.

**Comment by rohan-deshpande** [comment]
Guys just to make sure I am following correctly; let's say I have a single scene and a "main" light source. Is it possible with this technique to have certain materials ignore this main light source, while also casting shadows from a different light source?

**Comment by mrdoob** [comment]
Well, for that we'll also have to add layers support to materials.

What we can do at the moment is show/hide objects from the camera:

Say that you are doing a game and, in the editor, you use spheres to display colliders. Those spheres could be set to layer 1, the camera's editor could have layers 0 and 1 enabled, but the game camera could have be set to layer 0. That way, in your editor you see all the dummies, but in the game they're gone.

I think this will make more sense whenever I add the functionality to the editor itself. We should probably do some examples too.

**Comment by rohan-deshpande** [comment]
Right! So basically what I am wanting to do is, I have 2D characters in my Three JS world. These characters need "spot" shadows to make them look like they are part of the environment. I am currently achieving this using transparent black circle geometries placed at their feet and some fairly hacky stuff to get it working at angles. Even then it doesn't work well at all on complex surfaces. 

My original idea was to have invisible circle geometries places as "halos" above each character and create a light that is pointing directly down, covering the whole scene. These halos would only cast shadows from this light source while everything else in the scene would cast shadows from the "main" light source. 

I guess for this idea to work, we need layers right?

**Comment by WestLangley** [comment]
> These halos would only cast shadows from this light source while everything else in the scene would cast shadows from the "main" light source.

We used to have a `shadowOnly` option, but it was removed.

FWIW, there is [this approach](http://threejs.org/examples/webgl_shadowmesh.html) to creating shadows...

**Comment by rohan-deshpande** [comment]
Ah but shadowOnly wouldn't really work because then the halos would cast shadows from both light sources, I only want them to cast shadows from one.

I will check out that example, on the phone right now but looks promising.

**Comment by mrdoob** [comment]
Nope...

**Comment by rohan-deshpande** [comment]
Yeah thought so. Need layers! Hehe

**Comment by erichlof** [comment]
Hi @rohan-deshpande ,

Yes for your use case, you're going to need layers of some sort.  I was the one who implemented the shadowmesh feature a while back.  They were meant to be used for a scene containing a flat floor or ground, because they are single-planar shadows.  However, if you ever need fast, cheap (but correct) single plane shadows, these are hard to beat performance-wise.  The reason I added these was because even for simple demo scenes, shadowmaps dropped my framerate considerably.  Shadowmeshes on the other hand run fast even on my phone.   

You can check out my game that uses them here:  
https://github.com/erichlof/3dLightCycles

I'm rendering the scene twice through 2 different viewports and all game objects (cycles and trail walls) have correct shadows.  It runs silky-smooth on my smartphone, which would be impossible with shadowmaps for 2 scene renderings every frame.

+1 here for layers in the future :)

**Comment by rohan-deshpande** [comment]
@erichlof game looks and runs great on iPhone6 man.

Okay I guess I'll wait for layers. Until then my hacky solution will have to suffice.

**Comment by tarun29061990** [comment]
hey guys
This feature is implemented or not??

**Comment by tarun29061990** [comment]
Hey guys
Is this thing implemented?
http://stackoverflow.com/questions/33689781/casting-shadows-based-on-a-specific-light?noredirect=1#comment55153706_33689781

**Comment by rohan-deshpande** [comment]
No it hasn't been implemented yet. You'll have to wait for layers or try one of the solutions listed in ITT (separate scenes for example).

**Comment by curiouspers** [comment]
+99999 again

**Comment by brianchirls** [comment]
This would definitely be very helpful. And we now have layers working, which it sounds like is what's been holding this up. So, here's the friendly bump. ;-)

**Comment by rohan-deshpande** [comment]
@manthrax check this!

**Comment by fritx** [comment]
+99999 again

**Comment by bnolan** [comment]
I'd love for this. I have a situation where each avatar is lit by only the nearest light, and I can have thousands of lights into the scene, it'd be nice to specify a single light for each avatar.

**Comment by tiesselune** [comment]
Hi! 
I'm going to need this feature, and I thought of implementing it, since I think I've located where this could be done (`initMaterial` in `WebGLRenderer`) and it should be pretty straightforward using existing layers.

I'm thinking of creating a light-specific bit mask (as a `Layers` object) to select which layers are affected by a specific light object (independant of the light's own object layer), then filtering lights/shadowmaps that are set as uniforms for each object in the above-cited function.

Would that be relevant?

I'll try this and submit a pull request as soon as I've acheived this unless you redirect me to some other method before that.

**Comment by tiesselune** [comment]
**UPDATE:** 

https://github.com/tiesselune/three.js/tree/selective-lighting

I'm getting somewhere. Not sure how this might affect performance or how to optimize my code for perf, but it's working on the few tests I've made. Per-layer lighting! Yay!  

I still have to test some more though, and make a relevant example before submitting a pull request.

**Comment by tiesselune** [comment]
**UPDATE:**

I've made a few more tests, and having a same material on two objects that are on different layers (and have different lighting settings) causes the renderer to update the material constantly (via `needsUpdate`) since the lighting settings on the material changes between two objects, which was impossible before. This means a huge perf drop and visual oddities (since the last material upload wins at render time)

Of course, this can be avoided by creating a new material instance instead of using the exact same one for two objects with different lighting settings. But I doubt cloning it for the user is a good idea, since it would mean watching the original material for changes to mirror them onto the clone.

**Here are two solutions I could use:**

1. I could just display a warning when two objects on different layers with different lighting settings share a same material, so the user can create and manage a new clone material by himself.

1. I could add layers at a material level instead of the object's level (and create a parrallel layers system for lights) so that it's mandatory to use different materials to achieve different lighting settings. That would mean there would be the current layer system for visibility (on objects and cameras) and a different one for lighting (on materials and lights).

What do you guys think?

**Comment by brianchirls** [comment]
I was just thinking about this as I saw your comment come in. I think displaying a warning is not helpful, as many people probably won't see it. Of the two, I definitely prefer setting light layers on the material rather than on the object. It's a little counter-intuitive, but it still makes sense.

Just to clarify, when `needsUpdate` is set, in this case, it just recalculates the uniform values, right? It shouldn't have to re-compile a shader because the different shaders should all be cached. What kind of performance hit are you seeing? Did you use a profiler to see exactly where the extra computation is happening?

By the way, `filterAmbiantLights` should be `filterAmbientLights`.

**Comment by tiesselune** [comment]
You are right about the misspelling. I actually had written everything with "ambiant" before noticing it was wrong and I forgot an occurence. 😇

I think I'm gonna move the layer info on the material then. It seems more relevant and consistent with the way it works.

The performance drop came (and still comes) from `initMaterial` (and then `acquireProgram` and `getShaderParameter` which is tremendously slow for some reason) being called every frame several times because the `lightHash` would be different everytime, setting `material.needsUpdate` to `true`.

BTW I'm using Chrome's profiling tools. (Timelines and profiler).

**Comment by brianchirls** [comment]
That's fine by me, but I'm not clear why `acquireProgram` should be running all the time. If the number of each type of light gets added to the program parameters, then shouldn't recompiling the shader each time be unnecessary?

**Comment by tiesselune** [comment]
I don't get it either;

Here's the call stack (at every frame) and the terrible memory leak that follows, if you're familiar with these, that could help me understand what goes wrong. It looks like it's creating new `WebGLProgram`s every frame...

![threejscalltree](https://cloud.githubusercontent.com/assets/2751491/22257950/000c35c0-e260-11e6-81fd-f35eeeb3ab81.PNG)


Maybe it could be `replaceLightNums` that updates the vertex/fragment shader code during the WebGLProgram's creation, causing it to recompile, or considering it's a different shader... ?

**Comment by brianchirls** [comment]
It's probably a good idea to understand why this is happening just to make sure you fully understand the code and are not introducing some new bug. Can you step through it to see why the shader code changes every frame?

I don't know the `WebGLPrograms` well enough to say what's going on, but it seems like it should be caching those shaders for you.

**Comment by tiesselune** [comment]
It's quite simple, actually: 

- to know wether or not to call `acquireProgram`, `initMaterial` gets the shader "code" from the cache (it's more of a hash, actually, constructed in in `getProgramCode`)  and compares it to the"code" of the current material's program.
- Since this function creates the "code" from parameters including number of each type of light, which is filtered and though different between objects, the code can be different for a same material ( so to say, the same program) from an object to the other.
- Since this process is iterated through for each object, the "code" changes several times per frame, causing it to recompile as many times in a single frame: which causes the perf drop.
- That said, since several objects have the same material, and so, the same program, the last object iterated through imposed its parameters to the program, which caused both objects to be lit with the same light setup but not necessarily the same shadowMaps (that can be calculated for objects in a different order, but suffers the same "last object wins" problem), causing my visual oddities.

Now everything works as expected (since each object with different light setups have a different material and though a different program), except for a memory optimization I could do with my own light hashes, which I'm going to tackle soon. 

There could be some improvement if light numbers were variable, so that each material are just iterations of the same program, but since those numbers are inserted in the shader code (in `replaceLightNums`) it seems incompatible with the way things currently are.

Hope the explanation was understandable enough 😅

**Comment by mrdoob** [comment]
I wonder if we can pass the layer id to the shader (one uniform per object and one more uniform per light). Then we could add something like this

```js
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1374
```

Here:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/lights_template.glsl#L31

**Comment by mrdoob** [comment]
Something like...

```glsl
for ( int i = 0; i < NUM_POINT_LIGHTS; i ++ ) {

	pointLight = pointLights[ i ];
	pointLight.distance *= float( object.mask & pointlight.mask > 0.0 );

	...

}
```

**Comment by mrdoob** [comment]
Meh, I don't think we can do bitwise operations in glsl...

**Comment by tiesselune** [comment]
Yep, it looks like bitwise operations begin in GLSL 1.30 and that standard WebGL uses 1.00.  😕

**Comment by erichlof** [comment]
Hi @mrdoob and @tiesselune  ,
Chrome 56 has just landed, and with it brings WebGL 2.0 enabled by default, which uses OpenGL ES 3.0.  That means that Bit operations (and other cool stuff like 3d textures) are now available.  I don't know if Three has been slowly preparing for the shift to WebGL 2.0, but I made a few mandatory changes to my copy of three84.js and enabled WebGL 2.0, and did a bit operation in a shader just to make sure it worked, and it did!  

Just wanted to let you know.  +1 for the masking idea :-)

**Comment by tiesselune** [comment]
Hi @erichlof ! That's great news for WebGL2; it means that WebGL2 renderer will probably be able to approach the masking problems in a more efficient way.

Anyway, given the [very limited use of browsers supporting WebGL2](http://caniuse.com/#feat=webgl2) this far, I don't think we can discard efforts to make it work in WebGL 1 : it's taken a long time until nearly all browsers can run WebGL apps, so it will probably a bit longer until WebGL 2 is really usable at a large scale... 😕 But thanks for the hint!

**Comment by tiesselune** [comment]
Hi all!

I'm trying to **optimize the memory allocation** for this masking feature; as i'm currently doing, I'm creating a new array containing uniforms for each type of light by filtering the `_lights` properties according to the material's layers and the lights affected layers.

**I can't just reuse the same array over and over** since again, the last array update is gonna win (several materials being iterated before uniforms upload)

So I'm stuck with allocating new arrays of light uniforms, which is really not optimal. I'm thinking of trying to apply the mask at the uniform upload level, but I have no idea how to handle that. It would even be better considering CPU perf, I think. Any idea?

**Comment by tiesselune** [comment]
Hi again!

New update: I've done what I thought necessary for memory management, but JS heap garbage collection seams to have a lot to do with my software configuration (running programs, open tabs, extensions) at the time I run profiles. Can someone with a bit more experience on that confirm that my code is not that memory hungry compared to the current version of threejs?

Anyway, I've made an example in [examples/webgl_lights_selective_lighting.html](https://github.com/tiesselune/three.js/blob/selective-lighting/examples/webgl_lights_selective_lights.html). The thing is, I got visual artifacts when using two spotlights (on the same layers) simultaneously on the skinned objects of the scene. I've run tests and it happens on the dev branch also, without considering selective light layers at all (actually, I just added a spotlight in the shadowmap example, on the dev branch). Does anyone know where that comes from? 

Here's a screenshot:
![shadowmap](https://cloud.githubusercontent.com/assets/2751491/22502669/2ecd2040-e86e-11e6-93bc-4772b29b58a5.jpg)

**Comment by looeee** [comment]
It should be possible to view the example live here:

https://rawgit.com/tiesselune/three.js/selective-lighting/examples/webgl_lights_selective_lights.html

I'm getting an error though: 

```
Uncaught TypeError: Cannot read property 'set' of undefined
    at init (webgl_lights_selective_lights.html:117)
    at webgl_lights_selective_lights.html:67
```

**Comment by tiesselune** [comment]
@looeee : you'll have to `npm run build-uglify`. I voluntarily did not include builds in my commits for mergeability purposes...

**Comment by sasha240100** [comment]
Hey, +999999 from me. This should be implemented (at least with `THREE.Layers`)

**Comment by fritx** [comment]
```js
$$('.comment-body').reduce((acc, el) => {
  let mat = el.textContent.match(/\+(\d+)/)
  let num = +(mat && mat[1] || 0)
  return acc + num
}, 0)
>> 1219997
```

**Comment by mrdoob** [comment]
🤔

**Comment by makc** [comment]
@mrdoob he calculated +N-s in this thread

**Comment by makc** [comment]
btw, +14570 for selective lights

**Comment by trusktr** [comment]
This will be incredibly great for fine tuning how lighting works in a higher abstraction.

For example, I'd like to have lighting work one way for the DOM element vs another way for the Sphere in order for lighting to be more realistic in this example:

https://codepen.io/trusktr/pen/RjzKJx

**Comment by trusktr** [comment]
Certain effects that look like a single-point-light can be achieved by combining two or more lights that are selectively affecting only certain elements.

For example, in my previous example, I can increase the light intensity to get a good looking shadow on the "DOM element", but then the Sphere will look a bit too shiny and bright. If I were able to have a dimmer light for the Sphere, and a brighter light for the "DOM element", then I could achieve something more realistic this way, where it would seem to the viewer that there is still only one light. Then this sort of thing can be abstracted away in a higher-level API that makes it seem like there is only one light being manipulated when behind the scene two Three.js lights are actually in play.

**Comment by trusktr** [comment]
@WestLangley 

> As a work-around, can you achieve most of your requirements by having a separate scene for each room (and its lights)?

Do you have a link to an example of something like this? Can it have other unexpected rendering effects on the outcome?

**Comment by makc** [comment]
> other unexpected rendering effects on the outcome?

rendering order of transparent objects, for example - transparent objects in scene 1 will be rendered before opaque objects in scene 2.

**Comment by makc** [comment]
> Do you have a link to an example of something like this?

here, I made one just for you: https://jsfiddle.net/f2Lommf5/524/

**Comment by trusktr** [comment]
> rendering order of transparent objects, for example - transparent objects in scene 1 will be rendered before opaque objects in scene 2.

That makes the workaround only a workaround for limited cases. Looking forward to the real solution!

**Comment by makc** [comment]
well, you could argue that the problem would only happen if you could see opaque objects of scene2 from scene1 trough said transparent objects. but if that's the case, the lights should pass through as well, and there would be no reason to separate the scenes to begin with. but I agree this kind of argument is not really convincing.

**Comment by trusktr** [comment]
@makc Here's an example of the problem I'm trying to solve:

https://discourse.threejs.org/t/how-to-make-shadows-darker-on-transparent-objects/1389

I think selective lighting would really help with this.

**Comment by makc** [comment]
@trusktr I think you can solve that one by altering mrdoob's shadow material. it just shows black-white shadow texture, and you can modify it to be transparent as necessary

**Comment by trusktr** [comment]
Masks in PlayCanvas seem really easy to use selective lighting: https://forum.playcanvas.com/t/set-certain-object-to-not-receive-light/785

**Comment by ErikBehar** [comment]
can we get this merged in ?  I think the shadow problems were due to Lambert shader nothing to do with the change to the code. @tiesselune

**Comment by tiesselune** [comment]
@ErikBehar I was actually looking for something to do this afternoon, I'm going to try to update the code to latest threejs and submit a pull request maybe? I'd actually enjoy knowing I made a real contribution to such a big project. (And good to have confirmation that this bug had nothing to do with my changes)

**Comment by ErikBehar** [comment]
@tiesselune I kinda needed to get this into a project so I went ahead and ported your code over to v93 see: https://github.com/ErikBehar/three.js/tree/selectiveLights   

I can do a PR if you guys wish ? @mrdoob

**Comment by mrdoob** [comment]
@ErikBehar a PR would be great!

**Comment by ErikBehar** [comment]
@tiesselune I'll look into moving it as you suggest, or feel free to push a PR on my fork lol = ] and I'll post the PR soon @mrdoob

**Comment by VaelynPhi** [comment]
What's the status on this? I've merged the r94dev code from @ErikBehar into r94, then merged r97 into it, only a couple very straightforward conflicts (version change, a few variables for selective lighting, and the hash creation in renderers/WebGLRenderer.js; I'd be happy to put in a PR. @tiesselune if you can give me some idea where you intended the selective lighting state to go, I'd be happy to move it, test, and put in a PR.

**Comment by makc** [comment]
@VaelynPhi I'd think that, regardless of whether they are willing to accept @ErikBehar 's code or not, it is good idea to submit the PR, just to replace the outdated one in case other people will want it, like you yourself did

**Comment by ErikBehar** [comment]
Sorry to drop the ball on this guys = / ... @VaelynPhi  can you post your fork / branch  ?

**Comment by VaelynPhi** [comment]
No worries; I understand being busy. Alas, I couldn't get even the branch you had working, @ErikBehar; I settled on reading through the code to try and break it down so I could move the state to the appropriate location and hopefully fix any bugs. I have yet to get to a working port state even on v94. Perhaps I can clean it up and put in the PR just to update it as @makc suggests. Give me a bit; I'm super busy. :) At the very least maybe that'll help highlight the changes that need to be made to pull selective lighting into the recent version.

**Comment by Flyrell** [comment]
Hey guys, what's the status on this one? @tiesselune @ErikBehar Might I help you with something? Would be nice to implement it finally after 4 years 😄💯

**Comment by ErikBehar** [comment]
@flyrell I think we could maybe close this issue since it seems to be closer to done over in #15223 maybe ?

**Comment by ttiimmaacc** [comment]
Is this not yet done or what!? ... 8 years in the making

**Comment by makc** [comment]
@ttiimmaacc it is pretty much "nice to have, but please just use multiple scenes instead"

**Comment by adityakailash0399** [comment]
@makc while using multiple scenes, without setting any background it works fine. But once I change the Background it does not, do you have any idea?

**Comment by gillesboisson** [comment]
Hi, I also checking on the selective light feature for baked / dynamic light system , by mistake I thought it was supported on three js layer, but layers is only camera <> object filter and not light <> object <> camera.
What do you think of this approach, for me it makes more sense than having an extra channel property and it would use bitwise / flags based operation.

**Comment by Ctrlmonster** [comment]
+1 on the need for selective lighting. This would also enable cool stuff via Spotlight texture projection (i.e project fake shadows from a character while not affecting the character itself).

**Comment by FarazzShaikh** [comment]
https://github.com/mrdoob/three.js/assets/55190601/622471b3-5980-41c7-a25d-d5adee0dc11e

Just got this working for Point Lights. Going to make a draft PR shortly. Works by adding uniforms and testing the light mask vs the object mask in shader.

**Comment by Mugen87** [comment]
Since this feature is supported in `WebGPURenderer`, the issue can be considered as fixed. Since we want to focus our efforts on `WebGPURenderer`, `WebGLRenderer` won't support selective lighting. 

`WebGPURenderer` has a WebGPU and WebGL 2 backend and supports selective lighting for both. The respective demo is:

https://threejs.org/examples/webgpu_lights_selective
