### ISSUE TITLE
WebGLRenderer display bug at large sizes

### ISSUE THREAD

**Issue by jhickner** [mrdoob/three.js#5194]
Hello,

I'm running into a display bug at large output sizes with the WebGLRenderer. Fiddle [here](http://jsfiddle.net/jhickner/862de4nj/).

When setting the canvas size (with `renderer.setSize`) to a width or height above 4096, the output begins to distort and the camera appears to go off center. It happens with both Orthographic and Perspective cameras. You can get a feel for what's happening by just changing the width in the fiddle. Above 4096 the effect begins and becomes more and more pronounced as you go up from there.

It looks like everything renders correctly when using `CanvasRenderer`, so I think it's a problem in the WebGLRenderer. 

Thanks!

**Comment by mrdoob** [comment]
I wonder whether we should check `gl.getParameter( gl.MAX_RENDERBUFFER_SIZE );` and `gl.getParameter( gl.MAX_VIEWPORT_DIMS );` at init time and then if `setSize()` is being called with bigger values show an error.

**Comment by Mugen87** [comment]
> I wonder whether we should check gl.getParameter( gl.MAX_RENDERBUFFER_SIZE ); and gl.getParameter( gl.MAX_VIEWPORT_DIMS ); at init time and then if setSize() is being called with bigger values show an error.

We could implement something like this in `setSize()` and `setDrawingBufferSize()`:
```js
var maxRenderbufferSize = capabilities.maxRenderbufferSize;

if ( _canvas.width > maxRenderbufferSize || _canvas.height > maxRenderbufferSize ) {

	console.warn( 'THREE.WebGLRenderer.setSize(): Requested size %ix%i is too large. Maximum size of renderbuffer is %i.', _canvas.width, _canvas.height, maxRenderbufferSize );

}
```
However, this check seems not to work in Chrome since the browser checks for [5760 x 5760 total backbuffer area](https://chromium.googlesource.com/chromium/src/+/0781429bb10a95aae3c9eb3141fc47852cfe300a%5E%21/). Also see latest [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=756347#c12).

It seems that browser behave differently in this context which makes implementing a check like above not feasible.
