### ISSUE TITLE
No image in texture while trying to update

### ISSUE THREAD

**Issue by badjano** [mrdoob/three.js#5206]
line:24428      if ( texture.needsUpdate && texture.image ) {

sometimes the image on the texture is null, I don't know why, so this fixes the error of trying to update it without having any image

**Comment by Mugen87** [comment]
> The method sets the flag for you after the image loads.

This is also true for `TextureLoader.load()`. `ImageUtils` is deprecated since a while.

I guess this one is more a user error than a bug. Manually updating the texture too early (when the corresponding image is `null` or incomplete) is something the users needs to avoid. `three.js` entities like `TextureLoader` should set the flag at the right time.

**Comment by WestLangley** [comment]
>I guess this issue is more a user error than a bug.

Agreed.
