### ISSUE TITLE
CSS3D renderer issue with Firefox 32.0.1

### ISSUE THREAD

**Issue by nebeleh** [mrdoob/three.js#5320]
I have been using WebGL and CSS3D renderer in the same app, but since the latest Firefox update (32.0.1), Firefox doesn't show the CSS3D objects correctly (the rotation is inversed). Everything is fine in other browsers. For example, take a look at this example:

(http://jeromeetienne.github.io/videobrowser4learningthreejs/#Personalized%20and%20Polished%20Text%20for%20Your%20Three.js%20Game%20With%20threex.text)

I'm not sure whether this is a bug in three.js or a problem in Firefox's new release. In the latter case, do you know of a simple way for pinning down the problem so I can post a proper bug report for Firefox?

**Comment by autotel** [comment]
Hey! So I am using the rev 78. The Periodic table of elements looks well after it ends the first tween. I removed the first tween movement, and the transparency of the elements, and the wrong z culling happens. The problem is really weird
![capture](https://cloud.githubusercontent.com/assets/15053243/17616135/6b0e3880-607b-11e6-8862-4def7384804c.PNG)
Then, after the first tween, the z's look all right.
