### ISSUE TITLE
State of damping in OrbitControls.js

### ISSUE THREAD

**Issue by gabrielstuff** [mrdoob/three.js#5369]
Hi !

I've been playing with OrbitControls.js to add some inertia. Thus I've been reading thru the code and the examples and I figure out that in the examples, the OrbitControls is setup with : 

```
controls.damping = 0.2;
``` 
see: https://github.com/mrdoob/three.js/blob/master/examples/misc_controls_orbit.html#L71

But reading thru master and dev, in the OrbitControls.js file, i can't see any trace of damping property.
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/OrbitControls.js

But in the pull request that aded this param it did exist : https://github.com/lpsinger/three.js/blob/21b891af76ab5c7d20b114ab0450c8c2f5f9c6fa/examples/js/controls/OrbitControls.js#L254 

So, what can we do about that ? Adding the damping or not, that is the question !

thanks for the great work.

**Comment by yisk** [comment]
Please, do one of two things:
- Implement damping (inertia) in OrbitControls just like in TrackballControls
or
- Implement axes constraints in TrackballControls just like in OrbitControls
It may seem rediculous, but both of this plugins are totally useless for me, because I need smooth rotation AND axis constraints.
