### ISSUE TITLE
Allow configuring the scaling rate In THREE.TransformControls

### ISSUE THREAD

**Issue by blaise-io** [mrdoob/three.js#5489]
I have a simple editor for 3D models using three.js. This is my camera:

```
new THREE.PerspectiveCamera(30, window.innerWidth / window.innerHeight, 0.01, 10);
```

And this is my mesh's geometry:

```
new THREE.BoxGeometry(0.3, 0.3, 0.3);
```

I'm using THREE.TransformControls to scale the mesh.

Scaling works perfectly fine when meshes have units ~ 100, but when an object is between 0 and 1, scaling is _very_ slow. With _slow_, I mean that when you drag the scale slider half the canvas size, the mesh increases or decreases only a few percentages in size. I don't have this problem with other TransformControls modes. 

This is because there's a the [magic number 50](https://github.com/mrdoob/three.js/blob/1769fbfc6c994b51a54c15a5c096855fd3cb8a1a/examples/js/controls/TransformControls.js#L850) in the code that translates mouse movement to scale.

Can we make this number configurable, and/or make it use a sane default based on mesh size or camera?

[JSFiddle demonstrating slow scaling](http://jsfiddle.net/Lm19u6dj/1)

**Comment by sandromartis** [comment]
There was pull request that resolved this issue by taking the current object scale into account. (#8582)
This makes the scaling rate stay the same for different sizes of objects.

But I still think it would be nice to have a parameter to change the "sensitivity" of the scaling.
I added something like that in our version of the transform controls because the scaling was too fast for us.

I could probably make a pull request with those changes.
