### ISSUE TITLE
Missing Materials on Export from Blender

### ISSUE THREAD

**Issue by amiller27** [mrdoob/three.js#5501]
The exporter script for Blender produces fewer materials in the final JSON than existed in the original model, in some cases.

In particular, the extract_materials function in export_threejs.py does not account for the possibility of multiple materials with the same name on the same mesh.  For example, if the mesh has two materials attached to it and both materials have the same name, extract_materials will only return one material.  This results in the material indices not matching up with the number of materials in the final JSON.  I'm not sure how this could be fixed without reworking the entire handling of materials in the exporter.

**Comment by jpetitcolas** [comment]
Not sure if it is related, but I just exported a simple mesh with no materials, and I had no `materials` key in the output object, which causes some errors when using the JSON loader.

**Comment by repsac** [comment]
I don't know if it is related. Not sure which version of the exporter @amiller27 is referring to because this is kind of an old ticket. 

I also am not sure the context of where the actual problem lies. The exporter allows you to opt out of exporting no materials. So if you don't get a `materials` key that should be expected. JSONLoader logic seems to compensate for a missing `materials` key just fine. I think maybe where you are seeing errors (I have to completely guess based on what little information I have) that in the callback you aren't checking if the second argument is null and if it is create a new material manually. But again without some context on what "some errors" specifically refers to or the details on your work flow I don't have any answers.

If you look at this function
https://github.com/mrdoob/three.js/blob/master/utils/exporters/blender/tests/scripts/js/review.js#L122
You can see where I was working with a use case that my materials were not defined that I created a new array, with a single material, manually.
