### ISSUE TITLE
Cascaded shadowmaps bug

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#5536]
cascaded shadow maps used to work in r68, after moving onto r69 they stopped. Here's what i see in:
http://threejs.org/examples/#webgl_morphtargets_md2_control
![2014-10-28 20_33_34-three js - examples](https://cloud.githubusercontent.com/assets/5939063/4816706/f5c32154-5ee1-11e4-81ff-75dab894a5e6.jpg)
No shadows to be seen on the ground. Strangely, there is correct self-shadowing. Problem in material shaders?

Browser: Chrome Version 38.0.2125.104 m
GPU: nvidia gtx 660 ti
Graphics Driver: 344.48 WHQL (22/10/2014)
OS: WIndows 8 x64

**Comment by arya-s** [comment]
I'm playing around with this, and the firs thing I did was to use the new ```THREE.ShadowMapViewer``` to display the shadow map of each virtual light to see if the problem lies in creating the shadow maps or somewhere else.

I did that by introducing an array in ```THREE.ShadowMapPlugin``` that stores the virtual lights. However, when I added light's I accidentally used ```Array.add()``` (which does not exist in JS) instead of ```Array.push()```. I ran the code and magically shadows appeared correctly. When I noticed my error, I fixed it and used ```Array.push()``` and shadows disappeared again.

So introducing any kind of error in this line: https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/plugins/ShadowMapPlugin.js#L125

(I simply added this line: ```a.a();```)

makes CSM work again.....

![CSM works](http://i.imgur.com/57Bh4Cw.jpg)

On the bright side: shadow maps are created correctly, so the issue is somewhere when rendering the shadows. Here without the above introduced error:

![CSM doesn't work, shadow maps are OK](http://i.imgur.com/ezyt2bK.jpg)


So now we just need to find out what code is prevented from running when that exception happens, and prevent it, right? That should fix it?

**Comment by arya-s** [comment]
Live examples:

Without error: https://dl.dropboxusercontent.com/u/22156580/r71/withoutError/examples/webgl_m.html
With error: https://dl.dropboxusercontent.com/u/22156580/r71/withoutError/examples/webgl_m_err.html

**Comment by mrdoob** [comment]
Interesting finding! Here's something that bring us closer to the problem...

Leave the `ShadorMapPlugin` code as it was, and in the `webgl_morphtargets_md2_control.html` add the ground like this `setInterval( function () { scene.add( ground ); }, 0 );`.

**Comment by arya-s** [comment]
Ugh, that complicates everything @mrdoob ... I was hoping the issue is just in ```THREE.ShadowMapPlugin```.

**Comment by titansoftime** [comment]
Very exciting, I'm glad this is being looked into. Related Question: I'm assuming cascading shadowmaps have an increased performance hit vs standard yes? A 3x cascade would be 3x as expensive or no?

**Comment by arya-s** [comment]
Yes, roughly 3x the cost of normal SM.

**Comment by Usnul** [comment]
in theory you can use stencil to save on performance. Stencil out what is outside of camera's frustum, also stencil out areas in further cascades which are covered by closer cascades.

**Comment by mrdoob** [comment]
Cascaded shadow have been removed.

**Comment by Usnul** [comment]
They are just about the most used type of shadow mapping for games, so it's a real shame. CSM may cost more in terms of performance than standard shadow maps, but they bring good shadows to just about any scene, all you need to do is set up clipping planes, the rest just works like magic. With static maps it's artistry to get maps to work on larger scenes, and usually involves just upping resolution to whatever hardware can handle.

**Comment by mrdoob** [comment]
I'm open for PRs adding them back, but no one was maintaining, nor understanding, the old code.

**Comment by titansoftime** [comment]
> With static maps it's artistry to get maps to work on larger scenes, and usually involves just upping resolution to whatever hardware can handle.

This is precisely my situation.

**Comment by TrentWDB** [comment]
Are there currently any new alternatives to cascading shadow maps? Since this post is around a year old I'm hoping that something has been developed since then.

**Comment by mrdoob** [comment]
Unfortunately not.

**Comment by Usnul** [comment]
I can share my code for a view-space projected shadowmap, built on top of THREE.js, simply a controller for shadow camera, fed by a view camera as a parameter. It's a 1-cascade cascaded shadowmap :)

it serves my needs. You can see it in use here: http://server1.lazy-kitty.com/komrade/ (just don't zoom in too close, clipping plane code is wonky).

**Comment by TrentWDB** [comment]
That would be really helpful Usnul, thanks!

I'll send you an email so we don't spam the members of this thread.

**Comment by Fyrestar** [comment]
http://dev.theomader.com/cascaded-shadow-mapping-1/

It also fixes a major issue with the implementation we had (last page) making sure there is no visible pixel movement. I restored the source from cache (googles repo site is closed), i'm too busy recently, if anyone wants to give it a try tell me if you need the source.
