### ISSUE TITLE
Is SceneLoader really going to become deprecated?

### ISSUE THREAD

**Issue by rohan-deshpande** [mrdoob/three.js#5560]
From reading this issue https://github.com/mrdoob/three.js/issues/4259 and @mrdoob's answer, I'm taking it to mean that the `SceneLoader` is going to become deprecated. I'm wondering about this, because currently I am able to confidently export JSON from Blender into Three using the `SceneLoader`, while trying to switch to the `ObjectLoader` throws errors. 

Here's my JSON http://pastebin.com/18Mb7AyY

It makes sense to me to have separate loaders for scenes and objects, so I'm not too sure why this would become deprecated.

**Comment by jeum** [comment]
Hi

Trying to load a scene with exported models I also wonder why SceneLoader.js is deprecated since ObjectLoader.js can not achieve this (there's no addGeometryHandler). Moreover you diffuse a curent/actual SceneLoader example wich works with deprecated/SceneLoader.js.

So I wondered what it means, what you plan for this one ... Can we count on SceneLoader.js or is it a wrong way ?

**Comment by mrdoob** [comment]
Eventually `ObjectLoader` will support that too. It just takes time... Deprecating something means that you don't plan on spending energies on supporting that code, instead you're focusing on building a better designed code instead.
