### ISSUE TITLE
Reusable repeating textures: natural height/width

### ISSUE THREAD

**Issue by dhasenan** [mrdoob/three.js#5674]
I have a repeating texture -- brick wall -- that I want to apply to a large number of objects -- different sized walls. I want the texture to appear at the same scale every time. Three doesn't make this easy.

Right now, three allows me to specify the number of times the texture repeats on any surface it's applied to. This means I need to load the image, configure its natural scale (one repeat == 4.0 units vertical and 2.0 units horizontal, for instance), and stash that away in my own code. Then, when it's time to apply that to a wall, I look at the dimensions of the wall I'm applying it to, create a Texture and a MeshBasicMaterial from that, create a new array of materials to apply to that BoxGeometry, and then throw all that away because I can't reuse it on the next wall.

That's about eight allocations per BoxGeometry and a couple dozen lines of code. Or it's a lot of data that I have to precalculate and store somewhere. Fortunately, I only have to do this when the scene geometry changes, but still, that's not happy-making.

The natural way of specifying a repeat would be to say what surface area a texture takes up. My brick wall texture is 2m == 4.0 units tall and 1m == 2.0 units wide. Tile it the appropriate number of times for this surface and don't bug me for every little detail.

**Comment by MEBoo** [comment]
@mrdoob any news/alternative about?
@titansoftime this solution is good for simple geometries, but what about for imported ones?

I have many materials each one with its own measure, to be applied tiled to many imported geometries with 10000 faces each. 
Better explanation: the user can choose/change the material of an imported OBJ mesh, and each material has its own tile size while each OBJ has many faces with different sizes.

So I think this topic marked as suggestion is the only way to do that

**Comment by Mugen87** [comment]
> The cloned textures share the same loaded image.

Yes, but with the current code the engine uploads the texture multiple times to the GPU not just once, see #5821.

However, cloning textures in order to configure different texture transform settings is the intended workflow. I hope it can properly be supported when #17766 is solved. 

> this solution is good for simple geometries, but what about for imported ones?

There will be no solution by the engine that can automatically handle all possible geometries. It's best to author proper uv-coordinates at design time when possible. Otherwise you need a manual task like mentioned in https://github.com/mrdoob/three.js/issues/5674#issuecomment-64421443 although this gets complicated for more complex geometries.
