### ISSUE TITLE
Material Loader Skipping Textures Paths

### ISSUE THREAD

**Issue by Sneagan** [mrdoob/three.js#5765]
I found this when loading objects exported from Clara.io. It appears that the [Material Loader](https://github.com/mrdoob/three.js/blob/master/src/loaders/MaterialLoader.js) doesn't load the texture paths in materials, resulting in geometry loading without textures.

**Comment by Xantomen** [comment]
Hey guys, I'm probably late to the party but I didn't know this ticket was in place and made a silly little hack just to test that the problem was definetly on the ThreeJS side, and could be solved. I guess it's the same way Sneagan originally solved the problem, but anyway. I'm not skilled or knowledgeable of ThreeJS enough to make a implementation worth commiting, so just announcing to you that for now I'm presenting this hack around as a temporary solution for people that encounter the problem and sincerely don't know what to do / don't want to hardcode the textures in / don't want to do even dirtier hacks (like making the materials be named the same as the textures before exporting, then for-loop to create mesh and use materials.name as texture path).

My hack is in this post: https://forum.clara.io/t/exporting-models-with-materials-not-working-in-three-js/1566/7 

Thanks a lot for all your work and dedication, you really are doing incredible stuff with this.

**Comment by Mugen87** [comment]
Closing this issue. As mentioned here https://github.com/mrdoob/three.js/issues/12613#issuecomment-583721189, `MaterialLoader` is not responsible for loading textures. Since `ObjectLoader` is internally using `ImageLoader` for loading/deserializing images, it should be possible to process data URLs as well as ordinary ones. We can reopen the issue if complete JSON file is shared that demonstrates the issue.
