### ISSUE TITLE
Mesh simplification function

### ISSUE THREAD

**Issue by BjornMoren** [mrdoob/three.js#5806]
It would be useful to have a mesh simplification function in Three.js. I have noticed that some external libraries, for example the ThreeCSG.js, create meshes with lots of unnecessary triangles, which could be optimized away, since they are co-planar and adjacent.

Perhaps a useful way to implement this would be to define a new kind of mesh that is a list of 2D Shapes and their 3D plane and 3D position. Then add functions that convert regular meshes to and from this format.

**Comment by bhouston** [comment]
@zz85, that is awesome.  Now the primary way to choose edits is based on quadratic error metrics as described in this paper: http://www1.cs.columbia.edu/~cs4162/garland97.pdf

**Comment by bhouston** [comment]
The other things you can do, @zz85, is to have your modify take a list of edges to collapse at once.  Just ensure that they are not overlapping.  This will greatly improve the performance.

**Comment by zz85** [comment]
That was using Paul Bourke's approach. I haven't look at the details of these paper, but I also tried S Melax's approach for three.js which works reasonably fast. I have got an example coming, but will need a little time to clean them up.

**Comment by zz85** [comment]
Here's the experiment for my js port of Stan Melax Progressive Mesh type Polygon Reduction Algorithm. http://jabtunes.com/labs/3d/bunny/ Might probably need to modify this a little before a pull request.

![shrinking_bunny](https://cloud.githubusercontent.com/assets/314997/5696123/00b91734-99fd-11e4-9490-57ba42dd7c72.gif)

**Comment by bhouston** [comment]
@zz85 That is sweet!

I can not believe how fast it is.

It is weird that the plane shrinks when one optimizes it, but I guess that is called "preserve borders" and it is often an option.  I notice you have "isBorder" in the code, but I have a hard time understanding it -- usually one considers edges to be border edges if they only have one adjacent face, but it looks like you are doing border vertices which I think is difficult to figure out if you do not know which edges are borders (I think the definition of vertex borders are vertices that are part of a border edge.)  I actually had a bit of a problem figuring out the logic of that isBorder check.

There is already a Triangle class in THREE.js here, that I think you can repurpose (as it is very very similar) rather than creating a new one:

https://github.com/mrdoob/three.js/blob/master/src/math/Triangle.js

PS. I find that the slider doesn't work if I jump directly to a new level rather than slide it.

**Comment by bhouston** [comment]
Ah, I see that the Triangle structure you have created is sort of like a winged edge structure -- something with pointers between vertices and faces.

Those are really hard to maintain and scale I have found in the past.  But maybe that is where you get your speed.

**Comment by zz85** [comment]
@bhouston - indeed the data structure used by Stan Melax is pretty interesting particularly the way it sorts the faces by order of removal. Actually the reduction process is ran only once and cached - so its really fast to see the faces "collapsing" when the slider is move.

there is definitely more to play around with the algorithm - particularly the way the vertex removal cost is estimated should be able to give different interesting results.

**Comment by bhouston** [comment]
My concern about memory usage is because the place where mesh simplification is most needed is on large meshes -- meshes with 50,000 or 100,000 or 500,000 vertices.  Maybe you can try with a larger example?  I suspect it is probably as good as it gets.  I do still think the isBorder function is slightly wrong.

Some code review if you want it -- I would call ```vertex.neighbors```, ```vertex.adjacentVertices``` to be clearer in the code.  I am more used to the term adjacent than neighbors: http://mathworld.wolfram.com/AdjacentVertices.html
I wonder if there is a better term than just ```vertex.faces``` to clarify that those faces contain the vertex in question.  I'd also call ```vertex.cost``` to be ```vertex.collapseCost```  I'd use the Triangle.normal calculator here rather than writing a new one: https://github.com/mrdoob/three.js/blob/master/src/math/Triangle.js#L18  It should just be plug and play.  This snippet ```if ( f.v1 ) f.v1.faces.splice( f.v1.faces.indexOf( f ), 1 );``` and a similar line should probably be a function called removeObjectFromArray or something like that.

But I see that you are not copying around vertices, so that is amazing, and your structure remembers the original vertex ID, so that should be really useful.

Maybe move the changeLOD function into the modifer code as a static function or something -- then it is easier to call from elsewhere.

**Comment by gravi2** [comment]
@zz85 Thanks for your efforts on SimpleModifier. I tried to use it on a TubeGeometry& SphereGeometry but the vertices remained the same after using the modifier. Here is a quick codepen. Am I missing something?
http://codepen.io/gravi2/pen/PqXbqg?editors=001

**Comment by thejmazz** [comment]
@gravi2 I forked your pen and got it to work on a sphere. The trick is that `SimplifyModifier` returns some sorted of special object which can be used to generate different detailed versions of the model. I was able to get the sphere to change, though I do not know how to use the object returned by `simplify.modifiy(geometry)`. I tried out the `updateLOD(k)` stuff from @zz85's example, but couldn't figure it out. [http://codepen.io/thejmazz/pen/RWeyJr?editors=001](http://codepen.io/thejmazz/pen/RWeyJr?editors=001)

Two screens from before I forked:
<img width="1680" alt="screen shot 2015-11-08 at 4 35 59 pm" src="https://cloud.githubusercontent.com/assets/1270998/11023053/27b3515c-863c-11e5-99f9-37bfc771255f.png">
<img width="1680" alt="screen shot 2015-11-08 at 4 36 40 pm" src="https://cloud.githubusercontent.com/assets/1270998/11023055/33c1ef58-863c-11e5-96f3-41a798170391.png">

**Comment by samteb** [comment]
Hi everybody,

I have an issue with SimplifyModifier.js created by zz85.

I have a text with 3276 vertices and 6494 faces that I want to subtract from another geometry product using ThreeCSG.js

When I convert the text mesh into new ThreeBSP text, it creates a BSP tree with 1609 polygons which is huge and it has an impact on the subtraction time (between 45s and 1mn).

My idea was to reduce the number of vertices and faces to reduce the number of polygon to be converted. 
However, it seems that the code I tried to implement doesn't work when I fix the k parameter of the changeLOD function under 0,67: the text is visible in the viewer but the other geometry completely disappear. 

Last weird thing is that when k=0,67 the subtraction is a little bit faster but when I checked the object into the developer tool the number of polygons is still the same. There is an explanation to that ?

Ask me if you need further informations and thank you for your help !

**Comment by samteb** [comment]
Hello again everybody,

To answer to my own question ...

I had just to change the EPSILON parameter into ThreeCSG.js which was too small (1e-5).

With EPSILON = 0.03, the subtraction time execution falls to 3s.

**Comment by pineliu** [comment]
Hello,

Is there a version of the SimplifyModifier.js included in the library? The link that @zz85 provided does not work anymore. Thank you very much!

**Comment by mrdoob** [comment]
New link:
http://blurspline.com/labs/3d/bunny/

**Comment by zz85** [comment]
Apologies for abandoning this thread for sometime. Since @mattdesl pinged me on this, here's some updates

- With regards to scale @bhouston, some initial measurement shows that it takes about 2-3ms to reduce a single vertex. https://twitter.com/BlurSpline/status/741625571432534017/photo/1 
- From my rough estimates to reduce a geometry by 1000 vertices might take 3s, 10000 vertices might take 30s, 100K vertices might take 5 minutes.
- I haven't looked into optimization of the code yet, and I do not have comparison to how other algorithms work so I don't have a gauge to whether how fast or slow this is.
- The first time I'm trying to do is first get my code to run with the current three.js version. It might require me to work with BufferGeometry instead, so I'll try to see how it goes.

**Comment by zz85** [comment]
@bhouston re border preservation - you may have got a point though it seems to me that there's a different issue in the polygon reduction implementation. Stan's algorithm works by picking the least cost (direction sensitive) edge to collapse. When an edge is selected, a vertex is removed. However, the vertex may be connected to other high cost edges (eg borders). The seems to be why it isn't working great for planes

I've tried a different approach of averaging the edge costs at each vertex instead and seems like I have some initial successes. Will try to play around more and see....

**Comment by saabi** [comment]
@zz85 I'm working on a similar project and I've also ported Stan Melax's code to Typescript. I also intend to use a BufferGeometry, but my priority is to code texture coordinates as part of the vertex split data structure.

Perhaps we can collaborate?

**Comment by mrdoob** [comment]
#9159

**Comment by whatisor** [comment]
Hello,
Can you explain what condition for geometry to apply Simpififer?
I often get the error: THREE.SimplifyModifier: No next vertex

**Comment by Mugen87** [comment]
@whatisor Please use stackoverflow or the [forum](https://discourse.threejs.org/) for help requests.

**Comment by DVLP** [comment]
I added textures support and just came back a couple of days ago to add normals support so normals don't have to be recalculated after optimisation

![image](https://user-images.githubusercontent.com/5261364/50553108-cec32000-0c97-11e9-9883-94ccfb7bbade.png)

Here's my playground https://codesandbox.io/s/2o51o1q27p

Press "optimizeModel" to recalculate

For development purposes I added drag and drop for 3DS, DAE, FBX so you can just drop files where the Elf figure currently is and see how other models are working with this

**Comment by DVLP** [comment]
I've rewritten the whole thing to remove Vertex and Triangle custom classes and turn all data into flat typed arrays with SharedArrayBuffers to support workers and sharing memory.

https://codesandbox.io/s/qvx30mkzo6

Each worker gets it's range off vertices to process. Number of vertices / total workers * current worker

Race conditions in workers and general mess of early prototype make optimisation fail sometimes and "optimizeModel" has to be clicked to try again. workersAmount in line 1379 sets amount of workers(defaults to navigator.hardwareConcurrency) 
FIELDS_NO sets amount of fields for faces and neighbours belonging to each vertex(these are 2 flat arrays. Their length: number of vertices * 50 fields for data each), currently it's set to 50 but it also works with 20 or 1000, there's also support for oversized fields in separate arrays. These arrays are being copied instead of shared when creatigs workers so this needs improving.

Without stopping rendering in Codesandbox
Tested 22MB model with 225k vertices on 2 years old XPS 15 with i5 6300hq 4 cores and no hyper threading
main thread only - 120 seconds
1 worker - 120 seconds
2 workers - 33 seconds
3 workers - 21 seconds
4 workers - 14 seconds 

On my PC with 16 cores works in 4-5 seconds when using 8 workers

Due to security problems SharedArrayBuffer was disabled in Chrome for a while but now it's enabled by default.

**Comment by DVLP** [comment]
Updated the previous one because I broke the last version https://codesandbox.io/s/1zz4rrm337

Loading BufferGeometry without conversion to Geometry https://codesandbox.io/s/7yr886oo30
The result is weird because there's too much focus in some(look at the face) areas and some others remain untouched.

**Comment by mrdoob** [comment]
Very nice! At that speed this could be used for quickly generating LODs.

**Comment by DVLP** [comment]
Performance is the entire purpose of my work. I've been building this game and engine built on top of Three.js (https://bad.city and https://editor.bad.city) for a while and noticed that generating LODs for larger maps is blocking next downloads(currently using SEA3D format so additionally, after downloading files must be LZMA unpacked). Delegating the optimisation to the workers allows the main thread to start downloading next files and already loading time is 2x faster. The next step is to use a pool of workers so multiple objects can be optimised at once. Currently multiple workers can work simultaneously on one object but not on multiple objects at the same time. For games with real budget it's better to have manually optimised LODs but for prototyping automated optimisation saves time and money.

**Comment by saabi** [comment]
I used edge length indexing on a private version of the simplifier to give about a two orders of magnitude speedup. With some time I could isolate that code and integrate it into this implementation.

**Comment by DVLP** [comment]
That would be awesome, I'm very curious how much faster this can go. With SharedArrayBuffers all workers can have access to one edge length index array or even initial calculation could be split between them

**Comment by DVLP** [comment]
https://codesandbox.io/s/xrlplpmr1q fixed problems with very distorted mesh when loading BufferGeometry directly without Geometry

**Comment by saabi** [comment]
@DVLP I'm short on time, would you like to look at my code, which is very related to this simplifier, and analyze if you find it worth duplicating the indexing code that speeds up simplification?

I would give you access to the repo in that case.

**Comment by DVLP** [comment]
@saabi currently my game engine requires million other things and I also work full time but I can take a look. If I'll feel inspired I will spend some time reimplementing your solution in my sandbox too see if the speed increase will be great.

**Comment by yazancash** [comment]
Thank you @DVLP . i used your code after some edits to fit my project. [here example](https://rigmodels.com/3d_LOD.php?view=5OOOEWDBCBR630L4R438TGJCD).
