### ISSUE TITLE
Arcs does not go from start to end

### ISSUE THREAD

**Issue by Pitel** [mrdoob/three.js#5817]
See http://jsfiddle.net/qjonmmee/12/

The segments are not connected, but they should be.

Changing `curveSegments` on line 24 changes the start and end of the arc, but it shouldn't.

**Comment by dubejf** [comment]
The problem seems to be that the contour curve of each annular sector is interpreted as a single continuous curve, not as four distinct arcs with four hard corners. When the shape is discretized, it does not honor the end points. The true corners are clipped, creating a gap between the sectors. The gap shrinks as you increase the density with `curveSegments`.

I don't know if there if there is a way to specify the `Shape` that will preserve the end points of the original curves during discretization. Even if there is no other way, this seems more like a limitation of the library rather than a bug.

**Comment by WestLangley** [comment]
Closing as this is now outdated.
