### ISSUE TITLE
TypeError: array[i].call is not a function - threejs: 7105

### ISSUE THREAD

**Issue by yokotsumo** [mrdoob/three.js#5846]
I upgraded thre.js and OrbitControls.js to the latest version (r69) and each time I use the mouse, I have the following error in the console: 

TypeError: array[i].call is not a function - threejs: 7105

This is link to the 'change' event.
The controls on screen are working find but this error did not appear before.

**Comment by cipri-tom** [comment]
I think this is a bug in how `dispatchEvent` works, because if you pass an object that implements the `handleEvent` function, that function should be called, with the object as a context (detailed [here](https://www.thecssninja.com/javascript/handleevent))

So instead of saying [`.call`](https://github.com/mrdoob/three.js/blob/8f0a1c50483d4ec78c3f482bd7768b5333d4abdb/src/core/EventDispatcher.js#L82), it should say `.handleEvent`, which for functions would just invoke them.
