### ISSUE TITLE
Three.js for mobile development - webview - phonegap

### ISSUE THREAD

**Issue by APdevelopments** [mrdoob/three.js#5885]
Hi,
Sorry about trivial question, I'm new to 3d design and three.js library.

I want to create app with three.js (need to show some path), but also I need to convert my app into native app with phonegap. Phonegap use webView on android and webview DONT support weGL, but support well css3 3d functions.

So can I use three.js library to make 3d objects and animation but just with css3 so I dont need and I cant to use webGL.

Is there some example where is just 3d with css NOT webGL. Is it possible to use just css3 3d for creating objects?

**Comment by yomotsu** [comment]
This board is for [bugs and feature requests](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md). If you need help, please use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Anyway, three.js supports CSS3D Renderer as well. But it's limited and slightly different. Because CSS 3D is just for kinda layout, and not for graphics.

See

- http://slides.com/zz85/cssconf-2014#/

and

- http://threejs.org/examples/#css3d_molecules
- http://threejs.org/examples/#css3d_panorama
- http://threejs.org/examples/#css3d_periodictable
