### ISSUE TITLE
EdgesHelper not work as expected

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#5895]
I has some small code using EdgesHelper to show outer edges only.
var edges = new THREE.EdgesHelper(mesh, 0xffffff);

However, it only works with 1 model, others are NOT ( it shows full edges in same way with WireframeHelper)
Working file: http://www.fast-files.com/getfile.aspx?file=84658
Non-workign file: http://www.fast-files.com/getfile.aspx?file=84659

I am using r69 version.
Thank you.

**Comment by WestLangley** [comment]
There are problems with your model.

1. Your face normals are zero. They are required for `EdgesHelper`. Call `geometry.computeFaceNormals();`

2. Your model has back-to-back faces. This is evident because your face and vertex normals point both inside and outside the model. You have about twice as many faces as you should.

You need to repair your model.

**Comment by whatisor** [comment]
Thank you, you saved me :)
