### ISSUE TITLE
Dealing with drawingBufferWidth and drawingBufferHeight

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#5917]
So, apparently many WebGL samples including three.js samples are broken on Safari and Chrome on the new iMacs with 5k displays.

The issue is the apps request a fullscreen canvas which is 5120x2880 but Chrome and Safari often return a 4096x2880 canvas. [See bug report](https://code.google.com/p/chromium/issues/detail?id=445542). So what happens is because the app asked for 5120x2880 it sets the `gl.viewport` to that but because the drawingBuffer is actually 4096x2880 it's the wrong viewport setting (and the wrong aspect ratio given the way most of the examples are not using clientWidth/clientHeight) and so the samples don't work.

As it says in the bug this is spec compliant. Basically you can ask for a canvas of any size and WebGL will do its best but the size you actually get is in `gl.drawingBufferWidth` and `gl.drawingBufferHeight`. 

**The question is, should three.js and the examples change to handle that?**

Basically after you call `renderer.setSize` you need to check what size you actually got by checking `gl.drawingBufferWidth` and `gl.drawingBufferHeight` (could be some func like `renderer.getSize`) and then use those values in your code where appropriate. At the same time you should use `gl.canvas.clientWidth` and `gl.canvas.clientHeight` for your aspect ratio because the two won't match

NOTE: If you're curious why it's this way imagine you have a machine with 3 monitors side-by-side. Take any three.js sample and resize the window until it crosses and fills all 3 monitors. Let's assume the monitors are 1920x1080. You'll now have a window that's 5760x1080. The code will ask for a canvas 5760x1080 but the driver likely has a limit of 4096. So, rather than crash the spec says the canvas will have its width set to 5760 (so it fills the area of the page it's supposed to fill) but WebGL will make drawingbuffer whatever size it can. In this case probably 4096x1080.

Apparently they will look into the issue and see if they can make it return the fullsize on iMac 5k more often but (a) I went into the Apple store to test. It's not a hard coded limit AFAICT. Sometimes the samples work. Other times they don't. That suggests is a memory issue. 5120*2880 is 56meg. Antialiased that's at least 112meg, it's double buffered so that's 168meg, and then there's all the compositing tiles (b) even if they fix it so it happens less often it can still happen if your system is low on memory or if you have multiple monitors so it's still worth considering.

Thoughts?

**Comment by mrdoob** [comment]
Should be consider removing `camera.aspect`? Or defaulting it to `null`? That way we deal with things like this automatically. But I don't know if this would mean having to compute the `projectionMatrix` every frame...

Alternatively, we could indeed have a `renderer.getSize()` so people can deal with this issue.

**Comment by mflux** [comment]
Running into this very issue, in an unusual project that has 8 displays horizontally (1920x1080), a list of observations:

* Past 5760 pixels the canvas begins to get "stretched", eg one pixel will start taking up two or more pixels
* As mentioned, aspect ratio becomes incorrect
* renderer.setViewport / setScissor no longer causes renderer to paint at the right areas
* Canvas is still the correct size, all things considered

**Comment by greggman** [comment]
I don't think you have to hack anything for most apps. In your own code do something like 

        camera.aspect = renderer.domElement.clientWidth / renderer.domElement.clientHeight;

For viewport assuming you want the entire canvas do this

        renderer.setViewport(
             0, 0, renderer.context.drawingBufferWidth, renderer.context.drawingBufferHeight);

For scissor your kind of on your own. You could try normalizing like
        
        renderer.setScissor(
             x * renderer.context.drawingBufferWidth / renderer.domElement.clientWidth, 
             y * renderer.context.drawingBufferHeight / renderer.domElement.clientHeight,
             width * renderer.context.drawingBufferWidth / renderer.domElement.clientWidth,
             height * renderer.context.drawingBufferHeight / renderer.domElement.clientHeight);

If you need the same dimensions for the viewport do the same normalization.

Give it a try, tell me if it works.

**Comment by mflux** [comment]
Well, this is "fixed" by using Firefox ;)

**Comment by greggman** [comment]
You should file a bug at http://crbug.com to make sure they know you needed to switch to firefox for high end 3d apps :P 

Otherwise you can see on http://webglstats.com that a lot of high end cards go up to 16384 across. That's just barely enough for 8x1920 which is 15360. I guess Chrome (probably inherited from WebKit) has some artificial limit.

**Comment by mflux** [comment]
Good call, I've added to the same issue so as to not create a duplicate ticket. 

There is indeed a max 16384 across limit, and we actually need 9 screens so that breaks this limit (17280). The solution is to use a 3x3 configuration and position the viewports accordingly. This is bad with full screen shaders ofcourse, however that's a totally different issue.

**Comment by greggman** [comment]
Should probably take it off this thread but can you use [a solution like this](http://webglsamples.org/aquarium/README.html)?

**Comment by mflux** [comment]
That would be the backup solution, we're probably going to split it across two machines so yeah. Thanks for your input... back on topic!

**Comment by Mugen87** [comment]
Because several users had problems with WebGL + Ultra-HD resolutions on Chrome, i want to provide a short status update to this issue: 

Chrome has a built-in drawingBuffer limit of 4096x4096. If you allocate a higher size via `renderer.setSize` or via `devicePixelRatio` parameter, you will get a distorted image. I discovered this bug last year and reported it at the Chromium Project: [WebGL High-Resolution Problem] (https://code.google.com/p/chromium/issues/detail?id=445542). Finally after several month we have a fix in Chrome Canary which changes the limit from 4K per dimension to 4K x 4K total area. So 5K resolutions (see iMac 5K) should't be a problem any longer.

But it's important to keep in mind, that higher resolutions than 4K x 4K total area will still be a problem in Chrome. When you check out the history of the mentioned chromium issue, you will see that removing the limitation of the drawingBuffer caused problems with some graphics driver (GL_OUT_OF_MEMORY).

Because the bug is still open, i think we can expect even larger canvases in Chrome in the future. Maybe it's a smart idea, to refer to this github issue from other threads like [WebGLRenderer display bug at large sizes](https://github.com/mrdoob/three.js/issues/5194).

**Comment by Mugen87** [comment]
Let's focus on #5194
