### ISSUE TITLE
Dispose before groupsNeedUpdate

### ISSUE THREAD

**Issue by patrickFuerst** [mrdoob/three.js#5957]
Since groupsNeedUpdate initializes new buffers, dispose has to be called to delete the old ones.
Wouldn't it be better to deallocate geometry buffers automatically when groupsNeedUpdate is called ?

**Comment by mrdoob** [comment]
Well, `dispose` deletes the whole buffer. `groupsNeedUpdate` just update them.

**Comment by patrickFuerst** [comment]
When I debug my OpenGL  state I see that every time I call groupsNeedUpdate new buffers are allocated and the old ones still remain in memory.  The same happens with the webgl_objects_update example.

**Comment by mrdoob** [comment]
Oh. True that... Hmmm, I'll have to take a look at this part of the code...

**Comment by WestLangley** [comment]
> The same happens with the webgl_objects_update example.

Maybe @gero3 has some ideas.

It would also be nice if someone who understands this feature would update the [wiki](https://github.com/mrdoob/three.js/wiki/Updates) and the `THREE.Geometry` docs.

**Comment by gero3** [comment]
Actually the reason why the buffers stay in memory is because three.js store the buffers on the geometrygroup object and groupsNeedUpdate overwrites the list of geomtrygroups with a new list of  geometryGroup objects for a geometry. So the old buffer objects are unreachable after a groupsNeedUpdate.

[The recreation of geometrygroup without removal of buffers](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L3830-L3834)
[The check which doesn't see the old buffers](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L3848)

Actually 2 solution come to mind: 
- Implement [Buffers ](https://github.com/mrdoob/three.js/pull/6062#issuecomment-74173390) and store the buffers in geometry and update those accordingly to the new geometrygroup.
- Adapt make groups to reuse the current geometrygorups
