### ISSUE TITLE
Blender exporter use_cast_shadows error

### ISSUE THREAD

**Issue by mese79** [mrdoob/three.js#6008]
Hi
I've just tested the new blender exporter(r70) with blender 2.69 and a pretty simple scene and i've got this error on export:
    
    'Material' object has no attribute use_cast_shadow
    
Is it a bug or i did something wrong?
Thanks.

**Comment by repsac** [comment]
I suspect there is something up with your scene. I grep'd for `use_cast_shadow` and only found this

```
11:40 ~/work/repos/three.js/utils/exporters/blender/addons/io_three
$ find . -name "*.py" | xargs grep "use_cast_shadow"
./exporter/api/object.py:            return data.materials[mat].use_cast_shadows
```

`use_cast_shadows` is a standard material attribute in Blender
```
# In the Blender Python Console
>>> D.materials[0].use_cast_shadows
True
```
![use_cast_shadows](http://i.imgur.com/uG9nJOu.png)

Not really sure what is causing this. I noticed that your error ends with `shadow` and not `shadows`, did you past the whole error by chance? Also check your shell for the log file, when an export is successful it prints ```Log: <some path to $TMP>``` or if there is an error ```Error recorded to <some path to $TMP>```. The logs tell way more than Blender does. Use pastebin for sharing the logs.

**Comment by mese79** [comment]
Python console gives me the same error:
    
    >>> D.materials[0].use_cast_shadows
    Traceback (most recent call last):
      File "<blender_console>", line 1, in <module>
    AttributeError: 'Material' object has no attribute 'use_cast_shadows'
    
This must be the changes through blender 2.69, here is Material class in 2.69: [Material Class](http://www.blender.org/api/blender_python_api_2_69_1/bpy.types.Material.html#bpy.types.Material)
It has different properties like *use_cast_approximate*, *use_cast_buffer_shadows*, *use_cast_shadows_only*, *use_only_shadow*, *use_shadows* and *use_transparent_shadows* for shadows. but i guess **use_cast_shadows* must be replaced by **use_shadows** in order to exporter works in blender. i'll try.

**Comment by mese79** [comment]
Alright, i've made two changes and so far export is done!
io_three/exporter/api/object.py line 74:
    
    return data.materials[mat].use_cast_shadows
    # replaced by
    return data.materials[mat].use_shadows
    
And another change in io_three/exporter/base_classes.py line 17 (when object has no vertext color an error happend):
    
    def __setitem__(self, key, value):
        # add following condition
        if value is None:
            return
        if not isinstance(value, constants.VALID_DATA_TYPES):
            msg = 'Value is an invalid data type: %s' % type(value)
            raise exceptions.ThreeValueError(msg)
        constants.BASE_DICT.__setitem__(self, key, value)

**Comment by repsac** [comment]
Replacing `use_cast_shadows` with `use_shadows` isn't correct (mouse over these properties in the Blender UI to read the help docs). This is because `use_shadows` is what determines if a material receives shadows, this is indeed not the same as `use_cast_shadows` which is what allows a shadow to be casted. In fact `use_shadows` is already being used in the `receive_shadow()` function while `use_cast_shadows` is used in the `cast_shadow()` function. These are the function calls used to determine the shadow attributes of an object for `three`.
Reference: https://github.com/mrdoob/three.js/blob/master/utils/exporters/blender/addons/io_three/exporter/object.py#L84

> And another change in io_three/exporter/base_classes.py line 17 (when object has no vertext color an error happend):

What I should do is handle the geometry parsing in `geometry.py` smarter by not trying to set keys with a `None` value. Using
```
    if value is None:
        return
````
is really quite implicit and I don't like having a value quietly being skipped from being assigned to a key. I actually relied on the tracebacks heavily during development to help me debug test cases when I knew that there should be indeed a valid data type returned. Even updating `geometry.py`, to test values before setting keys, means adding logging so that the attributes aren't not being skipped quietly.

> I've just tested the new blender exporter(r70) with blender 2.69 

I believe this is the root of the problem. The sometimes drastic API changes made in Blender from version to version makes backwards compatibility a nightmare. It is recommended to be working with 2.7x releases if the source of the problems is an older version of Blender that doesn't support `bpy` attributes.

**Comment by mese79** [comment]
Yeah, i could see changes in blender 2.69 shadow setting (thanks for shot):
![2 69_1](https://cloud.githubusercontent.com/assets/1878378/6007837/66baa7e6-ab32-11e4-8f63-c00a4706cd45.png)

![2 69_2](https://cloud.githubusercontent.com/assets/1878378/6007848/7ed7702a-ab32-11e4-819f-0da0b2000811.png)

**Comment by repsac** [comment]
Development on this exporter started during Blender 2.70. As an FYI I don't plan to go backwards in compatibility for older Blender versions. Additionally I should note that the old exporter had its supported version changed from 2.6 to 2.7 for [r67](https://github.com/mrdoob/three.js/releases/tag/r67) and I believe there was a thread on this because of API changes elsewhere in Blender (tho I can't recall any details).

The only advice I can offer is to use a newer version of Blender. If you are stuck with 2.6x releases then you may have to consider using older versions of the now deprecated exporter (r66 and older).

Are there any other questions or concerns on this matter?

**Comment by mese79** [comment]
I'm upgrading my blender!
But i'm wondering the new json file created by new exporter just works the same with THREE.JSONLoader in r70?
Thanks for your time.

**Comment by repsac** [comment]
@mese79 sorry I completely missed your reply.

- The geometry exports work with JSONLoader
- The scene exports works with ObjectLoader

Best of luck.
