### ISSUE TITLE
Suggestion: Neon Lights

### ISSUE THREAD

**Issue by Chaky74** [mrdoob/three.js#6013]
All the lights in Three.js are from a single point (apart from directional and ambient). What is really lacking is light from a straight line (or curved, if possible), like neon light. Food for thought.

**Comment by dmtaub** [comment]
So emissive light from an arbitrary object influencing other objects in the scene?

**Comment by Chaky74** [comment]
That would be ideal, but simple line-sourced light would make a huge difference and open up a world of possibilities for photo-realistic rendering.

**Comment by arose** [comment]
There is http://threejs.org/examples/#webgldeferred_arealights

**Comment by Chaky74** [comment]
.. only for deferred renderer.
I use WebGL renderer for pretty much every scene.

**Comment by WestLangley** [comment]
Related #5792

**Comment by mrdoob** [comment]
I don't think I've seen much work on having light emissive shapes (apart from AreaLight) in realtime.

**Comment by Usnul** [comment]
there are emissive textures. Arbitrary emissive shapes aren't something i've seen either, but textures are used in many places. If i remember right, rage had all light sources as emissive textures "painting with light" expression was thrown around.

However, for complex lighting you really need deferred pipeline. The reason threejs deferred renderer isn't used by anyone in production is the fact that it doesn't support a wide selection of basic features that WebGLRenderer does. This is more of an abandonment, it was being actively developed at one point, and it looked like it would become the default, but then development was abandoned. I believe it's because WebGLRenderer is simpler to understand and main developer on deferred has left the project (i.e. aq).

On the side of game industry, deferred rendering is the default nowdays, since there are many passes required to achieve levels of graphics we are used to today in games. Unreal uses 8+ passes for instance:
- ambient
- scatter
- diffuse
- rim
- occlusion
- reflection
etc.

It would be great to see more work on deferred renderer, but we'd need a strong lead/team for that to happen i believe.

**Comment by QuaziKb** [comment]
its a shame the deferred renderer was abandoned, it really has potential, (It's not in bad shape atm, but could use some love)

**Comment by Usnul** [comment]
> Do you have a link? Arbitrary emissive textures on arbitrary meshes causing at least one bounce of light would require incredible amounts of computing power.
They would, that's why they are usually used on simple shapes. Most high-end engines support glow textures though. I know next to nothing how it is implemented, i must admit.
I remember hearing about rage light textures in JC's technical talk somewhere on youtube.
>  But don't forget that Unreal engine is written for applications that have exclusive and direct access to powerful console or desktop GPUs. 
unreal and unity both run on mobile devices. There is nothing inherently prohibitive about deferred rendering, many parts of shader code can be reused also, in fact old DeferredRenderer was relying on WebGLRenderer to do most of heavy lifting.
https://github.com/mrdoob/three.js/blob/master/examples/js/renderers/WebGLDeferredRenderer.js#L21-L31

This is perhaps the main reason why its so slow. It was written more as a proof of concept using existing parts, with little regard to performance by the looks of it.

I do believe that WebGLRenderer fits wider range of use-cases, but I don't believe that deferred renderer would bring about prohibitive performance penalties for most devices, I also think that large part of code-base could be re-used.

**Comment by crobi** [comment]
> I remember hearing about rage light textures in JC's technical talk somewhere on youtube.

Do you have a link to that talk? A quick google search reveals nothing about the internals of id tech 5, apart from forum posts claiming that the engine doesn't even support dynamic lighting (!) and that all lighting is baked into the textures.

> I don't believe that deferred renderer would bring about prohibitive performance penalties for most devices

Deferred rendering uses more GPU memory and more memory bandwidth. Also, currently [over 60% of all users](http://webglstats.com/) do not have multiple draw buffers, so it will use more fill rate as well. Depending on the use case, this might be a significant performance cost.

I'm not saying a deferred renderer would be bad, just that some people would prefer a simple forward renderer. Just don't delete the forward renderer without a serious discussion.

**Comment by Usnul** [comment]
> I'm not saying a deferred renderer would be bad, just that some people would prefer a simple forward renderer. Just don't delete the forward renderer without a serious discussion.

I agree. Argument is that forward renderer could co-exist. I'm fairly certain it could be made possible by large bulk of what is necessary for a decent deferred renderer, meaning it would require little maintenance. Graphics evolve pretty rapidly, sticking to 90s tech just because it's good now is not going to cut it, I do care about this project and would hate to see it left behind.

> Do you have a link to that talk? A quick google search reveals nothing about the internals of id tech 5, apart from forum posts claiming that the engine doesn't even support dynamic lighting (!) and that all lighting is baked into the textures.

I think that was it. I'm confusing glow textures. You could create light-emitting textures for low-frequency lighting with light-propagating volumes, or use the same technique as area light, or even ray trace them. to be clear: I don't believe it's a good idea, it is possible though.

> Deferred rendering uses more GPU memory and more memory bandwidth. Also, currently over 60% of all users do not have multiple draw buffers, so it will use more fill rate as well. Depending on the use case, this might be a significant performance cost.

Could you describe how it uses more memory in a significant way?
Fill rate for simple passes is not a big issue, pass-though fragment shader can run pretty fast as far as i understand. If you believe differently - i would love to be convinced.

**Comment by Chaky74** [comment]
>Deferred rendering uses more GPU memory and more memory bandwidth. Also, currently over 60% of all users do not have multiple draw buffers, so it will use more fill rate as well. Depending on the use case, this might be a significant performance cost.

I don't think that 40% of users should "suffer" the lesser performance (quality-wise) rendering just because they have superior configuration. I think that this project in general should (and must) be future-oriented, and one conclusion must be drawn about the future: configurations ARE going to be bigger, stronger, better.

Oh... and let's not forget about forthcoming WebCL either, that is ultimately going to exponentially increase the JS performance..

Just to keep things in perspective, thisi is how the [first ever webpage] (http://line-mode.cern.ch/www/hypertext/WWW/TheProject.html) looked like. Just text. Then someone managed to add pictures, styles, different fonts... then videos came about... 3D graphics is the next logical step, and I say spare no expences when it comes to quality.

**Comment by crobi** [comment]
This discussion got a bit off topic. I would suggest you create a new issue if you want to push the deferred renderer or discuss the future of three.js.
