### ISSUE TITLE
Rendered Objects Pixelated

### ISSUE THREAD

**Issue by Sneagan** [mrdoob/three.js#6027]
After update to r70, my rendered objects are very pixelated. I know I'm riding the support/issue line here, so I sincerely apologize if I'm crossing it, @mrdoob. :/

**Comment by arose** [comment]
After this changeset (14a98f9259bd158cf065191f5305baa04ebc14f3) you have to set the `pixelRatio` yourself.

**Comment by mrdoob** [comment]
@greggman @WestLangley So this is another case... If we remove all the `pixelRatio` stuff we're then forcing new users to have to learn what pixel ratio is...

**Comment by WestLangley** [comment]
@mrdoob Yes, there are trade-offs. But given the discussion in #5627 and #6028 and #5908, I think three.js needs to get out of the pixel-ratio-setting business.

As @mrdoob said, the downside is:

> And fixing that will require multiplying devicePixelRatio to *Renderer.setSize(), Line*Material.linewidth, Mesh*Material.wireframeLinewidth, PointCloudMaterial.size, etc.

/ping @greggman

**Comment by greggman** [comment]
I don't know what answer you're looking for. `pixelRatio` in three causes all kinds of problems. The way three was handling it before meant lots of magic happening behind the scenes which you have to divine/guess at if you want to deal with it in your own code.  

For example if you want to do picking and you want to call readPixels you expect if you called `renderer.setSize(100, 200)` that then calling `gl.readPixels(99, 199, 1,1)` would give you the top right pixel. But that breaks with automagic pixelRatio

Another example, if you want to do a fullscreen quad screen shader with code like this

    uniform vec2 resolution;
    ...
       vec2 uv = gl_FragCoord.xy / resolution;

Then you expect this will work

     renderer.setSize( width, height );
     uniform.resolution.value.setValue ( width, height );

but again that breaks with automagic pixelRatio

Therefore, removing pixelRatio from three moves that responsibility to the user. If they compute width and height they want and those numbers work everywhere.

Of course i'd also say `renderer.setSize` should never EVER set the CSS size. But fixing that would also break backward compatibility.

**Comment by mrdoob** [comment]
> Of course i'd also say `renderer.setSize` should never EVER set the CSS size. But fixing that would also break backward compatibility.

`renderer.setSize` sets the CSS size just because the pixelRatio business. Otherwise, the user will need to do this:

```javascript
renderer.setSize( width * pixelRatio, height * pixelRatio );
renderer.dom.style.width = width + 'px';
renderer.dom.style.height = height + 'px';
```

Which is not super pretty... And the API and user-friendliness is my main concern on all this. Seems like most of the problems this creates for advanced users get solved by just not touching pixelRatio (letting it just be at 1).

I agree that the  `setPixelRatio()` being after `setSize()` order issue is a problem and maybe it's better to have it in the constructor as it used to be... But defaulting it to 1.

I'm sorry this conversation is dragging for so long. For the record, I had just removed pixelRatio from my local repo and just realised about the CSS issue so I had to revert...

**Comment by greggman** [comment]
No, [as I pointed out before](https://github.com/mrdoob/three.js/issues/4903) if you used HTML and CSS as it was meant to be used then you'd just do this

    canvas { 
       width: 100%;
       height: 100%;
   }

And if you wanted a full page canvas you'd do this

    html, body {
       width: 100%;
       height: 100%;
       margin: 0px;
       overflow: hidden;     
    }

And it would all just work. No need to ever set `renderer.domElement.style`. Let the browser do that for you.

**Comment by greggman** [comment]
I would argue if your goal is to make it easier for beginners then CSS based sizing wins because you could automate sizing

     var renderer = new THREE.WebGLRenderer( { autoSize: true } ) // should be the default IMO

Then in renderer.render

     function resizeOfSizeChanged(gl) {
         var canvas = gl.canvas;
         var width = canvas.clientWidth;
         var height = canvas.clientHeight;
         if ( width != canvas.width || height != canvas.height ) {
            canvas.width = width;
            canvas.height = height;
            gl.viewport(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight);
            return true;
         }
         return false;
     }

     renderer.renderer = function( scene, camera ) {
         if ( this.autoSize && resizeIfSizeChanged( this.context ) ) {
            camera.aspect = this.context.canvas.clientWidth / this.context.canvas.clientHeight;
            camera.updateProjectionMatrix();
         ....

Now all code related to resizing in most samples could be deleted. You just set the CSS for what you want and it magically works. 20 lines deleted from most samples. Only samples using postprocessing would care.

Of course that conflicts with the `pixelRatio` issue :(

**Comment by greggman** [comment]
Let me also add I've recently gotten super used to events which is a common pattern in JavaScript. A simple event emitter (sorry if this is repeating something obvious)

    var EventEmitter = function() {
       var listenersByEvent = {};

       this.addListener = function(event, listener) {
          var listeners = listenersByEvent[event];
          if (listeners === undefined) {
             listeners = [];
             listenersByEvent[event] = listeners;
          }
          listeners.push(listeners);
       };

       this.removeListener = function(event, listener) {
         var listeners = listenersByEvent[event];
         if (listeners !== undefined) {
            var ndx = listeners.indexOf(listener);
            if (ndx >= 0) {
               listeners.splice(ndx, 1);
            }
         }
       }

       this.emit = function(event) {
         var listeners = listenersByEvent[event];
         if (listeners !== undefined) {
            var args = Array.prototype.slice(1);  // remove the event from args
            for (var ii = 0; ii < listeners.length; ++ii) {
                listeners[ii].apply(null, args);
            }
         }
       }
    }

What's the point of all that? That it's easy to decouple things and still provide easy ways to react. So for example

      WebGLRenderer = function(...) {
          ...
          this.eventEmitter = new EventEmitter();
          this.addListener = this.eventEmitter.addListener;
          this.removeListener = this.eventEmitter.removeListener;
      }

      // from above

     renderer.renderer = function( scene, camera ) {
         if ( this.autoSize && resizeIfSizeChanged( this.context ) ) {
            camera.aspect = this.context.canvas.clientWidth / this.context.canvas.clientHeight;
            camera.updateProjectionMatrix();
            this.eventEmitter.emit('resize', renderer);  // pass whatever you want here
         
Now user code can do this

      renderer.addListener('resize', function(renderer) {
           // update my render targets
           ...
      });

I'm not saying you could change to this. Just pointing out it's easy and useful.

**Comment by mrdoob** [comment]
Yep. I've been slowly implementing events here and there. [EventDispatcher](https://github.com/mrdoob/three.js/blob/master/src/core/EventDispatcher.js) is used when a geometry is deallocated or a texture needs to be updated. It was the only way to gets multiple renders to work with the same data.

**Comment by mrdoob** [comment]
@greggman 

Ok. So... would you be up for updating all the examples so they use the CSS based sizing and pixelRatio-less code? O:)

I think I like the auto resizing bit too. Specially so we can remove `camera.aspect`. But we can do that in a second PR.

**Comment by greggman** [comment]
Actually I would be up for that :)

But we need to decide what that means. I'll do one (with some changes like autoSize) and we can decide if that's the way forward?

**Comment by mrdoob** [comment]
Sounds good! :+1:

**Comment by mikaelgramont** [comment]
Hey, I just wanted to share my experience here. It is kind of embarrassing, but here goes.

I worked on this one threejs-based project of mine for a few months, and shipped it last month. I soon added a Cardboard VR option to it, and was quite happy with it, and though I was a bit disappointed by the quality of the display on my phone, I didn't think much of it.

Yesterday I tried another (native) Cardboard app and was shocked by how clean the display was. So I thought, something's up with HDPI... and that's how I came to learn that devicePixelRatio isn't handled automatically.

Part of me feels dumb for not noticing earlier, but since I'd never used it before, I couldn't tell the difference. Also, as acknowledged in the thread above, it's not very discoverable. I think it's very possible that there's an army of idiots like me out there who don't know about it and are missing out.

So, I'm sorry if I'm another newcomer reviving an old thread, but I kind of wish the constructor for WebGLRenderer would default to reading up window.devicePixelRatio. Is there consensus against it?

I did read the other threads, but I found the argument against it (constructor parameters should not change after instantiation - https://github.com/mrdoob/three.js/pull/6028#issuecomment-73117487) holds little weight (IMHO) in the face of users not discovering the setting. How often do people need to change the pixelRatio anyway?

**Comment by greggman** [comment]
The argument against doing automatically is that many three.js apps will flat out break in that case. I've already fixed several. So which is better

1. most apps work but some are lower-res than they could be

2. some apps get auto hi-res but many apps flat out break

The problem is authors won't know their apps are broken unless they test on both an HD-DPI display and a non-HD-DPI display

Unfortunately the current solution of calling `renderer.setPixelRatio` doesn't actually solve the issue because everyone just copies and pastes. Solving the issue would be to remove any reference to `devicePixelRatio` from three.js whatsoever. Then it would at least never been the fault of three.js when something is broken and it seems far more likely people using three.js and deciding to support HD-DPI would be aware of the issues.

**Comment by mikaelgramont** [comment]
Ok, I see what you're saying. 

How about this, until everything is automatic: on the first call to `render()`, if `DEBUG` is true and the canvas isn't set correctly to take advantage of the hi-res display, we log a message to the console to let the user know. WDYT?

**Comment by mrdoob** [comment]
@greggman just so I remember, your solution was to pass a canvas element to the renderer constructor and check if the dimensions had changed every requestanimationframe, right?

**Comment by andrevenancio** [comment]
been going through this too, and seems like this was fixed before! :) close?
