### ISSUE TITLE
exception when loading model that is exported with new blender exporter and THREE.ObjectLoader

### ISSUE THREAD

**Issue by lz000** [mrdoob/three.js#6037]
I'm trying to load this json model: https://www.dropbox.com/s/swhjmnvfs205nun/male.json?dl=0 that is exported with the new r70 blender exporter. The code I'm using is:

var loader = new THREE.ObjectLoader();
    loader.load(PATH_TO_JSON, _.bind(function (data) {

});
        
This throws an exception Uncaught TypeError: Cannot read property 'scale' of undefined. I found that in line 12644 of three.js: geometry = geometryLoader.parse( data.data ).geometry; the data.data is null, which caused this issue. Any idea?

**Comment by repsac** [comment]
OK I see the problem. When you export do not turn off `Embed geometry`
![embed geometry](http://i.imgur.com/NLLJhCn.png)

non-embedded geometry files was a feature of the old SceneLoader() and exporter. Because this seems like a logical feature to have I included it in the new exporter but it is not yet supported with ObjectLoader(). On the next PR this options will be removed from the Blender interface until it is supported again.
