### ISSUE TITLE
Uneven edges when using SubdivisionModifier

### ISSUE THREAD

**Issue by fallenartist** [mrdoob/three.js#6135]
Not sure if this has been discussed but when using SubdivisionModifier on a mesh with open edges, they are forming a jagged line, not even as I believe it should be:

![Mesh](https://cloud.githubusercontent.com/assets/661820/6374147/f08b7c12-bd06-11e4-92bd-f6455714afe4.png)

![Subdivided Mesh](https://cloud.githubusercontent.com/assets/661820/6374150/f8c01ffa-bd06-11e4-93bb-40073e2995ff.png)

http://codepen.io/znak/pen/QwrPOb?editors=001

Is this a bug or can it be overcome somehow? Thanks!

three.js r70 / Safari 7.1.3 / Mac OS X 10.9.5 / NVIDIA GeForce GT 120

**Comment by zz85** [comment]
Yup the current implementation of  `THREE.SubdivisionModifier` does not support open edges (or "sharp edges" as written in the comments in the source). Since there isn't any code to support it right now, It is not a bug and definitely an enhancement anyone could contribute to. I haven't look into the best way this could be implemented right now, but typically edges needs to be marked, and the modifying operation should not move the vertices of these edges.
