### ISSUE TITLE
THREE.Animation - On skeletal animation weights

### ISSUE THREAD

**Issue by willy-vvu** [mrdoob/three.js#6178]
I've been using THREE.Animation lately, and wanted to play two animations at once. Someone else on [StackOverflow](http://stackoverflow.com/questions/26496792/three-js-multiple-skeletal-animations) has the same question. Ideally, the effect would be achieved by playing two animations, both with `animation.weight = 1`.

Going into animation, my mental model of how animations work in Three.js is as follows:
1. Animations are functions. Every frame, animation takes in the current time and out comes a pose for the mesh.
2. The poses that come from the animations are then mixed together as weighted averages. Thus, the final pose assigned to the mesh:  `final = animation1(time1)*weight1 + animation2(time2)*weight2 + animation3(time3)*weight3 + etc...`

However, in reality, Three.js's model is not as straightforward as I thought.

Upon digging into the animation framework and playing around with weights myself, I realized that all animation weights are automatically (inherently, by the way the code is written) normalized. In other words, the absolute size of the weights do not matter - it's the relative sizes that do. Thus, having two animations both with weights 1 will have the same effect as having two with the weights 0.5: the SkinnedMesh will perform an animation that draws equally from both animations, becoming the average. I would expect that averaging would only occur with two weights of 0.5, and two weights of 1 would add the two animations together.

Could this auto-normalization feature be removed? If so, it would allow for greater flexibility by allowing two complete animations to play on top of each other. On the downside, if a programmer would like to smoothly blend between animations, they would have to makes sure all animation weights add up to 1 by themselves. For me, it makes sense that the weights need to add to 1 for a proper blend, as that's the way a weighted average works. I ended up writing normalization code anyways, and it was quite trivial.

Also, some immediate thoughts listed below that may spawn more issue threads:
- An animation's `currentTime` only works when increasing over time. I tried decrementing currentTime expecting the animation to run in reverse, though it just froze. This tripped me up because I thought animations would be functions that map any input time to any output pose.
- I expected to be able to adjust weights and blend between stopped/single frame animations, so I could transition between a Jump and Idle animation, for example. However, animation weights only affect the mesh when `animation.isPlaying == true`. Again, I assumed that non-playing animations would still contribute to the total unless the weight was set to 0.
- It would be nice to have a seamless way to transition between a game character facing right or left. One potential feature would be to be able to construct mirrored version of an animation with code and blend it with the forward facing animation programmatically. Alternatively, a potential feature could allow the reading/modification of an animation's intended pose before it is blended using weights, allowing a mirrored animation to be set and blended with the forward animation. I'm far from an industry game developer, so I don't know what tricks/functionality that commercial 3d graphics frameworks have that would facilitate such programmatic creation and blending of poses/animations, so there's likely a better way than naively constructing/modifying poses.

I'm excited about the potential of three.js's Animation framework, as great animation really makes games and interactives shine. Three.js has a workable animation foundation in place, though I'd love to see it grow and offer more power. I'm definitely looking forward to what browser gaming will become in the future!

**Comment by willy-vvu** [comment]
Oh, and extending my thoughts on my original mental model of animations:

What if skeletons (poses) could be manipulated similar to vectors? I know it'd be really memory-inefficient, but it's just for conceptualization. Imagine an animation system like this:

```coffeescript
walk = new THREE.Skeleton()
wave = new THREE.Skeleton()
walkAnimation = THREE.Animation(...)
waveAnimation = THREE.Animation(...)

walk.setFromAnimation(walkAnimation, 5) #5 is the time
wave.setFromAnimation(waveAnimation, 10)
wave.multiplyScalar(0.5)

mesh.skeleton.copy(walk).add(wave)
```

Also, these may spawn more issues if deemed worthy:
- Callbacks upon completing animations?
- A built-in configurable blend/transition from the end of one animation to the beginning of another?
- Events that can fire during an animation (e.g. a footstep that can be used to play a sound)
- Showing/hiding/dynamic parenting of a bone to another mesh (a similar concept already exists in an existing three.js issue)

**Comment by willy-vvu** [comment]
I read up a bit on [Unity's animation system](http://docs.unity3d.com/Manual/AnimationOverview.html). Unity uses a state machine to keep track of currently playing animations and to trigger+blend between other animations. It turns out, I wrote some Three.js animation code that acted like a state machine without knowing that Unity also used a state machine! This is definitely a higher-level feature, though my original premise for posting this issue was on the somewhat lower-level weight system. It also may be more specialized for games, and I believe that three.js is designed to be less specialized. I digress.

**Comment by crobi** [comment]
IMO, Unity has a nice system for animations. It uses two systems for controlling animations: [blend trees](http://docs.unity3d.com/Manual/class-BlendTree.html) and an [animation state machine](http://docs.unity3d.com/Manual/AnimationStateMachines.html). The state machine controls the transition between unrelated animations (e.g, when and how to switch from *running* to *jumping*), the blend tree is used to blend animations (e.g, a smooth blend between *walking* and *running*). 

The systems are independent of each other and should be equally complex to implement. AFAIK, three.js currently has nothing like the animation state machine. The way animations are blended using `THREE.Animation.weight` can be thought of as a simple kind of a blend tree.


> lower-level weight system

Game engines often use blend trees for this:
- The leaves of the blend tree are usually animation clips and produce a single pose for a given time.
- Interior nodes are used to combine (blend) two poses. There's many types of ways to blend two poses, see for example the [Unreal Engine docs](https://docs.unrealengine.com/latest/INT/Engine/Animation/NodeReference/Blend/index.html).
- The root of the blend tree is then the final pose of your animated object
- You could also combine inverse kinematics with a blend tree, but that is a really advanced feature.

For one of my projects, I have written a complete replacement of the three.js animation system. It's in an experimental state, but it has blend trees and should perform much better than the three.js system - on the other hand, it's meant to be used by a game engine and is probably not as flexible as the three.js system. Let me know if you're interested in the code.

> [...] allow for greater flexibility by allowing two complete animations to play on top of each other

This could also be solved by a blend tree: each blend tree node can use a different way to combine two poses. In [Unreal Engine](https://docs.unrealengine.com/latest/INT/Engine/Animation/NodeReference/Blend/index.html#applyadditive), there's a node for adding an animation on top of another one.

> The poses that come from the animations are then mixed together as weighted averages.

Just a minor note: three.js uses `slerp` for rotation interpolation. This is a more complex operation than a simple weighted average, and is [not commutative](http://number-none.com/product/Understanding%20Slerp,%20Then%20Not%20Using%20It/). So if you interpolate 3 or more animations, the final result will depend on the order in which you add them. 

> An animation's currentTime only works when increasing over time

Yes, I've had problems as well when doing arbitrary changes to `currentTime`. At that time (not sure if the code changed since then), one of the issues was that animation keyframes are not uniformly sampled and the animation has to find the two nearest keyframes every time `currentTime` changes. This is an expensive operation (O(log N)), so the code was optimized to perform well only if `currentTime` is always increasing, and only by small amounts (see `THREE.Animation.prototype.getPrevKeyWith` and `THREE.Animation.animationCache`).

**Comment by shibing624** [comment]
Good,although i did not understood.

**Comment by Usnul** [comment]
> At that time (not sure if the code changed since then), one of the issues was that animation keyframes are not uniformly sampled and the animation has to find the two nearest keyframes every time currentTime changes. This is an expensive operation (O(log N)), so the code was optimized to perform well only if currentTime is always increasing, and only by small amounts (see THREE.Animation.prototype.getPrevKeyWith and THREE.Animation.animationCache).

@crobi I would agree it's expensive if we were talking about millions of key frames. As things stand, it's possible to track delta from previous frame and get efficiency of original solution, while also being able to run animation in reverse and jump to arbitrary position. ln(1 000 000) is about 14, so that's not really an issue, i think, especially considering you'd only pay that when random seek happens.

**Comment by titansoftime** [comment]
> Let me know if you're interested in the code.

Absolutely.

 I modified BlendCharacter.js but still sometimes I get snapping on some animation transitions. Super frustrating.

**Comment by crobi** [comment]
@usnul I wasn't trying to say that using non-uniformely sampled keyframes is bad. I was pointing out that because finding the current keyframe requires *some* work, three.js uses an optimization (caching of the previous keyframe) which unfortunately breaks down if you start messing with the value of `currentTime`.

One problem might be that `currentTime` and `timeScale` are public members, so users can perform arbitrary changes on those values. If a user decreases `currentTime` while `timeScale` is positive, code that expects `currentTime` to increase (such as [here](https://github.com/mrdoob/three.js/blob/master/src/extras/animation/Animation.js#L219)) won't work correctly.

Speaking of which, I am having trouble understanding the code that searches for the next keyframe. [Here](https://github.com/mrdoob/three.js/blob/master/src/extras/animation/Animation.js#L219), the code seems to check whether the cached keyframes can still be used for the current time. This check should not depend on `timeScale`. Also, once the code decides that it needs new keyframes, it discards the keyframe cache and [starts searching from the beginning](https://github.com/mrdoob/three.js/blob/master/src/extras/animation/Animation.js#L222) of the list, using a [linear search](https://github.com/mrdoob/three.js/blob/master/src/extras/animation/Animation.js#L225). Doesn't this defeat the purpose of the keyframe cache?

By the way, O(log N) is the theoretical optimum if you use binary search, three.js performs a linear search, which is O(N). If implemented correctly, the linear search could still be good because most of the time you start from the cached keyframe and perform at most 1-2 iterations of the linear search.

**Comment by Usnul** [comment]
@crobi I concur about linear search, from my experiments in the past linear search on arrays in JS beats binary on small arrays (<100k say). I think this has something to do with optimizations of sequential iteration scenarios.

**Comment by crobi** [comment]
> linear search on arrays in JS beats binary on small arrays (<100k say)

I'm pretty sure that's not true - you might want to support your statements with some data or references, otherwise it looks like you're selling speculations and rumors as facts. A simple google search reveals several benchmarks ([here](http://jsperf.com/javascript-array-search) or [here](http://jsperf.com/searching-javascript-arrays-with-a-binary-search/13)) showing that binary search is faster even on very small arrays.

Anyway, I don't think this is the point of this issue. @willy-vvu was discussing the overall design of the animation framework, and bugs and limitations associated with the current design.

**Comment by Usnul** [comment]
@crobi 
My experience has been so. I apologize if my expressed opinion was perceived as fact. There are several factors that artificial benchmarks fail to take into account, lets assume they are irrelevant, just like my personal experience on my personal hardware with my specific problems. I can try to give you a refund if you believe i have sold you something.

**Comment by titansoftime** [comment]
Umm... so any ideas on how to remedy this issue?

**Comment by Usnul** [comment]
@titansoftime 
In fear of being called captain obvious. I think a functional interface described earlier
>An animation's currentTime only works when increasing over time. 
with underlying layer doing search optimization to make it work as efficiently as before. I.e. caching previous and maybe next frame.

A good starting point would probably be inefficient implementation of such functional interfaces just to make a starting point. Blend trees and other magic seems to map to this quite nicely unless I'm misunderstanding something.

**Comment by willy-vvu** [comment]
I'm back from a long period of inactivity.

I may as well move off the topic of animation weights for now and instead more broadly (high-level) onto how to make Three.js's animation system more friendly/coherent to use. I feel:

* Skeletal animations perhaps should be tied to a SkinnedMesh. It's hard to forsee using animations without one.
* Perhaps a simple API for playing a single animation and being able to specify (in the play method) how long to blend from the currently playing animation would be a straightforward way to start off. For most projects, this simple model would do the trick.
* Being able to play multiple animations at once and perhaps transforming animations (think about a player turning around) would be available with blend trees. Of course, this would be abstracted away with the simpler API described above, but it would be nice to be able to use the tree in advanced projects. The tree would also give control over the non-commutative slerps.

**Comment by Mugen87** [comment]
`THREE.Animation` is deprecated.
