### ISSUE TITLE
Adding THREE.AudioAnalyser

### ISSUE THREAD

**Issue by sachanacar** [mrdoob/three.js#6213]
Hello,

Right now we are able to affect Audio (panner) with the camera (using a listener) . However, it would be nice to be able to affect the mesh with the Audio (like frequency over time for example) 
Would it be possible to implement, within THREE.Audio or THREE.AudioListener, a way to retrieve frequency over time.

Similar to this demo: http://srchea.com/experimenting-with-web-audio-api-three-js-webgl

**Comment by mrdoob** [comment]
We would need a `THREE.AutioAnalyser` for that...

**Comment by sachanacar** [comment]
Alright I'm adding the title of this suggestion to 'Adding THREE.AudioAnalyser'

**Comment by sfpgmr** [comment]
+1

**Comment by makc** [comment]
@sachanacar how would this even work? suppose you have array of frequencies. what's next? is there the one and only "right" way for (vertex) shader to use this data? or is there some generic way that would also enable other useful applications, to justify increasing complexity?

**Comment by mrdoob** [comment]
Lets start by being able to query frequencies to scale an object ;)

**Comment by sachanacar** [comment]
agreed, being able to query frequencies and map the returned values to something (mesh, geometry, etc.)

**Comment by makc** [comment]
but "map to" is very broad concept, which is my point. IF you have to provide the code to perform this mapping, even if this is just event listener, there is already no point in this being built into the engine. because you could just as well copy-paste the code from your link (which is using three.js inside). and IF the "mapping" is built in, then how do you guarantee that those "256 megabytes" are enough for everyone?

**Comment by makc** [comment]
(it could be good thing to put in examples folder, however. just like those various "controls" scripts)

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/480968249d96a7bf71952a951c445190ffee20c8
