### ISSUE TITLE
Blender ThreeJS Exporter - Armature Support

### ISSUE THREAD

**Issue by Venryx** [mrdoob/three.js#6219]
I noticed the following in the Blender ThreeJS exporter script:

```python
def get_armature():
    if len(bpy.data.armatures) == 0:
        print("Warning: no armatures in the scene")
        return None, None

    armature = bpy.data.armatures[0]

    # Someone please figure out a proper way to get the armature node
    for object in bpy.data.objects:
        if object.type == 'ARMATURE':
            return armature, object

    print("Warning: no node of type 'ARMATURE' in the scene")
    return None, None
```

I explored around some, and found you can get the armature nodes + armatures themselves in the scene another way (a way which lets you know which armature nodes are linked with which armatures):

```python
def get_armature():
	for obj in bpy.data.objects:
		if obj.type == "ARMATURE":
			return obj.data, obj # the important bit; objects with armatures (i.e. where obj.type == "ARMATURE") can have their armatures accessed just by using the "data" property

	print("Warning: no node of type 'ARMATURE' found in the scene.")
	return None, None
```

Thought I'd mention this, as it allows for better handling of armatures. (instead of just the first armature, it can include all the armatures in the scene, because it knows which armature nodes are linked with which armatures now)

**Comment by repsac** [comment]
This code is from the old exporter. Since r70 we are running a new exporter. r70 users are highly advised to use the exporter from r71 dev because of all the improvements made to that branch.

`bpy.data.armatures[0]` is no longer being used. It was replaced with a Blender API call
https://github.com/mrdoob/three.js/blob/dev/utils/exporters/blender/addons/io_three/exporter/api/mesh.py#L768
