### ISSUE TITLE
True Physically-based falloff for lights

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#6243]
I'd like to submit a new PR that adds the option for true physically-based fall off for point, and spot lights.  I tried to get physical fall in as a previous PR but it didn't work -- I'd like to try again: https://github.com/mrdoob/three.js/pull/5787

The reason I am trying again is that I need a Physically-based renderer and this is a very important part of it.

To be specific, I would like to follow the model of UE4 and have an boolean option on each light called 'physicalFalloff', which when enabled causes the light to have a quadratic falloff in terms of area and it assumes that the intensity of the light is in lumens and the distance is in meters.  I think that making these assumptions for when you want to be physical is necessary.

Here is how UE4 describes their implementation and I would suggest following their lead nearly exactly:

![image](https://cloud.githubusercontent.com/assets/588541/6689002/f0c6e86a-cc8d-11e4-8a63-8532dd931cf4.png)

Source: https://de45xmedrsdbp.cloudfront.net/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf  (page 11)

If you guys approve, I'll submit a new PR that adds this new mode.

**Comment by WestLangley** [comment]
In spite of my prior objections, I now support adding this feature in conjunction with more physically-based models.

In order to be intellectually honest, however, I personally would not refer to it as "true physically-based falloff", because, like many other models, it is a compromise. I think that "quadratic falloff" is a better term than "physical falloff". It is up to you...

**Comment by mrdoob** [comment]
Sounds good to me!

**Comment by bhouston** [comment]
Completed.
