### ISSUE TITLE
tonemapping demo has bugs, leakage between all three views incorrectly.

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#6244]
This demo here:

http://threejs.org/examples/#webgl_shaders_tonemapping

When you modify the interactive settings on the right hand side, they should, according to the code here, only adjust the "adaptive" HDR Tone mapper, the view on the right.

https://github.com/mrdoob/three.js/blob/master/examples/webgl_shaders_tonemapping.html#L451

For example, try adjusting "middle gray", which should only affect the adaptiveToneMapper, the right hand view.  You will notice, moving this setting affects all three views.  This means there is leakage between the views in some way.

You can see in the code, the ```adaptToneMappingPass``` variable is only used in the right hand view:

https://github.com/mrdoob/three.js/blob/master/examples/webgl_shaders_tonemapping.html#L376

/ping @MiiBond

**Comment by MiiBond** [comment]
This isn't exactly a bug but it certainly isn't very well designed. All three views share the same tone-mapping shader (which use the same uniform for middleGrey and maxLuminance) even though they use differently compiled versions of the shader. The UI on the right contains other global values like sunLight and bloomAmount as well. However, it's weirdly inconsistent because it also contains the "adaptionRate" value that's specific to the adaptive version...

My local version of the adaptive tone-mapping has been modified pretty heavily since I made this demo. Hopefully, I'll have a chance in the near future to bring over my changes and clean up the inconsistencies in this demo as well.

**Comment by bhouston** [comment]
> All three views share the same tone-mapping shader (which use the same uniform for middleGrey and maxLuminance) even though they use differently compiled versions of the shader.

Hi @MiiBond, I'm pretty sure the three views actually use different tone map shaders, see these three lines of code:

https://github.com/mrdoob/three.js/blob/master/examples/webgl_shaders_tonemapping.html#L366
https://github.com/mrdoob/three.js/blob/master/examples/webgl_shaders_tonemapping.html#L368
https://github.com/mrdoob/three.js/blob/master/examples/webgl_shaders_tonemapping.html#L369

That is the confusing thing to me.  They do not appear to be sharing code, but they still act in concert?

What you are saying is that the uniforms are not being updated independently for the different tone map shaders?  Somehow one set of uniforms is being shared across all three?

**Comment by MiiBond** [comment]
Right, their using different versions of the shader but the same uniforms structure. The uniforms structure simply isn't being cloned when assigned to the shader.

**Comment by bhouston** [comment]
I think I found the bug, it is here:

https://github.com/mrdoob/three.js/blob/master/examples/js/postprocessing/AdaptiveToneMappingPass.js#L110

Basically you should be cloning these uniforms, rather using a global.

I suspect the same bug can be found here:

https://github.com/mrdoob/three.js/blob/master/examples/js/postprocessing/AdaptiveToneMappingPass.js#L98

**Comment by bhouston** [comment]
You do clone one set here, so we just need to apply this pattern to the other uniforms to fix the bug:

https://github.com/mrdoob/three.js/blob/master/examples/js/postprocessing/AdaptiveToneMappingPass.js#L25

**Comment by MiiBond** [comment]
Again, sharing the uniform is the way it was supposed to work. It might not be the best way to write things but it was intentional. The maxLuminance and middleGrey are meant to be shared across the 3 shaders. You're more than welcome to clean this up and have the UI update the uniform in all three shaders separately, if you'd like.

**Comment by bhouston** [comment]
I've submitted a PR that addresses the shared uniforms across all instances of AdaptiveToneMapping here: https://github.com/mrdoob/three.js/pull/6246

**Comment by bhouston** [comment]
@MiiBond Do you mind if we remove the gamma correction part of the AdaptiveToneMapping?  I feel that @WestLangley's PR here https://github.com/mrdoob/three.js/pull/6245 that allows for a separate gamma correction pass is a better approach because it can be done after all passes have been executed (as adaptive tone mapping is usually an intermediate pass.)

**Comment by MiiBond** [comment]
Absolutely. Go right ahead. I believe I've done the same in my local branch.

**Comment by bhouston** [comment]
I've made the modification in this PR to @WestLangley's repo: https://github.com/WestLangley/three.js/pull/1

**Comment by bhouston** [comment]
Fixed.
