### ISSUE TITLE
Skeletal animation from blender to threeJS using ThreeJs exporter, looks distorded.

### ISSUE THREAD

**Issue by laetitiakami** [mrdoob/three.js#6388]
Hello ThreeJS team!

First of all, I would like to thank you all for this amazing project. Now I feel like I can finally create a game using a browser, and my dreams are getting true! 

I'm using Dev r71 at the moment.

I tried to export a character from blender, part by part, binding each part (hand, head, body) to the same skeleton. So far, everything work fine, I bound all parts on an unique skeleton and they attach and position properly.

The problem occurs when I try to animate my character. I exported the skeletal animations but as you can see in that video, it doesn't work, part of the character doesn't animate, and also it looks distorded.

https://www.youtube.com/watch?v=hqVD1yw1aAw&feature=youtu.be

I'm not sure what I am doing wrong. Also, over my 5  different animations, it indeed exports 5 animations but they are all the same, just playing at different speed and duration.

Do you have any idea what could I be doing wrong? Which data can I give you to help debugging this issue?

Thank you in advance!

**Comment by repsac** [comment]
The way you describe it is that there are different objects/meshes bound to one skeleton. Is this correct?

**Comment by laetitiakami** [comment]
Yes, that's true.

After reading other issues about animations, I realised I didn't try to set REST properties to my skeleton, I will try that now and tell you if that fixes my animation. :)

Thanks!

**Comment by repsac** [comment]
OK, let me know. Also I am a bit skeptical about how effective scene exports are with animation exports because of how actions are handled in Blender. If you look at this function https://github.com/mrdoob/three.js/blob/master/utils/exporters/blender/addons/io_three/exporter/api/animation.py#L39

You will see that it simply iterates over the entire actions array in the scene. Because of how the Blender API works this seems to be a necessary evil that I am less than thrilled about because it doesn't seem to be clear on explicitly selecting actions relating to the current armature it is parsing.
