### ISSUE TITLE
NPM - Browserify Features are limited to core THREE.js functionality

### ISSUE THREAD

**Issue by michaeldeitcher** [mrdoob/three.js#6432]
Module support is very important to me. I've been attempting to use three.js as a module using browserify and the three.js npm package. This is ok but very limited. 

If I want to add a mouse click handler by raycasting, I will need to add /examples/js/renderers/Projector.js which is not in the npm installed module. There is no way for me to include THREE.Projector with the npm - browserify solution.

**Comment by mrdoob** [comment]
> If I want to add a mouse click handler by raycasting, I will need to add /examples/js/renderers/Projector.js 

That's incorrect. [This example](http://threejs.org/examples/#webgl_interactive_draggablecubes) is raycasting and doesn't require `Projector.js`.

**Comment by michaeldeitcher** [comment]
:) I just figured that out thanks.

**Comment by bugeats** [comment]
+1 I'm pretty committed to Browserify & ES6 modules at this point. I'm working on a project that uses three.js and it's the only lib that requires me to bend over backwards in order to get it in my build. 

I would suggest at least changing the npm package to include all the extras and examples. Better yet would be to migrate to npm compatible module system.

**Comment by mrdoob** [comment]
#4776
