### ISSUE TITLE
ObjectLoader doesn't support Face Materials

### ISSUE THREAD

**Issue by jpcloud** [mrdoob/three.js#6480]
My blender scene (low poly vallay with some trees): http://jppresents.net/static/blender/exportBug/untitled.zip (contains blend file)

Exported with the settings:
- geometry: vertices, faces, normals
- shading: face materials
- scene: scene, materials, hierarchy

Results in this export file: http://jppresents.net/static/blender/exportBug/scene.json

Every object now has only one material (in the export file, there is a property "material" on every mesh, and it's just one uuid. All materials assigned to the faces seem to get lost.

This is using Blender 2.74 with the dev exporter.

For comparison:
http://jppresents.net/static/blender/exportBug/blender.png
http://jppresents.net/static/blender/exportBug/three.png

**Comment by hekto** [comment]
Ping @mrdoob. Any news on this?
AFAIK the exporter handles the face materials correctly. It is just ignored in the loader.

I have a modified ObjectLoader somewhere that solved the issue for me if that would be of any use.

**Comment by mrdoob** [comment]
Yes, that's a known issue. Haven't been able to tackle it yet...

**Comment by usefulthink** [comment]
I ran into this problem yesterday and spent half the night with my debugger figuring out exactly why MultiMaterials are not created by ObjectLoader although the information is present in the exported geometries. After I had a solution hacked together I found this, and I would love to discuss it.

From a quick experiment it looks like this could be fixed with just a few tweaks here and there. I have to admit that I don't know very much about how the JSON-Format is being used and developed except for my few use-cases in exporting from blender to three.js. 

I would propose adding a property `materials` (as alternative to `material`) to the `object` JSON-structure for objects where the geometries use face-materials. 

This would look something like this and would likely be backward-compatible:

```javascript
      {
        "name": "singleMaterial",
        /* ... */
        "material": "A8094C11-04FC-3C4E-98FF-7CEB861372DA",
        "geometry": "C2B97B3F-B625-304C-935C-8209B4B0A178"
      },
      {
        "name": "multiMaterial",
        /* ... */
        "geometry": "0A4F7562-D188-3F99-B596-5908E44CB0BD",
        "materials": [
          "CFD25A0F-52CC-3690-9E40-7535F3B67FE6",
          "88D87DF2-EF89-34A8-802B-55EAC788EDEF"
        ]
      }
```

Handling these would only require a small change in the `getMaterial()`-function within `ObjectLoader.parseObject()`:

```javascript
// ObjectLoader.js, line 463:
function getMaterial( name ) {

  if ( Array.isArray( name ) ) {
    
    return new THREE.MultiMaterial( name.map( getMaterial ) );

  }

  // ... handle the regular case as before (i.e. return material from `materials`-map)

}
```

And everywhere where it is called:
```javascript
// ObjectLoader.js, line 517 (in case 'Mesh':)
object = new THREE.Mesh( getGeometry( data.geometry ),  getMaterial( data.material || data.materials ) );
```

What do you think? Is this something I could propose a PR for?
I am currently looking into what would need to be changed in the blender-exporter to have it properly export that materials-array, but that is probably something I could just as well solve by preprocessing the JSON-structure before parsing.

**Comment by usefulthink** [comment]
As for the blender-exporter, I think it should be possible to store the UUID generated for the material somewhere in the blender material-properties so it can be looked up when preparing the meshes for export. The material-information per geometry would then need to propagate to where the object-declarations are assembled.

**Comment by mrdoob** [comment]
@usefulthink I think I like that solution. I would avoid keep it singular though (`material`):

```javascript
      {
        "name": "singleMaterial",
        /* ... */
        "material": "A8094C11-04FC-3C4E-98FF-7CEB861372DA",
        "geometry": "C2B97B3F-B625-304C-935C-8209B4B0A178"
      },
      {
        "name": "multiMaterial",
        /* ... */
        "geometry": "0A4F7562-D188-3F99-B596-5908E44CB0BD",
        "material": [
          "CFD25A0F-52CC-3690-9E40-7535F3B67FE6",
          "88D87DF2-EF89-34A8-802B-55EAC788EDEF"
        ]
      }
```

**Comment by camoconnell** [comment]
What was the conclusion here? i've run into the same issue, thanks.

**Comment by usefulthink** [comment]
@camoconnell I didn't have enough time to pursue this on the blender-exporter side of things (turns out the exporter is a big project in itself), and I'm a bit unsure how to text/document changes to the JSON-Format, but I quickly put together a gist with what I have so far. Maybe that helps: https://gist.github.com/usefulthink/d1021e24854657bbb3a7e919bc50e2f6

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/10931#issuecomment-290734264
