### ISSUE TITLE
new ttf font loader & TextGeometry

### ISSUE THREAD

**Issue by gbox3d** [mrdoob/three.js#6558]
freetypface site is dead
and I make this....
https://github.com/gbox3d/ttf-threejs

**Comment by gero3** [comment]
@gbox3d It seems we had the same idea. I created [facetype.js](http://gero3.github.io/facetype.js/). We use the same underlying library ([opentype.js](http://nodebox.github.io/opentype.js/)to process the fonts. Maybe we should work together for next versions. The code seems similar enough to get further with this.

**Comment by bhouston** [comment]
The ultimate font system would allow for in-browser consumption of the Google Web Fonts directly without too much intermediary pre-processing:

https://www.google.com/fonts

If pre-processing was necessary, I bet one of us could make a web service that did the conversion on demand and cached the results.

**Comment by mrdoob** [comment]
👍!

**Comment by mattdesl** [comment]
I've been doing lots of stuff with fonts in the past several months.

I tinkered with making [a CLI tool](https://github.com/mattdesl/fontpath) which basically does the same as typeface.js, using FreeType2, but exports JSON with kerning and some extra meta-data about the font. It is still fairly experimental and needs to get cleaned up a lot.

I think [opentype.js](https://github.com/nodebox/opentype.js) is a better base since it's more robust and handles basic GPOS kerning.

Also in a lot of cases vector fonts are not that great; pretty expensive to triangulate, anti-aliasing woes when they are drawn to an offscreen buffer, etc. Recently I've been more interested in Mapbox's node-fontnik and other tools for SDF fonts.

Anyways, lots of related modules and code:
https://github.com/mattdesl/text-modules 

And a high-level text renderer for bitmap / SDF fonts in ThreeJS:
https://github.com/Jam3/three-bmfont-text
