### ISSUE TITLE
What do you think about what to rewrite three.js on asm.js for greater performance? and add fast physics engine

### ISSUE THREAD

**Issue by Maxmaxmaximus** [mrdoob/three.js#6578]
What do you think about what to rewrite three.js on asm.js (C++) for greater performance? and add fast physics engine

if it is an impossible job, you can write C ++ only hot pieces such.

**Comment by gero3** [comment]
This question has been asked before. This was my response on it back then.
http://stackoverflow.com/questions/18427810/three-and-asmjs/18439786#18439786

I think it is still very correct in explaining why asm.js is hard to use for three.js.

PS: This is still only my opinion

**Comment by Maxmaxmaximus** [comment]
No intelligible argument and it was not............

**Comment by makc** [comment]
Because they don't want to switch to C++ ? Nothing stops *you* from doing that, though.

**Comment by gero3** [comment]
>Firstly, because THREE.js has to interact with usercode, it isn't easy to write an asm.js library because of it's many restrictions (no objects).

Three.js makes it easy to write a 3D application by using objects to represent the 3D scene. 

>Secondly, Three.js will not gain much performance a whole lot in performance for calculations where asm.js is strong in. But will gain more from future updates from the browsers. (for instance, the creation of typedarrays in chrome which is now a pain point in THREE.js is comming soon. V8 issue)

On average, a three.js scene is composed of more then just calculations.

>Thirdly, The code in asm.js needs to manage its own memory. Which would mean that THREE.js has to figure out a way to make a large apps work with limited memory. Or make every application very memory hungry.

In asm.js, you need to define how large your memory pool needs to be. And that can differ a lot between three.js apps.

**Comment by RemusMar** [comment]
> What do you think about what to rewrite three.js on asm.js (C++) for greater performance?

I'm not so sure about that "greater performance".
On the other hand, THREE is user friendly, asm.js is not.
And finally, to develop your JavaScript/WebGL project is better than exporting to WebGL from Unreal or Unity5.
Simply because any kind of porting leads to wasted resources and unoptimized chuncks of code.

cheers

**Comment by tonnot** [comment]
+1

**Comment by makc** [comment]
> In asm.js, you need to define how large your memory pool needs to be. 
Actually you can override this in asm.js module

**Comment by erichlof** [comment]
Good points raised so far.  I would like to add possibly moving Three.js's math library to SIMD.js for greater performance.  I think all of Three's Math code (especially Vector3 and Matrix4) could greatly benefit from this. Here's a video link (check out 22:51 in the time code) :
https://youtu.be/CbMXkbqQBcQ?t=1371
When this feature lands in major browsers, every user would see a noticeable speedup in their framerate as a result, because all Three.js apps, no matter the complexity, use vectors and matrices under the hood.

**Comment by mrdoob** [comment]
Yup! Can't wait for SIMD to land!

**Comment by Maxmaxmaximus** [comment]
Just write hot parts on a asm.js )) Why not?


п.с. I'll write a renderer to the physics engine in C ++ does not because I know C ++, but because I have to learn it. Because the most important result, and not any effort expended.

**Comment by makc** [comment]
>  the language of the curve
:+1:

**Comment by mrdoob** [comment]
> Just write hot parts on a asm.js )) Why not?

We'll implement asm.js where we see appropriate. A big problem of asm.js is that is hard to maintain.
