### ISSUE TITLE
Loading OBJ and MTL

### ISSUE THREAD

**Issue by ExtremelySeriousChicken** [mrdoob/three.js#6590]
Hi @mrdoob is there a way to load obj and mtl file separately? I understand that from #5250 that objmtl loader is not optimal at the moment, However I am looking into uploading a model with its mtl file. Thanks!

**Comment by AlexeyGapon** [comment]
I am using JSON format. You may edit your materials inside it. And i write material library for each project. Because each time it i usefull to tune your materials a little for better looking. That is why JSON is better for thuis kind of uploading.
1) load textures -> once they are loaded
2) create materials- > once materials are created ->
3) load models.
