### ISSUE TITLE
Raycaster.near not working for PointCloud (r71)

### ISSUE THREAD

**Issue by felixturner** [mrdoob/three.js#6615]
Hi,

setting the 'near' property on Raycaster has no effect on PointCloud picking.

Repro: http://airtightinteractive.com/demos/threejs/my_webgl_interactive_raycasting_pointcloud.html

Let me know if you need more info.

**Comment by felixturner** [comment]
The workaround is to check the 'distance' property in objects returned by intersectObject(), and ignore those closer than a certain value.

**Comment by mrdoob** [comment]
I recall this being a known issue... Rings a bell @WestLangley?

**Comment by WestLangley** [comment]
Comparing with `Mesh.raycast()`, a one-line addition seems appropriate following the `distance` definition:

    var distance = raycaster.ray.origin.distanceTo( intersectPoint );

    if ( distance < raycaster.near || distance > raycaster.far ) continue;

Not to hijack the thread, but for comparison, in the case of `Mesh.raycast()`, the equation is slightly different:

    if ( distance < precision || distance < raycaster.near || distance > raycaster.far ) continue;

I am not sure why the `precision`test is present... It was added here: https://github.com/mrdoob/three.js/commit/62122822ec41674fd2b62479c3b4289f670bf56a /ping @stephomi

Previously, `precision` was used to test if the ray and face were parallel. `precision` now has a different purpose.

**Comment by stephomi** [comment]
@WestLangley Indeed it's useless now as it works identical to raycaster.near... but I think it was somewhat already the case : [state of Raycaster before my first commit](https://github.com/mrdoob/three.js/blob/5d2bc5631247c9e7368644c182f1358911ecc513/src/core/Raycaster.js#L152-L168)
Anyway I remeber addind a [comment](https://github.com/mrdoob/three.js/commit/1f7cc3d7f816baa6558eef9b1fbe00e3e2781205) because I wasn't sure.

As for for the point cloud, the ray near/far test is [missing](https://github.com/mrdoob/three.js/blob/dev/src/objects/PointCloud.js#L55) indeed.

**Comment by WestLangley** [comment]
@stephomi Thanks for the reply.

Prior to your PR, someone introduced some unwarrented changes. Here https://github.com/mrdoob/three.js/commit/3a59e4bd342599350a4ce13846a56eb23590a9a3 is the original code:

    // bail if ray and plane are parallel
    if ( Math.abs( dot ) < 0.0001 ) continue;

So, subesquently, `precision` took on a new purpose. I thiink it should be removed. I would appreciate your opinion.

**Comment by stephomi** [comment]
Ahh now I understand when I check the original code.
So the precision test was broken before my changes...

Well I don't have the big picture but I think you can safely remove the precision test.
It doesn't test the parallel case anyway and it's error prone (what if your scene is very small, etc...).

**Comment by dubejf** [comment]
Fixed by #6625.
