### ISSUE TITLE
Store material index in BufferGeometry draw-calls

### ISSUE THREAD

**Issue by ikerr** [mrdoob/three.js#6618]
We have a fork of Three.js that allows us to use MeshFaceMaterial with BufferGeometry objects. In our case, MeshFaceMaterial is a misnomer, because we only allow material assignments at the draw-call level. This makes the implementation in WebGLRenderer fairly straightforward.

However, I noticed that MeshFaceMaterial was recently removed. Is the intent to have a single material assignment per Mesh? I wouldn't be a huge fan of this, because most 3D file formats that we deal with allow multiple material assignments per mesh, and I'd like to keep a 1:1 mapping between meshes in say, an FBX file, and meshes in Three.js.

Are there any plans to support multiple material assignments per Mesh? Should I open a pull-request from our fork? Though, I'm not sure that our fork will work now that MeshFaceMaterial is gone.

Would be great to get everyone's thoughts on this.

**Comment by titansoftime** [comment]
I'm in the same boat. The absence of MeshFaceMaterial has been a HUGE pain for me. Trying to stitch together a plane (altered by a heightmap) manually constructed with multiple materials (also requiring terrain collision) has been a fruitless task after many attempts.

MrDoob mentioned something about creating a loader that emulates MeshFaceMaterial. I personally don't use any loaders but I'm sure it could be hacked up to support dynamically constructed meshes.

**Comment by RemusMar** [comment]
As far as I know, Ricardo (mrdoob) removed the MeshFaceMaterial because he is working on it.
Multiple materials per mesh is a MUST, so if MeshFaceMaterial is not replaced with something "better",
it will be back.

**Comment by titansoftime** [comment]
>As far as I know, Ricardo (mrdoob) removed the MeshFaceMaterial because he is working on it.
Multiple materials per mesh is a MUST, so if MeshFaceMaterial is not replaced with something "better",
it will be back.

That would be perfect. Can we get a confirmation on this?

**Comment by mrdoob** [comment]
Yep! When I started the `WebGLRenderer` refactoring I decided to remove `MeshFaceMaterial` to keep things simple. But while refactoring I realised that we could add materials to `BufferMaterial` drawcalls and bring back `MeshFaceMaterial`.

If you have some code working a PR would be more than welcome! 😊

**Comment by titansoftime** [comment]
< Super happy to hear that =]

**Comment by rfm1201** [comment]
I’m writing a 3D editor for dummies that should allow them to modify simple 3D object texture directly on the textured object. The target is marketing people who want to design all the things you can see in a supermarket to be able to show you their new design in a survey.

Today they aren’t able to do it with the 3D editors available, so they go to third parties societies that take big money and lot of time just to add a new promotional sticker on the 3D texture used to render the top of their yoghurt pot.

So I use MeshFaceMaterial a lot. For a standard packaging, a box, I use 6 textures, one for each face. In fact, in my editor each texture is (will be) a hidden canvas, where the real texture modification is done. All the code for my hidden canvas class (including serialization) is written, I’m currently integrating it in the three.js editor.

So I’m very interested to know if there will be a new kind of MeshFaceMaterial and if the change in the internal three.js structure will be huge.

The second point is because I need to serialize the entire scene, the geometries (done in r71) and all the textures used in the scene (not done in r71).
For the moment, I wasn't on the texture serialization, but if I should stop development of the editor part, waiting for the new multi-material solution, the texture serialization will be first in my to do list. If the internal structure is going to change, writing now code to browse the scene structure to find texture information and serialized them could be a bad idea.

Thanks for any tip on the future.

**Comment by rfm1201** [comment]
To know what’s going on, I took the current dev version and was pleased to see that the serialization of the textures is on his way, an sad to see that MeshFaceMaterial is not resurrected yet.

But why is the image always converted to base64?

If there is a real URL in image.src (or image.href), why create a canvas to serialize the image. Maybe I’m the only one, but I use image stored on a web server (I modified the editor to be able to load such images) and I really want those images to be used even after a serialization.

Ok, I just have to add a test on image.src (or image.href) in the toJSON method of Texture.js to have it work as I want, but why is it done that way?

I don’t understand where is the problem with an image URL, except for the JSON to be able to load offline. There is no cross domain issue when you save the URL, the image will be loaded without problem next time.

What do I miss (except create a new issue for this question)?

**Comment by mrdoob** [comment]
> Ok, I just have to add a test on image.src (or image.href) in the toJSON method of Texture.js to have it work as I want, but why is it done that way?

It was done this way to get something working. Eventually your case should be supported too.
