### ISSUE TITLE
Memory leaks (r71)?

### ISSUE THREAD

**Issue by mvellon** [mrdoob/three.js#6635]
I've noticed that, after a while, my program ends up with many unreleased vertex buffers (sorry, code is too messy to post).  If I track down the memory, I see that it's being held by "geometryGroups".  If I put a breakpoint in initGeometryGroups(), I see it getting getting called from initObject. Furthermore, I see that the object being initialized is a Mesh. All makes sense.

If I try to figure out where geometryGroups are released, it seems like deallocateGeometry() is the right place.  It's called from onGeometryDispose which makes sense because initObject added an event listener for this.  Dispose events are generally fired by dispose() methods supported by some THREE objects but not all. And, thus, the problem, THREE.Mesh does not support a dispose method. As far as I can tell, rendering (new) meshes will cause new entries to be added to geometryGroups and eventually things will blow up.

Does this make sense?

**Comment by dubejf** [comment]
My understanding is that `THREE.Mesh` doesn't have a `dispose` method because the components of the mesh (geometry, material, and texture of the material) can be shared by other objects and could still be in use. Thus, they cannot safely be deallocated automatically.

Assuming that your geometries are never shared, you can call `mesh.geometry.dispose()` manually yourself, anytime an object is removed from the scene - ideally wrapped inside `object.traverse`, to dispose of the geometry of all descendant objects. You need to manually manage this part yourself.

After I dispose of a geometry / material / texture, I tend to set `needsUpdate` to true on the disposed entity - this way, I think that the gl buffers will be reallocated in case the entity was still being used in the scene. But I might be mistaken on this.

Take a look at the webgl_test_memory.html example, or how `dispose` is handled in the editor.

**Comment by mvellon** [comment]
Thanks - I see that now. It’s not the mesh that’s put into geometryGroups, it’s the Geometry.


Level11.com





From: dubejf
Sent: ‎Wednesday‎, ‎June‎ ‎3‎, ‎2015 ‎11‎:‎23‎ ‎AM
To: mrdoob/three.js
Cc: Manny Vellon





My understanding is that THREE.Mesh doesn't have a dispose method because the components of the mesh (geometry, material, and texture of the material) can be shared by other objects and could still be in use. Thus, they cannot safely be deallocated automatically.

Assuming that your geometries are never shared, you can call mesh.geometry.dispose() manually yourself, anytime an object is removed from the scene - ideally wrapped inside object.traverse, to dispose of the geometry of all descendant objects. You need to manually manage this part yourself.

After I dispose of a geometry / material / texture, I tend to set needsUpdate to true on the disposed entity - this way, I think that the gl buffers will be reallocated in case the entity was still being used in the scene. But I might be mistaken on this.

Take a look at the webgl_test_memory.html example, or how dispose is handled in the editor.
