### ISSUE TITLE
Shadows should be applied only to shadow casting light.

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#6693]
A shadow should only multiply the light coming from its caster. Instead each shadow multiplies all lights in the scene. This is physically incorrect and impractical for creating good lighting.

To reproduce edit webgl_shadowmap_viewer.html

1. Reduce the intensity of all existing lights to 0. (scene should be completely dark)
2. Add another directional light (not shadow casting)
3. Notice that two shadows are still visible in the new light source.

**Comment by mrdoob** [comment]
Oh! Good catch.

**Comment by nn4e** [comment]
But what about onlyShadow option ?
We can use light source for rendering only shadows and illuminate the scene with another type of light

**Comment by CypD** [comment]
I think this issue has something to do with the fact shadows are casted with shadow darkness parameter, which is NOT physically correct. In real world shadow is just an area where the light doesn't reach, period.
The solution is here: #6420
Unfortunately I am still too busy with other things and don't have the time to implement it correctly yet.

regards

**Comment by mrdoob** [comment]
@CypD Hope you find time soon! 😊

**Comment by MiiBond** [comment]
I added this several years ago in our shaders (verold.com) but I never pushed it back because the solution wasn't great and requires tracking shadow values and then applying it in the lighting calculation. In the next few months, one of the things on my list is to build this back into Three.js. If @CypD wants to do this first, by all means :)

We should, however, keep the option of the "modulative" style of shadows. As @nn4e was saying, being able to use a directional light to only cast a shadow (and no light) can be useful, even if it's not physically correct.

**Comment by mrdoob** [comment]
Fixed! 48d8c5a9112f2171faf7a6949ca2eb0ba17a88e1

**Comment by Sarah-C** [comment]
Now broken!  =(

Using this: https://cdnjs.cloudflare.com/ajax/libs/three.js/88/three.min.js
Demo: https://codepen.io/SarahC/pen/zPjbdK?editors=0010
