### ISSUE TITLE
r72dev, dispose() doesn't release the memory of Geometry()

### ISSUE THREAD

**Issue by brianxu** [mrdoob/three.js#6729]
maybe it's a known issue with the latest change to the WebGLRenderer. looks like the dispose() only releases the memory of the buffer now. So a THREE.Geometry() will always have memory left unclean.
How to reproduce:
in webgl_test_meomry.html, and change the `THREE.SphereBufferGeometry` to `THREE.SphereGeometry`, use chrome's debugger to record the heap usage.

**Comment by dubejf** [comment]
There are still issues with `SphereGeometry` (at least when the dev tools are open).

* With current `r72dev`, this is `SphereBufferGeometry`:
![r72buff](https://cloud.githubusercontent.com/assets/8649151/8894607/dcecdf3e-338a-11e5-9d8c-ee8384e13ed8.PNG)
I'm not sure what's going on with the green line, but otherwise it looks okay. Memory usage is in the 10-20MB range

* This is a recording with `SphereGeometry`:
![r72console](https://cloud.githubusercontent.com/assets/8649151/8894612/024f6594-338b-11e5-95b1-88f9d7a93fc6.PNG)
After 15 seconds, memory usage is 600MB+.

* If I remove `console.log` in `BufferGeometry.setFromObject()`, I get this profile instead for `SphereGeometry`:
![r72noconsole](https://cloud.githubusercontent.com/assets/8649151/8894620/506b0ce2-338b-11e5-91fe-6b75f869e146.PNG)

**Conclusion:** there is too much logging going on. It should be commented out, or it shouldn't print the full geometry details, or the warning should be silenced after a couple of iterations.

Too bad #5791 was reverted. `THREE.warnOnce( )` would be great for this!

**Comment by mrdoob** [comment]
I think it's time to comment `BufferGeometry.setFromObject()`' `console.log()`s :+1:
