### ISSUE TITLE
Blender export fails for multiple materials 

### ISSUE THREAD

**Issue by flow-c** [mrdoob/three.js#6731]
FILES:
------
[This folder](https://myshare.box.com/s/5tsyroa9uhlct9bf89xhkngms722fm3o)  contains two blender projects, their respective THREE.js JSON exports, a texture file and this document:

* *1-material_ok.blend*	--> *1-material_ok.json*
* *2-materials_nok.blend*	--> *2-materials_nok.json*
* *dice.jpg*
* *README.txt*

DESCRIPTION:
------------
* *1-material_ok.blend* defines a cube with a single material and a simple UV texture map. 
==> As expected, the exported .json file contains six quad faces in the format ```[43, v0,v1,v2,v3, m, u0,u1,u2,u3, n0,n1,n2,n3]```, hence 14 entries per face.

* *2-materials_nok.blend* defines an additional material and UV texture map for one of the cube's faces.
==> Now, there are 18 entries per face in the exported .json file, and according to the metadata property it contains 17 faces. If imported with the THREE.JSONLoader, *2-materials_nok.json* doesn't cause an error but it is displayed with the first material only.

USED VERSIONS:
--------------
* Blender v2.74
* JSON exporter v1.4.0 (r71)

**Comment by poofik** [comment]
I ran into this problem too, you have to split your meshes - one material per mesh.

**Comment by repsac** [comment]
In `three` the second UV layer is reserved for light maps

**Comment by WestLangley** [comment]
> In `three` the second UV layer is reserved for light maps

...and aoMaps.

**Comment by flow-c** [comment]
Thanks, I wasn't aware of that convention. 

It seems that only one mesh can be exported at a time, so I'll have to load the different parts of my model into THREE.js separately and somehow group them back together there. Or is there a better way?

**Comment by repsac** [comment]
> It seems that only one mesh can be exported at a time, 

For geometry exports this is true. Have you tried the `Scene` option (and use ObjectLoader instead)?

**Comment by poofik** [comment]
With ObjectLoader you can have many meshes in one file, but only one material per mesh. This is true for thee.js v71 and v72. Since they started improving it with BufferedGeometry they broke multi-material per mesh. I believe v69 this was working with old blender exporter.

**Comment by flow-c** [comment]
Thanks, @poofik and @repsac! THREE.ObjectLoader did the trick!

**Comment by repsac** [comment]
Also; if you are only utilizing one material per mesh/object, and doing scene exports, to possibly use these material settings

- Shading:
Face Materials = False

SCENE:
Materials = True

The reason is that if both are checked then you will get a material entry for the object and a material entry for the geometry. There may be cases, especially with AO or light maps, in which have face materials makes sense. But, at least in my experience, if there is a single material affecting all faces then just having object based material assignments have worked just fine.

Now there may be some work flow or corner case where object material assignments don't work, as I can only speak for the use cases that I have been exposed to. But that is probably a discussion to be had on [Stack Overflow](http://stackoverflow.com/questions/tagged/three.js)

**Comment by erno** [comment]
Does this work now for Blender objects with multiple materials, or was this closed more in the vein of "won't fix"?

**Comment by inear** [comment]
What is the status of this one? Can we use multi materials on skinned meshes? Can't figure out how in rev 81.

**Comment by manthrax** [comment]
Multiple materials on a single mesh doesn't seem to be supported for any case that I can create in Blender.

Is there a plan for addressing this, or must we work around this by doing single material per mesh?

https://www.reddit.com/r/threejs/comments/5kejle/importing_a_model_from_blender_materials_not/

**Comment by poofik** [comment]
Yes someone [fixed it](https://github.com/mrdoob/three.js/pull/8077/commits/98a144be93a26ed0e68c09cf82400a7b5d51bcdd) for Blender exporter, but it was not merged into main repo.

https://github.com/mrdoob/three.js/pull/8087

**Comment by ScoreUnity** [comment]
which version of the exporter did he use?

**Comment by inear** [comment]
This one:
https://github.com/s9k/three.js/tree/exporter-multimat-fix2/utils/exporters/blender

I'm using it and it works great, also with the rev 83.

On Mon, Jan 9, 2017, 20:24 ScoreUnity <notifications@github.com> wrote:

which version of the exporter did he use?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mrdoob/three.js/issues/6731#issuecomment-271381164>,
or mute
the thread

**Comment by wilson0x4d** [comment]
this is also why you shouldn't mark development work "done" until it's merged and tested in a release, best to leave it open, tag it so we know where the "fix" is at instead.
