### ISSUE TITLE
Render not getting properly cleared after using ImmediateRenderObject (depth buffer issue?)

### ISSUE THREAD

**Issue by dmnsgn** [mrdoob/three.js#6783]
Mask a 3D scene with another 3D scene using EffectComposer seems to work fine with basic THREE objects but not with ImmediateRenderObject:

- basic example using THREE.Mesh http://jsfiddle.net/at4rumn6/3/

![maskmesh](https://cloud.githubusercontent.com/assets/1636460/8497271/c548f8a0-2173-11e5-8ff3-3a563ca015b6.jpg)

- MarchingCube example using THREE.ImmediateRenderObject http://jsfiddle.net/Lwm93rxr/2/

![maskimmediaterenderobject](https://cloud.githubusercontent.com/assets/1636460/8497281/d2bc03ce-2173-11e5-8776-b511a34ccca8.jpg)

The render loop is the following:
```javascript
// Render the scene with objects into the WebGLRenderTarget rtMain
renderer.render( sceneMain, camera, rtMain );

// Render the mask scene into the WebGLRenderTarget rtMask
// It contains a mesh with a material coloured red 0xff0000
renderer.render( sceneMask, camera, rtMask );

// Render the composer which has a ShaderPass 
// mixing the two textures rtMain and rtMask passed as uniforms
// gl_FragColor = mix( background, texelA, texelB.r )
composer.render();
```

It looks like something is not cleared after `renderer.render( sceneMain, camera, rtMain );`

I am posting this question as an issue as it might be a limitation in the library.

http://stackoverflow.com/questions/31192322/three-js-render-not-getting-cleared-after-using-immediaterenderobject

---

THREE.WebGLRenderer 71, Chrome 43, Mac OS X Yosemite, NVIDIA GeForce GT 755M 1024 MB

**Comment by brunoimbrizi** [comment]
I investigated this issue a bit further and found that:
- ``WebGLRenderer.renderObjectsImmediate()`` is called on every ``render()``
- ``_webglObjectsImmediate`` (the first parameter) is always the same, regardless of the ``scene`` passed in the render call

https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/src/renderers/WebGLRenderer.js#L3380

In the example above:
```javascript
renderer.render( sceneMain, camera, rtMain );
// WebGLRenderer.renderObjects( opaqueObjects ) nothing to draw
// WebGLRenderer.renderObjectsImmediate( _webglObjectsImmediate ) draws the MarchingCubes blobs

renderer.render( sceneMask, camera, rtMask );
// WebGLRenderer.renderObjects( opaqueObjects ) draws the red cube
// WebGLRenderer.renderObjectsImmediate( _webglObjectsImmediate ) draws the MarchingCubes blobs again -- it shouldn't
```

Is it possible to call ``renderObjectsImmediate`` only for the objects in a given scene?

**Comment by mrdoob** [comment]
Does this still happen in the `dev` branch?

**Comment by brunoimbrizi** [comment]
Unfortunately the issue still happens in the ``dev`` branch - plus there is another issue there that I'll describe here because it is related.

When running the MarchingCubes fiddle above with the ``dev`` three.js, the following error appears:
``Uncaught TypeError: Cannot read property 'side' of null``
``material`` is ``null`` in ``WebGLRenderer.setMaterialFaces()``
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L2082

This happens because ``WebGLRenderer.render()`` calls
``renderObjectsImmediate( objects.objectsImmediate, 'transparent', ...)``
even if there are no transparent objects in the render list.
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1635 

So ``webglObject.transparent`` is ``null`` on this line:
``if ( overrideMaterial === null ) material = webglObject[ materialType ];``
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1787

If the ``renderObjectsImmediate`` call passing the ``'transparent'`` parameter is commented out (line 1635), the error goes away, but the issue described by @dmnsgn still happens as in the ``master`` branch.

**Comment by mrdoob** [comment]
@brunoimbrizi Ok, e48ab82edddf68fc2869440af8edcb33677ec5a5 fixes the new issue. I'll look at @dmnsgn original issue next.

**Comment by mrdoob** [comment]
> - ``_webglObjectsImmediate`` (the first parameter) is always the same, regardless of the ``scene`` passed in the render call

Good catch!

**Comment by mrdoob** [comment]
Fixed!
