### ISSUE TITLE
BufferGeometry design questions

### ISSUE THREAD

**Issue by dubejf** [mrdoob/three.js#6877]
I have a couple of questions regarding the design and goals of `BufferGeometry`.

1) It is well known that a `BufferGeometry` can be reused by multiple `Object3D` of the same kind. For instance, a `BufferGeometry` can be shared by two `Mesh`.

But can a `BufferGeometry` be reused by the two objects of different kinds, say a `Mesh` and a `Line`? And if so, does it require an indexed geometry with `drawcalls`?

2) Can a `BufferAttribute` be reused in multiple `BufferGeometry`. For instance, is it legal to create a bunch geometries sharing a single `position` buffer, but each having its own `color` buffer?

If the `BufferAttribute` wrapper can't be shared, can the typed array `.array` be shared?

3) Are *per-element* attributes going to be supported in `BufferGeometry`? For instance, *color-per-face*. Of course, the *color-per-face* array would need to be unroll into a *per-vertex* temporary array during the `createBuffer` or `updateBuffer` phase of the renderer anytime an update is needed.

**Comment by makc** [comment]
4) Can we get rid of array safely after it made it to gpu?

**Comment by benaadams** [comment]
> 1) But can a BufferGeometry be reused by the two objects of different kinds, say a Mesh and a Line? And if so, does it require an indexed geometry with drawcalls?

No(ish) I found the draws are not happy when you cross the types (e.g. gl.LINES and gl.TRIANGLES) against the same buffer, and the drawcall actually returns an error about binding issues - however I didn't scientifically confirm this was the reason; sometime you get weird errors :) but see 2b) which is a quick work around.

> 2) Can a BufferAttribute be reused in multiple BufferGeometry. For instance, is it legal to create a bunch geometries sharing a single position buffer, but each having its own color buffer?

Yes, easily and the shared data will be uploaded to gpu once and shared between all the objects.

> If the BufferAttribute wrapper can't be shared, can the typed array .array be shared?

Yes, is more "when" rather than "can't" due to different draw types, though this will double load the data to gpu.

There are also the more exotic options of:

[InterleavedBufferAttribute](https://github.com/mrdoob/three.js/blob/dev/src/core/InterleavedBufferAttribute.js) where multiple ```BufferAttribute``` share the same ```.array``` via [InterleavedBuffer](https://github.com/mrdoob/three.js/blob/dev/src/core/InterleavedBuffer.js) so that vertex data can be positioned in proximity:

Which allows you to achieve some of the [best practices for mobile](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html#//apple_ref/doc/uid/TP40008793-CH107-SW10):

![Interleaved Buffers](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Art/interleaved_vertex_data_2_2x.png)

You can mix ```InterleavedBufferAttribute``` with regular ```BufferAttribute``` or [DynamicBufferAttribute](https://github.com/mrdoob/three.js/blob/dev/src/core/DynamicBufferAttribute.js)  when your use cases for the buffers is different, for example one of them gets updated but the other is fixed. (see best practices link above):

![Different usages](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Art/usage_pattern_vertex_data_2x.png)

> 3)  Are per-element attributes going to be supported in BufferGeometry? 

Don't know answer to this; but related to complete the ```BufferAttribute``` picture there is also [InstancedBufferAttribute](https://github.com/mrdoob/three.js/blob/dev/src/core/InstancedBufferAttribute.js) to use with [InstancedBufferGeometry](https://github.com/mrdoob/three.js/blob/dev/src/core/InstancedBufferGeometry.js); which allows you repeat the mesh, but with different per mesh attributes.

Some examples of the exotic types are:

[Buffergeometry Instancing](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_buffergeometry_instancing.html)
[Buffergeometry Instancing - Billboards](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_buffergeometry_instancing_billboards.html)
[Buffergeometry Instancing - Dynamic updates](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_buffergeometry_instancing_dynamic.html)
[Buffergeometry Instancing - Interleaved + Dynamic Updates](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_buffergeometry_instancing_interleaved_dynamic.html)

> 4) Can we get rid of array safely after it made it to gpu?

Yes if you are not going to update it and are not worried what will happen on context loss; but you should also probably be using [DynamicBufferAttribute](https://github.com/mrdoob/three.js/blob/dev/src/core/DynamicBufferAttribute.js) rather than [BufferAttribute](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferAttribute.js) if you are updating as it preps the gpu with hints that this will happen better.

**Comment by mrdoob** [comment]
> HTH and maybe @mrdoob can provide more info on 3) as it sounds like the haunting MeshFaceMaterial shadow...

Ideally there shouldn't be any "magic" (unrolling) when dealing with `BufferGeometry` and `BufferAttribute`.

**Comment by dubejf** [comment]
Thanks @benaadams for your thorough answers. I noticed that there still a few patches pending related to interleaved and instance buffers. Would say that the `dev` branch support for these features is complete enough to start using them? In your experience, is it worth the switch?

I originally asked because I was trying to implement functions to manipulate the geometry in `BufferGeometry`. Functions that are already available on `Geometry` such as `createVertexIndex`, `mergeVertices`, `removeDegenerateFaces`, ...

One small problem is that `BufferGeometry` is just a bag of vertex attributes. It doesn't know how vertices are arranged into elements - this information is stored in the `Object3D` that uses the geometry (`Mesh`, `Line`, ...). This problem could be solved by passing the type of elements in arguments to the function, `geom.removeDegenerateElements( TRIANGLE_STRIP )`.

There are other issues.  Each `Geometry` is independent, with its own set of vertices and faces. With `BufferGeometry`, the current approach seems to be that anything goes. `BufferGeometry`, or the `BufferAttribute`, or typed arrays could be shared with another entity. As you point out, there are good performance/memory reasons to do so. The drawback is that an attempt to clean-up one geometry (say, by modifying its `position` buffer in-place) could affect another entity.

**Comment by mrdoob** [comment]
> One small problem is that `BufferGeometry` is just a bag of vertex attributes. It doesn't know how vertices are arranged into elements - this information is stored in the `Object3D` that uses the geometry (`Mesh`, `Line`, ...).

I've been fighting with this a bit... This why ended up doing [BufferGeometry.setFromObject](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L151-L197). On top of this `material.wireframe` also affects to this :(
