### ISSUE TITLE
plane geometry drawing suggestion

### ISSUE THREAD

**Issue by prieston** [mrdoob/three.js#6916]
By my last reaserch i have been using THREE.PlaneGeometry or THREE.PlaneBufferGeometry for creating topografic applications and by this mean it would be better for real ground visualisation to create a plane havieng 4 triangles for a cell instead of two that there are now. So i am suggesting to add option to the type of the drawing applied in the geometry. What do you think?

**Comment by WestLangley** [comment]
In what sense do you feel 4 triangles per cell is "better"?

As an aside... `THREE.PlaneBufferGeometry` uses indexed `BufferGeometry`, meaning the vertices and normals are shared. That is great for smooth terrains.

For low-poly, faceted terrains, you can use the same geometry, because `MeshPhongMaterial` supports flat shading using screen-space derivatives. (In other words, you do not also need non-indexed geometry with unique normals per face.)

So, perhaps `THREE.TerrainBufferGeometry` could have 4 triangles per cell.

**Comment by Prieston** [comment]
In the topographical logic the elevation points influence the nearest  points by the nearest neighbor logic. So it is arbitrary to connect the bottom left vertex with the top right and not connect the bottom right with the top left cause they are equally distanced. 

So i believe that for this purpose is best to connect both and create 4 triangles instead of two, creating a middle intersection point that its elevation is based on the 4 vertexes elevation and not only two. 

With this you can actually create a triangle hill while with plane geometry it wasn't possible.

- THREE.PlaneBufferGeometry
![proposenow](https://cloud.githubusercontent.com/assets/12699128/8938175/b34b2b22-3565-11e5-9909-5ae63661620c.png)

- THREE.TerrainBufferGeometry
![propose](https://cloud.githubusercontent.com/assets/12699128/8938202/d5b3def2-3565-11e5-8e4c-4c4c30cf9671.png)

**Comment by makc** [comment]
They went beyond this in alternativa3d engine:

![GeoPlane](http://forum.alternativaplatform.com/uploads/attachments/1042=12-triangulation.gif)

This kind of "hexagonal" mesh is more isotropic.

**Comment by WestLangley** [comment]
OK, I hacked up something. We can see if the extra faces help. Maybe @makc's suggestion has merit.

![screen shot 2015-07-28 at 9 51 03 pm](https://cloud.githubusercontent.com/assets/1000017/8948481/b4812d24-3575-11e5-9a9d-5f470846f614.png)

**Comment by Prieston** [comment]
I thinkk it will help though i cannot test it. [@makc](https://github.com/makc) 's suggestion might have merit but its not useful for topographic data.

**Comment by satori99** [comment]
On the contrary, @makc 's suggestion in right on form. [Here is a short paper](ftp://ftp.cs.brown.edu/pub/techreports/05/cs05-14.pdf) explaining why an isometric grid is in many ways prefereable to a regular grid for heightmap terrains.

**Comment by WestLangley** [comment]
As discussed here, and in #6920, there does seem to be interest in alternate tessellations of terrain geometry.

I do not believe `PlaneBufferGeometry` will be changed at this point.
