### ISSUE TITLE
Three does not warn if rendering with a camera that's not in a scene

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#6941]
I just spent a long time debugging an issue that turned out to be because I hadn't added a camera to the scene:

```
scene.add(cubeCamera); // I forgot this line
```

Not only did `cubeCamera.updateCubeMap(renderer, scene)` work, but it produced output! The output was a bit garbled. I'm writing a reflection shader and was convinced the error was in my shader.

There are no warnings for updating the camera when it has no scene parent. I don't think this is a bug, but it would have been nice to have some way to know it was detached. I also have no idea if there'd actually be a use case for rendering a camera without a scene.

**Comment by WestLangley** [comment]
Regarding cameras in general, there is no requirement that a camera be added to the scene -- unless the camera has children (such as a light or a renderable object).

---

For a `CubeCamera`, the relevant line in `WebGLRenderer.render( scene, camera )` is

    		if ( camera.parent === undefined ) camera.updateMatrixWorld();

Since a camera that is a child of a `CubeCamera` has a parent -- the `CubeCamera` itself -- `updateMatrixWorld()` is not called.

Perhaps a fix is in order. It depends on whether this is considered a bug or a feature.

Note that the examples work properly because the  `CubeCamera` is added as a child of the scene.

---

Side note: @mrdoob @gero3 This is an example where `updateMatrixWorld()` requires traversal of children.

**Comment by WestLangley** [comment]
>There is no requirement that a camera be added to the scene.
