### ISSUE TITLE
OrbitControls panning with .target set

### ISSUE THREAD

**Issue by nwrobel** [mrdoob/three.js#6992]
I am having an issue with OrbitControls. I am trying to get the camera.lookAt() method to work correctly in my app, but the OrbitControls keeps calling the lookAt() method on a target when it updates, overriding mine. So I am trying to set the .target to get this functionality working. 

I have set the .target of the OrbitControls to the position of a mesh, and this works fine, but when I try to pan the scene, all the meshes seem to pan but the mesh which I set to be the target stays in the same place. Is this a bug?

**Comment by dubejf** [comment]
Without the code, my guess is that you have *replaced* the `.target` of your control with your mesh origin, using `=`. They now share the same reference a `THREE.Vector3`. Panning translate the `.target`; it translates your mesh origin too, because it's the same point. You need to use `control.target.set( ... )`, not `control.target = ...`. 

Example: https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/examples/webgl_shadowmap_viewer.html#L171

**Comment by nwrobel** [comment]
Thank worked, thank you very much!
