### ISSUE TITLE
MorphAnimMesh and MorphBlendMesh

### ISSUE THREAD

**Issue by tormozok** [mrdoob/three.js#7010]
I found 2 similar classes for playing morph animations. MorphBlendMesh allows to run multiple animations, MorphAnimMesh only one(probably).
I'm not found any docs. I'm not found any example with MorphAnimMesh (Is it works?). They have different interfaces(update/updateAnimation, (setAnimationFPS + playAnimation)/(playAnimation))... 
I confused. MorphAnimMesh is deprecated?

**Comment by Bab64** [comment]
I've close problems with MorphAnimMesh. My app. with R72 no loger works with R73 and R74 (THREE.MorphAnimMesh is not a constructor???)

**Comment by SpiritBreaker** [comment]
THREE.MorphAnimMesh is deprecated??? i think we need to describe it on docs.

**Comment by Bab64** [comment]
I strongly advice to choose between the following strategies:

1. you may still use THREE.MorphAnimMesh. Since it is no longer in the core, you have to include the suitable file located here: https://github.com/mrdoob/three.js/tree/dev/examples/js/THREE.MorphAnimMesh.js (please download the very last THREE release: R79)
2. You throw overboard THREE.MorphAnimMesh and you adopt the new approach for animation in THREE. Unfortunately, your require a lot of re-work in your app. The new support for animation in THREE is poorly illustrated. For basic understanding, I advice to look at this app: morphtargets horse (Browse examples in R79)
3. (I personnaly choose this one): Drop off THREE.MorphAnimMesh and reuse http://www.createjs.com/tweenjs. From experience, TWEEN.JS is easy to understand and can be integrated with THREE without difficulty.

Hope this helps

**Comment by looeee** [comment]
@tormozok can this issue be closed?

**Comment by rohan-deshpande** [comment]
I've run into this issue when porting my app to ES6 and using modules. I need to use `SceneLoader` as there is no replacement for this yet, even though it was removed from `three` entirely. 

I've got `SceneLoader` ported to ES6 (simply doing `import * as THREE from 'three'` and then export { SceneLoader }`) but it's complaining that `MorphAnimMesh`, which `SceneLoader` uses, is not present in `three` anymore. 

The block of code in question is 

```
else if ( objJSON.morph ) {

object = new THREE.MorphAnimMesh( geometry, material );

if ( objJSON.duration !== undefined ) {

	object.duration = objJSON.duration;

}

if ( objJSON.time !== undefined ) {

	object.time = objJSON.time;

}

if ( objJSON.mirroredLoop !== undefined ) {

	object.mirroredLoop = objJSON.mirroredLoop;

}

if ( material.morphNormals ) {

	geometry.computeMorphNormals();

}
```

I'm tempted to simply comment it out and see what happens but if I could get a solution that would be great.

**Comment by mrdoob** [comment]
>  I need to use `SceneLoader` as there is no replacement for this yet, even though it was removed from `three`. 

Oh? `ObjectLoader` is supposed to be the replacement of `SceneLoader`.

**Comment by rohan-deshpande** [comment]
It doesn't work the same way though, I tried it during my upgrade and just couldn't get it to work the same way :( I've made a stackoverflow post about it somewhere. It's fine though, `SceneLoader` still works, just had to do these little changes for my ES6 migration.
