### ISSUE TITLE
Should groups/drawcalls/offsets go in Mesh?

### ISSUE THREAD

**Issue by ikerr** [mrdoob/three.js#7092]
I was looking through the `BufferGeometry` source and noticed that `computeVertexNormals()` and `computeTangents()` assume that `BufferGeometry` stores triangles. For example:

```
for ( i = start, il = start + count; i < il; i += 3 ) {
```

But what happens if `BufferGeometry` is being used with `PointCloud` or `Line`, for example? I suspect that a runtime exception will be thrown or that incorrect normals/tangents will be computed.

This leads me to ask the question, why does `BufferGeometry` know about the ranges of vertices to draw, but not about the primitive type? The two are related, but currently exist in different parts of the implementation. Should `groups`/`drawcalls`/`offsets` be moved to `Mesh`, `Line` and `PointCloud`, where the primitive type is known?

Alternatively, the primitive type could be pushed _down_ to the `groups` level, so that a group looks like this:

```
{
    primitive: 'triangles', // one of 'points', 'lines', 'triangles', 'triangleStrip', 'triangleFan', etc.
    start: 32,
    count: 9,
    materialIndex: 1
}
```

If this approach were taken, it might make sense to refer to `groups` as `primitives`. The consequence of this is that a `Mesh` could contain several primitive types (e.g., points, lines, triangles), eliminating the need for separate `Mesh`, `Line` and `PointCloud` types. This would be a more drastic change than the first, so is likely not realistic, but I thought I'd throw it out there.

Thoughts on either approach?

**Comment by WestLangley** [comment]
Yes. I agree that `drawcalls` should be a property of `Mesh`, `Line`, `LineSegments`, and `PointCloud`, instead.

And `groups` should be renamed back to `drawcalls`, which is what they are. (Sorry, @mrdoob, I am not a fan of the `groups` property name.)

The renaming of `MeshFaceMaterial` to `MultiMaterial` was the right thing to do, as it now can apply to an array of any material types.

I know that @mrdoob has worked very hard to implement the current system, but I believe this approach is the right way to go.

**Comment by mrdoob** [comment]
I think we're mixing issues here...

What we have done in this cycle is remove the `Geometry` code path from `WebGLRenderer`. To do that we are "internally" converting `Geometry` to `BufferGeometry`. In the process, `BufferGeometry` gained support for skinning, morphTargets and multi materials.

The problem was that we had to convert `Geometry`'s `face.materialIndex` to `BufferGeometry`. So the challenge was to end up with 2 types of geometries that represent the same.

I don't think `WebGLRenderer` should add stuff to `Mesh` when converting. Maybe we can redesign things later, but at the moment the focus was on producing the same output without touching the user's objects.

> And `groups` should be renamed back to `drawcalls`, which is what they are. (Sorry, @mrdoob, I am not a fan of the `groups` property name.)

Yep, I'm aware. But I think `groups` is less limited. We're probably going to add `boudingSphere` to each group so we can better sort transparent elements. At that point it becomes more than just a drawcall.

Going back to @ikerr's issue...

I would rather create subclasses of `Geometry` (`MeshGeometry`, `LineGeometry`, `PointsGeometry`, ...).
