### ISSUE TITLE
Texture from canvas conflict with SCISSOR_TEST

### ISSUE THREAD

**Issue by NicolasMaciol** [mrdoob/three.js#7181]
Hello,

When creating a texture from a canvas and using it into a viewport the display texture is clipped.
Code looks like this:

	// Create the canvas
	var canvas = document.createElement('canvas');
	canvas.width = canvas.height = 1024;
	var context = canvas.getContext('2d');

	// Texture from canvas
	var texture = new THREE.Texture(canvas);
	
	// Load an image
	var imageObj = new Image();
	imageObj.src = "images/lightMap.jpg";
	imageObj.onload = function()
	{  
		context.drawImage(imageObj, 0, 0, 512, 512, 0, 0, canvas.width, canvas.height);
		texture.needsUpdate = true;
	};  
      
	// Create a material using the texture
	var material = new THREE.MeshBasicMaterial( {map: texture, side:THREE.DoubleSide} );

	// Create a plane using the material
	var mesh = new THREE.Mesh(
		new THREE.PlaneGeometry(200, 200),
        	material2
	);

	// ...

	// Render the scene in a viewport
	renderer.setViewport(50, 50, 512, 512);
	renderer.setScissor(50, 50, 512, 512);
	renderer.enableScissorTest(true);
	renderer.render( scene, camera );

Here is the patch I write to correct it (end of this.uploadTexture in WebGLRenderer.js) :

	} else {
		// PATCH: You need to disable scissor test when rendering canvas onto texture
		var oldScissor = _gl.getParameter( _gl.SCISSOR_TEST );
		_gl.disable( _gl.SCISSOR_TEST );
		
		_gl.texImage2D( _gl.TEXTURE_2D, 0, glFormat, glFormat, glType, texture.image );
		
		// PATCH: You need to restore scissor test after
 		oldScissor ? _gl.enable( _gl.SCISSOR_TEST ) : _gl.disable( _gl.SCISSOR_TEST );
	}

	}

	if ( texture.generateMipmaps && isImagePowerOfTwo ) _gl.generateMipmap( _gl.TEXTURE_2D );

		texture.needsUpdate = false;

		if ( texture.onUpdate ) texture.onUpdate();

	};

Hope it will help.

**Comment by mrdoob** [comment]
Do you mind creating a working jsfiddle to illustrate the issue?

**Comment by OlexandrPopov** [comment]
I have the same. My texture disappears when scissor test is enabled. However I'm not sure that it's an issue with three.js because I have this issue only when my app is running in Google Chrome. It looks like a memory issue.
Please take a look at this sample http://stackoverflow.com/questions/32462322/black-texture-in-google-chrome

**Comment by mrdoob** [comment]
Sorry guys, can you provide simple example?

**Comment by OlexandrPopov** [comment]
I updated my sample. Now there are only two cameras(orthographic and perspective), axis and camera helpers, a plane with a canvas texture.
Here is link to the sample http://codepen.io/OlexandrPopov/pen/RWPQmm

**Comment by WestLangley** [comment]
@OlexandrPopov 

1. Why are you removing and adding a plane to the scene each frame?
2. Type `renderer.info` into the console. You are not disposing of your objects properly.

**Comment by OlexandrPopov** [comment]
@WestLangley 

> Why are you removing and adding a plane to the scene each frame?

I thought it's a simplest way to update object, isn't it? I do that in the same way in my real project.

> Type renderer.info into the console. You are not disposing of your objects properly.

Do you mean that geometries and textures aren't removed from the scene? How is that possible?
I thought the following line removes the mesh.

`plane && scene.remove(plane);`

**Comment by OlexandrPopov** [comment]
Updated the sample. Now the plane is always on the scene and only its texture is updated.

**Comment by WestLangley** [comment]
@OlexandrPopov Please use stackoverflow for help. If you are not certain it is a three.js bug, we prefer you first seek help on stackoverflow. If you can demonstrate a three.js bug, please file your own bug report.

@NicolasMaciol Can you provide a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by OlexandrPopov** [comment]
**three.js versions**
v70, v71

**operating system, browser version, and graphics card**
Windows 8.1
Google Chrome version 45.0.2454.85 m 
Opera 32.0.1948.25
NVIDIA GeForce GTX 660 2GB

Mac OS 10.10.5
Google Chrome version 45.0.2454.85 (64-bit)
AMD Radeon HD 6770M 512 МБ

Mac OS 10.10.5
Google Chrome version 45.0.2454.85 (64-bit)
Intel HD Graphics 5000

**issue description**
There are 2 viewports in my project. First one takes all window and the second one takes a small rectangle in the bottom right corner. Also there is a plane on my scene. The plane has a texture that is updated in every frame. I don't need to show the plane in the first viewport, so I hide it. But I need it to be shown in the second viewport. The code looks like this:

    // make the plane invisible in the first viewport
    plane.visible = false;
    // render the first viewport
    renderer.enableScissorTest(false);
    renderer.setViewport(0, 0, window.innerWidth, window.innerHeight);
    renderer.clear();
    renderer.render(scene, camera);

    // make the plane visible in the second viewport
    plane.visible = true;
    // render the second viewport
    renderer.enableScissorTest(true);
    renderer.setScissor(window.innerWidth - WIDTH, 0, WIDTH, HEIGHT);
    renderer.setViewport(window.innerWidth - WIDTH, 0, WIDTH, HEIGHT);
    renderer.clear();
    renderer.render(scene, orthographicCamera);

The problem is that my texture disappears. I don't see my texture in the second viewport.

**test-case**
http://codepen.io/OlexandrPopov/pen/RWPQmm?editors=001
I expect to see green rectangle in the second viewport.

**live app**
http://popov.skyboxua.com/corebox/develop.html
I expect to see something like this https://dl.dropboxusercontent.com/u/12339427/corebox/empty2.PNG
Note: Go to fullscreen mode to reproduce the issue (https://dl.dropboxusercontent.com/u/12339427/corebox/fullscreen.PNG).

**screenshots**
https://dl.dropboxusercontent.com/u/12339427/corebox/no_texture1.PNG
https://dl.dropboxusercontent.com/u/12339427/corebox/no_texture.PNG

**Comment by mrdoob** [comment]
> **test-case**
http://codepen.io/OlexandrPopov/pen/RWPQmm?editors=001
I expect to see green rectangle in the second viewport.

Took me a while, but I now understand what the bug is. I'll take a look tomorrow!

**Comment by OlexandrPopov** [comment]
Hi guys, 

Is there any update on this issue? How do you think the NicolasMaciol's solution is the right way to resolve the issue?

**Comment by mrdoob** [comment]
@OlexandrPopov can you confirm this is still a problem?

**Comment by OlexandrPopov** [comment]
No, I can't reproduce the issue anymore. Tested on: 
Mac OS 10.11.2
Intel HD Graphics 5000
Google Chrome 47.0.2526.111 (64-bit)
Google Chrome 48.0.2564.82 (64-bit)

**Comment by mrdoob** [comment]
Yay!
