### ISSUE TITLE
r72 : RenderTarget.shareDepthFrom does not work

### ISSUE THREAD

**Issue by yomotsu** [mrdoob/three.js#7234]
`RenderTarget.shareDepthFrom` is not working.

As you can see, it was working in r70, however, WebGLRenderer.js has been changed and depthBuffer cannot be bridged.

in r71
![screen shot 2015-09-25 at 6 45 40 pm](https://cloud.githubusercontent.com/assets/212837/10097712/f6c35b9e-63b5-11e5-99e7-3a7cc932aa8f.png)

in r72
![screen shot 2015-09-25 at 6 45 25 pm](https://cloud.githubusercontent.com/assets/212837/10097711/f6c300ae-63b5-11e5-8dce-3b4125e6eda3.png)

Here is the actual demo.
https://jsfiddle.net/52uav5gk/

I think, the problem is here.
https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L3093

It used to be like this
```
renderTarget.__webglRenderbuffer = renderTarget.shareDepthFrom.__webglRenderbuffer;
```

But in r72, depthBuffer of another renderTarget is not bridged.
```
renderTargetProperties.__webglRenderbuffer = renderTarget.shareDepthFrom.__webglRenderbuffer;
```

`renderTarget.shareDepthFrom.__webglRenderbuffer;` returns `undefined`.

Is there any good idea to share the buffer between renderTargets...?

**Comment by kintel** [comment]
It's a good idea. See also my depth texture branch, where I also support sharing target textures for rendering. If we had an official examples or test using this feature, it would be easier to test and improve.

**Comment by mrdoob** [comment]
> If we had an official examples or test using this feature, it would be easier to test and improve.

That sounds good. Could someone create one?

**Comment by mrdoob** [comment]
Ohm... #5402 has quite a lot of changes...

**Comment by kintel** [comment]
@mrdoob The changes in #5402 should be pretty straight-forward. I'd be happy to split it up if that makes sense - not sure what can reasonably be split up though, apart from the RenderTarget.texture thing.

**Comment by mrdoob** [comment]
Yeah, let's start with RenderTarger.texture and once that's done and tested we can add the rest 😊

**Comment by kintel** [comment]
@yomotsu I think this problem is a bit more complex that it appears:

three.js recently changed how it handles GL resource internally (see 4c7239ebcb048d3d46b9ebd7a1a703449c437659): It now tracks resources using property objects, in order to separate GL resources from renderers and scenes. It's perfectly legal to share GL resources between renderers, as long as the renderers are attached to the same canvas. However, the renderer in question needs to keep track of which resources was created and which was just shared in order to correctly deallocate said resources. This tracking hasn't been implemented, so we need to be careful to not simply copy these GL resource references around.

This is also an issue for #5402, as that branch also allows for sharing target textures from an external source. @mrdoob Do you have any ideas off the top of your head how to deal with such resource management (I'm not familiar with the rest of the three.js codebase yet).

**Comment by yomotsu** [comment]
@kintel Thanks for considering this issue. I understand, its going to more efficient way.

**Comment by kintel** [comment]
I've written an initial attempt at supporting such sharing: https://github.com/kintel/three.js/tree/webglrendertarget-sharing

Using this, it's possible to share either target textures, depth buffers or both. See example webgl_rtt_share.html.
I didn't yet have time to look at your example.

**Comment by mrdoob** [comment]
> This is also an issue for #5402, as that branch also allows for sharing target textures from an external source. @mrdoob Do you have any ideas off the top of your head how to deal with such resource management (I'm not familiar with the rest of the three.js codebase yet). 

I think sharing depthTextures between renderers is a bit of a stretch... Not sure we should try to support that.

**Comment by kintel** [comment]
Ok, I'll resubmit the depth texture PR without resource sharing as a first, clean, step.
