### ISSUE TITLE
dev: Shadow maps exploding on >1 devicePixelRatio systems

### ISSUE THREAD

**Issue by kintel** [mrdoob/three.js#7239]
The dev branch somehow cannot handle shadows on systems with devicePixelRatio > 1.
The symptom is that the textures used double in size every frame and eventually become too large to use. No visuals are produced after that point.

A number of examples are broken due to this, e.g.:
examples/webgl_loader_stl.html
examples/webgl_shadowmap.html
examples/webgl_materials_cubemap_dynamic.html
examples/webgl_materials_bumpmap_skin.html

This one does work (as it doesn't actually use the devicePixelRatio, thus causing pixelated rendering):
examples/webgl_shadowmesh.html

**Comment by mkkellogg** [comment]
@mrdoob @kintel 

It looks like this bug is manifesting due to recent updates to ```WebGLShadowMap.js``` that save and restore the viewport during shadow map rendering. However, it appears the actual cause is a discrepancy in ```WebGLRenderer.js``` between these two functions:

```
	this.setViewport = function ( x, y, width, height ) {

		_viewportX = x * pixelRatio;
		_viewportY = y * pixelRatio;

		_viewportWidth = width * pixelRatio;
		_viewportHeight = height * pixelRatio;

		_gl.viewport( _viewportX, _viewportY, _viewportWidth, _viewportHeight );

	};
```

```
	this.getViewport = function ( dimensions ) {

		dimensions.x = _viewportX;
		dimensions.y = _viewportY;

		dimensions.z = _viewportWidth;
		dimensions.w = _viewportHeight;

	};
```

As you can see, the values **```_viewportWidth ```** and **```_viewportHeight```** are multipled by **```pixelRatio```** before setting the view port. However when calling ```getViewport()``` those values are not divided by **```pixelRatio```**, so the original values may not correctly be recovered.

I can work around this bug by setting **```pixelRatio```** to 1 during the rendering of the shadow maps, but that doesn't address this discrepancy. What would be the best way to proceed in this case?

**Comment by mrdoob** [comment]
@WestLangley good catch!

**Comment by WestLangley** [comment]
It wasn't I.    : - )

@mkkellogg nice find.

It also seems that in `WegGLShadowMap.js` 
```javascript
// save the existing viewport so it can be restored later
_renderer.getViewport( _vector4 );
```
should be moved outside the `for` loop.

And, of course, there needs to be an adjustment for `pixelRatio`.

**Comment by mkkellogg** [comment]
@WestLangley I will make that change to ```WegGLShadowMap.js```

Should I update ```getViewport ()``` in ```WebGLRenderer.js``` to properly account for ```pixelRatio```?

**Comment by mrdoob** [comment]
> It wasn't I.    : - )

Ops, the avatar confused me 😅

**Comment by mrdoob** [comment]
Fixed it directly. Thanks guys!

**Comment by kintel** [comment]
thx - confirmed to work for me as well!
