### ISSUE TITLE
Syntax error on delete. Reserved keyword.

### ISSUE THREAD

**Issue by myxibrium** [mrdoob/three.js#7298]
I am seeing the word "delete" being used as a function name in several places in the threejs source code.

I see the issue in these source files:

WebGLGeometries.js
WebGLProperties.js
WebGLRenderer.js

And this is ironic considering the proper use of the keyword is illustrated in the implementation of the offending method.

I thought, maybe it's a different ECMAScript version, but I did some research and this has been a keyword since the very beginning, so I'm very confused how this is even possible. By what standards is this valid syntax?

**Comment by mrdoob** [comment]
Do you mind liking to the spec you're referring to?

**Comment by GGAlanSmithee** [comment]
Maybe he' srefering to [this](http://www.ecma-international.org/ecma-262/6.0/#sec-delete-operator) ?

This is a newer (the latest?) spec, but as he said, delete has been a keyword since the conception of ES I belive.

**Comment by mrdoob** [comment]
Maybe he means that we can't used `get` and `delete` as object properties/methods?
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLProperties.js

**Comment by GGAlanSmithee** [comment]
I guess so..

I'm not sure where this "Syntax error" is being encountered, but it sure isn't from using `delete` as an identifier. [jsfiddle](https://jsfiddle.net/0dnzow9u/)

Im guessing @myxibrium just think its bad practise? There's nothing in the [mozilla reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords) about it being restricted. Looking at [this older SO answer](http://stackoverflow.com/a/17911822/3303776) there is a quote from the same reference stating that you should indeed *not* use a keyword as an identifier, but that quote is a few years old and it looks like it has been removed since.

**Comment by mrdoob** [comment]
Done. Thanks!

**Comment by myxibrium** [comment]
In case anyone is interested, I figured out the real issue. I am using Eclipse which validates javascript against ECMAScript 3, and this IS in fact a syntax error in ECMA 3 because it doesn't allow for keywords to be used as identifiers or properties. In ECMA 5, keywords cannot be used for identifiers, but can be used for properties. So this is technically legal now. So I will track down how to update my validator in Eclipse.

Thanks

**Comment by mrdoob** [comment]
I may revert to delete then... 😑

**Comment by myxibrium** [comment]
Trying to get this working in eclipse is a shitstorm. Apparently you can't turn off the outdated syntax validation. https://github.com/Nodeclipse/nodeclipse-1/issues/70

If you could change the method name, it would be super helpful for other Java developers in the future. Just saying ^///^

**Comment by Mouvedia** [comment]
@mrdoob `['delete']` would work just fine.
