### ISSUE TITLE
self not supported in node.js

### ISSUE THREAD

**Issue by emnh** [mrdoob/three.js#7306]
Ading self = this solves the problem.

**Comment by mrdoob** [comment]
#7268

**Comment by MasterJames** [comment]
Would this kind of thing there,  or early in initialization somewhere be wise or wasteful.

   if(self === undefined) self = this;

Or maybe there's already a worker-only block executing it could go with?

**Comment by emnh** [comment]
"if(self === undefined) self = this;" doesn't work (still reports self is undefined), but I put it in this clause  at the top:

} else if ( 'undefined' !== typeof exports && 'undefined' !== typeof module ) {

    module.exports = THREE;

    self = this;

}

**Comment by drone1** [comment]
@emnh's solution solution did not work for me, since 'this' is undefined at that point (for me, at least).

I threw this in, after the initial var THREE = { REVISION: ... } at the top of the file and it works on both server and client for me:

var self = ( 'undefined' !== typeof window ) ? window : {};

**Comment by drone1** [comment]
Looks like this issue is moot now, at least in dev. I don't see any references to 'self' anymore.
