### ISSUE TITLE
feature this!

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7308]
someone at esa did [this comet explorer](https://twitter.com/ESA_Rosetta/status/652017640660185088). not that mega impressive and has some runtime errors, but it is space stuff. kids used to love space stuff. :rocket:

**Comment by mrdoob** [comment]
Nice! Featured it in the Google+ page.
https://plus.google.com/+ThreejsOrg/posts/UAhgABWw8Ue

We should find a way to get people to produce json files using `BufferGeometry` instead of `Geometry` though... Seems like they used objconverter. I was going to remove that, but maybe it's better to update it so it outputs `BufferGeometry` based jsons...
