### ISSUE TITLE
KeyFrameAnimation doesn't loop with Collada model

### ISSUE THREAD

**Issue by LSERRE** [mrdoob/three.js#7344]
KeyFrameAnimation loop option doesn't work as expected. When i try to import a Collada model, the model is in my scene and the animation works as expected but without looping despite the loop attribute as true.

I'm maybe wrong because i'm not a Three.js expert, just want to know if the problem comes from my code or the library. I know github issues are not for support anymore so you can see my code if needed on [Stackoverflow](http://stackoverflow.com/questions/33126100/keyframeanimation-with-collada-model-doesnt-loop)

**Comment by mrdoob** [comment]
Is this something that used to work before r72?

**Comment by LSERRE** [comment]
I don't know, I just did a mistake in the issue title, sorry.

**Comment by Threstle** [comment]
I noticed problems with looping in collada some weeks ago. It did loop, but the animation wasn't smooth at all, and it skipped frames. I ended up setting the loop attribute at false and loop manually.

**Comment by LSERRE** [comment]
@Threstle how could I loop manually properly please?

**Comment by Threstle** [comment]
I check the current time of the animation in the animation loop, and I restart it if it's equal to the full length. It's a dirty workaround, but it worked for me. Hope it will for you !

```javascript
if(anim.currentTime==anim.data.length){anim.stop();anim.play();}
```

**Comment by LSERRE** [comment]
@Threstle  It's working, thanks!

**Comment by ramirofages** [comment]
Hi, I don't know if I should post a comment here or create a new issue, but here it goes. 

In my case the fix by Threstle didn't work, because anim.currentTime is updated as it should, this means that when it gets to the end of the animation it resets correctly to 0 and starts again. 
The problem is that this is not reflected in the model, it just stands still in the last frame of the animation. Any ideas?
