### ISSUE TITLE
WebGL-based Prefiltered Mipmaped Radiance Environment Map (PMREM) generator

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7402]
Thanks to @WestLangley's Physical material, we now need a proper prefiltered mipmapped radiance environment map generator to generate both the prefiltered specular cube maps as well as the prefiltered irradiance/diffuse cube maps.

We can use this tool to create them off line, but it is very inconvenient also this tool is slow:

https://seblagarde.wordpress.com/2012/06/10/amd-cubemapgen-for-physically-based-rendering/

It would best if we could generate them using the GPU so that generate was fast.  If generation becomes less than 50ms on most hardware, we can use this live rather than downloading the PMREMs.  Having it run real-time would be incredibly useful for doing live LightProbes (that would be awesome!)

Requirements:

- Float32 input textures in a cube map pattern (which cube map pattern doesn't matter, because we can likely convert to any format from any format.)
- Ability to generate guassian or cosine power filtered specular cube maps.
- Ability to specify the set of filter sizes desired.  Sometimes people want a full mipmap full, other times they just want 4 levels.
- Ability to create an irradiance map (for DiffuseLightProbes)
- Output should also be in a cubemap float32 format (we can convert to any format afterwards.)
- We'll want to have some utility methods to map one cubemap type to another - such as latlong to samplerCube, to 2D packed cubemap (i.e. cubeToUV), and eventually to the tetrahedral format.  This will be useful for both the input and output conversion. 

I highly recommend that we make the texture format RGBM encoding/decoding to be optional, because sometimes you want this and other times you do not.

My recommendation is that we use a samplerCube internally to this function to keep it simple.

BTW PlayCanvas has one of these here:

https://github.com/playcanvas/engine/blob/master/src/graphics/programlib/chunks/prefilterCubemap.frag

Does anyone want to try their hand at this?

**Comment by bhouston** [comment]
It may be best to try to accurately select Specular and Diffuse CubeMap LOD numbers using the approach linked here first, before writing our own sampler: #7411

**Comment by tschw** [comment]
Nice first shot at a spec.

> Does anyone want to try their hand at this?

Eventually, but I currently don't have enough time to give it the love it deserves. For now, I'll just add some notes, so we can make some progress by refining the spec:

There are two different projections one can use for a cubemap:
 1. A planar projection of a rectangular frustum for each side (this is what you get from a GL renderer and what is assumed by `samplerCube`).
 2. An equiangular projection (in this case, every texel represents the same area on a sphere).

In case we're talking about non-equiangular projections of any kind, there are two fundamentally different approaches to filtering:
 1. Apply the kernel to actual texels.
 2. Apply the kernel to equiangular sphere patches.

In either case we have to filter over the seams for seamless results. In the first case we have to consider the underlying projection but can get away with "Nearest" filtering. In the second case we can ignore the projection but we need seamless filtered sampling to be in place. 

Approach 1 accepts the projective distortion and passes it on through the levels. This is the assumption made by mipmapping: The result is sound in this case, because the coordinates and their derivatives are similarly distorted.

Approach 2 attempts to keep the distortion local to each LOD level. This is how we'd want to filter in order to approximate accumulated radiance over sphere patches of a fixed size. However, this approach is not suitable for mipmapping. 

Lumping both mipmapping and diffuse reflection together is in fact a hack, although a common and considerable one, especially in the context of real-time rendering. For us, keeping both properly separated should be at least worthwhile to consider as well: 
The extension that allows to select the GL LOD manually is not guaranteed to be available and it will also allow "filtering approach 2" (see above) along the diffuse reflection dimension. Given seamless prefiltering and manual sampling, mipmapping will be seamless - orthogonal to the diffusion, and automatic - without the need for a GL extension! The downside is, that this approach won't work well for real-time diffuse reflection mapping - generating NxM levels is relatively expensive. So ideally we'd want both options.

Talking about extensions, Float32, although widely supported, is not guaranteed to be available either. So in fact we just want to work with any pixel format and it's probably the least of all problems at implementation level. Why not just specify it that way? 

To
> accurately select Specular and Diffuse CubeMap LOD numbers

...is in fact a myth: It means that one has to consider the distortion of the panoramic projection that applies to the size of the integrated area for mipmap levels. Just taking the integral over an entire image (as cited article does, correctly calling it an approximation) in reality models different amounts of roughness for the same constant value depending on where the panoramic map got sampled. Even that part considered, linear interpolation of two integrals on an exponential scale (caused by the fractional level) certainly does not yield the sought integral in between, but again just an approximation. I think we should be aware of that and thus not call it "accurate" because it isn't anywhere near it - it's simply what we can get for cheap.

I think we should focus on single image cubemaps in the first iteration for the following reasons: 
 * They can be processed in one shot by rendering the quads and passing the parameters via vertex attributes, 
 * they are currently 2:1, so we can add a full pyramid of LOD levels without requiring higher implementation limits,
 * according to [webglstats](http://www.webglstats.com), the required implementation limits are not higher as for cube maps specified via six individual images (note using those *would* bump the required limits),
 * the result will be fast enough to allow real-time diffuse reflection mapping,
 * as discussed above, different projections require different considerations - I think trying to apply a general scheme right from the start will complicate the design process and has potential to cause a mess.

Then I suggest we have two modes:
 * **Quality mode** in this case we generate one dimension representing the area of accumulation into the (then square shaped) image and generate one dimension of (seamless) mipmaps for the resulting images.
 * **Performance mode** in this case we generate a single, mipmapping compatible dimension of LOD levels into the (then square shaped) image and get away with two shots; one for X and one for Y running X/Y-separated filters for a complete panoramic map (note it's possible to use a single shot but with an insane amount of overhead - for a 7x7 filter we're talking about 49 vs. 14 samples - we wouldn't want to go there).

Once this stuff is in place, it's easy to grow from there: Filtering e.g. Latitude/Longitude probes or irradiance maps will be about disabling stuff and changing the innermost code that does the filtering (I consider the latter "architecturally trivial", these want to use "performance mode" style filtering but do not necessarily need mipmaps), and the skeleton code for addressing the quads in the single-image cubemap can be extended to instead address the triangles in a tetrahedral map.

>  If generation becomes less than 50ms on most hardware

I think we should confidently aim at a higher goal. After all, Three.js is a general purpose rendering library, not just a viewer for static scenes.

**Comment by Usnul** [comment]
+1 just to show interest. I have used AMD's tool, and can vouch that is it frankly too slow. It's also unreliable and not maintained anymore. Radiance maps do add a lot to the final image and I have used them in the past and will continue using them in the future most likely. It's one of those things that if you never used it - you don't think much of it, but once you do - you're asking yourself how you could live without it.

**Comment by bhouston** [comment]
Another link to code and discussions: http://http.developer.nvidia.com/GPUGems/gpugems_ch18.html

**Comment by bhouston** [comment]
Another great reference: https://www.cs.ubc.ca/~heidrich/Papers/RW.00_2.pdf

**Comment by bhouston** [comment]
One more: http://web4.cs.ucl.ac.uk/staff/j.kautz/publications/glossyGI00.pdf

**Comment by cdata** [comment]
@bhouston kind of bummed that all of your links are 404 now :( I was hoping to read up on this topic

**Comment by moraxy** [comment]
@cdata in order:
http://developer.download.nvidia.com/books/HTML/gpugems/gpugems_ch18.html
https://vccimaging.org/Publications/Kautz2000UAP/Kautz2000UAP.pdf
http://jankautz.com/publications/glossyGI00.pdf

**Comment by NoxWings** [comment]
I was also reading this right now. What a coincidence! 
Thank you!!
