### ISSUE TITLE
Using MultiMaterials with ObjectLoader

### ISSUE THREAD

**Issue by arturitu** [mrdoob/three.js#7415]
When I tried to import from Blender meshes from a Blender scene with multiple materials don't work correctly with ObjectLoader. ( I think is because json has't assign correctly the material to the object, it uses a single uuid. (this happens in previous versions of three.js & blender exporter ( It is nothing new of this r73 version ) ).

I can only use MultipleMaterial with JSONLoader ( although with the R73 I have to remove 'DbgColor' & 'colorAmbient' info from .json file ) but in this case I need a json flie for every object.

Here an example > http://unboring.net/lab/7415/
And the source files > http://unboring.net/lab/7415/7415.zip

**Comment by mrdoob** [comment]
I'll take a look. Thanks for the files!

**Comment by mrdoob** [comment]
So seems like this is a Blender exporter issue (ping @repsac).

However, I've added `materialIndex` support to `Geometry.toJSON()` 😶 and robustified `MultiMaterial.toJSON()`, so... as a temporal workaround, you should be able to drag the file in the editor and export from there.

**Comment by arturitu** [comment]
Thanks for all!

I have tried to drag into the r74dev editor the .obj file ( converted directly from ringScene.blend file ) but only appears one of the materials. I suppose that I'm missing something, but don't worry, I'll wait for the fix for the next work... or I'll be back to try with the editor again.

**Comment by mrdoob** [comment]
No no. Drag the .json file 😊

**Comment by PaulSos** [comment]
We are running into the same problem. We want to use multiple materials on an object in a scene with more than 1 object. When exporting the scene only 1 material per object is applied. We are using the ObjectLoader because JSONLoader is deprecated.

**Comment by mrdoob** [comment]
Can you try the editor in the `dev` branch?

**Comment by arturitu** [comment]
With the editor in the dev branch, when I drag the .json file exported directly from Blender, only appears one of the materials. I am exporting in a wrong way?

- Files used ( .blend & .json ) > http://unboring.net/lab/7415_fixed/ringScene.zip
- Screenshot >

![image](https://cloud.githubusercontent.com/assets/5744112/10837710/03dc5a98-7ebd-11e5-9059-d06a1a9cf595.png)

**Comment by mrdoob** [comment]
Ok. Took a while to figure out but the issue is that the Blender exporter doesn't export `MeshFaceMaterial`/`MultiMaterial`. The `ObjectLoader` neither knows how to handle the materials that JSONLoader produce. We definitely need to clean this up.

In the meantime, your best bet is to use vertex colors instead (you'll have to duplicate the vertices).

**Comment by PaulSos** [comment]
After some testing we discovered when using face materials option (from Shading group) in the exporter materials are saved in the geometries. But object loader ignores them and uses only materials from root node.

What do you mean with duplicate the vertices? Do we only have to enable the vertex colors option while exporting?

**Comment by mrdoob** [comment]
> What do you mean with duplicate the vertices? Do we only have to enable the vertex colors option while exporting?

In @arturitu case, he is coloring faces, so he will have to duplicate vertices if we wants to use vertex colors.

**Comment by PaulSos** [comment]
Ahh ok, so thanks a lot.

Maybe you also got an Idea for our Problem too?
We want to Build a City. When we texture the objects, we only can use one material per object at the moment, cause when we export the scene to a .json file, only one Material is linked.
Is there maybe another Way to texture Objects, using more then one texture or material and export it sucessful to a json file?!

**Comment by mrdoob** [comment]
You should research "texture atlas".

**Comment by satori99** [comment]
I started playing with the new ability to use BufferGeometry groups with MultiMaterials and noticed that the ObjectLoader was ignoring the group.materialIndex property anyway.

I submitted a PR to parse the property #7552

**Comment by arturitu** [comment]
@satori99 thanks! I will try it for future works.

**Comment by trumanus** [comment]
I try to use the objectLoader (r82) to load a model in blender exported with animation and just one skinnedmesh  and multi material with a texture file each, but only one textured and material is dislayed..

i found in code : 
				function getMaterial( name ) {
					if ( name === undefined ) return undefined;
					if ( materials[ name ] === undefined ) {
						console.warn( 'THREE.ObjectLoader: Undefined material', name );
					}
					return materials[ name ];
				}
this is colled just once...

any ideas?

**Comment by inear** [comment]
@trumanus This is probably solved in your project already since it's 23 days ago. But I have problems with this my self and thought I could share a temporary workaround if someone else experience this. 

If you export a single mesh and not the whole scene, use the JSONLoader to load or parse JSON directly: 

```
var jsonLoader = new THREE.JSONLoader()
var obj = jsonLoader.parse(modelJSON)
```

this give you the objects materials-array. Wrap that in a THREE.MultiMaterial and use that on the mesh or when creating a new mesh. But first you might need to turn skinning on in each material first:

```
for (var i = 0; i < obj.materials.length; ++i) {
   obj.materials[i].skinning = true
}
var multiMaterial = new THREE.MultiMaterial(mesh.materials)
var skinnedMesh = new THREE.SkinnedMesh(obj.geometry, multiMaterial, false) 
```

If you load the whole scene with the ObjectLoader, then you can also extract the materials from the JSON directly on the selected object.

```
var loader = new THREE.Loader();
var materials = loader.initMaterials(modelJSON.geometries[i].materials)
yourMesh.material = new THREE.MultiMaterial(materials)
```

If it's possible to add support for multimaterials in the parsing to three.js and the ObjectLoader in particular, that would be great. But I'm not sure I fully understand the preferred way forward with the compatibility needs with exporters/ importers. And the shift to BufferGeometry needs a different way with handling multi materials I guess. If I guess a solution would be to check the objects materials-array while parsing, and maybe if faceMaterial-indexes are available. And in that use a MultiMaterial instead of a single one.

**Comment by mrdoob** [comment]
Seems like #8087 solved this. Unfortunately I couldn't get to merge it in time...

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/10931#issuecomment-290734264
