### ISSUE TITLE
PointsMaterial size should take into account devicePixelRatio

### ISSUE THREAD

**Issue by shreyass** [mrdoob/three.js#7451]
This is just a suggestion. The size specified for a PointsMaterial should be multiplied by the devicePixelRatio. If not, the points appear to be half the size on retina displays.

**Comment by mrdoob** [comment]
Yeah. I noticed that the other day trying in a huge retina display.

**Comment by mrdoob** [comment]
Done. Thanks!

**Comment by shreyass** [comment]
:+1: Cool!

**Comment by greggman** [comment]
Ugh! :(

**Comment by greggman** [comment]
Ugh :(

So now if I render to a renderTarget I have to know that PointsMaterial is going to render incorrectly.

This hole just keeps getting deeper and deeper

**Comment by mrdoob** [comment]
@greggman oh! good catch!

**Comment by mrdoob** [comment]
@greggman I know is not the solution you want, but now `WebGLRenderer` uses pixelRatio 1 when rendering to a `WebGLRenderTarget`. I actually considered adding `pixelRatio` to `WebGLRenderTarget` 😅

Lets continue in #4903.

**Comment by greggman** [comment]
>  but now WebGLRenderer uses pixelRatio 1 when rendering to a WebGLRenderTarget

I'm not sure how that helps. If you're doing picking and your WebGLRenderTarget is sized to match devicePixelRatio then suddenly your PointsMaterial objects are the wrong size and your picking breaks.

**Comment by mrdoob** [comment]
> I'm not sure how that helps. If you're doing picking and your WebGLRenderTarget is sized to match devicePixelRatio then suddenly your PointsMaterial objects are the wrong size and your picking breaks.

That's a different use case... Using pixelRatio 1 when rendering to a renderTarget solves the use case you mentioned 2 posts ago.

> So now if I render to a renderTarget I have to know that PointsMaterial is going to render incorrectly.

I understand you have problems with how devicePixelRatio is being handled, but saying that the fix I did doesn't fix anything upsets me 😟

**Comment by greggman** [comment]
Sorry, I didn't meant to upset you

At the same I just helped someone's code on SO that had an issue with devicePixelRatio and rendering with `gl_PointSize` in Three. He'd have the same issue with this fix. The issue is deeper as we've discussed before. I only meant to point out everytime I see more stuff added that's trying to propagate `devicePixelRatio` more traps are being set. Now there's one more bomb hiding in the code. If you render to a rendertarget your PointsMaterial points are not going to match in size.
