### ISSUE TITLE
In the use of THREE.XHRLoader, the server returns 404 or other error code, onerror does not function。

### ISSUE THREAD

**Issue by listenlin** [mrdoob/three.js#7464]

**Comment by mrdoob** [comment]
Could you create a jsfiddle that shows the bug?

**Comment by listenlin** [comment]
I am in China, jsfiddle can not be used, but I can use runjs

http://runjs.cn/code/se7utdxp

**Comment by leitzler** [comment]
This is how XMLHttpRequests work. If the request operation is successfully completed, the load event will fire instead of the error event. Your example contains response data, but also a status code (404).

The THREE.XHRLoaded should check for status 200 and readyState 4 (DONE) as shown in:
http://www.w3.org/TR/XMLHttpRequest/

I Created a PR for dev, #7491

**Comment by mrdoob** [comment]
Thanks guys!
