### ISSUE TITLE
Specular Environment BRDF is opaque

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7489]
Right now the indirect specular BRDF, aka the environmental BRDF, is opaque and can not be modified.  This is limiting our ability to improve our lighting model because we can not properly modify our responses to indirect specular lighting.

Given a normal microfacet BRDF model of D \* G \* F, I believe that the lod mip maps encode the D model for the most part, thus we should just be left with G and F in the indirect specular BRDF.  I believe that the environmental BRDF also includes other terms from the render equation such as dotNL (which is equivalent to dotNV in the case of an envMap reflection.)

Thus I believe that the Environment BRDF is something like `dotNL * G * F`.

**Comment by WestLangley** [comment]
[This post](http://brabl.com/tag/ibl/) and the embedded links may be helpful in understanding what is going on.

**Comment by WestLangley** [comment]
Also [this](http://blog.selfshadow.com/publications/s2013-shading-course/lazarov/s2013_pbs_black_ops_2_slides_v2.pdf).

**Comment by tschw** [comment]
@bhouston 
> lod mip maps encode the D model for the most part [ ... ]. 

Plus stuff we have in the rendering equation (or the *visibility term* V, as used in some papers). Most notably normalization factors (`1 / PI` weighting) that stem from the hemispherical integral are already in the data.

> Thus I believe that the Environment BRDF is something like `dotNL * G * F`

That's basically how I understand it too. I don't believe we need the `dotNL` part (at least not at this level, it might be *inside* of G), but I might be wrong and a careful re-read the SIGGRAPH stuff will probably clarify it. 

BTW I'd always think of `dotNL` it as `dotNV` in this context;  cosine of reflection angle / angle of emission rather than incidence.

For transparent surfaces, we have to consider the critical angle where we get [total internal reflection](https://en.wikipedia.org/wiki/Total_internal_reflection) in the Fresnel term (see [these figures](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Fresnel_reflection.svg/1200px-Fresnel_reflection.svg.png)).

A simple way to implement it is to scale the Schlick-style approximation to the appropriate range (since we're looking at cosines the angle axis is flipped):

```glsl
float eta = material.refractionIndex / trace.refractionIndex;
float cosCritical = sqrt(max(0., 1. - sqr(eta)));
cosSchlick = (cosReflect - cosCritical) / (1. - cosCritical);
```
![materials_transparent](https://cloud.githubusercontent.com/assets/3916357/10848257/50d7ae98-7f1b-11e5-81c9-7ebcd9b6fb38.jpg)
Note: The environment map in the image is filtered in the "hacky way"; with texel-based Gaussians to remain mipmapping compatible and they're from "single-sample real-time raytracing stuff" so three are some artifacts.

@WestLangley 
> This post and the embedded links may be helpful in understanding what is going on.

The original course notes are referenced here (Epic on UE4 @ SG 2013) https://github.com/mrdoob/three.js/pull/7028#issuecomment-133486274 .

**Comment by bhouston** [comment]
@tschw wrote:
> Plus stuff we have in the rendering equation (or the visibility term V, as used in some papers).

BTW I think the "V" term is just an alternate name for the "G" term.  The full name for it is "geometry visibility" function.

Very nice internal reflection -- now I know what you were complaining about with the lid of the anisotropic pot.  I wonder if you can get the same effect by rendering the back faces first, and then the front faces.  You may not get the refracted incident angle on the back surface exactly right, but it would save a trace, which I think can be hard with arbitrary geometry.

**Comment by tschw** [comment]
> Very nice internal reflection -- now I know what you were complaining about with the lid of the anisotropic pot.

Actually wasn't complaining (that would have been pretty bold, given how complicated it is trying to make some kind of a frame rate on consumer grade hardware) but calling it a challenge :-). 

>  I wonder if you can get the same effect by rendering the back faces first, and then the front faces.

In OpenGL it's illegal to render to a texture you are reading, so we'd have to flip buffers somewhere in the process.

Also, the ray is refracted two times, once when entering the transparent material and when leaving it. For the lid, a thickness parameter would probably give a sufficient approximation. For solid objects we'd obviously need to refract multiple times.

For a general & geometrically correct solution, we'd need some kind of environment map that contains what we are looking at (e.g. the inside of the pot). When we assume that the ray only goes to places where we can look at, which pretty seems like what you are suggesting, there are screen space approximations and I didn't really take too deep at a look at it, yet. E.g:

http://jcgt.org/published/0003/04/04/paper.pdf
http://www.npal.cs.tsukuba.ac.jp/projects/2014/liquid_rendering/nicoint_2014.pdf

Raytracing makes it all a lot easier, because you only have the math to worry about, and not so many additional hoops to jump through to get it rendered (different ones, when dealing with aliasing - but those are more general in nature).

**Comment by tschw** [comment]
> > Plus stuff we have in the rendering equation (or the visibility term V, as used in some papers).

> BTW I think the "V" term is just an alternate name for the "G" term. The full name for it is "geometry visibility" function.

I read at least one paper (and I currently don't recall which one - but should be amongst the SIGGRAPH stuff) that used `V` to refer to `G * <factors for analytic integration>`. 

Point was, `V_env = G` without these factors.

**Comment by tschw** [comment]
@bhouston 
> anisotropic pot

BTW, did you notice this suggestion: https://github.com/mrdoob/three.js/pull/7419#issuecomment-152293914

**Comment by bhouston** [comment]
@tschw wrote:
> In OpenGL it's illegal to render to a texture you are reading, so we'd have to flip buffers somewhere in the process.

I was just saying you could render the back faces assuming ior of internal 1.5 / external 1.0 and querying the environment map directly for what one sees through the object while accounting for total internal reflection.  And then render the front faces assuming an ior of external 1.0 / internal 1.5 and using the environment in the more traditional way as a fresnel reflection.  The ray angles on the back faces will not take into account the refraction angles from the front faces, but at least you get both effects in a single pass without a trace.  Not sure how good the result would be, because the front and back are fully decoupled.

**Comment by bhouston** [comment]
@tschw wrote:
> BTW, did you notice this suggestion: #7419 (comment) ?

It is a good idea.

One things we need to address is whether anisotropy is desired in a ThreeJS material, also clear coat, energy conservation modes (none, RGB, monochrome), and a [subsurface model](https://clara.io/view/5c7d28c0-91d7-4432-a131-3e6fd657a042) of some sort -- basically something equivalent to the UE4 Physical material.  I'd like to further extend the subsurface model to something appropriate for skin -- probably a normal warp approach.  I've already implemented versions of all of these features in my custom ThreeJS fork.

I greatly desire this as it is expensive for me to maintain my custom ThreeJS fork.  Our users also regularly complain that they can not get their exports to ThreeJS to look as good as our materials in Clara.io -- and there is not much I can do about it.

I understand that @WestLangey has stated that he wants to keep MeshPhysicalMaterial very simple in regards to additional model parameters -- specifically no clear coat support, but I suspect that desire also includes things like anisotropy and subsurface.  Thus I need to know what to do here.  Otherwise our discussions regarding anisotropy solutions are just theoretical, rather than practical.

**Comment by bhouston** [comment]
The other thing we should think about is whether we should argue about each model change or whether it is possible for us to find an existing model and just move towards that.  Good model candidates are Disney's PBR, UE4's Physical, V-Ray MTL, Sketchfab's, Arnold's Default shader, or Anders Langsland's uber shader, or Unity (although I find this one very limiting.)  If we had a system we were moving to, we could move very quickly and efficiently -- if we picked a popular one, it would have a built in user base, and it would easy conversion to and from.

**Comment by WestLangley** [comment]
> I understand that @WestLangey has stated that he wants to keep MeshPhysicalMaterial very simple

I would like to see both a simple PBR model for the average user, and a sophisticated model for the power user. I do not have a strong opinion on the material names. I have suggested in the past `MeshStandardMaterial` and `MeshPhysicalMaterial`, but it is up to @mrdoob. I also like `MeshPhysicalMaterial` and `MeshPhysicalMaterialAdvanced`. I am also open to what params should be included in the simple model.

**Comment by WestLangley** [comment]
> The other thing we should think about is whether we should argue about each model change or whether it is possible for us to find an existing model and just move towards that

Great idea. I believe the Disney one was parameterized in such a way that it would "just work". Personally, I like that. I also prefer the GGX BRDF parameterized by roughness, rather than the confusing term glossiness. I am thinking about the average user here. For the sophisticated user, maybe it makes sense to keep to the same model -- just support more options.

That is just my opinion. I can also see an argument for having only one model for everyone for the sake of simplicity. I am just concerned that the average user would be overwhelmed.

**Comment by WestLangley** [comment]
The `dotNL` term is part of the rendering equation.

In the case of an environment map serving as a model for an indirect light source, the rendering equation is:

    reflectance = int( EnvMap BRDF dotNL )

                = int( EnvMap F G * D dotNL )

where the integral is over the hemisphere.

That integral is too difficult, so it is approximated as the product of two integrals:


    reflectance = int( EnvMap * D dotNL ) * int( F G * D dotNL ) * scalingConstant


(I am not sure how good of an approximation that is. Also, the scaling constant is something we need to track down.)


The first term is the environment map convolved with a power-lobe that is a function of roughness. We approximate the first term via mipmapping.

The second term is the BRDF convolved with a cosine lobe, and is given the name "environment BRDF". So,

    environmentBRDF = int( BRDF dotNL )

It is the integral of the cosine-weighted BRDF over the hemisphere.

Note that the BRDF is a function of the Fresnel term -- and hence, a function of the model we choose for the Fresnel term.

So in my understanding, `environmentBRDF` can be thought of as the outgoing radiance that would be observed from uniform lighting of unit intensity.

**Comment by tschw** [comment]
@WestLangley makes some more sense and it seems we're getting closer to something that can be understood.
```
int( <something> dotNL )
```

being a shorthand notation for

```
int[ L in hemisphere around  N ]( f(L) )
```
right?

Not all light in the hemisphere in fact has an influence, so we're integrating over `D( roughness, L ) = 0` for a decent percentage of samples (all the of the environment map outside the filtered region). Is that why we have another D in the second integral?

```
reflectance = int( EnvMap * D dotNL ) * int( F G * D dotNL ) * scalingConstant
```

> I am not sure how good of an approximation that is.

OK, let's derive that product of integrals by applying the product rule `(fg)' = f'g + fg'` to see what we're in fact integrating over. It reads a lot like
```
sharpEnvironment(L) * blurryWeight(L) + blurryEnvironment(L) * sharpWeight(L)
```
IOW `specular + diffuse` to me.

...

**Comment by tschw** [comment]
@WestLangley & @bhouston 
Making sense to you, so far?

**Comment by tschw** [comment]
@bhouston 
> subsurface model

Wow! That looks super nice! 

Buddha is depicted as if he liked food a lot. Now we know he found enlightenment by swallowing a point light :-).

How does the rendering work?

**Comment by tschw** [comment]
> > > Plus stuff we have in the rendering equation (or the visibility term V, as used in some papers).

> > BTW I think the "V" term is just an alternate name for the "G" term. The full name for it is "geometry visibility" function.

> I read at least one paper (and I currently don't recall which one - but should be amongst the SIGGRAPH stuff) that used V to refer to G * <factors for analytic integration>. 

That's the one:

http://blog.selfshadow.com/publications/s2013-shading-course/lazarov/s2013_pbs_black_ops_2_notes.pdf
Page 1 reads:

> We also grouped G with the divide by (v ⋅ n)(l ⋅ n). This is often called the visibility function V(l,v,h).

See, even when I can't remember any source - I'm not making things up :-).

**Comment by WestLangley** [comment]
@tschw I'll have a response for you soon. I haven't forgotten you. : - )

Also, I used the term 'reflectivity' in the rendering equation. I meant 'reflectance'. Fixing...

**Comment by tschw** [comment]
> I think the "V" term is just an alternate name for the "G" term. The full name for it is "geometry visibility" function.

See also:
http://blog.selfshadow.com/publications/s2013-shading-course/hoffman/s2013_pbs_physics_math_notes.pdf
Page 18:

> In many cases, the geometry function partially cancels out the ( n ⋅ l )( n ⋅ v ) denominator in Equation 4 (EDIT: that's the rendering equation), replacing it with some other expression.

**Comment by tschw** [comment]
Repetition: By differentiating the two integrals (one baked at different LOD levels into an environment map and the other one being the material-dependent environment BRDF) with the product rule, we can see that we're in fact integrating over the sum of a specular and a diffuse part. Taking this apart in more detail:
```
L                                       o--o light direction
R                                       o--o viewer's direction reflected at normal

A = int[ L in hemi R ]( A' )            o--o color from environment map (scaled)
B = int[ L in hemi R ]( B' )            o--o ***environment BRDF***
C = int[ L in hemi R ]( A'B + AB' )     o--o outgoing light

C(L,s)                                  o--o reflected light color for spread(roughness)
spec(L,s)                               o--o specular weight over spread
C(L,s) * f(s), f(s) >= 1                o--o integrated light color w/o ***downscale***

A'B = C(L,0) * spec(R,s)                o--o specular reflection part
AB' = C(R,s) * spec(L,0) * f(s)         o--o diffuse reflection part
```
References:

http://blog.selfshadow.com/publications/s2013-shading-course/hoffman/s2013_pbs_physics_math_notes.pdf
General Lighting -> Image-Based Lighting, Pages 21-22

> Then, when the prefiltered sample is read, it should be multiplied by a
factor which reasonably approximates the reflectance integral.

Note: I called it `f(s)`.

http://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf
Image Based Lighting, Pages 4-8

--

Recalling how direct specular works:

The material is modeled as many tiny Fresnel mirrors also called microfacets. For an isotropic material, the surface normals of the microfacets are assumed to be evenly distributed around the normal of the (macroscopic) surface. The
halfway vector describes the surface normal microfacets ideally have to reflect light from a specific direction (the light source) into a specific direction (the viewer's eye). 

Now the Normal `D`istribution function does the statistics: "How many microfacets are pointing in right direction?".

Next we go for `F`resnel, that tells us how much light actually gets reflected **by our selection of microfacets** based on the reflection angle. Note that the angle of incidence (between L and H) equals the angle of emission (between
V and H).

Making complete sense is not quite that simple, because there are also microfacets pointing into other directions and those will partially occlude some of the light. This effect is modeled with the `G`eometry (also called "self-shadowing") term. Note that the overall surface area of all the microfacets of a rough material is larger than that of the macroscopic surface, therefore it's the geometry term's responsibility to account for energy conservation, IOW make sure no light gets invented.

--

For (specular) sharp reflection, we sample an environment map at
```glsl
R = reflect( V, N )
```
where `R` now corresponds to `L` in the direct specular form. The halfway vector `H` is the same as the surface normal `N`.

For diffusion we must integrate, but what exactly? 

The specular `D` and `F` terms get simplified by `dot(N,H) == 1`, and most `G` terms have the form `G_part( n ⋅ l ) * G_part( n ⋅ v )` (because of reciprocity). Note that we'd only have to integrate `G_part( n ⋅ l )` - the other part being a constant factor.

--

What do others do?

UE4 uses a 2D texture as a 2D lookup table, based on roughness and n ⋅ v, that contains the result from numeric integration:
http://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf

Black Ops II uses an analytic approximation:
http://blog.selfshadow.com/publications/s2013-shading-course/lazarov/s2013_pbs_black_ops_2_notes.pdf


To be continued...

@WestLangley 
> @tschw I'll have a response for you soon. I haven't forgotten you. : - )

Posting early so we don't do redundant thinking.

**Comment by WestLangley** [comment]
@tschw

Here are some responses to your earlier comments. I have not had time to study your more recent comments.

> int( <something> dotNL ) being a shorthand notation for...
> Edit: N actually being R, the reflected vector.

Not exactly. I'll switch to better notation.

    reflectance = int( BRDF EnvMap dotNL )

is shorthand for

    Lo( ωo ) = ∫ fr( ωo, ωi ) Li( ωi ) cos( θi ) dωi

`Lo( ωo )` is the reflected radiance in the direction `ωo`. `Lo( ωi )` is the incident radiance in the direction `ωi`. `fr` is the BRDF. It has units of inverse steradians. `dω` is a differential solid angle in the direction defined by `(θ, φ`). `θ` is the polar angle relative to the surface normal, and `φ` is the azimuthal angle. The integral is over the the hemisphere defined by the surface normal.

If `Li( ωi )` were constant equal to `L`, that is, if the environment map were a solid color, then we would get

    Lo( ωo ) = L * ∫ fr( ωo, ωi ) cos( θi ) dωi

The second term is "Environment BRDF". It is a unit-less quantity. This is the answer to @bhouston's question about what `EnvironmentBRDF` is.

As for the hack that splits the integral into two, the first term is to account for the fact, in a reasonable way, that (1) the environment map is not constant, and (2) there are many incoming directions that reflect photons in the same outgoing direction. Since it is a hack, I am having trouble providing a derivation for it and getting the scaling correct.

Regarding your comments about the diffuse component: Since GGX is a specular BRDF, we are only talking about indirect specular reflectance here.

To model indirect diffuse reflectance from the environment map, we usually compute an irradiance map, and assume a Lambertian BRDF for the material. I mentioned this technique in https://github.com/mrdoob/three.js/pull/7421#issuecomment-152748071, and link to an example that shows how to compute the irradiance from the radiance map using Spherical Harmonics.

The calculation of indirect diffuse is easy.

    Lo( ωo ) = ∫ fr( ωo, ωi ) Li( ωi ) cos( θi ) dωi

The Lambertian BRDF is

	fr( ωo, ωi ) = diffuse / π

so

    Lo( ωo ) = diffuse / π * ∫ Li( ωi ) cos( θi ) dωi

The integral is just the irradiance, which we compute from the environment map (or image-based-light) using Spherical Harmonics.

**Comment by tschw** [comment]
@WestLangley 
> The integral is over the the hemisphere defined by the surface normal.

OK my note is wrong there. However, despite all confusion, we're fetching the environment map at `R` therefore most of that hemisphere is actually weighted with a factor of 0 and we're in fact integrating over a sphere patch around `R`.

Also, how can you move a single angle and call it an integral over a hemisphere? It isn't what gets filtered either. 
Shouldn't it be [∫∫](https://en.wikipedia.org/wiki/Surface_integral)? There must be some reasoning for the reduction of dimensionality.

> As for the hack that splits the integral into two

...we better invert the process to see what's actually inside. The inverse of integration is differentiation and when we apply it to a product, we hopefully get something that can be interpreted. How much of a hack it is (and whether it is at all) in fact depends on the choice of the two integrals. That is, how the environment map gets filtered and how the sample is then treated during shading.

> Regarding your comments about the diffuse component: Since GGX is a specular BRDF, we are only talking about indirect specular reflectance here.

Using a filtered environment map *diffuses* the reflections. So we're still talking about specular, just for more than one sample at once - not to be confused with direct diffuse lighting in any way!!!

When sampling the map at LOD=0 we get in fact the differential, when sampling the map at LOD>0 we get a downscaled integral of the convoluted image.

Using the product rule we see both of these parts are having an influence (although the upscaled version of what we *would* fetch - the true integral. Note that we'll only be fetching one sample in practice and I'm trying to derive an interpretation to figure out what's going on): The "LOD>0 part" is weighted with a differential (or punctual at maximum resolution) specular term and the "LOD=0 part" is weighted with an integrated specular term.

However, other than for direct specular, the filter function must also be considered in the specular term we're talking about here. In fact certain parts of the BRDF are likely to be cancelled out to some degree - or are assumed to be, which is where we start approximating. 

@WestLangley 
Making some more sense to you now?

**Comment by tschw** [comment]
How to apply Fresnel correctly to a (spatially convoluted) environment map?

Problem: Fresnel only makes sense for `L ⋅ N = V ⋅ N`, however `L` varies under integration while `V` and `N` does not.
Solution: Do microfacet statistics, just as with direct specular.

Problem: We don't have `L` at runtime - only while baking the environment map and can't compute `H`. We can't compute `H` while baking either, because it depends on `V` which we only have at runtime,
Solution: At the center of the sample `L = R` and `H = N` and  `L ⋅ N =V ⋅ N`. Varying `L` around `R` changes `H` away from the surface normal by half of the angle. The effective size of the finite integral over `D` only depends on its maximum that describes the radial size (which can be approximated reasonably) of the convoluted area in the environment map.

Problem: How to get the second parameter considered

**Comment by tschw** [comment]
I should have given some motivation for the fever that caught me writing the above https://github.com/mrdoob/three.js/issues/7489#issuecomment-152782812 

Citing from http://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf :

> We pre-calculate the first sum for different roughness values and store the results in the mip-map levels of a cubemap. This is the typical approach used by much of the game industry [1,9].
> One minor difference is that we convolve the environment map with the GGX distribution of our shading model using importance sampling. Since it’s a microfacet model, **the shape of the distribution changes based on viewing angle to the surface, so we assume that this angle is zero, i.e. n = v = r.** 
> [...]
> This isotropic assumption is a second source of approximation and it unfortunately means we don’t get lengthy reflections at grazing angles. **Compared with the split sum approximation, this is actually the larger source of error for our IBL solution.**

Sacrificing the correctness of `D` by setting n = v = r for baking it into the environment map (the code in the paper shows in fact that `D` is not further considered) seems rather brutal: Luminance error is most perceptible where chroma error is a lot more tolerable.This fact is exploited for color TV, digital video compression, SH lighting, etc. Even when the colors are incorrect, the shape of the highlight should matter more. Restricting the filter to `D` also means there we can't use cheaper filters (ones that could easily work every frame) and imposes a hard requirement on two LOD dimensions for mipmapping (not talking about the LOD lookup but real mipmaps to avoid aliasing, these rely on texel-based filtering) to keep working correctly.

However, the above paper also documents the glorious idea of encoding the environment BRDF in a lookup table stored in a 2D texture containing the numerically precomputed integral. 

**My above post discusses how `D` could be moved out of the environment map and into a LUT like that**.

I figure a lookup texture is in fact our best bet. In case one of you is a total Calculus champ who can actually crack these integrals analytically, go ahead (and stick around) - I certainly can't, and there might not even be a known analytic solution. 
The other option is to look at the numerically integrated functions and approximate them manually. The result will be an opaque, optimized blob for a specific model and its implementation. The obvious downside is that the process must be repeated whenever something is changed or added (again, stick around). This approach is documented for a normalized Blinn/Phong-based model in

http://blog.selfshadow.com/publications/s2013-shading-course/lazarov/s2013_pbs_black_ops_2_notes.pdf discusses this process in much detail.

@bhouston 
> I believe that the lod mip maps encode the D model for the most part

Now we know that it's in fact a speciality of the UE4 implementation. I guess it might have been changed - as the 2013 paper already discusses it to be limiting. The same paper also explains why there is no specular color and they ended up having one. Is there newer literature around?
