### ISSUE TITLE
NPM three package missing XMLHttpRequest

### ISSUE THREAD

**Issue by TimothyStiles** [mrdoob/three.js#7567]
On line 14642 of the non-minified Three.js build in the NPM THREE package a <code>THREE.XHRLoader.load</code> method is provided, but it calls <code>THREE.XMLHttpRequest</code> which does not seem to be included. Is there a reason for this?

If the NPM build could include <code>THREE.XMLHttpRequest</code> this could make packaging and requiring loading examples much easier for node + browserify users. @bhouston what do you think?

**Comment by bhouston** [comment]
The npm package contents are fully determined by this command line utility:

https://github.com/mrdoob/three.js/blob/master/utils/npm/build.js

You'll notice it just runs build.bat or build.sh to create three*.js.  Thus it just includes what is included in the standard Three*.js build process with the exception of the header/footer.  Thus if there is a class or something missing, it really is a bug in ThreeJS, proper rather than the npm package.

**Comment by TimothyStiles** [comment]
If that's the case then I think that my problem is with how I'm requiring three in a nodeified version of STLLoader.js that I am working on.  I'm going to close this issue. Thanks @bhouston!
