### ISSUE TITLE
Multiple actions in Blender exporter broken

### ISSUE THREAD

**Issue by daniel-nth** [mrdoob/three.js#7631]
7812b25cd842dabdbaf5dbeb4e05f814ead3a2e3 broke the export of multiple actions for me. Instead, only the currently active animation of an armature will be exported. 
Isn't looping over `data.actions` and then checking for each action if it is identical to `armature.animation_data.action` the same as just exporting `armature.animation_data.action` in the first place?

**Comment by daniel-nth** [comment]
@antont Thanks! With the current exporter I get zero animations in the exported JSON. When reverting 7812b25, I get three. When I link an animation in the action editor, that one action gets exported.

@jackcaron Thanks for looking into it!
I committed a simple test file that we made for animation testing a while ago over here: https://github.com/daniel-nth/three.js-issue-7631. The behaviour is the same as with the deer, only a linked animation gets exported. Neither me nor our Blender guy know a way to link more than one animation to an armature in the action editor.

**Comment by satori99** [comment]
@daniel-nth

I am fairly certain that Blender actions are completely decoupled from armatures they may act apon.
Any action can be applied to any armature, and if the action group names match any bone names, they will be animated by the action data.

I have 'solved' this in a blender script by checking each actions' group names against armature deform bone name. I deem an action as applicable to an armature object if the action does not contain any groups which don't correspond to armature bones.

Something [like this](https://gist.github.com/satori99/5fb5c8c895f3c880ba5f)

It's not bullet-proof but it works well enough if your armature bone names are descriptive and not simply 'Bone, Bone.001, ...'.

Unfortunately, I don't know enough about the current exporter addon code to know if/how/where this could be applied.

**Comment by bhouston** [comment]
So just to clarify, the reason we did this was because if you had multiple rigged characters in a scene, like a dog, a person and a robot, the exporter would export every animation for every character.  Thus if there was 3 dogs animations, 1 person animation and 2 robot animation, the export would give the dog 6 animations, 3 of which were not his, the person 6 animations, 5 of which were not his, and the robot 6 animations, 4 of which were not his.

The current solution though clearly is exporting not enough, but the previous solution exported too many improper duplicates.

I guess one can undo our change until we get proper filtering.

**Comment by bhouston** [comment]
@daniel-nth if you wanted to make a PR with your fix, I think that would be a good idea.  Sorry for the trouble.

**Comment by daniel-nth** [comment]
@bhouston Thanks! PR is on the way.

**Comment by mrdoob** [comment]
#7666
