### ISSUE TITLE
{antialias:true} doesn't work on iOS and android 

### ISSUE THREAD

**Issue by 1007650105** [mrdoob/three.js#7655]
{antialias:true} doesn't work on iOS from v70 and later of three.js, and it alway doesn't work on android no matter which versions.

**Comment by mrdoob** [comment]
Can you provide a jsfiddle that uses r70 and one that uses the last version?

**Comment by 1007650105** [comment]
http://1007650105.github.io/html5dev/app/test/three-compatibility-test/

you could try to open this on your iOS or android devices.

On iOS devices, {antialias:true} can work in v69,bug not work in v70 and later.
On android devices,no matter which versions,{antialias:true} can't work correctly.
In v72 and v73,nothing will been shown on android devices.

**Comment by rlthomasgames** [comment]
+1 on this bug

**Comment by WestLangley** [comment]
I expect you just need to set the pixel ratio in r.71, r.72, and r.73.

```javascript
renderer.setPixelRatio( window.devicePixelRatio );
renderer.setSize( window.innerWidth, window.innerHeight );
```

**Comment by mrdoob** [comment]
Oh... Good catch @WestLangley! 😀

**Comment by rlthomasgames** [comment]
Oh so setting it in the camera is necessary or deprecated too, sorry I'm not at my work pc, Thankyou though will definitely try this tomorrow! :)

**Comment by rlthomasgames** [comment]
And Thankyou for threejs so much too, brilliant, thanks again!!

**Comment by rlthomasgames** [comment]
WORKS!!! Thankyou again! :D

**Comment by 1007650105** [comment]
Thank you very much!

**Comment by mlehel** [comment]
Hey guys! I'm reopening the discussion, since I can't seem to get antialiasing working on iOS devices. I'm using THREE.js version 75dev, I'm setting everything as in the comments above:

screenWidth = window.innerWidth;
screenHeight = window.innerHeight;

renderer = new THREE.WebGLRenderer({ antialias: true });

renderer.autoClear = false;
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(screenWidth, screenHeight);
renderer.setClearColor(0x000000);

What am I doing wrong?

**Comment by mrdoob** [comment]
iOS doesn't support antialias. I think it's coming on the next version though.

**Comment by mlehel** [comment]
Thank you so much for your answer :+1: so it wasn't me, it was the mobile Safari. Looking forward to the next version then, thanks!
