### ISSUE TITLE
KeyframeTrack default Time/ValueBufferType should be Float64Array

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#7693]
@mrdoob 
@tschw 

I think we should let default Time/ValueBufferType of KeyframeTrack be Float64Array or
it should provide a way to set user specified type into them on instance generation.

Because JavaScript can implicitly use 64-bit floating point value then some information can be lost if type is Float32Array.
Besides, to support backward compatibility, we'd better to use 64-bit floating point value unless memory consumption is huge.

Ex: information lose on console.

	> new Float32Array( [ 7.1 ] );
	< [7.099999904632568]

Indeed MMDLoader animation went wrong because of this information lost.
(so I used a workaround)

If it lets user be able to specify type, like this?

	THREE.KeyframeTrack = function ( name, times, values, interpolation, timeBufferType, valueBufferType ) {

	if ( timeBufferType !== undefined ) this.TimeBufferType = timeBufferType;
	if ( valueBufferType !== undefined ) this.ValueBufferType = valueBufferType;

What do you think of?

**Comment by mrdoob** [comment]
Additionally...

```
> new Float64Array( [ 7.1 ] )
< [7.1]
```

**Comment by tschw** [comment]
Originally everything was `Float64Array`. @bhouston suggested using 32-bit floats in the review. This suggestion makes sense, in particular for the keyframe data itself, because it halves the memory requirements. Based on subsequent benchmarking, I left the mixing buffers (in `PropertyMixer`) in 64-bit format and changed the data arrays to default to 32-bit.

> Because JavaScript can implicitly use 64-bit floating point value then some information can be lost if type is Float32Array

For certain values there is also information loss because of the base 10 -> base 2 conversion. For instance, there is no exact representation of 0.2.

> Indeed MMDLoader animation went wrong because of this 

Are you sure?

> I used a workaround
> [...]
> What do you think of?

`THRE.KeyframeTrack` is an abstract class and should not be constructed directly. The proper way to change the buffer types right now would be to subclass the tracks.  It's somewhat impractical, but so are many constructor parameters. 
I think it might be a better solution to have the types be defaults and only convert from JS -> typed or vice versa; in other words, omit the conversion in case the class defaults to a typed array type and a (possibly differently) typed array is given for the data.

**Comment by mrdoob** [comment]
>> Indeed MMDLoader animation went wrong because of this

> Are you sure?

I think he means the physics animation. The skirt used to break...

**Comment by bhouston** [comment]
Could it just be that the interpolator needs to be float64.  I think it
isn't a bad idea for the interpolator and those small working buffers ij
the mixer to be float64 as there is little penalty.  I have never heard of
anyone using float64 for storing animations though.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by bhouston** [comment]
@takahirox can you share an example of where this is happening?  Normally animations are not that sensitive to minor floating point errors.  Also it is highly likely that the original program which these were extracted from was using float32 for its animation.

**Comment by mrdoob** [comment]
I think @takahirox is referring to an issue with the `MMDLoader` where the skirt would get stuck:

https://www.youtube.com/watch?v=Ig9HV02YUm8

I think he fixed it by using [this](https://github.com/mrdoob/three.js/blob/dev/examples/js/animation/MMDPhysics.js#L25-L30) workaround.

Am I correct @takahirox?

**Comment by tschw** [comment]
> Could it just be that the interpolator needs to be float64. I think it isn't a bad idea for the interpolator and those small working buffers ij the mixer to be float64 as there is little penalty. I have never heard of anyone using float64 for storing animations though.

Not really, because that's exactly how it's implemented right now: Interpolation output (= `PropertyMixer`s' buffers) are still 64-bit, because it appeared to be faster that way when profiling it. Only the interpolation input (= keyframe data) is 32-bit.

> > > Are you sure?

> > I think he means the physics animation. The skirt used to break...

> Normally animations are not that sensitive to minor floating point errors. Also it is highly likely that the original program which these were extracted from was using float32 for its animation.

That's what I thought. Seems more like something relies on numerical identity where it shouldn't. In that case, 64-bit only fixes the underlying problem by chance and switching the library default precision to an astronomical scale isn't exactly a solution.

> @takahirox can you share an example of where this is happening?

Yes. Please investigate what's going on (if you haven't done so already) and report back. We should try to understand the root of the problem.

Maybe related: #7585

**Comment by takahirox** [comment]
In my case, the root issue was either one.
- Time type inconsistent. TimeBufferType is Float32 while others(i.e. deltaTime of THREE.Clock and  THREE.AnimationMixer,time) are Float64.
- There is no way to specify DiscreteInterpolant.js only for partial frames in one animation

And my issue can be changed, "how can I achieve teleportation in Animation system?"

The detail is below.

First of all, the issue isn't related to Physics, but Camera motion issue.
As you see, I control camera with animation system

http://takahirox.github.io/three.js/examples/index.html#webgl_loader_mmd_stage

Sometimes it looks like switching cameras.
It's achieved inside by moving camera like teleportation without interpolation.

And this kinda teleportation animation went wrong with TimeBufferType Float32Array.

This is the trick I use for teleportation.

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/MMDLoader.js#L2845-L2864

Even I change the "time: time - 1e-13" to the one for Float32Array, it didn't go well
because THREE.Clock.getDelta() returns 64bit floating point value and then 
the time can be in those two key frames.

**Comment by mrdoob** [comment]
So the problem is having multiple cameras? How about we create all the cameras and we switch from one camera to another instead?

Something like...

```javascript
renderer.render( scene, animation.currentCamera );
```

**Comment by takahirox** [comment]
It has only one camera and just acts as if switching camera among multiple cameras by doing "teleportation" as I explained above.

Anyways, actually making multiple cameras and switching is one option.
But I wanna know if there is a way to do teleportation in Animation system because it'll be easier for me to manage camera.

**Comment by tschw** [comment]
> Even I change the "time: time - 1e-13" to the one for Float32Array, it didn't go well because THREE.Clock.getDelta() returns 64bit floating point value and then the time can be in those two key frames.

For this approach to work, quantizing the input clock should do the trick, right?

> But I wanna know if there is a way to do teleportation in Animation system because it'll be easier for me to manage camera.

I don't think it should be "in" the animation system but "on top" - just use one `AnimationClip` per tracking shot and switch to the next when one finishes.

> Anyways, actually making multiple cameras and switching is one option.

You could also add an additional integer track (not sure we have these yet, but should be fairly easy to add) using discrete interpolation to select a camera clip by index. 
For example could bind it to `scene.userData.trackingShotIndex`, check it against the previous frame's value, and switch the camera clip when the index changes.

If you wanted to really have multiple cameras and multiplex the input (as they do on TV - e.g. to also let the user switch between cameras), you could play multiple clips, each targeting an `AnimationObjectGroup` and attach the renderer's camera to the appropriate one. Alternatively could use the previous method and do some math to only play one clip at a time using the correct time offset.

**Comment by takahirox** [comment]
Hm, ok. I still want Animation system to support "teleportation" but I understand your opinion. Let's close this issue so far because I already have a workaround.
