### ISSUE TITLE
THREE.AudioListener orientation not working correctly (v74 dev)

### ISSUE THREAD

**Issue by linkedz** [mrdoob/three.js#7709]
If make a scene with rotating audio listener in side of PositionalAudio then sound not playing correctly in headphones. 
In comparison to http://www.html5rocks.com/en/tutorials/webaudio/positional_audio/#toc-orientation source code in AudioListener.updateMatrixWorld has some difference:
They use

     var up = new THREE.Vector3(0,-1,0);
     up.applyProjection(camera.matrix);
     up.normalize();

(Sure, up vector should be taken from 'this.up').

With this difference applied as fix source audio is playing good.

**Comment by vincent-courtalon** [comment]
well, the AudioListener certainly doesn't update anything right now with the up vector (this hasn't changed). I have quickly looked at Object3D and doesn't seem the up vector is updated anywhere ?
it is only initialized by cloning the DefaultUp  vector (0, 1, 0)

so yes it would be a good idea to update it (i had not noticed the problem because my test were not doing backflip or anything of the sort with the camera...). However, it can't be directly with

```javascript
up.applyProjection(camera.matrix);
```
 because the listener may not be tied to the camera. Sure it is generally the case, but not always.
we should update the up vector accordingly to the orientation of the listener itself. I am  not sure how to do this. Should it be always updated, or have a flag to turn it on ?

**Comment by mrdoob** [comment]
Hmm, @linkedz can you provide an example/jsfiddle that shows the difference?

**Comment by linkedz** [comment]
Sorry, wrong issue. Everything is OK.
The problem was: In Listener and Source have the same position then sound will be present only in right headphone.
The next line of code is fixing my issue.
positionAudio.panner.panningModel = 'HRTF';  

There can be added a new method 'setPanningModel' to THREE.PositionalAudo class, like there is 'setDistanceModel'
