### ISSUE TITLE
Three.js references scratchapixel.com which is GPL licenced so it invalidates the MIT licence

### ISSUE THREAD

**Issue by nojvek** [mrdoob/three.js#7760]
Three.Ray ...

	intersectSphere: function () {

		// from http://www.scratchapixel.com/lessons/3d-basic-lessons/lesson-7-intersecting-simple-shapes/ray-sphere-intersection/

	intersectBox: function ( box, optionalTarget ) {

		// http://www.scratchapixel.com/lessons/3d-basic-lessons/lesson-7-intersecting-simple-shapes/ray-box-intersection/

scratchapixel has the following

 - Any redistribution or reproduction of part or all of the contents in any form is prohibited other than the following: 
- You may print or download to a local hard disk extracts for your personal and non-commercial use only 
- You may copy the content to individual third parties for their personal use, but only if you acknowledge the website as the source of the material. **You may not, except with our express written permission, distribute or commercially exploit the content**. Nor may you transmit it or store it in any other website or other form of electronic retrieval system. 
The source code from this website is distributed under the terms of the **GNU General Public License** as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

**Comment by erichlof** [comment]
Hi @nojvek and @mrdoob ,
Those commented-out links should be removed, as they are dead - scratchapixel has since updated their website.  In any case, this is not breaking any licences, because by the time the code in question was merged by mrdoob, it had taken on a different form to suit three.js .  With the link reference, I was trying to show @WestLangley where I was getting my ideas / mathematical concepts from, and although I used the general ray-sphere intersection algorithm from their website, it ended up being slightly changed for our purposes.  Plus, scratchapixel can't possibly lay claim to that ray-sphere intersection routine, as that algorithm has been around since the 1970's, at least in computer science / ray tracing research.  

Mrdoob, feel free to remove the commented-out links from the Ray.js source.

**Comment by mrdoob** [comment]
Do you agree @nojvek?

**Comment by nojvek** [comment]
Just sent an email to our legal folks and cc-ed you. Hopefully this is it.

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
can someone gpl a math algorithm? silly question, the answer is probably yes in america.

**Comment by mrdoob** [comment]
I've removed the references by now. We can re-open this if needed.
