### ISSUE TITLE
lightMap not usable in MeshLambertMaterial anymore

### ISSUE THREAD

**Issue by ilanusse** [mrdoob/three.js#7812]
Hello!

Why are lightMaps not supported for MeshLambertMaterials any longer? Is there another way to achieve the same use with another property?

**Comment by WestLangley** [comment]
They were removed for simplicity. As a work-around, you can use `MeshPhongMaterial` instead.

We could re-add support for light maps and ao maps back in to `MeshLambertMaterial`. If we do that, there is really no reason not to add emissive maps, too. We can't add bump maps or normal maps because the lighting is computed in the vertex shader.

Related discussions:

https://github.com/mrdoob/three.js/pull/6364
https://github.com/mrdoob/three.js/issues/7178

**Comment by ilanusse** [comment]
Thanks for replying!

If you could re-add support for light maps, it would be great! Otherwise updating to r73 will be a great hassle.

**Comment by mrdoob** [comment]
> We could re-add support for light maps and ao maps back in to `MeshLambertMaterial`. If we do that, there is really no reason not to add emissive maps, too. We can't add bump maps or normal maps because the lighting is computed in the vertex shader.

That sounds good to me.
