### ISSUE TITLE
Cannot clone BoxHelper

### ISSUE THREAD

**Issue by DanielAChandler** [mrdoob/three.js#7824]
In version r71 I could clone BoxHelper meshes. When I upgrade to r72 or r73, anytime I try to clone a BoxHelper or any object containing a BoxHelper I get the following exception:

Uncaught TypeError: object.updateMatrixWorld is not a function
You can replicate this by making the following change to the example code in "webgl_helpers.html"

Change line 73 from:

```
scene.add( new THREE.BoxHelper( mesh ) );
```

To:

```
var helper = new THREE.BoxHelper( mesh );
var helper1 = helper.clone();
scene.add( helper1 );
```

Is there a workaround?

**Comment by dhritzkiv** [comment]
@DanielAChandler in terms of quick workaround you could try:

```

**Comment by WestLangley** [comment]
@dhritzkiv 

Well, this seems to work...

```js
var helper = new THREE.BoxHelper( mesh );
var helper1 = THREE.Object3D.prototype.clone.call( helper );//<this is the cloning functionality
helper1.update( mesh );
scene.add( helper1 );
```

What is the permanent fix, though?

**Comment by dhritzkiv** [comment]
So the `clone` method is being inherited from the prototypal chain

`BoxHelper` -> `LineSegments` -> `Line` -> `Object3d`

and it works by simply creating a new instance of that object's constructor, passing in `geometry` and `material` from that object.

The problem is, while most of these objects have a constructor pattern of `(geometry, material)` the helper constructors have a pattern of `(object3d)`.

In any case, the fix is to create a new clone method at the `*Helper` level that returns a new object using the `LineSegments` constructor.

**Comment by dhritzkiv** [comment]
@WestLangley is the `update` line necessary? Won't a copy of `box` already reflect the boundingBox properties of `mesh` (unless `mesh` has somehow been transformed or morphed – something the code at r71 never dealt with)?

**Comment by WestLangley** [comment]
>@WestLangley is the update line necessary?

It was in my test. I created the mesh and helper prior to the first render.

>In any case, the fix is to create a new clone method at the *Helper level that returns a new object using the LineSegments constructor.

Well-stated. Would you be willing to file a PR to fix the helpers?

**Comment by dhritzkiv** [comment]
@WestLangley 

>> @WestLangley is the update line necessary?

> It was in my test. I created the mesh and helper prior to the first render.

You're right. I didn't notice that it wasn't working (it just wasn't breaking). That being said, instead of calling `helper1.update( mesh )`, I propose we effectively call `helper1.update( helper )`, since we aren't explicitly storing a reference to the `mesh` object, and using `helper` (that was derived from `mesh`) should give us the desired results.

> Well-stated. Would you be willing to file a PR to fix the helpers?

Yes. I should have mentioned that I'm already working on a PR. I'm looking into creating a BaseHelper object that contains a clone method like this:

```js

BaseHelper.prototype.clone = function clone() {
    
    var clonedHelper = new THREE.LineSegments(this.geometry, this.material);
    clonedHelper.update(this);
    return clonedHelper;

}

```

However, I'm not sure it will work, yet.

**Comment by WestLangley** [comment]
I believe `BoxHelper` is the only helper whose `update()` method requires an argument. To that end, we could change `BoxHelper`'s API if need be.
