### ISSUE TITLE
glTFParser is undefined in glTFLoader.js

### ISSUE THREAD

**Issue by BryceEWatson** [mrdoob/three.js#7920]
When importing the glTF loader files through require in the order below, I'm seeing that glTFParser is undefined, causing the loader to stop.

Crashes at: https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/gltf/glTFLoader.js#L499

Imports:
```
require('../node_modules/three-dev/examples/js/loaders/gltf/glTF-parser');
require('../node_modules/three-dev/examples/js/loaders/gltf/glTFLoader');
require('../node_modules/three-dev/examples/js/loaders/gltf/glTFLoaderUtils');
require('../node_modules/three-dev/examples/js/loaders/gltf/glTFAnimation');
```

Usage:
```
    var loader = new THREE.glTFLoader;
    loader.load(url, function (gltf) {
      self.model = gltf.scene;
      el.object3D.add(gltf.scene);
    });
```
I'm testing this in aframe-core, the relevant code can be seen here in this commit: https://github.com/BryceEWatson/aframe-core/commit/9c0523251a8da8bcbc88b4b40ec2d1f802360d44

**Comment by donmccurdy** [comment]
This is most likely just affecting A-Frame. I don’t think the example JS is included when importing Three.js — the OBJ and Collada loaders are [manually included with aframe-core](https://github.com/aframevr/aframe-core/tree/master/lib/vendor) right now. I ported the [OBJ+MTL loader](https://github.com/donmccurdy/aframe-obj-loader-component) to A-Frame and had to manually add the resources from Three.js’s examples/js folder, making some changes to get them to be browserify-friendly.

**Comment by BryceEWatson** [comment]
I see, is there an open task to browserify the gltf loader? I wouldn't mind taking a crack at it.

**Comment by donmccurdy** [comment]
The only change you should need would be using module.exports instead of setting a global - compare versions of OBJLoader.js, for example: https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJLoader.js and https://github.com/aframevr/aframe-core/blob/master/lib/vendor/OBJLoader.js

https://github.com/aframevr/aframe/issues/4 is related to dynamically including the loaders (and isn't exactly fixed yet). And then https://github.com/aframevr/aframe-core/issues/532 of course.

**Comment by mrdoob** [comment]
I think this should be discussed in https://github.com/KhronosGroup/glTF instead...
