### ISSUE TITLE
TransformControls: rotate doesn't work when Camera is at 0,0 for x,y

### ISSUE THREAD

**Issue by davegirdy** [mrdoob/three.js#7947]
I'm using the example here for TransformControls:
examples/misc_controls_transform.html

The rotate gizmo doesn't seem to work if the Camera's x,y position is at 0,0. 
I changed the line of code  
camera.position.set( 1000, 500, 1000 );
to 
camera.position.set( 0, 0, 1000 );

And rotating seems broken for going up/down and left/right.

**Comment by mrdoob** [comment]
Can you create a jsfiddle?

**Comment by arodic** [comment]
To rotate around Y axis, for example, the control casts a ray through XZ plane and determines the angle between drag start and drag end vector in that plane. When camera is at 0, 0 it is perfectly aligned with XZ and YZ plane and it doesn't make sense to project into those planes. This also makes the rotation difficult when camera is almost aligned. I noticed that many rotation gizmos suffer from this problem including tools such as Autodesk Maya.

Some time ago, I refactored and greatly simplified [TransformControls](https://github.com/arodic/ree.js/blob/master/app/js/controls/Transform.js) and also fixed bunch of bugs such as this one (by improving the angle calculation math and hiding the rotation handles when perfectly aligned to the plane). However, this improved version cannot be easily merged back into three.js since it relies on shared [Control](https://github.com/arodic/ree.js/blob/master/app/js/controls/Control.js) superclass (also used by improved [EditorContols](https://github.com/arodic/ree.js/blob/master/app/js/controls/Viewport.js)).

If there is interest to pull this back into three.js I can help with that.

**Comment by WestLangley** [comment]
> If there is interest to pull this back into three.js I can help with that.

up vote! T

**Comment by mrdoob** [comment]
I'm interested in the bug fixed and simplifications, but I would avoid the multiple files (`TransformControls` and `Controls`).

**Comment by sjlynch** [comment]
+1 -- interested in bug fixes.
