### ISSUE TITLE
OBJMTLLoader incredibly slow for complex geometry

### ISSUE THREAD

**Issue by borismus** [mrdoob/three.js#7969]
I was loading an .obj with ~70k vertices, and it was taking ~20s to load the model. The slowness was being caused by `mergeVertices` call here:

https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJMTLLoader.js#L101

I commented it out just to see what would happen, and it took about ~1s to load the model and there was no visible change. Any ideas?

**Comment by makc** [comment]
This should be titled 'mergeVertices is incredibly slow for complex geometry' then

**Comment by mrdoob** [comment]
`OBJMTLLoader` has been removed (duplicated and outdated code).
You should now use `OBJLoader` and `MTLLoader` (you'll find them in the `dev` branch).

**Comment by borismus** [comment]
Ah, good!

**Comment by davegirdy** [comment]
Hey guys, I switched over my code to use the OBJLoader and MTLLoader from the dev branch... but now I get this error: "THREE.WebGLRenderer: image is not power of two (640x400). Resized to 512x512". I was not getting this error when using OBJMTLLoader. 

My textures are in fact 640x400. Since the image get's resized, the texture doesn't get mapped correctly. I searched for this error and saw a solution of changing the textures minFilter to THREE.LinearFilter. I tried adding that to MTLLoader in loadTexture function, but it didn't seem to take. 

Do you think it's okay to assume that textures for the MTLLoader need to be a power of 2? Any idea of how else I can solve this problem? 

Thanks!

**Comment by mrdoob** [comment]
I don't think it's related, but yes... you should try to have power of 2 textures whenever you can.

**Comment by davegirdy** [comment]
Thanks for the information. I tracked it down a little further with no luck...
On Master, MTLLoader has a function called THREE.MTLLoader.ensurePowerOfTwo_ that was called after using a THREE.ImageLoader.
On Dev, MTLLoader uses a THREE.TextureLoader, and the ensurePowerOfTwo function was removed.

So that explains why I was seeing the warning from the Renderer on the Dev branch. I tried loading the texture by using the old code from Master, but the problem still persisted where my texture didn't map correctly. So I think you are right that the the power of 2 is not related. I'll keep looking into it. Thanks.
