### ISSUE TITLE
THREE.CubeTextureLoader Cross Origin Issues

### ISSUE THREAD

**Issue by theo-armour** [mrdoob/three.js#8013]
Using ImageUtils you can load cube URLs cross origin and display a skybox.

THREE.ImageUtils.crossOrigin = 'anonymous';

But using the following does not seem to work in master or in dev:

THREE.CubeTextureLoader.crossOrigin = 'anonymous';

The following script loads both types of textures. If ImageUtils is loaded last then the textures load and the skybox works. Vice versa. it's a fail and the skybox is black.

https://github.com/mrdoob/three.js/files/102633/skybox-cross-origin-r1.html

(I tried building a jsFiddle but the fiddle had issues.)

**Comment by Mugen87** [comment]
@theo-armour I've changed your function `addSkyBox1` so everything should work fine. The problem is you are using `THREE.CubeTextureLoader` in a static way (like the deprecated THREE.ImageUtils).

```javascript
function addSkyBox1( urls ) {

    // you need to create an instance of the loader like this
	var loader = new THREE.CubeTextureLoader();
	loader.setCrossOrigin( 'anonymous' );

	var textureCube = loader.load( urls );
	textureCube.format = THREE.RGBFormat;

	var shader = THREE.ShaderLib[ "cube" ];
	shader.uniforms[ "tCube" ].value = textureCube;

	var material = new THREE.ShaderMaterial( {

		fragmentShader: shader.fragmentShader,
		vertexShader: shader.vertexShader,
		uniforms: shader.uniforms,
		depthWrite: false,
		side: THREE.BackSide

	} );

	var geometry = new THREE.BoxGeometry( 50, 50, 50 );

	skybox1 = new THREE.Mesh( geometry, material );
	skybox1.position.x = -30;

	scene.add( skybox1 );

}
```

As i mentioned before, `THREE.ImageUtils` is deprecated. You should always use `THREE.CubeTextureLoader` or `THREE.ImageLoader`. 

Besides, if you need to load multiple textures/images, you can re-use the same loader instance. And you can use `THREE.LoadingManager` to control the progress of all you loadings...

**Comment by theo-armour** [comment]
Hi @Mugen87 

Thank you for the fix.

You are correct: creating the instance before setting the crossOrigin makes things work.

Thinking about it, setting crossOrigin with the instance is most likely the correct behavior and better than the previous behavior, so I will ask for this issue to be closed.
