### ISSUE TITLE
[r73] MultiMaterial visible error 

### ISSUE THREAD

**Issue by Bigmacbook** [mrdoob/three.js#8027]
Trying to create a simple Cube with MutiMaterial and it keeps giving an error

```
Uncaught TypeError: Cannot read property 'visible' of undefined
```
I traced it back to line 22548

```
if ( groupMaterial.visible === true ) {
```

Here is my code

```
var scene = new THREE.Scene();
var camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);

var renderer = new THREE.WebGLRenderer({
    antialias: true
});
renderer.setSize(window.innerWidth, window.innerHeight);
$('body').append(renderer.domElement);

var manager = new THREE.LoadingManager();
manager.onProgress = function(item, loaded, total) {

    console.log(item, loaded, total);

};

manager.onLoad = function() {
    render();
}

var skin;

var loader = new THREE.TextureLoader(manager);
loader.load('assets/sam.png', function(texture) {

    skin = texture;

    var mats = [];

    front_texture = skin.clone();
    front_texture.minFilter = THREE.LinearMipMapLinearFilter;
    front_texture.magFilter = THREE.NearestFilter;
    front_texture.offset.x = (1 / 64) * 8;
    front_texture.offset.y = (1 / 64) * 48;
    front_texture.repeat.x = (1 / 64) * 8;
    front_texture.repeat.y = (1 / 64) * 8;
    front_texture.needsUpdate = true;

    var front_material = new THREE.MeshBasicMaterial({
        map: front_texture
    });
    mats.push(front_material);

    var geometry = new THREE.BoxGeometry((1/16)*8, (1/16)*8, (1/16)*8);
    cube = new THREE.Mesh(geometry, new THREE.MultiMaterial(mats));
    scene.add(cube);

});

camera.position.z = 5;

var render = function() {
    window.requestAnimationFrame(render);

    renderer.render(scene, camera);
};
```

**Comment by Bigmacbook** [comment]
Are you kidding me! If I have only one material in the MutiMaterial it gives this error.

MutiMaterial should work with only one material in the array.

Such a stupid thing, I lost hours of time trying to figure out with is wasn't working

**Comment by mrdoob** [comment]
If you can create a jsfiddle showing the error we can take a look.

**Comment by pdjole** [comment]
Hello everybody, what is a status on this issue?
I am also experiencing it on version 77.

**Comment by mrdoob** [comment]
No progress. Seems like @Bigmacbook figured out the issue and didn't want to save other people's time.

**Comment by mrdoob** [comment]
@pdjole do you have a jsfiddle I can use to fix it?

**Comment by pdjole** [comment]
Hey @mrdoob, 
i just have to be sure if this is up to three.js, or there is a mismatch our in code regarding wrong face materialIndex and number of materials in coresponding MultiMaterial.
Cheers!

**Comment by pdjole** [comment]
Hey @mrdoob, just wanted to say that problem wasn't this issue, but something else.
It seems that **TetrahedronGeometry**, (actually **PolyhedronGeometry**) was being instantiated in older versions ( we are migrating from r70 ) with all faces having materialIndex === 0.
In version r77 i see that for some reason newly instantiated **TetrahedronGeometry** is now being instantiated with faces having different values of **materialIndex** (eg from 0 - 3).  This is affected by last line in this code below:
`
THREE.PolyhedronGeometry = function ( vertices, indices, radius, detail ) {

	THREE.Geometry.call( this );

	this.type = 'PolyhedronGeometry';

	this.parameters = {
		vertices: vertices,
		indices: indices,
		radius: radius,
		detail: detail
	};

	radius = radius || 1;
	detail = detail || 0;

	var that = this;

	for ( var i = 0, l = vertices.length; i < l; i += 3 ) {

		prepare( new THREE.Vector3( vertices[ i ], vertices[ i + 1 ], vertices[ i + 2 ] ) );

	}

	var p = this.vertices;

	var faces = [];

	for ( var i = 0, j = 0, l = indices.length; i < l; i += 3, j ++ ) {

		var v1 = p[ indices[ i ] ];
		var v2 = p[ indices[ i + 1 ] ];
		var v3 = p[ indices[ i + 2 ] ];

		faces[ j ] = new THREE.Face3( v1.index, v2.index, v3.index, [ v1.clone(), v2.clone(), v3.clone() ], undefined, j );

	}
...
`
Do you know why is this thus? :)

Best regards,
Djordje

**Comment by WestLangley** [comment]
/ping @rfm1201 regarding https://github.com/mrdoob/three.js/commit/1eebaf255d90fa75d84891261eb3062355f50465

Try `TetrahedronGeometry( 10, 2 )`, for example.

Maybe `PolyhedronGeometry` should be reverted to a single material index for all faces.

**Comment by rfm1201** [comment]
I will have time to test this point tomorrow, not today.

But there is one thing I totally disagree with [@pdjole](https://github.com/pdjole) it's when he says 
> MutiMaterial should work with only one material in the array.

And when there are two, it should, because my code just put two elements in the `MultiMaterial` ???

With `MultiMaterial` you have to adjust the size of the internal array to the number of faces. It's not just for `PolyhedronGeometry`. Use a `BoxeGeometry` with a `MultiMaterial` where there are less than 6 materials, what happens?

I write an editor with three.js. My users could have chosen a `MultiMaterial` but currently have only defined one "real" material. It works in all the cases I have tested. Of course the same "real" material (pointer) can be found in all the array elements required by the geometry. I adjust the number of materials in the `MultiMaterial` to the number of faces of the geometry.

If it doesn't work with the right number of material inside the `MultiMaterial`, it's a bug. I will try tomorrow to know if it's a bug or not.

**Comment by pdjole** [comment]
@rfm1201 
You mean Bigmacbook? 
I didn't say that. ;)

**Comment by rfm1201** [comment]
First, the change was made to allow each face to use a different material.

I first build the geometry with a `detail` parameter at 0. It generates the basic geometry with the right amount of faces and face indexes. I won't talk about UVs here.
- `THREE.TetrahedronGeometry` will give you 4 faces and 4 face indexes.
- `THREE.OctahedronGeometry` will give you 8 faces and 8 face indexes.
- `THREE.IcosahedronGeometry` will give you 20 faces and 20 face indexes.
- `THREE.DodecahedronGeometry` will give you 36 faces and 36 face indexes (I was expecting 12 faces).

Used with "normal" material or a `MultiMaterial` filled with the right amount of materials (the number of faces), there is no problem.

If you grow the `detail` parameter, each face is subdivided by 4 at each step and each resulting face keeps the face index of the initial face. For example `new THREE.TetrahedronGeometry(5, 2);` build a geometry with 64 faces (4 * 4 * 4) and 4 face indexes. It works with a "normal" material or a MultiMaterial filled with 4 materials. I tried with each geometry up to `detail` = 3.

If the question is, "will a `MultiMaterial` filled with one material generate a problem when used with a geometry generated by `THREE.PolyhedronGeometry` ?". The answer is "Yes it will". As it will if applied to a `BoxGeometry` (for example).

- Solution 1, use a non-multiple material when just one material is required. For me it is THE solution.
- Solution 2, use a multiple material and duplicate the material inside the multiple material. Be careful when freeing the `MultiMaterial` depending of the way it is coded. It works, I use it in my editor, but if the goal is to have just one material in the end, it's ugly.
- Solution 3, modify the way a `MultiMaterial` is used to render a frame when there is only one material in the `MultiMaterial`. I think it's not really a solution, there is no need to use a `MultiMaterial` in that case, but it will make @pdjole code works.
- Solution 4, revert to same index for all faces. In fact it means remove MultiMaterial, and there are people using three.js who need MultiMaterial (with more than one material). I'm one of them, but I'm not alone. Last year, when MultiMaterial disappears, I was not the only one to complain. Plus, there won't be an other solution to have more than one material applied to the geometry.

Why should it be impossible to apply more than one material on geometry with more than one face? If there is a problem with the current code, it may be "why the face index does not reflect the real amount of faces?". But I think it is not a problem, you ask for n faces, you've got n "logical" faces. They may be subdivided, but you ask for n faces.

My question to @pdjole, why do you need `MultiMaterial` with just one material inside?
Ok it works in the past because applied on a geometry that didn't work with `MultiMaterial`, but it was not really expected to work.
By the way, I don't know what "Bigmacbook" is.

**Comment by pdjole** [comment]
@Bigmacbook is a user that said:
> MutiMaterial should work with only one material in the array.
If you use that scroll button you will see it by yourself.

**Comment by rfm1201** [comment]
@pdjole I didn't realize the first two posts were not yours. I apologise.

**Comment by iefreer** [comment]
I got the same problem, in my case, this is because of the images have not been fully loaded yet.
