### ISSUE TITLE
Saw-tooth memory profile / leak (particularly bad with MeshStandardMaterial)

### ISSUE THREAD

**Issue by robhawkes** [mrdoob/three.js#8220]
I can't say if this is something new but I've recently been delving into the Chrome dev tools to increase performance for ViziCities and I noticed that there is some pretty dramatic memory leakage / saw-toothing going on, causing a lot of garbage collection every couple of seconds.

The reason I've brought this up as a bug is that I see the same thing with most of the Three.js examples on the main site, with the `MeshStandardMaterial` ones being particularly bad. It's definitely not related to ViziCities-specific logic – by the looks of it the culprit seems to be something to do with the way the material uniforms are handled.

Here's an example timeline for [the following Three.js MeshStandardMaterial example](http://threejs.org/examples/webgl_materials_variations_standard.html):

![](http://cl.ly/2t1h2q0F2W3E/Screen%20Shot%202016-02-24%20at%2018.04.40.png)

You can see the regular and dramatic saw-tooth memory profile as objects are created and freed (the blue bar at the bottom). You'll also notice that this doesn't seem to have a dramatic effect on the frame-rate, though I'd argue it's not a great thing to leave if it can be fixed.

Here is a comparison of some heap snapshots taken around the same time:

![](http://cl.ly/252p362s0e2C/Screen%20Shot%202016-02-24%20at%2018.04.28.png)

Notice the rather hefty amount of `number` objects created between the snapshots (~10MB), with another 10MB being freed through garbage collection. Clearly something is creating a lot of new `number` objects and discarding them.

By digging into the `number` objects you can see that the culprit appears to be something to do with the uniforms for the material – specifically `metalness`, `refractionRatio` and `roughness`. A large number of these values are being created and then disposed of by the GC.

I'm afraid I don't have much more than that, though I'd be happy to provide some more debugging if it helps. Just let me know what you need from me.

My stats:

* Seen in Chrome 48.0.2564.116 (64-bit) & Chrome 50.0.2657.0 canary (64-bit)
* OS X 10.11.3 (15D21)
* ATI Radeon HD 5770 1024 MB

**Comment by robhawkes** [comment]
I'm not 100% on the cause of the saw-toothing, though the above is a possible line of investigation.

Regardless, there's no denying that it's there and I'd very much like to identify exactly what's causing it and see what we can do to reduce it or prevent it entirely. For example, it may be that we just need to re-use objects somewhere to cut down on the creation / collection cycle.

So far, I've seen this in all the Three.js examples on the main site that I've looked at. The saw-toothing is the same but the amount of memory being created / collected differs depending on the scene complexity it seems (ie. I don't think it's a full-on leak, per-se).

**Comment by pailhead** [comment]
I've also noticed this happening. I was wondering about the arrays for object sorting being created every tick, but im not sure how much impact this has?

**Comment by tschw** [comment]
@mrdoob 
> /ping

Classic. Killer issue filed right after the release?

@pailhead 
> I was wondering about the arrays for object sorting being created every tick

Got rid of that a while ago. They are being reused, see [`render`](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L1117-L1126), [`projectObject`](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L1264-L1360) and [`pushRenderItem`](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L1215-L1262).

@robhawkes 
> Here is a comparison of some heap snapshots taken around the same time. [...] 
> Notice the rather hefty amount of number objects created between the snapshots (~10MB), with another 10MB being freed through garbage collection. Clearly something is creating a lot of new number objects and discarding them.

Everything becomes quite tame when not adding those `TextGeometry` instances to the scene...

> By digging into the number objects you can see that the culprit appears to be something to do with the uniforms for the material – specifically metalness, refractionRatio and roughness. A large number of these values are being created and then disposed of by the GC.

Seems like a red herring to me (sort order?). [`initMaterial`](http://threejs.org/examples/#webgl_materials_variations_standard) only runs at startup. I just verified it.

**Comment by MasterJames** [comment]
Not that this is a solution here, but I was thinking maybe if all 'var's where 'let's what would happen? How different would the readouts be? is that possible yet or an insane proposition? Is there an estimate when that would be possible?
I'm getting babel through meteor currently so no more vars for me. They now seem spooky and suspicious.
So ya otherwise I think maybe, it's just garbage collecting? all good.

**Comment by robhawkes** [comment]
@tschw: Definitely take my initial comments with a pinch of salt, I certainly don't understand the three.js codebase like yourself. Whatever it is, there's certainly saw-toothing going on (in all examples that I've checked) but I don't know what's actually causing it – I only know as much as what I could see in the heap snapshots (which isn't much).

@MasterJames: It's looks like just garbage collection to me (if a leak it'll grow and grow) but it's not great to be collecting that much garbage so often, and the amount collected seems to increase depending on scene complexity (even a static scene). GC locks the browser frame, after all, so as little GC as possible by three.js by default would be helpful.

**Comment by tschw** [comment]
@robhawkes 
> there's certainly saw-toothing going on

Whether it's harmful is a matter of the scale. Once it impacts the frame rate, there is obviously a problem.

The 10MB in `webgl_materials_variations_standard` become 1MB without `TextGeometry`  are being used (turning those into buffers will probably help), so I'm just documenting that it's less dramatic than it first seems.

That being said, I'm too interested why garbage piles up at all. I tried `webgl_geometry_cube` and there too is some oscillation. It comes out of the renderer and stops when telling the console to
```javascript
> renderer.render = function() {}
```
.

> > I was wondering about the arrays for object sorting being created every tick

> Got rid of that a while ago. They are being reused, see render, projectObject and pushRenderItem.

This is one of the prominent spots using dynamic memory every frame. But there should be no allocation required, unless the number of rendered objects varies due to culling.
We could tighten this case up even further, by replacing the array of structures by a structure of arrays. This way, no inner structures would ever have to be allocated. However, that approach won't play too well with in-place sorting, so I guess we'd need all arrays twice plus an extra array for the sort order to do it the way I sort keyframes (see [`AnimationUtils, line 45-84`](https://github.com/mrdoob/three.js/blob/master/src/animation/AnimationUtils.js#L45-L84)).

I also know that the renderer uses dynamic memory (without much optimizations in place, if what I remember is still the current state) for animated meshes, but there are none in the examples we look at.

@mrdoob 
Any clues?

**Comment by mrdoob** [comment]
@tschw Not sure. By now I just had a look at the Profiler and fixed some code that was deoptimising.

**Comment by tschw** [comment]
@mrdoob 
OK, I had a deeper look into this one.

You can see the sawtooth shapes in "Timeline" of `webgl_geometry_cube`. Now when actually recording heap allocations in the "Profiles" tab and selecting a timeframe (this is important, because the full heap is recorded at the beginning of the profile), you can see that the example actually runs entirely without allocations over multiple seconds. Occasional allocations are not from our code but from Chrome further optimizing the program while it is running.

Conclusion: **Sawtooth shapes show up, because Chrome uses dynamic memory for its internal bookkeeping and there is nothing we can do about it.**

**Comment by mrdoob** [comment]
Thanks for investigating!

There are functions that are being deoptimised though. I'll keep investigating and refactoring code so V8 is happy.
