### ISSUE TITLE
Setting antialias after constructing renderer doesn't work

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#8265]
_Rather a question than an issue... Might be an improvement if it is possible to change._

Normally I can set `antialias` during constructing of the `WebGLRenderer` like this:

    renderer = new THREE.WebGLRenderer({antialias: true});
    renderer.antialias = true;

But I cannot set antialias after construction like this:

    renderer = new THREE.WebGLRenderer();
    renderer.antialias = true;

I was a bit confused because normally this works for many of the other properties of the renderer.
It turns out this is because the actual antialias property is stored in a private variable `_antialias` so it is not publicly accessible. 

The question:
Is this on purpose because this setting cannot be changed after construction of the renderer? Or can it be made public so switching antialias on/off can be done in realtime?

**Comment by mrdoob** [comment]
> It turns out this is because the actual antialias property is stored in a private variable _antialias so it is not publicly accessible.

Nope, it's because we need to recreate the whole WebGL context in order to change that. I think the browser vendors were doing some work to be able to share resources between webgl contexts. With that in place it would make more sense to try to implement `.antialias`. So at the moment you could just create a new `WebGLRenderer` instead.

**Comment by Wilt** [comment]
@mrdoob Thanks a lot for the answer.
