### ISSUE TITLE
jagged edges on rotating sphere

### ISSUE THREAD

**Issue by jackiboy** [mrdoob/three.js#8320]
Hello.

I am having a few issues with jagged edges on a rotating sphere.

I have tried quite a few versions of Threejs (both dev & production), turning on and off the alpha channel and turning on and off anti aliasing. but I can't seem to smooth out the edges

The javascript file is located below.
[globe.js](https://github.com/jackiboy/the-solar-system/blob/gh-pages/assets/js/lib/threejs/globe.js)
And the result is below
[Result](http://thesolar.systems/planet/jupiter/)

Any help would be greatly appreciated.

##### Three.js version

- [X] Dev
- [X] Production
- [X] r74
- [X] r73
- [X] r72
- [X] r71
- [X] r70

##### Browser

- [X] Chrome
- [X] Firefox

##### OS

- [x] All of them
- [ ] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] Android
- [X] IOS

**Comment by bhouston** [comment]
Turn on anti-aliasing: http://benchung.com/antialiasing-three-js/

**Comment by bhouston** [comment]
I tihnk anti-aliasing generally helps.  The other thing you can do is position the light so that it is stationary even if you rotate the sphere and have it fall off / darken just as it reaches the edges of the sphere, that will soften the edges.  There are post effect approaches you can use with the EffectComposer, as well such as FXAA, SMAA and MSAA.  I'd recommend FXAA as the fastest one, although SMAA may produce better results at the cost of lower framerates.

**Comment by jackiboy** [comment]
@bhouston I tried turning anti aliasing on and it no effect. I have not used effectComposer before but will have a look. I want to keep the project as lean as I possibly can.

**Comment by erichlof** [comment]
Hi @jackiboy ,
The correct parameter name inside the WebGLRenderer constructor is 'antialias: true',  not 'antialiasing: true' as you have in your globe.js source file.  Here is the WebGLRenderer source code line confirming this:
https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L20

Also, upping the width and height segments of the sphere (planet) geometry might help smooth out its silhouette against the space background, at the possible minimal cost of framerate (something to be cautious of on mobile as you know).  To combat this, instead of using SphereGeometry as you have in your globe.js file, use SphereBufferGeometry, which is always more performant.  

If you have any more problems please use StackOverflow as stated in this message board's guidelines.  Best of luck to you! :)

**Comment by jackiboy** [comment]
@erichlof  @WestLangley apologies I should have read the guidlines more clearly.

Thank you for your tips & help. fixing the anti aliasing typo really made a big difference on desktop.

**Comment by WestLangley** [comment]
@jackiboy Typing `renderer.getSize()` into the console shows 300 x 150. You do not set the renderer size. That may be your problem. Study the three.js examples.
