### ISSUE TITLE
Missing ColorKeyframeTrack.js

### ISSUE THREAD

**Issue by sunag** [mrdoob/three.js#8447]
##### Description of the problem 
Hi. I have some problems in the last release r75.

~~- Problems when cloning. Missing conditional in set `userData` https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L700~~
- Missing ColorKeyframeTrack.js in .min https://github.com/mrdoob/three.js/blob/master/src/animation/tracks/ColorKeyframeTrack.js
...

##### Three.js version

- [x] r75
- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by sunag** [comment]
I think cloning bug was in my code :blush:

**Comment by tschw** [comment]
```
tosc@localhost ~/Development/webgl/three.js $ git status src/animation/tracks/ColorKeyframeTrack.js 
On branch dev
nothing to commit, working directory clean
```

OK.

Apparently not listed in https://github.com/mrdoob/three.js/blob/master/utils/build/includes/common.json and thus excluded from the build. 

As long as we just interpolate color values linearly (or nonlinearly because they're often already gamma-corrected for the display, however), might as well just use a vector track for colors. The tracks are array-based, so the distinction of `Color` vs. `Vector3` happens in the binding code.

**Comment by mrdoob** [comment]
Added.

**Comment by tschw** [comment]
Thanks. I was just about to make a PR.
