### ISSUE TITLE
OBJLoader does not handle more than one material per object/group

### ISSUE THREAD

**Issue by grzegorzborowiak** [mrdoob/three.js#8681]
##### Description of the problem 

It is possible for one object/group to have multiple materials, e.g. to have 12 faces of material A and next 12 faces of material B. Current implementation does not handle it properly. 

I changed OBJLoader.js, now it creates not one mesh per object, but one mesh per tuple (object name, group name, material name, material smoothness), named 'o:foo,g:bar,usemtl:baz,s:[01]'. This way there is still one material per mesh, but more than one mesh per object/group, albeit with somewhat convoluted names.

I don't know how to make an attachment in this issue tracker (I'm new to github), so I share that externally and provide links:

http://gnu.univ.gda.pl/~grzes/three.js/OBJLoader.js
http://gnu.univ.gda.pl/~grzes/three.js/OBJLoader.js.diff

##### Three.js version

- [x] Dev
- [ ] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by jonnenauha** [comment]
I think this is a "duplicate" at least of the discussion here https://github.com/mrdoob/three.js/issues/8203 

Creating more objects than what was defined in the file and/or mangling names does not sound like the best solution for this. We discussed in that issue how MultiMaterial and geometry groups should be utilized to achieve having different materials inside one geometry (changes material mid face declarations etc).

I haven't gotten into implementing that, mainly because I don't have good files to test it against. Could you provide your .obj and related .mtl/texture files as dropbox link or something here? Or do you know some model I could download to test this on.

**Comment by grzegorzborowiak** [comment]
This is a model which exhibits described behaviour:
http://gnu.univ.gda.pl/~grzes/arc/obj/domek/
You can view it correctly:
http://gnu.univ.gda.pl/~grzes/arc/
or incorrectly:
http://gnu.univ.gda.pl/~grzes/arc/wrong.html

**Comment by jonnenauha** [comment]
I've fixed loading of your asset in my above PR, lets see when it gets merged.

![objloader_domek](https://cloud.githubusercontent.com/assets/157519/14692011/27f81808-075d-11e6-93e9-39684d8082da.png)
