### ISSUE TITLE
Raycast caches bounding sphere and does not update on geometry change

### ISSUE THREAD

**Issue by jimmyland** [mrdoob/three.js#8715]
##### Description of the problem

The raycaster for mesh uses the bounding sphere, and computes it for the caller only if it is null.  If geometry is expanded after the first raycast (setting needsUpdate variables as needed), raycasts will fail on geometry outside the initial bounding sphere (unless the ray happens to intersect the initial sphere).

The geometry docs say the bounding sphere will not be implicitly computed, so I did not expect I'd need to maintain it unless my code was explicitly using it.  Perhaps the raycaster should not compute the bounding sphere implicitly, or the docs should explain the special cases where it will be computed implicitly?
##### Three.js version
- [ ] Dev
- [x] r76
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
> The raycaster for mesh uses the bounding sphere, and computes it for the caller only if it is null. If geometry is expanded after the first raycast (setting needsUpdate variables as needed), raycasts will fail on geometry outside the initial bounding sphere (unless the ray happens to intersect the initial sphere).

Can you create a jsfiddle with that case?

**Comment by jimmyland** [comment]
Here's a jsfiddle demonstrating the issue: http://jsfiddle.net/kLnrLypt/

Click the sphere to make it bigger.  The raycast won't hit anything outside the original sphere's bounding sphere.

**Comment by SuberFu** [comment]
@jimmyland From my understanding the bounding sphere is handled like this.
1. When a THREE.Geometry (or BufferGeometry) is created, no bounding sphere is calculated.
2. Whenever anyone needs a bounding sphere (raycaster, frustum culling, etc), it invoke computeBoundingSphere on the geometry to get one (said bounding sphere is cached on the geometry).
3. If there's already a boundingSphere, it reuse that boundingsphere on the geometry.

Therefore, everytime you update anything that would effect the bounding sphere, you need to explicitly called computeBoundingSphere to update it, just setting the needsUpdate is not enough.

I guess that's due to compute bounding sphere being a fairly intensive calculation, and should generally be called when you really need it to.

**Comment by jimmyland** [comment]
@SuberFu yes, my point was just that this is undocumented / actually in conflict with the docs, so either it or the docs should be changed, but I wasn't sure which or how.

**Comment by mrdoob** [comment]
Yeah, the boundingSphere will only be computed in cases when it's needed (raycasting, projecting) and it has not yet been computed. If you modify the geometry you'll need to call `computeBoundingSphere()`.

**Comment by jimmyland** [comment]
Ok cool; can/should I fix the docs to match that, then?

**Comment by mrdoob** [comment]
Yes please 😊
