### ISSUE TITLE
Bad deprecation warning in WebGLRenderTarget?

### ISSUE THREAD

**Issue by killroy42** [mrdoob/three.js#8789]
##### Description of the problem

I am currently seeing "THREE.WebGLRenderTarget: .minFilter is now .texture.minFilter." warnings generated in "Three.Legacy.js", line 609
(https://github.com/mrdoob/three.js/blob/6400f2c9b6ee58e01c005a66f00c7cd1113752aa/src/Three.Legacy.js#L609)

But looking at "WebGLRenderTarget.js", line 28 (https://github.com/mrdoob/three.js/blob/6400f2c9b6ee58e01c005a66f00c7cd1113752aa/src/renderers/WebGLRenderTarget.js#L28) it appears that there is no other way of passing minFilter into the constructor via options.

Perhaps I'm missing something here?
The code that causes this looks like this:

```
new THREE.WebGLRenderTarget(width, height, {
  minFilter: THREE.LinearMipmapLinearFilter,
  magFilter: THREE.LinearFilter,
  format: THREE.RGBFormat
});
```
##### Three.js version
- [x ] Dev
- [ ] r76
- [ ] ...
##### Browser
- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [] All of them
- [x ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by tschw** [comment]
Please post a stack trace.

Seems the options from the constructor are only passed on to the texture constructor, which gives me a reason to believe the warning actually originates elsewhere.

**Comment by tschw** [comment]
Setting a breakpoint in the deprecation handler should do...

**Comment by killroy42** [comment]
It was a warning, so there was no stack trace. Unfortunately I've made changes and no longer receive the warning. I will try setting minFilter all over and see if I can reproduce it again. Feel free to close this issue in the meantime, until I can create the reproduction.

**Comment by tschw** [comment]
@killroy42 
> It was a warning, so there was no stack trace.

I noticed this after by first post. Hence I added:

> Setting a breakpoint in the deprecation handler should do...

You can see the stack in the debugger when it stops at the warning then.

@killroy42 :
> I've made changes and no longer receive the warning.

So you can confirm that the constructor invocation above is innocent?

I guess *something* could still be touching it *somewhere*, unless you went `renderTarget.minFilter` in which case the warning would just be correct, since this property no longer exists.

In case of the latter, please close the ticket.

> Feel free to close this issue in the meantime, until I can create the reproduction.

Otherwise please leave it open.

Is your code based on an example / using components outside the core library?

**Comment by Mugen87** [comment]
> Feel free to close this issue in the meantime, until I can create the reproduction.

Okay 😊
