### ISSUE TITLE
VREffect should take into account VRStageParameters

### ISSUE THREAD

**Issue by borismus** [mrdoob/three.js#8829]
See spec: https://mozvr.com/webvr-spec/#interface-vrstageparameters

Without applying the sittingToStandingTransform to the camera, which should be done in VREffect (see https://github.com/toji/webvr-samples/blob/gh-pages/05-room-scale.html#L223), the scene will not render correctly in high end HMDs. Devs will also need to be cognizant of sizeX and sizeZ if they want to match their virtual environments to the real ones.

**Comment by borismus** [comment]
cc @dmarcos @toji

**Comment by toji** [comment]
`sittingToStandingTransform` should be applied in the `VRControls`, not the `VREffect`, since it's about the placement of the camera and not how the stereo view is rendered. Fortunately it's already been added and all devs have to do is set `vrControls.standing = true;`! (See https://github.com/mrdoob/three.js/blob/master/examples/js/controls/VRControls.js#L55 and https://github.com/mrdoob/three.js/blob/master/examples/js/controls/VRControls.js#L108)

Exposing the stage size is another matter, and we should figure out a reasonable way to handle it.

**Comment by borismus** [comment]
Ooh good points on all counts. Definitely should be part of controls, that was my mistake. Somehow didn't notice it was already implemented as I'm still on r75. This is great, will migrate to r76 and test! As for stage size for now we can have devs query the HMD directly.

**Comment by SpaceHexagon** [comment]
Perhaps the VREffect could use a similar ```this.scale``` as VRControls (if value supplied) ?  
I ran into this issue, where everything in my scene was too large (for my eyes).
https://github.com/mrdoob/three.js/blob/7d847de7bd8c999b822f2bcb4f43caebfcfecff0/examples/js/controls/VRControls.js#L52 https://github.com/mrdoob/three.js/blob/7d847de7bd8c999b822f2bcb4f43caebfcfecff0/examples/js/effects/VREffect.js#L313

**Comment by mrdoob** [comment]
@SpaceHexagon I would suggest scaling down the scene instead... `scene.scale.setScalar( 0.1 )`

**Comment by brianchirls** [comment]
This can probably be closed. I believe it's been implemented.
