### ISSUE TITLE
how to make a camera follows the terrain's height in this sample: http://threejs.org/examples/#webgl_terrain_dynamic

### ISSUE THREAD

**Issue by 78pvc** [mrdoob/three.js#8833]
Hi all,

I would like to know how I could make the camera in this three js example: [http://threejs.org/examples/#webgl_terrain_dynamic](url)
follows the terrain's height. 
So, while the terrain is moving, the camera will go up and down according to the hills (height) of the terrain.

In other words, how I could get the terrain's height, knowing that the height of the terrain is built by an heightmap ?

I've already try with a Raycaster as follow;
`var raycaster            = new THREE.Raycaster( camera.position, new THREE.Vector3(0, -1, 0) );`
`var intersects = raycaster.intersectObject( terrain, false );`
`var intersect_point = intersetcs[0].point;`

But `intersect_point` always has its y value equal to 0 no matter where the camera is located.
Indeed, the height of the terrain in this example is created by an heightmap. Thus, the geometry of the terrain which is a plan is not changed by the heightmap and remains flat, hence the result of the raycaster.

Could you help me on how to find a way to get the terrain's height for a given position.

thanks a lot for your help.

**Comment by 78pvc** [comment]
is that someone can help ?

**Comment by SuberFu** [comment]
First off, this should be in StackOverflow, as this is not an "issue" with the THREE.js library.

To answer your question. One possibility is to perform an additional rendering using a depth map.
In short, modify the `/examples/js/ShaderTerrain.js` so that instead of rendering with color of the terrain, have the color be based off the "distance" from the camera. Then, render to a depth map with a camera at the same position and pointed straight down, then read the "color" of the center pixel, that should give you the height.

**Comment by 78pvc** [comment]
Hi SuberFu,

thanks for your answer. 

Sorry if I used a wrong channel to put my question, but I've seen someone put his question here too, so I thought I could do the same.
Anyway, I've also put it on stackoverflow too: http://stackoverflow.com/questions/37197194/how-to-make-a-camera-follows-the-terrains-height-in-this-sample-http-threejs
