### ISSUE TITLE
IQ's fast stereo rendering article

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8849]
##### Description of the problem

Not sure how many of these are relevant to WebGL as it doens't support geometry shaders but it is a pretty decent article none the less:

http://www.iquilezles.org/www/articles/stereo/stereo.htm
##### Three.js version
- [ ] Dev
- [ ] r76
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
The articles of Íñigo Quílez are very educational. But unfortunately sometimes too complex for me :satisfied:

**Comment by tschw** [comment]
@bhouston 
Nice, a new one :). Interesting indeed, but before even going there, I guess we'd want to sort by GPU program (you once posted a link to an article comparing the cost different state changes, showing programs to be the most expensive ones by far). In this context, one could also consider the on-screen size of the objects to keep the painter order efficient. Coincidentally there's [another IQ article](http://www.iquilezles.org/www/articles/sphereproj/sphereproj.htm) that describes a simple heuristic that can be used for this purpose. With that in place, we will probably see a very nice performance boost from this approach to stereo.

@Mugen87 
> The articles of Íñigo Quílez are very educational. But unfortunately sometimes too complex for me

Sounds stereotypical (no pun intended). Did you actually look at it? This one's really easy to get. No computational geometry involved - just basic programming matters on renderer implementation :).

**Comment by Mugen87** [comment]
@tschw I've actually meant the more math related stuff. And yeah, i've read the mention article about stereo rendering :wink:

**Comment by capnmidnight** [comment]
I'd be interested in doing the work to implement this idea in Three.js. It's a really simple concept, and something I've done before as a hack on my own forks of Three.js (though I've since stopped doing that, because it makes keeping up with upgrades hard). So I'd be really interested to have stereo rendering "baked in" to WebGLRenderer instead of being applied as an ad hoc Effect class. 

But I'm not too familiar with your process, so I'd like to discuss it with everyone before I run off and do it and submit a PR that ultimately gets ignored because I didn't do things in the way everyone else expects.

This could potentially be implemented by making the `WebGLRenderer::render()` method gain the ability to treat the `camera` parameter as an Array of cameras. To reflect this, the name of the parameter would be changed to `cameras`:
* `render(scene, camera, renderTarget, forceClear)` to 
* `render(scene, cameras, renderTarget, forceClear)`.

In the legacy case of the cameras parameter being a camera object and not an Array of camera objects, the render method would replace it with a single-element Array containing the camera object that the user provided. Externally, it will appear that no different processing has occurred and the render will behave as before, providing a distinct "opt-in" for this feature and not getting in the way of any people not using stereo rendering.

The call tree from there would be modified as necessary to push the cameras parameter around and iterate over it at each draw-call site.

**Comment by capnmidnight** [comment]
I'm sorry, there was a hungry baby in the background that distracted me during second-guessing myself on the design.

Just having an array of cameras won't be sufficient. It also needs additional Viewport data. So nix nearly that entire previous post. 

# WebGLRenderer::render()
Instead, there should be an additional parameter to the `render()` method, called `views`:
* `render(scene, camera, renderTarget, forceClear)` to 
* `render(scene, camera, renderTarget, forceClear, views)`

Notes:
* The views are an Array of CameraViewOffset classes (see below)
* In the default case of `views` being undefined, it will make no additional processing performed, so stereo rendering is distinctly opt-in.
* The array will not be constrained to a certain length, to be able to support multiple cameras for use in a CAVE system or the like.
* Internally, the views will be passed around as necessary to be able to modify the camera and viewport just prior to each individual draw call.

# WebGLRenderer::renderStereo()

Additionally, a new method will be added to the WebGLRenderer class, having the implementation:

    renderStereo(scene, camera, views, renderTarget, forceClear){
        this.render(scene, camera, renderTarget, forceClear, views);
    }

This is to provide the user a more natural method call when opting in to stereo rendering, without breaking backwards compatibility. This way, they can leave off the renderTarget and forceClear values, as I assume is typically done in the vast majority of calls to `render()` for mono displays.

# CameraViewOffset
The CameraViewOffset class encapsulates all of the data to modify both the camera and the viewport on the WebGL context. Some pseudocode:

    class CameraViewOffset {
        transform: THREE.Matrix4,
        viewport: THREE.Vector4
    }


    var _cameraMatrixCopy = new THREE.Matrix4();
    var _viewportCopy = new THREE.Vector4();
    render(scene, camera, renderTarget, forceClear, views){
        if(views === undefined || views === null){
            views = [{
                transform: new THREE.Matrix4().identity(),
                viewport: new THREE.Vector4(1, 1, 1, 1)
            }];
        }
       
         // render shadows and such

        _viewportCopy.copy(_viewport);
        foreach(object in scene){
            // bind object properties
            foreach(view in views){
                _cameraMatrixCopy.copy(camera.matrix);
                camera.matrix.multiply(view.transform):
                this.setViewport(
                    _viewport.x * view.viewport.x,
                    _viewport.y * view.viewport.y,
                    _viewport.z * view.viewport.z,
                    _viewport.w * view.viewport.w
               );

               // perform draw call:
               //   blah blah blah

               // reset the camera
               camera.matrix.copy(_cameraMatrixCopy);
            }
        }
        _viewport.copy(_viewportCopy);
    }
           

# Issue
If the user has any objects added to the camera itself, then the objects will render strangely. However, since this is opt-in, I'm assuming the user will understand this and will have the camera attached to a notional "head" object in their scene graph, with the real camera having no transforms and all head-tracked orientation changes being applied to the "head" object.

**Comment by tschw** [comment]
@capnmidnight
> I'd be interested in doing the work to implement this idea in Three.js. It's a really simple concept, and something I've done before as a hack on my own forks of Three.js (though I've since stopped doing that, because it makes keeping up with upgrades hard). So I'd be really interested to have stereo rendering "baked in" to WebGLRenderer instead of being applied as an ad hoc Effect class. 

Cool! But, as said, I don't think our renderer is quite ripe for it yet. Yes, you can hack it into it. And you will even see a fine speedup already. Then OTOH, stereo is a fairly special case compared to anything else which isn't optimal yet, so I think we should go for that (probably greater) speedup (not just for stereo) first.

We'd want to determine the render state in the traversal / frustum culling a.k.a. projection phase and buffer it. This way, we also know which program (-instance != material, but currently oversimplified that way) will be used for each object. Then we can consider it during sorting and minimize the most costly state changes.

This is also in line with moving towards WebGL2 uniform buffers (also used in the above article), and closer towards fully automated uniforms as found in other engines. My proposal for a first step into this direction is discussed in #8552.

For frustum culling to happen only once, we'd need a better `StereoCamera`. I've recently done some research on it and wrote [this article](https://github.com/tschw/angler.js/wiki/The-Virtual-Stereo-Camera-Rig) which explains the mapping between mono and stereo frusta and the correct parametrization of the stereo system by meaningful values that control the aspects of the effect independently (with the naive approach found in many places, the inputs are geometrically coupled).

**Comment by mrdoob** [comment]
I think we could consider doing a `THREE.MultiCamera` to which we can add any number of cameras. Also, `THREE.PerspectiveCamera` does have a [`setViewOffset`](https://github.com/mrdoob/three.js/blob/master/src/cameras/PerspectiveCamera.js#L138-L151) already.

**Comment by tschw** [comment]
@mrdoob 
> I think we could consider doing a THREE.MultiCamera to which we can add any number of cameras.

For a "random" array of cameras we'd have to do frustum culling individually and duplicate all render items. For a true stereo setup, there's a specific calculation that allows you to extract one frustum that captures the field of view as seen by both eyes.

> Also, THREE.PerspectiveCamera does have a setViewOffset already.

Actually you can already use `.filmOffset` for the "stereo shear" and still have your installation span e.g. 4x4 screens, which could then easily be set up using `setViewOffset` :).

**Comment by Mugen87** [comment]
Closing. `THREE.ArrayCamera` was implemented with `R85`. It is an integral part of the engine's *Single-Pass Stereo Rendering* used for WebXR.
