### ISSUE TITLE
How to load real-time obj file effectively

### ISSUE THREAD

**Issue by cd547** [mrdoob/three.js#8863]
##### Description of the problem 
I have a system to generate an obj file at regular intervals.
Hope to achieve regular loading latest obj  file  and show it on website.
I use the method of objloader, but there will be a certain block in the browser when loading.I hope to find out more suitable method to solve.
##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by antont** [comment]
I recenty profiled a similar case, not using obj files though but ogre binary meshes. There at least the bottleneck is in the javascript parsing of the geometry. I think there are two possible solutions:

1. Use a worker so the geom parsing does not block rendering. Only the CTM loader in three.js does this currently. I tested with that and it seemed to help, especially on a powerful gaming laptop there was almost no visible pause at all anymore.

2. glTF format is made so that the geom is already webgl binary buffers so that it doesn't need to parsed in JS. Therefore it might be so quick to load that it doesn't cause a pause. I haven't measured this yet though, just a thought.

**Comment by cd547** [comment]
Thanks!
 I have OBJ file,But I don't have CTM file. 
Would you mind show me an example about Worker in Three.js？
