### ISSUE TITLE
Texture not consistent with MTLLoader and OBJLoader

### ISSUE THREAD

**Issue by unclecheah** [mrdoob/three.js#8871]
Textures that are big and takes longer to load does not show up. This does not happen with the old OBJMTLLoader. See http://webgl.unclecheah.com

Relevant codes:
```javascript
mtlLoader.setBaseUrl ('data/objects/skeleton/');
mtlLoader.setPath ('data/objects/skeleton/');
mtlLoader.load ('skelet.mtl', function (mat) {
	mat.preload ();

	objLoader.setMaterials (mat);
	objLoader.setPath ('data/objects/skeleton/');
	objLoader.load ('skelet.obj', function (obj) {
		scene.add (obj);
	}, onProgress, onError);
});
```

##### Three.js version

- [ ] Dev
- [X] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by jonnenauha** [comment]
Yeah, I noticed this yesterday. I can take a look. I assume that the `data/objects/skeleton` assets are in the repo.

@mrdoob I haven't touched any of the texture logic. My `setPath/setTexturePath` tweaks are not in r76 yet. This kind of sounds like the black textures in chrome bug. You also had that fix commit that does no longer set null textures to the gl state, if loading/using a material that does not have its textures in place yet?

@unclecheah any change you could try if `dev` HEAD of three.js fixes the issue? Also if you are using Chrome make sure you have the latest updates. There was a texture loading related bug in Chrome that failed to notify three.js texture loader the on loaded even (afaik when following the issue).

**Comment by jonnenauha** [comment]
Seems I can get the test assets from your site. Though I cant get the page to fail, textures do load always for me. Tried with and without cache. Without cache when choking the network in dev tools, you can see materials are black for a moment until textures are loaded.

Few of `[.CommandBufferContext]RENDER WARNING: there is no texture bound to the unit 0` are printed while the texture is null. I believe @mrdoob recent change fixes this, and its just a warning in render, has nothing to do with the texture fetch+load part.

**Comment by unclecheah** [comment]
@jonnenauha I tried dev HEAD as well as the latest of different browsers, all to no avail. No warnings/errors in console. I'm beginning to think it's my code, but can't figure out anything wrong. Are you saying you can load the model with everything textured? I only see the bones textured and every other parts white.

I've attached the object and all dependencies here; also attached the screen-capture of what I see.

![skeleton](https://cloud.githubusercontent.com/assets/2209281/15274281/e6163220-1ae0-11e6-9ce7-dde2a2dedf2a.jpg)


[skeleton.zip](https://github.com/mrdoob/three.js/files/264985/skeleton.zip)

**Comment by jonnenauha** [comment]
I see the same thing, I just wasn't sure what I was supposed to be seeing :)

I believe I know what the bug is now. Its related to issue I made recently https://github.com/mrdoob/three.js/issues/8792 

You file has 1) mtlib 2) usemtl 3) start object (g). I have to read the OBJMTLLoader a bit and see what the spec says. The OBJLoader parser reads `usemtl` to the currently parsed object. It looks like your file is declaring the material first, then the object. It then resets the material when a new object is started (right after the material). As you can see from the issue this is not what the spec says.

What exporter are you using? The obj seems to have a lot of redundant mtllib lines in it. I don't think its wrong, I just haven't seen that before.

Thanks for the test assets. I try to look into this soon.

**Comment by unclecheah** [comment]
Somebody else created this, I don't know what exporter was used. As a quick test, I downloaded and tried some free obj files. Most (though not all) seem to have the same problem.

Thanks for looking into this. Appreciate it!

**Comment by team4music** [comment]
Could it be that i have the same issue? I saw something simlar today on my models, but tought it is my exporter.. example 
![model](https://cloud.githubusercontent.com/assets/5567284/15288741/61d2a470-1b6d-11e6-8f43-4d70e2400535.jpg)

**Comment by jonnenauha** [comment]
@unclecheah Do you have a reference picture or can you tell me if this looks correct now. There are some black areas in the top of the skull, but I'm beginning to thing this is by design?

![image](https://cloud.githubusercontent.com/assets/157519/15330911/749ed1a0-1c67-11e6-92f7-431df02fc02b.png)

You obj was interesting as it does a few things differently. It declares `usemtl` before `o/g` objects and their faces. Usually `usemtl` is set after the object declaration, I could not find if this is by the spec, but it is unusual. On top of that you also had a MultiMaterial in the first geometry, which made me catch another bug while looking into this.

**Comment by unclecheah** [comment]
@jonnenauha I think you are right about the skull. Here is how it looks like with the old OBJMTLLoader.

![screenhunter_10 may 18 08 12](https://cloud.githubusercontent.com/assets/2209281/15343608/ac7aa6e4-1cd0-11e6-8418-b6ca37f23eeb.jpg)

Thank you so much for fixing this! :)
