### ISSUE TITLE
maybe add callback check to AnimationMixer.js

### ISSUE THREAD

**Issue by pontiffpublishing** [mrdoob/three.js#8885]
##### Description of the problem

How about adding a callback check to the updateTime function of the animation mixer.  At around line 770 of r76, right after the dispatch-event-"finished" call, or instead of it.

```
             if (this.callback) this.callback();
```

This makes it easier for the programmer to provide unique callbacks on a per-action basis, and it probably is more performant than processing an dispatched event.
##### Three.js version
- [ ] Dev
- [x ] r76
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by tschw** [comment]
@pontiffpublishing 
You may as well put your code into an event listener. This code path is not really *that* performance critical to worry about the overhead of the dispatched event: If you have so much action going on that it matters, other things will slow down way before it becomes significant.

An event listener that checks for a callback is one line of code, and JS programmers are usually quite familiar with this kind of interface, so I'd say it's sufficiently trivial to get a callback. As for replacing the event dispatch altogether, I don't really like the idea of replacing a flexible mechanism with a more limited one.

Hope this isn't too demotivating in case you've been looking for something to contribute. Since you seem articulate and have been digging into animation - I'd certainly welcome help on documenting it, for one instance - and it would make it easier to use too - to a much greater extent, even :).

**Comment by pontiffpublishing** [comment]
I wont have any free time for the next 10 days, or so.  If the
documentation still needs updating then, I will gladly help.  Thanks.

**Comment by pontiffpublishing** [comment]
Turns out, I am off today.  So I'll see if I can do something helpful with
the animation documentation.  If you want to give me some direction, that
would be great.

Funny story:  I could not make it to work today because all downtown San
Francisco is filled with tens of thousands of people dressed up like super
heroes, tetris pieces, and you-name-it.  The Bay to Breakers footrace.


---------- Forwarded message ----------
From: Kevin Pope <kevin.pope.ppc1@gmail.com>
Date: Sun, May 15, 2016 at 7:44 AM
Subject: Re: [mrdoob/three.js] maybe add callback check to
AnimationMixer.js (#8885)
To: "mrdoob/three.js" <
reply@reply.github.com
>


I wont have any free time for the next 10 days, or so.  If the
documentation still needs updating then, I will gladly help.  Thanks.

**Comment by looeee** [comment]
@pontiffpublishing if you are still interested in updating the animation docs... #10103
