### ISSUE TITLE
OBJLoader make one material for every mesh in the file

### ISSUE THREAD

**Issue by Mathieu-Pasco-Breillot** [mrdoob/three.js#8899]
##### Description of the problem 

When I load an OBJ file which contains multiple objects, I found a little issue which is a material reference between objects.
To be clear whatever I do to one mesh's material it will be applied to the other mesh.

There is a material reference made on meshes.

I'm expecting to be able to work on mesh's material independently, meaning they are not linked to each other. 

##### Three.js version

- [x] Dev
- [x] r76
- [x] master

##### Browser

- [ ] All of them
- [x] Chrome 50.0.2661.102
- [x] Firefox 46.0.1
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mathieu-Pasco-Breillot** [comment]
I know how to fix it by the way.
The fix must be done in OBJLoader.js at line 525 where :
`var material;`
must be replace by :
`var material = null;`

It will prevent the OBJLoader to reuse the same material for multiple object in one model.
It will prevent the reference to be added.

**Comment by jonnenauha** [comment]
hmm, good catch. I'll fix this, I have other pending fixes to the loader as well.

Thanks for reporting.

**Comment by Mathieu-Pasco-Breillot** [comment]
No problem it was my pleasure ;)

**Comment by jonnenauha** [comment]
@Mathieu-Pasco-Breillot I did not look at the code when I commented earlier. Looking at it more closely now this was already fixed by me after r76 in a separate PR (https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader.js#L616). So fix will come in r77 for you or just fetch latest `dev` branch and copy the new `ObjLoader.js` to your project (it is compatible otherwise with r76).

@mrdoob or @Mathieu-Pasco-Breillot you can close this issue
