### ISSUE TITLE
PBR reflection filtering. 

### ISSUE THREAD

**Issue by ghost** [mrdoob/three.js#8980]
##### Description of the problem

Hey! Straight to the problem: reflections on pbr materials are filtered in a very weird way and it can be easily seen on rough surfaces. I think this is connected with how roughness mip maps are filtered and generated.

Example: http://i.imgur.com/A9sOVBJ.png reflections look like they are celshaded.

HDR used: PISA files from examples.

Would love to see if there is a work around with this problem.
##### Three.js version
- [x] r76
##### Browser
- [x] All of them

**Comment by bhouston** [comment]
I've have to see an interactive example.

**Comment by 10-p** [comment]
The HDR cubemaps are not filtered, happens with your examples as well:
![reflectivity example](https://cloud.githubusercontent.com/assets/16543883/15629773/2c910c7a-2522-11e6-95bc-96becfbcffc5.png)

The original feature PR works good: [#8505 webgl_materials_reflectivity.html](http://ci.threejs.org/api/pullrequests/8505/examples/webgl_materials_reflectivity.html)

**Comment by bhouston** [comment]
I think I know why that was done.  I turned off interpolation of the HDR textures if they required decoding.  The reason was because interpolation of the values prior to decoding is wrong, especially for RGBE.  But that does produce other artifacts.  Maybe we should try to create a float/half representation if those extensions are available and that will allow for no-decoding to be used when accessing HDR values -- because they will not be encoded -- and we can interpolate half/float accurately.  Did you want to give that a stab and contribute it back?

**Comment by JansM** [comment]
Hey Ben! Sorry for the late answer. http://margevi.ch/hdrtest/test.html I modified your hdr environment example a little. At 0.7 roughness you can see what happens to blurred roughness reflections and I am not sure if example by 10-p demonstrates the same problem. At 0 rougness reflected environments look pretty good to me. I would love to contribute but as a 3d artist I rarely touch things beneath the bonnet. I will be happy if you can give me any articles/papers that I can research to have a better understanding of the problem (for personal study at least).
