### ISSUE TITLE
For OrthographicCamera Raycaster.SetFromCamera() sets ray.origin in the near plane

### ISSUE THREAD

**Issue by wojdyr** [mrdoob/three.js#9009]
For orthographic camera Raycaster.SetFromCamera() does:
```
      } else if ( camera instanceof THREE.OrthographicCamera ) {

        this.ray.origin.set( coords.x, coords.y, - 1 ).unproject( camera );
```
which sets `ray.origin` in the `camera.near` clipping plane, not in the plane of `camera.position`.
So if I want to set, say, `raycaster.far` consistently with `camera.far` I do:
```
  raycaster.setFromCamera(coords, camera);
  raycaster.far = camera.far - camera.near;
```

(if this was intended just close this issue.)

Three.js version: r77

**Comment by SuberFu** [comment]
Setting it from the "near" clipping plane do make more sense. As any objects closer than the near clipping plane is not visible. Otherwise, you get some weird issue that the ray caster is hitting an object that's not visible due to it being "removed" by the near clipping plane.

**Comment by WestLangley** [comment]
@wojdyr Yes, this [has come up before](https://github.com/mrdoob/three.js/issues/2453).

As you point out, the distance returned when raycasting using an orthographic camera is the distance from the near plane -- not the plane of the camera. The distance is still useful for sorting, however.

Since we reject hits that fall outside the raycaster near and far planes, and since the distance calculation is not correct unless `near` is zero, I expect there is a bug that needs to be fixed.

Who would like to propose a solution that works uniformly throughout the library?

**Comment by wojdyr** [comment]
I have no idea what else would need to be changed in the library, but in this particular function ray.origin could be set in the camera plane by replacing `- 1` in:
```
this.ray.origin.set( coords.x, coords.y, - 1 ).unproject( camera );
```
with `(camera.near + camera.far) / (camera.near - camera.far)`

**Comment by WestLangley** [comment]
@wojdyr That does appear to be correct, and the returned distance from raycasting matches the negative of the z-coordinate of the intersected point in camera space.
