### ISSUE TITLE
THREE.Box isEmpty returns false for empty box.

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#9146]
##### Description of the problem (three.js r78)

I closed [issue 9137](https://github.com/mrdoob/three.js/issues/9137) because I realized using the `intersectsBox`  is not the way to go for calculating whether I need to perform a boolean operation on my objects. 

I followed @carstenschwede his suggestion and will use the `intersect` method to calculate the intersecting box and check whether this intersecting box is empty instead using the `isEmpty` method, but then I discovered that the `isEmpty` method returns `false` for empty boxes.

##### Code example.
````
  min = new THREE.Vector3(0,0,0);
  max = new THREE.Vector3(0,0,0);
  emptyBox = new THREE.Box3(min, max);
  result = emptyBox.isEmpty();

````
Expected `result` to be `true` but it is `false`

**[A fiddle demonstrating this can be found here](https://jsfiddle.net/wilt/t6z8nLaf/)**

**Comment by Wilt** [comment]
A PR for this can be found [here](https://github.com/mrdoob/three.js/pull/9147)

**Comment by WestLangley** [comment]
In my view, a box containing a single point is not empty.

**Comment by carstenschwede** [comment]
I think I might have caused a little bit of confusion by introducing the concept of volume in your other issue. Although a box might have zero volume, it can still contain a point, because a point as such has no dimension.

I think the name `isEmpty` and the reference in the following comment about volume adds to the confusion:

```javascript
isEmpty: function () {
     // this is a more robust check for empty than ( volume <= 0 ) because volume can get positive with two negative axes
    return ( this.max.x < this.min.x ) || ( this.max.y < this.min.y ) || ( this.max.z < this.min.z );
},
```

`isEmpty` is *not* used to check for **volume** but instead to check if the result of an intersection is a valid overlap. (`isValid` or something might be a better name?)

This can happen for intersections that are a single point (like your example), a line, or a plane. All have zero volume but could still contain points that lie exactly on that intersection.

**Comment by mrdoob** [comment]
> In my view, a box containing a single point is not empty.

Correct.

Imagine a geometry with a single vertex at 0,0,0 used with `THREE.Points`. The bounding box will be 0,0,0 0,0,0 (instead of Infinity) The bounding box for such object shouldn't return as empty.

**Comment by Wilt** [comment]
@carstenschwede I think that is exactly what happened... Thanks all for clearing things up.
