### ISSUE TITLE
File size is too big when exported from threejs editor

### ISSUE THREAD

**Issue by prafful13** [mrdoob/three.js#9162]
Created an object in threejs editor using map feature of the editor to attach two images of 1.2mb and 0.3mb on two different planes. The object contains only these two planes and still on exporting the json file, the size comes out to be 11 mb.

**Comment by GGAlanSmithee** [comment]
Looking at the [editors toJson method](https://github.com/mrdoob/three.js/blob/master/editor/js/Editor.js#L462), it serializes the whole scene plus some additional things, including the editor history, which can be quite large under some circumstances I guess. I would suggest looking at the generated JSON to see what the large part of it is made up of.

**Comment by prafful13** [comment]
the JSON file is of just 105 lines and only the two url lines are too big.

**Comment by mrdumb** [comment]
> Created an object in threejs editor using map feature of the editor to attach two images of 1.2mb and 0.3mb on two different planes.
> The object contains only these two planes and still on exporting the json file, the size comes out to be 11 mb. 

That's because, by default, the textures are encoded base64 and included in that JSON.
p.s.
You should stay away from JSON, OBJ and other text files.
They might be good for didactical purposes, but they are noty suitable for online projects.
- significant downloading time
- huge memory footprint
- significant processing time
For best results in WebGL, use a **binary & compressed** format.
Such as **Sea3D**.

**Comment by Rayfoundry** [comment]
> For best results in WebGL, use a binary & compressed format.
> Such as Sea3D.

Interesting. How are materials handled with Sea3D? Can you use MeshStandardMaterial for instance?
