### ISSUE TITLE
Clock.js is counting time slower each time.

### ISSUE THREAD

**Issue by MaikSoriano** [mrdoob/three.js#9174]
##### Description of the problem 

Hi, I have an animation which start when I press a button, then I need to stop the animation after 5 sec since it started. The fact is that the second time I press the button the animation is playing for more time than the first. 

This is the animate function where I check the time:

`
function animate()
{
    requestAnimationFrame(animate, renderer.domElement);
    if((clock.getElapsedTime()-clock.lastTime)*100 > + 5.3)
    {
          clock.stop();
          clock.lastTime = clock.getElapsedTime();
    }
    console.log((clock.getElapsedTime()-clock.lastTime)*100);
}

`

And here you can see the [log in youtube](https://youtu.be/rNkzv3qSphI)

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by BrianCraig** [comment]
Hi! seems there is nothing wrong with the clock module, it's only youre using how its not supposed to be used. You don't drive a car opening the chasis and pushing the motor.
Remember that you should not modify an internal value like this
`clock.lastTime = clock.getElapsedTime();`
See that ? if you want to restart the counter you should use the method
`clock.start()`
or, get a new instance
`clock = new THREE.Clock()`

grettings :)

**Comment by MaikSoriano** [comment]
@BrianCraig Actually `clock.lastTime` is not a "real" property of clock, it has been created by myself. Same result if I change  `clock.lastTime` by a global variable.

Create a new instance each time takes too much resources, doesn't it?

**Comment by BrianCraig** [comment]
@MarkSoriano Hi! 

Shortly, **there is not a resource problem**. Here is [the source of clock
](https://github.com/mrdoob/three.js/blob/master/src/core/Clock.js), here is an explanation why it always not used clock instances get deleted [Memory management Mozilla Wiki](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management).

Because when you assign
`clock = new THREE.Clock()`
old instance of clock just get unreachable to your code, and gets deleted after a Garbage Collecction.

But now, if you want to over-use the instance, just use clock.start(), and get rid of your manual modifications.

`function animate()
{
requestAnimationFrame(animate, renderer.domElement);
if(clock.getElapsedTime() * 100 > + 5.3)
{
clock.start();
}
console.log(clock.getElapsedTime() * 100);
}`

**issue should be marked as closed**

**Comment by MaikSoriano** [comment]
@BrianCraig 

`clock.start()` is already in use. Each time I press the button, it call `clock.start()`.

What I wanted was play the animation for 5.3 seconds and then stop the animation until the button was pressed again, then other 5.3 seconds of animation.

`clock.start()` start the count at the last second counted, not start at 0. So to count 5 seconds you have to
1) start at 0 each time you start the clock
or
2) save last second with `lastTime = clock.getElapsedTime();` and then subtract this to the current time.


Anyway I'm using other way without Clock.js to do that, because it didn't count 5.3, each time I pressed start, the animation was played for different time.
