### ISSUE TITLE
what about take program.id into acount for reducing program change times when sorting opaque objects?

### ISSUE THREAD

**Issue by indif** [mrdoob/three.js#9208]
```
function painterSortStable ( a, b ) {

    if ( a.object.renderOrder !== b.object.renderOrder ) {

        return a.object.renderOrder - b.object.renderOrder;

    } else {

        if ( a.material.program && b.material.program ) {

            var aa = a.material.program.id << 16 | a.material.id;
            var bb = b.material.program.id << 16 | b.material.id;

            if ( aa !== bb ) {

                return aa - bb;
            }
        }

        if ( a.material.id !== b.material.id ) {

            return a.material.id - b.material.id;

        }
        else if ( a.z !== b.z ) {

            return a.z - b.z;

        } else {

            return a.id - b.id;

        }

    }

}
```

and this is the sort result:
![image](https://cloud.githubusercontent.com/assets/3214165/16330211/12fd324a-3a1a-11e6-90d0-e5add0f00b5d.png)

**Comment by WestLangley** [comment]
This came up before: https://github.com/mrdoob/three.js/pull/6346.

/ping @benaadams

**Comment by indif** [comment]
I'm sorry but why it hasn't been adopted?

**Comment by mrdumb** [comment]
> I'm sorry but why it hasn't been adopted?

Why do you need to sort (opaque) objects by shader?

**Comment by gero3** [comment]
>> I'm sorry but why it hasn't been adopted?

> Why do you need to sort (opaque) objects by shader?

@mrdumb, This is because of how a GPU works.
The following is a greatly simplified explanation (This is nowhere near a correct representation of the GPU nowadays.) to explain why it is nessecary based on webgl 1.0. 
A GPU has 3 core stages:
- The vertex shader stage
- The rasterisation stage
- The fragment shader stage

### How  to draw something
When trying to draw something you will send info about the shape you want to draw.
To keep things simple we will try to draw  2 triangles based from 6 points.

- The vertex shader stage is mainly used to find the position of the 6 point in the 2D canvas and the depth of a point based on the info given about the shape.
- The rasterisation stage calculates the area used of 3 points to get to the triangle and also the depth of the area based on the 3 points. This area is split in pixels. 
- The fragment shader stage is used to find the color of the pixels on the info given about the shape.

With this you will get a screen of 2 triangles.

### Why sort 

#### Sorting based on depth 

Again we will be using 2 triangles to draw. Let's assume that the 2 triangles have an overlapping area.

Let's start with first by drawing the furthest triangle.
- We draw the first triangle by using all 3 steps.
- Then we draw the second triangle completely since it needs it is closer to the screen.

Let's assume we now draw by using the closest triangle.
- we draw the first triangle  by using all 3 steps.
- Then we start drawing the second triangle by using the vertex shader stage and the rasterisation step. The rasterisation stage takes notice that a certain pixels are behind pixels that are already drawn. So it doesn't execute the fragment shader stage for the pixels in that area. 

This means that when we are drawing from closest to furthest we have to do less calculation on the GPU.

#### Sorting based on program

In webgl the vertex shader stage and fragment shader stage are programmable by programs. When we update these programs we call this a state switch in the GPU. A state switch is something that is slow because it completely reconfigures the GPU. So we try to avoid that also by sorting. 

Keep in mind that these rules only apply to opaque objects and this is a simplified example.

**Comment by mrdumb** [comment]
> @gero3  This is because of how a GPU works.

You seems to be a smart guy, but you miss the main point.
For mobile devices, the best approach is to sort **by state** in this order:
1) viewport
2) framebuffer
3) shaders
4) textures

**Comment by WestLangley** [comment]
>I'm sorry but why it hasn't been adopted?

@indif It appears to have been an oversight, but we will see...

**Comment by mrdoob** [comment]
This commit landed a few days ago...

https://github.com/mrdoob/three.js/commit/570499d5e68aae790cc9bf9653279fd50421ccd1

Isn't it the same?
