### ISSUE TITLE
editor fog broken

### ISSUE THREAD

**Issue by thmasn** [mrdoob/three.js#9227]
##### Description of the problem 

when using the threejs Editor, the fog drop-down does not affect the Scene, until render Settings are changed in the Project tab.

but then the fog Settings still aint saved & are not applied in app.js

##### Three.js version

- [ ] Dev
- [x] r78
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by GGAlanSmithee** [comment]
There seems to be three different parts to this issue;

1. Add fog information to JSON serialization of scene
    * add `scene.toJSON` method

2. Add

**Comment by GGAlanSmithee** [comment]
AFAICT, there seems to be three parts to this issue;

1. Add fog information to JSON serialization of scene
    * add `scene.toJSON` method
    * add `fog.toJSON` method
2. Add fog instantiation to `ObjectLoader.parse` method
3. Add `signal`s for fog toggling fog in the editor

Point 1 and 2 are very straight forward and I think I will have a try at adding that functionality. Part 3 will be a bit more tricky for me to fix since I don't have very good insight in how the editor is functioning, but might try to fix that too.

**Comment by GGAlanSmithee** [comment]
First two points addressed in #9369

If this gets merged, fog will be serialized and parsed, but you will still have to do the settings trick while editing

**Comment by GGAlanSmithee** [comment]
#9370 should fix updating the editor when changing fog type

**Comment by GGAlanSmithee** [comment]
I suggest that this issue is closed since #9369 was merged and that #9384 superseeds remaining points.

**Comment by mrdoob** [comment]
Not yet. The fog parameters don't get saved/loaded in the editor yet. Working on it!
