### ISSUE TITLE
Raw formatted NRRD format won't read.

### ISSUE THREAD

**Issue by marcelvanherk** [mrdoob/three.js#9316]
##### Description of the problem

Raw formatted NRRD format won't read.

```
NRRD0004
'# Complete NRRD file format specification at:
'# http://teem.sourceforge.net/nrrd/format.html
type: short
dimension: 3
space: left-posterior-superior
sizes: 512 512 33
space directions: (1.171875,0.000000,0.000000) (0.000000,1.171875,0.000000) (0.000000,0.000000,-10.000000)
kinds: domain domain domain
endian: little
encoding: raw
space origin: (-300.000000,-230.000000,1415.500000)

XXXXX binary data starts on this line XXXXX 
```

file size (17.301.897) bytes. Gives error:

```
SCRIPT5084: Invalid offset/length when creating typed array
NRRDLoader.js (309,3)
```

Apparently the header is incorrectly stripped from the _data passed there. The file reads OK in Seg3D2, but not in Slice Drop.
##### Three.js version
- [X] Dev
- [ ] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [X] Firefox
- [X] Internet Explorer
##### OS
- [ ] All of them
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

Non-hardware specific

**Comment by marcelvanherk** [comment]
Did that by opening an issue in his atlasviewer. thanks Marcel

**Comment by marcelvanherk** [comment]
Hi,

stity is not responding.

a temporary fix is to skip: _data = _data.buffer; for raw data.

and then for raw data parse the data as follows:

volume.data = new headerObject.__array( _data );
		
		for ( i = 0; i < headerObject.sizes[ 0 ]*headerObject.sizes[ 1 ]*headerObject.sizes[ 2 ]; ++ i ) {

			volume.data[i] = _data[i*2]+256*_data[i*2+1];

		}

Marcel

**Comment by stity** [comment]
Sorry guys,
I will not be available this week.
I will take a look in 8 to 10 days.
Thanks
Le 16 juil. 2016 3:38 PM, "marcelvanherk" <notifications@github.com> a
écrit :

Hi,

stity is not responding.

a temporary fix is to skip: _data = _data.buffer; for raw data.

and then for raw data parse the data as follows:

volume.data = new headerObject.__array( _data );

    for ( i = 0; i < headerObject.sizes[ 0 ]*headerObject.sizes[ 1
]*headerObject.sizes[ 2 ]; ++ i ) {

        volume.data[i] = _data[i*2]+256*_data[i*2+1];

    }

Marcel

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mrdoob/three.js/issues/9316#issuecomment-233130776>,
or mute
the thread

**Comment by NicolasRannou** [comment]
Can you please share the data?

Does it work with AMI?
https://fnndsc.github.io/ami/#viewers_dicom2D

**Comment by marcelvanherk** [comment]
[test.zip](https://github.com/mrdoob/three.js/files/379540/test.zip)
Hi,

the data is attached (7z and then zipped), and it works fine with AMI. What reader is used there?

Marcel

**Comment by NicolasRannou** [comment]
It is using https://github.com/scijs/nrrd-js.

The approach with AMI is very different that the one currently used in the ThreeJS NRRD loader though.
AMI uses custom shaders to do all the processing on the GPU whereas afaik all other available tools (including ThreeJS NRRD Loader) do all the work (slicing, window level, LUT, etc.) in Javascript.

There are Pros/Cons in both approaches and you have to choose the tool that bet fits your needs.

Anyway, it would be great to have the ThreeJS NRRD loader support this dataset too.

Best,
Nicolas

**Comment by marcelvanherk** [comment]
Hi,

this was a serious bug report - now 4 months ago, is there any chance of getting this fixed?

Marcel

**Comment by stity** [comment]
@mrdoob I made a PR for this issue.

@marcelvanherk Sorry for the delay, I am still a final year student who tries to balance his time between school projects and other projects. Lately I have been kind of overwhelmed and have had a hard time trying to find free time to take care of this issue. 
Anyway on the technical side, when I wrote this loader I had only gzip encoded NRRD files and didn't test it on raw files. As you mentioned, the issue was with the line _data = _data.buffer because it would get the original buffer with the header and therefore produce a length error. I fixed it by copying the data in a new array. I managed to make the official example work with your nrrd file as you can see in this screenshot.
![issue screenshot](https://cloud.githubusercontent.com/assets/11036145/20838106/65541ba6-b8a7-11e6-9943-666f243172ea.png)
I hope that you're happy with the result and but keep in mind that most of the contributors do this on their free time so please be less demanding or maybe consider contributing on future issues. :+1: 
That being said, can I ask you what is the project you're working on with threejs and medical data ?
Let me know, if you encounter any other issues with this loader, I will happily take a look at it although it might take a while until I post a solution
Thanks

**Comment by marcelvanherk** [comment]
Hi mrdoob,

thanks for this fix. I create and maintain conquest DICOM server and I was looking at a way to tie a three.js 3D data viewer into its web interface. The js issue was a bit over my head although I generally try to help out. I  coded the nrrd_writer on the conquest side round the time the bug was posted, so I was eager to get on with it.  Now the issue is fixes I will revisit the possible integration.

regards,

Marcel
