### ISSUE TITLE
Why does `Vector3#divideScalar(0)` set the vector to origin?

### ISSUE THREAD

**Issue by leewz** [mrdoob/three.js#9387]
The [docs](http://threejs.org/docs/#Reference/Math/Vector3.divideScalar) for Vector3 say

> Divides this vector by scalar s.
> Set vector to ( 0, 0, 0 ) if s == 0.

As an element of a vector space, dividing by 0 is invalid, and should throw an exception.

As a value array of IEEE floats, dividing by 0 should set each component to Infinity, -Infinity, or NaN, based on their original values.

What is the model being used here? The "vector space" model should make debugging easier, and the "array of floats" model might be useful for someone, but simply resetting the vector doesn't seem very useful to me, as it neither shows an error nor gives a "sane" result.

**Comment by WestLangley** [comment]
Yeah, the history of this issue can be found beginning here: https://github.com/mrdoob/three.js/pull/7326#issuecomment-148080916.

I do not think three.js checks for NaN's or +/-infintiy elsewhere in the libary, so I am thinking the "is finite" check can be removed here, too. But, I will defer to @bhouston on this one.

**Comment by bhouston** [comment]
The issue is you need to be able to not propagate NaNs or +/-INFs.  The choices you have is to either throw an error when this occurs or set the result to a default value.  In Matrix4.getInverse we provide an option to issue an error or not when the determinant is 0, and if one chooses to not have an error, we set the matrix to identity.  Here in Vector3 we just take the approach of setting a default value and hiding the error.

Generally the approach we have taken is the most common approach in 3D graphics libraries.  I could see it possible to pass in an option to throw an error when there is a divide by zero.  But I would highly highly recommend against allow for NaNs/+-Infs be created -- that will lead to really hard to debug code and one NaN in a render will usually cause a lot of strange malfuntions in the shaders, they are not designed to handle NaN/Inf - you will get dark or bright spots that look like bugs.

**Comment by leewz** [comment]
**Historical note**: The check was removed per the discussion in #10849
