### ISSUE TITLE
Include examples/js into the new Three.JS module system and rely on tree shaking

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#9403]
##### Description of the problem

It would be great if we could move a lot of the Three.JS example/js source code into the main /src directory tree and then rely upon the module system/tree shaking to remove the code that is not needed.

This would really make it easier to add code to three.js and also make everyone's builds small at the same time. :)  Basically better in every way.

I guess when one uses ThreeJS in another project one needs to rely upon a global rollup rather than a ThreeJS specific rollup.  I guess that can be hard to support.

/ping @Rich-Harris 
##### Three.js version
- [x] Dev
- [ ] r79
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by crabmusket** [comment]
How do you imagine the tree-shaking working in this case? I've been trying to get it working with just the core of Three.js but can't manage to get any benefit from it. See [this question](http://stackoverflow.com/questions/41538767/how-do-i-tree-shake-three-js-using-webpack-or-rollup), especially the comments after the first answer. I also tried importing Three.js from `src` directly. After I got a transformer for the `glsl` files, I still observed no change in the bundle size either.

If the examples are each completely separate source trees (i.e. they aren't imported by the main library) then I guess this would be feasible - but at that point it's not really tree shaking, is it?

**Comment by mutsys** [comment]
@crabmusket I've been looking at this as well, wondering why the simplest, most minimal import of Three.js results in monstrously huge bundles containing essentially every single module. I read through the discussion you pointed to above, performed numerous experiments and went so far as to generate graphs of the Three.js dependency tree to try and get to the bottom of this. Here are a few takeaways from the experience:

Importing from `src` is the right way to go. This is your best bet if you are counting on static analysis tools to detect and excise any unused code.

UglifyJS couldn't do much here since it does not yet understand es6 modules.

[Babili](https://github.com/babel/babili) **does** understand es6 modules and is capable of finding unused code that can be purged.

A multi-stage build/bundling process via Webpack, transpiling from TypeScript to es6, performing code elimination via Babili, transpiling to es5 via Babel and finally minifying via UglifyJS turned out to be the most effective strategy and was the only means of making a dent in the final size of the bundle produced by Webpack.

However, try as I might, after days of trials and experimentation, I can only get the size of the Three.js derived code down to 529.96 KB and when I dig in and take a look at which modules have been included, I still see tons of code that I am not using and should not end up in the final bundle.

I haven't done enough detailed analysis to be absolutely sure just why all of the extra modules are getting pulled in, but I have some intuition here. I think this may be caused by the "convenience" exports that can be found in `src/Three.js`. Every module is brought up to the "surface" of `Three.js` in an effort to make it easier for developers to import the modules they want to use without a bunch of hunting around in the docs. Unfortunately, this seems to have the undesirable side-effect of forcibly importing all of `Three.js` my default into your project whether you want it or not. This wouldn't be too terrible if the uneccessary code could be removed by the usual "tree-shaking" process down the line, but it never does get removed no matter how hard you try. I suspect this is becuase this is becuase all of these pre-emptively imported all depend on one another and there is enough complexity in these dependency relationships to prevent the tree-shaking process from correctly identifying and excising unused code. 

I can't state this with certainly yet, its just a hunch based on what I've observed while playing around with this for a few days. I am hoping to test this theory out soon.

**Comment by looeee** [comment]
> Babili does understand es6 modules and is capable of finding unused code that can be purged.

Maybe I'm missing something but I don't see anywhere on the Babili page that says it can understand ES6 modules, and their [online test](http://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=react%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=import%20*%20as%20foo%20from%20'.%2Ffdfd%2Fja.js'%3B%20%0A%0A%2F%2F%20Example%20ES2015%20Code%0Aclass%20Mangler%20%7B%0A%20%20constructor(program)%20%7B%0A%20%20%20%20this.program%20%3D%20program%3B%0A%20%20%7D%0A%7D%0Anew%20Mangler()%3B%20%2F%2F%20without%20this%20it%20would%20just%20output%20nothing%20since%20Mangler%20isn't%20used%0A%0Aexports%20%3D%20%20Mangler%20) doesn't support multiple files (compare it to the [rollup repl](https://rollupjs.org/repl)). 

Have you tested on a simple setup to see if it tree shakes unused modules?

**Comment by GGAlanSmithee** [comment]
@looeee I think you are looking for https://github.com/babel/babili, not https://github.com/babel/babel

**Comment by mutsys** [comment]
Take a look here to see some more details about what I am pursuing: [babili-webpack-pugin](https://github.com/webpack-contrib/babili-webpack-plugin/issues/8). The authors discuss a multi-stage transpile - bundle - minify process that I've been trying out. I do have a project where I have implemented this and I can say that I do get a smaller bundle using this technique with Babili as they describe than without it.

**Comment by crabmusket** [comment]
@mutsys thanks for the in-depth analysis! At this point I am honestly just planning on forking Three and hand-removing bits I don't want. But if it's actually to do with the internal module structure of Three, it seems like it might be worth experimenting with says of improving that. The files in `dist/` should obviously remain kitchen-sinkified, but if we can improve the way importing from `src/` splits modules it would be a big win.

If I get time I will look into it, but as this is for work it's hard to justify making more effort than to fork, prune and move on.

**Comment by mrdoob** [comment]
> I think this may be caused by the "convenience" exports that can be found in `src/Three.js`.

Why are you importing that file if you are building your app using modules directly? That file is only for producing the `THREE.*` which you shouldn't use when building with modules.

**Comment by mutsys** [comment]
@crabmusket I started working on a privater fork of `Three.js` myself the other night to see if I could make any meaningful reduction in the final bundle size by just getting rid of the convenience exports and directly importing any necessary modules directly (as `Three.js` itself does internally). Since I'm also using TypeScript, this requires me to also fork and tweak up `@types/three` as well, making this an excellent exercise in really grokking the structure of `Three.js` itself. If I am able to gain any additional insight I will be sure to post back here for you.

@mrdoob Flattered that my machinations caught your attention. Here are a few data points that illustrate why I'm spending my time on this.

Importing from `src/Three.js`:

The contributions from `Three.js` total up to:

component|size
-----------|------
stat size|729.77 KB
parsed size|529.96 KB
gzipped size|127.86 KB

and using `webpack-bundle-analyzer` to visualize which how much each module contributes to the final bundle, I get a very clear picture of what got pulled in from `Three.js` and I can see that there are many modules that I am not importing and should not be present at the end.

![screen shot 2017-05-27 at 9 00 49 pm](https://cloud.githubusercontent.com/assets/8465576/26526014/aecff5ae-431f-11e7-83fb-2dba17777dac.png)

Importing from `build/three.module.js`

The contributions from `Three.js` total up to:

component|size
-----------|------
stat size|665.94 KB
parsed size|477.72 KB
gzipped size|120.07 KB

which is a bit smaller, but still seems to be unjustifiably large, so I would like to unxderstand just which of the `Three.js` modules became part of my bundle. Unfortunately, the analysis of the bundle looks like this:

![screen shot 2017-05-27 at 9 18 30 pm](https://cloud.githubusercontent.com/assets/8465576/26526069/18fa8910-4322-11e7-832b-a05c701208d4.png)

`three.module.js` is totally opaque and does not lend itself to further analysis.

Finally, importing from `build/three.js`

The contributions from `Three.js` total up to:

component|size
-----------|------
stat size|672.68 KB
parsed size|467.73 KB
gzipped size|119.35 KB

which results in the smallest output (parsed size is what actually ends up in my webpack bundle), but one again, seems to be way larger that what I would expect to see and once again, analysis of the bundle results in:

![screen shot 2017-05-27 at 9 25 34 pm](https://cloud.githubusercontent.com/assets/8465576/26526117/92c36090-4323-11e7-83f5-53dda7dc18c6.png)

`three.js` is entirely opaque and thwarts any further discovery.

So although it does not result in the smallest bundle, importing from `src/Three.js` is the only method that allows for further analysis and provides me with any feedback on experiments.

Pretty much every other library I use provides me with view similar to what I see when I import from `src/Three.js`, providing me with the insight necessary to tune my use of the provided modules and make meaningful reductions in the size of my final bundle. The only two libraries that seem to be unusual or problematic in this respect are `THREE` and `PIXI`.

That being said, since I have immensely enjoyed learning and using `THREE` and have benefitted greatly from its existance, I am hoping that by digging into this riddle I might discover something that could lead to further improvement of an excellent library and contribute something back in return. Of course, if you are able to provide me with any insight that might help me out in my investigation, I would be grateful.

**Comment by mutsys** [comment]
@crabmusket @mrdoob OK, I spent a few hours tonight doing a deep dive into this. I was able to get a significant reduction in the size of my bundle, shaving a whole heck of a lot off of the contribution from `Three.js`. Here is where I am at now...

Importing from `src`, ignoring `src/Three.js` by declaring imports directly to the necessary modules (eg - `import { Object3D } from "three/src/core/Object3D";`) and refactoring the TypeScript definition files accordingly:

component|size
-----------|----
stat size|435.11 KB
parsed size|323.07 KB
gzipped size|78.47 KB

![screen shot 2017-05-28 at 4 44 20 am](https://cloud.githubusercontent.com/assets/8465576/26528478/b390089e-4361-11e7-8f40-3e51b4b5b6b0.png)

It appears my intuition was correct and the "convenience" exports from `src/Three.js` do in fact interfere with tree-shaking and dead code elimination. I did not have to make any modifications to any of the `Three.js` source, all I did was change the way in which I imported modules in my own code.

I'm not going to claim total victory just yet until I go over this again in detail and see if I catch any mistakes in here. It is very late at night now where I am and I'm super tired so I'm not going to get too excited just yet until I get some rest and give it another once over.

That being said, I do believe that there are additional opportuinities to improve upon this further. As I was refactoring the TypeScript definition files, it was apparent that there a fair number of circular dependencies throughout `Three.js`, a good number of dependencies that are declared backwards/in the wrong direction and some careless coding here and there that all serves to prevent identification and removal of otherwise unnecessary code during static analysis and minification.

Some examples:

Example 1)

`cameras/Camera -> math/Vector3`
and
`math/Vector3 -> cameras/Camera`

Two strikes here:

- circular dependency
- having math/Vector3 depend on cameras/Camera is totally backwards

Example 2)

`renderers/WebGLRenderer -> cameras/PerspectiveCamera`
and
`renderers/WebGLRenderer -> cameras/OrthographicCamera`

not necessarily bad by itself, but take a look at what happens in the `render` method:

```javascript
if ( background && background.isCubeTexture ) {

    if ( backgroundBoxCamera === undefined ) {

        backgroundBoxCamera = new PerspectiveCamera();

        backgroundBoxMesh = new Mesh(
            new BoxBufferGeometry( 5, 5, 5 ),
            new ShaderMaterial( {
                uniforms: ShaderLib.cube.uniforms,
                vertexShader: ShaderLib.cube.vertexShader,
                fragmentShader: ShaderLib.cube.fragmentShader,
                side: BackSide,
                depthTest: false,
                depthWrite: false,
                fog: false
            } )
        );

    }

    backgroundBoxCamera.projectionMatrix.copy( camera.projectionMatrix );

    backgroundBoxCamera.matrixWorld.extractRotation( camera.matrixWorld );
    backgroundBoxCamera.matrixWorldInverse.getInverse( backgroundBoxCamera.matrixWorld );


    backgroundBoxMesh.material.uniforms[ "tCube" ].value = background;
    backgroundBoxMesh.modelViewMatrix.multiplyMatrices( backgroundBoxCamera.matrixWorldInverse, backgroundBoxMesh.matrixWorld );

    objects.update( backgroundBoxMesh );

    _this.renderBufferDirect( backgroundBoxCamera, null, backgroundBoxMesh.geometry, backgroundBoxMesh.material, backgroundBoxMesh, null );

} else if ( background && background.isTexture ) {

    if ( backgroundPlaneCamera === undefined ) {

        backgroundPlaneCamera = new OrthographicCamera( - 1, 1, 1, - 1, 0, 1 );

        backgroundPlaneMesh = new Mesh(
            new PlaneBufferGeometry( 2, 2 ),
            new MeshBasicMaterial( { depthTest: false, depthWrite: false, fog: false } )
        );

    }

    backgroundPlaneMesh.material.map = background;

    objects.update( backgroundPlaneMesh );

    _this.renderBufferDirect( backgroundPlaneCamera, null, backgroundPlaneMesh.geometry, backgroundPlaneMesh.material, backgroundPlaneMesh, null );

}
```

The choice of camera here (and a few other modules as well) can only happen dynamically at runtime, so even if I never use one of these modules in my own code, both will always be included in the final bundle regardless. Sure enough, I am only only using `PerspectiveCamera` in my own code but I can see that my bundle contains `OrthographicCamera` anyway. There are quite a number of places in `Three.js` where similar "forced import" occurs. This example only adds about 2KB to the final bundle, but it all adds up. The area where something like this seems to be doing the most harm is in `renderers/shaders`. I don't know enough to really say whether or not everything in there is always needed all of the time, but I'm guessing that it isn't and some refactoring effort here might have some significant impact. There is some 100 KB or so of code there that look ripe for analysis.

**Comment by crabmusket** [comment]
@mrdoob in retrospect what you say makes things completely obvious. Maybe for other confused souls like myself it would be good to have a section in the readme or something? Just prompting people to import modules directly if they only need a subset of features. And reminding them they'll probably need a loader for .glsl files (e.g. [webpack-glsl-loader](https://www.npmjs.com/package/webpack-glsl-loader)).

@mutsys awesome work! Great to see those results and hear that there might be opportunities to improve further. I'll keep following this thread and will report back on the results of importing directly from `src` modules instead of `Three.js`.

My method will be basically to maintain my own local `three.js` file. I experimented with this before, but I was still importing everything from `Three.js` and relying on tree-shaking. Turns out I was putting too much faith in the system haha.

**Comment by tschoartschi** [comment]
Very interesting discussion! I'll keep an eye on it since I also tried to `tree shake` Three.js and I was also not satisfied with the results. Maybe there will be a good solution someday soon.

**Comment by tschoartschi** [comment]
@mutsys I also tried something very similar to your approach. I used `rollup` since we already have it in our build pipeline. Do you think I can get better results with `webpack`. I created a repo so if anyone is interested she or he can check it out, https://github.com/tschoartschi/tree-shake-threejs

In this example there is only a rotating cube and I think the file size is still quite big. Maybe there could be better results? Would be great to get some feedback

**Comment by mutsys** [comment]
@tschoartschi @crabmusket Wow, it has been a while since I was tinkering around with this and haven't looked at it lately but I do still have the repo where I was working on this. As you may have gathered from my previous comments, it took a significant amount of work in my own fork to get those results and if there is some way that the effort can further our shared goal I would happy to share it with everyone for analysis and feedback.

@crabmusket Keep in mind that the analysis was performed many months ago and more recent releases may have resolved that circular dependency I indentified between `math/Vector3` and `cameras/Camera`.

**Comment by zbigg** [comment]
Small report with my findings.
Use case: bundling three.js with other app.
Environment: webpack + typescript.

This always imports whole three.js (minimal bundle size around 430k, simetimes 534k)
```
import { Vector3 } from 'three';
```

```
import { Vector3 } from 'three/src/math/Vector3.js';
```
works in JS files and, yes tree-shaking workd.
However, TypeScript build fails because '@types/three' catch only 'three' module, not files hidden in 'three/src':
```
TS7016: Could not find a declaration file for module 'three/src/math/Vector3.js'. (...)
```
My workaround:
```
// foo.ts
/// <reference path="three.src.d.ts"/>
import { Vector3 } from 'three/src/math/Vector3.js';
..
// three.src.d.ts
declare module 'three/src/math/Vector3.js' {
    export { Vector3 } from 'three';
}
```
So, i basically declare all modules from 'src' with re-exports from '@types/three'.
webpack is happy because it doesn't have to deal with 'export * ...' in `src/Three.js` and `ts-loader` is happy because it know what hides behind `three/src/*`.

Maybe not best solution but i can handcraft my custom `three.src.d.ts` for each project.

Bundle summary with workaround (TS version):
```
    [0] ./foo.ts + 4 modules 46.3 KiB {0} [built]
        | ./foo.ts 197 bytes [built]
        | ./node_modules/three/src/math/Vector3.js 12 KiB [built]
        | ./node_modules/three/src/math/Math.js 3.01 KiB [built]
        | ./node_modules/three/src/math/Matrix4.js 20.2 KiB [built]
        | ./node_modules/three/src/math/Quaternion.js 11 KiB [built]
```

**Comment by bhouston** [comment]
I'm going to explore solving this issue via https://github.com/systemjs/systemjs

**Comment by donmccurdy** [comment]
Related: https://github.com/mrdoob/three.js/pull/14803

I'm strongly in favor of converting the packages under `example/js/*` into ES modules and (if needed for backward-compatibility) automatically building UMD modules from those. That's high priority IMO.

But how would SystemJS contribute? It seems useful for end-users' applications, or keeping the example demos functional on older browsers, but I'm not sure how it relates to distribution of the threejs library as a download or npm module.

The idea of moving a lot of `examples/js/*` into the `src/*` tree is less of a slam dunk I think. If it's possible to defer that conversation until the ES module change is settled, let's go that route.

**Comment by mrdoob** [comment]
Some progress... #15518

**Comment by PerspectivesLab** [comment]
this new /jsm/ files works great for importing the examples modules,
meanwhile has someone been successful to tree shake threejs with this, out of the box ( import {...} from 'three' ), and not importing source files...
im using webpack4 enabled all options for tree shaking, but the size of threejs doesnt move, still around 700 k meanning all library is included... :(

**Comment by mrdoob** [comment]
I think this can now be closed.

**Comment by mrdoob** [comment]
@PerspectivesLab Better create a thread in the [forum](https://discourse.threejs.org/) to discuss options.
