### ISSUE TITLE
BufferGeometry.prototype.merge not working

### ISSUE THREAD

**Issue by golopot** [mrdoob/three.js#9468]
```
a = new THREE.PlaneBufferGeometry( 1, 1, 2 )
b = new THREE.PlaneBufferGeometry( 1, 1, 2 )
console.log( a.attributes.position.array.length )
a.merge( b )
console.log( a.attributes.position.array.length )

Output:
18
18 (should be 36)
```

r79

**Comment by WestLangley** [comment]
Yes. The method does not support _indexed_ buffer geometries. Also buffer geometries can't be resized. Have a look at the source code so you understand what the method's limitations are.

Quite frankly, I can see a compelling argument for removing the method altogether -- or perhaps substituting a utility like:

    THREE.BufferGeometryUtils.mergeGeometries( ... )

which would merge multiple geometries at once, rather than incrementally. But even that method would have significant limitations.

**Comment by q4w56** [comment]
For my app I wrote a implementation that allocate a new `Float32Array` with needed length, then copy this and that, it works fine. 

I think the method should have the same behavior as the `Geometry.merge`.

What is the purpose of the second argument `offset` in `this.merge( ..., offset)` ?  I don't have a clue.

**Comment by pailhead** [comment]
Does merge work on regular Geometry in r79?

**Comment by Wilt** [comment]
Related: https://github.com/mrdoob/three.js/pull/8162
