### ISSUE TITLE
Blender exporter: "Armature is not a valid mesh object."

### ISSUE THREAD

**Issue by SalamiMitPizza** [mrdoob/three.js#9492]
##### Description of the problem 

The export of a mesh including an armature does not seem to work. The exporter works when exporting just the mesh. As soon as an Armature is added or selected, the export fails. It says "Armature is not a valid mesh object." I get this error in Blender 2.77 on Mac and Linux Mint. 

I have followed this [tutorial.](https://www.youtube.com/watch?v=eEqB-eKcv7k&index=15&list=PLOGomoq5sDLutXOHLlESKG2j9CCnCwVqg)

These are the export settings: 
![settings](https://cloud.githubusercontent.com/assets/12084165/17589169/703b0fb6-5fd3-11e6-8ed0-78104887774b.png)

[Here](https://www.dropbox.com/sh/j7mfyfk51msldvd/AADJYzsYGhQstxBT3CJ5Gopda?dl=0) is the blender file.

##### Three.js version

- [ ] Dev
- [x] r79

**Comment by etienne-gauvin** [comment]
Is the problem resolved ? If yes, could you tell what is your solution ? I have the same issue.

**Comment by jorisvanr** [comment]
Did you manage to figure out what the problem was? I get the same error when exporting a spline / path!

**Comment by SalamiMitPizza** [comment]
Unfortunately not, I gave up on it.

**Comment by Jeremboo** [comment]
I also had the same problem.
It comes to a selected element in your scene when you try to exports.
Unselect all (press A twice) to export correctly.

Hope to have helped

**Comment by sojoonsup** [comment]
any luck yet?

**Comment by jorisvanr** [comment]
Well, it basically says what the problem is: the armature is not a valid mesh object. This kind of makes sense because an armature is not a mesh. I believe we exported a rigged object by removing the armature in the "modifier" tab and exporting the mesh and the armature by selecting them both and exporting them (or as @Jeremboo mentioned, not select anything). Of course select the Geometry you need in the exporter.  

My problem was exporting a spline from Blender to JSON. This gave the same error because, well, a spline is not a mesh. Some python magic did the trick. I'm not a developer myself so I cant explain how kit was done. But with a little bit of Python knowledge, this shouldn't be to hard.

**Comment by wywzxxz** [comment]
>Because you had the armature selected. In the current state of the exporter you need to explicitly select the mesh. I am aware that the old exporter this wasn't a requirement but it isn't a high priority item until we get all bugs and kinks worked out
>--- from: [stackoverflow](http://stackoverflow.com/questions/28761520/blender-exporter-v70-to-json-three-js-skinning-animations)

Once you did this, the error will vanish and json files will be generated. Also you may want to set the exporter's option "type" to Geometry (rather than buffergeometry) and reset the pose (ALT R ALT G ALT S ), or your model could be really wired.

**Comment by leorich** [comment]
These comments helped me with the issue.  Additionally, the last thing you selected (before dis-selecting all with 'a' twice) is shown with white text in the 'outliner,' if the **last thing you selected was not a mesh**, you will run into this error.

**Comment by Sandstedt** [comment]
Had the same problem, solved it by selecting a mesh object in the outliner and then export.
