### ISSUE TITLE
Fix inconsistency on loaders parse method

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#9590]
Hi

Some of the loaders require a json object for parsing other accept a string.

Since pretty much every loader was the same contructor and load method code loaders could be created on top of a base class that could be also used as an implementation interface reference, this would also allow some space saving.

**Comment by mrdoob** [comment]
> Some of the loaders require a json object for parsing other accept a string.

Could you list them?

**Comment by tentone** [comment]
As an example FontLoader and OBJLoader

FontLoader parse method
```
	parse: function ( json ) {

		return new Font( json );
```

OBJLoader parser method
```
	parse: function ( text ) {

		console.time( 'OBJLoader' );

		var state = this._createParserState();
```

Now the ideal would be for the parse method to always receive text data since most of the Loaders actually load text files. But still there are some cases where binary data is needed.

**Comment by jonnenauha** [comment]
My 2 cents. If there was some asset system in three.js where each loader would register themselves, it might make sense to have a common interface for each loader. This could enable something like this.

```
var assets = [ "/assets/mesh.json", "/assets/another.obj", "/assets/textures/my.dds" ];
THREE.Assets.load(assets, callback);
```

This would make is easier to implement the internals of "THREE.Asset" system. And possibly visible also to the end users if they use particular loaders manually, eg. `THREE.Asset.loader("obj").load(data);`.

I have understood from @mrdoob that such asset system is out of scope for the three.js project. I kind of tend to agree, it would be another complex thing to maintain and keep running, instead of focusing on individual loaders.

Even if such asset system would not be created some kind of common interface for loaders might be beneficial. It could provide utilities for processing text/binary per line and maybe some string/math utils. I'm not sure who knows all the existing loaders well enough to define some commonality between them :)

**Comment by tentone** [comment]
Im actually implementing resource objects for threejs  (im already using them inside my project nunu studio), but i havent created a PR yet because there are still a bunch of things that i need to solve (stuff like gif's not updating when not on screen etc...)

I think for a project like threejs asset management is kind of over engineering, and thats what i also think about the current loaders system. I think that loaders classes should be reserved for external file loading (obj. json. dae. etc), i think that stuff like textures images etc... (every thing that can be serialized to JSON format) shouldn't need a loader for those we should use instead toJSON and fromJSON methods this would allow to shave off from threejs probably 50kb+ moving the object loader to something like

var constructors = [];
contructors["Object3D"] = Object3D;
constructors["Sprite"] = Sprite;

(....)

parseImages(data)
{
var images = [];
var length = data.length;
for(var i = 0; i < length; i++)
{
images.push(Image.fromJSON(data[i]);
}
return images;
}

(...)

parseObject(data)
{
var Constructor = constructor[data.type];

return Constructor.fromJSON(data);
}

For the remaining loaders (json, obj, mtl, dae etc) we should use a base class since most of them repeat the constructor code and use that to define a uniform inteface for all of them.
