### ISSUE TITLE
CylinderGeometry regression starting with r75

### ISSUE THREAD

**Issue by 50Wliu** [mrdoob/three.js#9663]
##### Description of the problem 

Starting with `r75`, `CylinderGeometry` seems to disrespect the `color` option when the `radiusBottom` value is very close to, but not exactly, 0.  Here's an example:
```js
const geometry = new THREE.CylinderGeometry(0.25, 2.4884797782360525e-24, 0.5, 100);
const plane = new THREE.Mesh(geometry, new THREE.MeshPhongMaterial({color: 0xFFFF00}));
geometry.rotateZ(Math.PI / 2).translate(-0.5 + 0.5 / 2, 0, 0);
geometry.dispose();

const group = new THREE.Object3D();
group.add(plane);
scene.add(group);
```
`radiusTop` does not appear to exhibit this bug.  The "top" is still colored though.

JSFiddles:
https://jsfiddle.net/f0ah1wua/1/ (r75, broken)
https://jsfiddle.net/f0ah1wua/2/ (r74, correct)

##### Three.js version

- [ ] Dev - Did not check.
- [x] r80
- [x] r79
- [x] r75
- [ ] r74

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox - Did not check.
- [x] Internet Explorer
- [x] Microsoft Edge

##### OS

- [ ] All of them
- [x] Windows 10 x64
- [ ] Linux - Do not currently have access to.
- [ ] Android - Did not check.
- [ ] IOS - Do not currently have access to.

##### Hardware Requirements (graphics card, VR Device, ...)

None that I'm aware of.

/cc @Mugen87: `git bisect` pointed towards #8239 as the culprit.

Sorry for the very late bug report but I've only recently had time to investigate this.

**Comment by WestLangley** [comment]
Well, for one thing, it appears the vertex normals are incorrect.

https://jsfiddle.net/f0ah1wua/3/  r.75 - broken
https://jsfiddle.net/f0ah1wua/4/  r.74

**Comment by mrdoob** [comment]
> /cc @Mugen87: `git bisect` pointed towards #8239 as the culprit.

@Mugen87 Yup. I think this bug came with `CylinderBufferGeometry`.

**Comment by Mugen87** [comment]
Oh dear! The problem is this line of code:

```javascript
var radius = v * ( radiusBottom - radiusTop ) + radiusTop;
```

If  `radiusBottom` is very close to zero, the calculation `radiusBottom - radiusTop` provides an incorrect result e.g.

`2.4884797782360525e-24 - 0.25 = - 0.25`

The subsequent code can't handle this special case yet. 

The mentioned line of code for `radius` calculation also exists in `CylinderGeometry` (see [here](https://github.com/Mugen87/three.js/blob/b1884c623ae00f6c0d0f319ea3d84d4cd14156f8/src/extras/geometries/CylinderGeometry.js#L43)). We didn't notice this problem because the normals were generated with `.computeFaceNormals`.

I'm not sure about the correct way to calculate the radius under these circumstances. Maybe we could clamp the radius via `Number.EPSILON`?

see https://jsfiddle.net/f0ah1wua/6/

**Comment by WestLangley** [comment]
>Maybe we could clamp the radius via Number.EPSILON?

That technique does not work when the geometry is scaled up by a factor of 100.

**Comment by Mugen87** [comment]
The PR does not clamp the radius but still uses `Number.EPSILON` to detect the mentioned special case.
