### ISSUE TITLE
Path to object is not resolved by MTLLoader when models are not in same directory

### ISSUE THREAD

**Issue by fleduc** [mrdoob/three.js#9674]
##### Description of the problem

In my Web application, you will find this directory tree:

```
root/
   models/ (with all the obj and texture files)
   mob/ (the application, php files)
      js /(with all tree, js files)
```

In my application, when I try to open an object that is found in the models directory Chrome return:

```
three.js:24569 GET http://localhost:8080/models/usracc_1/5/model_mesh.obj.mtl 404 (Not Found)
```

But when I place the models directory under the mob directory (in the same directory as the php file that is calling the object, its working...

In my code you will find

```
  var mtlLoader = new THREE.MTLLoader();
   mtlLoader.setBaseUrl( url );
   mtlLoader.setPath( url );
   mtlLoader.load( 'model_mesh.obj.mtl', function( materials ) {
```

Since the models are found in the models directory which is located in mob's parent directory, the value I place in url is "../models/usr1/5/", but is seems that the "../" is erased somewhere in the process, leaving url to be "models/usr1/5/" instead of "root/models/usr1/5/" .

Can anybody point me in the right direction to resolve this problem?

Thanks
##### Three.js version
- [ ] Dev
- [x ] r80
- [ ] ...
##### Browser
- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [] All of them
- [x ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by fleduc** [comment]
What?

**Comment by mrdoob** [comment]
@jonnenauha is dealing with that loader. I'm just paging him.

**Comment by fleduc** [comment]
Any news?

**Comment by jonnenauha** [comment]
Sorry, I forgot to respond to this earlier. Hate that I cant make messages sticky in github inbox :I

404 looks like the path is not hosted? Are you saying `http://localhost:8080/models/usracc_1/5/model_mesh.obj.mtl` is the **right url** but somehow three.js makes it 404? Does that URL work if you paste it to a normal browser tab, if not, three.js cant fetch the asset either.

If the path is hosted then could you give me what the value of `url` is in your example. What is the URL in the browser where you are running three.js.

    var mtlLoader = new THREE.MTLLoader();
    mtlLoader.setBaseUrl( url );
    mtlLoader.setPath( url );
    mtlLoader.load( 'model_mesh.obj.mtl', ....

`setBaseURL` is deprecated but still works. I renamed it to `setTexturePath` to make it clear what it is doing. https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/MTLLoader.js#L42-L76 

* `setPath` if set prepended to mtl (load) and texture (internals) refs
* `setTexturePath` prepended to textures only if set, otherwise uses `setPath`
 * This enables you to have .obj and .textures in totally different folders

Neither should do any trimming for `..` in the path/texture path.
