### ISSUE TITLE
SSAO radius working incorrectly with Orthographic Camera

### ISSUE THREAD

**Issue by ctechdevelopment** [mrdoob/three.js#9765]
##### Description of the problem

SSAO radius appears to be in screen space when using orthographic camera and world space when using perspective camera.

After a quick look, perhaps the radius calculation in:

`float calcAO( float depth, float dw, float dh )`

needs to somehow take into account the orthographic zoom value. 

https://github.com/mrdoob/three.js/blob/dev/examples/js/shaders/SSAOShader.js
##### Three.js version
- [ ] Dev
- [x ] r81
- [x] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by ctechdevelopment** [comment]
I can have a look at this - any suggestions on how you would like this done?

**Comment by mlknz** [comment]
As I understand the reason of different behavior: orthographic projection produces linear depth, while perspective projection doesn't. It is probably better fixed in renderDepth pass rather than in SSAO pass. [This commit from other engine](https://bitbucket.org/Unity-Technologies/cinematic-image-effects/commits/ceaa12a) and [packing](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/packing.glsl) ShaderChunk could be useful.

**Comment by ctechdevelopment** [comment]
Thanks @mlknz - great references ... I'll spend sometime this weekend look at this.

**Comment by Mugen87** [comment]
Should be solved via #15243
