### ISSUE TITLE
Ability to send a THREE.InstancedBufferAttribute as mat4 to the shader

### ISSUE THREAD

**Issue by hector-del-rio** [mrdoob/three.js#9916]
##### Description of the problem 

When trying to create a THREE.InstancedBufferGeometry with a THREE.InstancedBufferAttribute, the data cannot be read as mat4 from the shader. More info in [this SO question](http://stackoverflow.com/questions/40100640/three-js-read-a-three-instancedbufferattribute-of-type-mat4-from-the-shader)

##### Three.js version

- [x] Dev
- [x] r81

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by pailhead** [comment]
http://stackoverflow.com/questions/38853096/webgl-how-to-bind-values-to-a-mat4-attribute

**Comment by hector-del-rio** [comment]
so... is there a way to do this in three.js?

**Comment by pailhead** [comment]
There is a way to do this with webgl as demonstrated on stack overflow it seems. However, it seems that there is no high level way to set this up with three.js by just using "m4" instead of 4 x "v4".  Ie. it can't figure out that a "m4" attribute needs to run all that webgl code. 

You can certainly get the GL context from three.WebGLRenderer and do this yourself though.

**Comment by buchanae** [comment]
Can we reopen this then? Having an way to do this via THREE.js seems reasonable, and since there's a thick layer of THREE.js code between my app and webgl, I'm really not sure how to start working around this.
