### ISSUE TITLE
Plans around AnimationMixer and GLTFAnimation?

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#9922]
##### Description of the problem

Hi — just wondering what the target is for glTF animation, and whether that should (or even can) use the new THREE.AnimationMixer code. If there's work required there, would PRs for THREE.AnimationMixer be wanted, or GLTFLoader.Animations, or are they just incompatible?

**Comment by xirvr** [comment]
I have been using @tparisi's animation system in the original glTF loader, added a couple things like playTo, playFrom, etc, and shipped a thing with it this week.

* Heavily used Cinema4D exported to DAE (just quads with materials, it's a 2D project)
* Run through both the command line and Cesium converter (latter for designer testing)
*  Wrote a minimal sprite animator shader working in conjunction with those animated glTFs
* Have 5-10 glTF objects per scene (with overly expensive bounced keyframe animations), with multiple scenes switching back and forth (only rendering the active scene, though).
* Multiple other non-glTF ThreeJS sprites as well (because of a blending issue), and a particle system in these individual ThreeJS scenes

... and it all runs surprisingly solid.  So given we have a setup I trust :)  Could we pick apart the old glTF Animator and put it under a wrapper for the new Animation API?  @donmccurdy would this be possibly taking what you were doing for A-Frame, putting part of it in Three, and implementing the A-Frame specifics in the A-Frame component?

... or does this require [more expertise](http://i0.kym-cdn.com/photos/images/facebook/000/234/739/fa5.jpg) than that?

**Comment by tparisi** [comment]
Yes yes please by all means feel free to gut the old animation code and make it work the new way. I'm not married to it.

**Comment by richtr** [comment]
This sounds awesome @xirvr.

Ideally we would be providing `AnimationClip` objects back from parsed glTF and we should try to deprecate the `GLTFLoader.Animations` object if possible and use `AnimationMixer` instead.

The interpolation algorithm in `GLTFLoader.Animations` is effectively unchanged from @tparisi's version so the changes you have should also be applicable to the new glTF Loader.

I don't have any immediate plans to tackle this but overall I think this is heading in a great direction.

**Comment by donmccurdy** [comment]
Thanks all! I've started working on this, and so far the change to providing `AnimationClip` objects seems good. I'll send a PR when I have a few more things ironed out.

**Comment by donmccurdy** [comment]
Merged #10276.
