### ISSUE TITLE
Failed to load because no supported source was found.

### ISSUE THREAD

**Issue by cozcinar** [mrdoob/three.js#9942]
(**\* This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)
##### Description of the problem

Hello,

examples/webvr_video.html

I received 

> Uncaught (in promise) DOMException: Failed to load because no supported source was found.

error. It seams something needs to be changed in the new version of chrome. Any idea? 
Thanks
##### Three.js version
- [ ] Dev
- [ ] r82
- [ ] ...
##### Browser
- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [] All of them
- [ ] Windows
- [x ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Hmm... No idea...

**Comment by MichaelHazani** [comment]
Hi @cozcinar,

WebVR is [not yet implemented in Chrome](https://iswebvrready.org/). I'm able to run the example in FireFox Nightly (and presumably Chromium as well, since it's supported), which is one of the browsers that do support it. See more [here](https://webvr.info/).
![screen shot 2016-11-08 at 15 29 26](https://cloud.githubusercontent.com/assets/10997806/20121864/ade2e66e-a5c8-11e6-94d2-97e1ebb81a88.png)
