### ISSUE TITLE
MeshStandardMaterial mipmap sampling problem with envmap

### ISSUE THREAD

**Issue by Reider** [mrdoob/three.js#9956]
##### Description of the problem

MeshStandardMaterial when adding an envmap with linear mipmap sampling (default values) appears to behave like if nearest sampling was set. Black parts are rigid.

`sphereMaterial = new THREE.MeshStandardMaterial( { envMap: textureCube } );
sphereMaterial.metalness = 1;
sphereMaterial.roughness = 0;
`

![snap101](https://cloud.githubusercontent.com/assets/308075/19778020/2776d2f8-9c7b-11e6-99d7-5961ad3775c8.jpg)

When using MeshBasicMaterial the black parts are smooth.
`
sphereMaterial = new THREE.MeshBasicMaterial( { envMap: textureCube } );
`

![snap100](https://cloud.githubusercontent.com/assets/308075/19777990/05da8356-9c7b-11e6-869f-3b59e7296d50.jpg)

When viewing in Chrome and turning on the extension "WebGL Inspector" the problem strangely goes away.

![snap102](https://cloud.githubusercontent.com/assets/308075/19778280/4fdfe2a6-9c7c-11e6-9043-f94e49ba8ca9.jpg)
##### Three.js version
- [x] Dev
- [x] r81
##### Browser
- [x] Chrome
- [x] Firefox
- [x] Opera
##### OS
- [x] Windows
- [x] OS X 

Sample code:
https://drive.google.com/file/d/0B_ATy2nyBnzcQ21kUGlyRGFoc3c/view?usp=sharing

**Comment by bhouston** [comment]
> When viewing in Chrome and turning on the extension "WebGL Inspector" the problem strangely goes away.

WebGL Inspector disables most extensiosn to WebGL, not sure why.  But the extension causing the difference is likely: https://www.khronos.org/registry/webgl/extensions/EXT_shader_texture_lod/

It is because we set the LOD of the cube texture explicitly in standard material in order to simulate roughness.  0 is maximum sharpness.  When this extension isn't present I believe we do not override the LOD of the cube texture, thus it gets the default level.

By overriding the LOD of the cube texture we override the mipmap selection of LOD level.  This is the trade off we have to take if we want to use basic cube textures for representing roughness. 

The solution we take with Clara.io is to use the PMREM generator as demonstrated in this example: https://threejs.org/examples/#webgl_materials_envmaps_hdr
